### PR TITLE
🐛 Enable `0.x` with negative margins @ v4

### PR DESCRIPTION
**Pull request by k-utsumi**
I set it as below, but no negative margin was added.
`$spacers: (0\.5: ($spacer * .125));`

After investigating, it seems that `0 \ .5` is also evaluated as 0.
So I changed it to string comparison.

HTML example: ``

### CODE REVIEW

**Comment by mdo** [comment]
Is this needed in `main` for v5 as well?

**Comment by k-utsumi** [comment]
Maybe not.
I think v5 doesn't use this mixin.

**Review by mdo — APPROVED** [review]
I'm good with this. Any objections @twbs/css-review?

**Review by ffoodd — APPROVED** [review]
LGTM, never thought about such values 👌

**Pull request merged**
