### PR TITLE
Align floating labels with form-select sizes

### LINKED ISSUE #41008: Alignment issue with floating labels and small select (form-select-sm) padding in Bootstrap 5.3
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I have encountered an alignment issue when using Bootstrap 5.3’s floating labels with the small select element (form-select-sm). The selected value is misaligned, appearing further to the left than the floating label due to the reduced padding applied to the small select.

Steps to reproduce:

	1.	Create a form with a floating label using the form-floating class.
	2.	Include a select element with the class form-select-sm.
	3.	Observe that the selected value does not align with the floating label.

Expected behavior:
The selected value should align correctly with the floating label, regardless of the select size.

Actual behavior:
The selected value is offset to the left, causing misalignment with the label.

For a reduced test case demonstrating this issue, please refer to my CodePen link: [[VIew on Code Pen].](https://codepen.io/patrickzzz/pen/GRVXjLK)

### Reduced test cases

https://codepen.io/patrickzzz/pen/GRVXjLK

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.3 (latest)

### PR DESCRIPTION
**Pull request by patrickzzz**
### Description

This pull request addresses an alignment issue with Bootstrap’s floating labels when using the small `form-select-sm` element. The problem occurs because the selected value is misaligned with the floating label due to reduced padding applied to the small select. By adjusting the `padding-left` property to match the floating label's padding, this PR ensures the selected value aligns properly with the label.

### Motivation & Context

The change is required to fix the visual misalignment of the `form-select-sm` element when used with floating labels, as reported in [GitHub Issue #41008](https://github.com/twbs/bootstrap/issues/41008). This fix ensures a consistent and visually correct layout for the small select element when used with floating labels.

### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [X] All new and existing tests passed

#### Live previews

You can see the changes in the live preview, when adding the form-select-sm class:

- [<https://deploy-preview-41013--twbs-bootstrap.netlify.app/docs/5.3/forms/floating-labels/#selects>](https://deploy-preview-41013--twbs-bootstrap.netlify.app/docs/5.3/forms/floating-labels/#selects)

### Related issues

- Closes [#41008](https://github.com/twbs/bootstrap/issues/41008)

### CODE REVIEW

**Review by abay-2002 — COMMENTED** [review]
I understand the intention behind this change to address the padding misalignment for form-select-sm with floating labels, but I’d like to see whether this adjustment breaks any other components, particularly for larger select boxes or other form controls. It could be useful to test this across various form elements and screen sizes to ensure consistent behavior. If this padding tweak resolves the issue without side effects, it seems like a good solution to align the selected value with the floating label.

**Comment by coliff** [comment]
Great PR. I just tested this in a StackBlitz with the CSS generated from the deploy preview.

https://stackblitz.com/edit/bzr9zn?file=index.html

Separate issue I spotted though is that text is cropped on the Large variant (see the 'p' in the word 'Open')

**Comment by patrickzzz** [comment]
Hi @abay-2002  and @coliff, thanks for your feedback!

Yes, I have also observed the behavior with form-select-lg. 

This PR includes an adjustment to the padding-left for both form-select-sm and form-select-lg, aiming to improve alignment for selected values across sizes.

As for the cropped text in form-select-lg, I also see this as a separate issue, as it may require a different approach.

Thanks again for your insights!

**Review by louismaximepiton — CHANGES_REQUESTED** [review]
I'm fine with the actual changes.

Just requesting changes for https://deploy-preview-41013--twbs-bootstrap.netlify.app/docs/5.3/forms/floating-labels/#selects text to update and remove the mention of size since it works now thanks to you.

> It could be useful to test this across various form elements and screen sizes to ensure consistent behavior.

It looks like a quite located change since it's managed by `.form-floating > *` rule.

> As for the cropped text in form-select-lg, I also see this as a separate issue, as it may require a different approach.

It may be related to #39483 indeed.

**Comment by patrickzzz** [comment]
Hi @louismaximepiton,

the documentation at this point refers to the select's size attribute, which is still not supported (https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/size). So this text has to stay!

Otherwise i agree!

Regards,
Patrick

**Review by louismaximepiton — APPROVED** [review]
Nvm, you're right, I missed that 🤐 
The PR looks good, thanks again for the contribution!

**Review by julien-deramond — APPROVED** [review]
Thanks for the PR @patrickzzz and all for the team effort to review it!
LGTM! Also think that the cropped text issue on the large variant can be tackled in another PR and/or is a different issue.
Let's do it step by step :)

Just added a test case in `js/tests/visual/floating-label.html` based on https://stackblitz.com/edit/bzr9zn?file=index.html. I'll add Christian to the co-authored for that too.

**Comment by theodorejb** [comment]
@julien-deramond The cropped text issue would indeed be fixed by #39483. I'm still hoping it can be merged and included in the next patch release. I just rebased it again to fix the merge conflict following this PR.

**Comment by julien-deramond** [comment]
Thank you, @theodorejb, I'll try to find time to review it soon.

**Pull request merged**
