### PR TITLE
Docs for collapse should demo accordion-like groups

### LINKED ISSUE #33345: Docs for the collapse component do not include example for data-bs-parent
The [v5 docs for the collapse component](https://getbootstrap.com/docs/5.0/components/collapse/#via-data-attributes) state:

> To add accordion-like group management to a collapsible area, add the data attribute data-bs-parent="#selector". Refer to the demo to see this in action.

However, the example on that page does not show how to use the `data-bs-parent` attribute.

The [example from the v4 docs](https://getbootstrap.com/docs/4.6/components/collapse/#accordion-example) shows how to use the `data-parent` attribute to get accordion-like group management.

The `data-bs-parent` attribute works in v5, but I had to parse the docs for v4 in order to figure out how to use it.

I'm doing accordion-like group management, but not wanting the accordion markup, so using collapse with the `data-bs-parent` attribute works perfectly for me.

This appears to be a regression arising from moving the accordion to a separate section in the docs. Ideally, I think the v5 docs for the collapse component should have an example showing the use of the `data-bs-parent` attribute and the v5 docs for the accordion component should describe the `data-bs-parent` attribute as critical for accordion behavior.

See also #33214.

### PR DESCRIPTION
**Pull request by danielkauffman**
Fixes #33345

Preview: https://deploy-preview-33348--twbs-bootstrap.netlify.app/docs/5.0/components/collapse/#accordion-like-group-management

### CODE REVIEW

**Review by mdo — APPROVED** [review]

**Comment by ffoodd** [comment]
I seriously doubt about this pattern's accessibility, and as such don't think it should be added. Thoughts, @patrickhlauke?

**Review by patrickhlauke — CHANGES_REQUESTED** [review]
I found this example visually confusing, with the button for the currently active panel disappearing.

Further, as the button disappears, keyboard focus is lost when the button is yanked away - while some browsers error-correct for this, in the worst case focus is completely lost and reset to the start of the page.

In all, not a fan of this. Too confusing and currently inaccessible.

**Comment by danielkauffman** [comment]
@ffoodd @patrickhlauke I use this pattern when a user action should change the page state. For example, during a checkout process, user actions can (and should) change what is shown during the next step. This pattern also makes it easy to return to a previous step.

I find the pattern most helpful during a process. However, in trying to make the example as generic as possible, I omitted that context, and without that context, I understand your concern, because panels suggest that content is parallel, not sequential. Rewriting the example to show sequential steps instead of parallel panels makes this more clear, with the caveat that the example becomes more opinionated and less generic. That said, showing sequential steps would probably be an improvement.

Also, in the case of focus being lost, Chrome and Firefox handle the loss of focus reasonably well. Do you know whether or not the scenario of focus being reset to the start of the page actually occurs in any of the browsers supported by v5?

**Comment by patrickhlauke** [comment]
> Also, in the case of focus being lost, Chrome and Firefox handle the loss of focus reasonably well. Do you know whether or not the scenario of focus being reset to the start of the page actually occurs in any of the browsers supported by v5?

Chrome + JAWS bypasses Chrome's error correction, just as one example. Do not rely on focus error correction, it needs to be explicitly handled.

**Comment by danielkauffman** [comment]
> Do not rely on focus error correction, it needs to be explicitly handled.

This sounds like a distinct issue: "some components should be able to explicitly set focus".

For example, it looks like the same issue occurs when toggling between modals, see https://getbootstrap.com/docs/5.0/components/modal/#toggle-between-modals

I could imagine an attribute `data-bs-autofocus` that grabs focus when an ancestor is shown. More precisely, when any element is shown (including when the document is first shown), the first child having `data-bs-autofocus` would be given focus. This would also allow modals to set focus on the user name for a sign in form, or on the close button. Or in the example I'm describing, it would be easy to focus on the next step in the process.

**Comment by patrickhlauke** [comment]
> This sounds like a distinct issue: "some components should be able to explicitly set focus".
>
> For example, it looks like the same issue occurs when toggling between modals, see https://getbootstrap.com/docs/5.0/components/modal/#toggle-between-modals

focus *is* programmatically handled and sent to the newly shown `<div>` which has a `tabindex="-1"` to be able to receive programmatic `focus()`

**Comment by mdo** [comment]
Think we can close this one out as stale and possibly too confusing to include in the docs. I'm into adding more docs examples whenever possible, but per other feedback, closing out.

**Pull request closed without merging**
