### PR TITLE
Fix scrollspy and accented anchor links

### PR DESCRIPTION
**Pull request by alemendoza-v**
### Description

The `js/src/scrollspy.js` file was changed. I used the `decodeURI()` method to allow french words as ids. This method  was added to the line that finds the `observable sections` and the one that sets the `target links`.

### Motivation & Context

French words were not allowed as ids for the `Scrollspy` component.

### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

- <https://deploy-preview-38502--twbs-bootstrap.netlify.app/>

### Related issues

N/A

### CODE REVIEW

**Comment by mdo** [comment]
@GeoSot @XhmikosR Can you review for v5.3.0 stable?

**Comment by GeoSot** [comment]
@alemendoza-v  can you please provide a codepen, showing the existing problem?
I tried a simple approach but couldn't get the difference 
image

**Comment by alemendoza-v** [comment]
> @alemendoza-v can you please provide a codepen, showing the existing problem? 
@GeoSot Sure, here is the CodePen, the error shows up on the console, it does scroll but with this fix, the error does not show up on the console. https://codepen.io/alemendoza-v/pen/JjmyrJq

**Comment by alemendoza-v** [comment]
> @alemendoza-v can you please provide a codepen, showing the existing problem?

@GeoSot Hello, sure. If you comment out the parts that include the link to the french word the nav bar items will change to active, while when it is not commented out it will not.

https://codepen.io/alemendoza-v/pen/JjmyrJq

**Review by GeoSot — APPROVED** [review]

**Comment by GeoSot** [comment]
Thanks a lot @alemendoza-v

**Comment by alemendoza-v** [comment]
@GeoSot No problem!

**Pull request merged**
