### PR TITLE
Fix issue #15601 — Position of Charset, X-UA-Compatible, and Viewport Meta Tags

### LINKED ISSUE #15601: Position of X-UA-Compatible <meta> tag should be mentioned in the "Browser and device support" doc
Recently I had some issues with the IE compatibility mode. The X-UA-Compatible meta tag was present in the head section of my page. Nevertheless, in IE 8 the compatibility mode button was still visible in the browser status bar.
The solution was to include the meta tag as the first entry of the head section.

### PR DESCRIPTION
**Pull request by kkirsche**
Fixes #15601
Add comment about the position of X-UA-Compatible, charset and viewport

### CODE REVIEW

**Comment by cvrebert** [comment]
This need to be copied into all the example HTML files too: https://github.com/twbs/bootstrap/tree/master/docs/examples

**Comment by kkirsche** [comment]
Fixed @cvrebert in commit f92395 and I made sure to have it correctly say 2 for the non-responsive

**Comment by cvrebert** [comment]
:+1:

**Comment by XhmikosR** [comment]
@kkirsche: can you squash those 2 patches?

**Comment by kkirsche** [comment]
Squashed @XhmikosR — only took me 3 or 4 pull requests to finally get squashing process right.

The key is that I've only seen in the comments that I had to use `git rebase -i` but not what to do after that as a normal push fails because the branch already had stuff on it. For that reason I had to do a force push to get it to work. Not an issue just worth noting as it may reduce issues when getting some people who are less familiar with squashing commits through with less trouble :+1:

**Comment by kkirsche** [comment]
Also can you guys for a re-test. It didn't fail cause of my code but because:

```
Loading "autoprefixer.js" tasks...ERROR
>> Error: Cannot find module 'escape-string-regexp'
Loading "compress.js" tasks...ERROR
>> Error: Cannot find module 'escape-string-regexp'
Loading "concat.js" tasks...ERROR
>> Error: Cannot find module 'escape-string-regexp'
Loading "copy.js" tasks...ERROR
>> Error: Cannot find module 'escape-string-regexp'
Loading "cssmin.js" tasks...ERROR
>> Error: Cannot find module 'escape-string-regexp'
Loading "jade.js" tasks...ERROR
>> Error: Cannot find module 'escape-string-regexp'
Loading "less.js" tasks...ERROR
>> Error: Cannot find module 'escape-string-regexp'
Loading "uglify.js" tasks...ERROR
>> Error: Cannot find module 'escape-string-regexp'
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'escape-string-regexp'
```

**Comment by mdo** [comment]
Triggered another rebuild.

**Comment by philwareham** [comment]
Quick question, why *must* the viewport meta tag appear in stated position - I thought it could go anywhere within the head section?

**Comment by kkirsche** [comment]
@cvrebert this I believe would need to be added to twbs/bootstrap#15624 but I could be wrong :+1: 

@philwareham I'm under the understanding, though I could be wrong, that it's for support of older (age) browsers / devices which will ignore it if it appears later. I don't have anything to back that statement up though.

**Comment by cvrebert** [comment]
@XhmikosR Please add the ship list entry.

**Comment by XhmikosR** [comment]
I don't find it important enough to mention it.

**Comment by juthilo** [comment]
Doesn't everything apart from grunt runs and dependency updates usually go on the ship list, especially given that it's no longer added to the blog post?

**Pull request merged**
