### PR TITLE
Replace uglify-js with terser.

### PR DESCRIPTION
**Pull request by XhmikosR**
Opening this to check the diff and investigate the switch.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@Johann-S: your thoughts? Not sure about this personally. I mean, to me, the most stable is closure, but it requires more work to configure it and it's a lot slower, although the latter let's say we ignore it.

On the other hand, I don't see any fixes in uglify for months and the latest version has known issues.

**Review by Johann-S — APPROVED** [review]
The diff LGTM 👍

**Comment by XhmikosR** [comment]
I'm still a little scared to make the switch yet...

**Comment by Johann-S** [comment]
personnally I want this in v5.

BTW Angular switch to Terser in their v7 and Terser did a lot of things so I think now it should works better

**Comment by XhmikosR** [comment]
Ok, let's merge it and see how it goes. Compared to an unmaintained package with known bugs, this *should* be better.

**Pull request merged**
