### PR TITLE
Avoid using $.offset() on SVGs since it gives incorrect results in jQuery 3

### LINKED ISSUE #20280: Unit test for tooltip on SVG element fails in Chrome+Safari under jQuery 3
Specifically, https://github.com/twbs/bootstrap/blob/1956146787d686f5771ae51f7b96f3a3ad62ce09/js/tests/unit/tooltip.js#L1042 fails.

Refs #16834.

### PR DESCRIPTION
**Pull request by cvrebert**
Fixes #20280.
Refs https://github.com/jquery/jquery/issues/3137
CC: @XhmikosR @hnrch02 @patrickhlauke

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 6b1e2bc5941f567ab1c4fe53add3a6d0bdfe1c43
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/145303749
Docs preview: http://preview.twbsapps.com/c/${commitSha.sha}

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
The Savage failure is Safari-specific, seemingly unrelated, and probably transient: https://saucelabs.com/jobs/c8bda0f8f4db468491e30a985319aabc
Will retry shortly.

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: c4d1cdd8f2b9aa92cbd0f02976215be7dbb5f9ef
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/145305276
Docs preview: http://preview.twbsapps.com/c/${commitSha.sha}

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by hnrch02** [comment]
So for SVGs the position is now determined based on `getBoundingClientRect` alone, right? Does that mean tooltips are now be properly positioned when used in SVGs? I remember reading an issue about that problem some time ago.

**Comment by XhmikosR** [comment]
LGTM as far as I can tell.

**Comment by cvrebert** [comment]
For extra assurance, I upgraded to jQuery 3 in an experimental commit (b9ac9e5078d696e2a33c65f41492cf10ef317866) and the Sauce tests still passed on all browsers:
https://travis-ci.org/twbs/bootstrap/jobs/146142422

**Comment by hnrch02** [comment]
LGTM then.

**Pull request merged**
