### PR TITLE
Fix 22616 - Modal close button without title is left aligned

### PR DESCRIPTION
**Pull request by shankara-subramani**
Fixed Issue: https://github.com/twbs/bootstrap/issues/22616

Solution:  Added `margin-left:auto` to `button.close` in `_close.scss`

PS: This is my first PR here. So let me know if I did anything wrong. Thanks!

### CODE REVIEW

**Comment by Johann-S** [comment]
I don't know what you did but you make the same commit twice, and you run `dist` task.

As it mentionned here you shouldn't edit those files : https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#pull-requests

Please discard those changes and keep the modification you added

**Comment by shankariyerr** [comment]
Ah, I did run `dist`. Ok, I'll do it as you directed.

**Comment by shankariyerr** [comment]
@Johann-S I think I finally did it. Sorry and thanks.

**Comment by mdo** [comment]
Properly scoped fix coming in #22855.

**Pull request closed without merging**
