### PR TITLE
Feature/offside canvas unobtrusive

### PR DESCRIPTION
**Pull request by hidegh**
**Off-side menu** (slide/push - in) from left-or right or **sliding panels** like in facebook app on mobile (with almost the same JS code)...
**Download:** https://github.com/hidegh/bootstrap/tree/feature/offside-canvas-unobtrusive and start ../tests/offside/offside-test.html **example** to see how it works.

### CODE REVIEW

**Comment by mdo** [comment]
We already have an offcanvas menu in our examples. We won't be implementing anything for it in v3, but might in or after v4 releases. Thanks though!

**Comment by hidegh** [comment]
If you check out example, you'll see **it's more than a simple sidebar panel**.
It has multi page navigation (like facebook - CSS configured for 1 to 5 panels) or sliding panels like yours or more like: http://mobify.github.io/pikabu/

When I needed a sliding panel, I saw only this example: http://getbootstrap.com/examples/offcanvas/# + haven't seen offcanvas.js inside the current bootstrap JS folder...

**Comment by mdo** [comment]
We never implemented it as a full plugin or feature, so it remains an example only.

**Comment by timnicholson** [comment]
I would love to see full support for an off-canvas menu like this added to Bootstrap as well. They are quickly becoming the standard for mobile apps and would work great for modern sites with large header images so as to not obstruct the image with the full navbar.

**Comment by hidegh** [comment]
@timnicholson I'm glad you like'd it. It was fun to create, hope it'll be soon a part. More +1's from people like you and maybe it get's there. Until then feel free to use the committed JS, CSS and HTML.

**Comment by mdo** [comment]
@timnicholson @hidegh They're also ripe for abuse where folks cram as much as they can into the drawer without much consideration for the experience users have with them. It's a toss-up for me either way, but be aware it's not a perfect solution. I'm unsure if this will ever make it to v4 either right now—have a lot of other things to tackle first there.

**Pull request closed without merging**
