### PR TITLE
progress: Fix IE overflow

### LINKED ISSUE #29622: Progress bar: 0% text showing in IE
When writing a stacked progress bar like so:

```html
<div class="progress">
  <div class="progress-bar" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">0%</div>
  <div class="progress-bar bg-success" role="progressbar" style="width: 30%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100">30%</div>
  <div class="progress-bar bg-info" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">20%</div>
</div>
```

the "0%" text is shown on the left-hand side even though the bar itself is not displayed. This is happening in IE11 on Windows 10. In other browsers (Chrome, Firefox, Edge), the "0%" is not visible. I'm using Bootstrap v4.3.1.

[Minimal JSFiddle](https://jsfiddle.net/j0nfor3v/) using a slightly modified version of [Bootstrap's own stacked progress bar example](https://getbootstrap.com/docs/4.3/components/progress/#multiple-bars)

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Fixes https://github.com/twbs/bootstrap/issues/29622

Demo https://jsfiddle.net/84qo07hg/1/embedded/result,css,html,js

### CODE REVIEW

**Comment by XhmikosR** [comment]
Personally I cannot reproduce on the v4 docs nor on master docs with IE 11.

If you reproduced this on BrowserStack, please let me know.

**Comment by MartijnCuppens** [comment]
https://jsfiddle.net/j0nfor3v/ on IE via Browserstack:
image
Fix:
image

We don't have a `0%` width example in our docs.

**Comment by XhmikosR** [comment]
Can you make an updated fiddle with the fix?

**Comment by MartijnCuppens** [comment]
> Can you make an updated fiddle with the fix?

It's in the PR description: jsfiddle.net/84qo07hg/1/embedded/result,css,html,js

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
