### PR TITLE
Adding class to center caption on carousel

### LINKED ISSUE #29250: Carousel caption flex alignment
Hello,
I wanted to center the carousel caption vertically inside the carousel but I noticed the caption has an absolute position. 
Is it somehow possible to use flex with the carousel to align the caption?

Regards
Andi

### PR DESCRIPTION
**Pull request by mendozagioo**
Fixes #29250 
It adding a new class for center `carousel-caption`

### CODE REVIEW

**Review by MartijnCuppens — CHANGES_REQUESTED** [review]
Hi @mendozagioo,

This needs to be documented in our docs

**Comment by mendozagioo** [comment]
You're right @MartijnCuppens, here is the documentation

**Comment by XhmikosR** [comment]
This wrongfully targets the v4-dev branch.

**Comment by mendozagioo** [comment]
@XhmikosR what is the right branch?

**Comment by XhmikosR** [comment]
The default repository branch, master.

**Comment by mendozagioo** [comment]
Master branch is for v5, can’t you accept this PR for this branch, and after, merge it for v5 when will be able to deploy?

**Comment by XhmikosR** [comment]
Nope, everything goes into master first and then we cherry pick it if
needed. And in this case I don't know if this patch should be cherry picked
at all for v4.

**Comment by mendozagioo** [comment]
OK, let me create a new PR for master branch

**Pull request closed without merging**
