### PR TITLE
Modernize caret

### PR DESCRIPTION
**Pull request by inwardmovement**
https://github.com/twbs/bootstrap/issues/31069

### CODE REVIEW

**Comment by mdo** [comment]
Quick feedback:

- Don't commit `dist` files
- Don't change stylelint rules

Can you undo that and re-push?

**Comment by mdo** [comment]
Screen Shot 2020-06-18 at 10 43 08 AM

Also, this new caret is uneven—the right side sits higher than the left.

**Comment by inwardmovement** [comment]
I don't know how I can make this PR while complying with the stylelint rules, and cannot spend more time on this for now. It's just to give an idea for https://github.com/twbs/bootstrap/issues/31069. Maybe I should've just provide a preview, not make a PR...

**Comment by inwardmovement** [comment]
That's weird, it's even from my place:
image

**Comment by mdo** [comment]
Let's have you hold on it then for now and we can try to figure it out :). Thanks for submitting!

**Pull request closed without merging**
