### PR TITLE
Nested <dl> inside .dl-horizontal also becomes horizontal

### PR DESCRIPTION
**Pull request by preaction**
`<dd>` tags are allowed to have further `<dl>` inside of them, but if a `<dl class="dl-horizontal">` has a `<dl>` inside of it, the nested `<dl>` also shows up as horizontal, and with a misaligned first term as well.

Simply binding the `.dl-horizontal` class tightly to its child `dt` and `dd` fixes the problem.

http://jsfiddle.net/h58n2198/embedded/result/ demonstrates the problem

### CODE REVIEW

**Comment by cvrebert** [comment]
Seems like this might break backward compatibility..

**Comment by mdo** [comment]
It shouldn't in that the only allowable children of `<dl>` are `<dt>`s and `<dd>`s (as far as I know), but it would if folks were expecting the nesting. Could punt on doing this in v3 and tackle in v4 if it's an issue still though.

**Comment by cvrebert** [comment]
> It shouldn't in that the only allowable children of `<dl>` are `<dt>`s and `<dd>`s

@mdo OP is talking about a `dl` within a `dd` within a `<dl class="dl-horizontal">`, not a `dl` as a direct child of another `dl`. See the fiddle.

**Comment by preaction** [comment]
If they're doing what I'm doing, they'd have to fix it somehow, likely by extending the rule that's already there to try to move things back into place. And yeah, there'd likely be a compatibility break unless they completely overrode the rule (but probably can't rely on that).

I could instead add a note to the docs explaining the known issue and recommending a course of action. Though, I'm not sure what the remedy would be besides "copy this rule set, name the class something else, and use the child selector in place of descendant selector".

**Comment by mdo** [comment]
Yeah, doesn't seem worth it now. Thanks, but we'll pass and leave it as-is for v3.

**Comment by cvrebert** [comment]
Proposed a docs patch so that Bootstrap v4 will handle this case properly: #18788

**Pull request closed without merging**
