### PR TITLE
Set auto as default @page size

### PR DESCRIPTION
**Pull request by coorasse**
See:

* https://github.com/twbs/bootstrap/pull/25164
* https://github.com/twbs/bootstrap/issues/27888
* https://stackoverflow.com/questions/49785039/printing-bootstrap-4-html-page-in-chrome-cuts-off-chrome-header-footers/50400421

I think any option would be better than "a3"

### CODE REVIEW

**Review by MartijnCuppens — DISMISSED** [review]
I've changed the value to `null`, since this won't generate any additional css. Need an additional approval from @twbs/css-review to be sure.

**Comment by patrickhlauke** [comment]
does this cause any additional issues a la https://github.com/twbs/bootstrap/issues/26598, or does it solve them?

**Comment by MartijnCuppens** [comment]
I did some research about this and it seems browsers behave pretty inconsistent and there are a lot of factors we can not control:
- We never know what the size of the paper will be, so whenever we try to fix this for one paper size with fixed widths, it will break for other cases.
- Media queries seem to behave very buggy for print. I've used [this technique](https://codepen.io/MartijnCuppens/pen/jjBJyG) to determine the width of a page, but the results I got were pretty inaccurate:
  - IE/Edge: `648px`
  - Chrome/ New Edge: `540px`
  - Safari: The window width
  - Firefox: `793px`
- Safari seems to print the page with the width of the window, while chrome has a width around ~1260px (A4 paper size), for Firefox it's pretty hard to determine, since it scales all content whenever its wider than, I don't know what happens with Edge or IE, I gave up after FF.  
- Browsers rescale the page "when needed". This "when needed" is pretty opinionated by the browsers since every browser seems to do this in a different way.

I think we should just ditch the page size and `$print-body-min-width`. Yes, browsers will generate different print layouts, but that's better than the behaviour we have now where parts of the pages are cut of.

Maybe we should also mention the problems with print layouts in our docs.

**Comment by XhmikosR** [comment]
Just a reminder, we need to be extra careful with this since it's for v4. If we can't be 100% sure about any side effects, I say we leave it as is...

**Comment by patrickhlauke** [comment]
historically the print styles have been broken/problematic in many tiny aspects, so if this fixes at least some of the common situations even though it may not get to 100% perfection every time, it's probably an improvement though

**Comment by MartijnCuppens** [comment]
I agree with Patrick. https://github.com/twbs/bootstrap/pull/25164 broke more than it fixed I'm afraid. But this PR shouldn't be merged without removing (or `null`-ifying) the `$print-body-min-width` thing.

**Comment by MartijnCuppens** [comment]
@mdo, what do you think, should we remove the size and min-width or leave it as is?

**Comment by MartijnCuppens** [comment]
Ping @mdo

**Comment by XhmikosR** [comment]
Ping @mdo for a decision.

**Review by mdo — DISMISSED** [review]

**Comment by XhmikosR** [comment]
I'm still not sure about this change @mdo. It can and will introduce change in behavior. See the above comments https://github.com/twbs/bootstrap/pull/28753#issuecomment-504671905

**Comment by mdo** [comment]
Hmm, re-reading again, I could be convinced to not do this and just drop it entirely like we have in v5.

**Comment by MartijnCuppens** [comment]
Fine by me, close it than?

**Pull request closed without merging**
