### PR TITLE
Missing variable braces on $pagination-margin-start calc

### PR DESCRIPTION
**Pull request by alexbogias**

### CODE REVIEW

**Review by julien-deramond — CHANGES_REQUESTED** [review]
Thanks for this PR @alexbogias :)

The rendering seems to be broken when comparing [v5.2 Pagination](https://getbootstrap.com/docs/5.2/components/pagination/#overview) and [Pagination in this PR](https://deploy-preview-36501--twbs-bootstrap.netlify.app/docs/5.2/components/pagination/). There is an issue with the border radius probably coming from a missing modification here:

https://github.com/twbs/bootstrap/blob/5b0bf3f49a94ca96334651eca9aeeb56d48bf144/scss/_pagination.scss#L78

Could you please provide as well in the description a use case where the original code is not working? I'm probably missing something but I've done some basic tests with the original code without finding any issue.

**Comment by alexbogias** [comment]
Nope, it was just the PhpStorm that triggered the error and wanted to let you know...
image

**Comment by mdo** [comment]
I don't see any issue in our compiled code, so I'm inclined to leave this as-is. Will monitor if others run into issues though.

**Comment by Ahoba02** [comment]
After compiling the scss (version 5.2 beta), the generated css will display '$pagination-margin-start' and '$table-border-width'.

to solve the issues:
in _variables.scss

$pagination-margin-start:           calc($pagination-border-width * -1) !default;
should be
$pagination-margin-start:           calc(#{$pagination-border-width} * -1) !default;

in _tables.scss
border-top: calc(2 * $table-border-width) solid $table-group-separator-color;
should be
border-top: calc(2 * #{$table-border-width}) solid $table-group-separator-color;

**Pull request closed without merging**
