### PR TITLE
Update to Jekyll v3.0.0.

### LINKED ISSUE #18073: Update Jekyll to v3.0.0
I'll try to take care of this in the next days.

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #18073

~~We need to wait for jekyll-redirect-from to support Jekyll 3 first; https://github.com/jekyll/jekyll-redirect-from/issues/75, we need a new gem published~~

### CODE REVIEW

**Comment by XhmikosR** [comment]
OK, we get one error

```
Liquid error: undefined method `getConverterImpl’ for #<jekyll::site:0x00000003a51fd8></jekyll::site:0x00000003a51fd8>
```

Trying to figure it out.

**Comment by XhmikosR** [comment]
I think it's due to our callout.rb plugin.

**Comment by XhmikosR** [comment]
All right, I think everything should work now.

**Comment by cvrebert** [comment]
Tested it out locally; LGTM.
:ship:

**Comment by XhmikosR** [comment]
Should we backport this to 3.x too so that we don't have to switch Jekyll stuff around?

**Comment by cvrebert** [comment]
I can't find a reason not to backport it.

**Pull request merged**
