### PR TITLE
Fixed clipping of radios in webkit browsers

### PR DESCRIPTION
**Pull request by josephfusco**

### CODE REVIEW

**Comment by josephfusco** [comment]
[#16756](https://github.com/twbs/bootstrap/issues/16756)

**Comment by mdo** [comment]
Problem with this is every other instance of these inputs becomes off by one pixel. not sure I'm okay with making that trade-off.

**Comment by josephfusco** [comment]
@mdo Great point! This should do the job then.

**Comment by mdo** [comment]
Sorry, that's not what I meant—I was hasty in my reply. I mean that in every other browser, these inputs will be off by 1 pixel.

**Comment by josephfusco** [comment]
Exactly. But that is the only option we have. This is actually an [open chromium Issue](https://code.google.com/p/chromium/issues/detail?id=396726) for OSX. Until it is resolved, I think normalize.css should decide on how to go about it, or just wait till there is a fix, since this isn't exclusively a bootstrap issue.

**Comment by mdo** [comment]
Right on. I'd holler at Normalize and see if they want to address this then. I'm very hesitant to do anything to tweak subtle values in v3 given it's current state (we're only doing critical bug fixes) ahead of v4.

**Comment by josephfusco** [comment]
Sounds good thanks. [carried over to normalize.css](https://github.com/necolas/normalize.css/issues/462)

**Pull request closed without merging**
