### PR TITLE
add feature #26514

### PR DESCRIPTION
**Pull request by moogacs**
This PR is adding a modifier class to jumbotron `.jumbotron-full` that makes it height `100vh`.

### CODE REVIEW

**Comment by andresgalante** [comment]
This PR is adding a modifier class to jumbotron `.jumbotron-full` that makes it height `100vh`.

**Comment by moogacs** [comment]
hi @andresgalante  thanks for the replay, it make sense , true i would like to contribute  with you guys ,
what is the hottest issues need to be fixed, so I can contribute more with you under which label ?

**Comment by andresgalante** [comment]
Hi @moogacs great! 

There are many ways you can contribute. If you want to write CSS, look issues under `CSS`. If you want to help with JS there are `JS` issues.

If you like to write, you can read the docs and help improve them.

Also, you can help the community by helping people on the slack channel, replying to issues, or reviewing PRs.

If you are using Bootstrap for one of your projects you can fix things that you see broken or suggest features that you'd like to see.

Thanks!

**Comment by mdo** [comment]
Closing this out since the recommended fix here would be viewport sizing utilities instead of component-specific modifiers.

**Pull request closed without merging**
