### PR TITLE
Set -ms-overflow-style:scrollbar to workaround apparent IE11+Edge @viewport bug

### LINKED ISSUE #18543: Scrollbar overlaps content on desktop IE
This issue is still going on even in IE 11. 

The issue comes down to the following bootstrap.css rule:
@-ms-viewport {
  width: device-width;
}

The temporary solution is to override the rule in another css file:
@-ms-viewport{
    width:auto!important;
} 

It would be nice to see this issue taken into consideration in future releases.

Thank you.

### PR DESCRIPTION
**Pull request by cvrebert**
Closes #18543.
CC: @patrickhlauke @mdo

### CODE REVIEW

**Comment by patrickhlauke** [comment]
LGTM

**Comment by mdo** [comment]
So everyone in those browsers receives a visible scrollbar at all times?

**Comment by patrickhlauke** [comment]
Yes, as is the case with all other browsers on Windows. The alternative is that otherwise any content that's at the right 10px or so of the window can't be reached/activated when the scrollbar appears over it

**Comment by cvrebert** [comment]
Erm, my understanding is that it receives a visible scrollbar whenever the content overflows the window. If there's no overflow, there's not supposed to be a scrollbar of any kind.

**Comment by patrickhlauke** [comment]
> my understanding is that it receives a visible scrollbar whenever the content overflows the window

sorry, my fault for misunderstanding @mdo's question. as @cvrebert said, it still only shows a scrollbar when needed (when there's content overflowing the window size). what it does is force it to remain visible (and not auto-hide after a second or two of inactivity/no mouse movement). this also forces the scrollbar to take up space, rather than appearing on top of actual content on the edge

**Pull request merged**
