### PR TITLE
Enable floats to work with flex

### PR DESCRIPTION
**Pull request by pierreneter**

### CODE REVIEW

**Comment by andresgalante** [comment]
Hi @pierreneter thanks for the PR. 
I am sorry but I don't follow, can you please explain why we'd want to add an `order` to the float mixins?

**Comment by shtse8** [comment]
@andresgalante because flex only concern order, not float

**Comment by mdo** [comment]
Don't mix floats with flex—choose one method and stick with that.

**Comment by pierreneter** [comment]
@shtse8 set an `order` greater than 10 is a deliberate to custom css, oryou have more than 10 columns. So I think the value of 10 is reasonable. Or maybe, set it to `13`?

**Comment by pierreneter** [comment]
@mdo do you have any suggestions? The `floats` don't work with `flex` now. Create a new class like `flex-right`?

**Comment by pierreneter** [comment]
Oh, I see the relevance with #24915, I agreed with it. Thanks. Do not care about this PR (#24946) anymore.

**Pull request closed without merging**
