### PR TITLE
Create SECURITY.md

### LINKED ISSUE #28222: Question: How should security issues be reported
I cannot find any documentation on how to report security issues for this project.

Ideally, they should be reported in confidence to the maintainers. A direct message, however, seems inappropriate and could potentially get lost.

I'm honestly a bit surprised that GitHub doesn't have a mechanism that allows someone to create a security issue for a project that only the OP and maintainers can view.

Is there another service this project uses for reporting security issues that just isn't documented?

### PR DESCRIPTION
**Pull request by bardiharborow**
Using the email address from the CoC for the time being.

Fixes #28222

### CODE REVIEW

**Review by XhmikosR — CHANGES_REQUESTED** [review]
Needs an address we all get notified from.

**Comment by mdo** [comment]
@XhmikosR I can probably setup a new Gsuite account and have it forward to us all. Thoughts?

**Comment by XhmikosR** [comment]
@mdo: yup, something like that sounds perfect.

**Review by mdo — APPROVED** [review]
Alias has been setup.

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
