### PR TITLE
Fix Edge bounce and restore original transition easing

### LINKED ISSUE #27156: IE Edge Carousel slide animation bounces slightly on completion
Similar Issues:
#22291
#21751
#22392

Issue seems **not be be solved** with current version using Microsoft Edge 42.17134.1.0 and BS v4.1.3:
https://getbootstrap.com/docs/4.1/components/carousel/

microsoft edge 30 08 2018 19_20_52_1

### PR DESCRIPTION
**Pull request by MartijnCuppens**
https://github.com/twbs/bootstrap/pull/22392 didn't solve the bounce effect and changed the transition from `ease-in-out` to `ease`. This PR restores the original transition.

The bounce in #27156 is caused by the switch from `position: absolute` to `position: relative` which causes a repaint. This PR uses a float based technique which will only change the transform. 

I also removed `align-items: center;`, `.carousel-item` doesn't use flexbox.

Fixes #27156.

### CODE REVIEW

**Review by mdo — DISMISSED** [review]
Wonderful debugging <3.

**Comment by XhmikosR** [comment]
I see a little jump when the transition ends on Edge.

**Comment by MartijnCuppens** [comment]
I removed a lot of browser hacks to see how the browser handles the transitions now and it looks like we don't need these anymore. Removing the hacks also fixes the little jump @XhmikosR spotted in Edge. Sometimes there's still a small line between the images (probably caused by the fact that 2 transitions are going on at the same time), but I don't think that's something we can easily fix without breaking changes to the carousel.

I've tested the latest changes on native devices in:
- Chrome (macOS, Windows & Android)
- Firefox (macOS, Windows & Android)
- Edge (Windows)
- IE11 (Windows)
- IE10 (Emulated in IE11 & "native" via BrowserStack)

**Comment by XhmikosR** [comment]
Thanks, @MartijnCuppens for the follow-up!

I can't see any jumping with the latest patch on 42.17134.1.0/ EdgeHTML 17.17134.

I'm gonna test it a little more and if all is good merge it.

**Comment by XhmikosR** [comment]
@MartijnCuppens: do you have a patch for the Edge line this PR is introducing? I wonder how breaking it'll be.

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
