### PR TITLE
Fix npm.js to avoid polluting the global namespace

### PR DESCRIPTION
**Pull request by jesusprubio**
Hi, I've opened #15638 that I'm solving with this PR. I've also added a note to the README to show how to load the library without exporting/overwriting anything in the global namespace. Now we can require it in this way:

``` javascript
var jquery = require('jquery');
require('bootstrap')(jquery);

console.log('Is Bootstrap loaded?');
console.log((typeof jquery().emulateTransitionEnd === 'function'));
```

### CODE REVIEW

**Comment by ibc** [comment]
:+1:

**Comment by cvrebert** [comment]
This makes things less modular since you can't import individual Bootstrap jQuery plugins anymore, right?

**Comment by jesusprubio** [comment]
Yep, you're right. I think I could change it to support it if you're interested. :)

**Comment by cvrebert** [comment]
I don't know if this is worth bothering with. We're already going to address module systems in Bootstrap v4, and folks have made due with globals since Bootstrap v1, so this isn't a must-have.

**Comment by ibc** [comment]
The point of this commit is to make Bootstrap valid for widget. Imagine that, instead of building an entire website the aim is to create a widget (a single JS library build with browserify that includes all its dependencies, even the CSS and images converted into Base64).

The idea is to put such a library/widget into any existing website without getting into conflict with website JS libraries. If Bootstrap depends on `window` globals then conflict can easily happen (conflict with a different version of jQuery, etc).

The way in which the current PR works is as follows (assuming Node like development + browserify):

```
// Load *our* own version of jQuery (which does not expose $ nor jQuery into window)
// and store it into a local variable "jquery".
var jquery = require('jquery');

// Load bootstrap by giving it our jQuery module, so bootstrap appends its own
// stuff into the given jQuery module.
require('bootstrap')(jquery);


// Use it as usual:
jquery('#myWidget').show();

// etc
```

**Comment by cvrebert** [comment]
> The idea is to put such a library/widget into any existing website without getting into conflict

Bootstrap's CSS will still conflict, unless you're postprocessing it with extra tooling.
Anyway, nobody is saying JS module systems aren't useful. It's just debatable whether this stop-gap is worth it when we're already planning to properly fix it in v4 anyway.

**Comment by ibc** [comment]
> Bootstrap's CSS will still conflict, unless you're postprocessing it with extra tooling.

True.

> Anyway, nobody is saying JS module systems aren't useful. It's just debatable whether this stop-gap is worth it when we're already planning to properly fix it in v4 anyway.

Clear. Thanks a lot.

**Comment by jesusprubio** [comment]
After some testing and research now any library can be loaded individually. Due to Browserify nature the only way to achieve this (without including the whole code in the module) is having different NPM packages. All of them should be published to the NPM registry like the main one.

Thanks :)

**Comment by cvrebert** [comment]
I don't believe there's currently much appetite among the team for the additional overhead of publishing N different npm modules or adding so many extra files to the repo..

CC: @hnrch02 @XhmikosR for their opinions.

**Comment by hnrch02** [comment]
Strongly agreeing with @cvrebert here. :-1: for v3.

**Comment by XhmikosR** [comment]
Yeah, me too. Not only for v3 but even for the future.

**Comment by jesusprubio** [comment]
Just for the record, this isn't the recommended way to solve this. The better option is to make the module [UMD](https://github.com/umdjs/umd) compatible like in this issue:
https://github.com/FezVrasta/bootstrap-material-design/pull/467

**Comment by cvrebert** [comment]
Yeah, we briefly tried UMD, but IIRC it didn't work with script concatenation, so we had to back it out.
Like I said, we hope to have a better module system story in v4.

**Comment by jesusprubio** [comment]
BTW, we're using now this fork. It's the best way I found to achieve this doing minimal changes in your actual structure. 
https://github.com/eface2face/bootstrap/blob/master/dist/js/npm.js

It's enough for us until v4.

**Pull request closed without merging**
