### PR TITLE
Change copyright year to 2021

### PR DESCRIPTION
**Pull request by sophianyberg**

### CODE REVIEW

**Comment by rohit2sharma95** [comment]
HI, @sophianyberg 
It is better to create a single PR for the same change. Can you move all your changes in a single PR? :slightly_smiling_face:

**Comment by sophianyberg** [comment]
I cannot.

**Comment by rohit2sharma95** [comment]
You can merge your branches locally into a single branch and then close other PRs. And keep a single PR open for the branch in which you have all the changes. Hope it helps.

**Comment by sophianyberg** [comment]
Hello @rohit2sharma95 ,
I am on an iPad and I can not merge this pull request until you approve it. Can you please approve this and the other pull requested?
Thanks,
@sophianyberg

**Pull request closed without merging**
