### PR TITLE
Fix+example

### PR DESCRIPTION
**Pull request by louismaximepiton**
Header.js and index.html shouldn't be merged but this is for a working tooltip example.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Sorry, but what's the need for a new file?

**Comment by GeoSot** [comment]
> Sorry, but what's the need for a new file?

I suppose just for checking, but I was wondering the same.


@louismaximepiton before I try to dig in this solution, have you seen the two failing tests? Both fail to recognize empty string as false. (probably caused , because of the removal of boolean casting)

and both of `_isWithContent` now are resolved as it is. In case of a function (especially in the rare case it returns null), I guess it will fail again

**Comment by louismaximepiton** [comment]
Sorry, I was off for few days. Yeah, the new files are my working example, they shouldn't be merged at all, I'll remove them with the next update of the PR.

I'll have a look at these examples and try to fix them all this afternoon.

**Comment by GeoSot** [comment]
@louismaximepiton please, make a rebase (we merged #35679), or reopen on main branch. 

Many, many thanks in advance :smiley:

**Pull request closed without merging**
