### PR TITLE
Tweak temporal inputs

### LINKED ISSUE #16346: Height of plain <input type="week"> doesn't match height of other temporal <input>s in Chrome
As a side-effect of https://github.com/twbs/bootstrap/blob/6ba595f3fffee275922c377a7cc1bc46fc5e58c1/less/forms.less#L179 , the height of a plain `<input type="week">` without any Bootstrap classes doesn't match the height of other plain temporal `<input>`s.
Tested on OS X Chrome using http://jsfiddle.net/5Lh045wd/1/

### PR DESCRIPTION
**Pull request by mdo**
Fixes #16346.

Scopes the overrides for temporal inputs to our input classes rather than all inputs. Also accounts for `week` inputs.

/cc @cvrebert

### CODE REVIEW

**Comment by cvrebert** [comment]
`type="week"` was supposedly unnecessary as of the version of iOS when the bug was reported to us: https://github.com/twbs/bootstrap/pull/13099#issuecomment-37846568
Have you re-tested and gotten different results on the latest iOS?

**Comment by patrickhlauke** [comment]
iOS8.3 does not support datetime and week, FWIW

**Comment by mdo** [comment]
You're right, week doesn't even render as a text field as a fallback in iOS. I removed that at least and tied the remaining ones from our current version to the `.form-control` class. Should be enough now.

**Comment by cvrebert** [comment]
:smile:

**Pull request merged**
