### PR TITLE
Fix #19344 - Use a single class name for opened/expanded/shown state of widgets

### LINKED ISSUE #19344: Use a single class name for opened/expanded/shown state of widgets?
Refs https://github.com/twbs/bootstrap/issues/19254#issuecomment-185167402

* I don't know of any particular good reason why we currently use multiple different classes for this. Seems to just be an accident of history.
* Using a single name would make things more uniform in general
* Using a single name would make reimplementing Bootstrap's JS in $JS_FRAMEWORK_OF_THE_HOUR slightly easier

### PR DESCRIPTION
**Pull request by Johann-S**
Use only `.active` when a widget is opened/expanded/shown

TODO : 
- [x] Alert
- [x] Collapse
- [x] Dropdown
- [x] Modal
- [x] Popover
- [x] Tooltips
- [x] Documentation
- [x] Visual tests

~~PR in progress~~

Close : #19344

### CODE REVIEW

**Comment by mdo** [comment]
😻 

(Woof, we gotta fix Hound. I know we have to either rewrite those tests or do something else, but maybe there's a fix for Hound itself or another JS validator?)

**Comment by Johann-S** [comment]
I read a bit on HoundCi and I didn't found any option to lint differently JavaScript from ``js/tests/`` folder unless to ignore them with .eslintignore see : 
https://houndci.com/configuration#eslint
http://eslint.org/docs/user-guide/command-line-interface#ignoring-files-from-linting

About my PR, I have to change exemples in the documentation and visual tests

**Comment by Johann-S** [comment]
Everything is done @mdo 💪

**Comment by mdo** [comment]
This. Is. AWESOME. You're a champ!

**Comment by mdo** [comment]
One thing I didn't think about was the differences between `.open` and `.active` for selected nav links. If a dropdown link in a nav is active, it might not necessarily open as well. I might have to change that state to `.selected` or something similar.

**Pull request merged**
