### PR TITLE
Popover/Tooltip: streamline `config` property to start with underscore

### PR DESCRIPTION
**Pull request by GeoSot**

### CODE REVIEW

**Comment by rohit2sharma95** [comment]
Although, this is not really a protected property but its name was started with underscore (`_`), because it is a protected property used by a child class as well.

Nevertheless it is just a property (But you should keep the consistent naming convention IMO :slightly_smiling_face:)

**Comment by XhmikosR** [comment]
I assume these were the only places? The reason must be because these two components share common part.

**Comment by GeoSot** [comment]
I have searched the whole project. I didn't found it anywhere else

**Review by rohit2sharma95 — APPROVED** [review]

**Comment by tungphan995** [comment]
tim

**Pull request merged**
