### PR TITLE
`.form-control` input width by `size` attribute

### PR DESCRIPTION
**Pull request by WinterSilence**
Sandbox https://codepen.io/WinterSilence/pen/VwyeEmb

### CODE REVIEW

**Comment by mdo** [comment]
I think we'll skip this, but wouldn't mind @ffoodd's opinion.

**Comment by ffoodd** [comment]
I think it'll conflict with the grid at some point. I know `size` is meant for this, but is also less predictable than `width`- and a lot less than the grid.

Have a look at [MDN explanations for `size`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-size) which clearly states that:
- CSS takes precedence,
- `size` unit depends on `type`,
- it's not allowed for every inputs.

So I'll close this —also according to last comment, but as usual feel free to discuss further if you have any other arguments.

**Comment by WinterSilence** [comment]
@ffoodd
> CSS takes precedence

can you explain it?

> size unit depends on type

when it's can create any problems?

> it's not allowed for every inputs.

no matter, it's allowed to "text" inputs(`text`, `email` and etc.). or you want change width of checkboxes?

It already used indirectly in [auto sizing](https://getbootstrap.com/docs/5.1/forms/layout/#auto-sizing)

**Comment by ffoodd** [comment]
If any one uses CSS `width` on a form control (directly or through any helper or utility), `size` wouldn't apply.

`size="10"` won't set the same width depending on input type, so when defining a form layout containing several input types, it wouldn't be reliable for alignment. The grid is.

And finally `.form-control` can be applied to any type, so your suggestion may apply to any form control with the size attribute—even if the said input do not honor `size`—leading to an uncontained width input.

So yeah, that's a no-go IMO.

**Comment by WinterSilence** [comment]
@ffoodd 
> If any one uses CSS width on a form control (directly or through any helper or utility), size wouldn't apply.

i don't see any problems in this - user can customize inputs as he wish

> size="10" won't set the same width depending on input type, so when defining a form layout containing several input types, it wouldn't be reliable for alignment.

checbox/radio use `.form-check-input`, range not effect, date/time/datetime have fixed size. 
can you post example with there it's work not same?

**Comment by ffoodd** [comment]
This could lead to unexpected behaviour for some users, and Bootstrap used to recommend the grid for such layouts, which is way more predictable.

I don't see us providing support for this due to the changes it'd introduce, the inconsistencies it could lead to (probably generating new issues), and the fact that it's unneeded and don't provide any clear advantage over the grid.

**Pull request closed without merging**
