### PR TITLE
Use an `h5` for callouts

### PR DESCRIPTION
**Pull request by XhmikosR**
This is so that they are not included in ToC.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Now that I think about it... It doesn't make sense the header levels for some of the includes

**Comment by XhmikosR** [comment]
The thing is we can't know the level of the previous sibling item and thus use the same level in the callouts.

**Comment by XhmikosR** [comment]
So, perhaps we should just hide the callouts' headers consistently?

**Comment by patrickhlauke** [comment]
nobody dies if a heading level is skipped. unless we have a way to embed callouts at any level, and the callout auto-adapts the level to be subordinate of the last heading level it's at, it's safest to keep the heading level to something guaranteed to be subordinate in every situation...so let's leave it to `h5`, or heck could even go to `h6`. whether it's included in the TOC or not is up for debate.

**Comment by XhmikosR** [comment]
The reason for this PR wasn't the skipped level. Was to show the callout in the ToC. But after thinking about it, I believe it's better if we just hide all callouts instead from ToC.

**Review by patrickhlauke — COMMENTED** [review]
if we can guarantee that the callout is only ever included with a preceding `h3`, and not an `h4` or `h5`, then sure. but i think it's not a major problem even as is.

**Comment by patrickhlauke** [comment]
ah gotcha,hadn't seen your comment until now. yeah, i think it's fine even if the callouts AREN'T in the TOC

**Comment by XhmikosR** [comment]
All right, I'm gonna hide them by using an `h5`.

**Comment by XhmikosR** [comment]
Actually, it might be a bug in jekyll-toc. Waiting for confirmation/fix https://github.com/toshimaru/jekyll-toc/issues/70

**Comment by m5o** [comment]
@XhmikosR Consider review/cherry-pick https://github.com/twbs/bootstrap/pull/25838/commits/08b096d18a926efea484a3d469bbebaa6191278a from #25838 this should cover the whole list.

**Comment by XhmikosR** [comment]
Thanks but I want this fixed upstream.

**Comment by mdo** [comment]
FWIW, I don’t want callouts to be listed in the table of contents. Any of them that are there currently are there unintentionally.

**Comment by XhmikosR** [comment]
Yeah, I think I will just change them so that they don't show up for now. No idea when this will be fixed upstream.

**Review by MartijnCuppens — APPROVED** [review]

**Pull request merged**
