### PR TITLE
Compress images.

### PR DESCRIPTION
**Pull request by XhmikosR**
Don't merge this yet; one of the two patches should be committed.

Please try and see if anyone with retina sees any difference. Personally, I don't see any difference and the size decrease is very big, so I'd go with the 8-bit ones.

/CC @mdo @cvrebert 

```
Losslessly compress images.

Before: 1,28 MB (1.351.880 bytes)
After:  1,27 MB (1.341.411 bytes)

4631b22

----

Lossy compress the 2 new images.

Before: 538 KB (551.052 bytes)
After:  179 KB (183.296 bytes)

[ci skip]

7da2d3c
```

### CODE REVIEW

**Comment by mdo** [comment]
:shipit:

**Comment by XhmikosR** [comment]
So you had a look at the lossy ones?

**Comment by mdo** [comment]
They all seem fine to me.

**Comment by XhmikosR** [comment]
Cool I'll rebate and merge.

**Comment by mdo** [comment]
<3 thanks!

**Pull request merged**
