### PR TITLE
Button hover class

### PR DESCRIPTION
**Pull request by KaduAmaral**
Add button hover class, for use with another class, ie:

```
<button class="btn btn-default btn-success-hover">Success on hover</button>
```

### CODE REVIEW

**Comment by mdo** [comment]
I believe this has come up before and we've punted on it. I can't recall the issue, and there's not much of an argument for it here. At the very least since v3 is no longer seeing new features, we'll be punting as a won't implement here.

**Comment by jlbooker** [comment]
@mdo Any chance of adding this in v4?

**Comment by mdo** [comment]
For this exact thing, not likely honestly. For a generic `.hover` in addition to `:hover`, maybe.

**Comment by jlbooker** [comment]
@mdo, Rather than just a generic `.hover`, I was hoping for hover classes with contextual colors (primary, success, info, warning, danger).

You mentioned that there wasn't much argument here.. The reason I'm using these hover styles is that sometimes the button styles have too much visual weight for a page, particularly with `.btn .btn-danger`. On an interface with relatively few other stand-out colors, a `.btn-danger` really draws the user's eye. But, I don't always want to draw someone's eye immediately to a "Delete" button. Instead, adding the red color on-hover still allows that "danger" idea to be communicated at the last second, without drawing tons of attention to the button from the start.

For an example, see GitHub's 'SSH Keys' interface in your account settings. The button to delete an SSH key shows the behavior I'm after.

There was a reasonable looking pull request in #16776, but it was done in LESS. I'm not sure how difficult that would be to port to SASS, but if you're open to the idea I'd be happy to do the work and open a new PR.

**Comment by mdo** [comment]
Perhaps something like http://v4-alpha.getbootstrap.com/components/buttons/#outline-buttons would be a bit more helpful?

**Comment by KaduAmaral** [comment]
@mdo when I posted this request the v4 had not yet been presented. I liked the outline buttons. Any idea when will the official release?

**Comment by mdo** [comment]
Probably a couple months honestly. No rush on our part, still lots of iteration.

**Pull request closed without merging**
