### PR TITLE
Revisit our browserslist config

### LINKED ISSUE #29314: Review v5 browsers
Our current browserslist config includes support for opera mini, which we do not support. We need to exclude that somehow or review our current approach.

We also need to update our https://twbs-bootstrap.netlify.com/docs/4.3/getting-started/browsers-devices/ page.

### PR DESCRIPTION
**Pull request by XhmikosR**
Closes #29314.

I kept the Edge patch separate because ATM the update hasn't shipped on all supported Windows versions: <https://support.microsoft.com/en-us/help/4541302/the-new-microsoft-edge-is-available> (see also my last point)

`master` branch:

```
Browsers:
  Chrome for Android: 81
  Firefox for Android: 68
  And_qq: 10.4
  UC for Android: 12.12
  Android: 81
  Baidu: 7.12
  Chrome: 83, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60
  Edge: 83, 81, 80, 79, 18, 17
  Firefox: 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60
  iOS: 13.4, 13.3, 13.2, 13.0-13.1, 12.2-12.4, 12.0-12.1, 11.3-11.4, 11.0-11.2, 10.3, 10.0-10.2
  Kaios: 2.5
  Opera Mini: all
  Opera Mobile: 46
  Opera: 68
  Safari: 13.1, 13, 12.1, 12, 11.1, 11, 10.1, 10
  Samsung: 11.1

These browsers account for 92.74% of all users globally
```

This branch:

```
Browsers:
  Chrome for Android: 81
  Firefox for Android: 68
  And_qq: 10.4
  UC for Android: 12.12
  Android: 81
  Baidu: 7.12
  Chrome: 83, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60
  Edge: 83, 81
  Firefox: 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60
  iOS: 13.4, 13.3, 13.2, 13.0-13.1, 12.2-12.4, 12.0-12.1, 11.3-11.4, 11.0-11.2, 10.3, 10.0-10.2
  Kaios: 2.5
  Opera Mini: all
  Opera Mobile: 46
  Opera: 68, 67
  Safari: 13.1, 13, 12.1, 12, 11.1, 11, 10.1, 10
  Samsung: 11.1, 10.1

These browsers account for 91.88% of all users globally
```

This branch without the Edge patch:

```
C:\Users\xmr\Desktop\bootstrap>npx autoprefixer --info
Browsers:
  Chrome for Android: 81
  Firefox for Android: 68
  And_qq: 10.4
  UC for Android: 12.12
  Android: 81
  Baidu: 7.12
  Chrome: 83, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60
  Edge: 83, 81, 80, 79, 18, 17
  Firefox: 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60
  iOS: 13.4, 13.3, 13.2, 13.0-13.1, 12.2-12.4, 12.0-12.1, 11.3-11.4, 11.0-11.2, 10.3, 10.0-10.2
  Kaios: 2.5
  Opera Mini: all
  Opera Mobile: 46
  Opera: 68, 67
  Safari: 13.1, 13, 12.1, 12, 11.1, 11, 10.1, 10
  Samsung: 11.1, 10.1

These browsers account for 93.97% of all users globally
```

Notes:

1. Do note that dropping Opera Mini does not gain us anything, i.e. no prefix is removed/added.
2. We could drop the `defaults` change, but IMO we should change what we were using because `1 last version` isn't proper
3. I'd also argue about the Edge change, but I don't want to hold us back in v5 either. That being said, it does feel too soon to drop it, but depends to when we will actually ship v5.0.0 stable.

Preview: https://deploy-preview-30986--twbs-bootstrap.netlify.app/

EDIT: actually dropping Opera Mini should allow us to use `const`/`let`. I will experiment with that later.

### CODE REVIEW

**Comment by mdo** [comment]
Hmm, makes me think we could drop legacy Edge (17 and 18) given the difference there in those %s.

**Comment by mdo** [comment]
Is this okay to review and get merged @XhmikosR?

**Comment by XhmikosR** [comment]
I'm still not sure if it's the right time to drop Legacy Edge. The percentage, which might seem small, does not reflect the real number. I'm just thinking out loud here so that we make the right choice for our users and the project.

Also, I wanted to make another change, I'll do it later.

**Comment by ffoodd** [comment]
Despite the fact that I'd love to use logical properties for RTL, I'm not sure about dropping Legacy Edge.

The New Edge is only available for every Windows for a few weeks, isn't it?

**Comment by XhmikosR** [comment]
Yeah, it hasn't shipped to all supported Windows 10 versions yet AFAICT and I don't know where they track this.

Also, there might be more stuff we can remove if we go with the Edge removal and ideally I'd like all the related changes to be in the same PR (not this one).

**Comment by XhmikosR** [comment]
Also, do note that the Legacy Edge removal saves us a significant amount of bytes from the JS dist files. CSS doesn't save a lot.

**Comment by mdo** [comment]
Chatted with @XhmikosR about this in Slack and wanted to reiterate here. I'm in favor of dropping this knowing that it'll be a couple months to stable v5 and we're going to be working on this for at least a year, hopefully a little more. Having some foresight into what things will look like at that point is what I'm hoping to rally around. if that makes sense.

**Comment by mdo** [comment]
Also slating this for alpha 2 now to make sure we're all aligned on it :).

**Review by mdo — APPROVED** [review]
Let's also modify the Migration and Browsers & Devices pages to make sure we have the latest shown there.

**Comment by XhmikosR** [comment]
This isn't ready though due to #31153 which I need to report upstream in Babel.

**Comment by voltaek** [comment]
Are we planning to re-drop Legacy Edge (v17 and v18) now that Edge v18 usage is less than half that of IE 11 and Edge v17 usage is non-existent, according to [recent worldwide stats](https://gs.statcounter.com/browser-version-partially-combined-market-share#monthly-202004-202009)? It seems like the Windows Update to push out Chromium-based Edge has done well to replace Legacy Edge.

**Comment by coliff** [comment]
> Are we planning to re-drop Legacy Edge (v17 and v18) now that Edge v18 usage is less than half that of IE 11 and Edge v17 usage is non-existent, according to [recent worldwide stats](https://gs.statcounter.com/browser-version-partially-combined-market-share#monthly-202004-202009)? It seems like the Windows Update to push out Chromium-based Edge has done well to replace Legacy Edge.

I was wondering about this too. This page shows it a little clearer: https://caniuse.com/usage-table
Certainly looks like at the very least, Edge v17 can be dropped - but I suspect v18 will be >0.1% by the time Bootstrap v5 hits Beta.

**Comment by XhmikosR** [comment]
Yeah, we plan to actually drop Legacy Edge support since we are late anyway.

**Comment by XhmikosR** [comment]
So, here's the current situation:

* use browserslist defaults which is `> 0.2%, last 2 versions, Firefox ESR, not dead`
* remove Android since Android WebView is Chromium based
* drop Legacy Edge support; Microsoft will ship the new version to Windows >= 1803

```
C:\Users\xmr\Desktop\bootstrap>npx autoprefixer --info
Browsers:
  Chrome for Android: 84
  Firefox for Android: 79
  And_qq: 10.4
  UC for Android: 12.12
  Android: 81
  Baidu: 7.12
  Chrome: 85, 84, 83, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 49
  Edge: 84, 83
  Firefox: 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60
  iOS: 13.4-13.5, 13.3, 13.2, 13.0-13.1, 12.2-12.4, 12.0-12.1, 11.3-11.4, 11.0-11.2, 10.3, 10.0-10.2, 9.3
  Kaios: 2.5
  Opera Mini: all
  Opera Mobile: 46
  Opera: 70, 69
  Safari: 13.1, 13, 12.1, 12, 11.1, 11, 10.1, 10
  Samsung: 12.0, 11.1-11.2

These browsers account for 93.64% of all users globally
```

The only "issue" I see is iOS 9.3 being included, and some other browsers we might not care about.

I think if we switch to >= 0.25% and last 3 major versions it might be better?

```
Browsers:
  Chrome for Android: 84
  Firefox for Android: 79
  And_qq: 10.4
  UC for Android: 12.12
  Android: 81
  Baidu: 7.12
  Chrome: 85, 84, 83, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 49
  Edge: 84, 83, 81
  Firefox: 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60
  iOS: 13.4-13.5, 13.3, 13.2, 13.0-13.1, 12.2-12.4, 12.0-12.1, 11.3-11.4, 11.0-11.2, 10.3, 10.0-10.2
  Kaios: 2.5
  Opera Mini: all
  Opera Mobile: 46
  Opera: 70, 69, 68
  Safari: 13.1, 13, 12.1, 12, 11.1, 11, 10.1, 10
  Samsung: 12.0, 11.1-11.2, 10.1

These browsers account for 93.72% of all users globally
```

/CC @twbs/team

**Comment by XhmikosR** [comment]
Also, do note that with this patch as is the generated JS files use `const`/`let` and ES6+. Not sure if that's OK for the consumers of the dist files.

**Comment by mdo** [comment]
Let's roll with the second option I think @XhmikosR. We can drop iOS 9.3 IMO.

**Comment by XhmikosR** [comment]
I need to revisit this thoroughly because 1) iOS 10 tests fail and 2) I see `const`/`let` and more ES6 features in our dist files.

**Review by mdo — APPROVED** [review]
Pre-approving for when this comes up for review.

**Comment by XhmikosR** [comment]
```
C:\Users\xmr\Desktop\bootstrap>npx autoprefixer --info
Browsers:
  Chrome for Android: 86
  Firefox for Android: 82
  And_qq: 10.4
  UC for Android: 12.12
  Android: 81
  Baidu: 7.12
  Chrome: 86, 85, 84, 83, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60
  Edge: 86
  Firefox: 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60
  iOS: 14, 13.4-13.7, 13.3, 13.2, 13.0-13.1, 12.2-12.4, 12.0-12.1, 11.3-11.4, 11.0-11.2, 10.3, 10.0-10.2
  Kaios: 2.5
  Opera Mini: all
  Opera Mobile: 59
  Opera: 72
  Safari: 14, 13.1, 13, 12.1, 12, 11.1, 11, 10.1, 10
  Samsung: 12.0

These browsers account for 92.57% of all users globally
```

```
C:\Users\xmr\Desktop\bootstrap>npx autoprefixer --info
Browsers:
  Chrome for Android: 86
  Firefox for Android: 82
  And_qq: 10.4
  UC for Android: 12.12
  Android: 81
  Baidu: 7.12
  Chrome: 86, 85, 84, 83, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60
  Edge: 86, 85
  Firefox: 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60
  iOS: 14, 13.4-13.7, 13.3, 13.2, 13.0-13.1, 12.2-12.4, 12.0-12.1, 11.3-11.4, 11.0-11.2, 10.3, 10.0-10.2
  Kaios: 2.5
  Opera Mini: all
  Opera Mobile: 59
  Opera: 72, 71
  Safari: 14, 13.1, 13, 12.1, 12, 11.1, 11, 10.1, 10
  Samsung: 12.0, 11.1-11.2

These browsers account for 94.65% of all users globally
```

**Comment by XhmikosR** [comment]
Let's land this as is; it doesn't really change anything in the dist files as is. Due to the issue we are having when removing Android, I say we revisit this later.

**Review by mdo — APPROVED** [review]

**Pull request merged**
