### PR TITLE
Fix hover-popover/tooltip flickering when mouse re-enters

### PR DESCRIPTION
**Pull request by sgonyea**
I'm not exactly happy with the code change I've made to fix this issue, but this at least demonstrates a fix (as well as the bug itself).

JSBin:  http://jsbin.com/hajeta/2/

Issues:
- Mouse out / mouse in over elements within the popover, the popover will continually flicker (until your mouse hovers over _only_ the popover itself.  no child elements)
- Mouse out / mouse in, if the user scrolled within the popover -- that scorll position is lost (b/c the popover is recreated repeatedly)

Steps to trigger the flickering bug:
- Hover over the text "Hover here!"
- Mouse over the tooltip itself
- Mouse-out and then quickly mouse back in (specifically, mouse back in over the text itself)
- See a flicker.  Then mouse up over other text.  The flickering continues.

Additionally: You can scroll within the popover and see the flicker / (continual) resetting of the inner scrollbar position.

Hopefully the explanation and the demo make sense.

Thank you very much!  Bootstrap is fantastic.

### CODE REVIEW

**Comment by creative3d** [comment]
Hello everybody. I've found this issue looking for a fix for this joomla issue: https://github.com/joomla/joomla-cms/issues/10821 . If it's not much of a trouble, please help to fix that issue, or just write some advice to joomla developers because they are not trying to fix it, they are just waiting for you. Or maybe you can provide with a hot fix or something... Thanks.

**Comment by C-Lodder** [comment]
@creative3d - In Joomla we're still using BS2 which is no longer officially supported. To get the issue fixed, we'll either need to do it ourselves or perhaps it has already been fixed by a 3rd party who decided to keep supporting BS2

**Comment by creative3d** [comment]
@C-Lodder, "it has already been fixed" well, it wasn't, as far as I know, I was just able to pay their attention on this from the third attempt two month ago, no movements since then. As for fixing ourselves, I'd like to, but I'm not a developer, have no idea how. Thanks for answering.

**Comment by C-Lodder** [comment]
I'll look into it: https://github.com/joomla/joomla-cms/issues/10821#issuecomment-240348846

**Comment by creative3d** [comment]
Thanks a lot!

**Pull request merged**
