### PR TITLE
s/grunt-sed/npm script/

### LINKED ISSUE #18338: Replace grunt-sed with npm script
Refs https://github.com/twbs/bootstrap/pull/17446#issuecomment-137989190

Useful reference material: http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/

### PR DESCRIPTION
**Pull request by cvrebert**
Fixes #18338.
CC: @XhmikosR @hnrch02 @fat for review

### CODE REVIEW

**Comment by XhmikosR** [comment]
Wow, great job as usual!

I'm gonna try it later today or tomorrow and let you know.

**Comment by cvrebert** [comment]
@XhmikosR Had a chance to test it out yet?

**Comment by XhmikosR** [comment]
@cvrebert: sorry didn't have the time yet. I'll do it this weekend.

**Comment by XhmikosR** [comment]
@cvrebert: I tried it, and seems to work fine apart from the dist files. I know, that those are supposed to be generated but you know.

After that, I'd say we can merge it.

**Comment by XhmikosR** [comment]
Oh, don't forget to remove the old stuff from Gruntfile.js and npm-shrinkwrap.json.

Finally, do you think we should `exec` this via Grunt for consistency since we don't have any other `npm scripts`?

**Comment by XhmikosR** [comment]
Oh, also, the JS files are using `4.0.0`, we might need to normalize this.

**Comment by cvrebert** [comment]
> Oh, don't forget to remove the old stuff from Gruntfile.js

Done.

> and npm-shrinkwrap.json.

Will re-shrinkwrap right after this is merged.

> Finally, do you think we should exec this via Grunt for consistency since we don't have any other npm scripts?

Meh, particularly since this script wont be used by anyone outside of Core Team.
And I'm hoping to have more npm scripts going forward.

**Comment by XhmikosR** [comment]
OK, then we should just normalize the version across the codebase and merge.

**Comment by cvrebert** [comment]
> seems to work fine apart from the dist files. I know, that those are supposed to be generated but you know.

Including them feels kinda dirty, but okay, I've removed the exclusion of `dist`.

**Pull request merged**
