### PR TITLE
Update which required jQuery release folks should use

### PR DESCRIPTION
**Pull request by Johann-S**
We already changed that in our `package.json` so we should do the same and warn folks which do not use jQuery 3

### CODE REVIEW

**Comment by XhmikosR** [comment]
@Johann-S: I'd say we should do this for all other places.

* bootstrap.nuspec
* bootstrap.sass.nuspec
* bower.json

**Comment by XhmikosR** [comment]
And maybe we should change the version range on package.json to reflect the fact that we need <4.

**Comment by Johann-S** [comment]
That's true 👍

**Comment by Johann-S** [comment]
Is it ok for you now @XhmikosR ?

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
@mdo: not sure in which section to mention this change in the ship notes, so feel free to add it yourself.

**Pull request merged**
