### PR TITLE
Documentation tweaks

### PR DESCRIPTION
**Pull request by MartijnCuppens**
- The `.col-12` classes are redundant
- Mention the `xs` infix is not used
- Clarify the mobile first approach better

This should be backported to `v4`

### CODE REVIEW

**Review by midzer — COMMENTED** [review]
I stumbled upon term `printed` for xs class infix.
Maybe use something more common like `used` if this goes in same direction?

Everything else looks fine.

**Comment by MartijnCuppens** [comment]
Definitely better, thanks @midzer

**Comment by ysds** [comment]
I found a similar code in the document.

https://github.com/twbs/bootstrap/blob/c2fa74b65278415fb6ed545186f4dd6c23c575cf/site/content/docs/4.3/layout/grid.md#L306

https://github.com/twbs/bootstrap/blob/c2fa74b65278415fb6ed545186f4dd6c23c575cf/site/content/docs/4.3/layout/grid.md#L480

**Comment by MartijnCuppens** [comment]
Just searched for more redundant appearances of `.col-12` and removed those too

**Review by ysds — APPROVED** [review]

**Comment by XhmikosR** [comment]
I believe this was a leftover from the old days. Still, I need @mdo's approval just to be safe.

**Review by mdo — APPROVED** [review]

**Comment by XhmikosR** [comment]
@MartijnCuppens: I'm having trouble cherrypicking this, please have a look later (maybe redo this manually in my `v4-dev-xmr-backports` branch).

**Pull request merged**
