### PR TITLE
Rebuild the dist to pickup new utilities file

### PR DESCRIPTION
**Pull request by mdo**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@mdo: please pull the branch, do `npm i` and regenerate any dist files.

**Comment by mdo** [comment]
Reran, had `package-lock.json` changes. Pushed the latest.

@XhmikosR if this looks off or needs something else, feel free to push changes and/or close this and open a fresh PR.

**Comment by XhmikosR** [comment]
If we are sure about the icons location, I'll fix it here later.

**Comment by XhmikosR** [comment]
@mdo: please make sure you either using 10.16.0 or the latest Node.js 12.x and not an npm version other than the one that ships with those.

**Comment by XhmikosR** [comment]
I'll verify the lock changes, but in theory there shouldn't be any if you follow what I said above.

**Comment by XhmikosR** [comment]
yeah, @mdo you are using an old npm. I'd suggest you remove any node.js and npm packages and install the latest 10.x (preferably) or 12.x.

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
