### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by XhmikosR**
@Johann-S: the babel ones is what I haven't tested thoroughly. We need to read the release notes in case we need to update our config or something. Also, make sure you are using node 10.3.0 which ships with npm 6.3.1.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Hmm, locally the build works fine for me. Maybe we should add node.js 10 to Travis?

**Comment by XhmikosR** [comment]
OK, it seems we need some changes in our config somewhere and it's not related to Node.

**Comment by XhmikosR** [comment]
Ping @Johann-S

**Comment by XhmikosR** [comment]
@hzoo: do you know how to fix these errors after beta45?

**Comment by hzoo** [comment]
```
{ Error: ENOENT: no such file or directory, mkdir '/home/travis/build/twbs/bootstrap/js/coverage/dist'
    at Object.fs.mkdirSync (fs.js:885:18)
```

Hm never seen that before, maybe related to https://github.com/loganfsmyth/babel/commit/2cbfc34570dbc66724ce403d52ba2189802219f1#diff-f93fbf6dce06b5cbf6cc65f5f7dac101? @loganfsmyth?

**Comment by loganfsmyth** [comment]
@hzoo Filed: https://github.com/babel/babel/issues/8182

**Comment by XhmikosR** [comment]
Thanks @hzoo and @loganfsmyth. Until we have a new release with this fix and the Windows RegExp fixes, I'm gonna stay with beta.44.

@Johann-S please review so that we merge this.

**Review by Johann-S — APPROVED** [review]

**Pull request merged**
