### PR TITLE
[Feature] Easy & small carousel for multiple items

### PR DESCRIPTION
**Pull request by wtorsi**
Hello everyone.

In the last project i thought about horizontal/vertical slider for thumbs, partners and other things which everybody use for scrollable lists, and which can be slid right and left/up and down, and i hope i found a easy solution. 

So, my idea was to provider the
- Minimal weight slider supporting bootstrap grid system. 
I want `carousel` behaviour (not all behaviour for now), but for multiple items. As a note, there are a lot of supporting Google queries which make standard bootstrap carousel works as I want, but they a very complicated and not unique - you always need cheating solutions, need more code. 
I want to use usual `grid` and `flex` utilities to create the slider which you need. 
At this moment I've dropped infinite loop at all, because I don't have tests which passing this option in usability. Those kind of elements usually come from _design_ and _common things for nowage web_. 

- No nav slider utils on mobile (nav is redundant when you have swipes). I want native browser swiping (because it's cheaper for fx). 
- I want easy and fast customisation with `html` only, because it's independent from other languages.
 
As the result, I came up to the following solution, and I want to discuss it (it has bugs). Because it needs more work, but I think it can become a new component.

Here is the request.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Hello.

Not sure if we'll even go ahead with this, but the master version does not use jQuery. Also always make sure tests pass.

**Comment by XhmikosR** [comment]
Let alone the folder 4.1 shouldn't exist. I'm tempted to just close this one and when you are ready to make a proper PR do it then.

**Comment by wtorsi** [comment]
Sure, it's just a template for https://github.com/twbs/bootstrap/issues/29928 issue

**Comment by patrickhlauke** [comment]
just skimming the code, that example would only work for mouse users. no touchscreen, keyboard, or assistive technology support. and particularly for AT on touch, currently the only proper way to support a slider correctly is to have an actual range input and hijacking that (e.g. https://codepen.io/patrickhlauke/pen/byWPMX) or, at that stage, just using some CSS to style an actual range input.

**Comment by wtorsi** [comment]
@patrickhlauke 
First of all, happy new year! 🎄

Just checked, touch and keyboard is supported by default (Chrome) because it's a native scrollable container. You can check `dev` version https://rvio.itsd.one/ (first row after accordeon, and the last row of logos before footer), maybe it will be more informative.

At this moment there are no AT in the example, because I'm not good in the technology, but I hope this moment can be resolved with smbd help. 
For now I don't see any reasons to use `range` inputs in the slider, but at this moment I need more investigation as well, maybe you can describe the reasons more precisely?

**Comment by wtorsi** [comment]
Ok, i think this is a misunderstanding, according to https://www.w3.org/TR/wai-aria-practices-1.1/#carousel  
it's not a slider, it's a carousel. There is no need in range inputs here.

**Pull request closed without merging**
