### PR TITLE
Add border-radius style to navbar

### PR DESCRIPTION
**Pull request by jlbooker**
### Description

Add `border-radius` style to the `navbar` class, using a new `$navbar-border-radius` variable, which inherits from the global `$border-radius` variable.

### Motivation & Context

All the other components I'm using (e.g. alerts, buttons, form components) have rounded corners via `border-radius`, but I noticed the `navbar` class doesn't. For consistency, I've added the same `border-radius` to the Navbar.

Further background: I'm upgrading a site's theme from v3 to v5 (a little late, I know..) and noticed the navbar lost its rounded corners somewhere between v3.3.5 and latest. I looked back through the commit history on `_navbar.scss` to see if this was done intentionally, but a quick scroll of the last ~100 commits (back to 2017) didn't yield anything that stood out. It looks like the radius was being overridden and set to 0 specifically in a v4 alpha, but that was removed in 819978cb7.

Marked this as a breaking change, since the navbar's  appearance will be slightly different by default.

Edit: grammar, and to add that I hope I'm not unintentionally starting a religious bikeshedding war regarding rounded vs non-rounded corners. 

### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [x] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

(Existing tests pass locally for me. I didn't see any relevant documentation or tests that would need to be updated.)

#### Live previews

- <https://deploy-preview-39326--twbs-bootstrap.netlify.app/>

### CODE REVIEW

**Comment by julien-deramond** [comment]
I'd say this is a good thing to make it customizable for consistency with other "Sass/CSS interfaces".

However, I'm not sure it should be rounded by default in terms of usage. Most of the time, they are used as headers, so it could cause some trouble by default like we can see in basically all our examples containing a navbar as a header (e.g. https://deploy-preview-39326--twbs-bootstrap.netlify.app/docs/5.3/examples/album/).

Maybe we can do the same thing as for the breadcrumbs where `$breadcrumb-border-radius: null !default;` but is still customizable via:
* `$breadcrumb-border-radius`
* `--#{$prefix}breadcrumb-border-radius`
* or by using `.rounded-*` utilities

**Comment by jlbooker** [comment]
Hmm, yea, I see what you mean when the Navbar is used at 100% width.

For reference, I'm looking at how it was used under v3.3.5, where the navbar was in a container that kept it at < 100%:
https://getbootstrap.com/docs/3.3/components/#navbar

Was that version ever used at 100% widths? Or did it just have the oddly rounded edges?

**Comment by julien-deramond** [comment]
> when the Navbar is used at 100% width.

Yep and when it is stuck to the edge of a container (or the window). You would also have for instance the following where the top-left|right corner is an issue:
Screenshot 2023-10-25 at 18 22 18

> Was that version ever used at 100% widths? Or did it just have the oddly rounded edges?

I don't have the history, I never used the v3, but when it's used at 100% width in the documentation of the v3, other classes are used to make it transparent or to set the width of the border to 0.

**Comment by jlbooker** [comment]
Alrighty then. I'll close then and just use the `.rounded` util class on my navbar.

**Pull request closed without merging**
