### PR TITLE
Separator for table direct children

### LINKED ISSUE #34732: Rowspan affects tbody border color
Second `tbody` has wrong `border-color` on cells having `rowspan` attribute.

image

<details>
<summary>HTML</summary>

```html
<table class="table table-sm">
  <thead>
    <tr>
      <th></th>
      <th class="text-end">
        <span class="fw-bold">Длина</span>
        <br>
        <span class="fw-normal">мм</span>
      </th>
      <th class="text-end">
        <span class="fw-bold">Толщина</span>
        <br>
        <span class="fw-normal">мм</span>
      </th>
      <th class="text-end">
        <span class="fw-bold">Высота</span>
        <br>
        <span class="fw-normal">мм</span>
      </th>
    </tr>
  </thead>
  <tbody class="">
    <tr>
      <td>ПСТ 60.9.2,5-Т</td>
      <td class="text-end" rowspan="3">5890</td>
      <td class="text-end" rowspan="3">250</td>
      <td class="text-end">880</td>
    </tr>
    <tr>
      <td>ПСТ 60.12.2,5-Т</td>
      <!-- . -->
      <!-- . -->
      <td class="text-end">1180</td>
    </tr>
    <tr>
      <td>ПСТ 60.15.2,5-Т</td>
      <!-- . -->
      <!-- . -->
      <td class="text-end">1480</td>
    </tr>
  </tbody>
  <tbody>
    <tr>
      <td>ПСТ 60.9.3-Т</td>
      <td class="text-end" rowspan="3">5890</td>
      <td class="text-end" rowspan="3">300</td>
      <td class="text-end">880</td>
    </tr>
    <tr>
      <td>ПСТ 60.12.3,5-Т</td>
      <!-- . -->
      <!-- . -->
      <td class="text-end">1180</td>
    </tr>
    <tr>
      <td>ПСТ 60.15.3,5-Т</td>
      <!-- . -->
      <!-- . -->
      <td class="text-end">1480</td>
    </tr>
  </tbody>
</table>
```
</details>

### PR DESCRIPTION
**Pull request by ffoodd**
Fixes #34732, closes #34764 as a replacement, basically refactoring the evolution from v4 instead of adding old code.

The main culprit here is getting back to a `2px` border, since for whatever reason a `1px` border is hidden behind cells borders. As pointed out by @adityadees, a `1.1` multiplicator would be enough, but feels like a magic number to me.

IMHO @mdo we'd better recommend to use our border utilities (eg. `.border-dark` in the initial issue, as in [this dedicated CodePen](https://codepen.io/ffoodd/pen/QWgNpLY)) rather than fixing this. Any thought?

--- 

Demo [on CodePen](https://codepen.io/ffoodd/pen/OJgNWym).

### CODE REVIEW

**Comment by mdo** [comment]
I feel like the new code is actually simpler somehow? I don't mind it as the path forward. Utilities could work, but ideally stuff like this works out of the box IMO. Maybe I made tables too opinionated in v5 😬

**Comment by ffoodd** [comment]
So what about this 😄? Do we stick with the `2px` border as in this PR, or do we move things again to support this?

**Comment by adityadees** [comment]
> I feel like the new code is actually simpler somehow? I don't mind it as the path forward. Utilities could work, but ideally stuff like this works out of the box IMO. Maybe I made tables too opinionated in v5 😬

Nah, I think since v5 you reduce 2 to 1. But I don't know why?
That's why I just put 1.1 just to add second border bigger than first border without change initial value from v5.

**Review by mdo — APPROVED** [review]
@ffoodd I think we stick with the 2px still. Let's ship it!

**Pull request merged**
