### PR TITLE
Docs: Add --save-dev to npm install command

### PR DESCRIPTION
**Pull request by CoolGoose**

### CODE REVIEW

**Comment by cvrebert** [comment]
@CoolGoose It's not obvious to me why it would be a devDependency vs. a non-dev dependency. Seems like the dev-ness might vary by project, making this too opinionated.

**Comment by CoolGoose** [comment]
@cvrebert a couple of things
1. It needs at least --save if not --save-dev, mostly because beginners will not understand that they need at least one or the other
2. People are mostly using pre-processors when using the node package (be it with less, sass, or just including the full css)

**Comment by cvrebert** [comment]
1. Many other npm packages get away fine with just saying `npm install foo` in their instructions and leaving saving (or manual editing of `package.json`) to the users.
2. There's no data to confirm or deny that, just anecdote. Among all users of Bootstrap, I'd wager a great deal that CSS is most popular. Since it's perfectly valid to use either the Sass or the CSS, personally I'd prefer to stay agnostic. If we chose either the dev or non-dev side, we'd likely eventually get an issue filed by someone who wants to use the other.

CC: @hnrch02 @XhmikosR @patrickhlauke for more opinions

**Comment by mdo** [comment]
I'm fine punting on this—it's been the same way since we added those instructions way back when. No reason to change them now in v3's docs.

**Pull request closed without merging**
