### PR TITLE
[Idea] ✨ Add TOC to variables.scss

### PR DESCRIPTION
**Pull request by k-utsumi**
to make the structure easier to understand and organize♻️

---

I often look at [variables file](https://github.com/twbs/bootstrap/blob/v4.4.1/scss/_variables.scss).
That file is hard to understand what exists, so I suggest to include TOC.

I usually do like that.

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
Not sure what the benefit of a TOC is if it doesn't provide any anchor links? The find function in IDE's are doing a great job imo?

**Comment by ffoodd** [comment]
@MartijnCuppens I think the main concern here is not to go to a specific section, but to know they exists.

FWIW I'm not in favor of this (yet) since it could conflict with #28553 and #28662 — and at least doesn't seem to go the same way.

**Comment by MartijnCuppens** [comment]
In that case, we should focus on using `scss-docs` more, which makes it easier to notice without having to dive into the variables file.

Gonna close this since I think this implementation won't be the solution.

**Comment by k-utsumi** [comment]
I understood it is not the solution.
This is for a messy CSS project in my job.

I want to make the TOC simpler and easier to find information like this.
https://github.com/k-utsumi/bootstrap/blob/bd0f58ec0e941c041fe413ad115c0791ee6f1341/scss/_variables.scss

I think it will help organize the order and grouping of codes.

I'll watch those issues. thanks!

**Comment by k-utsumi** [comment]
I found a similar change 💡
https://github.com/twbs/bootstrap/commit/5310bb4c0f1d8516edccd416a976ed903016e406#diff-df1f74faf207a474f1d78c86393221c8R1-R10

**Pull request closed without merging**
