### PR TITLE
Fix copy button hover effect and position.

### LINKED ISSUE #18438: Clipboard "Copy" buttons in docs aren't styled correctly
#17751 appears to have broken the positioning and hover-coloring of the clipboard "Copy" buttons in the docs.

Old styling:
old-copy

Current styling:
new-copy

CC: @XhmikosR

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #18438.

/CC @cvrebert

### CODE REVIEW

**Comment by cvrebert** [comment]
This does fix the hover color, but the positioning on http://localhost:9001/content/images/ is still broken.

**Comment by XhmikosR** [comment]
That I don't get. I can change the `top` value to `1.2rem`, this is how it'll look like:

**Comment by XhmikosR** [comment]
Or maybe even `1.5rem`?  But it looks crap when the example is small like `http://127.0.0.1:9001/getting-started/introduction/#quick-start`

**Comment by XhmikosR** [comment]
OK, I think I sorted it out. Please check this branch and let me know so that I squash before merging.

**Comment by cvrebert** [comment]
Looks sufficiently aesthetically pleasing to me.

**Comment by mdo** [comment]
Fixed in 4520b0f.

**Pull request closed without merging**
