### PR TITLE
Fixed issue with .offcanvas-lg in dark mode.

### PR DESCRIPTION
**Pull request by tcasaniv**
Fixed issue with .offcanvas-lg in dark mode on screen widths less than 991.98px.

Navbar was not displayed correctly. #35857 
image

This is how it is fixed:
image

### CODE REVIEW

**Comment by mdo** [comment]
What browser and OS are you seeing this on?

**Comment by julien-deramond** [comment]
> What browser and OS are you seeing this on?

Don't know about the OP. Just tried it quickly. On my side I can see it on Chrome (Ubuntu) and not on Firefox (Ubuntu).

**Comment by mdo** [comment]
This PR got messed up, so closing it out for now and leaving a comment in the dark mode PR for me to revisit this.

**Pull request closed without merging**
