### PR TITLE
Release v3.4.0

### LINKED ISSUE #25679: v3.4 release
Hi all, opening this to track a possible v3.4 final release. It would be great to have this, as the v3.4-dev branch includes #23687, which fixed a few xss vulnerabilities. 

There are also a few [remaining v3 issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Av3), but it's not clear to me how critical they are.

### PR DESCRIPTION
**Pull request by XhmikosR**
@mdo @Johann-S

TODO:

- [x] Fix any 404s and useless redirects
- [x] Remove customizer's gist creation
- [x] Fix Browser tests
- [x] Go back to single colon pseudo elements for backwards compatibility with the browsers we support in v3
- [x] Fix docs search
- [x] Replace ZeroClipboard with clipboards.js since Flash is dead
- [x] Tweak clipboard.js styles
- [x] Update team
- [x] Nuke jobs from docs
- [x] Add the unprefixed `appearance` property
- [x] Add BrowserStack thanks in README.md
- [x] Exclude docs less files from Jekyll
- [x] Test builds with real apps just in case
- [x] Verify sourcemaps work
- [x] Customizer: remove drag and drop support and references, or fix this
- [x] **Make sure the SRI hashes are updated and correct!**
- [x] **Make a dist commit on non-Windows and make sure there are no modifications; if there are, commit them, then rebase the branch**
- [x] Detailed references to the XSS fixes for each component in release notes/post
- [x] **Merge https://github.com/algolia/docsearch-configs/pull/577 after the release is live**

Ship list:

- 29f9237, 13bf8ae fixed XSS issue in Alert, Carousel, Collapse, Dropdown, Modal and Tab components, see https://snyk.io/vuln/npm:bootstrap:20160627.
- 48f1482 added a `.row-no-gutters` class.
- cf6f867 Add padding to `navbar-fixed-*` on modal open
- 4f4592c and subsequent commits reorganized the v3 docs CSS to use Less.
- 1d83280 added a dropdown to the docs nav for newer and previous versions.
- 059969b update the docs to use a new baseurl, `/docs/3.4`, for that versioning life when we deploy to GitHub Pages.
- 4ebe2b8 switch to BrowserStack for tests
- e105d15 use https/fix broken links in docs
- 25d017a replace ZeroClipboard with clipboard.js
- d7ab2fb remove gist creation in customizer since anonymous gists are disabled by GitHub
- b304c61 remove drag and drop support from customizer since it didn't work anymore
- d24d47c Add docs searching via Algolia
- Remove the double border on `<abbr>` elements.

Closes #25679.

**Docs Preview: <https://twbs-340.netlify.com/>**

### CODE REVIEW

**Comment by Johann-S** [comment]
Tests I did:

- v3.4.0 works well with jQuery 3
- Our JS works well
- Tested the build

**Comment by XhmikosR** [comment]
All good then, I also tested the build with Chrome and FF in an app of mine. I didn't try IE at all though, I will try it later.

So, only sourcemaps testing is left and a couple of docs styling from @mdo.

**Comment by mdo** [comment]
Spun this up locally today...

- I had to install `karma-cli` globally to get `grunt` to run—it'd fail every time trying to run Karma tests otherwise. Are we missing a declared dependency?

- Need to update the ship list to exclude the mention of native font stack—I unshipped that a bit ago because of concerns around old browsers and OSes.

- Need to update the local dev docs in the readme to point to the correct localhost URL (e.g., it's no longer just ` http://0.0.0.0:9001/` but ` http://0.0.0.0:9001/docs/3.4/`).

- Should we point the About page link in the footer to the v4.x about pages? I don't want to get into the habit of maintaining two versions of the team pages, for example.

Otherwise, I _think_ this looks good!

**Comment by XhmikosR** [comment]
@mdo 

1. not true, something on your side for sure
2. your call :)
3. your call also
4. well that's a tricky thing. Because we can't always point to the latest docs and this was basically an old branch with other people involved anyway

**Review by mdo — APPROVED** [review]
🤘

**Pull request merged**
