### PR TITLE
WIP: Add variable to documentation pages

### PR DESCRIPTION
**Pull request by jhechtf**
Document the variables that each component uses or otherwise declares in order to make theme-ing a bit more streamlined.

Similar to how Bulma's documentation lists the applicable variables [Example of Bulma's Navbar component](https://bulma.io/documentation/components/navbar/#variables)

### CODE REVIEW

**Comment by XhmikosR** [comment]
Hmm, so many conflicts.

**Comment by jhechtf** [comment]
Yeah, that part I don't understand. I merged in the V4 master from the main
repo before pushing the code up. So it should all match.

**Comment by XhmikosR** [comment]
You are not supposed to do that. v4-dev is never merged on master, only the other way around.

You need to do `git rebase -i upstream/master` and drop all unrelated patches.

**Comment by jhechtf** [comment]
My mistake. I had a vage memory of V4-Dev being the base for V4 related
development. I'll fix it in a second.

**Pull request closed without merging**
