### PR TITLE
fix get the transition duration parent

### PR DESCRIPTION
**Pull request by Johann-S**
Fix our build: https://travis-ci.org/twbs/bootstrap/jobs/352733509

/CC @XhmikosR to fix our build and @MartijnCuppens

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
Why would you get the transition duration from the parent if the element has no transition duration?

**Comment by Johann-S** [comment]
Because as I linked, you cannot get the inherited transition duration on Safari, and in Bootstrap sometimes we use `Util.getTransitionDurationFromElement` with a child element which do not contain any transition duration

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
