### PR TITLE
Set `cursor:pointer` for `<summary>`

### LINKED ISSUE #24617: Add `cursor: pointer` for `details`?
Noticed this on our docs, https://github.com/twbs/bootstrap/blob/v4-dev/docs/4.0/getting-started/introduction.md

/CC @mdo

### PR DESCRIPTION
**Pull request by andresgalante**
This PR changes the cursor to pointer on the docs.

@mdo I wonder if this belongs to reboot.

closes #24617

### CODE REVIEW

**Comment by mdo** [comment]
> I wonder if this belongs to reboot.

Given it's an element, let's put it in Reboot. If it was a `.class`, it'd be something to reset elsewhere :). Let's also add a note to the Reboot docs to explain that we make this change.

**Comment by andresgalante** [comment]
Before we merge it, lets consider this: I found out why the cursor is `text` and not `pointer`:

If you have an anchor inside the summary, then the anchor will have a pointer:
https://codepen.io/pen/?editors=1010

**Comment by XhmikosR** [comment]
How about we just use our collapse?

**Review by mdo — APPROVED** [review]

**Comment by patrickhlauke** [comment]
> Before we merge it, lets consider this: I found out why the cursor is `text` and not `pointer`:
> If you have an anchor inside the summary, then the anchor will have a pointer

it's a pretty bad UI/UX decision at the moment in browsers. and as anchors/links in the summary would still be styled like normal links, it's not really problematic i'd say.

**Comment by patrickhlauke** [comment]
sorry @mdo, didn't notice the v4-stable project. have i messed up the release plan?

**Comment by mdo** [comment]
@patrickhlauke Nope, just trying to budget out issues and PRs :).

**Pull request merged**
