### PR TITLE
Custom checkboxes and radios retheming

### LINKED ISSUE #27063: Custom checkboxes and radios retheming
The custom checkboxes and radios are cool, but I think they might need some retheming. I don't think it's a good idea to make them gray, it looks like they are disabled and there isn't much of a difference between the disabled and not disabled versions.

Imo they should have the same background and border color as the `.form-control` elements and also take over the theming of disabled state.

I made a demo of the rethemed custom checkboxes here: https://codepen.io/MartijnCuppens/pen/KBYKKz

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Closes #27063

### CODE REVIEW

**Comment by XhmikosR** [comment]
LGTM but I'd even go with even more darker border.

Either way, the final review is for @mdo @andresgalante to make (for now :P)

**Comment by MartijnCuppens** [comment]
Made a third version with a darker border (`$gray-600`) https://codepen.io/MartijnCuppens/pen/PywvVJ. I think this is a bit too dark and the border color differs too much from `.form-control`

**Comment by XhmikosR** [comment]
Yup, agreed, this one is a little too much. But let's move this on the PR itself. :)

**Review by mdo — APPROVED** [review]
Dig the new look, thanks!

**Pull request merged**
