### PR TITLE
Use Flexbox instead of display:table for .input-group

### PR DESCRIPTION
**Pull request by boogerlad**
http://philipwalton.github.io/solved-by-flexbox/demos/input-add-ons/

### CODE REVIEW

**Comment by XhmikosR** [comment]
What's the rationale behind this?

**Comment by boogerlad** [comment]
I view using tables as a hack. This requires less code and seems to be the more modern way of doing things properly.

**Comment by XhmikosR** [comment]
Well, `flex` isn't available in old browsers.

/CC @mdo @cvrebert

**Comment by cvrebert** [comment]
Yup. Flexbox requires IE10+. Bootstrap supports IE8+, and I doubt we'd be willing to require a polyfill for this. Perhaps in Bootstrap 5 :-P
IE8 is a bastard.

**Comment by cvrebert** [comment]
X-Ref: #15721.

**Comment by johnnyshields** [comment]
@cvrebert It would be very nice if we could have an `input-group-flex` or something that would allow this, with the obvious caveat that IE8 isn't supported. `input-group`s are particularly nasty, and for those of us not using IE8 we'd really benefit...

**Comment by cvrebert** [comment]
@mdo is working on optional Flexbox support for Bootstrap v4 (off by default, controlled by a Sass variable.

**Pull request closed without merging**
