### PR TITLE
Update Brazilian Portuguese translation's URL

### PR DESCRIPTION
**Pull request by adammacias**
Now Bootstrap Brasil have custom domain. :wink:

### CODE REVIEW

**Comment by AndreLGava** [comment]
How can I contribute to translation?

**Comment by adammacias** [comment]
@AndreiRailean you can help us here @bootstrapbrasil

**Comment by cvrebert** [comment]
CC: @XhmikosR @hnrch02

**Comment by XhmikosR** [comment]
The website doesn't seem to work for me.

**Comment by cvrebert** [comment]
Works for me, although third-party "getbootstrap" domains make me uncomfortable from a brand/trademark perspective.

**Comment by XhmikosR** [comment]
Might be a DNS update issue.

And yeah I agree with you. It indicates even indirectly that this is
official.

**Comment by hnrch02** [comment]
> Works for me, although third-party "getbootstrap" domains make me uncomfortable from a brand/trademark perspective.

I'm inclined to agree, but I think that's more of @mdo's field.

---

Other than that I don't know what to comment about here. 👍  for translations and this seems to only update the URL anyway.

**Comment by adammacias** [comment]
Guys, we @BootstrapBrasil know the importance of official brand Bootstrap, obey the license to mention the official link in all pages our website. :smiley: The domain that way help users memorize, anyway, the domain is redirecting to the other link `http://bootstrapbrasil.github.io/`.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Pull request closed without merging**
