### PR TITLE
Sass map trickery for easier customization

### PR DESCRIPTION
**Pull request by mdo**
**Peep the [CodePen demo](https://codepen.io/anon/pen/XaJeVd).**

This PR creates a `!default` empty Sass maps for our `$grays`, `$colors`, and `$theme-colors` lists and `map-merges` a default setting for all colors into them. This way, anyone can continue to `map-merge` in additional or replacement `key: value` pairs as needed without having to replace the _entire_ original Sass map as @martinbean pointed out in #23112.

This technique was pointed out by @hokiecoder in https://github.com/twbs/bootstrap/issues/22891#issuecomment-316463806.

---

Thoughts? If folks are interested, we'll need to update the `options.md` docs page to explain this, and add some code comments in our Sass files.

### CODE REVIEW

**Review by bardiharborow — APPROVED** [review]

**Comment by martinbean** [comment]
@mdo It’s an improvement in that we don’t have to re-define unnecessary variables to override a sub-set now 😀 

Curious as to why the move to holding theme colours in a map now though, rather than simple variables? As my feeling is it was a lot easier to reference `$brand-primary` in custom Sass style sheets than `map-get($theme-colors, "primary")`. I think for designers and front-end developers not familiar with things like maps in Sass, this change may make Bootstrap less accessible to them and steepen the learning curve for them.

**Comment by kartikluke** [comment]
@martinbean They iterate over the map when generating buttons, etc. so just by adding to the array you can add new theme colors for buttons, etc. which is useful.

If it's possible to dynamically generate Sass variables you could iterate through the map and make flat variables which people could use.

**Comment by liquidvisual** [comment]
I agree with @martinbean regarding ease of use. I'm a designer, and I find the ```map-get($theme-colors, "primary")``` so cumbersome to write. I use $brand-primary everywhere, and it's a no-brainer to type.

**Comment by martinbean** [comment]
I’m getting an error when trying to override the primary colour.

My *app.scss*:

```scss
@import "custom";
@import "node_modules/bootstrap/scss/bootstrap";
```

My *_custom.scss* file:

```scss
$theme-colors: (
  primary: #c00
);
```

The error I get when trying to compile:

> Error: node_modules/bootstrap/scss/_forms.scss
> Error: argument `$color` of `rgba($color, $alpha)` must be a color
> 
> Backtrace:
> &nbsp;&nbsp;node_modules/bootstrap/scss/_forms.scss:280, in function `rgba`
> &nbsp;&nbsp;node_modules/bootstrap/scss/_forms.scss:280
> &nbsp;&nbsp;&nbsp;&nbsp;on line 280 of node_modules/bootstrap/scss/_forms.scss
>  &gt;&gt;   background-color: rgba($form-feedback-invalid-color,.8);

**Comment by mdo** [comment]
> I'm a designer, and I find the `map-get($theme-colors, "primary")` so cumbersome to write. I use $brand-primary everywhere, and it's a no-brainer to type.

@liquidvisual You don't have to pull from the map at all times—we have all the variables there still. We use the Sass map to reduce overhead and iterate over all our variables to generate every component's themed modifier classes

> How come the implementation demonstrated in the aforementioned Pen not implemented for the beta? As that’s what I followed.

I didn't have time to get this into the beta and this isn't a breaking change. It'll make it into beta 2.

**Comment by dfinucane** [comment]
@martinbean I think you are getting that error because you don't import functions before variables

**Comment by SirCmpwn** [comment]
Having to use map-get everywhere is *awful*. Strong :-1:

**Comment by martinbean** [comment]
> now have no idea how to make basic customizations

This.

Bootstrap used to be so simple to customise. Maps may be a great data structure to hold things like colours of a theme, but they’re not accessible or great for beginners or non-full-time front-end developers to customise.

It’d be great if the top-level `$brand-` variables were brought back and a map used “under the hood” to hold the colours belonging to the theme, but I think the current solution is just going to frustrate and turn away a _lot_ of users.

**Comment by SirCmpwn** [comment]
It definitely turned me away. I reverted back to v4.0.0-alpha.6 and will not be upgrading so long as this is a problem.

**Comment by Soullivaneuh** [comment]
> I didn't have time to get this into the beta and this isn't a breaking change. It'll make it into beta 2.

@mdo You you have any eta for the release of the beta 2?

**Comment by braginteractive** [comment]
So does anyone know how to change the theme colors so it will edit all the elements that use primary, secondary, etc? 

For example, I am looking to change the $primary color, so when I use things like btn-primary it will be my custom color. The following doesn't work:

```
$custom: #123;

$theme-colors: (
  primary: $custom
);
```

Is there another step to override and use the map defaults?

**Comment by dfinucane** [comment]
I have a file I named _custom_bootstrap.scss that contains something like the following
`
@import './bootstrap/scss/functions';

$gray-100: #f8f9fa;
$gray-600: #868e96;
$gray-800: #343a40;
$black:  #000;
$blue:    #0082cc;
$red:     #dc3545;
$yellow:  #ffc107;
$cyan:    #17a2b8;

$theme-colors:(
    primary: $blue,
    secondary: $gray-600,
    success: $blue,
    info: $cyan,
    warning: $yellow,
    danger: $red,
    light: $gray-100,
    dark: $gray-800
);
`
then in my applications styles.scss I have the following
`@import 'custom_bootstrap';

@import 'bootstrap/scss/bootstrap';
`
The thing that helped me understand how this had to work was I realized that what SASS calls variables are really constants in that once they are defined they can't be changed.  So knowing that all you need to do is import your _custom_bootstrap.scss before bootstrap defines those same 'variables'.

**Comment by braginteractive** [comment]
@dfinucane worked perfectly. Thanks

**Comment by martinbean** [comment]
> And it needed the whole map

Yup. This is what I’ve been trying to get over. It’s overkill when all people will want to do is change the brand primary colour.

**Comment by kartikluke** [comment]
@braginteractive This PR is meant to fix the issue you just had. The name is a bit confusing but this is the main part.

> This way, anyone can continue to map-merge in additional or replacement key: value pairs as needed without having to replace the entire original Sass map as @martinbean pointed out in #23112.

**Comment by philipchristopher** [comment]
@liquidvisual You can reduce some of the complexity of the "map-get" function by using bootstrap's "theme-color" function which simply returns the theme-color. Makes it a little less cumbersome.

```css
@import "~bootstrap/scss/functions";

h2 {
  color: theme-color("primary");
  /* color: map-get( $theme-colors, primary); */
}
```

**Comment by d4rky-pl** [comment]
It's still more cumbersome because now my IDE does not autocomplete this which ruins my flow, making me pause to stop and think and triple-check if I didn't make a mistake or typo. 

It was so great to just type `$brand-` and get a full list of available options... :(

**Comment by martinbean** [comment]
@mdo Thanks for making customisation easier again in beta 2! 😘

**Comment by 9peppe** [comment]
I believe the base color constants (`$white` to `$cyan`) should probably be separated in a different scss file. So that they can be imported *before* the maps are created to easily define the logical function colors (`$primary` to `$dark`) in customizations. 

In beta2 this is really confusing, because you can easily override variables like `$body-bg` and `$body-color` after `@import "variables";` but you **cannot** effectively do the same with `$primary` and the like.

**Pull request merged**
