### PR TITLE
Popup and tooltip: dimensions  in rem and bug fix of arrow placement

### PR DESCRIPTION
**Pull request by NielsHolt**
Hi
This PR will change the dimensions of popover and tooltip from px to rem AND fix a bug in the way the arrow of popover and tooltips are placed. The current placement of the arrow is only centered on the element when border-width and arrow-width are default values. This PR will allow both border-width and arrow-width to be changed
It need to be merged/integrated with #23763
Could solve #23793 and issues in #23468 
Setting `$border-width: 20px; $popover-border-width:10px;` in Bootstrap 4-beta would give
bootstrap-popover-4-beta
In this PR (with `$popover-arrow-width: 1rem;`) it would be
bootstrap-popover-nielsholt

### CODE REVIEW

**Comment by Johann-S** [comment]
is it possible to have a live example on a Codepen ?

**Comment by NielsHolt** [comment]
@Johann-S - I put some images in my original comment. I haven't used CodePen before but I give it a try (but it may take a while)

**Comment by NielsHolt** [comment]
Hi @Johann-S 
I have made a Codepen [here](https://codepen.io/NielsHolt/pen/yzBwEm)
Do 
[https://github.com/FezVrasta/popper.js/issues/417](https://github.com/FezVrasta/popper.js/issues/417)

**Comment by NielsHolt** [comment]
Sorry - closed by mistake

**Comment by wojtask9** [comment]
@NielsHolt 
I created PR https://github.com/twbs/bootstrap/pull/23936 (based on your) but should fix some other issues.
Can you check if my PR fix also your issues?

**Comment by NielsHolt** [comment]
Ups - was closed by mistake. Reopened with updated [demo](https://codepen.io/NielsHolt/pen/yzBwEm)

**Comment by mdo** [comment]
Not a fan of this approach, thanks though!

**Pull request closed without merging**
