### PR TITLE
Fix missing !important rule in responsive breakpoints classes

### LINKED ISSUE #18300: Responsive text utilities are missing the !important rule (v4)
When doing something like `<p class="text-left text-md-right">I'm always aligned to the left</p>` the `text-left` helper class takes precedence, because the responsive utility classes are missing the `!important` rule (or should be removed from the base classes):

```
.text-left           { text-align: left !important; }
.text-right          { text-align: right !important; }
.text-center         { text-align: center !important; }
.text-justify        { text-align: justify !important; }
.text-nowrap         { white-space: nowrap !important; }
.text-truncate       { @include text-truncate; }

// Responsive alignment

@each $breakpoint in map-keys($grid-breakpoints) {
  @include media-breakpoint-up($breakpoint) {
    .text-#{$breakpoint}-left   { text-align: left; }
    .text-#{$breakpoint}-right  { text-align: right; }
    .text-#{$breakpoint}-center { text-align: center; }
  }
}
```

### PR DESCRIPTION
**Pull request by deilv**
Fixes #18300.

The !important tag should not be used in every possible scenario, because it leads to cascading css problems.

However, it's highly recommended for utility classes such as "text-_-left", "text-_-right" and "text-*-center". These utility classes are only used inline and you actually expect them to be enforced and override any other behavior of that element.

### CODE REVIEW

**Comment by Deilv** [comment]
This is for the v4-dev branch.

Travis seems to crash at the moment, perhaps it doesn't like node5 that much.

**Comment by cvrebert** [comment]
> Travis seems to crash at the moment, perhaps it doesn't like node5 that much.

No, it doesn't like RVM much: https://github.com/rvm/rvm/issues/3559

**Comment by cvrebert** [comment]
For future reference, when crafting a pull request to fix a known issue, wording your commit message to utilize https://help.github.com/articles/closing-issues-via-commit-messages/ is appreciated.

**Comment by cvrebert** [comment]
Merged as 2c3a592a6edb6596ca05c240abf7b053f6333c02. Thanks.

**Pull request closed without merging**
