### PR TITLE
Variable darken percentage for emphasized links

### LINKED ISSUE #25574: Emphasized link
The darken percentage of a link is not the same as the darken percentage of an emphasized link (link with a class like `.text-success`). If we use a variable for this, it would also be possible to disable the darkened links on hover (sometimes you only want an underline on hover).
 
https://github.com/twbs/bootstrap/blob/9057d8da164bed683f49d30c6414753dad41de3e/scss/_variables.scss#L153

https://github.com/twbs/bootstrap/blob/9057d8da164bed683f49d30c6414753dad41de3e/scss/mixins/_text-emphasis.scss#L11

PR incomming

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Closes #25574.

### CODE REVIEW

**Comment by andresgalante** [comment]
Hi @MartijnCuppens you are right they both should be 15%.

I don't think the implementation is correct though.

`$link-hover-color:` is allowing users to change the way they do hover, they can even change it to be lighten or any other function.

As you mention the `text-emphasized` mixin is hardcoding it.

By generating a variable to change the percentage we'd be allowing users to customize how dark the link color can be, but it's not flexible enough to produce the same results they'd get from changing `$link-hover-color:`.

Therefore I suggest a new variable like: 
```
$text-hover-color:                        darken($color, 15%) 
```

What do you think?

**Comment by MartijnCuppens** [comment]
And how would you implement this `$text-hover-color`? Wouldn't this make all the hover colors of all links with a `text-*` color class the same?

**Comment by MartijnCuppens** [comment]
I've got an idea. We could calculate the difference in lightness between `$link-color` and `$link-hover-color` with the [lightness()](http://sass-lang.com/documentation/Sass/Script/Functions.html#lightness-instance_method) function and than darken (or even lighten) the hover color of emphasized links.

**Comment by MartijnCuppens** [comment]
@andresgalante, what do you thing of the latest changes? This doesn't require an extra variable and feels more flexible.

**Comment by andresgalante** [comment]
Hi @MartijnCuppens there are other color functions apart from lighten and darken. Let me think about this one and get back to you.

@mdo any good idea of how to make this flexible and consistent?

**Comment by mdo** [comment]
This one's tough. There's no real way to do what we do elsewhere—a variable for the entire thing like `$link-hover-color`. In this case, I think it's ultimately okay to limit things or have some constraints in an effort to avoid complexity. I think I'm fine with just a variable.

**Comment by MartijnCuppens** [comment]
Jup, this was getting too complex indeed. I've reverted my changes to the initial commit. Is `$emphasized-link-hover-darken-percentage` a good name for the variable or do you have another suggestion, @mdo?

**Review by XhmikosR — APPROVED** [review]

**Review by mdo — APPROVED** [review]

**Comment by XhmikosR** [comment]
@MartijnCuppens: this needs a rebase.

**Comment by MartijnCuppens** [comment]
@XhmikosR, done.

**Pull request merged**
