### PR TITLE
Add a badge to track our dependencies

### PR DESCRIPTION
**Pull request by Johann-S**
Add a badge to track easely our dependencies, currently this badge looks like that (inSecure) : 

[dependencies Status](https://david-dm.org/twbs/bootstrap)

Because we choose to require at least jQuery `1.9.1` but all the release of jQuery under jQuery `3` are vulnerable to this XSS issue : https://nodesecurity.io/advisories/jquery_xss

So I recommand to change our required jQuery version to : `>=3.0.0`

Side Note : jQuery `3` compatibility https://jquery.com/browser-support/

/CC @mdo @XhmikosR @bardiharborow

### CODE REVIEW

**Comment by XhmikosR** [comment]
Only commen is that I'd move the dependencies badge before the devDependencies one.

Other than that, I'm definitely in favor of requiring jQuery 3.x.

**Comment by Johann-S** [comment]
Thank you @XhmikosR , I made those changes 👍

**Review by mdo — APPROVED** [review]
Looks good, let's do it for Beta 2! <3

**Comment by mdo** [comment]
I quickly merged this, but we might need to revisit for `peerDependencies`?

**Comment by Johann-S** [comment]
It seems ok because you merged v4-dev in this branch

**Comment by XhmikosR** [comment]
@Johann-S @mdo: you mean add a peerDendencies badge?

**Comment by mdo** [comment]
Yeah what @Johann-S said :D

**Pull request merged**
