### PR TITLE
Add a parameter for the focused button box shadow color

### PR DESCRIPTION
**Pull request by mroskamp**
I noticed the same mix() call was being made several times for the button focus box shadow. I also ran into a scenario where I wanted to customize the box shadow. Since the mixin already supplies multiple parameters for different colors for the various states, it made sense to add a parameter for this as well.

### CODE REVIEW

**Review by ffoodd — APPROVED** [review]
Nicely done, thanks!

**Comment by ffoodd** [comment]
Could be backported [to v4](https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_buttons.scss) BTW.

**Comment by XhmikosR** [comment]
@mdo up to you to add any projects and review

**Comment by tpatartmajeur** [comment]
Hi, any news regarding this PR?

**Comment by ffoodd** [comment]
Friendly ping @mdo 🙂

**Comment by mdo** [comment]
Good optimization! I think we can actually skip this though and wait for #34600, which does the same thing via CSS variable. Thoughts?

**Comment by ffoodd** [comment]
Agreed 👌

**Comment by XhmikosR** [comment]
@mdo this was marked for backport so if we still want this there we need a separate PR targeting v4 assuming we proceed with skipping this PR in favor of #34600.

**Comment by mdo** [comment]
Unclear if we want to add this to v4, but noted for after the other PR merges. Closing out in favor of that path.

**Pull request closed without merging**
