### PR TITLE
Added support for RTL

### PR DESCRIPTION
**Pull request by awinny**
Added support for RTL mentioned in following support issue:  https://github.com/twbs/bootstrap/issues/16419
Integrated this fix as a part of the general structure rather than a override on top on the existing structure.
This changes behavior of columns, navbar and other components rendering elements using float rules.
These will now instead be aligned using display: inline-block and block making it more easy to handle and to understand.

### CODE REVIEW

**Comment by cvrebert** [comment]
> This changes behavior of columns, navbar and other components rendering elements using `float` rules.
These will now instead be aligned using `display: inline-block`

We've previously determined that the `inline-block` approach is inferior to the `float` approach, and aren't open to switching the grid system over to `inline-block`. See #17915.
So could you please undo that portion of your changes?

**Comment by Knodden** [comment]
> We've previously determined that the inline-block approach is inferior to the float approach, and aren't open to switching the grid system over to inline-block. See #17915.
Sure I´ll modify that part so it instead uses float rules then, however as I see it `display: inline-block` would make alignment of other thing easier to handle and make it possible to remove those clear fixing stuff.

**Comment by PejmanNik** [comment]
why this pull is in awaiting reply?
@Awinny dosen't work on it any more?
how can i help?

**Comment by OmarIthawi** [comment]
Thanks @Awinny for your work. It is definitely much better to include the RTL in the core @twbs.

@cvrebert other than the `inline-block` issue. Do you see any major issues preventing this work from getting merged? I'd be willing to take it from here if the work is acceptable product-wise.

I already have a lot of experience with RTL/LTR and recently I've done a major contribution to make the [edx-platform support RTL](https://github.com/edx/edx-platform/pull/2682), and I'd be more than happy to work on @twbs on that matter.

**Comment by mdo** [comment]
Thanks, but this is too much to handle in one PR right now. Punting until we're ready to do this full-time and can break it down into manageable PRs.

**Comment by OmarIthawi** [comment]
Thanks @mdo  for your reply. I'm very invested in this work. Could you please let me know when do you think there will be time to support the RTL?

I'd be very happy to collaborate, and I think I can be flexible enough to match your contribution preferences like breaking the PRs and others as well.

**Pull request closed without merging**
