### PR TITLE
Use class name variables in selectors

### PR DESCRIPTION
**Pull request by ghost**
See comments and PR changes.

### CODE REVIEW

**Review by Johann-S — CHANGES_REQUESTED** [review]
Please fix this build issue : https://travis-ci.org/twbs/bootstrap/jobs/201115160#L198-L199

**Comment by DavisMiculis** [comment]
Okay, seems like tests now passed. Sorry for not checking correct linting.

**Comment by Johann-S** [comment]
IMO you should check other plugins to see if you can find same issues in their (to add consistency to your PR)

**Comment by DavisMiculis** [comment]
Seems like `[role="menu"]` and `[role="listbox"]` also can be modified to variables.  Need some input about `VISIBLE_ITEMS`.

**Comment by DavisMiculis** [comment]
I did something similiar with tabs JS, but I need input if this is even "right" or "correct" ? Just seems strange for me to keep class name in variables, but then again use class names as strings.

**Comment by bardiharborow** [comment]
@DavisMiculis, yep, this is correct from my point of view. Is this ready to merge?

**Comment by DavisMiculis** [comment]
I will try to go over all JS files later today. Should I try to use variables as much as possible in selectors?

**Comment by bardiharborow** [comment]
@DavisMiculis, either we won't be merging this, or we'll want them all done, so I'd suggest doing everything.

**Review by Johann-S — APPROVED** [review]

**Comment by DavisMiculis** [comment]
Guess not.

**Pull request closed without merging**
