### PR TITLE
Add CSS properties to extend browser support

### PR DESCRIPTION
**Pull request by mhmmdtech**
### Description

I discovered issues while using Hint tools to check my website, and some of them were related to Bootstrap so I decided to resolve them in Bootstrap repository

This request includes 3 changes with the addition of 2 CSS properties to support a wider range of browsers.

1- Change the priority of text-align: inherit; and  text-align: -webkit-match-parent:
In this case, -webkit-text-align is placed before text-align so that WebKit browsers can recognize and apply the -webkit-match-parent value. Other non-WebKit browsers will ignore the -webkit-text-align property, and the text-align property will be used instead.

2- Adding text-size-adjust: 100%;
By placing the standardized property first, it will be recognized and applied by most modern browsers. The subsequent -webkit-text-size-adjust property will be recognized by WebKit-based browsers and used as a fallback for older browser versions that require the vendor-specific property.
It's important to note that in this specific case, where both properties have the same value and affect the same CSS attribute, the order may not have a noticeable impact on the rendered outcome.

### Motivation & Context

These changes include properties that allow to support more browsers

### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

- <https://deploy-preview-39164--twbs-bootstrap.netlify.app/>

### CODE REVIEW

**Comment by julien-deramond** [comment]
Thanks for opening this PR @mhmmdtech 
Could you please update the description of this PR to explain in detail what issues? It could help with the review.

**Comment by mhmmdtech** [comment]
> Thanks for opening this PR @mhmmdtech Could you please update the description of this PR to explain in detail what issues? It could help with the review.

Hi @julien-deramond I hope you are well
I have updated the description and hope it can be helpful

**Review by arm666 — COMMENTED** [review]
Looks good !!

**Comment by XhmikosR** [comment]
This needs @mdo's eyes. Reboot is supposed to fix issues, not have all properties present.

**Comment by mhmmdtech** [comment]
Hello @XhmikosR , I hope you are well
It would be great if you @mdo  review this issue.
Please keep in mind that by doing this we will support more browsers and we won't face warnings in website optimization analyzer tools.

**Comment by ffoodd** [comment]
Hi there, FWIW the current code will always apply `inherit`, singe the last wins, in CSS — so whatever your tool hints, at least the order must remain the same.

No need for the webkit prefix either, Autoprefixer will take care of it if needed.

IMO the code should be:

```css
text-align: inherit;
text-align: match-parent;
```

It'd need to be checked through BrowserStack I guess, because the `inherit` fallback could be useless now, depending on our target.

**Comment by binler** [comment]
@mdo I think it should be fixed in the latest version (specifically v5.3.4)

**Pull request closed without merging**
