### PR TITLE
Add newer version 5 alert on top of v4 and v5 pages

### LINKED ISSUE #38331: Documentation: 4.3 page should inform about v5
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

The documentation for version 4 should have a note about it beong older version and a link to version 5 doc

### Motivation and context

When I search for various Boostrap terms, Google gives me links to the version 4 documentation for example https://getbootstrap.com/docs/4.3/components/alerts/

IMHO these pages should have a note about outdated information, and a link to the most recent documentation - like on https://fontawesome.com/v5/docs

### PR DESCRIPTION
**Pull request by julien-deramond**
### Description

This PR adds a banner to the top of the docs to inform the users about the new Bootstrap version.

_Sorry for the amount of files changed_

* **3.3**: Banner was already here so changed "Bootstrap 4 is here!" into "There's a newer version of Bootstrap!"
* **3.4**: Banner was already here so changed "Looking for Bootstrap 4?" into "There's a newer version of Bootstrap!"
* **4.0/4.1/4.2**: Banner was already here so changed "There's a newer version of Bootstrap 4!" into "There's a newer version of Bootstrap!"

From here, I tried to avoid using `.old-bv` class that was added manually in `gh-pages` `docs.min.css`. Preferred to find already existing classes. Also changed the HTML structure in order to have a working visible focus (more details in https://github.com/twbs/bootstrap/pull/38410#issuecomment-1544017267)

* **4.3/4.4**: New banner by using `.swatch-purple`
* **5.0/5.1/5.2**: New banner by using `.skippy`

### For future selves

This is how you can add easily this banner in a specific version in this `gh-pages` branch:

Screenshot 2023-04-04 at 22 08 31

### Motivation & Context

Inform the users about the new Bootstrap version but is mostly useful when you arrive from a search engine in the v4 docs for example.

### Type of changes

- [x] Refactoring (non-breaking change)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] I have updated the documentation accordingly
- (N/A) I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

- You can run locally `php -S localhost:8008` or `npx http-server` to test it.

### Related issues

Closes #38331

### CODE REVIEW

**Review by louismaximepiton — COMMENTED** [review]
TBH, I don't really like having the new version number of Bootstrap mentioned since it means that we'd need to change it afterwards, meaning more maintenance for future.

I'd rather have something like in v2:
`<a href="https://getbootstrap.com/">Looking for the lastest version of Bootstrap? Check it out!</a>`

The only thing not to forget here is to add this banner when we upgrade minor/major versions. I don't know if it has to be written down anywhere?

**Comment by julien-deramond** [comment]
> TBH, I don't really like having the new version number of Bootstrap mentioned since it means that we'd need to change it afterwards, meaning more maintenance for future.

Yep, I agree with it. Tried to match the existing pattern in v3 and v4 but I can change it everywhere to use the exact same label without mentioning the version. Other thoughts in the team?

**Comment by XhmikosR** [comment]
Converted the PR to draft so that we discuss it first.

I think we should go with with the same way for all old banners; no need to mention the version. And maybe don't touch v3; we need to be extra careful there because the HTML files were minified.

Either way, thanks for tackling this, we'll land one solution or another. :)

**Comment by mdo** [comment]
Pushed a change to tweak the copy. I think touching v3 is fine, there's still some traffic that goes to those pages, but if someone feels stronger, feel free to remove. This can be reviewed and merged whenever.

**Comment by XhmikosR** [comment]
v3: It can't be reviewed so easily was my point, since the files were minified.

As for the rest, I still don't think we should tie things to a specific version number. The message should read: There's a newer major version of Bootstrap. Or something like that :)

**Comment by mdo** [comment]
Oh I'm down with that actually.

**Comment by julien-deramond** [comment]
In this PR, we might take the opportunity to make this banner accessible by adding a visible focus.

I was thinking about how to improve the workflow after this PR. It could be interesting to add in our _main_ branch at the right place the code for this banner associated with a `.d-none` class so it is not displayed while it is the latest version. But when we will release a new version, by going back to `gh-pages`, we would only have to remove this class to render it correctly. I'm thinking about it because it is easier to change the rendering in the _main_ branch with the right classes rather than after when the classes might have changed.

**Comment by XhmikosR** [comment]
We shouldn't **really** try to improve the old version docs. They are a snapshot of what we had on the development branch when the version was current.

Just add the link to the main site with a general message and we are done with it. We won't have to go back to them again for the same issue.

As for the future, we only need to do this on main and it should be discussed then. Generally, adding useless stuff just in case we need it, it's not preferable, at least to my eyes; when we need something we add it then.

**Comment by XhmikosR** [comment]
BTW, I'm not saying I'm against your idea for the next versions, we just need to discuss it in a PR that implements it (CC me).

**Comment by julien-deramond** [comment]
> We shouldn't really try to improve the old version docs. They are a snapshot of what we had on the development branch when the version was current.

I'm not talking about improving the old version docs. I'm only talking about adding a class or two in the existing banners to make them accessible since I have to change their labels as well. If not possible with classes, let's forget it.
I understand your point about the docs in `gh-pages` being snapshots of what we had on the development branch when the version was current. But that's not true for these banners that have been added in `gh-pages` after.

For the new banners, I have to choose a style with classes. So while I'm at it, if possible, let's use classes that allow the visible focus to be displayed.

> As for the future, we only need to do this on main and it should be discussed then.

Yep, that's what I explained. Just wanted to suggest this idea in this context. I'll create a PR then to tackle this specific topic. No problem.

**Comment by mdo** [comment]
@julien-deramond That's my desire as well—if we can do it with classes, let's do it. Otherwise, punt on it :). Thanks for doing this!

**Comment by julien-deramond** [comment]
Modified the entire PR via https://github.com/twbs/bootstrap/pull/38410/commits/08a32c3ef887cb8a661277ddd9686b6b74cf70a9 to use unique wording: "There's a newer version of Bootstrap!"
Feel free to change it. You just have to search/replace this sentence to change everything at once.

I'll check this afternoon if it is possible to add some a11y with classes and come back with a new commit. If not possible, I'll make this PR "Ready for review".

**Comment by julien-deramond** [comment]
OK so this is not possible to add the visible focus in versions before 4.3 (excluded) because I'd need to modify the HTML structure used to display these banners. They are all in the same spirit as the following:

```html
<a href="https://getbootstrap.com/" class="d-block px-3 py-2 text-center text-bold text-white text-decoration-none skippy">There's a newer version of Bootstrap!</a>
```

In order to work, we should have a `<div>` as a container with this `.d-block` class and the link inside. Based on the previous example, should be rather:

```
<div class="d-block px-3 py-2 text-center text-bold text-white text-decoration-none skippy">
<a href="https://getbootstrap.com/">There's a newer version of Bootstrap!</a>
</div>
```

However, from 4.3 (included), I've used this new structure for the newly added banners via https://github.com/twbs/bootstrap/pull/38410/commits/1b33e1682bdef9322141c676b3eafd4f9df93149.

**Review by mdo — APPROVED** [review]

**Pull request merged**
