### PR TITLE
Updated background properties using safe shorthands.

### PR DESCRIPTION
**Pull request by rouralberto**
Well, the title is self-explanatory. Just cleaning code... =)

### CODE REVIEW

**Comment by XhmikosR** [comment]
/CC @mdo 

Personally, I like this approach.

**Comment by roura356a** [comment]
Hi! Any update here? A better approach maybe? //@mdo

**Comment by XhmikosR** [comment]
@cvrebert: your thoughts?

**Comment by cvrebert** [comment]
I don't see what the advantage would be. Is it just "fewer declarations"?

And if we went this route, wouldn't using one variable for the entire `background` value allow for better customization?

**Comment by mdo** [comment]
I prefer the individual properties for legibility and explicitness.

**Comment by XhmikosR** [comment]
All right, closing this then.

**Pull request closed without merging**
