### PR TITLE
Utilities for overflow and object fit

### PR DESCRIPTION
**Pull request by MadeByRaymond**
**Added "overflow-x" and "overflow-y"**
- Having the same properties as overflow but for just the x and y axises
- Usecase being I want my y axis to be scrollable but not my x axis
- E.g a card with a vertical list of items.

**Added "object-fit" utilities**
- The CSS object-fit property is used to specify how an `` or `<video>` should be resized to fit its container.
- A responsive alternative to using background-img for a resizable fill/fit image.

### CODE REVIEW

**Comment by mdo** [comment]
I could be down for these in v5.3.0. Going to play a bit more with them myself and see if we'd want to update any docs to better utilize these. Speaking of, can you take a pass at creating a docs page and/or updates for these?

**Comment by MadeByRaymond** [comment]
> I could be down for these in v5.3.0. Going to play a bit more with them myself and see if we'd want to update any docs to better utilize these. Speaking of, can you take a pass at creating a docs page and/or updates for these?

Alright @mdo, I can take a pass at the docs and update the PR.

**Comment by MadeByRaymond** [comment]
@mdo  done!

**Review by mdo — APPROVED** [review]

**Comment by MadeByRaymond** [comment]
@mdo Updated placeholder "img" markup to address HTML Validation Errors

**Comment by MadeByRaymond** [comment]
@mdo I don't think I should be able to update the .bundlewatch.config file. 
Right?

**Comment by julien-deramond** [comment]
> @mdo I don't think I should be able to update the .bundlewatch.config file. Right?

Given the content of this PR, you can update the following corresponding values of `.bundlewatch.config.json` by adding a step of 0.25:

```
FAIL ./dist/css/bootstrap-utilities.css: 8.39KB > 8.25KB (gzip)
FAIL ./dist/css/bootstrap-utilities.min.css: 7.68KB > 7.5KB (gzip)
FAIL ./dist/css/bootstrap.css: 29.44KB > 29.25KB (gzip)
FAIL ./dist/css/bootstrap.min.css: 27.33KB > 27.25KB (gzip)
```

So for example the modification for `bootstrap-utilities.css` will be:
```diff
diff --git a/.bundlewatch.config.json b/.bundlewatch.config.json
index cea957f5e..0fda9d5d6 100644
--- a/.bundlewatch.config.json
+++ b/.bundlewatch.config.json
@@ -18,7 +18,7 @@
     },
     {
       "path": "./dist/css/bootstrap-utilities.css",
-      "maxSize": "8.25 kB"
+      "maxSize": "8.5 kB"
     },
     {
       "path": "./dist/css/bootstrap-utilities.min.css",
```

**Pull request merged**
