### PR TITLE
Update modal docs

### LINKED ISSUE #30055: Modal Documentation for Vertically Centered isn't Correct
The docs for the vertically centered don't appear to fully match what should be shown.  The "Launch Demo Modal" text should be "Vertically centered modal," but what really matters is that there's no class mentioned for `modal-dialog-scrollable` in the **Vertically Centered** section.
image

Very minor issue.

### PR DESCRIPTION
**Pull request by ysds**
* Simplify modal snippets
* Use id for data-target
* Unify the id positions

Closes #30055

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
Imo, this PR removes a little too much. I think people like it to just copy-paste the whole modal.

**Comment by ysds** [comment]
I do not think so. The first snippet in the "Scrolling long content" section makes no sense. Also, the current snippets of the size options don't work already because there are no content in the `.modal-content.` To make all snippets that can be copied successfully need too long line.

**Comment by XhmikosR** [comment]
I'm in between personally; I see @ysds's and @MartijnCuppens's points.

/CC @mdo to the rescue :P

**Comment by patrickhlauke** [comment]
FWIW i don't mind the cuts here

**Review by mdo — APPROVED** [review]
Cut it! :D

**Review by MartijnCuppens — APPROVED** [review]
Fine by me, let's do this

**Pull request merged**
