### PR TITLE
5 simple Lines of code to dropdown object model and life is easier

### PR DESCRIPTION
**Pull request by Sergisa**
From time to time when I use bootstrap I need to define the selection event on dropdown. But 5 simple lines of code help me to define this event in bootstrap API and simply use it. Like this:

```javascript
$('#myDropdown').on('selected.bs.dropdown', function () {
  // do something...
})
```
This change does not touch other bootstrap infrastructure.

**TODO:**
- [x] Add documentation

### CODE REVIEW

**Comment by XhmikosR** [comment]
You have an unrelated patch in this branch. Also make sure all tests pass please.

**Comment by Sergisa** [comment]
Yes, sorry, I forgot tests. Now everything is ok.

> You have an unrelated patch in this branch. 

you mean your changes with image file permissions?

**Comment by XhmikosR** [comment]
>you mean your changes with image file permissions?

Yeah

**Comment by Sergisa** [comment]
I've tried my best to remove your changes from my commits. 
Is everything OK now?

**Comment by MartijnCuppens** [comment]
This needs documentation:
https://twbs-bootstrap.netlify.com/docs/4.3/components/dropdowns/#events

**Comment by Sergisa** [comment]
> This needs documentation:
> https://twbs-bootstrap.netlify.com/docs/4.3/components/dropdowns/#events

You mean i must add documentation for my additions?
Please tell me which files i must edit... I'm not quite good in all project files hierarchy...

**Comment by MartijnCuppens** [comment]
@Sergisa, this file: https://github.com/twbs/bootstrap/blob/master/site/content/docs/4.3/components/dropdowns.md

**Comment by MartijnCuppens** [comment]
Made a demo of this: https://codepen.io/MartijnCuppens/pen/poJwJoG?editors=1111
> Fired when click event happens on one of dropdown list elements.

This is not true, this event is also triggered when the dropdown is triggered. Also, the event target always is the dropdown itself, not sure if this is really useful. On the other and, it is quite easy to write click events for dropdown items, not sure if this is useful in general.

**Comment by Sergisa** [comment]
@MartijnCuppens, yes, realy. Maybe it will be better if event listener will return html object of clicked item?

**Comment by MartijnCuppens** [comment]
Gonna close this. Adding a click event to the dropdown items will be way more straight forward than creating a custom event which does exactly the same.

**Pull request closed without merging**
