### PR TITLE
v4: Grid redux

### PR DESCRIPTION
**Pull request by mdo**
Addresses a handful of grid changes:
- #17119: Stubs out docs for flexbox grid.
- #17131: Adds auto layout for flexbox grid columns (to mixins and predefined classes) with the addition of `.col-{breakpoint` classes. For example, use `.col-xs` to create as many grid columns as you'd like from `xs` and up.
- #17261, #17603: ~~Adds a new `.col` base class for grid columns and~~ Changes the responsive grid modifier naming scheme from `.col-{breakpoint}-{modifier}-{size}` to `.{modifier}-{breakpoint}-{size}` for simpler grid classes. For example, instead of `.col-md-3.col-md-push-9` it's `col-md-3.push-md-9`. Also updates all examples to new markup.
- #17512, #17514: Overhauls the grid mixins to merge `make-col` and `make-col-span` into a single `make-col` mixin, thereby ensuring mixins and predefined classes utilize the same float/flex behaviors.
- #17593: Adds basic grid migration documentation, including mention of flexbox support, flexbox utils, and variables/maps changes.
- #18024 , #18164: Horizontal flexbox alignment utilities added.
- #18691: Documents flexbox vertical alignment utilities.
- #18785: Cherry-picks the changes to rename our flexbox grid utilities to global flexbox utilities.
#### Todo:
- [x] Document flexbox utilities

### CODE REVIEW

**Comment by mdo** [comment]
Most of this is done, including feedback from @cvrebert and @glebm, but I think I fucked up haha.

Need to revisit this a bit more yet—responsive is broken right now. I _think_ I need to redo the main `grid-framework` mixins to generate something more akin to the Bootstrap 3 and http://flexboxgrid.com approaches. That is to say, nuke the base class and list out all the classes with a specific `.col-{breakpoint}` class for auto-width flexbox instead.

Going to need to noodle on that for awhile if no one jumps in to help.

**Comment by karlhorky** [comment]
Looks like this addresses #18088 as well. I've closed it.

**Comment by julien-gargot** [comment]
About :

> #17512, #17514: Overhauls the grid mixins to merge make-col and make-col-span into a single make-col mixin, thereby ensuring mixins and predefined classes utilize the same float/flex behaviors.

Problem is, now, you have to override row-padding for working with contextual gutter widths.
If you can use `make-container($gutter)` and `make-row($gutter)`, it could makes sense to have a `$gutter` parameter in `make-col($size, $columns)` too. What do you think?

**Comment by julien-gargot** [comment]
# @mdo It’s seams that in the `make-grid-columns($columns: $grid-columns, $gutter: $grid-gutter-width, $breakpoints: $grid-breakpoints)` mixin in `scss/mixins/_grid-framework.scss`, the `$gutter` parameter is not used. The variable `$grid-gutter-width` is used to set the padding (lines 18, 19). Should this not be `$gutter`

**Comment by timalbert** [comment]
I don't think v4 documentation for modifier is updated

**Pull request merged**
