### PR TITLE
add keyboard and focus option and toggle method to toast

### LINKED ISSUE #37158: Add Modal's keyboard escape and focus options to Toasts
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Add configuration options to Toast components that allow for keyboard escapes and element focus using the same methods as modals.

### Motivation and context

Modals contain configuration options that allows for toggling off/on the ability for the user to keyboard esc to close and grant focus to the modal-window on init. Toasts can be used for similar, but less intrusive purposes in the UI, and allow to disable the autohide feature, but don't currently allow for keyboard escape options or focus, though they are perfectly capable of housing user inputs, meaning they are partially obscured from non-mouse users. Adding the same option gives both the developer and the user greater control over visibility of toasts.

### PR DESCRIPTION
**Pull request by debadutta98**
### Description

- Add keyboard escapes option
- Add toggle method to toggle toast
- Make changes on js\src\toast.js and js\tests\unit\toast.spec.js

### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [x] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

https://deploy-preview-37246--twbs-bootstrap.netlify.app/docs/5.2/components/toasts/#examples

### Related issues

Closes #37158

### CODE REVIEW

**Comment by debadutta98** [comment]
Hi, i add all possible test cases to toast.spec.js
image

**Comment by GeoSot** [comment]
@debadutta98 your MR is very well approached, and thank you very much for that. 

I wasn't sure about the focus functionality, so I 've asked the accessibility expert @patrickhlauke's opinion
According to this [comment](https://github.com/twbs/bootstrap/issues/37158#issuecomment-1268159750), we will need to wait a bit, for a well planed specification.


 **/CC** @patrickhlauke  in case of any extra thoughts, can you please update us here?


_Note:  I would also think the separation of these two concepts in different MRs_

**Comment by debadutta98** [comment]
> @debadutta98 your MR is very well approached, and thank you very much for that.
> 
> I wasn't sure about the focus functionality, so I 've asked the accessibility expert @patrickhlauke's opinion According to this [comment](https://github.com/twbs/bootstrap/issues/37158#issuecomment-1268159750), we will need to wait a bit, for a well planed specification.
> 
> **/CC** @patrickhlauke in case of any extra thoughts, can you please update us here?
> 
> _Note: I would also think the separation of these two concepts in different MRs_

@GeoSot Thank you for your appreciation it means a lot to me as a beginner open source contributor

As you mentioned above I remove toast focus functionality from this PR and now it's solved two issues instead of a total of three issues
- keyboard functionality
- toggle functionality

for focus functionality, I will make a different branch and make a PR
Thank you awaiting for your reply

**Comment by patrickhlauke** [comment]
confirming that when I check https://deploy-preview-37246--twbs-bootstrap.netlify.app/docs/5.2/components/toasts/ and trigger the live toast example, it can be dismissed with `Esc`.

worth adding extra prose to the docs that explains this behaviour, and the short descriptions on the tests could probably do with a slight language tweak to be a bit more readable.

worth also testing how this behaves in more complex situations: a toast triggered from inside a modal dialog for instance - does the `Esc` just close the toast, or the modal as well? if it just closes the toast, and the modal is left as it was, is a subsequent `Esc` press then correctly closing the modal? is the event listener for `Esc` removed if the toast automatically disappears?

as a side note, we probably want a similar behaviour for popovers (so they can be dismissed)

**Comment by debadutta98** [comment]
Hi, @GeoSot when will this PR will be merged? should I need to do any changes?

**Comment by patrickhlauke** [comment]
> [Modal with toast](https://codepen.io/debadutta98/pen/QWrzRmB)
> * In this test, I observed that on pressing `esc` both toasts, as well as the modal, is closed at a time.

my point was that, if possible, this shouldn't happen. `Esc` should just close the toast and keep the modal as it was. Then, a subsequent `Esc` should close the modal.

**Comment by GeoSot** [comment]
To be honest I postpone answering on this, because a new  listener is added on document for each instance, and I am not sure about the final effect :confounded:

**Pull request closed without merging**
