### PR TITLE
Examples updates

### LINKED ISSUE #22847: Docs: off-canvas example focus order is incorrect
In the off-canvas example, once the extra nav is collapsed, keyboard users can toggle the navigation - but then have to navigate through the rest of the page before reaching the off-canvas navigation.

offcanvas-focus

Ideally, once the off-canvas navigation is toggled, focus should be moved to it programmatically.

### PR DESCRIPTION
**Pull request by mdo**
Fixes bugs, updates to newer techniques, and adds some new examples. In addition, I've replaced the old `examples.md` file with an `examples.html` that loops over a new data file, `examples.yml`, to generate our list of examples.

- **Added four new examples—Pricing, Checkout, Product, and Floating Labels.** Closes #18296.

- **Overhauled Dashboard** with a brand new navbar and layout, large Chartjs example instead of placeholder circles, icons from Feather, and more.

- **Redesigned Offcanvas**  completely to be a mobile-focused example that integrates a drawer menu into the Bootstrap navbar.

- **Redesigned Blog** to give it the appearance of popular blogging platforms and magazines, featuring horizontal cards, Google Web Fonts, and more.

- **Updated Sign-in** to vertically center the form via flexbox and add more copy, images, and footer.

- **Refreshed Album** to remove the bulk of the `.card` overrides, add more components to the albums, and improve the visual styles.

- **Updated Cover** to replace the table hack for vertical centering with flexbox, simplifying the HTML and CSS. Also fixed a bug where the nav would be left aligned on mobile devices.

Still have some more to do here, so leaving as WIP for v4 stable.

- [x] Responsive Product
- [x] Spacing on responsive Checkout
- [x] Medium responsive on Pricing
- [x] Responsive Blog (cards, scrolling nav)
- [ ] Retake screenshots
- [ ] Compress screenshots
- [ ] Squash useless commits

---

Closes #22847, takes a first pass implementation for #21312.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@mdo: when you are ready, please squash any patches that can be squashed.

**Review by ghost — COMMENTED** [review]
Jumbotron narrow? Oh dear, my most beloved example... 😟

**Comment by fulldecent** [comment]
Hello from the Chart.js team. Thanks for adding the example!

**Comment by mdo** [comment]
@fulldecent Woohoo! Holler if there's anything else we can do to improve the page! <3

**Pull request merged**
