### PR TITLE
Bump copyright year to 2019 and dist

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Review by mattonit — APPROVED** [review]

**Review by mattonit — APPROVED** [review]

**Review by Johann-S — APPROVED** [review]

**Review by MartijnCuppens — APPROVED** [review]
LGTM 👍Good call making the years variable in the templates.

**Comment by mdo** [comment]
Just pushed the dist build. That's a lot of new lines though 🤔

**Comment by MartijnCuppens** [comment]
@mdo, it's caused by what will be fixed with this PR: https://github.com/twbs/bootstrap/pull/28005

**Comment by mdo** [comment]
Thanks everyone! Just pushed up a fresh build.

**Comment by MartijnCuppens** [comment]
:shipit:

**Comment by XhmikosR** [comment]
I want to rebase first before merging and squash

**Pull request merged**
