### PR TITLE
add .carousel-indicator-square and .carousel-indicator-circle

### PR DESCRIPTION
**Pull request by aditya1906**
This is a fix to the issue #28791

### CODE REVIEW

**Comment by morrissey-ingenious** [comment]
I don't really like this implementation, I would rather see indicators accept overrides with the `rounded` class

**Comment by aditya1906** [comment]
Do you think instead of using .carousel-indicators-circle we should use .rouned?

**Comment by forghan89** [comment]
> 
> 
> Do you think instead of using .carousel-indicators-circle we should use .rounded? I think indicator-square is fine.

I think `.carousel-indicators-round` is better.

**Comment by aditya1906** [comment]
@MartijnCuppens, @XhmikosR is this PR okay?

**Comment by XhmikosR** [comment]
It's up to @twbs/css-review, but for what is worth, I think it might be useful to others.

**Comment by ysds** [comment]
My concern is to increase CSS even though there are few cases where different styles are used in one application.

I think it may be enough to just document about  customization.

**Comment by mdo** [comment]
Agreed with @ysds, we don’t need these variants in the project. I also don’t think we need to do much there to customize the look and feel since the styles include `width`, `border-radius`, etc. There’s nothing clever here if I recall.

Thanks, but we’ll pass.

**Pull request closed without merging**
