### PR TITLE
avoid unnecessary HTML string building+parsing

### PR DESCRIPTION
**Pull request by cvrebert**
Rather than building a string of HTML and then parsing it, which is overkill and comparatively slow, this simply creates a new blank `<div>` and then adds the requisite classes via jQuery.
This could be further tweaked to use `className` instead of jQuery's `addClass` at the cost of a bit more verbosity; I opted to be conservative.

### CODE REVIEW

**Comment by cvrebert** [comment]
CC: @hnrch02 @XhmikosR

**Comment by XhmikosR** [comment]
I couldn't find any references that this is faster. Do you have any numbers? Also, are these the only cases?

The idea seems fine to me, just wondering.

**Comment by cvrebert** [comment]
> Do you have any numbers?

Yes: http://jsperf.com/dom-constr-42
jsperf
firefox
(Firefox won't upload due to bad CSRF token problem for some reason.)

> Also, are these the only cases?

Yes, except for the unit tests.

**Comment by XhmikosR** [comment]
Wow, huge difference! Definitely :shipit: .

How did you spot this?

**Comment by cvrebert** [comment]
I was reminded about it when nitpicking an instance of it in some new unit tests in a PR the other day.

**Pull request merged**
