### PR TITLE
Add focus style for checkboxes and radios

### LINKED ISSUE #28957: No focus style on checkbox and radios
### Description

There's no visual feedback when focusing a checkbox or radio.

### Ask

- Is this intended ?
- If not, will it be fixed ?

### Test case

Can be tested on [the current doc](https://getbootstrap.com/docs/4.3/components/forms/#checkboxes-and-radios)

### Additional Info

- A similar bug was opened for v.3 and has been fixed #14923
- [Custom form controls](https://getbootstrap.com/docs/4.3/components/forms/#custom-forms) checkboxes and radios have a focus style.

### PR DESCRIPTION
**Pull request by alienlebarge**
Add focus style for default checkboxes and radios 

#28957

### CODE REVIEW

**Comment by patrickhlauke** [comment]
I'm in favor of this, although note that it's not always 100% perfect in, say, Chrome

> with the new styles

but then, neither is Chrome's default

> default chrome outline on radio buttons

**Comment by patrickhlauke** [comment]
@mdo if you're not planning to have these styles for v5 (though I'm not sure I understand why/what the rationale is), then at least this can be backported to v4 though

**Comment by patrickhlauke** [comment]
urgh ok, so changing base just to v4 made this PR super-ugly...in which case (as we'd want this still in v4 i'd say) would you mind closing this one and starting a fresh PR targeting `v4-dev`? sorry about the to-ing and fro-ing

**Comment by XhmikosR** [comment]
We can rebase it if needed.

**Comment by MartijnCuppens** [comment]
@alienlebarge,
Could you clarify what these lines are for:
https://github.com/twbs/bootstrap/blob/cf521701c46407d8ca479b0037c21e9a62471896/scss/_forms.scss#L222-L224

**Comment by patrickhlauke** [comment]
i think a more concise way may be to just add the mixin, without even needing to replicate the `:focus` block manually here
```
@include form-control-focus($ignore-warning: true);
```

**Comment by alienlebarge** [comment]
@MartijnCuppens

> @alienlebarge,
> Could you clarify what these lines are for:
> 
> https://github.com/twbs/bootstrap/blob/cf521701c46407d8ca479b0037c21e9a62471896/scss/_forms.scss#L222-L224

I have simply use the code of the `@include form-control-focus($ignore-warning: true);` mixin but since it will be deprecated, I havn't use the mixin itself.

As @patrickhlauke propose, it could be better to use it and it will be refactor when removed

@patrickhlauke 

> urgh ok, so changing base just to v4 made this PR super-ugly...in which case (as we'd want this still in v4 i'd say) would you mind closing this one and starting a fresh PR targeting `v4-dev`? sorry about the to-ing and fro-ing

Do you still want a PR targeting `v4-dev`?

**Comment by patrickhlauke** [comment]
@alienlebarge sorry for all the to-ing and fro-ing, and yes there's lots of moving parts now that we've got v5 but still maintaining some parts of v4 etc...

if you don't mind, simplest would probably be to close this, make a new PR just with the mixin inclusion, and target v4-dev

**Pull request closed without merging**
