### PR TITLE
[Fix #17555][V4] fix resetting style on closing collapse

### LINKED ISSUE #17555: v4 - Collapse JavaScript - not removing a temporary style.
Hello,

when closing a collapse element, this line gets triggered:
this._element.style[dimension] = 0
causing the correct animation but which is not overwritten by
this._element.style[dimension] = ''
when the transition is completed.

After closing a collapse, there is a leftover height style, which might break layout and has to be removed when close transition is finished.

Should be added around line 232.

### PR DESCRIPTION
**Pull request by Johann-S**
Hi,

it's a fix for https://github.com/twbs/bootstrap/issues/17555

### CODE REVIEW

**Comment by Johann-S** [comment]
Sorry @cvrebert to PING you but I made my PR a long time ago (13 days) and nobody reviewed it

**Comment by cvrebert** [comment]
CC: @fat

**Comment by maniqui** [comment]
I can confirm this pull request fixes an issue with Collapse not removing a "leftover" inline style (`style="height: 0"`) after collapsing. After a navbar has been expanded and then collapsed, this leftover inline style will break the layout, when changing the viewport width (for example, by maximizing the window).

**Comment by Johann-S** [comment]
Thanks for your support @maniqui :smile:

**Comment by Johann-S** [comment]
Thank you @mdo 👍

**Pull request merged**
