### PR TITLE
System theme preference

### PR DESCRIPTION
**Pull request by iamstr**
themed according to the user's color scheme preference.
as well as a theme-dark-color map

### CODE REVIEW

**Comment by ffoodd** [comment]
You must not commit dist files. Please read our contribution guidelines.

**Comment by XhmikosR** [comment]
And also, this has many unneeded changes that should be reverted. Plus, many of the colors are not dark-friendly nor do they have proper contrast.

**Comment by iamstr** [comment]
> You must not commit dist files. Please read our contribution guidelines.

my bad I thought the .gitignore handled that😫

**Comment by mdo** [comment]
Closing out for now as this has tons of dist changes and conflicts. Please open a new PR without the dist files being modified so we can properly evaluate our options :).

**Pull request closed without merging**
