### PR TITLE
fix branch for coveralls badge

### PR DESCRIPTION
**Pull request by Johann-S**
/CC @XhmikosR

### CODE REVIEW

**Comment by XhmikosR** [comment]
@Johann-S: can you change it to shields.io?

**Comment by Johann-S** [comment]
Wow we should just run coverall for one build not for all 😆 and done @XhmikosR 😉

**Comment by Johann-S** [comment]
Oh yes you're right, I wasn't sure about that 😄

**Comment by XhmikosR** [comment]
@Johann-S: not sure why, but every time you change the package-lock.json you make many changes. Please make sure you are using `npm` that ships with node 8 or 10 and not another version. I'm gonna revert the changes, but we need to make sure it doesn't happen again.

**Comment by Johann-S** [comment]
I use npm `v6.0.0` and node `v9.7.1` 😟

**Comment by XhmikosR** [comment]
Yeah, please move to 8 or 10.

**Comment by XhmikosR** [comment]
OK, so this runs coveralls after success, but for both builds. It doesn't seem to affect anything.

**Comment by Johann-S** [comment]
and no more comments 🎆

**Comment by XhmikosR** [comment]
I could move the `after_success` call to run only after node.js 8. What do you think about that?

**Comment by Johann-S** [comment]
Much better to just run it once 👍

**Comment by XhmikosR** [comment]
Not sure this would run if `browser` stage doesn't run though :/

We need some help here.

**Comment by Johann-S** [comment]
Or you can revert that change and let `coveralls` command in our package.json as we do not have Coveralls comments

**Comment by XhmikosR** [comment]
OK, I think we just need  a little shell help. See my last push.

**Comment by Johann-S** [comment]
I made a change, which run `coveralls` just for node 8, can you take a look @XhmikosR ?

**Comment by XhmikosR** [comment]
Does the job indeed!

But I think we should not export another variable and just do the version check in the if check.

Something like this: https://stackoverflow.com/questions/48250235/how-to-setup-travis-to-skip-script-on-particular-nodejs-version

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
LGTM @Johann-S, feel free to rebase and merge :)

**Comment by XhmikosR** [comment]
@Johann-S: I just become aware there's a `TRAVIS_NODE_VERSION`. Might be worth checking if this variable is something we can just use.

**Comment by XhmikosR** [comment]
OK, it works :) I'm gonna merge when the build finishes.

**Pull request merged**
