### PR TITLE
[WIP] Experimental carousel example.

### PR DESCRIPTION
**Pull request by XhmikosR**
Show three items, slide by one.

Needs some love, but opening this so that we don't forget about it.

Ideally our JS plugin should handle this.

TODO:

- [ ] Style the whole example
- [ ] Add screenshots

Preview: <https://deploy-preview-28210--twbs-bootstrap.netlify.app/docs/5.0/examples/carousel-experiment/>

### CODE REVIEW

**Comment by XhmikosR** [comment]
This needs to be rewritten in vanilla JS.

**Comment by XhmikosR** [comment]
@mdo @MartijnCuppens: this is functional thanks to @Johann-S (it was broken afte rthe jQuery removal), so you can style it and then we can ship it

**Comment by MartijnCuppens** [comment]
Does it really need theming, I don't know what you had in mind?

**Comment by XhmikosR** [comment]
It just feel too plain right now, you know. So maybe you guys have some suggestions how to make the whole example more appealing maybe like the normal carousel example?

**Comment by mdo** [comment]
FWIW, I wouldn't mind something like this. Unsure how feasible it is to add to the existing plugin though for v5.

**Comment by XhmikosR** [comment]
I'm going to close this since I think this feature should be in core. PRs welcome :)

**Pull request closed without merging**
