### PR TITLE
Release v5.0.0-beta2

### PR DESCRIPTION
**Pull request by XhmikosR**
Preview: <https://deploy-preview-32467--twbs-bootstrap.netlify.app/>

### CODE REVIEW

**Comment by XhmikosR** [comment]
@ffoodd can you please have a quick look at the dist CSS changes so that we make sure everything's alright?

**Comment by ffoodd** [comment]
Seems good to me, I recognize every change with a single exception than I'm unable to trace back: some `.fs-*-*` utilities are removed, but I can't even find where they were coming from :thinking: 

@MartijnCuppens Might it relate to RFS?

**Comment by XhmikosR** [comment]
Yeah, that must be due to #32397

**Comment by ffoodd** [comment]
Indeed, missed that one— thanks :)

**Review by mdo — APPROVED** [review]

**Pull request merged**
