### PR TITLE
Fix <small> and .small colors on .panel-title 

### LINKED ISSUE #15493: Improve visibility of text in <small> elements within panel-title of panel-primary
When using the <small> Element within 'panel-title' classed headline of a 'panel-primary' the text is not readable. This is similar to #12397 and #13377.

See example: http://jsfiddle.net/9hfdyha5/2/

### PR DESCRIPTION
**Pull request by corymcdonald**
fixes #15493

### CODE REVIEW

**Comment by mdo** [comment]
An `inherit` instead of repeating the properties is likely all we need here.

**Comment by CoryMcDonald** [comment]
I'm not so sure, as `.panel-title` already has `color: inherit` so the following aren't displaying correctly because of their parent style.

1. `<h1 class="panel-title"><small><a>data</a></small></h1>` - overridden by `h1 small`
2. `<h1 class="panel-title"><span class="small"><a>data</a></small></h1>` - overridden by `h1 .small`
3. `<h1 class="panel-title"><small><a>data</a></small></h1>` - Overridden by `a` style.

**Comment by CoryMcDonald** [comment]
Or were you talking about?
    > small {
       color: @panel-primary-text;
       a {
         color: inherit;
       }

**Comment by mdo** [comment]
Alternate, compact fix merged in from #15594.

**Pull request closed without merging**
