### PR TITLE
v4 — Update  ZeroClipboard

### LINKED ISSUE #17340: Update ZeroClipboard
Now that we don't need support for old IE, we should update ZeroClipboard to the latest version.

### PR DESCRIPTION
**Pull request by kkirsche**
Fix #17340

### CODE REVIEW

**Comment by XhmikosR** [comment]
Definitely not so simple. There are API changes. Plus you didn't update the flash file.

**Comment by kkirsche** [comment]
Wouldn't it make sense to document with a more thorough bug rather than waiting for situations like this?

**Comment by XhmikosR** [comment]
It's common sense for someone who knows what they do.

**Comment by XhmikosR** [comment]
@kkirsche: do you plan to update the PR so that it actually works or should we close this for now?

**Comment by kkirsche** [comment]
I do plan to just been traveling for work

**Comment by XhmikosR** [comment]
No hurry, just wondering.

**Pull request closed without merging**
