### PR TITLE
Add new Chinese Simplified translation

### PR DESCRIPTION
**Pull request by MrWillCom**
This is an [open source](https://github.com/bootstrap-zh-cn/bootstrap-zh-cn.github.io) Chinese Simplified translation which is more pure than [another one](https://code.z01.com/v4/).

### CODE REVIEW

**Comment by MrWillCom** [comment]
Also, can we start translating v5's docs? If we can, which branch should we start from?

**Review by mdo — APPROVED** [review]

**Comment by mdo** [comment]
> Also, can we start translating v5's docs? If we can, which branch should we start from?

I'd wait on that for at least the beta release.

**Comment by XhmikosR** [comment]
@MrWillCom please rebase your branch and make sure the check to allow edits from maintainers is ticked in the future.

**Comment by MrWillCom** [comment]
> @MrWillCom please rebase your branch and make sure the check to allow edits from maintainers is ticked in the future.

I didn't find the checkbox of "Allow edits from maintainers" even I've read [Allowing changes to a pull request branch created from a fork - GitHub Docs](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork). So how to allow it?

**Comment by XhmikosR** [comment]
Please just rebase your fork yourself so that we can proceed with this. If you need help consult [GitHub's article](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork).

**Comment by MrWillCom** [comment]
> Please just rebase your fork yourself so that we can proceed with this. If you need help consult [GitHub's article](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork).

I followed the article, commit https://github.com/twbs/bootstrap/pull/31540/commits/0f8d69ab98881622beab457738c1595a85769926 .

**Comment by MrWillCom** [comment]
@XhmikosR It looks like that [getbootstrap.com](https://getbootstrap.com/docs/4.5/about/translations/) is not updated currently, maybe it needs a rebuild.

**Comment by XhmikosR** [comment]
The live website will be updated when we make a new release.

**Comment by MrWillCom** [comment]
> The live website will be updated when we make a new release.

Okay, thanks a lot. 😀

**Pull request merged**
