### PR TITLE
Add decodeURI to anchor hashes

### LINKED ISSUE #38367: Scrollspy and French anchor links
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Scrollspy behavior has changed between the v5.1 and the v5.2 regarding the handling of characters in anchor links/ids.
It was possible before to do the following:

```html
<nav id="navbar-example2" class="navbar bg-body-tertiary px-3 mb-3 rounded-2">
    <a class="navbar-brand" href="#">Navbar</a>
    <ul class="nav nav-pills">
      <!-- -->
      <li class="nav-item">
        <a class="nav-link" href="#présentation">Présentation</a>
      </li>
      <!-- -->
   </ul>
</nav>
<div class="scrollspy-example bg-body-tertiary p-3 rounded-2" data-bs-spy="scroll" data-bs-target="#navbar-example2" data-bs-root-margin="0px 0px -40%" data-bs-smooth-scroll="true" tabindex="0">
  <!-- -->
  <h4 id="présentation">Second heading</h4>
  <!-- -->
</div>
```

Now, using an id like "présentation" throws an error in the console:

> Uncaught DOMException: Element.querySelector: '#pr%C3%A9sentation' is not a valid selector

It is linked to https://github.com/twbs/bootstrap/issues/37545 and other issues in the past. Different opinions have been raised in comments on these issues and maybe not have been studied because the issues were already closed. Maybe we can reconsider it and provide a final answer based on more recent data.

I don't know what they use but for example, Wikipedia has such ids when the page is in French (e.g. https://fr.wikipedia.org/wiki/Bootstrap_(framework)#G%C3%A9n%C3%A9ralit%C3%A9s).

https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier was mentioned as an answer but is more linked to CSS isn't it? But if I create the following, its works:

```css
#présentation {
  color: red
}
```

https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute seems more permissive and more linked to this issue considering only HTML.

---

/cc @Lausselloic

### Reduced test cases

- In v5.1: https://codepen.io/julien-deramond/pen/ExeJWEo
- In v5.2: https://codepen.io/julien-deramond/pen/OJoGpOK

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v5.2

### PR DESCRIPTION
**Pull request by alemendoza-v**
### Description

Added the `decodeURI()` function to the anchor hashes inside the `js/src/scrollspy.js` file to allow anchors to have special characters.

### Motivation & Context

The `Scrollspy` component was having some issues when using words with special characters like "présentation"  as html ids.

### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- N/A New feature (non-breaking change which adds functionality)
- N/A Refactoring (non-breaking change)
- N/A Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- N/A My change introduces changes to the documentation
- N/A I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

None

### Related issues

Fixes #38367

### CODE REVIEW

**Comment by alemendoza-v** [comment]
@XhmikosR Hello, are there any guidelines for testing? I'm new to contributing and not sure how I should test my changes.

**Comment by alemendoza-v** [comment]
Hello, I added a unit test and a visual test, could someone review please?

**Comment by XhmikosR** [comment]
Yeah, this doesn't work.

Please make sure you test everything locally.

**Comment by alemendoza-v** [comment]
@XhmikosR could you tell me why it does not work please?

**Comment by XhmikosR** [comment]
Tests failed hence why I said you should test everything locally before making a PR :) https://github.com/twbs/bootstrap/actions/runs/4766874349/jobs/8474441900

**Comment by alemendoza-v** [comment]
@XhmikosR Hello, I'm running the tests on vscode using the commands but the errors are not showing up, how can  I see when the tests fail?

**Comment by salihozkara** [comment]
@XhmikosR I have a similar problem. And for me, this change solves the problem. Can you add the change here to the main branch?

**Pull request closed without merging**
