### PR TITLE
Add spinners for Bootstrap

### PR DESCRIPTION
**Pull request by LKay**
Adds simple, lightweight spinners to Bootstrap 4 as it was mentioned on nice to have feature list (#17021).

Includes 4 types of spinners, supports bootstrap colors, sizes and different positioning.

Works out of the box for new browsers. To support IE9, small fallback plugin is included which inserts special element instead of using `:before` element and basic animation for rotating the element.

Some basic tests are also included.

Can be easily extended with new spinner variations if they are compatible with single element CSS spinner such as [Single Element CSS Spinners](http://projects.lukehaas.me/css-loaders/) or [Loaders Kit](http://cssdeck.com/labs/loaderskit)

### CODE REVIEW

**Comment by cvrebert** [comment]
(Note: Will need squashing when merging)

**Comment by Izopi4a** [comment]
niiiice +1

**Comment by AntonTrollback** [comment]
+1

**Comment by cvrebert** [comment]
CC: @mdo for review

**Comment by arg** [comment]
+1

**Comment by ThorinDev** [comment]
+1

**Comment by LKay** [comment]
@mdo It's been while but since IE9 support is officially dropped, I updated the PR and removed all fallbacks as CSS animations are supported natively in IE10+. 

Anything left before it could be merged in and included in v4?

**Comment by Johann-S** [comment]
Hi @LKay you have build error see : https://travis-ci.org/twbs/bootstrap/jobs/218307896#L236

**Comment by januszm** [comment]
:+1:

**Comment by mdo** [comment]
Coming in #22960 with v4.1.

**Pull request closed without merging**
