### PR TITLE
Update popper.js to 1.12.9.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by Johann-S** [comment]
Why not using the last release [1.12.9](https://github.com/FezVrasta/popper.js/releases/tag/v1.12.9) ? Which fix critical bugs on Popper.js

**Comment by XhmikosR** [comment]
Because I wasn't aware there is one.

I'll try that later. Still it would be pretty useful if the license header
included the version.

**Comment by Johann-S** [comment]
:laughing: we made the same commit

**Comment by XhmikosR** [comment]
@Johann-S: 1.12.9 seems to work fine.

**Comment by Johann-S** [comment]
Can you remove `//# sourceMappingURL=popper.min.js.map` on `popper.min.js`

**Comment by XhmikosR** [comment]
Why remove it? We don't care about it.

**Comment by Johann-S** [comment]
Because they are few months you asked me to remove it because it produce errors on our docs

**Comment by XhmikosR** [comment]
I don't even remember about it, but since it's a third-party file, it better stay like that.

**Comment by Johann-S** [comment]
You can see currently we removed it : http://getbootstrap.com/assets/js/vendor/popper.min.js

**Comment by XhmikosR** [comment]
Sure, but I don't want having to do remember to do that.

**Comment by Johann-S** [comment]
Ok that's fine for me :+1:

**Comment by XhmikosR** [comment]
Then approve :P

**Review by Johann-S — APPROVED** [review]

**Pull request merged**
