### PR TITLE
Color input validation icon

### LINKED ISSUE #34151: form-control-color should not use validation icons
ugly:

### PR DESCRIPTION
**Pull request by ffoodd**
Fixes #34151

This might not be ideal but should not break things. Any thoughts?

--- 
Screenshot: 
image

### CODE REVIEW

**Review by unrealapex — APPROVED** [review]

**Comment by mdo** [comment]
The box-sizing change, if someone gives this a fixed height, that'd cause an issue, right? Anyway to avoid that change?

**Comment by ffoodd** [comment]
The only way around I can think of is adjusting the `width` in validation styles, to account for the extended padding.

Does this sound better to you?

**Comment by alecpl** [comment]
There is a 3rd option. Get rid of `max-width` and handle color inputs as any other input. Imo, that's the best option.

**Comment by ffoodd** [comment]
Indeed, but that may break things too if one accounted for this small width already.

**Comment by mdo** [comment]
> The only way around I can think of is adjusting the width in validation styles, to account for the extended padding.

Yeah, I think that sounds the best at this point. We can maybe revisit for v6 then?

**Comment by ffoodd** [comment]
@mdo antoher call for this, by simply handling `width` to account for `padding`.

**Comment by ffoodd** [comment]
Up on this, I think it's pretty safe :)

**Review by mdo — APPROVED** [review]

**Pull request merged**
