### PR TITLE
Use box shadows instead of linear gradients to colorize tables

### LINKED ISSUE #32266: Linear gradients slow down (large) table rendering by a lot
This concerns the `table` styles in BS5 alpha 3. Apparently due to the recently introduced use of `linear-gradient` the rendering of my (rather large) tables becomes very slow. My tests have been done on a Macbook Pro i5 with Intel Iris Graphics 6100.

When including a very large table in a document, after scrolling down, the rendering of the next part of the document takes as much as a second. The screen is actually white while waiting for the renderer to "catch up". This does **not** happen when the `linear-gradient` backgrounds are disabled. However, in Bootstrap 5, disabling those will also remove visible striping, for example.

**--> Demonstration**

Below is a Codepen with a large table that clearly shows this problem in Safari 14.0.1 (16610.2.11.51.8) and Chrome 87.0.4280.67 on Mac Intel. In Firefox 83.0, the problem is less noticeable but still apparent.

https://codepen.io/stgm/pen/poEoryZ

You can uncomment the style in this Codepen to override the use of the linear-gradient and appreciate the difference. It may be easier to see the problem if you enable the "Full Page View", because you can then scroll faster and see how this seems to make the problem even worse.

**--> Relevant links**

Origin of the linear-gradient idea: https://github.com/twbs/bootstrap/issues/29244
First jab at integrating these: https://github.com/twbs/bootstrap/pull/30342
Final PR containing the linear gradients for tables: https://github.com/twbs/bootstrap/pull/30466

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Closes https://github.com/twbs/bootstrap/issues/32266

Before: https://codepen.io/MartijnCuppens/pen/oNzxwZY
After: https://codepen.io/MartijnCuppens/pen/PoGNjpQ

Scroll fast to see the effect. Effect most noticeable in Safari & Chrome.

### CODE REVIEW

**Comment by septatrix** [comment]
For me this only improves the experience marginally (Samsung Galaxy A51, Chrome 86) but the white unrendered sections are still very noticeable.

**Comment by septatrix** [comment]
I may be missing something but why is it not possible to just set the `--bs-table-bg` as the background on the `<table>` element and just have the child elements use `--bs-table-accent-bg` as the normal background?

**Comment by MartijnCuppens** [comment]
> I may be missing something but why is it not possible to just set the --bs-table-bg as the background on the `<table>` element and just have the child elements use --bs-table-accent-bg as the normal background?


We use this technique so we can mix the striped/active/hover tables with our table variants https://getbootstrap.com/docs/5.0/content/tables/#variants

**Comment by septatrix** [comment]
Okay I did not even realize this is now possible with v5, that sounds great. I guess some `:before`/`:after` trickery was already considered as does not work for some reason?

**Review by mdo — APPROVED** [review]
Very noticeable difference on Safari. Wondering if we need a full `9999px` or if we could get away with something smaller?

**Comment by MartijnCuppens** [comment]
> Very noticeable difference on `Safari`. Wondering if we need a full `9999px` or if we could get away with something smaller?

I used `9999px` because it was also used in our CSS for `.modal-scrollbar-measure`. It 'll always be some kind of magic number and the lower we go, the more chance we run into issues.

**Comment by ihorzenich** [comment]
> > I may be missing something but why is it not possible to just set the --bs-table-bg as the background on the `<table>` element and just have the child elements use --bs-table-accent-bg as the normal background?
> 
> We use this technique so we can mix the striped/active/hover tables with our table variants https://getbootstrap.com/docs/5.0/content/tables/#variants

Wouldn't the same visual effect be achieved by using these variables directly in `background-color` instead?
I'm wondering why `box-shadow` is necessary in this case.

I tested it by simply replacing
`background-color: var(--bs-table-bg)`;
with
`background-color: var(--bs-table-bg-state, var(--bs-table-bg-type, var(--bs-table-accent-bg)))`;
and it seemed to work as expected.

**Pull request merged**
