### PR TITLE
Round results from gutter division to prevent decimal margins and padding

### LINKED ISSUE #16281: Grid gutter issue with uneven pixel values
I have a layout with a 1px grid gutter; the columns are colored boxes. 

Bootstrap’s grid translates this in -0.5px margins along with 0.5px paddings. That seems to work, actually (and I have tested it in some browsers), because the bowsers seem to generally decide if they tilt the columns to the left or to the right, to finally feature one full pixel gap. 

But this feels overall accidentally, and I’m worried that that this might break on day, at least when it comes to sub pixel rendering … 

So I’m asking myself if it wouldn’t be a good idea to enhance the grid mixin with a logic for uneven values, that produces regardeless just full pixel values; in my case 1px left, 0px right, for example. 

Alternatively maybe optional variables for left-/right-gutter-part would be fine. 

Thanks a lot, 
7R5N

### PR DESCRIPTION
**Pull request by thomasphorton**
Fixes #16281

left rounds up, right rounds down. should keep everything playing nice.

### CODE REVIEW

**Comment by mdo** [comment]
Nice, I think this should be good to go. The default code doesn't change obviously, and it should handle that half pixel problem nicely.

**Comment by kminek** [comment]
this change break computing for non-px values. suppose i would like to use only grids from bs and set @grid-gutter-width: 3em - i would expect 1.5em value should be set on both sides - currently it's not :(

**Comment by thomasphorton** [comment]
What behavior do you see? Does one go to 1 and the other 2?

That's a big oversight on my part. If you give me some more information I'll look into a fix.

**Comment by zacechola** [comment]
Open up a new issue, @kminek.

**Comment by mdo** [comment]
Yeah, that's a valid concern. If that's the case, I'm actually in favor of removing any and all rounding for the grid. We've gotten by for nearly two years without it, we can stick it out until v4 :).

**Comment by kminek** [comment]
i would also remove rounding and take approach suggested in #16281 - that is to introduce optional variables for left-/right-gutter-part :)

**Pull request merged**
