### PR TITLE
fix memory leak in tooltip $element

### LINKED ISSUE #17973: Tooltip causing memory leak
The destroy method in Tooltip sets all the DOM references to `null` except `$element`. This causes DOM nodes to leak even after the destroy method is called.

Nullifying this variable removes the leak.

### PR DESCRIPTION
**Pull request by gregsheremeta**
Fixes #17973

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: a9efd66b8e5d2f930b4e96a0e7dd54963d0e5131
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/120151148

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
@twbs-savage Retry

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: a9efd66b8e5d2f930b4e96a0e7dd54963d0e5131
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/120165154

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by XhmikosR** [comment]
@cvrebert: I think this looks good. Can we merge or is there something else?

**Comment by cvrebert** [comment]
@XhmikosR I just wasn't sure (without taking time to trace thru the flow) what situation makes the `if` necessary.

**Comment by gregsheremeta** [comment]
I'm not sure about the "if" either. The fix seemed to work without that extra "if" in our project, but according to #16451, some people need the extra "if". So I added it in there. It's just extra safety -- I see no harm in leaving it.

**Comment by cvrebert** [comment]
Guess we should merge and add a TODO to revisit the "if" later.

**Comment by XhmikosR** [comment]
@gregsheremeta: can you add the comment?

**Comment by cvrebert** [comment]
Merged as f01f3e5f34c1acdd802cc61ea9aae9f9b14169c3. (Rebased to add the comment in.)

**Comment by cvrebert** [comment]
@gregsheremeta Thanks!

**Comment by cvrebert** [comment]
Bookkeeping note: No corresponding patch appears to be required for v4, since it already nullifies the element instance variable upon tooltip destruction: https://github.com/twbs/bootstrap/blob/14c7ba95f97d853ef653893abfe530a919a1ed24/js/src/tooltip.js#L237

**Comment by kntmrkm** [comment]
When release v3.3.7?

**Comment by cvrebert** [comment]
Some time in the next few weeks, most likely. As always, no absolute guarantee though.

**Comment by Herst** [comment]
The TODO comment is part of the release now.

**Comment by cvrebert** [comment]
That's fine.

**Comment by natalan** [comment]
It looks like this PR is a root cause for https://github.com/twbs/bootstrap/issues/20511

**Comment by gregsheremeta** [comment]
Probably want to add that "if" back in then

**Pull request closed without merging**
