### PR TITLE
Added css + html for back to top button in nav in documentation

### PR DESCRIPTION
**Pull request by edanbarak**
Fix for #22604

### CODE REVIEW

**Comment by patrickhlauke** [comment]
could you remove the minified css and the map from the PR? we generally just want the raw changes to templates / scss

**Comment by edanbarak** [comment]
@patrickhlauke I have rebased the commit and removed the minified files.

**Comment by patrickhlauke** [comment]
leaving it up to @mdo to decide if this gets merged. personally, i'm not a massive fan of back to top links as users have many more ways to do it ("Home" key on keyboard, scrollbar, tapping on system bar on mobile, etc)

**Comment by Johann-S** [comment]
Personally I like "back to top" button and I continue to look for this button on v4 documentation because they are one on v3 😆

**Comment by mdo** [comment]
Thanks, but we'll pass on the back to top link. I have some design ideas in mind for the docs to help.

**Pull request closed without merging**
