### PR TITLE
Collapse - Fix check to not prevent event for input and textarea

### PR DESCRIPTION
**Pull request by Johann-S**
Thank you @git-marijus

Close : #22296

### CODE REVIEW

**Comment by mdo** [comment]
Does the test need updating per https://github.com/twbs/bootstrap/issues/22296#issuecomment-289909869?

**Comment by Johann-S** [comment]
I improved my unit test

**Comment by vanduynslagerp** [comment]
In you new unit test you just added `assert.ok(e.isDefaultPrevented() === false)` that test if the `shown.bs.collapse` event is prevented. That will never be prevented.

Your modification in the code prevent the event from `Event.CLICK_DATA_API`.
They are not the same event. Your test still doesn't do what you intend.

You should test if the `<div id="collapsediv1"/>` has the class `show` instead, to make sure that the click on the checkbox did expand the collapsible area

**Comment by Johann-S** [comment]
Thank you @vanduynslagerp 👍 Time for me to sleep I make to much mistakes tonight

**Pull request merged**
