### PR TITLE
v4 docs Collapse trigger using anchor tags should have `role="button"`

### PR DESCRIPTION
**Pull request by pat270**

### CODE REVIEW

**Review by patrickhlauke — APPROVED** [review]

**Comment by patrickhlauke** [comment]
Good spot. May also be worth adding something to the accessibility bit later on in that page?

**Comment by patrickhlauke** [comment]
Good spot. May also be worth adding something to the accessibility bit later on in that page?

**Comment by pat270** [comment]
I added a little blurb to the Accessibility section. I wasn't sure if the role button thing was an oversight, Thanks!

**Comment by patrickhlauke** [comment]
@pat270 lovely, thank you

**Pull request merged**
