### PR TITLE
Add shrink-to-fit viewport directive

### PR DESCRIPTION
**Pull request by patrickhlauke**
Fixes potential problems with iOS9's new viewport behavior - see for
instance https://forums.developer.apple.com/thread/13510

### CODE REVIEW

**Comment by cvrebert** [comment]
@patrickhlauke What about the template in the Getting Started docs?

**Comment by cvrebert** [comment]
See also https://twitter.com/awfulben/status/646382994496729088

**Comment by Quy** [comment]
and under [Responsive meta tag](http://v4-alpha.getbootstrap.com/getting-started/introduction/#responsive-meta-tag)?

**Comment by patrickhlauke** [comment]
@Quy ah, good point, that one slipped me by.  Will add tonight.

**Comment by patrickhlauke** [comment]
@Quy done. thanks for spotting that.

**Pull request merged**
