### PR TITLE
remove empty sass if directives

### PR DESCRIPTION
**Pull request by neilhem**

### CODE REVIEW

**Comment by cvrebert** [comment]
Might've been a deliberate stylistic choice.
CC: @mdo

**Comment by roura356a** [comment]
If doesn't compile I don't see the problem of having the empty if for future additions.

**Comment by vsn4ik** [comment]
https://github.com/twbs/bootstrap/pull/17589#issuecomment-142439423

**Comment by mdo** [comment]
:shipit:

**Pull request merged**
