### PR TITLE
Improve partial caching logic

### PR DESCRIPTION
**Pull request by regisphilibert**
More partials are cached by adding "variations" arguments when possible.

See comments in files.

### CODE REVIEW

**Comment by regisphilibert** [comment]
@XhmikosR I ran local tests to make sure this was proper, but not being too familiar with the project, I will let you run the production builds etc... to make sure everything is good.

**Comment by XhmikosR** [comment]
Thanks @regisphilibert for the patch :)

Now, looking at it, it doesn't appear we save a lot. I'm afraid this might cause issues with not so experienced Hugo people, and I'm wondering what's your opinion about maybe not using parialCached at all, after all? If the gains were big, I wouldn't even discuss it, but being that they are not big, maybe this will cause us more issues in the future?

**Comment by regisphilibert** [comment]
Yes a new comers would have to be familiar with the current caching logic. I would not recommend going through that process if there's no gain. But if it ever comes to really needing this, you could always get back to that code and review.

**Comment by XhmikosR** [comment]
Let me merge this to my branch so that we have everything is one place in case we need this in the future.

Thanks again for the patch. I hope this doesn't put you off to help us out more :)

**Pull request merged**
