### PR TITLE
Update anchor.js to v0.4.0

### PR DESCRIPTION
**Pull request by coliff**
Update anchor.js to latest version
https://raw.githubusercontent.com/bryanbraun/anchorjs/master/anchor.js

### CODE REVIEW

**Comment by cvrebert** [comment]
CC: @XhmikosR

**Comment by XhmikosR** [comment]
Definitely against this... We need to move the custom CSS out of anchor.css
and update that too...

**Comment by mdo** [comment]
What are you against @XhmikosR?

**Comment by XhmikosR** [comment]
Like I've said many times :p we need to move the custom code you have added
in anchor.css to our docs CSS. This is a half update due to that.

Secondly, v1.0.0 should be out soon if not already (I haven't checked from
here) which changes some stuff and includes bug fixes and improvements like
excluding selectors.

Anyway, as long as we move the custom code outside of the third party file
I can have a look myself. (If you remember I had a branch for this but
ditched it)

**Comment by kkirsche** [comment]
It's not yet @XhmikosR — RE: bryanbraun/anchorjs#34

**Comment by bryanbraun** [comment]
Anchor.js maintainer here. I released 1.0.0 yesterday, and one of the big improvements is that it makes `anchor.css` obsolete by pulling the most common adjustments into config options. 

@XhmikosR, I've submitted a separate PR which does the update (similar to this one), but also moves the styles out of `anchor.css`. See: https://github.com/twbs/bootstrap/pull/16488

**Comment by XhmikosR** [comment]
Thanks @bryanbraun! Closing in favor of #16488.

**Pull request closed without merging**
