### PR TITLE
Add 404 page (for Hugo)

### LINKED ISSUE #28319: Custom 404 Page for Docs
Currently the 404 page is the default GitHub Pages one. It'd be nice to have a custom Bootstrap branded one with links in header and footer so any folks reaching the page can quickly get to where they want to go on the site. Jekyll has support for this: https://jekyllrb.com/tutorials/custom-404-page/

### PR DESCRIPTION
**Pull request by coliff**
Fixes #28319

### CODE REVIEW

**Comment by XhmikosR** [comment]
Yeah this needs more work.

1. the output should be 404.html
2. the layout that's used now makes no sense to me
3. Just showing that a page isn't found, isn't very useful IMO. There should be a back to home button and ideally the search.

For the third thing, don't worry about it, we can tweak it later.

**Comment by XhmikosR** [comment]
@bardiharborow @MartijnCuppens thoughts? https://deploy-preview-28332--twbs-bootstrap.netlify.com/404.html

I will try fixing the 404 layout later/tomorrow but I think we need to improve the page, maybe add search or at least a button to the homepage.

**Comment by MartijnCuppens** [comment]
I pushed the footer to the bottom of the page, it was weird having some white space below the footer.

**Comment by XhmikosR** [comment]
How about content :)

BTW see https://github.com/opencollective/opencollective/issues/1764

**Review by bardiharborow — APPROVED** [review]
LGTM, there's probably some room to be more creative but no need to delay merging this.

**Comment by coliff** [comment]
Thanks for finishing the work on this PR @XhmikosR  - looks good - and a big improvement over the default GitHub Pages 404. The footer looks much better - thanks @MartijnCuppens !

I was thinking it might not be a good idea to include a search as a user might have been looking for a Bootstrap v3 class in which case the search (if it was search for v4 may not show results)... and if it were to combine search results for all versions it could get confusing.

**Pull request merged**
