### PR TITLE
Removal of one of the most iconic components of Bootstrap: the jumbotron

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Ditch the jumbotron in favour of utility classes.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Let's wait a bit until I optimize the modified images a bit more.

**Comment by XhmikosR** [comment]
On a side note, `bg-light` is quite lighter than what we used.

**Review by ysds — APPROVED** [review]

**Comment by MartijnCuppens** [comment]
> On a side note, bg-light is quite lighter than what we used.

I've updated the screenshots because of this. We 'll probably have more grey tints when #28268 is finished (I've added it as a to do).

@XhmikosR, did you optimize the images with your latest push?

**Comment by XhmikosR** [comment]
Yeah, everything is good to go from my side.

**Comment by mbejda** [comment]
Removing the most iconic component.  :(

**Pull request merged**
