### PR TITLE
Assorted Event handler patches

### PR DESCRIPTION
**Pull request by GeoSot**
mostly renaming, to help my eyes, follow the logic and some minor refactoring to separate some logic

### CODE REVIEW

**Comment by GeoSot** [comment]
@julien-deramond @louismaximepiton does these changes make sense to you guys? 😷

**Comment by julien-deramond** [comment]
> @julien-deramond @louismaximepiton does these changes make sense to you guys? mask

I haven't tested the minor refactoring but the new naming allows a better understanding.
Especially for me:
* `getEvent` → `getElementEvents` that highlights when you read it the fact that you get multiple events
* `delegation` → `isDelegated` is more obvious as well
* I know some developers don't like the fact to have a function used only one time but IMO `hydrateObj` makes the code more readable here

Regarding callable I don't know well this JS file so I don't have an opinion on this. I just like that it avoids having `originalHandler` + `handler`.

**Comment by louismaximepiton** [comment]
> @julien-deramond @louismaximepiton does these changes make sense to you guys? 😷

I haven't tested too, but the changes seems good and understandable to me.

Regarding the `hydrateObj` function, I was wondering if this function could be in the utils file instead of a standalone one here ?

**Comment by GeoSot** [comment]
> Regarding the hydrateObj function, I was wondering if this function could be in the utils file instead of a standalone one here ?

Thank you, I 'll keep it in mind, for later usage . For now, I didn't find any other place that needs this functionality

**Review by mdo — APPROVED** [review]

**Pull request merged**
