### PR TITLE
Fixed incorrect instructions: "Press ⌘ to copy"

### PR DESCRIPTION
**Pull request by tjkohli**
Changed to "Press ⌘C to copy"

### CODE REVIEW

**Comment by wolfy1339** [comment]
According to http://www.fileformat.info/info/unicode/char/2318C/index.htm this PR would be wrong

**Comment by tjkohli** [comment]
@wolfy1339 Have you tried the code in your browser? The last C is the letter "C" and not part of the character. u2318 renders the command icon (⌘)

**Comment by wolfy1339** [comment]
Yes I have, but It can be mis-interpreted as another Unicode glyph. So it would be better to use string concatenation to avoid any potential bugs when using any other font than the ones in default Bootstrap

**Comment by Kovah** [comment]
Why not simply using `\u2318 + C` = ⌘ + C?

**Comment by tjkohli** [comment]
@Kovah I do not recommend that as Apple stylizes shortcuts without a '+' sign, and adding a '+' could possibly confuse users. There is no '+' action between the ⌘ and the C, so ⌘C makes the most sense.

**Comment by tjkohli** [comment]
I updated it to concatenate the two pieces. Should this work now?

**Comment by tomlutzenberger** [comment]
I'd recommend `'Press \u2318 + C to copy'`(remove those single-quotes).

**Comment by tjkohli** [comment]
@tomlutzenberger I don't recommend that, at least for Mac users, who this PR applies to.

> I do not recommend that as Apple stylizes shortcuts without a '+' sign, and adding a '+' could possibly confuse users. There is no '+' action between the ⌘ and the C, so ⌘C makes the most sense.

screen shot 2016-09-08 at 10 32 54 am

**Comment by tomlutzenberger** [comment]
Hm okay...
In that case I would do the following:
```javascript
      const modifierKey = /Mac/i.test(navigator.userAgent) ? '\u2318' : 'Ctrl-';
      let fallbackMsg = 'Press ' + modifierKey + 'C to copy';
```

That way you dodge unnecessary string concatenation AND prevent duplicate code/text.
Note that I also changed `var` to `let`.

**Comment by tomlutzenberger** [comment]
Oh yes, I forgot. They have this "no-semicolon-on-line-endings"-Rule.
After removing those, it should be fine @tjkohli

**Comment by tjkohli** [comment]
@tomlutzenberger Done. Thanks dude!

**Review by bardiharborow — APPROVED** [review]

**Comment by tomlutzenberger** [comment]
Why do the checks still fail?
Is there a possibility to restart them?

//cc @cvrebert

**Comment by bardiharborow** [comment]
@tomlutzenberger just `git commit --amend` the last commit and `git push -f` the branch again.

**Comment by bardiharborow** [comment]
@tjkohli could you rebase and squash these commits, and force push the branch again. This will also trigger Travis to rebuild this PR.

**Comment by mdo** [comment]
Merged this with #21236, so closing. Thanks!

**Pull request closed without merging**
