### PR TITLE
Add new rounded sizes classes

### LINKED ISSUE #27934: New utility classes: `rounded-lg` and `rounded-sm`
Would be nice to have utility classes like `rounded-lg` and `rounded-sm` as you already have SCSS variables for `border-radius-lg` and `border-radius-sm`.

### PR DESCRIPTION
**Pull request by jt143**
- Add `.rounded-sm` and `.rounded-lg`

Fixes #27934 

Demo preview: https://deploy-preview-28011--twbs-bootstrap4.netlify.com/docs/4.2/utilities/borders/#sizes

### CODE REVIEW

**Review by XhmikosR — COMMENTED** [review]
Please do not touch any dist files.

**Comment by XhmikosR** [comment]
Also, there's a good reason for using `!important` in utilities.

**Comment by jt143** [comment]
updated!

**Comment by MartijnCuppens** [comment]
Thanks for the PR, @jt143!

These classes have `!important` because they are utility classes. The classes just do one thing and shouldn't depend on other classes.

Therefor I would go for `.rounded-sm` classes instead of `.rounded.rounded-sm` classes (same for `.rounded-lg`). And also `.rounded-top-sm` classes instead of `.rounded-top.rounded-sm` (and same behaviour for other variants).

**Review by mdo — CHANGES_REQUESTED** [review]
We wouldn't chain these new classes to the side classes like this. Utilities should never ben extended, chained, or modified. For now, I'd suggest we do `.rounded-sm` and `.rounded-lg` only.

**Comment by jt143** [comment]
Hi @mdo and @MartijnCuppens 
Thank you for your reviews! I have updated as requested.

**Review by MartijnCuppens — APPROVED** [review]
LGTM :+1:

**Review by mdo — APPROVED** [review]
Looks good!

**Pull request merged**
