### PR TITLE
Docs: Add captions above progress bars

### PR DESCRIPTION
**Pull request by cvrebert**
Refs #17264. Gratuitous screenshot:

CC: @mdo for review
CC: @patrickhlauke to ensure whether `aria-describedby` is sufficient to make the captions accessible

### CODE REVIEW

**Comment by mdo** [comment]
I'd rather we didn't show this in all the examples and instead offer an isolated example with supporting text above or below using the same method.

**Comment by cvrebert** [comment]
I somewhat disagree on copy-paste-ability grounds, but okay, changed.

**Comment by mdo** [comment]
Biggest reason is that I can see folks wanting to do their own supporting progress text. Some folks want it above, below, right, or left. Depends entirely on the overall design.

**Comment by cvrebert** [comment]
@mdo LGTY?

**Pull request merged**
