### PR TITLE
Fix tooltip positioning with regards to viewports

### PR DESCRIPTION
**Pull request by ericmartel**
The getPosition function was simplified with a new function,
getViewportBounds, was added to specifically
tackle the cases where we’re looking for the viewport bounds.

‘absolute’ and ‘fixed’ tooltips are now matched against the screen
where other ones are made to fit inside the viewport element.

### CODE REVIEW

**Comment by cvrebert** [comment]
@twbs-savage Retry

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: bc9a3ad829a05b330ac66161ba4b62b860868c0b
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/45925623

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
@ericmartel I'll just squash the history before merging this. Could you add a commit to fix [the rounding problem](https://github.com/twbs/bootstrap/pull/14226#discussion_r20701400) and address the other minor comments I made?

**Comment by ericmartel** [comment]
@cvrebert sorry I think I missed this comment, let me know if I can do anything else to help!

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 388064a84ed771e47959cfc77b2f47472ab4c56f
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/45946437

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by ericmartel** [comment]
@cvrebert there seems to be problems with the tests, I doubt it has anything to do with my changelist though :/

Could not connect to Sauce Labs API: Error: read ECONNRESET

**Comment by cvrebert** [comment]
@twbs-savage Retry

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 388064a84ed771e47959cfc77b2f47472ab4c56f
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/45960000

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by ericmartel** [comment]
@cvrebert thanks for the retry, is there a way to get more details than:

   13972015-01-05 15:53:17:344 - info: [IOS_SYSLOG_ROW ] Jan 5 07:53:17 itako36176 assertiond[631]: assertion failed: 13F34 12B411: assertiond + 11523 [3F572A0B-7E12-378D-AFEE-EA491BAF2C36]: 0x1

is there a way to extract which assert failed?

Thank you very much, I'm sorry if I'm being a burden

**Comment by cvrebert** [comment]
Should be in the screencast on fe963a60d91d48a999a3a8e750010755

**Comment by ericmartel** [comment]
@cvrebert the error seems to come from affix.js, possibly from my bad merge?

**Pull request closed without merging**
