### PR TITLE
Change property from background to background-image

### PR DESCRIPTION
**Pull request by itxchandan**
For Gradient, We have to use the background-image instead of only background.

### CODE REVIEW

**Review by MartijnCuppens — DISMISSED** [review]
Correct, thanks!

**Comment by XhmikosR** [comment]
Shouldn't we backport this?

**Comment by XhmikosR** [comment]
Yeah, but it's always better to be explicit than using the shorthand which resets many of the other properties. We actually try to do this across the codebase.

/CC @mdo

**Review by mdo — APPROVED** [review]
Correct, we always strive to be explicit in our CSS properties and avoid unnecessary shorthand notations.

**Pull request merged**
