### PR TITLE
Auto positioning of tooltip

### PR DESCRIPTION
**Pull request by ghost**
This patch changes the positioning of the tooltip when there is no room for the tooptip in the position it would normally show.

As discussed here: https://github.com/twitter/bootstrap/issues/7399

### CODE REVIEW

**Comment by niftylettuce** [comment]
@nonumber did you ever get a solid solution for this or some plug in created?

**Comment by nonumber** [comment]
I have written and used this extra script for some time now:
https://gist.github.com/nonumber/54d9edff3730ed7d25c1

**Comment by niftylettuce** [comment]
Thanks @nonumber !

**Comment by niftylettuce** [comment]
@nonumber I ran that file through JSHint and got the following errors, can you correct it?

```
/Users/nexus/test.js: line 0, col 0, ES5 option is now set per default
/Users/nexus/test.js: line 17, col 53, Expected '===' and instead saw '=='.
/Users/nexus/test.js: line 23, col 100, Expected an assignment or function call and instead saw an expression.
/Users/nexus/test.js: line 1, col 1, '$' is not defined.
/Users/nexus/test.js: line 2, col 11, '$' is not defined.
/Users/nexus/test.js: line 37, col 27, '$' is not defined.
/Users/nexus/test.js: line 38, col 45, '$' is not defined.
/Users/nexus/test.js: line 38, col 69, '$' is not defined.
/Users/nexus/test.js: line 39, col 28, '$' is not defined.
/Users/nexus/test.js: line 40, col 45, '$' is not defined.
/Users/nexus/test.js: line 40, col 70, '$' is not defined.
/Users/nexus/test.js: line 45, col 76, 'tooltips_fallback_position' is not defined.
/Users/nexus/test.js: line 50, col 73, 'tooltips_fallback_position' is not defined.
/Users/nexus/test.js: line 55, col 75, 'tooltips_fallback_position' is not defined.
/Users/nexus/test.js: line 60, col 74, 'tooltips_fallback_position' is not defined.

15 errors
```

**Comment by nonumber** [comment]
That's because it uses jQuery.
Try now: https://gist.github.com/nonumber/54d9edff3730ed7d25c1

**Comment by joncjordan** [comment]
For each case, you may want to add $tip.addClass('top'); or $tip.addClass('left'); so that we can get the arrows displaying properly.

**Comment by nonumber** [comment]
No need. That is already being done inside the `applyPlacement`.

**Comment by akrohn** [comment]
Doesn't work for bootstrap 3.3.6? Error shown on console for bootstrap.js.

Is there a solution that calculates the viewport of a canvas, when the popover is inside this canvas?

**Comment by cvrebert** [comment]
This feature has been addressed in Bootstrap v4.

**Pull request closed without merging**
