### PR TITLE
Close modal with keyboard=true & backdrop=static

### PR DESCRIPTION
**Pull request by mendozagioo**
This avoid the no close of modal with options:

```js
$('#my-modal').modal({
backdrop: 'static',
keyboard: true
})
```

fix issue: #29978 

Preview: <https://deploy-preview-29986--twbs-bootstrap.netlify.com/docs/4.3/components/modal/#static-backdrop>

### CODE REVIEW

**Review by Johann-S — APPROVED** [review]
Nice PR thanks @mendozagioo 👍

**Review by MartijnCuppens — APPROVED** [review]
Seems to work fine, thanks!

**Comment by XhmikosR** [comment]
Thanks for the patch @mendozagioo!

@Johann-S this will need to be manually backported to my v4-dev-xmr branch when you have some time :)

**Comment by XhmikosR** [comment]
@mendozagioo can you please backport this to my v4-dev-xmr branch?

**Comment by mendozagioo** [comment]
@XhmikosR, I added the appropriate tests

**Pull request merged**
