### PR TITLE
enable sourcemaps for bundles, include sourcemap for plugins in npm package

### PR DESCRIPTION
**Pull request by delagen**
related #19063

### CODE REVIEW

**Comment by XhmikosR** [comment]
@Delagen: why haven't you enabled sourcemaps for all JS files? Also, you should inline the source files to avoid issues like #19063.

@mdo @Johann-S: do you remember what was the reason for us not to include sourcemaps for JS files? It's like this from v3, so there must be some reasoning.

**Comment by Delagen** [comment]
@XhmikosR As i see, dist/js/bootstrap.bundle.js.map contains all sources, and others also.

**Comment by XhmikosR** [comment]
@Delagen: even so, I'll verify after you address the other issue I mentioned above.

**Comment by Delagen** [comment]
@XhmikosR Which issue? Include recompiled files in commit?

**Comment by XhmikosR** [comment]
@Delagen: you haven't enabled sourcemaps for all of our dist JS files.

**Comment by Delagen** [comment]
@XhmikosR enabled for minified files

**Review by XhmikosR — DISMISSED** [review]
We need `includeSources` and `url` for uglify-js. See https://github.com/mishoo/UglifyJS2#cli-source-map-options

Also, we need to do the same for `js-minify-docs`.

**Comment by Delagen** [comment]
@XhmikosR updated

**Comment by XhmikosR** [comment]
@Delagen: `url` isn't a boolean; you need to specify the filename.

**Comment by Delagen** [comment]
@XhmikosR it use basefilename with postfix by default

**Comment by XhmikosR** [comment]
Because the bundle already has sourcemaps specified in rollup step.

**Comment by XhmikosR** [comment]
@Johann-S: any ideas?

**Comment by Delagen** [comment]
@XhmikosR I understand. I don't use cli tools at all

**Comment by XhmikosR** [comment]
The sourcemaps still don't show the sources for me. I'll try to find why, otherwise if anyone has any ideas please comment here.

**Comment by XhmikosR** [comment]
Hmm, Chrome loads the source files fine. FF v57 beta doesn't here on Windows.

**Comment by Delagen** [comment]
@XhmikosR I think it's due base&root source map settings. Many `../` in source paths.

**Comment by XhmikosR** [comment]
@Delagen: that is with Chrome, right? Because with Chrome it works for me too but with FF doesn't work.

**Comment by Delagen** [comment]
@XhmikosR Also in Firefox 
image

**Comment by XhmikosR** [comment]
Ah, true. It's grouped under the `(no domain)` row.

All tight, all seems good now.

One last thing; should we include the map files for CSS too?

**Comment by XhmikosR** [comment]
Scratch my last comment.

**Review by XhmikosR — APPROVED** [review]

**Comment by Delagen** [comment]
@XhmikosR Yes. The problem is in base and root )

**Comment by XhmikosR** [comment]
@Delagen: do you have a fix for that?

**Comment by Delagen** [comment]
@XhmikosR I think rollup calculate paths relative to output, so I'll see how to tune this.

**Comment by Delagen** [comment]
@XhmikosR I think if files required from node_modules, all be fine due long path to it, and it points to real files. If we change source mapping, we broke package debugging, so I think we must keep it unchanged.

**Comment by XhmikosR** [comment]
@mdo: are you OK with adding sourcemaps for JS files? I know we didn't include them in v3, not sure what the reasons were.

They don't hurt being present plus we already include sourcemaps for CSS files.

**Comment by XhmikosR** [comment]
@mdo: ping

**Comment by mdo** [comment]
I've no preference on including or not—that's a better question for @Johann-S and @bardiharborow.

**Comment by Johann-S** [comment]
Not against it because we already provide source map for our minified CSS

**Comment by XhmikosR** [comment]
@mdo: when you do `npm run dist` next time, don't forget to include the new files.

**Pull request merged**
