### PR TITLE
Update devDependencies.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by Johann-S** [comment]
It's strange it's an update of our dependencies but they are no change in our `package.json` 🤔

**Comment by XhmikosR** [comment]
Not strange at all. That's how it works when using `^x.y.z`.

**Comment by tomscholz** [comment]
You are also correcting a typo. I think you should mention that somewhere. Otherwise looks good

**Comment by Johann-S** [comment]
Oh yes I forgot that thank you 👍

**Review by Johann-S — APPROVED** [review]

**Comment by XhmikosR** [comment]
@tomscholz: nah, not worth. Ideally the branch protection wouldn't be here and I could push directly like in the past. In that case I would do things differently but now I'm spending too much time on useless stuff like rebasing and waiting for tests to pass.

**Pull request merged**
