### PR TITLE
Remove potential false positive assertions

### PR DESCRIPTION
**Pull request by spicalous**
querySelector() returns null but `expect(document.querySelector('...')).toBeDefined()` checks that the value is not `undefined`. This can lead to false positive tests

### CODE REVIEW

**Comment by XhmikosR** [comment]
Can you check if there are more cases please?

**Comment by spicalous** [comment]
Added more cases I could find in unit tests for assertions against values that assigned from `.querySelector(...)`

**Comment by XhmikosR** [comment]
Thanks for the PR. There must be more instances, from a quick look. At least for `getInstance`.

**Comment by spicalous** [comment]
Added in https://github.com/twbs/bootstrap/pull/33288/commits/ee7e29104932573bd416f65f716e8c8863b59cbb :+1:

**Comment by spicalous** [comment]
Do we still want these changes?
 
I can rebase to resolve conflicts so it can be ready to merge, otherwise I will close this PR

**Comment by GeoSot** [comment]
@XhmikosR this might has to be in 5-stable

**Comment by spicalous** [comment]
Thanks @GeoSot please let me know when is the best time to rebase, it would be great if I can avoid doing it multiple times :+1:

**Comment by GeoSot** [comment]
in case of stable-5 is a good time to be rebased. But it doesn't depends by me and only. Thanks for your understanding

**Comment by spicalous** [comment]
I have rebased the changes against master

**Comment by XhmikosR** [comment]
Sorry for the delay @spicalous but we are only a few volunteers.

This PR can wait after 5.0.0, since it doesn't fix any bug. I hope you understand.

The same applies to your other PR you closed, you should reopen it until someone has a look at it.

**Comment by spicalous** [comment]
No problemos, just give me a shout when this needs to be rebased again :+1:

**Comment by GeoSot** [comment]
@spicalous  I saw about 17 more `deDefined` checks. If it is easy, please make a check on them too

**Comment by spicalous** [comment]
When looking through some of the matchers, I think it's not very clear when some return null or undefined

What do you guys think about using `toBeTruthy` / `toBeFalsy` ?

**Comment by XhmikosR** [comment]
toBeTruthy() coerces the values AFAICT so it's a little moot IMHO. Either we are always explicit or not :)

**Comment by spicalous** [comment]
@GeoSot I have updated more cases

Regarding these ones, I think they provide no value and can be removed. What do you guys think?
https://github.com/twbs/bootstrap/blob/f61a0218b36d915db80dc23635a9078e98e2e3e0/js/tests/unit/dom/manipulator.spec.js#L118
https://github.com/twbs/bootstrap/blob/f61a0218b36d915db80dc23635a9078e98e2e3e0/js/tests/unit/dom/manipulator.spec.js#L131
https://github.com/twbs/bootstrap/blob/f61a0218b36d915db80dc23635a9078e98e2e3e0/js/tests/unit/scrollspy.spec.js#L79

**Comment by spicalous** [comment]
> toBeTruthy() coerces the values AFAICT so it's a little moot IMHO. Either we are always explicit or not :)

So the original reason for this PR was that I noticed the assertions could result in a failing test to pass e.g. in the case where element is null
`expect(element).toBeDefined()` === TEST PASS false positive 
`expect(element).not.toBeNull()` === TEST FAIL correct 
`expect(element).toBeFalsy()` === TEST FAIL correct

wouldn't `toBeFalsy` suffice here?
https://github.com/jasmine/jasmine/blob/2fc5182ddcdd67456b89c92c2eedbc2443c928c6/src/core/matchers/toBeDefined.js

Similar case for truthy checks

Given that a property is null, we assert `.not.toBeNulll` (null !== actual)
What happens if behaviour is changed 
e.g.
instead of `property = null`, someone may `delete property`
In this case, the assertion would pass as `undefined !== null` and we end up with false positives again

In this case, I think truthy assert would be better again, we just don't want null AND undefined

Ah... Javascript..... :)

**Review by alpadev — APPROVED** [review]

**Pull request merged**
