### PR TITLE
Jumbotron Variants

### PR DESCRIPTION
**Pull request by mgibas**
Just added mixin for jumbotron and basic set of variants.

for a sake of backward compatibility:
.jumbotron = .jumbotron .jumbotron-default

### CODE REVIEW

**Comment by mdo** [comment]
I think for the time being, since we're not adding new features to v3.x and v4 is soon to land in alpha (soon, I swear), we'll punt on it for now.

**Comment by mdo** [comment]
Thanks though!

**Comment by StevenBlack** [comment]
:+1: 

Should we have the same treatment for Wells?  Seems reasonable.

**Comment by mgibas** [comment]
:+1: 

Fair enough :)

**Comment by cvrebert** [comment]
As mentioned previously elsewhere, there's a new widget in v4 that replaces & consolidates Alerts, Wells, and Panels.

**Pull request closed without merging**
