### PR TITLE
Use more https URLs

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@cvrebert: before this goes in, who's in charge of the domain? I assume @mdo. We should redirect to https in CloudFlare.

**Comment by cvrebert** [comment]
@mdo indeed. I have no idea what magic he's currently using to support HTTPS.

**Comment by XhmikosR** [comment]
No magic, it's just CloudFlare as one can easily see from the HTTP headers :)

**Comment by bardiharborow** [comment]
Related #19724. Should this be rebased to v4? Also might want to think about [HSTS](https://www.chromium.org/hsts).

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Comment by vszakats** [comment]
Disappointing to see this work being thrown away after keeping it in limbo without pretty much no feedback for 2 months.

**Comment by bardiharborow** [comment]
@vszakats, don't take the automated message too personally. mdo has just been drowning in issues and hit them with all with a blunt hammer. All your changes and some others are now rebased for v4 in #20557, and will probably be merged eventually.

**Comment by vszakats** [comment]
Thank you @bardiharborow for the pointers. I should have noticed the referenced PR above, only the fact this was as automated/bulk message was not readily obvious. Very good news the updates continue to live and won't be lost after all, my thanks for the rebase.

**Pull request closed without merging**
