### PR TITLE
Optimize file size for 512px Android favicon

### PR DESCRIPTION
**Pull request by spjpgrd**
Used [ImageAlpha](https://pngmini.com) and [ImageOptim](https://imageoptim.com) (through [ImageOptim-CLI](https://github.com/JamieMason/ImageOptim-CLI)) to squeeze out all the bytes.

**Was:**
8.745kb

**Now:**
4.358kb

**Savings:**
4.387kb (49.83%)

### CODE REVIEW

**Comment by XhmikosR** [comment]
Sorry, but it's already optimized the best way possible **losslessly**. Everything else changes color depth etc.

**Comment by XhmikosR** [comment]
Actually, I just triple checked and it's the only one I missed converting to 8-bit.


That being said, unless I can reproduce the file changes, I cannot merge.

**Comment by XhmikosR** [comment]
All right, there are 2 more PNGs plus I'm getting better results my way using zopflipng too so I'm gonna close this and make a new PR.

Thanks for bringing it into my attention.

**Comment by spjpgrd** [comment]
My pleasure! And thanks for introducing me to zopflipng 👍 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
