### PR TITLE
Fix width and height of data svg images in IE10

### PR DESCRIPTION
**Pull request by mort3za**
Inline svg of custom-select is broken in IE10 because there is no width and height attributes.
Tested on a real IE10 in browserstack, it works.

### CODE REVIEW

**Comment by XhmikosR** [comment]
If this lands it needs to target master and also make sure all other SVGs don't have this issue.

**Review by MartijnCuppens — APPROVED** [review]

**Comment by XhmikosR** [comment]
Changed the target branch so that it can be merged blindly. See my message above.

**Comment by MartijnCuppens** [comment]
He did a PR targeting the master branch here: https://github.com/twbs/bootstrap/pull/28882. I asked him to do target the `v4-dev` branch because we're dropping IE10 support anyway. If you prefer the master branch to be targeted, you can close this PR and reopen #28882, @XhmikosR.

**Comment by XhmikosR** [comment]
Switched this to v4-dev-xmr.

**Comment by XhmikosR** [comment]
But yeah, master is moot indeed.

**Comment by XhmikosR** [comment]
I'd still appreciate someone checking the other inline SVGs, because IIRC we don't use width/height.

**Comment by mort3za** [comment]
@XhmikosR I'll check them today

**Comment by mdo** [comment]
Going to make a note of this for my v5 forms branch at #28450.

**Comment by mdo** [comment]
Yeah, it just reminded me that I don't recall if there are any major hiccups and we're going all in on custom forms in v5. With new SVGs, I want to make sure I'm keeping things in mind and can document known issues to help folks customize.

**Comment by mort3za** [comment]
Searched entire project, only variables.scss has such inline SVG images. Pull request updated.

**Comment by XhmikosR** [comment]
@twbs/css-review: can you review one final time please?

**Comment by XhmikosR** [comment]
I'll rebase this when we have the final OK.

**Review by ysds — APPROVED** [review]

**Pull request merged**
