### PR TITLE
Use Tether's addTargetClasses option instead of manually removing classnames

### PR DESCRIPTION
**Pull request by lincolndbryant**
As of [Tether 0.7.1 (May 2015)](https://github.com/HubSpot/tether/pull/79/files) - we introduced `addTargetClasses`, which prevents adding any classnames to the target el when `false`.  I confirmed this with the visual tests, but can add a unit test if helpful.

I found [the issue referenced in the comment](https://github.com/HubSpot/tether/issues/36) and will resolve, sorry that got lost.

Thanks so much for incorporating Tether!

### CODE REVIEW

**Comment by thomas-mcdonald** [comment]
\cc @fat

**Comment by cvrebert** [comment]
> Thanks so much for incorporating Tether!

Thanks so much for maintaining Tether! Our hand-rolled positioning logic was getting pretty hairy and yet still wasn't bug-free; we were quite glad to be able to nuke it in favor of Tether.

**Comment by fat** [comment]
oh this is fire

**Comment by fat** [comment]
@lincolndbryant sorry took so long to get this in - thanks for the help!

**Comment by adamschwartz** [comment]
:smile:

**Pull request merged**
