### PR TITLE
Update _card.scss - border on one card accordions

### PR DESCRIPTION
**Pull request by dangowans**
Add back the border for accordions that only have a single card inside.

### CODE REVIEW

**Comment by mdo** [comment]
Do we have a demo in the docs to show this one? Want to make sure we're able to see these things better when merging PRs :).

**Comment by dangowans** [comment]
First timer here, so not entirely sure what you mean.  (Sorry.)

But here's the behaviour I'm seeing.
https://jsfiddle.net/8t5oev9r/1/

And here's the card accordion with my pull request.
https://jsfiddle.net/8t5oev9r/2/

**Review by MartijnCuppens — CHANGES_REQUESTED** [review]
Hi @dangowans, 

Thanks for the PR, but I think we can fix this in one line. Could you just change line 275 to:
`    &:first-of-type:not(:last-of-type) {`

**Comment by XhmikosR** [comment]
@dangowans: ping

**Comment by XhmikosR** [comment]
@MartijnCuppens can you tackle this yourself?

**Pull request closed without merging**
