### PR TITLE
Download link in README

### LINKED ISSUE #31585: Broken link from Readme to download the latest release
"Download the latest release" link from Readme to `https://codeload.github.com/twbs/bootstrap/zip/v5.0.0` is broken and returns `404: Not Found`

Operating system and version: macOS Catalina
Browser and version: Firefox 80.0

### PR DESCRIPTION
**Pull request by ffoodd**
Fixes #31585

### CODE REVIEW

**Review by mdo — APPROVED** [review]

**Comment by XhmikosR** [comment]
Note that this was done intentionally and there might be more places.

**Comment by ffoodd** [comment]
@XhmikosR I didn't find any other occurrences, since even the `_config.yml` targets the alpha release.
 And I may be wrong but `README.md` is handled by `build/change-version.js`, so there's no real point to use an invalid target here, is it?

**Comment by XhmikosR** [comment]
I'm not sure why I left some links TBH, but I'd like to have a closer look and wrap this properly :)

**Comment by XhmikosR** [comment]
The only other instance is `composer require twbs/bootstrap:5.0.0`. I'll try it later to see if it works and update the PR if needed.

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
