### PR TITLE
Fix sourcemaps

### LINKED ISSUE #23254: CSS sourcemaps are broken
I'm on Windows and tested Firefox but shouldn't really matter.

/CC @Johann-S @mdo @bardiharborow

### PR DESCRIPTION
**Pull request by XhmikosR**
Without this, the sourcemaps aren't found for me.

Fixes #23254

### CODE REVIEW

**Comment by XhmikosR** [comment]
Actually, can someone try this locally who is not on Windows and see if it fixes the issue?

I have opened an issue with clean-css because I see the paths use Windows separator on Windows.

**Comment by XhmikosR** [comment]
OK, I confirmed it fixes the issue for me.

**Review by Johann-S — APPROVED** [review]
LGTM 👍 on Win10

**Comment by XhmikosR** [comment]
Thanks @Johann-S for confirming!

@mdo: should we merge this now? Currently the sourcemaps are broken for v4.

**Comment by mdo** [comment]
I've no idea why this fails elsewhere, but it doesn't break source maps for me, so :shipit:!

**Pull request merged**
