### PR TITLE
variablized-backdrop-color-and-opacity

### PR DESCRIPTION
**Pull request by jonnysp**
### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

- <https://deploy-preview-37421--twbs-bootstrap.netlify.app/>

### CODE REVIEW

**Comment by mdo** [comment]
I don't think we can make this change in v5 since it's a breaking change on the CSS variable names.

**Comment by jonnysp** [comment]
> I don't think we can make this change in v5 since it's a breaking change on the CSS variable names.

Is not a breaking change, is a extension.

**Comment by mdo** [comment]
> > I don't think we can make this change in v5 since it's a breaking change on the CSS variable names.
> 
> Is not a breaking change, is a extension.

Changing the names of the existing CSS variables—like `--bs-backdrop-bg` to `--bs-modal-backdrop-bg`—is a breaking change.

**Comment by jonnysp** [comment]
> > > I don't think we can make this change in v5 since it's a breaking change on the CSS variable names.
> > 
> > 
> > Is not a breaking change, is a extension.
> 
> Changing the names of the existing CSS variables—like `--bs-backdrop-bg` to `--bs-modal-backdrop-bg`—is a breaking change.

The idea was to make the backdrop not independent from the modal and use the same termologie on both and make this with variables.

**Comment by mdo** [comment]
Going to pass on this for now. Maybe for v6?

**Comment by jonnysp** [comment]
Ok

**Pull request closed without merging**
