### PR TITLE
Refactor ESLint configuration.

### LINKED ISSUE #20466: Hound warnings on JS test files
[I've opened a few PRs](https://github.com/twbs/bootstrap/pulls/maxbeatty) and each gets lots of comments from @houndci-bot because the [JS unit test files](https://github.com/twbs/bootstrap/tree/0416f761dddae04a1b4d3ce70afece518330ca4d/js/tests/unit) do not conform to [the ESLint settings](https://github.com/twbs/bootstrap/blob/0416f761dddae04a1b4d3ce70afece518330ca4d/js/.eslintrc.json). Here are few ways I've considered addressing this:
1. Ignore the test files similar to #20446. This is the least amount of work and will get other PRs passing and more likely to merge.
2. Fix the eslint issues in the test files, add a grunt task or npm script (#20332) to transpile the test files, and update the references in [`index.html`](https://github.com/twbs/bootstrap/blob/0416f761dddae04a1b4d3ce70afece518330ca4d/js/tests/index.html#L149-L159). This is obviously more work but would be more of a long term benefit.

I'm open to other ways to please @houndbot-ci when changing JS test files and willing to put in the work 😅

### PR DESCRIPTION
**Pull request by bardiharborow**
In lieu of an official style guide, this takes the `eslint:recommended` preset, and then enables every ESLint rule that does not cause significant disruption to the codebase. It then disables the rules needed for `js/tests` to pass, as that follows a slightly different style. We may wish to tighten quite a bit of this later, but it's better than what we currently have.

This is one half of the fix for #20466, the other half being houndci/hound#889. This works towards #20740, but I suspect there is more to do, noting especially that ESLint does not cover all folders yet, as per #17924.

### CODE REVIEW

**Comment by wolfy1339** [comment]
Hound uses the config found in the Bootstrap repo, not the new config you want to give it

**Comment by Johann-S** [comment]
I read a bit on HoundCi and I didn't found any options to lint differently JavaScript from ``js/tests/`` folders unless to ignore them with .eslintignore see : 
https://houndci.com/configuration#eslint
http://eslint.org/docs/user-guide/command-line-interface#ignoring-files-from-linting

But I don't understand why you said @bardiharborow ? 
> Travis will fail until #21003 is merged.

If we remove the PhantomJS Bridge nothing will change because of units tests will stay in ES5 and HoundJS will continue to warn us

**Comment by bardiharborow** [comment]
@Johann-S oh, that was just because `js/tests/unit/phantom.js` does not pass the new ESLint rules and I didn't fix it because I was going to get it removed.

I'm going to follow up with Hound and see if we can get Hound to use the recursive`.eslintrc.json` discovery strategy that ESLint uses by default.

**Comment by mdo** [comment]
Have some conflicts here now.

I'm unsure where this and #21003 lie, so @bardiharborow and @Johann-S, I defer to you two on what get's merged when :). Happy to chat more over Slack if it'd help btw.

**Comment by Johann-S** [comment]
Just a question @bardiharborow is it still possible to run QUnit tests in a web browser with your PR ? Or we have to build the tests into ES5 with Babel

**Comment by bardiharborow** [comment]
@mdo, we're good to go here. Travis is green. :)

**Comment by mdo** [comment]
Had a small conflict from merging #17642, but I think I fixed it right up. Merged! Thanks so much <3.

**Pull request merged**
