### PR TITLE
Improve accessibility of helper text in forms overwiew

### PR DESCRIPTION
**Pull request by MewenLeHo**
### Description

Improve accessibility of helper text in forms.

### Motivation & Context

Better accessibility by using a more robust method and add a programmatic link to the label.

### Type of changes

- [X] New feature (non-breaking change which adds functionality)

### Checklist

- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [X] My code follows the code style of the project _(using `npm run lint`)_
- [X] My change introduces changes to the documentation
- [X] I have updated the documentation accordingly
- [X] I have added tests to cover my changes
- [X] All new and existing tests passed

#### Live previews

- <https://deploy-preview-37506--twbs-bootstrap.netlify.app/docs/5.2/forms/overview/#overview>

### CODE REVIEW

**Comment by julien-deramond** [comment]
FYI there are other occurences of this use case in the source code. For example, at least in the Cheatsheet examples (LTR and RTL).

**Review by patrickhlauke — CHANGES_REQUESTED** [review]
Unclear why you say this is more robust. This also mixes the concepts of accessible *name* and accessible *description*, cramming everything into the *name*, which is not correct.

**Comment by patrickhlauke** [comment]
there is nothing more "robust" about this, and it's conceptually dubious.

**Comment by mdo** [comment]
Closing per comments above.

**Pull request closed without merging**
