### PR TITLE
select option aria hidden option added

### LINKED ISSUE #37614: in docs/forms/select, the default selected option tag should have an aria-hidden="true"
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

hello,
in docs/forms/select, the default selected option tag should have an aria-hidden="true" to avoid a vocalization of the content of the option when an AT is entering the select tag. This content is not really needed and the label of the select is enough to understand his purpose.
And this has to be made in every select tag of the docs...

### Reduced test cases

https://getbootstrap.com/docs/5.0/forms/select/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

v5.0 and down

### PR DESCRIPTION
**Pull request by UnfixedSun**
### Description
Closes #37614 which is in docs/forms/select, the default selected option tag should have an aria-hidden="true" to avoid a vocalization of the content of the option when an AT is entering the select tag. This content is not really needed and the label of the selection is enough to understand his purpose. And this info in the default option is much more for visual users than AT.
And this has to be made in every select tag of the docs.

### Motivation & Context

Added the aria-hidden properties for the select option tag.
### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

#### Live previews

- <https://deploy-preview-{your_pr_number}--twbs-bootstrap.netlify.app/>

### CODE REVIEW

**Review by julien-deramond — CHANGES_REQUESTED** [review]
From a pure a11y point of view, I'll let @patrickhlauke provide elements here or in the correspondig issue for the OP about whether we need this change or not.

However, if this change is needed, the modification in this PR should be propagated in all the files using `<option selected>` without any `aria-hidden="true"` for consistency.

**Comment by patrickhlauke** [comment]
note that this would fail WCAG 2.1 SC 2.5.3 Label in Name https://www.w3.org/TR/WCAG21/#label-in-name

I'd also say that this is perhaps overkill/gilding the lily a little bit, particularly for what's intended to be a very generic example in the docs ... and it might raise more questions/lead to people just cargo-culting this approach without properly understanding it and creating accidentally inaccessible output.

**Comment by Aniort** [comment]
hello,
yes, this would fail WCAG 2.5.3, but  this <option> is just used as a label for the <select>,
perhaps we should use, instead of the aria-hidden="true", an aria-label="Empty default option" to inform AT users that this <option> is a default empty option for this select,

**Comment by julien-deramond** [comment]
I'm not aguing against or in favor of this modification but when you say "that will not be an actual issue for AT users going through our generic documentation pages...".
There are AT users but there are also developers who will copy/paste this code in their project. I know that everyone should understand what's in the code but we know it's not always like that :D 
Just an extra-question just for have more elements, if we think in terms of propagation of this element in real projects, would it be still overthinking/overengineering in your opinion Patrick?

**Comment by patrickhlauke** [comment]
> if we think in terms of propagation of this element in real projects, would it be still overthinking/overengineering in your opinion Patrick

personally, I'd say so yes. mainly because I work closely with AT users, and this sort of thing has never been mentioned as an actual problem or point of confusion for them (though maybe it's because they're more resilient/savvy users).

**Comment by Aniort** [comment]
ok, this modification is more "comfort" than accessibility, I agree on this point!
so, No changes are required

**Comment by patrickhlauke** [comment]
also, don't get me wrong @Aniort ... these are nicely considered suggestions. I just feel they're probably more for experienced devs to make for their own specific sites, rather than something to push in a more generic docs site.

**Comment by patrickhlauke** [comment]
a different outcome of this may well be that we take a good look at our docs for the next version, and avoid the whole debacle by providing more complete examples with an actual visible `<label>` instead and an empty default option, or similar

**Comment by mdo** [comment]
Agree on waiting to do something else in v6. Thanks though!

**Pull request closed without merging**
