### PR TITLE
FIX (carousel): MS Edge image width issue on carousel

### LINKED ISSUE #16915: Incorrect image scaling on carousel slide in MS Edge
image

### PR DESCRIPTION
**Pull request by sanusart**
- fix incorrect image width issue on carousel

Closes #16915 ref #16932

### CODE REVIEW

**Comment by GiorgioPingendo** [comment]
..

**Comment by GiorgioPingendo** [comment]
.

**Comment by GiorgioPingendo** [comment]
..

**Comment by cvrebert** [comment]
The relevant bug is no longer present as of the latest stable version of Edge (25.10586.0.0). :smile: 
Thus, I'm closing this PR since its changes should no longer be necessary.

**Pull request closed without merging**
