### PR TITLE
Allow defining navbar font and color

### PR DESCRIPTION
**Pull request by nicoonoclaste**
This is helpful for people customizing their Bootstrap stylesheets.

I ran into this usecase while making a Solarized colorscheme for
Bootstrap.

### CODE REVIEW

**Comment by nbraud** [comment]
I don't understand the comment from @houndci-bot ...

**Comment by copynpaste** [comment]
You have following order

    font-family: $navbar-font-family;
    font-weight: $navbar-font-weight;
    position: relative;
    padding: $navbar-padding-y $navbar-padding-x;

But should have

    position: relative;
    padding: $navbar-padding-y $navbar-padding-x;
    font-family: $navbar-font-family;
    font-weight: $navbar-font-weight;

**Comment by tomlutzenberger** [comment]
See https://github.com/twbs/bootstrap/blob/v4-dev/scss/.scss-lint.yml#L140
Before you make a PR, you should run grunt and make a complete build to prevent such things.

**Comment by nbraud** [comment]
@copynpaste OK, thanks!

@tomlutzenberger I did run Grunt, that's what I do to generate my custom stylesheet anyhow.  
However, it seems I don't have `scss-lint`...

Anyhow, thanks for the patient explanation.

**Comment by mdo** [comment]
We don't set empty/inherit properties in our CSS for potential customization; that just adds bloat over time. Instead, we set smart defaults wherever possible and allow inheritance in CSS to do it's thing in a few global areas. This kinda thing is perfect for your own local styles.

Thanks though!

**Comment by nbraud** [comment]
@mdo So, `EWONTFIX`?

**Comment by nbraud** [comment]
@mdo Also, I didn't really get this:

> we set smart defaults wherever possible and allow inheritance in CSS to do it's thing in a few global areas. This kinda thing is perfect for your own local styles.

I thought local styles were supposed to be `_custom.scss` only.

**Comment by mdo** [comment]
Well, to be clear, this isn't a bug, so it's not a won't fix—it's a won't implement. Custom styles *can* go in that partial, but it's not required—put them wherever you like.

**Pull request closed without merging**
