### PR TITLE
Update doc assets

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @cvrebert

### CODE REVIEW

**Comment by XhmikosR** [comment]
@cvrebert: hound needs fixing it seems.

**Comment by XhmikosR** [comment]
Note to self: don't merge this yet until #20302 is sorted

**Comment by XhmikosR** [comment]
Rebased.

**Comment by bardiharborow** [comment]
The Hound issue should be fixed in #20446 if I understand correctly.

**Comment by XhmikosR** [comment]
@cvrebert: bump

**Comment by mdo** [comment]
This has conflicts—is it good to merge otherwise?

**Comment by XhmikosR** [comment]
Well, it **was** good; now I'll need to check for newer versions :p

**Comment by bardiharborow** [comment]
You can look at #20555 if you want to avoid fixing the conflicts in this. It originally started off as a small PR by now encroaches quite a bit on this.

**Comment by XhmikosR** [comment]
Nah, I'd rather do it myself.

**Comment by vsn4ik** [comment]
Not necessary after merge #20555.

**Pull request closed without merging**
