### PR TITLE
Using calc() for columns width

### PR DESCRIPTION
**Pull request by IvanKalinin**
In Firefox the gird with widths of `*.333333%` have a "half-pixel" issue on certain window widths..
To resolve the problem, use css `calc()` to let browsers calculate actual width by themselves instead of hardcoded values.

firefox bs grid

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
Which browserversion, OS and screenwidth are you testing on? I can't really reproduce this at the moment.

**Comment by IvanKalinin** [comment]
@MartijnCuppens 

bug if ff


how to reproduce:
1. The bug reproduces only in Firefox
2. The container should have dynamic width (e.g. `.container-fluid`)
3. Columns should have flex-basis. `*.3333333%` (e.g. `col-4`)
4. Add borders to be able to see the bug
5. Open the template in responsive mode and change width pixel by pixel. 
6. See the bug in some certain window width

[What a video](https://www.useloom.com/share/3f3ace8be42042448b08638f1293b8de)

**Comment by XhmikosR** [comment]
Can you try with a different DPI setting too?

I've definitely hit similar inconsistencies with rounding on Firefox.

**Comment by IvanKalinin** [comment]
It is interesting. 
Seems like it reproduces on certain DPIs.
It is easily reproduces on my external LG 34'' screen but when I move browser window in MacBook  screen there it no rounding problems.

**Comment by XhmikosR** [comment]
For me 125% on a Windows 7 VM triggered it IIRC.

**Comment by MartijnCuppens** [comment]
I could just reproduce this behaviour with browser zoom. This PR fixes the issue and I think this is a better approach than the rounding we have now.

Maybe it's worth reconsidering adding `postcss-calc` to optimise the `calc()` functions if we continue with this? (#23582)

**Comment by XhmikosR** [comment]
We need to check if we have other places we need to do such changes.

And we can look into postcss-calc if this lands.

**Comment by MartijnCuppens** [comment]
I did some tests with `postcss-calc`, turns out it transforms `calc()` functions like `calc(100% / 3)` into `33.33333%`, so we'll just end up with the same problem.

**Comment by XhmikosR** [comment]
We can look into that later, @MartijnCuppens https://github.com/postcss/postcss-calc#preserve-default-false

**Review by MartijnCuppens — DISMISSED** [review]

**Comment by XhmikosR** [comment]
How about other places? I know for sure we use this in embed and we have a ticket for sure.

**Comment by XhmikosR** [comment]
Found it https://github.com/twbs/bootstrap/issues/26284

Can someone tackle that in a separate PR too?

**Comment by XhmikosR** [comment]
Thanks but that adds another feature too :/

It's always better to split this stuff to be able to merge faster.

Anyway, let's not get more sidetracked here :) Thanks for all the help @MartijnCuppens!

**Comment by mdo** [comment]
I'm inclined to skip this in v4. It only happens on zooming or non-standard DPIs it seems. I'm also wary of adding calc expressions to all our grid classes (it's a lot of them) for performance reasons.

**Comment by patrickhlauke** [comment]
i'll just note that increasingly there's no point talking about "non-standard DPIs", as more devices come along with different DPIs and there's no clear "standard DPIs" anymore...

**Comment by patrickhlauke** [comment]
i'll just note that increasingly there's no point talking about "non-standard DPIs", as more devices come along with different DPIs and there's no clear "standard DPIs" anymore...

**Comment by patrickhlauke** [comment]
i'll just note that increasingly there's no point talking about "non-standard DPIs", as more devices come along with different DPIs and there's no clear "standard DPIs" anymore...

**Comment by patrickhlauke** [comment]
i'll just note that increasingly there's no point talking about "non-standard DPIs", as more devices come along with different DPIs and there's no clear "standard DPIs" anymore...

**Comment by patrickhlauke** [comment]
i'll just note that increasingly there's no point talking about "non-standard DPIs", as more devices come along with different DPIs and there's no clear "standard DPIs" anymore...

**Comment by patrickhlauke** [comment]
i'll just note that increasingly there's no point talking about "non-standard DPIs", as more devices come along with different DPIs and there's no clear "standard DPIs" anymore...

**Comment by patrickhlauke** [comment]
i'll just note that increasingly there's no point talking about "non-standard DPIs", as more devices come along with different DPIs and there's no clear "standard DPIs" anymore...

**Comment by XhmikosR** [comment]
Yeah, I agree with Patrick on this one. DPIs != 100% will be more and more frequent.

**Comment by MartijnCuppens** [comment]
I made a PR for `postcss-calc` in https://github.com/postcss/postcss-calc/pull/61. With this option we could simplify some calc expressions like `calc(100% / 4)` to `25%`.

**Comment by mdo** [comment]
Noted on the DPI conversation. I'm still inclined to leave this as-is, but let me think on it a bit more.

**Comment by mdo** [comment]
Let this one sit and coming back to it, going to punt on it. Thanks, though!

**Comment by ysds** [comment]
I believe this is worth revisiting for v5.

**Comment by ysds** [comment]
oh I mistakenly re-opened this instead of issue. Close this and create a new issue for clarity.

**Pull request closed without merging**
