### PR TITLE
remove bro from comment

### PR DESCRIPTION
**Pull request by mathisonian**

### CODE REVIEW

**Comment by NYPD** [comment]
Idk, I kinda like the bro in there

**Comment by XhmikosR** [comment]
Seems a little too much. I'd say just leave it as is.

**Comment by patrickhlauke** [comment]
FWIW i'm in favor. It's only a comment in the CSS, and if it removes any form of unease for those that do take issue with it, removing it is a good thing (without opening a whole "people who get offended somehow by this need a thicker skin..." debate)

**Comment by XhmikosR** [comment]
@mdo must have added that so I guess he should make the choice after all.

**Comment by mdo** [comment]
No idea when or why I did, I'm in favor of nuking it though.

**Comment by patrickhlauke** [comment]
:+1:

**Pull request merged**
