### PR TITLE
Added more responsive embed aspect ratio formats

### PR DESCRIPTION
**Pull request by riichard**
I've added support to the embed-responsive component for:

Square 1:1 embedables format such as vine/instagram
Mobile 3:2 for screencasts
Mobile 2:3 for vertial screencasts and snapchats
Cinematic ~~21:9 or~~ 2.35:1 formats.

Also added guides the docs on how to use these additional formats.

### CODE REVIEW

**Comment by mdo** [comment]
I could see doing 1x1, but unsure about the rest of those.

**Comment by riichard** [comment]
I thought the 3:2/2:3 aspect ratio made sense for mobile screenshots. But
that ratio was deprecated since the release of the iPhone 5, which is 16:9

The specific 2.35 cinematic aspect is less common and should maybe be left
out.

I'll remove these two from the pull request.

**Comment by riichard** [comment]
I've removed the non-popular aspect ratios. 1:1 is the only addition right now.

**Comment by mdo** [comment]
Nice, thank you. Can you squash your commits please and debase to fix the merge conflicts? Thanks!

**Comment by riichard** [comment]
I squashed it and fixed the merge conflicts. Does this work for you?

**Comment by wolfy1339** [comment]
There are unwanted commits: 4788bc9 and e185604

**Comment by cvrebert** [comment]
Merged as c960169807102d1f78b700fbadac44106ff06716. Thanks.

**Pull request closed without merging**
