### PR TITLE
Run all lint targets in `test` script.

### LINKED ISSUE #23164: Make sure we run all the needed tasks on CI
For example, `js-lint-docs` and probably more.

Tasks:

* `js-lint-docs`

/CC @bardiharborow @Johann-S

### PR DESCRIPTION
**Pull request by XhmikosR**
@Johann-S: can you check if we are missing something else?

Fixes #23164.

### CODE REVIEW

**Review by Johann-S — APPROVED** [review]
LGTM 👍

**Comment by XhmikosR** [comment]
@Johann-S: any other targets we might be missing to run on CI?

**Comment by XhmikosR** [comment]
Freaking saucelabs is failing and I can't merge.

@mdo: I think we need to remove the restrictions :)

**Comment by Johann-S** [comment]
That's happen sometimes when we push a lot and Saucelabs is used a lot

**Pull request merged**
