### PR TITLE
allow to pass popper.js configuration for tooltip/popover and dropdown

### LINKED ISSUE #28661: Allow us to pass other Popper.js configurations to dropdowns and tooltips
Popper.js provides a lot of configuration that can be used for our utilities, but most of them are not being used by the plugins themselves.

I'm in a situation where I require a `dropdown` to be of `fixed` position rather than `absolute`, popper allows this via:

```
Popper.Defaults.positionFixed = true
```

However that would change everything that is using Popper in my page. I can't really change this configuration per-element basis.

It would be of great help to let us pass a second param to the built in functions, being the Popper options (not supported in the plugin) to be merged in the Popper config when initializing an object.

```
$('.dropdown-toggle').dropdown({
    boundary:'viewport' // Plugin config
}, {
    positionFixed: true // Popper config
});
```

### PR DESCRIPTION
**Pull request by Johann-S**
Fixes: #28661

### CODE REVIEW

**Comment by mdo** [comment]
Is this ready for v4.4.0, or does it need to be saved for alter?

**Comment by XhmikosR** [comment]
It'll need a manual backport, but I need to look at it first so let's wait a bit. We still have time.

**Comment by Johann-S** [comment]
The backport in v4.4 is easy and can be done quickly

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
@Johann-S feel free to merge and backport this in my v4-dev-xmr branch; just make sure you reference the PR in the backport commit.

**Pull request merged**
