### PR TITLE
Docs: add note about the grays being "cool"

### PR DESCRIPTION
**Pull request by patrickhlauke**
Closes https://github.com/twbs/bootstrap/issues/27332

### CODE REVIEW

**Review by midzer — COMMENTED** [review]
I would prefer the describtion: "(...), which tend towards subtle blueish tones, rather than neutral grays."

**Comment by patrickhlauke** [comment]
@mdo? doesn't seem like a huge compromise to add this wording...but up to you...

**Comment by XhmikosR** [comment]
Ping @mdo

**Review by mdo — APPROVED** [review]

**Comment by patrickhlauke** [comment]
as i managed to mess up this PR by accidentally deleting the branch...successor: https://github.com/twbs/bootstrap/pull/27824

**Pull request closed without merging**
