### PR TITLE
Clear duplicated class `border-0`

### PR DESCRIPTION
**Pull request by k-utsumi**
dist/css/bootstrap-utilities.css

- https://github.com/twbs/bootstrap/blob/ec1425efb4a01408414b09e6021a147263fae4ac/dist/css/bootstrap-utilities.css#L200-L202
- https://github.com/twbs/bootstrap/blob/ec1425efb4a01408414b09e6021a147263fae4ac/dist/css/bootstrap-utilities.css#L272-L274

### CODE REVIEW

**Comment by ffoodd** [comment]
Nice catch, thanks!

Wouldn't it be better to drop [the relevant entry in `_utilities.scss` (L77)](https://github.com/twbs/bootstrap/blob/e79c8f3489527d7f5eef2bb3cf14856f26c49871/scss/_utilities.scss#L77) instead? @mdo any opinion?

**Comment by k-utsumi** [comment]
> Wouldn't it be better to drop [the relevant entry in `_utilities.scss` (L77)](https://github.com/twbs/bootstrap/blob/e79c8f3489527d7f5eef2bb3cf14856f26c49871/scss/_utilities.scss#L77) instead?

I think that's no good 🙈

In the current dist CSS order,
make it impossible to set some directions border with clearing the components border.

- [example @ jsfiddle](https://jsfiddle.net/h1jk2qpn/)

**Comment by ffoodd** [comment]
For the record, this is somehow unrelevant: if you want to clean some borders only (and not all), do not use `.border-0` which means drop all borders. Use `.border-top-0` and so on.

However I prefer that `.border-0` matches `border: 0;` instead of `border-width: 0px;` so I'd stick to your suggestion. :)

**Review by ffoodd — APPROVED** [review]

**Review by mdo — COMMENTED** [review]
This needs a migration guide entry. @k-utsumi Care to take a pass at that?

**Comment by k-utsumi** [comment]
I don't know what the migration guide entry is, and I'm not very good at English 😂
Please write that, or I'll try to write if show me some examples 🙋‍♂️

**Comment by ffoodd** [comment]
@k-utsumi The migration guide is `migration.md` in `site/content/docs/5.0/`, you may simply mentionned something like:

> Dropped the `0` entry in `$border-widths` map to remove duplicated utilities.

**Comment by k-utsumi** [comment]
@ffoodd Thanks, maybe I understood🙌

**Review by mdo — APPROVED** [review]

**Comment by k-utsumi** [comment]
Thanks😊

**Pull request merged**
