### PR TITLE
fix floating-labels min-height

### PR DESCRIPTION
**Pull request by jonnysp**
### Description
fix floating-labels min-height. textareas have other min-height as normal textareas

i have set it for all input, maybe it is better only for textareas?

### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

#### Live previews

- <https://deploy-preview-38366--twbs-bootstrap.netlify.app/>

### CODE REVIEW

**Comment by mdo** [comment]
Not sure we need it? Textarea height is covered at http://getbootstrap.com/docs/5.3/forms/floating-labels/#textareas. Does this fix a bug or something we have right now?

**Comment by jonnysp** [comment]
is for floating labels textarea min-height not for height 

in normal textareas is set, but is to small for floating textareas. 

grafik

**Comment by Sysix** [comment]
I could reproduce this bug my manually resizing the textarea with the browsers resize icon (bottom right).

**Comment by jonnysp** [comment]
yes, but it is only in FF, Edge and Chrome on windows. in Safari on MAC everything is fine.
Screenshot-2023-04-05-091443

**Review by mdo — APPROVED** [review]

**Comment by jonnysp** [comment]
nice

**Pull request merged**
