### PR TITLE
Focus (visually hidden) input radio/checkbox

### PR DESCRIPTION
**Pull request by patrickhlauke**
This allows for keyboard navigation (e.g. arrow keys left/right to trigger different radio buttons) following an initial mouse click interaction on a radio button or checkbox

A simplified port of https://github.com/twbs/bootstrap/pull/19192 to the new v4 code base

### CODE REVIEW

**Comment by patrickhlauke** [comment]
Savage appears to be stuck. As local tests and Travis don't report anything untowards, I'm going to be bold and merge...

**Comment by cvrebert** [comment]
We might be able to use raw DOM's https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus instead of jQuery here.

**Comment by patrickhlauke** [comment]
Ah sorry, already merged. But would our preference be to go vanilla instead of jquery then?

**Comment by cvrebert** [comment]
The strategy for v4's JS seems to be to not use jQuery in cases where it doesn't really buy us anything. It's more performant if nothing else.

**Comment by maugusto-cit** [comment]
@patrickhlauke , it seems this issue has been tackled many times, but it also seems it is back in the latest version (4 alpha 5). If you check the sample [here](http://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons), you'll see that keyboard navigation (in Safari) is not changing the checked attribute in the input radio. Should I report a new issue?

**Comment by patrickhlauke** [comment]
@maugusto-cit yeah this issue is still not fixed :( i made a start over here https://github.com/twbs/bootstrap/issues/18874 but need to find some time to take it further

**Pull request merged**
