### PR TITLE
Remove page reload in pwa.js.

### LINKED ISSUE #24868: Your service worker creates an infinite loop on page load
At https://getbootstrap.com/ I get an infinite loop trying to load the documentation tab. See dev tools:
screen shot 2017-11-24 at 10 48 23 am

There's an infinite loop in the service worker.

Chrome Version 62.0.3202.94 (Official Build) (64-bit) on MacOS

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @Lyricalz: *I think* this should be fine, i.e. leaving it up to the browser to do its job.

Fixes #24868

### CODE REVIEW

**Comment by Lyricalz** [comment]
That will work yeah, but do you still want me to write a "proper" solution?

**Comment by XhmikosR** [comment]
If this solution works out of the box, without any side-effects, the only thing I'd like it's just a `console.log`. Feel free to improve it later when you have some time :)

**Comment by Lyricalz** [comment]
You'd like a `console.log` or you'd prefer to remove it?

**Comment by XhmikosR** [comment]
Now that I think about it lets keep it simple as long as it works without
any side effects.

Feel free to improve the whole experience and ping me :)

Thanks!

**Comment by XhmikosR** [comment]
@mdo @Johann-S please approve

**Review by Johann-S — APPROVED** [review]

**Pull request merged**
