### PR TITLE
Handle Chromium to run Karma

### PR DESCRIPTION
**Pull request by ffoodd**
I do not have Chrome nor stable Firefox and am always using this locally to run tests.

Could also add Firefox Nightly or ESR but I guess Chromium is a first, better choice.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@ffoodd don't we need a new karma launcher package for Chromium?

**Comment by ffoodd** [comment]
Confirmed: https://github.com/karma-runner/karma-chrome-launcher#readme

> Launcher for Google Chrome, Google Chrome Canary and Google Chromium.

The same for Firefox BTW, a single launcher works for ESR, Stable, DevEd and Nightly.

**Comment by XhmikosR** [comment]
Marked it for backport too since it helps you and doesn't hurt having it :)

I'll try to install Chromium on my VM and try this later to confirm it works.

**Comment by XhmikosR** [comment]
OK, so I tested this on Windows and Chromium isn't detected. But on Linux Mint it works, so I guess it's fine :)

**Review by XhmikosR — APPROVED** [review]

**Review by ghost — COMMENTED** [review]
#32178 #32163 #30015 #31705 #30042

**Pull request merged**
