### PR TITLE
accessibility - carousel aria fix

### PR DESCRIPTION
**Pull request by Lausselloic**
Propose a PR to fix aria role listbox required children

### CODE REVIEW

**Review by patrickhlauke — CHANGES_REQUESTED** [review]
see https://github.com/twbs/bootstrap/issues/22061#issuecomment-292926679 - i would actually suggest removing the `role="listbox"` at this stage, rather than adding `role="option"`. happy to do this myself in a separate PR, if you'd prefer closing this one (as it seems a bit messy already with various extraneous commits)

**Comment by patrickhlauke** [comment]
xref https://github.com/twbs/bootstrap/issues/22061

**Comment by Lausselloic** [comment]
Yes I will close it

**Comment by patrickhlauke** [comment]
i hope i didn't scare you off from contributing though...would have been happy for you to rework the PR (but it would mean a rebase etc). let me take opportunity though to say thank you for raising these things which i knew were there but never got around to methodically look at :+1:

**Comment by Lausselloic** [comment]
No don't wory I won't be affraid :-) 
I agree with the proposition to remove the listbox. 
I need to cleanup my dedicated PR repository, as I know my PR are not very clean and doesn't only contain proper PR code.

I will continue to push accessibility improvement.

**Pull request closed without merging**
