### PR TITLE
Remove the jasmine-core devDependency.

### PR DESCRIPTION
**Pull request by XhmikosR**
karma-jasmine already depends on jasmine-core.

### CODE REVIEW

**Comment by Johann-S** [comment]
You're right 👍

**Review by Johann-S — APPROVED** [review]

**Comment by floreengrad** [comment]
I now get a warning on karma-jasmine-html-reporter having a non met jasmine-core dependency.

**Comment by XhmikosR** [comment]
It's something on your side, there's nothing wrong with this change.

**Comment by floreengrad** [comment]
indeed I was using yarn.
yarn install seems to display some warnings that I don't see with npm.

**Comment by XhmikosR** [comment]
Since karma-jasmine depends on jasmine-core, it's redundant to have jasmine-core in the devDependencies, which is what this patch was about.

I don't use yarn or any other package managers, nor do we test them on CI.

**Comment by floreengrad** [comment]
I totally get the dep removal, no prb with that, it makes total sense.
I was trying to catch up with the last 100 commits you did since October and noticed this change, that's all.

**Pull request merged**
