### PR TITLE
Revert "Make jQuery 2.0 the minimum supported version."

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by cvrebert** [comment]
LGTM. Will merge as soon as Travis finishes.

**Comment by cvrebert** [comment]
Ah, right. Freaking https://github.com/travis-ci/travis-ci/issues/5092

**Comment by JulienMelissas** [comment]
Thank you!

**Comment by danimalweb** [comment]
Thank you!

**Pull request merged**
