### PR TITLE
Switch from qunit to jasmine

### PR DESCRIPTION
**Pull request by Johann-S**
Things to do:
- [x] Move each plugin in a separate folder
- [x] Rewrite all the plugins unit tests
	- [x] dom
		- [x] data
		- [x] eventHandler
		- [x] manipulator (#28543)
		- [x] selectorEngine
	- [x] util
		- [x] index
		- [x] sanitizeHtml
	- [x] Alert
	- [x] Button
	- [x] Carousel
	- [x] Collapse
	- [x] Dropdown
	- [x] Modal
	- [x] Popover
	- [x] Scrollspy
	- [x] Tab
	- [x] Toast (#28562)
	- [x] Tooltip

### CODE REVIEW

**Comment by bershanskiy** [comment]
@Johann-S Now I see what you meant by "Bootstrap file structure changing a lot" in #27542. I would like to help moving away from jQuery, if there is a task I could tackle.

**Comment by Johann-S** [comment]
Hi @bershanskiy, if you're willing to help us to move away from jQuery there is a list of tasks here: https://github.com/twbs/bootstrap/issues/28342

And if you want to help us to move away from QUnit you can simply rewrite the unit tests of one of our plugins.
To do that you have to create one `describe` by methods, with one or several `it` in

**Comment by bershanskiy** [comment]
@Johann-S 
One minor thing: [bootstrap/js/index.esm.js](https://github.com/twbs/bootstrap/blob/a81f11a1a98db198bb66def43f58475141fac266/js/index.esm.js#L10) and [bootstrap/js/index.umd.js](https://github.com/twbs/bootstrap/blob/a81f11a1a98db198bb66def43f58475141fac266/js/index.umd.js#L10) still have
```
import Carousel from './src/carousel'
```
which might need to updating to
```
import Carousel from './src/carousel/carousel'
```

**Comment by Johann-S** [comment]
Thanks @bershanskiy 👍 The rewrite of the carousel is still in progress

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
