### PR TITLE
Add equal-width columns for flexbox grid

### PR DESCRIPTION
**Pull request by bassjobsen**
see: https://github.com/twbs/bootstrap/issues/17131

suggested documentation:

```
### Example: Auto-width columns

Use the `col-{breakpoint}-auto` classes to create rows with 5, 7, 8, and 10 columns. Each column gets the same width.

<div class="bd-example-row">
{% example html %}
<div class="row">
  <div class="col-md-auto">1</div>
  <div class="col-md-auto">2</div>
  <div class="col-md-auto">3</div>
  <div class="col-md-auto">4</div>
  <div class="col-md-auto">5</div>   
</div>
{% endexample %}
</div>
```

### CODE REVIEW

**Comment by cvrebert** [comment]
> create rows with 5, 7, 8, and 10 columns

Where do these numbers come from?

**Comment by bassjobsen** [comment]
@cvrebert good question. I think it should be  5, 7, 8, 9, 10, 11 being not divisors of 12

**Comment by cvrebert** [comment]
I'm obviously not mdo, but I'd perhaps suggest a different name (perhaps something like `.col-*-eq-width`) and describe it like:

> Use the `.col-{breakpoint}-eq-width` classes to create rows with an arbitrary number of columns (as opposed to the normal 12-column grid) where all columns are of the same width.

**Comment by bassjobsen** [comment]
I agree that `*-eq-width` is more descriptive.

**Comment by browner12** [comment]
i personally like the `col-md-auto` naming convention. or maybe even `col-md-flex` since this option is specific to users with flexbox enabled.  my 2 cents on that.

i don't think you need to specifically say what number of columns this can create, because essentially it can create **any** number of columns.

but why are we locking ourselves into `flex: 1; ` here?  wouldn't it be more beneficial to give users the option to decide their own flex value?  this would open up the ability to have columns with different flexible widths. something along the lines of `col-md-flex-1`, `col-md-flex-2`. Then the question is how high do you go, but i think you could find a sensible max. in edge cases, users could override with their own classes or local styling.

**Comment by jamespegg** [comment]
I think it just needs to be `flex : 1`. My use case is that I've got a variable number of columns, so I'd want to use something like `col-md-flex` to make a variable width column that takes up the available space.

I'm guessing there's no non-flexbox fallback, so shouldn't this feature check whether flexbox is enabled?

**Comment by mdo** [comment]
Support for equal width flexbox columns was added in #19099.

**Pull request closed without merging**
