### PR TITLE
Progress page: remove toggle animation button

### PR DESCRIPTION
**Pull request by XhmikosR**
We don't use the same approach with a button on the Placeholders page.

Preview: https://deploy-preview-34787--twbs-bootstrap.netlify.app/docs/5.1/components/progress/#animated-stripes

### CODE REVIEW

**Review by ffoodd — APPROVED** [review]
LGTM! Was this done on purpose for accessibility, maybe? Ping @patrickhlauke just in case 😄

**Comment by patrickhlauke** [comment]
> LGTM! Was this done on purpose for accessibility, maybe? Ping @patrickhlauke just in case 😄

nah, i'm pretty sure that was well before my time, and it was there mainly to dynamically demonstrate how adding the class started the animation. no concerns with removing it (as this obeys `prefers-reduced-motion` which in my book counts as a mechanism to pause/stop/hide animations)

**Comment by ffoodd** [comment]
:shipit:

**Comment by XhmikosR** [comment]
The main reason for having the toggle button is that this animations are not GPU accelerated thus they crippled performance on low-end devices.

But since we do not have a button in Placeholders, this makes things consistent . We can bring it back if needed.

**Pull request merged**
