### PR TITLE
Switch to `stylelint-config-bootstrap`

### PR DESCRIPTION
**Pull request by ntwb**

### CODE REVIEW

**Comment by ntwb** [comment]
There is a handfull, ~10 rules that differ between the `.stylelintrc` and `stylelint-config-bootstrap`, I'm going to go through those shortly and update accordingly.

I've not deleted `.stylelintrc` from this pull request at this stage and am keeping it as a  comparison check, in the end this file would no longer be required.

**Comment by cvrebert** [comment]
Wrong target branch. You want v4-dev, not v4-npm.

**Comment by cvrebert** [comment]
Oh, so that was intentional. Hmm. Not clear that that branch will actually get merged. And PRing against a PR is weird.
I'll try to cherry-pick this into v4-dev tomorrow then.

**Comment by cvrebert** [comment]
@ntwb Could you add https://www.npmjs.com/~twbs to the collaborators of https://www.npmjs.com/package/stylelint-config-bootstrap ?

**Comment by ntwb** [comment]
> And PRing against a PR is weird.

That's why the branch name is `pacth-1`, my Git Foo couldn't get the branch correct to PR against the PR, so GitHub UI got that sorted 😝 

> Could you add https://www.npmjs.com/~twbs to the collaborators of https://www.npmjs.com/package/stylelint-config-bootstrap ?

Done

> I'll try to cherry-pick this into v4-dev tomorrow then.

The PR should be able to be merged directly into `v4-npm`, as none of that is in `v4-dev` yet is it?

Either or though, pretty easy and straight forward PR, can be closed and redone as needed etc

**Comment by mdo** [comment]
Closed #20332, so closing this.

**Comment by ntwb** [comment]
Per https://github.com/twbs/bootstrap/pull/20332#issue-166660947:

> _"Lint Sass before trying to compile (with stylelint over scss-lint)"

The PR that has been created in #22045 continues to use `scss-lint` rather than stylelint

Before I delete this branch and make any decisions on what to do with the `stylelint-config-bootstrap` repo and NPM package I'd just like to confirm that this is what is intended, to continue using scss-lint and not stylelint? 

cc @mdo @cvrebert

**Comment by bardiharborow** [comment]
@ntwb per my comment in #22045, we still intend to switch to stylelint, it's just too many changes to juggle for that specific PR if I also need to go through a write a stylelint config (this PR seems to indicate that the `stylelint-config-bootstrap` config is not complete; if that's not the case, or if that can be finished; then I can easily get the stylelint changes into that PR before it merges).

**Comment by ntwb** [comment]
@bardiharborow The `stylelint-config-bootstrap` config is as complete as it can be at the moment, it needs iteration but that is not an obstacle.

If there are issues with the config, we can update the config and release an update, feedback and contribution from the Bootstrap team for any of this would be fantastic.

**Pull request closed without merging**
