### PR TITLE
Minor grammar tidy-up on Utilities doc page

### PR DESCRIPTION
**Pull request by davidjb**
For clarity and readability

### CODE REVIEW

**Comment by cvrebert** [comment]
Leave the dash as-is; see https://github.com/twbs/bootstrap/pull/17625#discussion_r40520035

**Comment by davidjb** [comment]
Seems I've fallen into the same readability issue as mentioned over there.  It's easier to see (at least now that I'm looking for it) when rendered @ http://v4-alpha.getbootstrap.com/components/utilities/ but hard to notice when it's a monospaced font in a terminal.  Not many people would be referring to the docs in this way so that seems fine.  I'll adjust the PR.

**Comment by davidjb** [comment]
Adjusted.  It's just the removal of one superfluous word.

**Comment by cvrebert** [comment]
Thanks!

**Pull request merged**
