### PR TITLE
Prevent extraneous whitespace around date time inputs in Webkit

### LINKED ISSUE #34433: Date Input has incorrect sizing in Safari
In Safari 14.1 (on macOS Big Sur) the following will render 'incorrectly' on Safari - the date input element is over-sized.

The issue isn't related to having another column or another field - but having a regular text input helps to highlight the sizing bug.

FF seems to render it correctly. 

```html
<div class="container">
<div class="row g-3">
  <div class="col">
    <input type="text" class="form-control" placeholder="First name" aria-label="First name">
  </div>
  <div class="col">
    <input type="date" class="form-control"">
  </div>
</div>
</div>
```

### LINKED ISSUE #37313: Fix `.form-control` padding for date/time inputs
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Some browsers (for example, FF and Chrome) add extra "padding" to date/time inputs when calculate area of visible text. As result, part of text is hide:

изображение

Need fix `padding-right`:
~~~scss
[type="date"].form-control,
[type="time"].form-control,
[type="datetime"].form-control,
[type="datetime-local"].form-control {
    padding-right: ...;
}
~~~
`+` same fixes for `.form-control-sm` and `.form-control-lg`

### Reduced test cases

~~~scss
[type="date"].form-control {
    width: 8rem;
}
[type="date"].form-control-sm {
    width: 7rem;
}
[type="time"].form-control {
    width: 5rem;
}
[type="time"].form-control-sm {
    width: 4.5rem;
}
[type="datetime"].form-control,
[type="datetime-local"].form-control {
    width: 11.5rem;
}
[type="datetime"].form-control-sm,
[type="datetime-local"].form-control-sm {
    width: 10.5rem;
}
~~~
~~~html
<input type="datetime-local" name="from" class="form-control" value="2022-12-28 13:30">
<input type="time" name="to" class="form-control" value="13:30">
<input type="datetime-local" name="from" class="form-control form-control-sm" value="2022-12-28 13:30">
<input type="time" name="to" class="form-control form-control-sm" value="13:30">
<input type="datetime-local" name="from" class="form-control form-control-lg" value="2022-12-28 13:30">
<input type="time" name="to" class="form-control form-control-lg" value="13:30">
~~~

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v.5.*

### PR DESCRIPTION
**Pull request by stephenreay**
Fixes #34433, closes #37313.

### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

- Before: https://codepen.io/stephenreay/pen/dyexpoG
- After: https://codepen.io/stephenreay/pen/NWMQRxy

### Related issues

twbs/bootstrap#34433

### CODE REVIEW

**Comment by mdo** [comment]
LGTM! Thoughts @julien-deramond?

**Review by julien-deramond — COMMENTED** [review]
LGTM as well! Tried it on the latest versions of FF, Chrome, Safari and Edge + all Safari version until 13 (there was an issue with the rendering of CodePen with the 12 but I suppose it'll work as well).

@stephenreay In order to merge this PR could you please just update the corresponding value of `FAIL ./dist/css/bootstrap.css: 29.5KB > 29.5KB (gzip)` in `.bundlewatch.config.json` to set it to `"maxSize": "27.75 kB"`.

**Comment by stephenreay** [comment]
> LGTM as well! Tried it on the latest versions of FF, Chrome, Safari and Edge + all Safari version until 13 (there was an issue with the rendering of CodePen with the 12 but I suppose it'll work as well).
> 
> @stephenreay In order to merge this PR could you please just update the corresponding value of `FAIL ./dist/css/bootstrap.css: 29.5KB > 29.5KB (gzip)` in `.bundlewatch.config.json` to set it to `"maxSize": "27.75 kB"`.

Assuming you meant `29.75`, done.

**Review by julien-deramond — APPROVED** [review]

**Comment by Turbo87** [comment]
should this be added to the Reboot file similar to how it was done in https://github.com/twbs/bootstrap/pull/30269?

**Pull request merged**
