### PR TITLE
Refactor utility spacer to use a multiplier instead of hardcoded value

### PR DESCRIPTION
**Pull request by kkirsche**
Fix for: refactor spacer utilities Sass to include a variable-based multiplier instead of a hard-coded one.

### CODE REVIEW

**Comment by kkirsche** [comment]
I did consider refactoring down with `$margin-x` / `$margin-y` for example (similar for padding) which included the formula instead of just replacing the hard coded value to reduce line lengths if that is of benefit.

**Comment by kkirsche** [comment]
Rebased

**Comment by kkirsche** [comment]
Rebased

**Comment by kkirsche** [comment]
If this is how you want the code per hound I'll change it but I assumed you wanted them aligned like you had originally done...

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by RsD0p9BK** [comment]
How about
```
.mb1 instead .m-b
.mb3 instead .b-a-lg
.mx1_2 instead .m-x-md 
```

**Comment by mdo** [comment]
Unsure how much this actually buys us tbh. I'm inclined to punt on adding the math aspect just to keep it super simple.

**Comment by kkirsche** [comment]
So is it just a change in direction / goals for the classes or the implementation?

**Comment by cvrebert** [comment]
This overlaps with #18185.

**Comment by mdo** [comment]
Yeah, I just want to keep things as simple as possible for as long as possible. The math work as-is here, but folks might want to change the scale themselves. It makes less sense to me that we should engineer some flexibility when we don't know what folks want to be flexible about these classes.

Thanks though!

**Pull request closed without merging**
