### PR TITLE
[WIP] Adding in variables used in each component.

### PR DESCRIPTION
**Pull request by jhechtf**
The goal of this merge request is to add in the variable names used by each component to give people an easier to access way to theme bootstrap. This is a work in progress, as each component involves me reading through the code to get an appropriate determination of what they do.

| Status | Component | Comments | 
| --- | --- | ---|
| ✅ | alerts | |
| ✅ | badge | |
| ✅ | breadcrumb | |
| ✅ | button-group | |
| ✅ | buttons | |
| ✅ | card | |
| ✅ | carousel | |
| ✖ | collapse | |
| ✖ | dropdowns | |
| ✖ | forms | |
| ✖ | input-group | |
| ✖ | jumbotron | |
| ✅ | list-group | |
| ✖ | media-object | |
| ✖ | modal | |
| ✖ | navbar | |
| ✖ | navs | |
| ✖ | pagination | |
| ✖ | popovers | |
| ✅ | progress | |
| ✖ | scrollspy | |
| ✅ | spinners | |
| ✖ | toasts | |
| ✖ | tooltips | |
| ✅ | code | |
| ✅ | figures | |
| ✅ | close-icon | |

### CODE REVIEW

**Comment by XhmikosR** [comment]
@jhechtf: this is wrong again... You need to rebase against upstream/master.

**Comment by XhmikosR** [comment]
Also, to be honest, I'm not sure I like the maintenance weight this adds.

**Comment by jhechtf** [comment]
@XhmikosR 
In response to the maintenance weight, it really wouldn't add much so long as people follow the same pattern that I am currently seeing in the `_variables.scss` file, which is where I'm pulling the values from. It would just have to be an expectation for anyone in the future who introduces a new variable to make sure that they document and describe its use, which I don't think is unreasonable, especially considering that Bootstrap is as much a stand-alone CSS/Javascript framework as it is a themeable base.

As for the rebase -- can you please do me a favor and clarify what you mean by rebasing against upstream/master? in the last ticket you told me to remove anything that was unrelated. I took that to mean "remove anything that isn't from my changes." Assuming I rebase from upstream master, what are types of changes are ones that I should keep, and what are ones I should remove? I'm asking for clarity as I'd really rather like to only do this once more before going back to documenting the other components.

**Comment by XhmikosR** [comment]
But we'd need to update those manually, which is an extra things for us.

Sure, I can automate it probably with Hugo's `readFile` and some filtering, but I'm still not sure this is worth it.

/CC @twbs/css-review

**Comment by jhechtf** [comment]
I really don't think "if you add / edit / remove a variable from the `_variables.scss` file, you need to make sure to add/edit/remove the entry in the corresponding Variables table to reflect the changes" is asking too much, especially since I am going to be giving the brunt of most of that work, unless the bootstrap variables change very suddenly in 4.4 or beyond. Even then I'd be willing to go through this all again to make sure that the tables are updated for future use, because documenting how these values interconnect is important.

**Comment by XhmikosR** [comment]
It is a lot of work unless it's automated, and I speak from experience, when I say that anything not automated will be a problem.

Leaving this to @twbs/css-review . I'd personally wouldn't add this, unless it's properly automated.

**Comment by MartijnCuppens** [comment]
I like the idea of additional variables documentation, but this approach will be hard to maintain. We'll probably get out of sync at some point, because it 'll be easy to miss a variable because they can be listed anywhere in the docs. I'm more in favour in something that's automated (and simple). That 'll be quite a challenge I guess.

**Comment by jhechtf** [comment]
I'm all ears if anyone has another way to build the documentation.

**Comment by MartijnCuppens** [comment]
@JLammeer once did a pretty nice job here: https://jlammeer.github.io/bootstrap-sassdoc/

But that lead to a pretty huge variables file which was mad it a bit more unclear on the `scss` side because of the amount of comments:
https://github.com/JLammeer/bootstrap-sassdoc/blob/master/documented-items/_variables.scss

We don't have an out of the box solution yet, it looks like a lot of people are looking for this or want to create a solution for Bootstrap. A simple solution we can plug into Hugo would be ideal I guess.

**Comment by jhechtf** [comment]
Let me look into Hugo (never used before) and see if I can find something.

**Comment by XhmikosR** [comment]
It's doable with `readFile` like I mentioned. Then we need to find a way to filter only the related variables, which can be done with a specific comment in _variables.scss, like `// ** Tooltips` or similar.

**Comment by MartijnCuppens** [comment]
Thanks @jhechtf, you can ping us when you got something. I'm going to close this PR for the maintenance issues we mentioned above.

**Pull request closed without merging**
