### PR TITLE
CI: specify `OPENCOLLECTIVE_HIDE: true`

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by ffoodd** [comment]
Does it simple drop the funding message in console?

**Comment by XhmikosR** [comment]
Yeah

**Comment by XhmikosR** [comment]
TBH this shouldn't be needed https://github.com/opencollective/opencollective-postinstall/blob/d6627320e81bc4effa140f04998aab9ed7a064fa/index.js#L7

But apparently nodemon is using their own implementation https://github.com/remy/nodemon/blob/f74f4a20772b5d96506386d2e35569bc3e2c1811/bin/postinstall.js#L4

**Comment by XhmikosR** [comment]
This might not be needed if https://github.com/remy/nodemon/pull/1800 is merged

**Pull request closed without merging**
