### PR TITLE
Toast z-index

### LINKED ISSUE #34028: Toast is hidden under offcanvas
If you have a offcanvas open and show a toast then the toast gets hidden under the offcanvas. I expected to the toast to always be visible on top of everything else.

Browser: Firefox 88, Chrome 90, Edge 92
Demo: https://jsfiddle.net/zrtv9f0d/

### PR DESCRIPTION
**Pull request by jasonsperske**
defines a z-index for toasts and updated the docs to use it.

---

Fixes #34028

### CODE REVIEW

**Review by ffoodd — COMMENTED** [review]
Thanks for drafting this! 💪

A few concerns here :

- You're setting `z-index` but it doesn't have a `position` on its own.
- Also setting it to the highest value doesn't feel right: what if a modal is opened while toast is shown, for example?

I think `z-index` utilities (in progress in #31486) would be a more consistent solution.

Any thought?

**Comment by jasonsperske** [comment]
> * You're setting `z-index` but it doesn't have a `position` on its own.
I hadn't noticed that, the `position-fixed` class seem universal to any use of "Toast" that I would assume people are expecting, so placing it's css properties in .toast-container should seem like a logical fit, but then there is the issue of sizing. 

> * Also setting it to the highest value doesn't feel right: what if a modal is opened while toast is shown, for example?
> I think `z-index` utilities (in progress in #31486) would be a more consistent solution.

I looked at `z-index` utilities and that would satisfy this use case and give flexibility to the page author without requiring anyone to update varibles.scss file and recompile bootstrap.  If that's the preferred solution I'm happy to abandon the draft and close this ticket.

**Comment by XhmikosR** [comment]
Please do not include any dist files and make sure tests pass  before pushing.

**Comment by mdo** [comment]
Closing as stale and with a dirty diff.

**Pull request closed without merging**
