### PR TITLE
Keep rounded corners for the first `.btn` in vertical button group

### LINKED ISSUE #31255: Vertical button group variations example has an un-rounded top
> On the button group page, the last example under the vertical variations has an un-rounded top.

[Comment](https://github.com/twbs/bootstrap/pull/31201#pullrequestreview-442765111) by @mdo and [Codepen](https://codepen.io/rohit2sharma95/pen/eYJMjoM).

This is because the current selector to remove the rounded corner is
https://github.com/twbs/bootstrap/blob/49934b2bba514582c92bd423f94ddbf890bc3a66/scss/_button-group.scss#L137
And the label in the button group is not the first child (First child is the input in real)

### PR DESCRIPTION
**Pull request by rohit2sharma95**
Closes #31255

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
This could introduce other issues like https://codepen.io/MartijnCuppens/pen/eYZKjPj?editors=1100 where you have a combination of buttons and links.

**Comment by mdo** [comment]
Hmm yup, and I tried `> .btn:not(:first-child):not(:first-of-type)` and got another problem still. Brain dead right now, will need to think more about it.

Screen Shot 2020-09-16 at 10 23 20 PM

**Comment by rohit2sharma95** [comment]
This can be achieved via **[Subsequent-sibling combinator](https://www.w3.org/TR/selectors/#general-sibling-combinators)**
[In this way](https://github.com/twbs/bootstrap/compare/main...rohit2sharma95:vertical-button-group-updates), I think :thinking:
@MartijnCuppens

**Comment by rohit2sharma95** [comment]
Ping @mdo 🙂

**Review by MartijnCuppens — APPROVED** [review]
Wow, that's a neat solution @rohit2sharma95, Thanks!

**Comment by MartijnCuppens** [comment]
Gonna ask for a 2nd approval from @twbs/css-review here.

**Review by ffoodd — APPROVED** [review]
Very nice Indeed 👌

**Review by mdo — APPROVED** [review]

**Comment by XhmikosR** [comment]
This has an effect on our docs sidebar:

| Before | After |
| ------- | ----- |
| image | image |

Is this still ready to merge @MartijnCuppens @mdo ?

**Pull request merged**
