### PR TITLE
Assign Multiple variables the same value

### PR DESCRIPTION
**Pull request by aditya1906**
Hi, In some of the js source file I felt it was better to group assign the same value in a much cleaner way. In this way the variables that are assigned the same values are grouped together, And it is easier to find out which variables are assigned the same value.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Please don't open this kind of PRs.

**Comment by aditya1906** [comment]
You want a single commit PR?

**Comment by XhmikosR** [comment]
This kind of changes is not something we are interested in, sorry. You can test it locally *before* opening any PR with `npm t`.

**Comment by aditya1906** [comment]
Can you give me suggestions in order to contribute to open source project like bootstrap. Which also interests you to the changes I make to the source code?

**Comment by Johann-S** [comment]
Hi @aditya1906,

We have a lot of issues marked as `js` so feel free to tackle some of them: https://github.com/twbs/bootstrap/labels/js

**Pull request closed without merging**
