### PR TITLE
v4 - Use doge instead of css for <pre> example

### PR DESCRIPTION
**Pull request by jamiebuilds**
When reading through this it looked like another code example, so to make it look extra example-y I made it doge.

### CODE REVIEW

**Comment by kkirsche** [comment]
What is "doge"?

**Comment by Murilirum** [comment]
It's an internet meme that @thejameskyle hasn't learned is irrelevant these days.

**Comment by thejameskyle** [comment]
@Murilirum http://i.imgur.com/oSYafs2.gif

**Comment by Murilirum** [comment]
@thejameskyle I love my doge, don't you worry. https://github.com/returnString/DogeSharp

**Comment by patrickhlauke** [comment]
Aeh...it's a no from me.

**Comment by mdo** [comment]
I'm a no on the doge thing, but we can clarify it I imagine. Perhaps rename the example code to `.example-element` instead of changing the text all together?

**Comment by thejameskyle** [comment]
Fixed

**Pull request merged**
