### PR TITLE
Update jQuery to v2.2.4.

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @cvrebert

### CODE REVIEW

**Comment by yasinkocak** [comment]
update the shiplist https://github.com/twbs/bootstrap/issues/18480

**Comment by chicheng** [comment]
jQuery v2.2.4 was released last week: http://blog.jquery.com/2016/05/20/jquery-1-12-4-and-2-2-4-released/

**Comment by franz-josef-kaiser** [comment]
Four weeks ago, [3.0.0 was released](https://github.com/jquery/jquery/releases).

**Comment by cvrebert** [comment]
@franz-josef-kaiser See #16834 and #19433. And in general, please open new issues instead of posting comments on old, tangentially-related closed ones. Thanks.

**Pull request merged**
