### PR TITLE
v4: Flexbox navbar

### LINKED ISSUE #18053: v4 navbar with container inside results in extra padding
I build a simple navbar like shown in the docs with the container inside: http://v4-alpha.getbootstrap.com/components/navbar/#containers

The problem is that in mobile layout, as soon as the container has the size of the page, the content inside the navbar does no longer align with the normal content of the page.

Here the example: http://jsbin.com/fisovineku/1/edit?html,output

a simple workaround is to remove the padding of the navbar but that would require another class on the navbar so it isn't a nice automatic solution.

### LINKED ISSUE #18115: v4: light vs dark in navbars and cards
I found that the navbar component uses the `navbar-light`, `navbar-dark` classes to create link colors. The output of this classes can be set with the `$navbar-light-` and `$navbar-dark-*` variables.
The card modules uses a `.card-inverse` to set a light font.
Should it be more consequent when the card module also got a `card-light` and `card-dark` class? Including some variable to set them?

Also the navbar use the contextual backgrounds classes, shouldn't the card modules use these classes too? Which requires having contextual border classes too.

### LINKED ISSUE #18875: Flexbox navbar elements wrap onto new line instead of inline
Meta list: #18467

[Test case](http://jsbin.com/jeyudiw/edit?html,css,output) 

It appears that there is not an implementation for nav items that responds to `$enable-flex: true;`.  This may not be in-scope, but wanted to mention it.

NOTE that it is not based on compiled css with `$enable-flex: true;` as that doesn't exist in `dist`.   Nonetheless, I see the same behavior in a flex enabled scenario.  Here's a screenshot of the same thing rendered with `$enable-flex: true;`:

test_ _bootstrap_material_design

### LINKED ISSUE #20116: Support for text-only items in navbar
I have the same issue shown here:
https://github.com/twbs/bootstrap/issues/11735

The conclusion stated was that navbar-text is not meant for the li items in a list.
".navbar-text is used directly inside div class="navbar-collapse""
"The .navbar-text is not meant for placement in nav components."

Therefore, when you need an li that is not a link, but is just text, we don't have a class as far as I know that can be applied to ensure it aligns properly in both non-collapsed and collapsed.

It seemed like navbar-text is part way there, but doesn't align properly in collapsed mode.  A new navitem-text or something similar would be great to handle this scenario.

### LINKED ISSUE #20766: Sugestion: `navbar-center`
It seems that there is alot of people wanting to have their navbars centered on the page, may be good to include a css class such as navbar-center that will center all the element in the navbar.

`text-center` on the navbar div doesn't work as it meant to only center text and not all elements.

Reference:
http://stackoverflow.com/questions/21980660/bootstrap-3-align-navigation-to-center
http://stackoverflow.com/questions/18777235/center-content-in-responsive-bootstrap-navbar

### LINKED ISSUE #20937: Further navbar refinement
Alpha 5 is seeing a major navbar update, but it's still not ready for prime time. I'm struggling to figure out a solid way to build this right now that works for all the components, responsive behaviors, and the default/flex variations.

With some of the other Alpha 6 changes I have planned, I'm hoping to get these remaining navbar issues in our next release:
- [ ] #18053: Container adding extra padding for mobile sizes
- [ ] #18115: Revisit light/dark nomenclature revisited
- [ ] #18875: Flexbox support added
- [ ] #20116: Better `.navbar-text` support
- [ ] Migration docs added

### LINKED ISSUE #21012: v4 alpha 5 - navbar toggler inconsistencies
It seems that `.navbar-toggler` only gets a `background-image` applied if it is in a `.navbar-dark` or `.navbar-light` for example.  This doesn't seem right - it should always get a background-image, and there should be a class to turn this off.  Otherwise we can't use FontAwesome icon easily with `<i class="fa fa-bars"></i>`.

### LINKED ISSUE #21361: Aligning collapsible button to the right makes the list messy
Trying to make the collapsible button of the navbar aligned to the right and keeping the brand to the left makes the list messy like in this example (tested on latest chrome):

https://plnkr.co/edit/gHA1Ea7JhYX2eWSyOgWp?p=preview

As you can see the "home" stays on the top and the rest moves to the left only when it's fully collapsed...

### LINKED ISSUE #21364: v4 examples, empty navbars.
Despite #17532 being [marked as resolved and closed](https://github.com/twbs/bootstrap/issues/17532#issuecomment-254742079), visiting https://v4-alpha.getbootstrap.com/examples/navbar-top-fixed/ gives a navbar containing nothing but the toggler:

```
    <div class="pos-f-t">
      <div class="collapse" id="navbar-header">
        <div class="container-fluid bg-inverse p-1">
          <h3>Collapsed content</h3>
          <p>Toggleable via the navbar brand.</p>
        </div>
      </div>
      <div class="navbar navbar-light bg-faded navbar-static-top">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-header" aria-controls="navbar-header" aria-expanded="false" aria-label="Toggle navigation"></button>
      </div>
    </div>
```

The parent documentation page features a [screenshot of a navbar containing many different items](https://v4-alpha.getbootstrap.com/examples/screenshots/navbar-fixed.jpg) but here is what I get:
image

### PR DESCRIPTION
**Pull request by mdo**
Following up on #21389, this PR is a WIP for adding the flexbox navbar. It started off as a late night experiment again with `display: table`—which was pretty awesome mind you—and got me thinking heavily about flex options. Given we're going all flex now, this approach gets even easier.

Still a ton to do, but wanted to open this sooner than later.

---

### Done
- Fixes #18875 and fixes #18875 with move to flexbox-based approach.
- Fixes #20937 by closing out all the below issues.
- Moves `.navbar-toggleable-*` from the `.collapse` to the `.navbar`, making it even easier to toggle content as needed.
- Fixes #21364 by updating all examples to use new navbars.
- Revamp navbar docs to push responsive implementation from the get-go instead of at the end. Also adds new examples.
- Fixes #21361 by changing how togglers works. Alignment has changed and the icon is now a separate element, `.navbar-toggler-icon`, within `.navbar-toggler`.
- Adds left and right absolutely positioned toggler variations.
- Fixes #20766 with ability to center navbar links (with example in docs)
- Fixes #18115: Renamed `.navbar-dark` to `.navbar-inverse` to match nomenclature of `.bg-inverse` and `.card-inverse`. `.navbar-light` is still the default class.

### Todo
- [x] Fixes #21012 Better toggler styling and alignment
- [x] Fixes #18053: Container adding extra padding for mobile sizes
- [x] Fixes #20116: `.navbar-text` is supported and documented properly.
- [x] Migration docs

### CODE REVIEW

**Comment by mdo** [comment]
Updated the `examples/navbar/` to be `examples/navbars/` to show some variations to things the styling and subcomponents within a navbar.

screen shot 2016-12-21 at 2 31 11 pm

**Comment by mdo** [comment]
Reminder for later, I hacked together a bad sidebar drawer.

```
### Drawer

Add a `.collapse` somewhere on your page, give it an `id`, and add the modifier classes to turn it into a drawer: `.width.collapse-drawer`.

{% example html %}
<div class="collapse width collapse-drawer" id="navbarToggleDrawer">
  <div class="bg-inverse p-4">
    <h4 class="text-white">Navbar drawer</h4>
    <p class="text-muted">
      This is an offcanvas drawer that can be toggled via our Collapse plugin. It's a little hacky, but it works!
    </p>

    <button class="btn btn-outline-info" type="button" data-toggle="collapse" data-target="#navbarToggleDrawer" aria-controls="navbarToggleDrawer" aria-expanded="false">Close</button>
  </div>
</div>
<nav class="navbar navbar-dark bg-inverse">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleDrawer" aria-controls="navbarToggleDrawer" aria-expanded="false" aria-label="Toggle navigation"></button>
</nav>
{% endexample %}
```

```sass
// Somewhat hacky solution to the drawer
.collapse-drawer {
  position: fixed;
  top: 0;
  left: 0;
  bottom: 0;
  z-index: 1000;
  display: block;
  height: 100%;
  width: 16rem !important;
  margin-left: -16rem;
  background-color: $gray-dark;
  @include transition(transform .2s ease-in-out);

  &.show,
  &.collapsing {
    transform: translateX(16rem);
  }
}
```

**Comment by mdo** [comment]
Here's an updated screenshot and [live demo in a JS Bin](https://output.jsbin.com/sapiyok) for folks to play with.

screen shot 2016-12-21 at 10 25 18 pm

**Comment by jipexu** [comment]
coool !!
in the example  https://output.jsbin.com/sapiyok 
the Centered nav only (is NOT centered @ small screen) is it a choice or little mistake ?

thanks

**Comment by daminufe** [comment]
Sweet! Looking forward to implement it on my project.

**Comment by mdo** [comment]
> the Centered nav only (is NOT centered @ small screen) is it a choice or little mistake ?

By choice; this is easily customized though with a different utility class.

**Pull request merged**
