### PR TITLE
Button cleanups

### PR DESCRIPTION
**Pull request by svenheden**
I've cleaned up two minor things in the Button component...
- Removed a redundant `hasClass()` check
- Merged two jQuery `is()` calls where one is sufficient

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 84ac267f620b1dad8e70ef4b516c384cb12c25f9
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/73547706

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
LGTM.

**Comment by XhmikosR** [comment]
@cvrebert: LGTM. Should I merge this manually?

**Comment by cvrebert** [comment]
Sure. Please also port to v4 if the changes are still applicable there.

**Pull request closed without merging**
