### PR TITLE
Manually optimize SVGs

### PR DESCRIPTION
**Pull request by MartijnCuppens**
- Removal redundant `fill`, `clip-rule` & `fill-rule` attributes.
- Removal redundant groups
- Removal redundant clip paths
- Removal redundant path. The letter B was rendered twice, causing the edges to become a little crispy.
- Shorter filter & fill names

Before:
- https://v5.getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo.svg
- https://v5.getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo-white.svg
- https://v5.getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo-black.svg

After:
- https://deploy-preview-32187--twbs-bootstrap.netlify.app/docs/5.0/assets/brand/bootstrap-logo.svg
- https://deploy-preview-32187--twbs-bootstrap.netlify.app/docs/5.0/assets/brand/bootstrap-logo-white.svg
- https://deploy-preview-32187--twbs-bootstrap.netlify.app/docs/5.0/assets/brand/bootstrap-logo-black.svg

### CODE REVIEW

**Review by ffoodd — APPROVED** [review]
Nice catch :+1:

**Comment by XhmikosR** [comment]
Can you maybe change any IDs to be more specific? Usually it's not an issue, but I'm not sure if it's OK when including multiple SVGs and we end up with the same IDs. If it doesn't change anything, just ignore this comment :)

PS. I'd like @mdo's approval just so that we are safe since he created these in the first place.

**Comment by XhmikosR** [comment]
BTW after this lands, we need to update any icons in the blog and the icons repo.

**Review by XhmikosR — APPROVED** [review]

**Comment by mdo** [comment]
The after doesn't look right to me on latest iOS.

image

**Comment by MartijnCuppens** [comment]
Pushed the fix for iOS:
image

**Comment by mdo** [comment]
Ah, I see what's changed now. The extra B was intentional to give it a 1px white stroke, while the rest of the B had a gradient. Just an extra bit of styling. Thoughts on keeping/cutting?

**Comment by MartijnCuppens** [comment]
> The extra B was intentional to give it a 1px white stroke

I've just added the stroke, it's barely visible, but I can see it 2x zoom:

To be honest, I don't really see the difference between with or without the stroke:
image


image

**Review by mdo — APPROVED** [review]

**Comment by XhmikosR** [comment]
@MartijnCuppens feel free to merge when squashing; not sure what the commit message should be after your changes :)

**Pull request merged**
