### PR TITLE
Detach accordion from card

### PR DESCRIPTION
**Pull request by Johann-S**
- [x] Add unit test

/CC : @mdo @bardiharborow 

Closes : #22025

### CODE REVIEW

**Comment by Johann-S** [comment]
For me everything is done here @mdo except the documentation

**Comment by Johann-S** [comment]
Only JavaScript here @bardiharborow no CSS for the labels

**Comment by mdo** [comment]
> Only JavaScript here @bardiharborow no CSS for the labels

Whenever something affects or is related to the CSS (in this case the `.collapse` classes), we generally apply the CSS label :). This does need the JS one, too, though!

**Comment by mdo** [comment]
I'll take a stab at adding some docs examples here shortly.

**Pull request merged**
