### PR TITLE
Resolves error preventing the dropdowns from working in the docs

### LINKED ISSUE #20410: Dropdown examples in docs are broken
http://v4-alpha.getbootstrap.com/components/dropdowns/

Clicking any dropdown button on this documentation page gives you only a jQuery error:
<code>
Uncaught Error: Syntax error, unrecognized expression: #
</code>

### PR DESCRIPTION
**Pull request by judetucker**
Resolves #20410

### CODE REVIEW

**Comment by bardiharborow** [comment]
Maybe I misunderstand this patch, but I can't see how this fixes #20410. You're only changing highlighted code, not anything which is actually run.

**Comment by bardiharborow** [comment]
This fixes all the other dropdowns on the page, but breaks the actual example you are changing.

**Comment by judetucker** [comment]
Thanks for your feedback on this PR. I believe that the docs are supposed to show those dropdowns as forced open. See v3 docs http://getbootstrap.com/components/#dropdowns they don't open/close here either.

As far as the actual code in the example goes, I can verify that it works when used in a project. http://codepen.io/judetucker/pen/GqXpRV

**Comment by bardiharborow** [comment]
The commit edits the `And with <a> elements:` example, in order to fix #20410 which is about a conflict which causes other examples on the page (e.g. `The best part is you can do this with any button variant, too:`) to not work. I'm well aware that the first two examples are locked open, my point is that your commit fixes other examples on the page but actually breaks the link on the `And with <a> elements:` example.

**Comment by judetucker** [comment]
I guess #20434 was better.

**Pull request closed without merging**
