### PR TITLE
Use `defineJQueryPlugin` method only in the base component

### LINKED ISSUE #34103: Remove duplicate `DOMContentLoaded` events
Is this normal?

Captura de tela de 2021-05-14 00-04-56

Bootstrap 5.0.0

_Originally posted by @o-alquimista in https://github.com/twbs/bootstrap/discussions/33980_

### PR DESCRIPTION
**Pull request by rohit2sharma95**
Fixes #34103

There are multiple duplicated `DOMContentLoaded` events attached to the document, they are not really needed. 

It is the very beginning of the idea, this approach may work IMO.
_:warning: Tests are not updated yet_

/CC @twbs/js-review for the early feedback :slightly_smiling_face:

### CODE REVIEW

**Comment by alpadev** [comment]
I could be wrong but when using a bundler there might be no global `bootstrap` object.

Another scenario that I could think of as problematic, is when the bundle is included after the document was loaded. Since you call `defineJQueryPlugin()` in the base-component, the other components might not yet defined since the base-component is a dependency and needed to be run upfront.

**Comment by rohit2sharma95** [comment]
> the other components might not be defined yet because the `base-component` is a dependency and needs to execute upfront and `onDOMContentLoaded` will run the code synchronously.

`onDOMContentLoaded` will run the code when the content has been loaded (It means the other plugins are also loaded). Is not it? :thinking:

**Comment by alpadev** [comment]
> `onDOMContentLoaded` will run the code when the content has been loaded (It means the other plugins are also loaded). Is not it? 🤔

```js
const onDOMContentLoaded = callback => {
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', callback)
  } else {
    callback()
  }
}
```

**Comment by alpadev** [comment]
I mean, I'm talking about edge cases here. (You may read this for more details: https://javascript.info/onload-ondomcontentloaded#domcontentloaded-and-scripts - specially the warning block.)
The problem with the synchronous execution IMO can be fixed on our end by wrapping the callback within `setTimeout` for example.

The first problem might be a bigger one, because we can't control if someone uses a bundler like webpack that wouldn't expose `bootstrap` on window (without us doing this explicitly).

**Comment by rohit2sharma95** [comment]
Closing in favor of #34158

**Comment by alpadev** [comment]
Oh I didn't mean to replace that PR, sorry @rohit2sharma95 :(

Figured you see some potential in refactoring our approach we add our components to jQuery (and as a side effect, also to get rid of the multiple listeners).

**Comment by rohit2sharma95** [comment]
NP @alpadev :heart:
Your PR was better, there is an issue related to it though #32664

**Pull request closed without merging**
