### PR TITLE
Remove precss plugin from webpack.md documentation

### PR DESCRIPTION
**Pull request by pmendelski**
AFAIK `precss` is not needed. Moreover I have tested it in a [side proejct](https://github.com/mendlik/webpack-starter/tree/master/webpack-starter-bootstrap-spa) and it broke some styling. 

For example when you add `precss` to [plugins](https://github.com/mendlik/webpack-starter/blob/7f32bfdca59aa0efa43e52d855a37f6e518edc2d/webpack-starter-bootstrap-spa/lib/webpack/config/styles.js#L43) the there is no `:root` styling in the result css file.

Fixes: #24949

### CODE REVIEW

**Comment by XhmikosR** [comment]
@Johann-S: LGTY?

**Comment by XhmikosR** [comment]
@Johann-S ping

**Review by Johann-S — APPROVED** [review]
LGTM 👍

**Comment by XhmikosR** [comment]
Well it seems the author has deleted the repository thus this cannot be rebased unless I do it manually.

So, closing for now. If anyone wants they can make a new PR.

**Pull request closed without merging**
