### PR TITLE
Docs: Use proper <button> instead of faked <a> element for popover example

### PR DESCRIPTION
**Pull request by patrickhlauke**
sidesteps #31391 but on principle should really use `<button>` here

### CODE REVIEW

**Comment by patrickhlauke** [comment]
only browser that currently seems to have a problem with this, from testing, is Safari. investigating further what its beef is...

**Comment by patrickhlauke** [comment]
ok, root of the problem seems to be the fact that Safari doesn't actually focus elements like `<button>` when you click them with the mouse. which is ... not ideal https://twitter.com/patrick_h_lauke/status/1289988990146211840

and Firefox/Mac copied that silly behavior too. good good. considering adding some basic additional behavior that also sets `focus()` when clicking these controls...

**Comment by patrickhlauke** [comment]
will likely keep this PR parked, do a separate PR for a potential cross-browser fix (or, well, a patch for Safari and Firefox on Mac), and hopefully this can then get merged when that fix is merged

**Comment by XhmikosR** [comment]
@patrickhlauke do we close this?

**Comment by patrickhlauke** [comment]
yeah as i get the feeling Apple are in no rush to change their behaviour in Safari (and Firefox will just copy what Safari does on macOS for "platform consistency"), and since I doubt we want to hack away at adding extra scripting that explicitly focuses the button after a click ... i think i'll just abandon this. annoying.

**Pull request closed without merging**
