### PR TITLE
Use embedded SVGs for carousel icons

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Part of https://github.com/twbs/bootstrap/issues/30052.

@XhmikosR, do you know a way to easily indent the svgs in the example code?

### CODE REVIEW

**Comment by XhmikosR** [comment]
My main concern with this is that the SVGs shouldn't be in the docs since we don't distribute the docs.

**Comment by MartijnCuppens** [comment]
> My main concern with this is that the SVGs shouldn't be in the docs since we don't distribute the docs.

From my perspective, the SVGs are just markup that are needed to make the carousel work.

**Comment by XhmikosR** [comment]
>From my perspective, the SVGs are just markup that are needed to make the carousel work.

I agree, but people might argue that the SVGs should be included.

I'm not against this, obviously, just trying to think what issues we might face.

**Comment by XhmikosR** [comment]
>@XhmikosR, do you know a way to easily indent the svgs in the example code?

Not sure about this right now, I'll need to play with it and see, because using `~` doesn't seem to have any effect.

**Comment by ffoodd** [comment]
About markup VS distribution, just a reminder that for now our close button is text-based and thus requires to get the markup. I think it's the same.

Apart from that, it'd be very easy to make SVGs downloadable from the docs without distributing them in our package: might be another way around this.

**Comment by mdo** [comment]
Closing for #31650.

**Pull request closed without merging**
