### PR TITLE
Set `cursor: default` on disabled `.form-check-label`

### LINKED ISSUE #35056: V5: Pointer incorrectly shown on disabled input's form-check-label if set via $form-check-label-cursor
If $form-check-label-cursor: pointer is set, the pointer shows up on the form-check-label even if the corresponding form-check-input is disabled. Pointer-events should probably be set to none, similar to how this works for the input.

Confirmed in Edge, Chrome & Firefox on W10.

Please see [this Pen](https://codepen.io/PatrickKennisnet/pen/gORQNBm) for an isolated case.

### PR DESCRIPTION
**Pull request by TheFakeCake**
This PR remove custom pointers on disabled form-check-label.
Another solution could be to add a `$form-check-label-cursor-disabled` variable to specify the label cursor when it's disabled.

Fixes #35056

### CODE REVIEW

**Comment by ffoodd** [comment]
@patrickhlauke Is there any concern regarding accessibility here ? It's disabled so I don't think, but prefer to double-check.

**Comment by patrickhlauke** [comment]
I'm more concerned here that `pointer-events:none` will make the label element "transparent" to clicks etc, so this may cause weirdness if there's something else behind the label - after this change, it'll suddenly receive clicks etc as if the label simply wasn't there.

If this is trying to address the visual change in cursor style, would it not make more sense to target *that* property?

**Comment by ffoodd** [comment]
You're right, that's risky without any reason. Improving our `cursor`s makes more sense.

@TheFakeCake, want to give it a try?

**Comment by TheFakeCake** [comment]
I agree the change is not optimal. The goal is to fix the form-check-label cursor showing when the `$form-check-label-cursor` variable is set but the input is disabled (see the mentioned issue in the first post).

Here are 3 (4?) other solutions I can see. I'm not a CSS nor a Bootstrap guru, so I'd like to have your opinions.

#### Solution 1

We replace the line I added in the commit with `cursor: default;`.
As @patrickhlauke stated, it makes more sense to target the `cursor` property.

```scss
form-check-input {
  // ...
  &[disabled],
  &:disabled {
    ~ .form-check-label {
      cursor: default; // Here
      opacity: $form-check-label-disabled-opacity;
    }
  }
}
```

#### Solution 2

We take **Solution 1** and put the `cursor` value in a new Sass variable like `$form-check-label-disabled-cursor`. This is more flexible and Bootstrap-like I guess.

```scss
// _variables.scss
$form-check-label-disabled-cursor:        default !default;
```
```scss
form-check-input {
  // ...
  &[disabled],
  &:disabled {
    ~ .form-check-label {
      cursor: $form-check-label-disabled-cursor; // Here
      opacity: $form-check-label-disabled-opacity;
    }
  }
}
```

#### Solution 3

If we assume the already existing Sass variable `$form-check-label-cursor` should only apply when the input is NOT disabled, we can update the CSS like bellow. It has the advantage to only add the CSS cursor rule when required, so there's no need for another rule that revert the cursor back when disabled.

```scss
form-check-input {
  // ...
  // Add following rules
  &:not([disabled]),
  &:not(:disabled) {
    ~ .form-check-label {
      cursor: $form-check-label-cursor;
    }
  }
}

.form-check-label {
  // cursor: $form-check-label-cursor; removed
  color: $form-check-label-color;
}
```
#### Bonus solution - Maximum flexibility

We can mix 2 and 3 with a `null` default value for `$form-check-label-disabled-cursor`. So if someone really wants a cursor on his disabled labels, it's possible. It's even possible to have a label cursor only when disabled, but I don't think these are valid use cases.

**Comment by ffoodd** [comment]
I'd go for the first solution, simply add `cursor: default`. We may introduce a new variable if requested, but IMHO that's not necessary. @TheFakeCake Still up to do this?

**Review by ffoodd — APPROVED** [review]
Thanks 👌

**Review by mdo — APPROVED** [review]

**Pull request merged**
