### PR TITLE
Gray color utility fixed

### LINKED ISSUE #38569: Gray color utilities do not follow text-{color}-{level} convention
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When following the example given at [Color: Generating utilities](https://getbootstrap.com/docs/5.2/customize/color/#generating-utilities), the color naming convention applies to all but `$grays`.

```
<p class="text-green-300">this should be green</p>
<p class="text-gray-500">this should be a light gray</p>
<p class="text-500">this should be black because this class shouldn't exist</p>
```

### Reduced test cases

https://codepen.io/jcandan/pen/yLRKLQv

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.3

### PR DESCRIPTION
**Pull request by afeefuddin**
### Description

The gray color utility was not working as mentioned in the issue #38569 . There was a major syntax error in the variables.scss file. I have fixed the syntax. 
### Motivation & Context

The gray utility was not working previously when the class name "text-gray-{level}" was used. Whereas it was working properly for other colors. I have fixed the codebase and now it is working fine.

### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

- <https://deploy-preview-38585--twbs-bootstrap.netlify.app/>

### Related issues

Closes #38569

### CODE REVIEW

**Comment by afeefuddin** [comment]
@julien-deramond done

**Review by julien-deramond — CHANGES_REQUESTED** [review]
Haven't checked everything but there's at least one issue with this change. Generated `bootstrap.css` via `npm run css` now contains:

```css
--bs-gray-gray-100: #f8f9fa;
  --bs-gray-gray-200: #e9ecef;
  --bs-gray-gray-300: #dee2e6;
  --bs-gray-gray-400: #ced4da;
  --bs-gray-gray-500: #adb5bd;
  --bs-gray-gray-600: #6c757d;
  --bs-gray-gray-700: #495057;
  --bs-gray-gray-800: #343a40;
  --bs-gray-gray-900: #212529;
```

Should stay as it was before without the double `gray` in the name.

**Comment by afeefuddin** [comment]
Hey @julien-deramond , I realized that this issue is there at many places, after compiling. I have few doubts in my mind , why the gray color is defined before other colors in the file _variables.scss . If you can clarify it will be very helpful for me to move forwad. As I am a newbie , I need some guidance.

**Comment by afeefuddin** [comment]
Hey @julien-deramond , I have solved that issue . Now after compiling double `gray` is not there in the name.

**Comment by julien-deramond** [comment]
Please be patient. You'll get notified when we'll have the time to review it.

**Comment by afeefuddin** [comment]
Really sorry, for the bad solution. Can I still work on the problem and provide a better solution in the future?

**Pull request closed without merging**
