### PR TITLE
Wall of Browser Bugs: position:sticky support landed in MS Edge

### PR DESCRIPTION
**Pull request by Herst**
Patch to remove it from "Most wanted features" now that `position: sticky` support is in Microsoft Edge 16.

~~(Also includes #24751.)~~

### CODE REVIEW

**Review by XhmikosR — CHANGES_REQUESTED** [review]
I don't see why you include the other issue when it has its own PR. Please remove it from this PR.

**Review by Herst — COMMENTED** [review]
I assumed the changes would be in the same file which is why I took the other PR as a basis.

**Comment by Herst** [comment]
I assumed the changes would be in the same file which is why I took the other PR as a basis.

**Comment by Herst** [comment]
OK, done.

BTW, I would be glad if #24751 got merged in before the final release (assuming there is still no further reaction from the Chromium team's side).

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
