### PR TITLE
Use Jekyll's smartify filter when possible.

### PR DESCRIPTION
**Pull request by XhmikosR**
Example before:

```html
<p class="bd-lead">Get started with Bootstrap, the world's most popular framework for building responsive, mobile-first sites, with the Bootstrap CDN and a template starter page.</p>
```

After:

```html
<p class="bd-lead">Get started with Bootstrap, the world’s most popular framework for building responsive, mobile-first sites, with the Bootstrap CDN and a template starter page.</p>
```

### CODE REVIEW

**Comment by patrickhlauke** [comment]
is docs/4.0/content/tables.md the *only* place where single quotes/apostrophes need to be manually changed? i somehow doubt that (i for one never bother with smart quotes myself, and i'm sure there's more places in the md files where they're present).

this feels more like something that should be hooked into build step also for the `{{ content }}` but i guess that would result in far too many false positives when it hits markup bits?

**Comment by XhmikosR** [comment]
There are no other cases. Rule of thumb: just don't use them in Markdown files.

**Comment by XhmikosR** [comment]
Note that inside HTML code, even if that is in a markdown file, the quotes aren't converted. In those cases, one needs to explicitly use them.

**Comment by patrickhlauke** [comment]
> There are no other cases. Rule of thumb: just don't use them in Markdown files.

not sure i follow here. so you're saying one shouldn't straight `'` quotes in markdown, but author using actual smart quotes always? it's a pain to do in Windows fwiw, but i'm more concerned if from now on we then need to make sure any PR that touches docs must be checked for appropriate use of smart quotes? (and if so that all reviewers be made aware of this)

**Comment by XhmikosR** [comment]
I wouldn't say we need to do anything. Using smart quotes doesn't hurt
anything assuming the proper file encoding is used.

So the changes I made here is so that we are consistent and secondly so
that we use smart quotes where possible.

We don't need to overcomplicate things. The rules is what I said above.
Pure Markdown code doesn't need smart quotes because they are automatically
converted. HTML code anywhere needs it but there only a few places which I
plan to change later.

**Comment by patrickhlauke** [comment]
> Pure Markdown code doesn't need smart quotes because they are automatically
converted.

ah, i don't think you actually said that above. in that case fair enough.

**Review by patrickhlauke — APPROVED** [review]

**Pull request merged**
