### PR TITLE
add firfox bug in doc #23489

### PR DESCRIPTION
**Pull request by chiraggmodi**
add browser bug as mention in #23489. i have also tried as suggestion in comment to add `display: block` but it is not printing properly. have attached 
screenshot

### CODE REVIEW

**Comment by prateekgoel** [comment]
@chiraggmodi I think you should not submit a PR for the issue where someone is asking or claiming to work on it.
/CC @mdo

**Comment by mdo** [comment]
We're going to link to a 16 year old bug in Firefox? Surely there's something more up to date...

**Comment by prateekgoel** [comment]
@mdo Seems like setting `display` to `block` instead of `flex` is the only solution right now.
I did a little research on this and found that firefox has issues with printing flex containers.
Also, noted here:
https://stackoverflow.com/questions/4609007/firefox-printing-only-1st-page
https://stackoverflow.com/questions/43492724/firefox-prints-first-page-only-but-other-browsers-doing-fine

I tried changing `display:flex;` to `display:block;` in Firefox web inspector and this solved the printing issue for me.

**Comment by chiraggmodi** [comment]
yes, i do change to `display:block` but we need to change many classes to print appropriate as chrome

**Comment by mdo** [comment]
Closing per #23489.

**Pull request closed without merging**
