### PR TITLE
Mention what Sass compiler we use

### LINKED ISSUE #29760: Docs: add a warning about the Sass implementation
See #29743

### PR DESCRIPTION
**Pull request by mdo**
Fixes #29760.

### CODE REVIEW

**Comment by XhmikosR** [comment]
I'm not against this, but #32512 is already open and does offer a little more explanation about precision and history behind it, which is definitely applicable to v4.

**Comment by ffoodd** [comment]
Agreed, we definetely need to mention the precision thing too and our own recommendations. 
However it makes more sense to document this in "Build tools" rather than in "Customization", IMHO.

**Comment by voltaek** [comment]
Would you like me to move the explanation from **Customization** into **Build Tools** in #32512? I'd also then leave the removal of the outdated precision info from the **Customization** section like I have now.

**Comment by mdo** [comment]
@voltaek That works for me!

**Comment by voltaek** [comment]
I've updated my PR as requested.

**Comment by mdo** [comment]
Closing for #32512, thanks!

**Pull request closed without merging**
