### PR TITLE
Fix width scrolling problem with .card-deck

### PR DESCRIPTION
**Pull request by ghost**
Updated value of space between cards to 0.9375rem which is 15px

### CODE REVIEW

**Comment by cvrebert** [comment]
> Fix width scrolling problem

@anupjon What scrolling problem are you talking about?

> Updated value of space between cards to 0.9375rem which is 15px

Why 15px specifically?

**Comment by anupjon** [comment]
https://github.com/twbs/bootstrap/issues/19883

**Comment by ckugot** [comment]
This fixes the issue on Mac Chrome as well.

**Comment by mdo** [comment]
Closing out since I think I want to do this with the grid instead of extra classes; plus this user is no more given the `@ghost` account.

**Pull request closed without merging**
