### PR TITLE
Fixed Padding - Alert-Dismissable-cross | Buttons

### PR DESCRIPTION
**Pull request by adsingh14**

### CODE REVIEW

**Comment by wolfy1339** [comment]
This pull request is invalid for 2 reasons:
1. You didn't edit the SCSS files
2. You added `bootstrap.css`, that file shouldn't be there

**Comment by mdo** [comment]
Closing per last comment.

**Comment by adsingh14** [comment]
@wolfy1339 - Okay, I'll provide `.scss` along with `.css` file. 

After all Its my first pull request 😅.

**Comment by wolfy1339** [comment]
No, don't include changes to the .css file.

________________________________

**Comment by adsingh14** [comment]
@mdo 
Should I edit the .scss files from `bootstrap/scss` only ?

**Pull request closed without merging**
