### PR TITLE
inline svg: base64 > ASCII85

### PR DESCRIPTION
**Pull request by efender**
ASCII significantly reduces size.
Preview - http://sassmeister.com/gist/031303db9b45b7ed1a24

|  | plain | gzip |
| --- | --- | --- |
| base64 (original) | 4428 bytes | 1573 bytes |
| ASCII85 | 1656 bytes | 632 bytes |

### CODE REVIEW

**Comment by XhmikosR** [comment]
@cvrebert: so how about this? It sort of makes sense since those SVGs are small.

**Comment by cvrebert** [comment]
SGTM.
CC: @mdo

**Comment by slavanga** [comment]
The SVGs need to be URL encoded to support IE 11 and below.
See: https://connect.microsoft.com/IE/feedbackdetail/view/969438/ie-11-support-non-encoded-data-uris

**Comment by cvrebert** [comment]
@slavanga Yup, that's why Oleg's code has `%3C` etc. in it.

**Comment by slavanga** [comment]
@cvrebert ah right, I always thought the whole thing has to be encoded. Thank you for the hint.

**Comment by mdo** [comment]
Gotta balance this with #17222.

**Comment by mdo** [comment]
Punting for #17222.

**Pull request closed without merging**
