### PR TITLE
Adds button styles to `.list-group-item`

### LINKED ISSUE #16204: List group with anchors and buttons semantic html and accessibility
I'm reviewing pull request react-bootstrap/react-bootstrap#467 and could use some input on a clear direction to take the `ListGroup` and `ListGroupItem`  React components we are putting together there.

When working with a `list-group` component the docs highlight two major code paths using either `div` or `ul` which lead me to this example:

```
<div>
  <ul class="list-group">
    <li class="list-group-item">Dapibus ac facilisis in</li>
    <li class="list-group-item">Cras sit amet nibh libero</li>
    <li class="list-group-item">Porta ac consectetur ac</li>
    <li class="list-group-item">
      <a href='#'>Vestibulum at eros</a>
    </li>
  </ul>
  <div class="list-group">
    <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
    <a href="#" class="list-group-item">Cras sit amet nibh libero</a>
    <a href="#" class="list-group-item">Porta ac consectetur ac</a>
    <span class="list-group-item">Porta ac consectetur ac</span>
    <button class="list-group-item">Vestibulum at eros</button>
  </div>
</div>
```

Which produces:

I thought about using a vertical button group, but the background colors for contextual items are darker with the btn-group.

Have you considered having buttons within a list-group styled the same as the anchors? Or on the flip side having anchors and buttons that are direct children of an `li` appear the same as the `div` approach?

### PR DESCRIPTION
**Pull request by zacechola**
Closes #16204.

Includes buttons with anchor sytles and modifies buttons to match width
and text alignment.

This doesn't yet address the accessibility issue @patrickhlauke raised in that thread, nor does it yet add documentation on the use of buttons.

### CODE REVIEW

**Comment by mtscout6** [comment]
Does it really close #16204 if it doesn't account the the accessibility concerns? :wink:

**Comment by zacechola** [comment]
> yet

:smile:

I'm not sure if it'll make more sense to tack documentation changes onto this PR or to do that as a separate one.

**Comment by mdo** [comment]
It'd be cool to update the docs to mention this as well @zacechola. Want to take a stab at duplicating the *Linked items* section for the button variation?

@patrickhlauke Did you want to add something to the docs about this stuff?

**Comment by zacechola** [comment]
No problem. I'll add that.

**Pull request merged**
