### PR TITLE
Fix Popper preventOverflow boundary config

### PR DESCRIPTION
**Pull request by kyletsang**
Currently, the boundary config is being assigned to the wrong var (`rootBoundary`) in the popper config.  It should be assigned to the `boundary` var in popper's config.

Ref: https://popper.js.org/docs/v2/utils/detect-overflow/#boundary

### CODE REVIEW

**Comment by XhmikosR** [comment]
@kyletsang do we have any issue about this? I don't suppose this issue could be related to any of the other Popper issues we have in v5?

**Comment by kyletsang** [comment]
@XhmikosR, currently no issue reported.  I was reviewing the code to see if there's any new modifiers I needed to port over to `react-bootstrap` when I stumbled on it.

This could potentially cause issues due to incorrect usage of `rootBoundary`.  Unfortunately, I haven't tested in-depth though.

**Comment by XhmikosR** [comment]
@kyletsang do you think you could add some tests about this?

**Comment by kyletsang** [comment]
Ugh, I think I'm going to need some assistance on this.  I can't seem to come up with a demo that shows any difference when setting an incorrect `rootBoundary` vs a correct one.

**Comment by XhmikosR** [comment]
Unfortunately, I have no idea how to test for this. We should have a test to make sure we don't hit this again, but if we can't have a test, I guess we could make an exception here.

**Review by mdo — APPROVED** [review]

**Comment by XhmikosR** [comment]
@rohit2sharma95 LGTY?

**Review by rohit2sharma95 — APPROVED** [review]

**Pull request merged**
