### PR TITLE
WIP: Add dependencies to our Sass files

### PR DESCRIPTION
**Pull request by mdo**

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
`_variables.scss` depends on `_functions.scss`, so these two should be switched

**Comment by celestehorgan** [comment]
not what I envisioned when I opened an issue, but this would satisfy my needs as a user. Thank you!

**Comment by XhmikosR** [comment]
@mdo I suppose we can close this? We could probably do something like you did on main in a new PR.

**Comment by mdo** [comment]
Closing as stale.

**Pull request closed without merging**
