### PR TITLE
V4: Add old .hidden-* classes to visibility utilities

### PR DESCRIPTION
**Pull request by richterdennis**
For better and simpler hiding an element on one specific breakpoint, adding the old .hidden-\* classes

### CODE REVIEW

**Comment by cvrebert** [comment]
How often do you really need to hide something at **exactly** 1 screen size, rather than "size X and up" or "size X and down"?

**Comment by richterdennis** [comment]
Imagine you design a page layout that changes between md and sm (sidebar moves or hides), that the main content have on xs and md the same space and on sm and lg the same space. And the space is not enough for an element on xs and md, but it have it on md and lg.

**Comment by mdo** [comment]
Punting on this; it's unlikely we'll do both up/down and exact breakpoint utilities like this in v4's lifespan. Thanks though!

**Comment by dmiko** [comment]
mdo, please review this item once more.

The problem with removing hidden-XX and visible-XX classes is that you increase problems level for automated WYSIWYG Bootstrap editors.

For example before they had checkboxes array for column:
* visible in xs
* visible in sm
* visible in md
* visible in lg

Now they need to always check only one visible interval existence. Or to use another very custom control. And to explain to user why he can not check only XS and MD together.

Finally the problem is more complicated if editor supports both B3 and B4 at one time.

**Comment by ademaro** [comment]
Which way it is now possible to realize the hidden items only on the tablet, for example? It turns out that absolutely can not be?

**Pull request closed without merging**
