### PR TITLE
Added not allowed cursor in disable form

### PR DESCRIPTION
**Pull request by chiraggmodi**
as per suggestion in #23460 i have added not allowed cursor.

### CODE REVIEW

**Review by patrickhlauke — COMMENTED** [review]
I'm personally not a fan of `cursor: not-allowed` for aesthetic reasons (on windows, it results in an ugly red "not allowed" sign which looks rather jarring), and because default native forms don't have this sort of indication on disabled form controls. leaving it up to @mdo to make the call (but since we removed that particular cursor in a previous PR, this would mean reintroducing it / making sure it's consistently re-added)

**Comment by lowegreg** [comment]
I agree with @patrickhlauke and also not a fan of the cursor: not-allowed.  I only added it as an issue because the control had it.  In my opinion regardless of which way you go, the control and label should have the same cursor...

Greg

**Comment by mdo** [comment]
We'll pass on it for now then given @patrickhlauke's comment. Thanks though!

**Comment by danjford** [comment]
Just adding my experience on this. I did some UX testing with some partially sighted users who used a mixture of screen readers, braille keyboards and screen magnifiers.

I believe it was the users who were using screen magnifiers who gave the feedback that they found the not-allowed image on windows particularly useful as the opacity did not help them to distinguish that something was disabled.

**Comment by chiraggmodi** [comment]
i agree, `cursor: not-allowed` is useful as UX point of view. Believe me i am also not fan of `cursor: not-allowed` property.

**Pull request closed without merging**
