### PR TITLE
Move Sauce credentials out of .travis.yml

### PR DESCRIPTION
**Pull request by cvrebert**
And into the Travis settings page.
CC: @XhmikosR

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 4684c50bd5fae6c0edcc7b6410719a158089d113
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/144082800
Docs preview: http://preview.twbsapps.com/c/${commitSha.sha}

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
Same recent Firefox issue as usual. The important point is that the tests still actually ran.

**Comment by XhmikosR** [comment]
What lead you to do this? Is there something wrong?

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Pull request closed without merging**
