### PR TITLE
Fixes to increase test stability

### PR DESCRIPTION
**Pull request by mukesh-lt**
### Description
Two main changes
- Using Regex in the real device names so that tests don't get errored out in case of specific device unavailability
- Bumping timeoutInterval to avoid `disconnected` failures and captureTimeout to make sure that the devices get allocated to the tests 

### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [ ] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [ ] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

#### Live previews

- <https://deploy-preview-{your_pr_number}--twbs-bootstrap.netlify.app/>

### CODE REVIEW

**Comment by XhmikosR** [comment]
@mukesh-lt can you please revert the package-lock.json changes?

**Comment by akshatlambdatest** [comment]
> @mukesh-lt the thing with this approach is that tests become more unpredictable. We don't know which device is used explicitly beforehand. Are these changes really needed in browsers.js?

@XhmikosR These changes will make the unit tests more reliable by ensuring that the device which has the maximum availability with the desired platform version is being allocated to the test.

**Comment by akshatlambdatest** [comment]
@XhmikosR The browsers will remain the same, it will be Chrome for android real devices and Safari for ios real devices.

**Comment by XhmikosR** [comment]
Ah, sorry, I meant devices.

**Comment by vipulkv** [comment]
hi @XhmikosR : using `regex` feature will increase the device count applicable for tests and reduce the queue time, hence it increase the reliability of tests execution. 

If you notice, we have **not** removed `platformVersion` so all tests will run on fixed OS version only - that will ensure that testing is being done on expected OS version. 

Also, if you would like to know where which devices tests were executed, you can visit [LambdaTest Dashboard](https://accounts.lambdatest.com/dashboard) to see device name.

Let us know if these helps you.

**Comment by XhmikosR** [comment]
Thanks, I merged it to test it a bit.

**Comment by XhmikosR** [comment]
We are still getting a failure on the second run :/ https://github.com/twbs/bootstrap/actions/runs/4812251125/jobs/8567436887

**Pull request merged**
