### PR TITLE
Grunt: extend `prep-release` task.

### PR DESCRIPTION
**Pull request by XhmikosR**
Make it so that everything is done for us to reduce the possibility of missing something when releasing.

/CC @cvrebert @mdo

### CODE REVIEW

**Comment by cvrebert** [comment]
I don't think `docs-build` is worth it. It's a duplication that can fall out of sync, and the lints it avoids don't take long enough to run for me to care.

**Comment by XhmikosR** [comment]
Well, you said you didn't want docs in the past due to the lint checks, hence the duplication. Either works for me.

**Comment by XhmikosR** [comment]
Updated.

**Comment by cvrebert** [comment]
:+1: :shipit:

**Comment by cvrebert** [comment]
Refs #16311

**Pull request merged**
