### PR TITLE
Document migration of outline button class in v4

### PR DESCRIPTION
**Pull request by jorrit**
See #17719

### CODE REVIEW

**Comment by vsn4ik** [comment]
`.btn-*-outline` not available on v3.

**Comment by pkozlowski-opensource** [comment]
@vsn4ik this PR is for the `twbs:v4-dev` branch so v3 is not relevant here.

**Comment by vsn4ik** [comment]
@pkozlowski-opensource http://v4-alpha.getbootstrap.com/migration/#summary.

**Comment by jorrit** [comment]
@vsn4ik I see what you mean, `.btn-*-outline` was introduced in some earlier version of v4 and not in v3 or before.

**Pull request closed without merging**
