### PR TITLE
Rebuilt accordion to fix styling for single card

### PR DESCRIPTION
**Pull request by kampalex**
Signed-off-by: Alexander Kamp <git@akamp.nl>

### CODE REVIEW

**Comment by ysds** [comment]
Hi @kampalex, thanks for your report. It would be helpful for us if you create a demo with 
 static HTML for reproduce the issue.

**Comment by kampalex** [comment]
Hi @ysds I've created a CodePen example - using the Bootstrap 4.3.1 [accordion example](https://getbootstrap.com/docs/4.3/components/collapse/#accordion-example) (card 2 and 3 are commented). _card.scss doesn't cover the single card scenario directly under .accordion.
https://codepen.io/kampalex/pen/zQzQyg

Swap linked CSS to [pull-request CSS](https://deploy-preview-28780--twbs-bootstrap.netlify.com/docs/4.3/dist/css/bootstrap.min.css) to see difference.

**Comment by kampalex** [comment]
Just a thought...
Because the styling is only applicable for .card elements directly under .accordion, is it better to use *-child instead of *-of-type?
Compared to project usage, *-child is more commonly used than *-of-type.

**Comment by khitermedachraf** [comment]
good good

**Comment by XhmikosR** [comment]
Does this apply to master too? If so it should target the master branch.

**Comment by MartijnCuppens** [comment]
This is fixed in the meantime (BS 4.4.1): https://codepen.io/MartijnCuppens/pen/NWPwxzo

**Pull request closed without merging**
