### PR TITLE
Fixed Chrome box sizing inheritance bug (#22872)

### LINKED ISSUE #22872: Chrome details element doesn't correctly propagate box-sizing
There is a [bug in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=589475&q=details%20box-sizing&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) where inheritance of box-sizing does not happen correctly with the `details` element. This results in all `input` (and every other element that is `width: 100%`)  overflowing the `details`.

This is demonstrated by [this codepen](https://codepen.io/andrewbelcher/pen/mwWZEM).

The solution is to add:
```
details > * {
  box-sizing: border-box;
}
```

Would post a PR, but can't get grunt working locally and don't have time to fix it now.

### PR DESCRIPTION
**Pull request by prateekgoel**
I have changed:
```
*,
*::before,
*::after {
  box-sizing: inherit; }
```
to
```
*,
*::before,
*::after {
  box-sizing: border-box; }
```

Fixes #22872.

### CODE REVIEW

**Comment by wolfy1339** [comment]
Please remove dist files

**Comment by prateekgoel** [comment]
@wolfy1339 , Should i not make changes to dist files?

**Comment by wolfy1339** [comment]
They only want changes to the SCSS files only, not the dist files. So no compiling the source

**Comment by prateekgoel** [comment]
Ok thanks. I'll remove those.

**Comment by mdo** [comment]
Cool, I'll take a look after the first beta. Thanks!

**Comment by prateekgoel** [comment]
Thanks @mdo 
I feel this is a very basic change. Can we have this included at this moment?

**Comment by mdo** [comment]
> I feel this is a very basic change. Can we have this included at this moment?

Nope, not yet. This PR hasn't been reviewed, hasn't been tested, isn't an urgent bug (only affects one HTML element), misses the follow-up step of removing the now duplicate `box-sizing` from the `html` selector above, and includes compiled CSS files.

**Comment by prateekgoel** [comment]
Ok Thanks @mdo.
By the way, I removed the compiled file from dist directory as per comment by wolfy1339.
I would like to work for the solution for duplicate `box-sizing` from the `html` selector above.

**Comment by mdo** [comment]
You still have compiled CSS in your diff.

**Comment by prateekgoel** [comment]
Sorry but I am not able to see any files from `dist` directory. See the image for reference. Are you talking about the `bootstrap.css` located in the `scss` directory?

image

**Comment by prateekgoel** [comment]
I have done the required change and submitted a new PR https://github.com/twbs/bootstrap/pull/23118
You can close this one.
@mdo - Please review and share your thoughts.

**Pull request closed without merging**
