### PR TITLE
Less restrictive Regex in Util.getSelectorFromElement issue #18641

### PR DESCRIPTION
**Pull request by joseph-allen**
PR for issue #18641

### CODE REVIEW

**Comment by Johann-S** [comment]
Overlaped with #21615 and #21654 which remove totaly this regex

**Comment by joezcool02** [comment]
@Johann-S shall we close the original issue?

**Comment by Johann-S** [comment]
No, until they are a PR merged which close this issue

**Comment by mdo** [comment]
Closing since we merged #21615.

**Pull request closed without merging**
