### PR TITLE
Add portuguese brazilian translation

### PR DESCRIPTION
**Pull request by adammacias**

### CODE REVIEW

**Comment by cvrebert** [comment]
Thank you.

**Comment by adammacias** [comment]
:blush: :+1:

**Comment by adammacias** [comment]
@cvrebert why you closed with unmerged commits? :\

**Comment by cvrebert** [comment]
I had to rebase your original commit to tweak a few things.

**Comment by adammacias** [comment]
It's ok :dancers:. I had other think in ment, because you didn't docs regenerate, but i agree you'll be this later... so, no problem, thank you!

**Pull request closed without merging**
