### PR TITLE
[SCSS] Reuse $dark variable on $table-dark-bg

### PR DESCRIPTION
**Pull request by andrerom**
Instead of Setting the same grey tone, reuse variable value to simplify theming.

Note: The thead-light color does not reflect `light` color too though.

### CODE REVIEW

**Comment by andrerom** [comment]
Note: The thead-light color does not reflect `light` color too though.

**Comment by XhmikosR** [comment]
Not sure if this even applies to main or if it's valid @twbs/css-review ?

**Comment by MartijnCuppens** [comment]
This was already changed in v5:
https://github.com/twbs/bootstrap/blob/5bd7aa365cc268ec52fbdf4e139242a0c9769939/scss/_variables.scss#L545

In v4, this would be a BC?

**Comment by XhmikosR** [comment]
Probably, yeah.

**Comment by MartijnCuppens** [comment]
Closing this than.

**Pull request closed without merging**
