### PR TITLE
new feature: break long words to next line

### PR DESCRIPTION
**Pull request by 0xadri**
See relevant feature request: https://github.com/twbs/bootstrap/issues/19315

### CODE REVIEW

**Comment by adrien-be** [comment]
Just realized my PR was on Bootstrap 3 ... :/

**Comment by cvrebert** [comment]
My note and comment from #19313 apply here as well.

**Comment by IdanCo** [comment]
@adrien-be , love the utility class, but why not do it globally?

in #18927 they specifically mentioned that `We deliberately do NOT reset font-size or word-wrap.`. What am i missing here? does any one **wants** titles or paragraphs to exceed container's width?

**Comment by adrien-be** [comment]
Because I'd rather let everyone opt-in.
And if one wants to opt-in globally, you can do this easily using
sass mixins.
First world problem I suppose ^^

**Pull request closed without merging**
