### PR TITLE
tooltip/popover that supports scroll and resize events

### PR DESCRIPTION
**Pull request by mothsART**
Hi,

I propose improved " tooltips " .
You can take this "pull request" more like a draft than a real patch.

I noticed that using "scrolling" & "resize" events are penalizing for positionning tooltips .
Mainly, when tooltips are in a wrapper with the property "overflow: scroll/auto".

In advanced, Thanks to tell me if this feature can make sense in the Bootstrap project and what i must to improve / adapt for it to be included. (give optional features, refactoring , unit tests , etc. )

Best regards

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 4a9cb4a764a3e2ccc76c0e9ae8d72e222eb9e3ed
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/72675596

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: ee981e5dce797acfc9e2c90572242791219dff08
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/72682253

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: d733c35f7517c016d1ba8b24322ccd2e15c8ee37
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/72682810

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 397d0ae4a63fd494c2c709619f3e247034f4d868
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/72688691

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
In order to focus on Bootstrap v4, we aren't making any major changes to tooltips/popovers in Bootstrap v3 anymore.
In Bootstrap v4, we plan to switch the tooltip/popover plugin to utilize an existing positioning library (e.g. [Tether](http://tether.io/)) instead of maintaining the complicated positioning logic ourselves.

So, unfortunately, we won't merge this pull request. However, we appreciate the thought and effort you put into this PR. I encourage you to come back after the first alpha version of Bootstrap v4 is released, examine the new tooltip code, and offer any suggestion you might have.

Thanks!

**Pull request closed without merging**
