### PR TITLE
dashboard example: minor fix

### PR DESCRIPTION
**Pull request by techvanity**
`dashboard.css` (and rtl version) contain rules for `.sidebar-sticky`, but these are not being applied currently.

### CODE REVIEW

**Comment by ffoodd** [comment]
Reading `.position-sticky` on the same elements makes me wonder if the CSS shouldn't be dropped, instead of adding the class name in markup?

Thoughts, @julien-deramond? Might be a leftover from peeviois refactors.

**Comment by julien-deramond** [comment]
Confirm what's been said by @ffoodd: `.sidebar-sticky` has been removed in https://github.com/twbs/bootstrap/commit/0ca2cf4ccac251bfd97c767f5608fa012673d5c3 in favor of `.position-sticky`.
In this PR @techvanity you can drop `.sidebar-sticky` rules in both `dashboard.css`/`dashboard.rtl.css` files rather than using `.sidebar-sticky` in the markup.

**Review by julien-deramond — CHANGES_REQUESTED** [review]
Confirm what's been said by @ffoodd: `.sidebar-sticky` has been removed in https://github.com/twbs/bootstrap/commit/0ca2cf4ccac251bfd97c767f5608fa012673d5c3 in favor of `.position-sticky`.
In this PR @techvanity you can drop `.sidebar-sticky` rules in both `dashboard.css`/`dashboard.rtl.css` files rather than using `.sidebar-sticky` in the markup.

**Comment by ffoodd** [comment]
I think the RTL is generated, isn't it?

**Comment by julien-deramond** [comment]
> I think the RTL file is generated, isn't it?

Yep it is possible to modify `dashboard.css` and then to run `npm run css-prefix-examples-rtl` to regenerate/modify `dashboard.rtl.css`.

**Comment by julien-deramond** [comment]
> @julien-deramond and @ffoodd I beg to differ. Those styles are important, especially setting `height` and `overflow-y` so that the sidebar is scrollable when number of items is large. I just tested it - scrolling breaks upon removing that css.

You're right indeed we can see the issue while reducing the window vertically. So I'd say you can keep your modification (addition of `.sidebar-sticky`) and remove in both CSS files the unused/useless rules. I haven't tested it but I'm thinking of `padding-top` already set with `.pt`, probably `position: relative` and some others.

**Comment by techvanity** [comment]
Made the requested changes.
Thanks

**Review by julien-deramond — APPROVED** [review]
LGTM! Thanks @techvanity for this PR!

**Pull request merged**
