### PR TITLE
Update copyright year

### PR DESCRIPTION
**Pull request by dtarellano**

### CODE REVIEW

**Review by XhmikosR — CHANGES_REQUESTED** [review]
@dtarellano: please check any other places like README.md.

**Comment by lguima** [comment]
Done on #25234 @XhmikosR

**Comment by XhmikosR** [comment]
@mdo: can you take care of the copyright bump for the files you want to do it? It's a so trivial thing and we keep getting PRs which, you know...

**Comment by mdo** [comment]
Closing for #25303.

**Pull request closed without merging**
