### PR TITLE
docs(3.3): fix input-groups link

### PR DESCRIPTION
**Pull request by simon04**
Currently, https://getbootstrap.com/docs/3.3/css/#forms-example links to https://getbootstrap.com/components/#input-groups which  redirects to https://getbootstrap.com/docs/4.5/components/alerts/

### CODE REVIEW

**Comment by XhmikosR** [comment]
This is already fixed in 3.4, and we usually don't bother with old docs. @mdo your call

**Comment by simon04** [comment]
Searching for "getbootstrap 3" on https://duckduckgo.com/?q=getbootstrap+3&ia=web directed me to the 3.3 docs, https://getbootstrap.com/docs/3.3/ –

**Comment by XhmikosR** [comment]
Sure, but that doesn't mean anything, really. Every release includes doc fixes which are applied in new releases. We don't really fix the old docs unless it's something important, and this is already fixed in 3.4 which is the latest 3.x release.

**Comment by mdo** [comment]
Feels like a harmless fix we can push to old docs. I'm fine seeing it move ahead @XhmikosR.

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
