### PR TITLE
Fix issue #18208

### PR DESCRIPTION
**Pull request by phmasek**
Added `this.isShowing` flag. This disables toggle while modal is "transitioning" to open state. When state reached, toggle is enabled again. Also cleaned visual test page for `modal.html` and added visual test as specified in #18208 with `onClick` event.

Addresses issue #18208

### CODE REVIEW

**Comment by cvrebert** [comment]
> Never commited any changes to the Unit tests.

Yeah but you committed changes to the code that the tests test. It seems that your changes caused some breakage.

**Comment by Pletron** [comment]
yeah, you're right. Fixed it now.

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 7c12dd0e161c79227c74466c671676f55c004ff4
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/91994366

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Pletron** [comment]
Now it works!

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Pull request closed without merging**
