### PR TITLE
Misaligned close button in toasts examples

### PR DESCRIPTION
**Pull request by ffoodd**
https://deploy-preview-30532--twbs-bootstrap.netlify.com/docs/4.3/components/toasts/#basic

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
I prefer the current implementation:

Current:
image

PR:
image

**Comment by ffoodd** [comment]
Oooh I think I understand what's going on… Might be font related, since I'm on Ubuntu. This is what it looks like on both Chrome and Firefox on Ubuntu:

Master:
Screenshot_2020-04-08 Toasts

This PR:
Screenshot_2020-04-08 Toasts(1)

Removing `.mb-1` may not be the answer, but this alignment should probably not depend on font / OS, am I wrong?

**Comment by MartijnCuppens** [comment]
we should ditch the × in favour of an SVG which is easier to align and style (see https://github.com/twbs/bootstrap/issues/27163)

**Comment by ffoodd** [comment]
Agreed, I need an override in Boosted for now!

I'm closing this.

**Pull request closed without merging**
