### PR TITLE
fixed issue with hr tag mention in 23032

### LINKED ISSUE #23032: [v4] <hr> not visible in Cards
When adding an `<hr>` inside a `.card`, the line does not appear. I believe this may be a bug.

The only way I found to make it appear, is by adding `width: 100%;` to the `<hr>`. But this doesn't seem like an intended feature.

### PR DESCRIPTION
**Pull request by chiraggmodi**
have added `margin-left:0; margin-right:0;` to `_card.scss` to make `hr` visible inside `.card` class.

Fixes #23032

### CODE REVIEW

**Comment by XhmikosR** [comment]
@chiraggmodi: please rebase against v4-dev and remove any unrelated changes.

**Comment by XhmikosR** [comment]
Unrelated change is also touching package-lock.json.

**Comment by chiraggmodi** [comment]
ok so can you guide me how to remove all unrelated changes? as i am doing rebase command but it is showing me conflict error. or do you suggest me to push new PR?

**Comment by XhmikosR** [comment]
Now it's OK, but it's not rebased. So leave it as is.

But if you're feeling adventurous, `git rebase -i upstream/v4-dev` and drop your unrelated commits. Then after you verify all is good locally force push your branch.

**Comment by mdo** [comment]
As a quick heads up for folks who don't rebase via command line, there's no need to really do it yourself these days. GitHub has a `Rebase and merge` option, so I can consolidate an entire PR down into one commit for you when we're ready :).

**Comment by XhmikosR** [comment]
Yeah, that is why I suggested to leave it as is since we don't have any conflicts :)

**Comment by chiraggmodi** [comment]
Cool,  git is really a smart ass!!

**Comment by XhmikosR** [comment]
@chiraggmodi: don't mix your patches. What you pushed is wrong. Also, test locally before pushing.

**Comment by chiraggmodi** [comment]
yes, mistakenly i have push in wrong branh

**Review by mdo — APPROVED** [review]

**Pull request merged**
