### PR TITLE
Carousel cleanups

### PR DESCRIPTION
**Pull request by svenheden**
A couple of minor code cleanups in the Carousel component.

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: c42f351f29d97122493936e19fababee1eea6bac
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/73552891

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
Seems to have failed on OS X Chrome, but that might just be due to Sauce flakiness.

**Comment by cvrebert** [comment]
@twbs-savage retry

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: c42f351f29d97122493936e19fababee1eea6bac
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/73609155

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by jonathanp** [comment]
Oh ok, didn't know that. I've reverted my commit in 8e80624 now.

**Comment by cvrebert** [comment]
@fat You okay with the `$.proxy` change?

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 8e80624e8f32ab120db495575a2a9af6b5e1494e
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/73669018

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by XhmikosR** [comment]
Not sure about the `proxy` change. But the rest I like. Perhaps @jonathanp could split those to a separate PR?

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Pull request closed without merging**
