### PR TITLE
Fix theme.css .btn[disabled] styles.

### PR DESCRIPTION
**Pull request by vsn4ik**
http://jsbin.com/pevucucowa/4/edit

### CODE REVIEW

**Comment by vsn4ik** [comment]
Also need fix `box-shadow: none;` on `:active` event.

**Comment by mdo** [comment]
Will you be adding that fix here @vsn4ik? Or should we tackle that separately?

**Comment by vsn4ik** [comment]
PR updated. `box-shadow` problem seen only with `.glyphicon.glyphicon-*` element.
http://jsbin.com/lurowelele/4/edit (dist from master).

**Comment by mdo** [comment]
Fantastic! Thank you @vsn4ik.

**Pull request merged**
