### PR TITLE
v5: Utilities CSS cleanup, new border and bg utils, renames rounded to radius

### LINKED ISSUE #29989: Confusing classes `rounded-sm` and `rounded-lg`
Hello, 

I think there might be a cause of misunderstanding, which I experienced now about the `rounded-lg` and `rounded-sm` classes, because when I saw `rounded-lg`, I instantly got the message that the element edges should be rounded when the screen size is greater than `md` dimensions. 

How about using `.rounded-lg`, `.rounded-md`, `.rounded-sm`, `.rounded-xl` as they are meant to be as breakpoint definers and add `.rounded-1`, `.rounded-2`, `rounded-3` like size definitions as they are in `p-1`, `p-2` (padding) definitions?

**Use case**: For example jumbotron uses exactly this, on screens smaller than lg it has no border-radus, and larger than md, it has. Why don't we have something like this for example like the `card-img`? We can add `rounded-0 rounded-lg` to achieve this easily. `rounded-lg-1` would be delicious too.

### PR DESCRIPTION
**Pull request by mdo**
- Rearranges utilities CSS to better reflect our property order
- Renames `rounded` utils to `radius`, closes #30048 and closes #29989.
- Adds new `border-gray-500` and `border-gray-700` class
- Adds new `bg-gray` class
- Adds some docs to the border utils page to show how I intend these new utils to be combined

### CODE REVIEW

**Comment by alecpl** [comment]
I kinda prefer the long suffixes (-left, -right, -top, -bottom). I see from where the short version comes from, but.... `radius-1` (one) and `radius-l` (left) looks almost the same, which might be confusing.

I propose to use `rl`, `rr`, `rb`, `rt`. Also, adding `x` and `y`variants and all 6 size specifiers would make sense. Also, make the size specified required (so no `radius`, but `r-X`). It would unify radius tool with spacing utilities.

**Comment by alecpl** [comment]
After writing above comment I realized that most utilities do not use abbreviations. So, it would make more sense if spacing utilities would use whole words (padding, margin, top, left, etc.) too. Rather than changing `radius` to `r`

**Comment by MartijnCuppens** [comment]
Feels weird to have numbers in the border utilities, but not in the bg colors. Not sure how we could improve that though.

**Comment by mdo** [comment]
> Feels weird to have numbers in the border utilities, but not in the bg colors. Not sure how we could improve that though.

Agreed... will think on it more.

**Comment by mdo** [comment]
Closing as it's full of conflicts.

**Pull request closed without merging**
