### PR TITLE
Add a working example for tabs plugin with dropdown

### PR DESCRIPTION
**Pull request by rohit2sharma95**
While working for #31443, I found that docs are missing a working example for the tabs plugin with dropdown (Since [that PR](https://github.com/twbs/bootstrap/pull/31443) is not working for tabs with dropdown). It is not that much required though but it covers one more use case with a working demo 🙂

### CODE REVIEW

**Comment by XhmikosR** [comment]
@patrickhlauke so, how do we proceed with this? I mean, if it's a bad practice, it doesn't make any sense to add it...

**Comment by patrickhlauke** [comment]
my preference would be not to include it. we even have this already in the docs

> Note that dynamic tabbed interfaces should not contain dropdown menus, as this causes both usability and accessibility issues. From a usability perspective, the fact that the currently displayed tab’s trigger element is not immediately visible (as it’s inside the closed dropdown menu) can cause confusion. From an accessibility point of view, there is currently no sensible way to map this sort of construct to a standard WAI ARIA pattern, meaning that it cannot be easily made understandable to users of assistive technologies.

**Comment by ffoodd** [comment]
Agreed with @patrickhlauke — we should really avoid this.We may even promote this paragraph to a callout, I guess.

**Comment by XhmikosR** [comment]
Going to close this then. @patrickhlauke feel free to change the wording, although it looks like it's clear enough. So, perhaps we should make it a callout after all.

**Pull request closed without merging**
