### PR TITLE
Add NuGet badge

### PR DESCRIPTION
**Pull request by supergibbs**

### CODE REVIEW

**Comment by cvrebert** [comment]
Were we gonna use NuGet with v4? From folks in the discussion, I thought it was considered quasi-deprecated by ASP.next (or whatever) in favor of Bower/npm, and thus kinda an interim thing?

**Comment by supergibbs** [comment]
My understanding from @mdo in slack was it would continue to be supported. Plus you merged in https://github.com/twbs/bootstrap/pull/17214 :smiley:

**Comment by cvrebert** [comment]
Hmm, well `v4-dev` doesn't currently have a `nuget/` folder, so things are gonna break when v4 becomes `master`..

**Comment by supergibbs** [comment]
True, I'll make a PR so MyGet will continue to work when that happens. Will be a v3 branch for a while as well for bugfixes? If so, we can set up another build in MyGet to maintain that too.

**Comment by cvrebert** [comment]
> Will be a v3 branch for a while as well for bugfixes?

Yeah. Once v4 hits `master`, the old `master` (v3) will get moved to another branch.

**Pull request merged**
