### PR TITLE
bug fix: Fixes #23926 responsive state on navbar

### LINKED ISSUE #23926: Navbar responsive state is broken
The navbar is broken on `v4-dev` on a mobile size :

screen shot 2017-09-12 at 1 41 01 pm

it was introduced on this PR: https://github.com/twbs/bootstrap/pull/23652

`flex-grow: 1` makes element to grow, it will not wrap.

I am working on it, finding a solution that also works on IE, I'll send a PR soon

### PR DESCRIPTION
**Pull request by andresgalante**
#23652 fixes IE10 but introduces a bug on small devices on navbar on any browser, you can test it on `v4-dev` branch.

This PR closes #23926.

I've tested on IE10 up and other modern browsers.

@XhmikosR @mdo can you please review it?

### CODE REVIEW

**Comment by XhmikosR** [comment]
Will do as soon as I'm back, thanks!

**Comment by Fouzyyyy** [comment]
Hi @andresgalante,

Just tested the pushed code, there is an issue with the _Firefox browser v54.0_, _Chrome 60.0.3112.113_, in the responsive mode (900 * 480) for instance. It's the same behavior reported in #23926

**Review by XhmikosR — APPROVED** [review]
@mdo: please have a look too; I confirmed it fixes the regression and also works on IE

**Comment by andresgalante** [comment]
@Fouzyyyy you are right, the issue persists on the examples on the docs but not on the examples/jumbotron/ example.

I'll see if I can fix it

@mdo don't merge as is

**Comment by mdo** [comment]
@andresgalante Do you have an update here for the fix? If it'll take some time, I'm probably going to revert the original PR instead to fix the newest bug.

**Comment by andresgalante** [comment]
@mdo Yes, just updated it, its ready to merge now.

**Comment by mdo** [comment]
Weirdly I was building files locally and accidentally pushed before hitting submit on my review. Thanks, @andresgalante!

**Pull request merged**
