### PR TITLE
Set the correct color for popover header bottom border

### LINKED ISSUE #34005: Bottom border of 'popover-header' does not respect value specified for $popover-border-color
When customizing Bootstrap, setting a new value for `$popover-border-color` does not affect the value for `border-bottom` of elements with `popover-header` class.

The same does not occur when setting a new value for `$card-border-color`, where `card-header` get the correct color for `border-bottom`.

From `_card.scss`:
```scss
.card-header {
  padding: $card-cap-padding-y $card-cap-padding-x;
  margin-bottom: 0; // Removes the default margin-bottom of <hN>
  color: $card-cap-color;
  background-color: $card-cap-bg;
  border-bottom: $card-border-width solid $card-border-color;

  &:first-child {
    @include border-radius($card-inner-border-radius $card-inner-border-radius 0 0);
  }
}
```
From `_popover.scss`:
```scss
.popover-header {
  padding: $popover-header-padding-y $popover-header-padding-x;
  margin-bottom: 0; // Reset the default from Reboot
  @include font-size($font-size-base);
  color: $popover-header-color;
  background-color: $popover-header-bg;
  border-bottom: $popover-border-width solid shade-color($popover-header-bg, 10%);
  @include border-top-radius($popover-inner-border-radius);

  &:empty {
    display: none;
  }
}
```

### PR DESCRIPTION
**Pull request by brneor**
Fixes #34005

### CODE REVIEW

**Comment by ffoodd** [comment]
Not quite sure about this: the existing border color is meant to be a shade of the background color. That's questionable and I tend to agree with your suggestion, but it's more a design decision than a CSS one. @mdo, your call :)

**Comment by brneor** [comment]
> Not quite sure about this: the existing border color is meant to be a shade of the background color. That's questionable and I tend to agree with your suggestion, but it's more a design decision than a CSS one. @mdo, your call :)

I was in doubt if this was a flaw or a design choice, but as I stated on #34005, this differs from the `card-header` behavior.

**Comment by ffoodd** [comment]
Well, they aren't the same component, so they may differ :D In this case, popover lies above another content, so its surrounding borders are more important than card's ones IMHO. But I agree it'd be more consistent, even in the component scope.

**Review by ffoodd — APPROVED** [review]

**Comment by brneor** [comment]
Looks like pull bot messed up this PR...

**Comment by XhmikosR** [comment]
@brneor please make a new PR and ideally don't use that bot please.

**Comment by brneor** [comment]
@XhmikosR done in #34026. Sorry for the inconvenience.

**Pull request merged**
