### PR TITLE
Use partialCached in some cases.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@regisphilibert  do you have some time maybe to tweak this even more?

**Comment by regisphilibert** [comment]
I'll take a look tomorrow!

**Comment by regisphilibert** [comment]
How should I proceed? Is there a way to check this branch in my own fork?

**Comment by XhmikosR** [comment]
Yup. Just fork the repo and check out this branch :) Or feel free to start from scratch, this patch was done very quickly

**Comment by XhmikosR** [comment]
I'm going to close this since it's been a while and there are conflicts which I cannot resolve. Thanks for the patches, and if you think this can help us significantly, please do submit another PR :)

**Pull request closed without merging**
