### PR TITLE
v5: Redo blockquote attributions

### PR DESCRIPTION
**Pull request by mdo**
This is an alternate to #30085.

- Renames `$blockquote-small-*` variables to `$blockquote-footer-*`
- Updates blockquote demos with attribution to place it outside the blockquote with a figure wrapper

TODO:

- [x] Still need to update blockquotes elsewhere in the docs if this sticks.

Preview: <https://deploy-preview-30814--twbs-bootstrap.netlify.app/docs/5.0/content/typography/#naming-a-source>

### CODE REVIEW

**Comment by XhmikosR** [comment]
> ✖ Variable $blockquote-footer-font-size is not being used!

**Review by ffoodd — APPROVED** [review]

**Comment by ffoodd** [comment]
FWIW, as commented in #30085, the only missing occurrence in your PR is in the Masonry Example: https://deploy-preview-30814--twbs-bootstrap.netlify.app/docs/5.0/examples/masonry/

**Review by XhmikosR — CHANGES_REQUESTED** [review]
Need to take care of @ffoodd's comment and see if there are more instances in the codebase

**Comment by XhmikosR** [comment]
And now I see we had it in the TODO already 😛

**Comment by XhmikosR** [comment]
@ffoodd if you have some time, can you update the rest of the instances so that we land this please?

**Comment by ffoodd** [comment]
Done. @mdo The Masonry examples changes a bit with this refactor: since paragraphs become blockquote's `:last-child`, they lose their bottom margin, making blockquote smaller. Masonry does not compute the same result anymore.

We may reintroduce the previous result by applying `margin` utilities. Do you have any preference?

**Comment by mdo** [comment]
I think the masonry page looks fine as-is—not a huge change. Thanks for making the last changes, this looks great!

**Review by XhmikosR — APPROVED** [review]

**Comment by Glenn-Domin** [comment]
Yep, that works. 👍

**Pull request merged**
