### PR TITLE
Responsive cards decks

### PR DESCRIPTION
**Pull request by DaSchTour**
While working on my project I wanted to try to create the responsive card deck I mentioned in #19826
Here is my first version of responsive cards.
I'm sure there is a lot to improve, but I would love to bring in this kind of cards to bootstrap.

### CODE REVIEW

**Comment by DaSchTour** [comment]
Nobody here. I guess I'll move to another framework.

**Comment by wolfy1339** [comment]
This is a volunteer run framework, not everybody is availble at all times. You can re-open this pull request and eventually, someone will come and mark this as a feature to v4

**Comment by DaSchTour** [comment]
Well, as I already moved to another framework I don't have any interest in this feature in bootstrap anymore. Implementation in the other framework also was a lot easier.

**Comment by patrickhlauke** [comment]
Good for you. Sorry we couldn't immediately accommodate your request...

**Pull request closed without merging**
