### PR TITLE
IE8 uglifyjs compatity

### PR DESCRIPTION
**Pull request by namiltd**
IE8 compatibility for project like https://github.com/coliff/bootstrap-ie8

### CODE REVIEW

**Comment by Johann-S** [comment]
Sorry but we won't be compatible with IE 8

/CC @mdo and @XhmikosR

**Comment by namiltd** [comment]
This is not about bootstrap IE8 compatibility, only about compatible 'min' compression.

**Comment by Johann-S** [comment]
UglifyJS docs said: 
>Support non-standard Internet Explorer 8. Equivalent to setting `ie8: true` in `minify()` for `compress`, `mangle` and `output` options.  By default UglifyJS will not try to be IE-proof.

X-Ref: https://github.com/mishoo/UglifyJS2#command-line-options

**Comment by XhmikosR** [comment]
There's no point in this PR or discussion. We just don't want to even try to support an ancient browser.

You are of course free to do what you want in your project.

**Pull request closed without merging**
