### PR TITLE
dropdown show method should do the same as toggle

### PR DESCRIPTION
**Pull request by Johann-S**

### CODE REVIEW

**Comment by XhmikosR** [comment]
Do we have an issue about this? This changes the behavior, not sure if it should go in 4.x...

**Comment by Johann-S** [comment]
No we don't have an issue but the current behaviour is really bad, why toggle should use Popper and not show ? Toggle should use show and show should have the same behaviour as our old toggle method

**Comment by XhmikosR** [comment]
Well, 1) tests don't pass and 2) it's a breaking change.

So for master this would be OK assuming the tests are fixed, but v4 I don't think this should land...

**Comment by Johann-S** [comment]
The tests are just a question of time you know that...
And it's not a breaking change because it doesn't change the current behaviour and fix some accessibility problem too

**Comment by Johann-S** [comment]
there is a way to backport that to v4 without a breaking change, I'll show you that 😉

**Review by XhmikosR — APPROVED** [review]
LGTM AFAICT for master

**Pull request merged**
