### PR TITLE
Add support for fractional viewport widths (zoom/high-dpi displays)

### PR DESCRIPTION
**Pull request by patrickhlauke**
Current breakpoint `min-width`/`max-width` calculations have a gap when viewport width is fractional (as can happen when the user zooms, but more importantly when the user has a high-dpi display with a fractional dpr/devicePixelRatio, such as the Surface 3 at `1.5`). See the related clarification I added to CSS MQ4 https://github.com/w3c/csswg-drafts/pull/1083

Instead of spacing the `min-` and `max-` values by `1px`, precision is now increased to `0.01px`, which should cover most fractional values in the foreseeable future.

xref https://github.com/twbs/bootstrap/issues/24137, https://github.com/twbs/bootstrap/issues/21552

### CODE REVIEW

**Comment by patrickhlauke** [comment]
@mdo i know you said this would not be the ideal solution https://github.com/twbs/bootstrap/issues/21552#issuecomment-275019087 ... but I think the impact is minimal (in terms of confusion) and it elegantly solves a problem we'll hit more and more with high-dpi displays that use fractional dpr

**Comment by XhmikosR** [comment]
@patrickhlauke: I suppose the two decimal points are enough, right?

Otherwise it seems like a fine solution until this is sorted by browsers, if ever.

**Review by XhmikosR — APPROVED** [review]

**Comment by patrickhlauke** [comment]
> until this is sorted by browsers

once browsers support proper range context queries, we'll be able to do things like

```
@media (width < 576px) { ... }
@media (width >= 576px) and (width < 768px) { ... }
@media (width >= 768px) and (width < 992px) { ... }
...
```

but yes, for the time being, using decimal points is the best solution (and to be clear, current behavior is not a browser bug per se, just an inadequacy in the original `min-` and `max-` spec which didn't foresee the situation with fractional values)

**Comment by patrickhlauke** [comment]
going to wait for @mdo to give his final blessing :)

**Review by andresgalante — APPROVED** [review]
Hi @patrickhlauke I wonder if it's worth adding a comment on the scss that explains why the `*.99px`

Other than that I am for merging this PR 😄

**Comment by patrickhlauke** [comment]
@mdo unless you're philosophically opposed to this, I'd love to merge this for beta 2
@andresgalante i think it's fairly self-explanatory, no need to document?

also worth keeping an eye out for this bug https://bugs.webkit.org/show_bug.cgi?id=178261 if it starts having an impact

**Comment by mdo** [comment]
I'd prefer to wait on this—we don't see that many problems with this in the grand scheme and the approachability of our setup goes down significantly with changes like these.

**Comment by patrickhlauke** [comment]
I can't quite see what the problem is, @mdo...

Going from "-1px" logic to "-0.01px" doesn't seem to be a significant barrier to approachability to me. Would adding a note in the docs alleviate your concern?

As for problems, this also tackles some of the problems brought up by zooming (when zooming to values that result in fractional viewport widths), so would solve some (but not all) long-standing "we don't support this" type of issues, issues on devices like Surface 3 with non-integer dpr, and future-proofs the queries.

**Comment by patrickhlauke** [comment]
@mdo FWIW i just pushed a new commit with some extra documentation (as an include) and comment for the SCSS. see if that would help sway you?

further, i'll be sending a proposed PR against the CSS4 MQ spec to include the example of high-precision values to deal with fractional viewports as a solution until range queries are supported in browsers. this way, we'll be using an approach that will be actually covered in the relevant spec itself.

**Comment by patrickhlauke** [comment]
xref https://github.com/w3c/csswg-drafts/pull/1884

**Comment by simevidas** [comment]
@patrickhlauke W.r.t. my WebKit bug that you’ve linked above, it might be worth performing a few more tests on iOS devices. According to [my test](https://twitter.com/simevidas/status/918843619326550016), `(max-width: 374.99px)` evaluates to `true` on an iPhone with a 375-pixel viewport (that’s the bug), but `(max-width: 374.98px)` doesn’t. Additional tests on other devices (iPhone Plus, iPad, etc.) could effectively confirm that the `.99px` fraction is problematical, and that `.98px` is safe, in which case Bootstrap could just use that fraction instead.

**Comment by patrickhlauke** [comment]
but it's a clear bug in webkit, and as those breakpoints don't fall on any specific phone/tablet sizes, i'd rather keep it clean and understandable (otherwise the question arises "why -0.02px and not -0.01px" for the docs...

**Comment by patrickhlauke** [comment]
"those breakpoints" meaning the ones BS uses, i.e. 575.99px, 767.99px, 991.99px, 1199.99px

**Comment by patrickhlauke** [comment]
@mdo as the CSS 4 spec now explicitly has my example of using higher-precision values, and the callout should clarify any minor confusion seeing those ".99px" values may cause...are your concerns alleviated? I'd really like to put this one to bed and merge it, as I don't think in the grand scheme of things it will cause much, if any, confusion for authors

**Comment by liquidvisual** [comment]
Just an FYI - this change had the adverse effect in my unzoomed MacOS Safari (hdpi and normal screens); causing elements that should be hidden to show during a 1px gap.

**Comment by simevidas** [comment]
@liquidvisual For the record (and for what it’s worth), this issue does not manifest if the MQ breakpoint is changed from `767.99px` to `767.98px`, according to my test in Safari.

**Comment by patrickhlauke** [comment]
so -0.02px instead of -0.01px? ok, i'll make a patch with a comment in the CSS later...sigh

**Comment by patrickhlauke** [comment]
@simevidas et al - see https://github.com/twbs/bootstrap/pull/25177

**Pull request merged**
