### PR TITLE
tests: replace deprecated jQuery method

### PR DESCRIPTION
**Pull request by rohit2sharma95**
The `.on()` and `.trigger()` methods can set an event handler or generate an event for any event type, and should be used instead of the shortcut methods.

Event aliases like `.click()` will likely never be removed, but jQuery encourages the use of alternatives.

https://blog.jquery.com/2018/01/19/jquery-3-3-0-a-fragrant-bouquet-of-deprecations-and-is-that-a-new-feature/

### CODE REVIEW

**Comment by XhmikosR** [comment]
I wonder if this really makes sense? I mean, from what we know, `click()` will never be removed.

**Comment by rohit2sharma95** [comment]
I found it in the blog post of jQuery: https://blog.jquery.com/2018/01/19/jquery-3-3-0-a-fragrant-bouquet-of-deprecations-and-is-that-a-new-feature/
image

**Comment by XhmikosR** [comment]
Yes, but it explicitly says that `click()` will likely never be removed :)

Do we have any other instances? How about v4?

**Comment by rohit2sharma95** [comment]
There are no more instances for the jQuery's click method (to trigger the click event) in V5 and in V4 I can see only the native click method of the DOM elements.

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
