### PR TITLE
Ensure transition effect displays on modals with remote content

### PR DESCRIPTION
**Pull request by joshreed**
Currently, remote content, unless loaded really quickly, or already cached in-browser, will not always show the (CSS) transitions, which is a nuisance.

This change makes it so that the "in" class is not added to the modal until loaded even is triggered (if applicable). This seems to work well, though if there are suggestions on a better/preferred alternative implementation, I'm certainly flexible.

Additionally, I did not add any Unit tests, because I didn't see any examples of how you would be handling remote/ajax requests in your tests? This change will only be applicable in situations where the "remote" option is set. I am assuming the best way would be to "mock" the request; if you have any suggestions, I would be happy to add test cases. All existing tests still passed when I ran the suite.

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: d11c857f8f5a53efac7538a0bdb34c152c056299
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/91466598

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 13fd112f95de24290560a8ee26699fd3d37f45b3
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/91467858

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 7bceee1a607787f70ef23040fd642f324a54016a
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/91468154

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 3c61e2f866802ebef71e73e802046b7ea128217c
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/91469035

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by twbs-rorschach** [comment]
Hi @joshreed!

Thanks for wanting to contribute to Bootstrap by sending this pull request!
Unfortunately, your pull request seems to have some problems:
* [Changes must be made to the original Sass or Less source code file(s), not just the compiled CSS file(s).](https://github.com/twbs/rorschach/blob/master/docs/css.md)

You'll need to **fix these mistakes** and revise your pull request before we can proceed further.
Once you've fixed these problems, you can either ask the maintainers to re-open this pull request, or you can create a new pull request.
Thanks!

(*Please note that this is a [fully automated](https://github.com/twbs/rorschach) comment.*)

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: a10cdef736764868d5e207b84e000c86795f87c9
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/91473317

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
Successor: #18274

**Pull request closed without merging**
