### PR TITLE
Remove invalid bower.json (#24584)

### LINKED ISSUE #24584: Don't block using Bower
Hi

I understand why you don't support Bower anymore, but there are no need to block for Bower by having an invalid bower.json
Could you please remove bower.json making it possible for those of us who haven't had time to switch away from Bower to  still include Bootstrap (manually) in our projects

### PR DESCRIPTION
**Pull request by iamam34**
Fixes #24584 ("Could you please remove bower.json making it possible for those of us who haven't had time to switch away from Bower to still include Bootstrap (manually) in our projects").

The earlier PR to remove bower support is #23568.

I'm motivated to contribute as part of [Hacktoberfest](https://hacktoberfest.digitalocean.com/).

### CODE REVIEW

**Comment by mdo** [comment]
> I'm motivated to contribute as part of Hacktoberfest.

Awesome! :D

---

I think there was an assumption previously that this wouldn't cause errors for folks, and would instead provide an answer when folks go looking for the file. Hearing it's causing issues definitely means this is totally safe to merge for me.

**Review by mdo — APPROVED** [review]

**Comment by myorangeca** [comment]
How does one download BS4 using bower?

I tried :  "bootstrap": "git://github.com/twbs/bootstrap.git#v4.0.0-beta.2" but got EMAILFORMED error as bower install. My json is valid.

**Comment by jgacuca567** [comment]
@myorangeca 

**Bower** is no longer supported. Use Either `Webpack` or `NPM`
See https://getbootstrap.com/docs/4.0/migration/ Under Beta 2 Changes.

**Comment by myorangeca** [comment]
@jgacuca567 thanks, I have been following all the changes since Alpha.3 :) I am well aware bower support was dropped in beta.2. 

That wasn't my question. Bower should still allow you to download BS4 files manually using my above method, but its throwing me an error.

**Comment by wolfy1339** [comment]
git+htpps:\\github.com\twbs\bootstrap should work

**Comment by myorangeca** [comment]
@wolfy1339 

Still same error...

image

**Comment by mdo** [comment]
There's no more Bower support. Use npm or Yarn, please.

**Pull request merged**
