### PR TITLE
Check modal close time exist open modal

### PR DESCRIPTION
**Pull request by muradsofiyev**
You remove `modal-open` class from the `body ` every modal close time but I think you must be check exist open modal.

### CODE REVIEW

**Comment by Johann-S** [comment]
Hi @muradsofiyev,

We don't need that check because Bootstrap do not allow multi modal see in our docs: 
https://getbootstrap.com/docs/4.1/components/modal/#how-it-works

>Bootstrap only supports one modal window at a time. Nested modals aren’t supported as we believe them to be poor user experiences.

**Comment by muradsofiyev** [comment]
Please look snippet. 
https://jsfiddle.net/92q0b43n/

**Comment by muradsofiyev** [comment]
Please look this snippet 
https://jsfiddle.net/92q0b43n/

**Comment by Johann-S** [comment]
yep that's what we called multi modals or nested modals

**Pull request closed without merging**
