### PR TITLE
Multiple input group addon

### LINKED ISSUE #17927: Invert selectors in input group
I am using Chrome 45.0.2454.10.

This issue persists in v3 and v4, when an input group contains only one `<input type="text" class="form-control"/>` element, it would lost the 100% width and renders all four corners without radius.

Another problem about the selector is when I add more than one addon at the same side, only `:first-child` and `:last-child` removes the border of the opposite side.

See [this plunker](http://run.plnkr.co/plunks/Tud4LzDeDy8p3O6XetXk/) for a demo.

This issue can be fixed by,

0. Adding `width: 100%` to `.input-group`.
0. Flipping `:first-child` selectors to `:not(:last-child)` in `.form-control`, `.input-group-addon` and `.input-group-btn` under `.input-group`
0. Flipping `:last-child` selectors to `:not(:first-child)` in `.form-control`, `.input-group-addon` and `.input-group-btn` under `.input-group`

Not sure if this introduces other issues, any ideas?

### PR DESCRIPTION
**Pull request by vicary**
Resubmit to `v4-dev` branch.

Fixes #17927

See this [plunker](http://run.plnkr.co/plunks/7YoCtoXU75EKoi5zR4Ef/) for a live demo.

### CODE REVIEW

**Comment by cvrebert** [comment]
@vicary You're going to need to craft a new patch with `v4-dev` as your starting point. `master` and `v4-dev` have diverged too much for a patch against `master` to apply to `v4-dev` anymore.

**Comment by vicary** [comment]
@cvrebert Not sure but can I rebase to `v4-dev`?

**Comment by cvrebert** [comment]
Since almost all the files basically got rewritten when we ported the code from LESS to Sass, rebasing is very unlikely to usefully work.

**Comment by vicary** [comment]
Ok I'll start again from `v4-dev`.

**Comment by cvrebert** [comment]
Successor: #18500

**Pull request closed without merging**
