### PR TITLE
Remove --save option as it isn't required anymore

### PR DESCRIPTION
**Pull request by stevemoser**
"As of npm 5.0.0, installed modules are added as a dependency by default, so the --save option is no longer needed. The other save options still exist and are listed in the documentation for npm install."

https://stackoverflow.com/a/19578808/142358

### CODE REVIEW

**Comment by XhmikosR** [comment]
Unfortunately, node.js 6.x is still supported and that ships with node 3.x.

**Comment by XhmikosR** [comment]
Reopening as we are going to require Node >= 8 on master.

**Review by XhmikosR — APPROVED** [review]

**Comment by Johann-S** [comment]
@XhmikosR shouldn't we remove `jquery` here ?

**Comment by XhmikosR** [comment]
Not in master, in your no jquery branch these changes should be made.

**Pull request merged**
