### PR TITLE
#10756 Dropdown auto position fix

### PR DESCRIPTION
**Pull request by andreyshikov**

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: f47df45900a2bb609148da63117b0a2099dca8a9
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/56556700

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: a2ebb76d4f05f452b7eeba89ebe60c62fcbd55c9
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/56576515

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
I'm pretty sure we've deemed this feature as out-of-scope for bootstrap v3. I'm about to takeoff; another Core Team member can hopefully find the previous issue to reference.

**Comment by cvrebert** [comment]
Closing per https://github.com/twbs/bootstrap/issues/10756#issuecomment-42911101
Perhaps in Bootstrap v4.

**Pull request closed without merging**
