### PR TITLE
remove generated content value for progress

### PR DESCRIPTION
**Pull request by patrickhlauke**
as it's currently not displayed, and (in my opinion) would look fugly if it did appear...

### CODE REVIEW

**Comment by cvrebert** [comment]
Agreed. At a minimum, I assume the length of the percentage text changing as its number of digits increased would make the bar jump around a bit.
And the lack of a "%" sign doesn't help.
CC: @mdo

**Comment by patrickhlauke** [comment]
also, to make this work consistently in IE/Edge, Firefox etc would require further generated content / vendor prefixed pseudo element acrobatics too...for little gain, I'd say.

if we DO decide that having the value shown is necessary, i'd alternatively like some simple class to turn this off (or better, have it off by default but opt-in)

**Comment by patrickhlauke** [comment]
> And the lack of a "%" sign doesn't help.

more generally, the value is only ever a percentage when `max=100`. as `max` can be any value, it would be inappropriate to add "%" to the generated content unless we do some extra math somewhere to calculate (value/max)*100 ... urgh

**Comment by patrickhlauke** [comment]
not hearing any objections (and considering that currently the CSS isn't actually generating anything visible, so this change is not actually changing anything)...merging.

**Pull request merged**
