### PR TITLE
V4 dev docs library updates

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @cvrebert @hnrch02

### CODE REVIEW

**Comment by cvrebert** [comment]
The Holder.js update seems to break in Chrome:
holder-broke

**Comment by cvrebert** [comment]
The updated Anchor.js and Clipboard.js seem to work fine.

**Comment by XhmikosR** [comment]
Weird, I tested Firefox, IE 10 and worked fine there. I'll skip the holder update and merge.

**Comment by XhmikosR** [comment]
@imsky: any idea why this happens?

On a side, note this happened with Firefox the second time, so it's like random. v2.8.2 works fine in all cases, it seems.

**Comment by imsky** [comment]
i'll look into why this is happening

**Pull request merged**
