### PR TITLE
Fix: Preserve Up/Down Arrow Key Scrolling Functionality in Tabs Navigation

### LINKED ISSUE #39969: Horizontal tabs: Down and Up Arrows usage not allowed
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

According to the [W3C tabs pattern](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/):
_When a tab list has its **aria-orientation** set to **vertical**:
Down Arrow performs as Right Arrow (moves focus to the next tab).
Up Arrow performs as Left Arrow (moves focus to the previous tab).
If the tab list is horizontal, it does not listen for Down Arrow or Up Arrow so those keys can provide their normal browser scrolling functions even when focus is inside the tab list._

These rules aren't supported by Boostrap 5 actually

### Reduced test cases

It's possible to check these keyboard interactions in the documentation page https://getbootstrap.com/docs/5.3/components/navs-tabs/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

v5.3

### PR DESCRIPTION
**Pull request by ac-mmi**
This pull request addresses [#39969](https://github.com/twbs/bootstrap/issues/39969) issue where the arrow up and arrow down keys, used for navigating between tabs in Bootstrap, override the default scrolling functionality. 
The proposed changes allow users to navigate between tabs using the arrow keys without disabling the default scroll behavior of the up and down keys.

Closes #39969

### CODE REVIEW

**Review by julien-deramond — CHANGES_REQUESTED** [review]
Thanks for creating a PR @ac-mmi 
I haven't looked at the code, but there are already things to change, please:
* fix the linting issues
* fix the JS tests that are failing
* add some unit tests to cover this use case

**Comment by ac-mmi** [comment]
> Thanks for creating a PR @ac-mmi I haven't looked at the code, but there are already things to change, please:
> 
> * fix the linting issues
> * fix the JS tests that are failing
> * add some unit tests to cover this use case

`Done`

**Comment by ac-mmi** [comment]
> Thanks for creating a PR @ac-mmi I haven't looked at the code, but there are already things to change, please:
> 
> * fix the linting issues
> * fix the JS tests that are failing
> * add some unit tests to cover this use case

done

**Comment by julien-deramond** [comment]
Thanks a lot for your time @ac-mmi and the creation of this PR. However, based on the discussion in https://github.com/twbs/bootstrap/issues/39969, we decided to keep the current behavior. So, this PR can be closed and won't be merged.

**Comment by ac-mmi** [comment]
> Thanks a lot for your time @ac-mmi and the creation of this PR. However, based on the discussion in #39969, we decided to keep the current behavior. So, this PR can be closed and won't be merged.

but don't you think it is evident that when using horizontal alignment one would only use right/left and up/down for scrolling

**Pull request closed without merging**
