### PR TITLE
Change floating label placeholder's color

### LINKED ISSUE #39420: Placeholder colour for floating labels
### Discussed in https://github.com/orgs/twbs/discussions/39394

<div type='discussions-op-text'>

<sup>Originally posted by **lonix1** November 12, 2023</sup>
For floating labels: in the non-floating position it is dark, and in the floating position it is light.

But a placeholder is typically light to show that it's not real text.
</div>

I was surprised that in the non-floating state it is a dark colour. I thought it must be a mistake on my side - but when I checked the docs I found that it is the same (dark).

### PR DESCRIPTION
**Pull request by TommasoAllegretti**
### Description

Changed the floating labels placeholder's text color from black to light gray (`opacity: 0.65`).
I removed the styling from the other `label` tags under `.form-select` and `.form-control:-webkit-autofill` parents as every `label` should now have the same behavior.

### Motivation & Context

As requested in issue #39420 

### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

#### Live previews

 <https://deploy-preview-39494--twbs-bootstrap.netlify.app/docs/5.3/forms/floating-labels/#example/> 

### Related issues

#39420

### CODE REVIEW

**Comment by theodorejb** [comment]
👍 Yes! I've often been confused by the current text color since it looks like a value rather than a placeholder.

**Review by louismaximepiton — APPROVED** [review]
The solution looks fine from a CSS point of view. Any thoughts @mdo ?

**Review by mdo — APPROVED** [review]
Do we need to modify the `$form-floating-transition` value as well?

**Comment by louismaximepiton** [comment]
I think it's fine as-is.

**Comment by theodorejb** [comment]
Is there anything preventing this from being merged?

**Comment by julien-deramond** [comment]
> Is there anything preventing this from being merged?

For the moment, the target of this one is v5.4.0. The next version will probably be a v5.3.x. We'll evaluate when to merge it at the appropriate time.

**Review by mdo — APPROVED** [review]
I think we can add this in v5.3.4.

**Review by julien-deramond — APPROVED** [review]

**Pull request merged**
