### PR TITLE
Make equal-width flexbox extend grid-column

### PR DESCRIPTION
**Pull request by vinpac**
Fixed equal-width flexbox columns, so now they will act like normal columns as they break.

### CODE REVIEW

**Comment by vinpac** [comment]
A `col-fill` would be a great feature too, but I'm looking for more real world examples before adding it.

```
.col-fill {
  flex: 1 1 auto;
}
```

**Comment by mdo** [comment]
What does this fix exactly? I don't see the benefit of this without a JS Bin or demo showing the before and after.

**Comment by vinpac** [comment]
These equal-width flexbox classes aren't breaking as normal columns do. When they were supposed to break, they just don't break, making the breakpoints useless on them. It happens because they were not extending %grid-column.

Here's an example: https://jsbin.com/baqoriqagu/edit?html,css,output

Just change the `$equal-width-flex-extend-grid-column` to see the difference.

**Comment by mdo** [comment]
Gotcha. Okay, I took a look and cleaned some things up in #20829. Thanks!

**Pull request closed without merging**
