### PR TITLE
Update nav-tab.md

### PR DESCRIPTION
**Pull request by jitangupta**
Updated the `anchor` tag with `button` in sample examples

### CODE REVIEW

**Review by mdo — APPROVED** [review]

**Review by ffoodd — APPROVED** [review]

**Comment by XhmikosR** [comment]
@mdo @ffoodd: we use both `a` and `button`s in the markup examples, are you sure it makes sense to change the JS API examples?

**Comment by ffoodd** [comment]
I'd recommend to always use buttons for tabs, so yes. Might we replace `a`s with `button`s everywhere, too?

**Comment by XhmikosR** [comment]
I'd just change this patch to indicate that both can be used for now using a JS comment, since both markups are allowed.

**Comment by mdo** [comment]
Going to merge as-is and we can iterate on this further with additional PRs.

**Pull request merged**
