### PR TITLE
Add `.mt-3` to some of the buttons in form docs

### LINKED ISSUE #27606: Button spacing/position in Dropdowns forms component docs
The button placement within the dropdown menu in the Docs example doesn't look great being so squashed against the 'remember me' checkbox, I think there needs to be some additional margin at the top here: https://getbootstrap.com/docs/4.1/components/dropdowns/#forms

### PR DESCRIPTION
**Pull request by sts-ryan-holton**
Fixes #27606

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
@sts-ryan-holton, I would prefer to keep the `.form-group` as wrapping class, like we have here: https://getbootstrap.com/docs/4.1/components/forms/#custom-styles

Can you maybe change that?

**Review by sts-ryan-holton — COMMENTED** [review]
Removed `.mt-3` and wrapped in `.form-group`

**Comment by sts-ryan-holton** [comment]
@MartijnCuppens Makes sense, not sure if you wanted to move the `.form-check` element inside the existing `.form-group` or generate a new `.form-group` and put it in there. I decided to go with the latter and create a new wrapping `.form-group` to keep things consistent here.

**Review by MartijnCuppens — COMMENTED** [review]
Looks good, thanks @sts-ryan-holton!

**Review by MartijnCuppens — APPROVED** [review]

**Pull request merged**
