### PR TITLE
add information about valid selectors

### PR DESCRIPTION
**Pull request by Johann-S**
Finally I revert this code, because there are a lot of use case to detect a valid uniq `id`, so it's better to add information about that in documentation

### CODE REVIEW

**Review by glebm — APPROVED** [review]
Thanks!

**Comment by XhmikosR** [comment]
I'm personally thinking we might need to revert this change. I mean, technically we are right, but it is a breaking change...

That being said, I'd change this one to a warning or something to make it stand out maybe.

**Comment by Johann-S** [comment]
That's not a breaking change @XhmikosR because that's what we shipped in our last release see: https://github.com/twbs/bootstrap/blob/v4.1.3/js/src/util.js#L78-L89 That's exactly the same code, we just add some information about valid selectors

**Comment by XhmikosR** [comment]
Yes, I meant when this was added, not the revert.

**Comment by Johann-S** [comment]
Oh ok 😄 
Why not make that into a `warning` but I thought it was to huge to be a warning 🤔

**Comment by XhmikosR** [comment]
@Johann-S: is it hard to revert the related changes? If it's too hard let's leave it as is and make this a warning. But ideally we shouldn't introduce breaking changes.

**Comment by XhmikosR** [comment]
I don't know at this point. When was this introduced? 4.1.3 or older?

**Comment by Johann-S** [comment]
It was on 4.1.2

**Pull request merged**
