### PR TITLE
Add information about our bundle dist file which contain Popper.js inside

### PR DESCRIPTION
**Pull request by Johann-S**
Add information about our bundle dist file which contain Popper.js inside

/CC @XhmikosR and @mdo because I'm not sure of my english here 😄

### CODE REVIEW

**Comment by XhmikosR** [comment]
I'm not a native English speaker either as you know :)

That being said, I think the word `inside` is redundant here.

**Comment by FezVrasta** [comment]
> already includes

maybe

**Comment by Johann-S** [comment]
I made some changes 👍

**Comment by XhmikosR** [comment]
@Johann-S: I'd go with this:

```md
Be sure to include [popper.min.js]({{ site.cdn.popper }}) before Bootstrap's JavaScript or use `bootstrap.bundle.min.js` / `bootstrap.bundle.js` which contains Popper.js.
```

**Comment by Johann-S** [comment]
yep that's better thanks @XhmikosR

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
