### PR TITLE
[Accessibility / JS] Add unit tests for aria-describedby to popover suite

### PR DESCRIPTION
**Pull request by kkirsche**
Add unit tests for `aria-describedby` to popover suite. This tests that `aria-describedby` is added when showing the popover and removed when it is hidden.

### CODE REVIEW

**Comment by kkirsche** [comment]
Not sure why this isn't triggering a Travis Build... anyone able to help with why that's not occurring?

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: df3b93296260c0c09aeeb1c7e5ed75a0e8f973ee
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/52150381

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by hnrch02** [comment]
Hmm, this is already covered by `aria-describedby` in the tooltip unit tests.

**Comment by kkirsche** [comment]
Fair. If you or any of the other admins feel this should be closed we can do that.

My thought process behind it is that popover needs to implement Tooltip so I assume it would be possible for things to get messed up and function differently on each component situation.

**Comment by hnrch02** [comment]
Since the popover doesn't override either the `show` or the `hide` method and I doubt that this is going to change in the future, I'll close this. Thanks though.

**Pull request closed without merging**
