### PR TITLE
Fix reboot for placeholder links

### LINKED ISSUE #28010: Reboot for focused placeholder link
The focus states are taken into consideration, but I have a doubt about the necessity of them.

https://github.com/twbs/bootstrap/blob/39b76861a7afc2ccc90752a61fa5aa998e94761f/scss/_reboot.scss#L199-L211

It can be removed IMO. After:

```scss
a:not([href]) {
  color: inherit;
  text-decoration: none;

  @include hover {
    color: inherit;
    text-decoration: none;
  }
}
```
Related to:  #21633, #21487, #19411

Any thoughts?

P.S: If we have `plain-hover()` mixin like the [plain-hover-focus() mixin](https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_hover.scss), can be more simplified:

```scss
a:not([href]) {
  @include plain-hover {
    color: inherit;
    text-decoration: none;
  }
}
```

### PR DESCRIPTION
**Pull request by ysds**
Fixes #28010

* native: https://codepen.io/anon/pen/eqdNVZ
image
* current: https://codepen.io/anon/pen/oKzXGG
image
* after: https://codepen.io/anon/pen/PMGqaX
image

### CODE REVIEW

**Comment by ysds** [comment]
I'm not sure should backport this to v4.

**Review by MartijnCuppens — APPROVED** [review]

**Comment by XhmikosR** [comment]
Should we backport this?

**Comment by MartijnCuppens** [comment]
Yup. I would wait for @patrickhlauke's aproval before merging this, just to be sure.

**Comment by patrickhlauke** [comment]
so if it's a placeholder, but it has been explicitly made focusable with `tabindex="0"` or any tabindex value > 0, this would suppress any focus indication? if so, not sure i'd agree...focus needs to be shown somehow.

**Comment by ysds** [comment]
@patrickhlauke The after behavior is:

focus

Windows 10, Chrome 75

**Review by patrickhlauke — APPROVED** [review]

**Comment by XhmikosR** [comment]
This needs to be manually backported to v4-dev. Can someone do it?

**Comment by patrickhlauke** [comment]
urgh only noticed now, should probably also amend the preceding comment in the scss that talks about tabindex...

**Comment by patrickhlauke** [comment]
> This needs to be manually backported to v4-dev. Can someone do it in my v4-dev-xmr branch?

done https://github.com/twbs/bootstrap/pull/29162

**Pull request merged**
