### PR TITLE
iPhone X Fix

### PR DESCRIPTION
**Pull request by Dygear**
Adds `viewport-fit=cover` to the meta viewport tag allowing for page headers and footers to span the entire screen with the iPhone X.

### CODE REVIEW

**Comment by Dygear** [comment]
Ok, so that wasn't the cleaest way to do that. I didn't read the `Add more commits by pushing to the patch-1 branch` Until after the fact. But that commit cleans up the rest of the places where the meta viewport is used within adding `viewport-fit=cover` for the iPhone X.

**Comment by andresgalante** [comment]
@Dygear Don't worry if it gets merge it'll be squashed.

Let me add this article about "the notch" for more clarification on what this PR is doing:
https://css-tricks.com/the-notch-and-css/

**Review by patrickhlauke — COMMENTED** [review]
Would be good to test all of this to ensure that there's no content now falling into the safe area that would require additional padding or similar before merging.

**Comment by Dygear** [comment]
I’m actually using it. But I can provide example screen shots if you wish based on these code changes here to prove it doesn’t require additional padding. (On the iPhone Simulator for the iPhone X.)

**Comment by mdo** [comment]
Before and after screenshots here. Going to need a bit more than the viewport change I think.

screen shot 2017-10-02 at 5 41 19 pm
screen shot 2017-10-02 at 5 41 07 pm

**Comment by XhmikosR** [comment]
I'm personally not sure about this change. It's not like things work fine out of the box by just adding `viewport-fit=cover`.

**Comment by Dygear** [comment]
I’m going to have to add some padding to make this work correctly on the iPhone X without the content div wrapper.

**Comment by mdo** [comment]
Closing this out for now given it doesn't cleanly solve the problem. Looking forward to other ideas though! I can test on mine in 2-3 weeks. 😆

**Comment by ThomasBerends** [comment]
@mdo The addition of a padding fix could solve the problem:

https://booking.design/how-we-adapted-the-booking-com-mobile-site-for-the-iphone-x-notch-e880fa00e989

**Pull request closed without merging**
