### PR TITLE
Input group - fix margins

### PR DESCRIPTION
**Pull request by vchebotarev**
Hi.
With the help of input-group i want to make something like this (perfect variant already fixed)
joxi_screenshot_1528964290145
But there is a problem with double borders
joxi_screenshot_1528963219807
So i've fixed it, and now it looks like this - without double margins
joxi_screenshot_1528965389632

### CODE REVIEW

**Comment by TheJoppley** [comment]
Hi, where are you from?

**Review by andresgalante — APPROVED** [review]
Thanks @vchebotarev

**Comment by andresgalante** [comment]
@vchebotarev I've patch your PR to add an example of an add on between 2 inputs on the docs.

**Comment by ysds** [comment]
This change will cause a problem when there is validation feedback.

@andresgalante Please check with the test cases in #25352

**Comment by ysds** [comment]
Please see also #25120

**Review by andresgalante — CHANGES_REQUESTED** [review]
Thanks @ysds I'll change my approval for this PR, sorry @vchebotarev It will cause problems for feedback validation described here #25352 and #25120

Thanks again @ysds for keeping an eye on it

**Comment by mdo** [comment]
Thanks, but we'll pass on this for now as it starts to take us in an even crazier direction with input group support for multiple components.

**Pull request closed without merging**
