### PR TITLE
Update Translations page's Chinese Language website link for bootstrap 5

### PR DESCRIPTION
**Pull request by zoomla**
We are the maintenance team of the bootstrap Chinese Language website,Glad to see Boostrap 5 published beta1.
This is A exciting news！

Now， We apply to Update Translations page's Chinese Language website link,
Here is the new information：
Title: Bootstrap 5 · 全球最流行的HTML、CSS和JS前端web框架
Url: http://code.z01.com/bootstrap

At the same time, we will continue to optimize Chinese translation, so that our products can be known and adopted by more users, and contribute to the development of the Internet!

Thinks!

-- by Zoomla! CMS Team(boostrap Chinese Language website maintainer)

### CODE REVIEW

**Comment by XhmikosR** [comment]
Something seems off with your site...

image

Also, I see plenty of non-https links and stuff that are not present in our docs.

**Comment by zoomla** [comment]
Our colleagues have just updated the webpage, so there are some problems, which have been solved now.
we website Support at the same time https or http,Because the Internet environment for Chinese users is relatively conservative，
you kan click: https://code.z01.com/bootstrap 
or : http://code.z01.com/bootstrap 

At present, many Chinese users are not used to forcing HTTPS (there are still many users using IE8 in China). After a period of time, we will implement unified enforcement of HTTPS.

Please approving ,tks.

**Comment by XhmikosR** [comment]
The issue is still not fixed here.

Also:

1. jQuery shouldn't be needed in v5, not sure why you even load it. Let alone you are loading twice
2. You don't need to load popper. Just load our bundle dist file like we do ourselves
3. your site is super slow from Europe (I assume the same from everywhere in the world apart from Chine), can't you use GitHub Pages and/or Cloudflare in front?

**Comment by zoomla** [comment]
> * 一样加载我们的bundle dist文件
> * 您的网站来自欧洲的速度非常慢（我认为除中国以外，世界各地的网站都一样），您不能在前面使用GitHub Pages和/或Cloudflare吗？

好的，我们再优化它。

**Comment by XhmikosR** [comment]
Also, https://code.z01.com/bootstrap/assets/js/ie-emulation-modes-warning.js is not needed. Bootstrap v5 does note support IE at all.

So, this makes your argument about IE8 moot. The site won't work on IE properly, so this means you should only use https.

**Comment by XhmikosR** [comment]
I don't speak Chinese, sorry. Unless the issues are sorted, I'm afraid we can't merge this.

**Comment by XhmikosR** [comment]
```
09:40:45.583 downloadable font: cmap: multiple 0xffff terminators found (font-family: "zico" style:normal weight:400 stretch:100 src index:1) source: https://ico.z01.com/dist/fonts/zi-regular.woff
09:40:45.959 downloadable font: cmap: multiple 0xffff terminators found (font-family: "zicoTm" style:normal weight:400 stretch:100 src index:1) source: https://ico.z01.com/dist/fonts/zi-tm.woff
09:40:47.112
Uncaught 
Restricted {  }
bootstrap:367:1
    <anonymous> http://code.z01.com/bootstrap/:367
09:46:02.416 Blocked loading mixed active content “http://ico.z01.com/dist/css/zico.min.css”
bootstrap
09:46:02.440
Uncaught ReferenceError: Holder is not defined
    <anonymous> https://code.z01.com/bootstrap/:367
bootstrap:367:1
    <anonymous> https://code.z01.com/bootstrap/:367
```

**Review by XhmikosR — CHANGES_REQUESTED** [review]
Plenty of fixes are needed

**Comment by zoomla** [comment]
> Plenty of fixes are needed

ok,tks

**Comment by zoomla** [comment]
Dear XhmikoR:
1.According to your valuable comments, we deleted the Jquery and popper.
2.Mandatory use  model https 
3.With regard to the speed of visits, yes, China's visits are controlled by the government. Not all international visits (Europe and North America) are smooth. We call it "翻墙 fan qiang".We didn't even have a smooth access to GitHub :(
That's why we need a Chinese language version of the site. In bootstrap v4.x, we have been providing accurate translation to serve 1.6 billion people in China.
4. In fact, we will also provide some Chinese optimization to meet the Chinese people's usage habits. There is a huge difference between them. However, we are committed to public welfare and have no business motivation.
5. 
Next, we will optimize the translation, including a lot of details, just like https://code.z01.com/v4.

Hope to get approval ,tks!

**Comment by XhmikosR** [comment]
I'm sorry but your page is still broken here.

image

You are wrongfully loading our docs.min.js. Never do that for obvious reasons.

**Comment by XhmikosR** [comment]
Closing for now. Feel free to make a new PR when everything is sorted. Thanks!

**Pull request closed without merging**
