### PR TITLE
More minor build tweaks.

### LINKED ISSUE #22476: Build issues
Due to the merged of https://github.com/twbs/bootstrap/pull/22045

~they are few errors, on Travis see :~
~- https://travis-ci.org/twbs/bootstrap/jobs/223876338#L312~
~- https://travis-ci.org/twbs/bootstrap/jobs/223876309#L303~

And on my computer (Win10) `js-compile-bundle` don't work because it failed here : 
`shx sed 's/^(import|export).*//'`

I changed this part of this task into to make it works : 

`shx sed \"s/^(import|export).*//\"`

/CC @bardiharborow

### LINKED ISSUE #22490: Rewrite build system documentation to document new npm scripts.
Things done: 
- cloned bootstrap (v4-dev latest commit was: fb3303f)
- $npm install 
- $npm test finishes and succeeds

When running grunt test-js:
```
bootstrap]$ grunt test-js
Warning: Task "test-js" not found. Use --force to continue.

Aborted due to warnings.
```
Running only grunt yields to the same result. 

Changing to branch master, grunt test-js runs.

### PR DESCRIPTION
**Pull request by bardiharborow**
Closes #22388. Closes #22476. Closes #22490.

### CODE REVIEW

**Comment by Johann-S** [comment]
Is it possible @bardiharborow to clear a bit because in logs they are all the requests logged and it's useless for us for example : https://travis-ci.org/twbs/bootstrap/jobs/223901460#L1161

**Comment by bardiharborow** [comment]
@Johann-S that's fixed in https://github.com/twbs/bootstrap/pull/22477/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R41

**Comment by Johann-S** [comment]
Nice thank you @bardiharborow 👍

**Comment by patrickhlauke** [comment]
new build system seems borked on windows at the moment? did a completely fresh node installation, tried `npm install`, and it errors out
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

**Comment by wolfy1339** [comment]
@patrickhlauke that's normal on Windows, it hapens all the time.
`fsevents` is only for macOS/OSX

**Comment by patrickhlauke** [comment]
@wolfy1339 didn't happen in previous build system. ok, as it's marked as optional, ignoring.

running `npm run test` it then fails (despite latest node) here
```
'export).*' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! bootstrap@4.0.0-alpha.6 js-compile-bundle: `shx cat js/src/util.js js/src/alert.js js/src/button.js js/src/carousel.js js/src/collapse.js js/src/dropdown.js js/src/modal.js js/src/scrollspy.js js/src/tab.js js/src/tooltip.js js/src/popover.js | shx sed 's/^(import|export).*//' | babel --filename js/src/bootstrap.js | node build/stamp.js > dist/js/bootstrap.js`
```

(sorry, not trying to be difficult...just hoping these can be resolved and these cryptic messages mean something to you folks, as i'm hopelessly lost in this command line stuff and just want to get back to a working build environment to tackle some issues :) )

**Comment by Johann-S** [comment]
@patrickhlauke fixed in this PR, also reported by me

**Comment by patrickhlauke** [comment]
@Johann-S ah ok cool. it's all greek to me, so not even tried checking this PR out. i'll hang fire in hopes that it gets merged soon...

**Comment by Johann-S** [comment]
@bardiharborow How can I use `watch` task in our new build system ? Because it's an convenient task and I'm afraid this task is missing 😨

**Comment by bardiharborow** [comment]
@patrickhlauke hey, sorry for breaking Windows support, that was not very well tested from my end. I'm merging this now. Please ping me if there's anything else broken. I might try to get hold of a Windows box to test as well.

**Comment by patrickhlauke** [comment]
@bardiharborow sorry, was being more cranky then usual there. will give this a whirl and report back in a happier mood :)

**Comment by patrickhlauke** [comment]
just tested. `npm run test` runs smooth now, but fails at linting stage
```
[htmllint] found 256 errors out of 102 files
```
are the linting rules new/changed in this new build process?

**Pull request merged**
