### PR TITLE
Hover element-state utility clasess

### PR DESCRIPTION
**Pull request by DougPuchalski**
Make consistent use of element-state emulating classes in hover mixin.

### CODE REVIEW

**Comment by alecpl** [comment]
Imo, adding`.hover` does not make much sense to me. I also don't really know why we have `.focus`.

**Comment by aceofspades** [comment]
@alecpl Honestly it's really just for troubleshooting and to be able to produce a design palette showing all of the styles. IMO there needs to be a static way to activate all styling so as not to rely on actual interactions in the browser.

**Comment by mdo** [comment]
I like that last comment—having a CSS debug mode would be helpful.

I think this can be skipped for now, but I'd like to see something explore more for debugging styles. The 1px red outline is a classic one, triggering focus/hover/active states could be another, etc.

**Comment by aceofspades** [comment]
@mdo What's the proper way to move forward if not with an open issue?

**Pull request closed without merging**
