### PR TITLE
Remove unnecessary reduce motion when $enable-transition: false

### PR DESCRIPTION
**Pull request by ysds**
When `$enable-transition: false`, 
```scss
@media (prefers-reduced-motion: reduce) {
   transition: none;
}
```
is unnecessary.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@ysds don't forget to add the projects in the PRs :)

**Comment by XhmikosR** [comment]
If this is supposed to be backported to v4, we need the 4.4.2 project too.

**Review by MartijnCuppens — APPROVED** [review]

**Comment by XhmikosR** [comment]
Any reason why not include this in alpha-1 and 4.4.2 subsequently?

**Comment by ysds** [comment]
I think this a minor bug. To speed up the release of Alpha1, I targeted this to Alpha2 not to increase our review work, but now the review was completed it is fine to include this in Alpha1.

I forgot to put it in 4.4.2 ^^;

**Pull request merged**
