### PR TITLE
Update Popper.js to 1.12.3

### LINKED ISSUE #23622: Update NuGet Popper.js dependency version
Right now the nuspec file is requiring for `1.11.x` but the first valid/non-broken NuGet version of Popper.js is 1.12.2

### PR DESCRIPTION
**Pull request by Johann-S**
Update Popper.js with the first non-broken NuGet version of Popper.js

Fixes #23622

### CODE REVIEW

**Comment by jipexu** [comment]
Hi 
with this version of popper i got js error on console  ...
please see at this 
[(https://github.com/FezVrasta/popper.js/issues/398)]

but i can not reproduce in code pen ..

Any idea ?

**Comment by XhmikosR** [comment]
I can't comment on the update itself since I haven't been following popper.js's development, so if you test and everything is good we are fine.

One thing I'd change is to use the Jekyll config variable. So if you agree and everything is good merge after that @Johann-S

**Review by XhmikosR — APPROVED** [review]

**Comment by Johann-S** [comment]
Is it possible to create a Codepen with Bootstrap @jipexu ?
I'll try to do some more test today before merging this PR 
and thanks @XhmikosR that's a very good change 👍

**Comment by jipexu** [comment]
hi @Johann-S  no i tried but i can not see on codepen console ... 
to see is simple juste create some element with attribut title and data-toggle="tooltip"  ... 
on hover if some value of the title attribut are empty in html we get the error in the browser console
i will try again to see this in code pen.... Thanks

**Comment by jipexu** [comment]
@all many sorry i was wrong i used data-placement="top-start" so i got this error :-(

**Comment by Johann-S** [comment]
So everything is fine 😃 I'll merge this one or @XhmikosR it seems he is present 😆

**Pull request merged**
