### PR TITLE
Add custom range styles

### LINKED ISSUE #17916: New feature request:  Add a style class for input type="range"

### PR DESCRIPTION
**Pull request by wolfy1339**
Fixes #17916
I'm open for comments and able to do a rebase.
This was inspired by [m8tro's range style](https://github.com/idleberg/m8tro-bootstrap/blob/master/src/themes/m8tro/input/slider.less) but fully changed to use Bootstrap default colors.

### CODE REVIEW

**Comment by wolfy1339** [comment]
Hello, I was just wondering if everything is alright about my pull request. It was a while since the last activity on it.

**Comment by wolfy1339** [comment]
Rebased on latest `v4-dev` branch and used the transition mixin instead of if statements

**Comment by wolfy1339** [comment]
Update: Added docs

**Comment by wolfy1339** [comment]
Hello, Can anyone review this

**Comment by mdo** [comment]
Closing for the more complete #23380. Sorry for the lack of a response here, @wolfy1339, and thank you for the PR nonetheless. <3

**Pull request closed without merging**
