### PR TITLE
Remove explicit suppression of focus outline

### PR DESCRIPTION
**Pull request by patrickhlauke**
It's unclear what the reason for first introducing the original hack here (for `[tabindex="-1"]:focus {...}`) was. Seems something that may have been useful/necessary in SuitCSS, but don't think BS ever relied on this. https://github.com/twbs/bootstrap/issues/18330
It's since been modified to only apply when the browser wouldn't apply a visible outline anyway based on its own heuristics (the `:not(:focus-visible)` part) https://github.com/twbs/bootstrap/pull/28437/

But now, thinking this through more...in browsers that do support this pseudo-selector, what this is essentially saying is redundant: don't apply outline in cases where a `tabindex="-1"` element receives focus but the browser wouldn't normally apply focus outline". at best, this is unnecessary. at worst, this actually overrides things an author may explicitly be trying to do with adding `:focus { outline: ... }` explicitly.

### CODE REVIEW

**Comment by patrickhlauke** [comment]
prompted by https://github.com/twbs/bootstrap/issues/29875

**Comment by patrickhlauke** [comment]
Want to primarily see if removing this in reboot causes any of bootstrap's own components to suddenly start showing inappropriate focus outlines on things like modal dialog containers etc. It shouldn't, since I believe we explicitly suppress these cases where `tabindex="-1"` is used and focus is set to it. And if we do find that core BS components do suffer when this is removed, the problem should likely be fixed *there* at the component level, rather than with this heavy-handed-yet-redundant-if-you're-doing-it-right fix in reboot

**Comment by patrickhlauke** [comment]
Doesn't seem to adversely affect any of our components, from testing. And, as the change in https://github.com/twbs/bootstrap/pull/28437 already essentially neutered this directive, I think it's safe to fully remove it.

**Comment by ffoodd** [comment]
Just had a look using Firefox—which IMHO is the most susceptible of messing focus styles— and didn't notice anything. Tested modals, collapses and skip links.

**Review by ffoodd — APPROVED** [review]

**Pull request merged**
