### PR TITLE
Only change aria-pressed if it's not an input-based radio or checkbox group

### PR DESCRIPTION
**Pull request by patrickhlauke**
`aria-pressed="true"`/`aria-pressed="false"` is really only useful for making on/off toggles out of, say, `<button>` elements. the attribute is useless (and potentially confusing/conflicting) on, say, `<label>` elements for an existing `<input type="radio">` or similar.

closes https://github.com/twbs/bootstrap/issues/22040

### CODE REVIEW

**Review by Johann-S — DISMISSED** [review]
Maybe is it possible to add a unit test here ?

**Comment by patrickhlauke** [comment]
@Johann-S ah yes, good call on unit tests. will get on that this morning

**Comment by patrickhlauke** [comment]
@Johann-S mind having a look over the unit test i just added? admittedly, i'm not so hot on qunit nor clean jquery, so likely i'm going about this in an unnecessarily convoluted way

**Comment by Johann-S** [comment]
It seems you let some trailing spaces see : https://travis-ci.org/twbs/bootstrap/jobs/220509346#L220

But your unit test is fine 👍

**Comment by patrickhlauke** [comment]
@Johann-S cool. trailing spaces killed. will go ahead and merge. thank you :)

**Pull request merged**
