### PR TITLE
Bump website copyright year

### PR DESCRIPTION
**Pull request by zlatanvasovic**

### CODE REVIEW

**Comment by yakov116** [comment]
#29944

**Comment by zdroid** [comment]
@yakov116 that's `master` branch, this is `gh-pages`.

**Comment by XhmikosR** [comment]
I don't think this gives any value and in fact we should just remove the meta from the gh-pages branch, unless we link to these files. (LICENSE, LICENSE-DOCS)

/CC @mdo

**Comment by mdo** [comment]
We can remove them from `gh-pages`.

**Comment by XhmikosR** [comment]
Made #29959 which removes these files.

**Pull request closed without merging**
