### PR TITLE
fix collapse and modal for IE which do not handle boolean in Object.keys

### PR DESCRIPTION
**Pull request by Johann-S**
This code is covered that's why there are no unit tests in this PR

Fixes: #26266

/CC @XhmikosR

### CODE REVIEW

**Comment by XhmikosR** [comment]
@Johann-S: I'm still seeing errors with IE10. I can't try IE11 so please try that too.

```
jQuery.Deferred exception: Object.keys: argument is not an ObjectTypeError: Object.keys: argument is not an Object
   at _objectSpread (http://127.0.0.1:9001/dist/js/bootstrap.js:49:7)
   at _getConfig (http://127.0.0.1:9001/dist/js/bootstrap.js:2983:9)
   at Tooltip (http://127.0.0.1:9001/dist/js/bootstrap.js:2577:9)
   at Anonymous function (http://127.0.0.1:9001/dist/js/bootstrap.js:3060:13)
   at each (https://code.jquery.com/jquery-3.3.1.slim.min.js:2:2755)
   at each (https://code.jquery.com/jquery-3.3.1.slim.min.js:2:1429)
   at _jQueryInterface (http://127.0.0.1:9001/dist/js/bootstrap.js:3050:9)
   at Anonymous function (http://127.0.0.1:9001/assets/js/src/application.js:59:7)
   at each (https://code.jquery.com/jquery-3.3.1.slim.min.js:2:2755)
   at each (https://code.jquery.com/jquery-3.3.1.slim.min.js:2:1429)undefined 
SCRIPT5007: Object.keys: argument is not an Object 
jquery-3.3.1.slim.min.js, line 2 character 31232
```

**Comment by Johann-S** [comment]
Before we had that: https://github.com/twbs/bootstrap/blob/v4.0.0/dist/js/bootstrap.js#L31-L47

And now: https://github.com/twbs/bootstrap/blob/v4.1.0/dist/js/bootstrap.js#L46-L63

**Comment by XhmikosR** [comment]
https://github.com/babel/babel/tree/master/packages/babel-plugin-proposal-object-rest-spread#loose

**Comment by Johann-S** [comment]
@XhmikosR I fixed unit test in a separate commit, for me it's all good and we should merge this PR.

About `extends` warning, as you said on Slack we use it like this before so LGTM like that 👍

**Comment by Johann-S** [comment]
BTW it's possible to remove `loose` and avoid `extends` warning if you prefer 🤔 let me know 😉

**Comment by Johann-S** [comment]
Superseded by: #26291

**Pull request closed without merging**
