### PR TITLE
Remove old/unnecessary reboot bug fix

### PR DESCRIPTION
**Pull request by patrickhlauke**
From initial testing, this bug ("transparent `button` background results in a loss of the default `button` focus styles") doesn't seem to manifest itself anywhere in Bootstrap (since we don't just set transparent background anywhere on buttons, and when we do set explicit button styles in the more specific stylings, we already do create a custom `:focus` style anyway)

Incidentally, this forced definition of `:focus` is biting us in the rear because it essentially circumvents the browser logic that only applies focus outline based on the browser's heuristic (i.e. not applying the button outline when clicked with a mouse). this forces the focus style to always show even after a mouse click, which is causing is hassle that we then need to work around - see https://github.com/twbs/bootstrap/pull/32630

### CODE REVIEW

**Comment by patrickhlauke** [comment]
Testing with Firefox (and IE, though of course v5 isn't aimed at it, but the principle is the same for v4.x which does include it) on https://deploy-preview-32631--twbs-bootstrap.netlify.app/docs/5.0/content/reboot/#forms and https://deploy-preview-32631--twbs-bootstrap.netlify.app/docs/5.0/components/buttons/#outline-buttons and various other places, I see no issues with "transparent `button` background	results in a loss of the default `button` focus styles" per the comment. It may well be that we've been cargo-culting this fix unnecessarily.

**Review by MartijnCuppens — APPROVED** [review]

**Comment by patrickhlauke** [comment]
just want to wait/check with others like @mdo who may know of the original reason that patch was added in the first place... (or i could go on an archeological expedition to find the commit where this was first added)

**Comment by septatrix** [comment]
In the future it should be possible to use `:focus-visible` to only show focus styles when the browser determines they are necessary however support is currently not perfect

**Review by mdo — APPROVED** [review]

**Comment by patrickhlauke** [comment]
i'd say it's worth backporting as it shouldn't actually affect anything in v4. and other PRs that i think are worth backporting as well (e.g. https://github.com/twbs/bootstrap/pull/32630#pullrequestreview-562082948) rely on this PR to be backported if they're also to be backported

**Comment by patrickhlauke** [comment]
seems that while removing this fixes the unsightly behaviour in firefox (for when buttons are used as tab riders), something still trips up chromium making it show its default outline even on mouse press. this may need a further fix. adding

```
button:focus:not(:focus-visible) {
  outline: 0;
}
```

to reboot seems to work (and as it seems to only still be a problem in chromium, and recent chromium is one of the few browsers that supports `:focus-visible`, this seems like a fair enough addition...thoughts?)

**Comment by XhmikosR** [comment]
@mdo @MartijnCuppens please confirm if this can safely be backported or not.

**Pull request merged**
