### PR TITLE
alert border & position fix

### PR DESCRIPTION
**Pull request by AnnaLisik**

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
What does this fix?

**Comment by AnnaLisik** [comment]
> What does this fix?

it isnt fix; its enhacement.

**Comment by ffoodd** [comment]
And what does it enhances?

- `.alert-header` would be forced to be `.alert` direct child, why?
- `position: absolute` makes `.alert-header` out of flow, meaning your alert size does not account for it anymore and could possibly overflow—moreover your heading is now above additionnal content…
- why on earth applying `border-radius` on header? it doesn't have `background` nor `border` so it seems useless.

This seems irrelevant. Do you have further explanations?

**Comment by MartijnCuppens** [comment]
This doesn't make sense, closing this.

**Pull request closed without merging**
