### PR TITLE
Fix broken Examples link in the docs footer include – `footer.html`.

### PR DESCRIPTION
**Pull request by StevenBlack**
Re:  #23343 – **Broken Links on getbootstrap.com**

Clicking the `Examples` link in the home page footer yields 404.

If merged, this makes the footer `Examples` link like the one in docs-navbar.html which is the same source code folder.

Therefore `_includes/footer.html` and `_includes/docs-navbar.html` now use the same link to `Examples`.

### CODE REVIEW

**Comment by XhmikosR** [comment]
I don't have an issue with examples locally.

**Comment by XhmikosR** [comment]
BTW, I meant that there is a redirect in place.

**Comment by StevenBlack** [comment]
@XhmikosR  the problem is on the live website at http://getbootstrap.com, on every page that includes the footer.

**Comment by XhmikosR** [comment]
I know what you mean ofc.

I'm just saying, I don't get why this happens since the redirect **is** there.

@mdo: I guess it should hurt to merge. Can you update the gh_pages so that we stop getting such reports?

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
I'd still like to know why it happens though since the redirect is there.

**Comment by StevenBlack** [comment]
@XhmikosR my guess: a different `.htaccess` that's, understandably, not in the repo.

**Comment by XhmikosR** [comment]
There is no .htaccess. Everything is hosted on GitHub pages, thus the jekyll-redirect-from plugin.

**Comment by StevenBlack** [comment]
@XhmikosR this is still broken on the live website.

I understand that "docs go with the release" as @mdo said in a related PR, but I wonder if that's wise because, man, this error is all over the current getbootstrap site.

**Pull request merged**
