### PR TITLE
Support for prefers-color-scheme media query

### PR DESCRIPTION
**Pull request by silvinor**
This pull request seeks to offer the beginnings of a solution to issue #27514.

Following a conversation with @mdo (and @ffoodd) on his personal [AMA]( https://github.com/mdo/ama/issues/300) I decided to attempt to merge my experimentations with Dark Mode in my [bootstrap-dark-5]( https://github.com/vinorodrigues/bootstrap-dark-5) project, that in turn was just an add on to my [bootstrap-dark]( https://github.com/vinorodrigues/bootstrap-dark) ramblings.

This submission is a very specific iteration of those works wherein I attempt to merge a pure `prefers-color-scheme: dark` media query driven “Dark Mode” as a 5th variant of the CSS.  That means no toggle button etc., but easily attainable with one line setting in the `_variables.scss` file and a whole lot of JS to drive that. *(I can contribute to building that a bit later.)*

This work, and the original works, would not have been possible without the advice of Thomas Steiner (@tomayac) and his [prefers-color-scheme: Hello darkness, my old friend](https://web.dev/prefers-color-scheme/) blog post.  Reading that (and his [color-scheme CSS property](https://web.dev/color-scheme/) post) and some of @mdo’s work inspired the original text.

It includes both the SCSS changes and the docs to go along with it.

### CODE REVIEW

**Comment by ffoodd** [comment]
This is really impressive!

I still think custom properties should be the preferred way to go, since it'd allow to leverage `-alt` mixins. This PR is really helpful to get a detailed view of what need to be handled, thanks a lot. :)

Need time to dig this!

**Comment by XhmikosR** [comment]
For what is worth, the example doesn't look good for me. Also, please do not commit any dist files @vinorodrigues.

**Comment by tifroz** [comment]
This is a life saver for us having to support dark mode on iOS. Hopefully it gets merged as some point!

**Comment by XhmikosR** [comment]
Please do not commit any dist files. Also, check the diff, you are making changes that shouldn't be there.

**Comment by vinorodrigues** [comment]
haven't intentionally committed a dist file since you first asked - the ones that are there are automatically put there by a github sync to upstream

**Comment by tyt2y3** [comment]
Thank you for the great work @vinorodrigues 
Mind sharing why are you closing this PR?
Are you drafting a new one or you decided to not merge into upstream, leaving bootstrap-dark-5 as is?

**Comment by vinorodrigues** [comment]
umm... long story... 16 years ago I wrote code professionally, but decided to give it up - the main reason was that developers have the very unproductive hubris of thinking their way is the only way.  Me I'm different - I seek out those who know more than me and that I can learn from.  So when I come across people like @mdo and @tomayac I try to learn as much as I can from them - because a) they share, and b) they're open to others views.
But, some others are arrogant, lazy, impatient and full of hubris - I was reminded why I had no wish consume my time with insignificance.  My aim was to teach ... bootstrap-dark does that for me already.

**Comment by tyt2y3** [comment]
I feel sorry for you @vinorodrigues 
Keep up the great work!
I found it very useful.
Thank you :)

**Comment by vinorodrigues** [comment]
sorry?  don't - since leaving software I've gotten 2 masters degrees in finance and business .. and I'm still learning.  I'm in a better place.

**Pull request closed without merging**
