### PR TITLE
Update redirects in shortcut dirs

### PR DESCRIPTION
**Pull request by julien-deramond**
### Description

This PR suggests to change some HTML redirections in `gh-pages` branch in order to avoid having redirections to v3 or v4. Maybe it'll help with SEO as well.

⚠️ I've only updated what already existed. IMO we should either have all shortcuts for each sections in the docs or nothing at all (and so remove `/examples`, `javascript`, etc. in this branch at the root level). Thoughts?

Deleted redirections because doesn't exist anymore:
* https://getbootstrap.com/browser-bugs/ (redirected to v4.5)
* https://getbootstrap.com/css/ (redirected to 3.4)
* https://getbootstrap.com/examples/jumbotron-narrow/ (redirected to 3.4)
* https://getbootstrap.com/examples/justified-nav/ (redirected to 3.4)
* https://getbootstrap.com/examples/navbar-fixed-top (redirected to 3.4)
* https://getbootstrap.com/examples/static-top (redirected to 3.4)
* https://getbootstrap.com/examples/navbar (redirected to 3.4)
* https://getbootstrap.com/examples/non-responsive (redirected to 3.4)
* https://getbootstrap.com/examples/offcanvas (redirected to 3.4)
* https://getbootstrap.com/examples/signin (redirected to 3.4)
* https://getbootstrap.com/examples/theme (redirected to 3.4)
* https://getbootstrap.com/examples/tooltip-viewport (redirected to 3.4)
* https://getbootstrap.com/javascript (redirected to 3.4)

Modified redirections to v5.3:
* https://getbootstrap.com/customize/ (redirected to 3.4)
* https://getbootstrap.com/examples/blog (redirected to 3.4)
* https://getbootstrap.com/examples/carousel (redirected to 3.4)
* https://getbootstrap.com/examples/cover (redirected to 3.4)
* https://getbootstrap.com/examples/dashboard (redirected to 3.4)
* https://getbootstrap.com/examples/grid (redirected to 3.4)
* https://getbootstrap.com/examples/jumbotron (redirected to 3.4)
* https://getbootstrap.com/examples/starter-template (redirected to 3.4)
* https://getbootstrap.com/examples/sticky-footer-navbar (redirected to 3.4)
* https://getbootstrap.com/examples/sticky-footer (redirected to 3.4)

### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] I have updated the documentation accordingly
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by XhmikosR** [comment]
These are still used and should not be modified.

**Comment by XhmikosR** [comment]
To clarify, these are for historical reasons mostly, used for the old docs, pre v4.0.

We should not touch them, because they are unrelated to the current state of things.

Also, generally, try to avoid touching anything in gh-pages without having the accompanied changes in the main branch. That is, if we want to add/change redirects for the current docs, we should have them in the main branch first.

**Comment by julien-deramond** [comment]
Understand the arguments even if having https://getbootstrap.com/examples/blog/ redirecting to 3.4 instead of 5.3 bothers me. If someone thinks it is useful to start something in the _main_ branch to add redirections, please let me know.

**Comment by XhmikosR** [comment]
We shouldn't touch such ancients redirects. We should try not to break anything out there :)

We can start making root redirects for some of our current pages, but it's an extra thing to keep in mind when updating the gh-pages branch in case these redirects are removed in the future, so we need to think about the approach.

**Comment by julien-deramond** [comment]
It's not that important right now no problem. But just FYI we did it in Boosted via https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1088. It is mainly extra work when you deploy the HTML files in the `gh-pages` because you have a lot of more dirs to handle containing `index.html`. Works well btw but pretty boring to deploy. That's the limit of static redirections with Hugo; at least what we succeeded to do.

**Comment by XhmikosR** [comment]
I don't mind the number of files; I mind that I have to remember to delete the folders manually, which is error prone.

That being said, I'm not against having more root redirects, assuming we need them and use them.

We can use Cloudflare too, but I'd rather keep most redirects here, unless we need some wildcard ones like we did with alpha domains bulk redirects.

**Comment by julien-deramond** [comment]
The big advantage was for us to have a "latest" URL and keep almost-always-valid URLs with:
- /docs redirecting to /docs/5.2/getting-started/introduction
- /docs/getting-started to /docs/5.2/getting-started/introduction
- /docs/getting-started/introduction to /docs/5.2/getting-started/introduction

Same thing for all URLs and "sub-URLs"

**Comment by XhmikosR** [comment]
That we can do, the current old redirects can stay. But again, it's too troublesome to update, so I'd like this to be handled by Hugo ideally. Otherwise, we need a maintainable way for this.

**Pull request closed without merging**
