### PR TITLE
Fix `.form-control-plaintext` for select and textarea

### PR DESCRIPTION
**Pull request by WinterSilence**
Hide select "arrow" (icon at right center) and textarea "resizer" (icon at right bottom).
Base on #35688

### CODE REVIEW

**Review by ffoodd — COMMENTED** [review]
There's a concern still around `select`s — which can't be `readonly`. Removing its `appearance` doesn't feel right.

I wonder if we shouldn't be more accurate when applying those styles, using `:read-only` for `input`s and `textarea`s, and applying `appearance: none` to `select:disabled`.

Any thoughts?

**Comment by WinterSilence** [comment]
@ffoodd 
> selects — which can't be readonly

checkbox/radio/range inputs too can't be readonly.

This class is only "sugar" to styling controls, it's not changing behavior.

**Comment by ffoodd** [comment]
It could change users' behaviour, since if they don't know the text is a form element they won't use it.

Regarding input types, that's another argument in favor of the `:read-only` pseudo-class since it would prevent the whole declaration from applying to inputs that can't be readonly.

Still thinking out loud, needs a bit more research IMHO.

**Comment by WinterSilence** [comment]
@ffoodd 
> since if they don't know the text is a form element they won't use it.

hm... I thought that `.form-control-plaintext` was created for this, or why we attached styles to this class instead `[readonly]` selector?

**Pull request closed without merging**
