### PR TITLE
 Use cached `noop` function

### PR DESCRIPTION
**Pull request by rohit2sharma95**
`noop` function returns a new function every time whenever it is called. So just use the `noop` function, not the value returned by it (So that the event handler can remove the same function that was attached before).

Ref: https://github.com/twbs/bootstrap/pull/33451#discussion_r601248762

### CODE REVIEW

**Comment by XhmikosR** [comment]
I recall noticing this in the past but forgot to make a separate PR for sure. :) That being said, shouldn't our tests have caught this? I mean `null` !== `noop()`. The extra args are OK, though.

**Comment by GeoSot** [comment]
@XhmikosR I suppose, you remember [this ](https://github.com/twbs/bootstrap/pull/32523#discussion_r556808303) 
Do we still need this tweak @patrickhlauke ?

**Comment by XhmikosR** [comment]
Yeah, that's another change :) But I still wonder why this wasn't caught :/

**Comment by rohit2sharma95** [comment]
> Do we still need this tweak @patrickhlauke?

Not sure about that but that should be considered in another PR IMO (If that is not needed) @GeoSot. :slightly_smiling_face: 
So this PR is complete and will help #33466 to proceed.

**Review by GeoSot — APPROVED** [review]

**Review by patrickhlauke — APPROVED** [review]

**Pull request merged**
