### PR TITLE
V4: Add :disabled for disabled fieldset

### PR DESCRIPTION
**Pull request by ysds**
This PR is #29740 for v4, targets the `v4-dev-xmr` branch.

Before (4.4.0): https://codepen.io/fellows3/pen/LYYwejp
After: https://codepen.io/fellows3/pen/pooMpWQ

### CODE REVIEW

**Comment by XhmikosR** [comment]
@ysds does this apply to master too or only v4?

**Comment by ysds** [comment]
Only v4!

**Comment by XhmikosR** [comment]
Hmm, then we need @MartijnCuppens and @mdo to review too.

**Review by MartijnCuppens — APPROVED** [review]

**Comment by MartijnCuppens** [comment]
If we're going to include this in 4.4.1, we'll need to update our blogpost a bit

**Comment by XhmikosR** [comment]
If you guys think it's safe, we can include it since have the patch ready.

**Comment by MartijnCuppens** [comment]
I think we're save with this one

**Comment by MartijnCuppens** [comment]
I've added this in https://github.com/twbs/blog/pull/123

**Pull request merged**
