### PR TITLE
Fix `.btn` padding for input/button[type="image"]

### PR DESCRIPTION
**Pull request by WinterSilence**
### Description

Remove padding for input/button containing image.

### Motivation & Context

Fix incorrect size of input/button: padding added to image size.

### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

https://codepen.io/WinterSilence/pen/jOxdyeO?editors=1100

### CODE REVIEW

**Comment by julien-deramond** [comment]
Thanks for creating this PR @WinterSilence.

Could you please add some more elements in the description to explain where the issue is seen?
There is an issue to with the [CSS job](https://github.com/twbs/bootstrap/actions/runs/3241641313/jobs/5313855971) to fix as well.

**Comment by WinterSilence** [comment]
@julien-deramond https://codepen.io/WinterSilence/pen/jOxdyeO?editors=1100

**Comment by WinterSilence** [comment]
@julien-deramond 
> There is an issue to with the CSS job to fix as well.

already done

**Comment by mdo** [comment]
I don't see many image inputs these days and this feels a bit like a random one-off style override right now. Going to pass on this for the time being, thanks though!

**Pull request closed without merging**
