### PR TITLE
Fixed proper navigation element selection on backward scrolling (from the bottom to the top)

### PR DESCRIPTION
**Pull request by maximandrews**
Found scrollspy issue.
It was selecting wrong navigation element. Wrong behavior were produced by unnecessary equal sign on line 99 (comparison of target offsets)

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 83371735fcc4ceba3c1b35d91bb3ba8c41365861
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/53855150

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
I've confirmed that the new unit test correctly fails when the included fix is reverted.

**Comment by maxstorm** [comment]
@cvrebert thanks for immediate response.

**Comment by cvrebert** [comment]
MSTM and LGTM. Thanks for including regression/unit tests!
CC: @XhmikosR @hnrch02 @juthilo for further review

**Comment by maxstorm** [comment]
You welcome.

**Pull request merged**
