### PR TITLE
Replace dependencies badge by peer dependencies badge

### LINKED ISSUE #23282: Add a peerDependencies badge in README.md

### PR DESCRIPTION
**Pull request by Johann-S**
Fixes #23282

/CC @XhmikosR and @mdo

### CODE REVIEW

**Comment by XhmikosR** [comment]
Perhaps just adding the new badge and not replacing the dependencies one so that it shows `none` would be better?

**Comment by Johann-S** [comment]
If you prefer like that, why not, personnaly I don't have any advice on what should be better here 🤔

**Comment by XhmikosR** [comment]
No preference either, just wanted to point this out. I guess @mdo will decide

**Review by XhmikosR — APPROVED** [review]

**Review by mdo — APPROVED** [review]
Given there are no dependencies now, I'm inclined to replace it.

**Pull request merged**
