### PR TITLE
v4: Navbar improvements

### PR DESCRIPTION
**Pull request by mdo**
WIP as I slog through #18467.

---
- New Sass variables for various navbar components.
- #17250: Improved (and highly flexible) responsive behaviors added.
- #17532: Dropdown example for navbars.
- #17539 , #18863, #18865: Navbar togglers don't respect color scheme.
- 083271ae48d0ce1ff5b869413449f5ecf777b6e9: Update collapsible navbar docs to demonstrate color scheme functionality of navbar toggler.
- #17990, #20392, #20749: Clear the floats within `.navbar-toggleable-*` to avoid broken animation on close.
- #18049: Restore `.navbar-text` and add some docs examples.
- #18855: Docs for examples of using images in navbar brand component.
- #18599: Clarify usage of `.active` in navbar navs.
- #20543: Improve color contrast of navbar nav links.
- #20856: Navbar brand and image options (solved thanks to utilities).

Still to do:
- [ ] #18053: Container adding extra padding
- [ ] #18115: Revisit light/dark nomenclature
- [x] #18557: Make sure docs navbar is updated
- [x] #18751: Input group sizing in navbar
- [ ] #18875: Flexbox navbar
- [ ] Migration docs

### CODE REVIEW

**Comment by os1r1s110** [comment]
Is there anything preventing this from being merged in dev branch? I might not really understand completely how it all works yet... sorry.

**Comment by rafalp** [comment]
@os1r1s110 as first words in PR's say, this is **work in progress** PR that aims to solve certain issues within BS4's navbars that are tracked here:

https://github.com/twbs/bootstrap/issues/18467

It'll likelly get merged when it's considered done by the author... unless @mdo decides to split the work in few PR's and merges what he has done so far.

**Comment by os1r1s110** [comment]
@rafalp I did effectively read that this was WIP, but you know sometimes in big open source projects, some open PR get lost in the sea of PRs and other issues so I just wanted to know what was up with this one as there had been no update since a couple of weeks, that's it....  :|

**Comment by rafalp** [comment]
@os1r1s110 It seems that @mdo has reduced his commitment to the project lately:

https://twitter.com/mdo/status/745652402687090688
https://twitter.com/mdo/status/745667785758388224
https://twitter.com/mdo/status/745734499586056192

It may suck if you are waiting for Mark to wrap up his PR's, but that's how it is with open source. Give it time, I'm wholly expecting @mdo to come from nowhere one day and push boatload of work into BS4 ;)

**Comment by os1r1s110** [comment]
Ahah yeah,  I couldn't say it sucks to wait for him to close up the navbar PRs because I can't complete them myself so I can't complain. 

I'm pretty new to frontend development so I'm trying to build my own version of navbar and just cut it from the bootstrap alpha 2 build to avoid compatibility issues.

**Comment by sixteenstudio** [comment]
@mdo - do dropdowns need adding to navbars - or are they abstracted from the navbar docs now?

**Comment by mdo** [comment]
Added #20543 to this PR to address color contrast a bit.

**Comment by mdo** [comment]
Pushed a few major changes to this the last few days. The toggler has been updated, toggleable classes are now generated from the breakpoint Sass map, and docs updated. Overall I think this is in a solid enough place to build on just a tad more in Alpha 6. Definitely want folks to try using it more.

**Comment by mdo** [comment]
Updated opening comment with clearer list of issues this all fixes, and the remaining todos.

**Comment by mdo** [comment]
Punting on some of this for Alpha 6. Trying to wrangle all this ahead of dropping Alpha 5 tomorrow, so apologies for the potentially half baked ship here. 😬

**Comment by mdo** [comment]
Going to track remaining work for Alpha 6 in #20937.

**Pull request merged**
