### PR TITLE
variables: adds empty `$utilities`

### PR DESCRIPTION
**Pull request by zalog**
This PR expose the possibility of adding new utility classes.

If it's ok, please give me some feedback of what comment description we should leave there.

@MartijnCuppens what do you think?

### CODE REVIEW

**Comment by XhmikosR** [comment]
The branch is not based on the latest master branch @zalog :)

**Comment by zalog** [comment]
Wow! My bad :)
Now it's ok.

**Comment by MartijnCuppens** [comment]
Not sure about this, I think it's clearer to leave it in the separate file.

**Comment by zalog** [comment]
Yeah, but I think exposing this on our most visible scss file, and leave there a comment, can open developers eyes. What do you think?

**Comment by MartijnCuppens** [comment]
Hmm, not sure. It's weird to only have an empty variable. We have a documentation page dedicated to the Utility API (https://twbs-bootstrap.netlify.com/docs/4.3/utilities/api/) and I think this covers it well enough.

**Comment by zalog** [comment]
Ok. Please think about this if we will need some sort of specific order in variables regarding this.

Tnks for your time.

**Comment by MartijnCuppens** [comment]
We still have https://github.com/twbs/bootstrap/pull/29451 open, feel free to drop ideas there

**Pull request closed without merging**
