### PR TITLE
Mixins form-control-focus and button-variant output invalid box-shadow value with shadows enabled

### PR DESCRIPTION
**Pull request by pat270**
When shadows are enabled and `$btn-box-shadow`, `$btn-active-box-shadow`, `$input-box-shadow`, or `$input-focus-box-shadow` have the value `none` these mixins output invalid values for the `box-shadow` property (e.g., `box-shadow: none, 0 0 0 0.2rem rgba(0, 123, 255, 0.25)`).

### CODE REVIEW

**Review by andresgalante — APPROVED** [review]
@pat270 good catch! The specs state:

> The property accepts either the none value, which indicates no shadows, or a comma-separated list of shadows, ordered front to back.
https://drafts.csswg.org/css-backgrounds-3/#the-box-shadow

**Comment by mdo** [comment]
I merged #25070 and updated your branch to resolve a conflict—can you re-review?

**Comment by pat270** [comment]
This LGTM, Thanks!

**Review by mdo — APPROVED** [review]

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
@pat270: please fix the conflicts and squash your commits.

**Comment by pat270** [comment]
@XhmikosR I ended up using rebase instead of merge, sorry about that!

**Review by XhmikosR — CHANGES_REQUESTED** [review]
@pat270: please rebase and remove the dist commit.

**Comment by mdo** [comment]
Cherry-picked ffcbdb5a1 into `v4-dev` to sidestep the rebase and what not :).

**Pull request closed without merging**
