### PR TITLE
Changed the "Triggers" JS Code on Alerts

### PR DESCRIPTION
**Pull request by mrsrmn**
When I tried the given code, it didn't work. I changed it into this and it worked. I wanted to fix it in case if it was the same for everyone

### CODE REVIEW

**Comment by XhmikosR** [comment]
I don't see how this works and the previous doesn't. An alert must have the `.alert` class present, doesn't it?

**Comment by MakufonSkifto** [comment]
> I don't see how this works and the previous doesn't. An alert must have the `.alert` class present, doesn't it?

Absolutely same, but the given code didn't work and this one did. I imported everything possible (jquery, css, js) but the given one didn't work.

**Comment by GeoSot** [comment]
@MakufonSkifto maybe you missed the `forEach` doesn't return the Alert instances
Try this:
```js
var alertList =
[...document.querySelectorAll('.alert')].map(alert =>  new bootstrap.Alert(alert))
alertList[0].close()
```

**Comment by XhmikosR** [comment]
@GeoSot so the question is if we should clarify this on our side or not?

**Comment by MakufonSkifto** [comment]
> ```js
> var alertList =
> [...document.querySelectorAll('.alert')].map(alert =>  new bootstrap.Alert(alert))
> alertList[0].close()
> ```

This one showed up but it closed itself without me even seeing it.

**Comment by GeoSot** [comment]
> This one showed up but it closed itself without me even seeing it.

try to remove `alertList[0].close()`





> @GeoSot so the question is if we should clarify this on our side or not?

I am not sure we need. Alert (till now) works by itself and is initialized only once, by the `dismiss` btn click, just to trigger the events and to remove itself from everywhere.

**Comment by MakufonSkifto** [comment]
> > This one showed up but it closed itself without me even seeing it.
> 
> try to remove `alertList[0].close()`
> 
> > @GeoSot so the question is if we should clarify this on our side or not?
> 
> I am not sure we need. Alert (till now) works by itself and is initialized only once, by the `dismiss` btn click, just to trigger the events and to remove itself from everywhere.

Thanks, it worked when i removed it. But I think you guys should update the code on the docs as that one doesn't work, for me at least. (Normal alerts doesn't work either)

**Comment by GeoSot** [comment]
#33402 has the proper documentation changes. So I close this.

@MakufonSkifto  if you have any proposals over the doc change you can comment there

**Pull request closed without merging**
