### PR TITLE
Empty badge

### PR DESCRIPTION
**Pull request by WinterSilence**
Added variable to change visible of empty badge.

### CODE REVIEW

**Comment by ffoodd** [comment]
Why not — but what's the point of showing an empty badge?

If you need this eg. because you add an icon as a pseudo-element, then it's likely you need a visually hidden content in your badge for accessibility (thus making the badge non-empty). Am I missing something?

**Comment by WinterSilence** [comment]
@ffoodd
1. hiding/showing badge change width of parent element. If you update badge content by JS it causes "jerking"
2. you can use empty badge as marker/pin for menu/list

**Comment by ffoodd** [comment]
Thanks for explaining! Both use cases feel weird to me: removing content from a badge could remove the badge entirely, and utilities would be a better approach for list markers.

Apart from that, I don't see any issue in allowing this as it does not change our default build. @mdo any thought?

**Comment by WinterSilence** [comment]
@ffoodd 
> removing content from a badge could remove the badge entirely

if `$badge-display-empty: inline` badge will displaying if content is empty

> utilities would be a better approach for list markers

why utilities would be a better? and then why not remove badge and use utilities instead?

**Comment by XhmikosR** [comment]
This offers no value... we already have the display utilities people should leverage.

**Pull request closed without merging**
