### PR TITLE
More concise improvements for `add()` and `subtract()`

### PR DESCRIPTION
**Pull request by ffoodd**
Better fix for #33953, improves #34047

@oliwerAR Back to this, made [a quick SassMeister to play with](https://www.sassmeister.com/gist/8c06fb2ca03fae00da39c83e986521f5).

From my understanding, brackets are required on `subtract()` second argument only when it contains an addition, am I right? Thinking so, I also checked that second argument contains a `+` sign to only output brackets when necessary.

### CODE REVIEW

**Comment by oliwerAR** [comment]
@ffoodd I'm afraid that's not right. The second argument of substract should be put in brackets always when it's a complex expression (not type-of number), whatever sign it contains.

Simple match:
a - b = ?
a = 100

b = 10 + 1 = 11
100 - (10 + 1) = 100 - 10 - 1 = 89

b = 10 - 1 = 9
100 - (10 - 1) = 100 - 10 + 1 = 91

The results of your last two tests:
```scss
    font-size: subtract(1vw, $add); =  font-size: calc(1vw - (1rem + 1em));
    font-size: subtract(1vw, $subtract); =  font-size: calc(1vw - 1rem - 1em);
```
are mathematically equal, though obviously the **should not** be.

**Comment by ffoodd** [comment]
Just updated the PR [and made another SassMeister](https://www.sassmeister.com/gist/fad02650787cd3de954cd209ccbadfbe). Should be better :)

**Comment by oliwerAR** [comment]
@ffoodd This version seams to be working fine (mathematically correct).

**Comment by XhmikosR** [comment]
Just to confirm @ffoodd did you check the dist file changes? Does everything look good now?

**Comment by ffoodd** [comment]
@XhmikosR Yes, we only had 5 occurrences of unneeded parenthesis (`(x + (a + b))` for all of them). AFAIK it's safe for our core, and should be for other cases as demonstrated in Sassmeister.

**Review by mdo — APPROVED** [review]

**Pull request merged**
