### PR TITLE
Removed vertical-align from form-select class

### PR DESCRIPTION
**Pull request by mikayelgr**
vertical-align: middle Property is ignored due to the display. With 'display: block', vertical-align should not be used.

### CODE REVIEW

**Comment by alecpl** [comment]
You should not touch dist files.

**Comment by MichaelGrigoryan25** [comment]
I have just changed a one line. Everything else has stayed as it was.

**Comment by alecpl** [comment]
Did you see your change? It is not even possible to see what have you changed.

Dist files are generated from other files, so you have to find the proper file with your line and do a change there.

**Comment by MichaelGrigoryan25** [comment]
> 
> 
> Did you see your change? It is not even possible to see what have you changed.
> 
> Dist files are generated from other files, so you have to find the proper file with your line and do a change there.

Yeah I see the commit now. Lemme see how can I fix this

**Comment by MichaelGrigoryan25** [comment]
I'll just create a new PR

**Pull request closed without merging**
