### PR TITLE
Rename .tag to .badge to avoid conflicting with WordPress

### LINKED ISSUE #20542: Bootstrap 4.0.0-alpha3 .tag class breaks WordPress
When using the new .tag class in WordPress, it is conflicting with the post tag class names applied to a lot of WordPress elements like the body class, hentry etc.

It just won't work on WordPress.

Any work around on this?

Thanks!

### PR DESCRIPTION
**Pull request by mdo**
Fixes #20542.

This renames the `.tag` component to `.badge` to avoid conflicts with some core WordPress styling. It's a bit of a flip flop, but that's okay. It's an easy fix on our end to resolve this larger issue with a huge community. I've updated the file names, docs pages, examples, mixins, Sass variables, and more. Should be good to go.

### CODE REVIEW

**Comment by browner12** [comment]
omg, you've got to be kidding me

**Comment by guylepage3** [comment]
@mdo, `.badge` sounds good to me. i don't think there are any conflicts with anything else.

**Comment by j0an** [comment]
:'(

**Comment by guylepage3** [comment]
@j0an yes.

**Comment by mdo** [comment]
Hosted docs will get updated when we do a release. Until then, they reflect the latest release. Docs in the branch are up to date though.

It's worth noting this is how all our releases go; docs updates come with the general release.

**Comment by guylepage3** [comment]
thanks for letting us know the doc release process @mdo.

**Pull request merged**
