### PR TITLE
Fixed Navbar documentation

### LINKED ISSUE #30880: .nav-item is not required on .nav-link inside .navbar-nav
When list-based approach is not used for the navbar, class `.nav-item` is not required on `.nav-link` inside `.navbar-nav`. Link for the [docs](https://getbootstrap.com/docs/4.5/components/navbar/#nav).

See [this comment](https://github.com/twbs/bootstrap/issues/28423#issuecomment-630286599) in #28423

### PR DESCRIPTION
**Pull request by psjishnu**
Fix #30880: .nav-item is not required on .nav-link inside .navbar-nav

### CODE REVIEW

**Comment by psjishnu** [comment]
@XhmikosR Requesting review .

**Comment by XhmikosR** [comment]
You don't need to ping us, someone will have a look when they have time, thanks.

**Comment by mdo** [comment]
@psjishnu Can you clean up the commits here? There are several unrelated ones in the history.

**Comment by XhmikosR** [comment]
@mdo it doesn't matter if you squash and merge :)

**Comment by psjishnu** [comment]
Please ping me if there is need of any changes

**Comment by XhmikosR** [comment]
I haven't checked if there any other cases @mdo, but if it looks good, I"ll backport it to v4-dev too.

**Comment by rohit2sharma95** [comment]
It has been covered in #30973 though.

**Comment by mdo** [comment]
Closing for #30973.

**Pull request closed without merging**
