### PR TITLE
Set max-width to 100%

### LINKED ISSUE #27114: Grid col-auto max width - overflow
Hi,

AFAIK, since commits 8a2d845a4f7fe1611da79c6d4349d9bcd1117832 and 48d17bc8b86af468230cba5420f3b56856b161c5, the `max-width` on `col#{$infix}-auto` is now reset to override inherited `max-width` from lower grid tiers.

My concern is about the new value of `max-width`. With `max-width: none` , a `col-auto`  column may overflow from its `row` container / parent. Is it an expected behavior? Why not use `max-width: 100%` to override it and keep the column inside the row?

Example `col-auto` overflow: https://codepen.io/anon/pen/oPgXgM
Exemple `col-auto` with `max-width: 100%`: https://codepen.io/anon/pen/VGYLmq

Kind regards,
Florian

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Fixes #27114

### CODE REVIEW

**Review by andresgalante — APPROVED** [review]
thanks a lot @MartijnCuppens 😄 

@mdo since this is related to the grid, can you take another look, please?

**Comment by MartijnCuppens** [comment]
You're welcome 😉

**Comment by mdo** [comment]
Should be fine? Will need to look at some of the docs examples.

**Comment by rjoly** [comment]
Thanks @florianlacreuse for the issue, @MartijnCuppens for the PR and Bootstrap team for including it in v4.2 ;-)

**Pull request merged**
