### PR TITLE
examples: Update font utility classes to new v5 versions

### PR DESCRIPTION
**Pull request by alanorth**
The `.font-style-*` and `.font-weight-*` utility classes were renamed to `.fst-*` and `.fw-*` in Bootstrap v5 but a few references in the examples didn't get updated.

### CODE REVIEW

**Review by ffoodd — APPROVED** [review]
LGTM, we may need to check every renamed utilities at some point.

**Comment by XhmikosR** [comment]
> LGTM, we may need to check every renamed utilities at some point.

Could have a quick look soon please? There shouldn't be too many left, hopefully :)

**Comment by alanorth** [comment]
@XhmikosR I found a few more `font-weight-light` and `font-weight-bold` in the RTL docs that should be migrated to `fw-light` etc. Should I add them to this PR?

**Comment by XhmikosR** [comment]
Yes, please!

**Comment by alanorth** [comment]
@XhmikosR I've updated the few other references I found in the documentation. Cheers.

**Pull request merged**
