### PR TITLE
FIX memory leak because dettached element on inline function

### PR DESCRIPTION
**Pull request by orlandoaleman**

### CODE REVIEW

**Comment by cvrebert** [comment]
@orlandoaleman Ping.

**Comment by cvrebert** [comment]
@orlandoaleman Ping. Please get the PhantomJS tests passing.

**Comment by hnrch02** [comment]
And maybe also share some more insight into the alleged memory leak.

**Comment by PetersonLian** [comment]
It seems that bootstrap follows semicolon-less style.But why this style?Is there any links to the discussions somewhere?I want to know what coding style of bootstrap.Is there a document somewhere?

**Comment by kkirsche** [comment]
@PetersonLian I would probably reference #3057 for a discussion related to semicolons. At the end of the day though semicolons are largely optional because of automatic semicolon insertion.

Personally, I prefer having them in my own code, but it's Jacob's style and in my opinion more power to them since even if I don't prefer that style, it's still open and I could always fork it and change that type of thing if I felt strongly about it.

Code guidelines though can be found here:
https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#code-guidelines

**Comment by cvrebert** [comment]
> It seems that bootstrap follows semicolon-less style.

Yes.

> But why this style?

Because @fat personally likes it and he's Bootstrap's head JS maintainer.

> I want to know what coding style of bootstrap. Is there a document somewhere?

* https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#js
* [JSCS](http://jscs.info/) configuration: https://github.com/twbs/bootstrap/blob/master/js/.jscsrc
* [JSHint](http://jshint.com/about/) configuration: https://github.com/twbs/bootstrap/blob/master/js/.jshintrc

**Comment by orlandoaleman** [comment]
@cvrebert pong!! I'm going to review this (and I look back in the memory  :p ). I guess the tooltip retains its context around and it causes that the GC doesn't go fine. 

PS: We are developing a single page applicacion (a web desktop), therefore our users are always in the same page and to maintain the memory low is a priority.

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 12533b8b58efc9ef654fb01432c116e810c44a52
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/52547368

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 716a92e3585d7eebe8a3ce43b84c367f904a81da
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/52548345

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
I think this has been addressed by 7429fc7ff965147fe218b3b4e124d922b08118f2. You will need to destroy (rather than merely hide) a tooltip/popover when you're permanently done with it, of course.

**Pull request closed without merging**
