### PR TITLE
Work around Travis failures.

### LINKED ISSUE #24921: Karma tests fail
@Johann-S: opening this to track the problem. Is it reported upstream?

### PR DESCRIPTION
**Pull request by XhmikosR**
Note that we should revert this when the issue is fixed.

Fixes #24921

### CODE REVIEW

**Review by Johann-S — APPROVED** [review]
Thanks @XhmikosR for taking care of that 👍

**Comment by XhmikosR** [comment]
No, don't merge it :/ They are reverting their image.

**Comment by Johann-S** [comment]
too late 😆 Please notice me and I'll remove that commit

**Comment by XhmikosR** [comment]
No worries, I made #24926; just approve that but don't merge.

**Pull request merged**
