### PR TITLE
V5 form validations

### LINKED ISSUE #28414: Validation feedback/tooltips lack association with their form control
the feedback and tooltip containers need to be programmatically associated with their respective form controls, e.g. using `aria-describedby="..."`, e.g.

```html
<label for="validationTooltip03">City</label>
<input type="text" class="form-control" id="validationTooltip03" ... required>
<div class="invalid-tooltip">
   Please provide a valid city.
</div>
```

to

```html
<label for="validationTooltip03">City</label>
<input type="text" class="form-control" id="validationTooltip03" aria-descriebedby="validationTooltip03-tip" ... required>
<div class="invalid-tooltip" id="validationTooltip03-tip">
   Please provide a valid city.
</div>
```

### PR DESCRIPTION
**Pull request by ysds**
Drop feedback messages by sibling selector for V5.

There is no way to solve the #25110 and #29439 maintaining the current specification. If you are using a modern JavaScript framework, this removal of sibling selectors is not a problem, because feedback messages are almost always controlled by `if` directives (e.g. `ng-if`). Control styling with the `.is-valid/.is-invalid` has the same feature as v4.

Also this close #28414 and #30438.

image

Preview: https://deploy-preview-30170--twbs-bootstrap.netlify.app/docs/5.0/forms/validation/

PR for v4 is #30180

### CODE REVIEW

**Comment by mdo** [comment]
So with this change, there is no built-in and functional form validation in Bootstrap? Because everything would need to be controlled by another JS library or framework?

**Comment by ysds** [comment]
Does not deny the creation of new built-in JavaScript plugins. We can consider it after the alpha release.

At the least, the current  control by sibling selectors should be abolished.

**Comment by XhmikosR** [comment]
Just keep in mind there's one snippet using inline JS to handle validation. If it's supposed just to be an example we should make it so, because currently it applies to the code.

**Comment by ysds** [comment]
I rebased into the master and updated the first custom JS example.

**Comment by mdo** [comment]
Any chance this could be rebased @ysds?

**Comment by XhmikosR** [comment]
I don't want to hurry this @mdo. The tooltip example doesn't look right, the feeback is always shown.

**Comment by ysds** [comment]
Sorry for being away for a while.

> The tooltip example doesn't look right, the feeback is always shown.

It's intentional that the feedback tooltip examples are always visible, but what do you think it should be?

**Comment by XhmikosR** [comment]
>It's intentional that the feedback tooltip examples are always visible, but what do you think it should be?

I thought it was a mistake since previously they didn't show up nor in v4. If it's intentional then all good :)

**Comment by ysds** [comment]
👍  As commented on https://github.com/twbs/bootstrap/pull/30170#issuecomment-586534806
, additional JS is required to toggle the display of feedback messages. I think the static sample is enough for now.

**Comment by mdo** [comment]
@ysds Can you confirm something here before I attempt to resolve conflicts and merge this? Are we removing all feedback elements from the examples under the `## Server side` heading? Your earlier commit does that, and I may have screwed that up in my later commits.

**Comment by mdo** [comment]
Hoping this can be replaced by #31666.

**Comment by XhmikosR** [comment]
@mdo is this still valid? #31666 was closed in favor of #31953

**Comment by mdo** [comment]
Closing as out of date—miss you @ysds! <3

**Pull request closed without merging**
