### PR TITLE
Move close icon to components in docs

### PR DESCRIPTION
**Pull request by MartijnCuppens**
The close icon is a component, not a utility.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Should we backport this?

**Comment by MartijnCuppens** [comment]
Nah, it's just the place where it's documented, not that important but if we're going to use the https://github.com/twbs/bootstrap/pull/28445 for utilities, it would be better if we move this.

**Comment by XhmikosR** [comment]
@mdo: your thoughts?

**Comment by ysds** [comment]
> The close icon is a component

My only concern is:

https://github.com/twbs/bootstrap/blob/06635be7bd4e1d469a25e48a0a36c4427f7d7fe9/scss/_close.scss#L2

If remove this, the `close` button is going to be a truly component.

**Comment by MartijnCuppens** [comment]
`.close` is only used by `.modal` (positioned with flexbox) and `.alert` (positioned with `position: absolute`) so we can easily drop `float: right` (which I just did)

**Comment by ysds** [comment]
LGTM👍,  but would be perfect by changing its name to "Close button" IMO 😄

**Review by ysds — APPROVED** [review]

**Comment by MartijnCuppens** [comment]
It could also be a link in another context, so let's leave it for now.

**Pull request merged**
