### PR TITLE
fix border issue for nested card inside accordions

### LINKED ISSUE #26556: Border card-group doesn't work in a accordion collapse
I have no idea if it is my problem but when I use a card-group in a accordion collapse it doesn't show borders properly. 
Version: bootstrap 4.1.1
Browsers: IE, Edge, Chrome, Opera, Firefox
Code: https://codepen.io/anon/pen/qYvLdN

### LINKED ISSUE #27510: Nested Card inside Accordion's `body` missing bottom border
When nesting a card inside an accordion's card body, the nested card inside the card body of an accordion is missing the bottom border.

- Operating system and version: Windows 7 SP1 64 bit 
- Browser and version: Chome 69.0.3497.100
- Reduced test case: https://codepen.io/JJCoolBean/pen/KGraWv

### PR DESCRIPTION
**Pull request by ovpv**
After analysing the code in scss/_card.scss, in line 281, the styles added for .card class inside .accordian class is targeting all the cards inside instead of its immediate children elements with the class .card.

Code now:
```
.accordion {
  .card {
    ...
  }
}
```
Fix:

```
.accordion {
  > .card {
    ...
  }
}
```

Fixes #27510, fixes #26556.

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
Hi @ovpv,

Can you provide a demo to make clear what this fixes?

**Comment by ovpv** [comment]
**The issue demo** 
https://codepen.io/JJCoolBean/pen/KGraWv

**The fix demo**
https://codepen.io/ovpv/pen/REoZdw

@MartijnCuppens , In the above fix demo, you can see that the the `border-bottom: 0` property is only applied to the accordian cards and not the child cards inside the accordian card-body.

**Comment by MartijnCuppens** [comment]
Hi @ovpv,

Thanks for the PR! If you open a PR which closes an issue, you can add `Closes #issuenumber` so that we can easily check what the PR is about. This also automatically closes the issue if the PR gets merged.

Apart from that, this looks good! Thanks for the solution.

**Review by MartijnCuppens — APPROVED** [review]
LGTM! 👍

**Comment by ovpv** [comment]
> Hi @ovpv,
> 
> Thanks for the PR! If you open a PR which closes an issue, you can add `Closes #issuenumber` so that we can easily check what the PR is about. This also automatically closes the issue if the PR gets merged.
> 
> Apart from that, this looks good! Thanks for the solution.

Thanks for the approval @MartijnCuppens . This is my first contribution on github! 😄

 I will make sure that I add the necessary details for a PR in my future contributions 👍

**Comment by ovpv** [comment]
@MartijnCuppens @XhmikosR @mdo 

I see changes made into v4-dev.
Should I push the latest updates from v4-dev to this branch?

**Comment by svenevs** [comment]
Thanks for fixing this!  If others are in a situation like me where they need to rely on official releases (rather than building from source with this commit in there), before 4.3 rolls out this is working for me:

```js
$('.accordion').on('show.bs.collapse', function() {
  /* modify this vvvvv selector for your code */
  $('div[data-fixcollapse="true"]').css({
    "border-bottom": "1px solid",
    "border-radius": "4px"
  });
});
```

What I'm doing is relying on the fact that the cards whose borders are deleted I also explicitly mark with a custom `data-fixcollapse="true"` attribute on the `<div class="card" ...>`.  I didn't know of an easier / better way to do it (I'm a really weak frontend programmer...).  My situation may be specialized, I have a set of nested accordions that sometimes have on the innermost `card-body` elements some `card` divs that do **not** have a `collapse` class.  Those ones were the ones that were having the bottom border deleted.  If I applied the css hack to all of them, then the `div`s that *do* have `collapse` class get messed up (those ones are working just fine).

Anyway, just wanted to share a potential solution for people before 4.3 releases in hopes that it may be useful :slightly_smiling_face:

**Comment by osnofa** [comment]
It didn't solve everything. Please try this:
```
<div class="container">
        <br />
        <div class="accordion">
          <div class="card">
            <div class="card-header" data-toggle="collapse" id="cardHead" href="#collapseAccordCard" aria-expanded="true">
              <a class="card-title">Accordian Title</a>
            </div>
            <div id="collapseAccordCard" class="collapse show" aria-labelledby="headingAccordCard">
              <div class="card-body">
                <div class="row">
                  <div class="col-md-4">
                    <div class="card">
                      <div class="card-body">Lorem Ipsum 1</div>
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="card">
                  <div class="card-body">Lorem Ipsum 2</div>
                              </div>
                          </div>
                          <div class="col-md-4">
                              <div class="card">
                                  <div class="card-body">Lorem Ipsum 3</div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div> 
  </div> 
  </div> 
```

**Comment by XhmikosR** [comment]
@osnofa you should probably make a new issue.

**Comment by osnofa** [comment]
> @osnofa you should probably make a new issue.

Done. https://github.com/twbs/bootstrap/issues/29426

**Pull request merged**
