### PR TITLE
Simpler docs footer

### PR DESCRIPTION
**Pull request by mdo**
Fewer links, new background, and no Twitter `widgets.js` which is outrageously large for two buttons.
screen shot 2015-07-31 at 3 05 30 pm

### CODE REVIEW

**Comment by cvrebert** [comment]
@mdo Could we please bring back the version number?

**Comment by mdo** [comment]
If we really need it, sure. I don't mind having it, but it didn't seem super critical.

**Comment by patrickhlauke** [comment]
:heart:

**Comment by adammacias** [comment]
better! :+1:

**Pull request merged**
