### PR TITLE
 Accessibility and headings hierarchy for the CSS page.

### PR DESCRIPTION
**Pull request by StevenBlack**
Just a few adjustments here.

Below are the before-and-afters for all the changes in this PR.

bs-css

bs-css2

### CODE REVIEW

**Comment by kkirsche** [comment]
Thanks for your hard work on this/these. I personally like the changes you've made :+1:

**Comment by StevenBlack** [comment]
aw... thanks @kkirsche!

BTW, how can I learn more about what's cooking in v. 4?

**Comment by kkirsche** [comment]
@StevenBlack honestly I don't know. It's kind of a secret between the admins and collabs. :smiley: Sorry! Wish I knew as I would love to try to contribute to it and help out with it

**Comment by XhmikosR** [comment]
@cvrebert @patrickhlauke: LGTM, any objections before merging this?

**Comment by cvrebert** [comment]
None from me.

**Comment by XhmikosR** [comment]
Actually, @StevenBlack has made quite a few PR on this matter so we should merge all of them. As far as I can tell, they all look good.

**Comment by patrickhlauke** [comment]
:shipit:

**Pull request closed without merging**
