### PR TITLE
Add unit test of aria-expanded to dropdown suite

### PR DESCRIPTION
**Pull request by kkirsche**
[Redo of #15876 which broke when trying to rebase against master which updated QUnit] Add unit test of aria-expanded to dropdown suite

cc: @cvrebert

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: c5968060f50343e4a8264608f4d2d3a8999306c4
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/52034338

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 2bbf70fc663ab7044aea9e31dd91db5fcd82b4be
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/52036240

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by kkirsche** [comment]
@cvrebert 

Build Failed due to:

```shell
Running "jade:customizerVars" (jade) task
>> Error: Cannot find module 'acorn'
Warning: Jade failed to compile "docs/_jade/customizer-variables.jade". Use --force to continue.
```

**Comment by juthilo** [comment]
@kkirsche Reran the tests, all good now. :)

**Comment by kkirsche** [comment]
Thanks @juthilo I appreciate it.

**Comment by kkirsche** [comment]
Added test case for when the dropdown is hidden again so that the dropdown has complete coverage regarding the `aria-expanded` attribute.

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: cc8740293e72f1b766de79a29f852ad2fff03ea0
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/52051380

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Pull request closed without merging**
