### PR TITLE
browsers-devices.md: escape what we read.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Review by mdo — CHANGES_REQUESTED** [review]
Why are we reverting the GA exclusion here? We just approved and merged that change.

**Comment by XhmikosR** [comment]
Because it introduces an JS error locally, and TBH I find this change useless myself.

**Comment by mdo** [comment]
> Because it introduces a JS error locally, and TBH I find this change useless myself.

I don't see an error on my local dev for `master`. And if you find it useless, open an issue or PR to discuss that again—that change is unrelated to this PR.

**Comment by XhmikosR** [comment]
It does introduce a JS error. Try clicking on the themes navbar link for example.

>ReferenceError: ga is not defined[Learn More]

**Comment by mdo** [comment]
Split the commits myself—see cross-referenced PRs at #28488 and #28489.

**Pull request closed without merging**
