### PR TITLE
docs: README.md -> add repo size badge

### PR DESCRIPTION
**Pull request by prayogaea**
### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [x] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

- <https://deploy-preview-{your_pr_number}--twbs-bootstrap.netlify.app/>

### CODE REVIEW

**Comment by XhmikosR** [comment]
Thanks for the PR. I'm not sure this is important info for consumers, though.

@mdo: what's your take on this?

**Comment by prayogaea** [comment]
Consumers can find out the size of the file id in the repository
and consumers can take into account computer specifications when they want to contribute to the repository

**Comment by XhmikosR** [comment]
Consumers of the package should not care about the repository size...

Contributors might care, but it's not something we can improve anyway.

So, this badge doesn't give any real value IMHO.

**Comment by mdo** [comment]
I'm inclined to leave it off too. We ship tons of dist files that bloats the size anyway.

**Pull request closed without merging**
