### PR TITLE
Proposal: Rename navbar-inverse to navbar-dark

### PR DESCRIPTION
**Pull request by Varunram**
Intended as a fix for #22745. I'm new here, so please do comment your views :)

### CODE REVIEW

**Comment by Johann-S** [comment]
It seems you have some errors @Varunram see : https://travis-ci.org/twbs/bootstrap/jobs/241576992#L227

**Comment by Varunram** [comment]
Ah, expected it. I thought I'd start off with the class definition first and based on feedback, go about editing the others. Will edit this shortly. Thanks for your time!

**Comment by Varunram** [comment]
Done! If the changes are accepted, then we can modify the docs :)

**Comment by akhyarrh** [comment]
What if user set darker color as base color ? Using `navbar-dark` but output bright color makes no sense

**Comment by Varunram** [comment]
Well, the same logic applies to `navbar-light` too

**Comment by akhyarrh** [comment]
As the linked issue stated, the problem is with classes name. `navbar-light` & `navbar-dark` or `navbar-inverse` is okay. But what if user use different base & second color

**Comment by mdo** [comment]
Closing per https://github.com/twbs/bootstrap/issues/22745#issuecomment-308639412.

**Comment by dinatih** [comment]
For people (like me) who thinks that it is not integrated, because of the closed status, it is integrated since 26 June. https://github.com/twbs/bootstrap/commit/36e482ed2728eec37188b5ec486283334bb3034f

also related issue : https://github.com/twbs/bootstrap/issues/22745

**Pull request closed without merging**
