### PR TITLE
Prevent generation of invalid negative border-radius values

### PR DESCRIPTION
**Pull request by ghost**
When @border-radius-base equals 0 compiled css is invalid:

``` css
.popover-title {
  padding: 8px 14px;
  margin: 0;
  font-size: 14px;
  background-color: #f7f7f7;
  border-bottom: 1px solid #ebebeb;
  border-radius: -1px -1px 0 0;
}
```

``` css
.panel-heading {
  padding: 10px 15px;
  border-bottom: 1px solid transparent;
  border-top-right-radius: -1;
  border-top-left-radius: -1;
}
```

In border-radius negative values are now allowed. See https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius#Values_2

Use http://lesscss.org/functions/#math-functions-max to avoid this

### CODE REVIEW

**Comment by kkirsche** [comment]
I just wanted to clarify: did you mean that they are NOW valid or did you mean to say that they are NOT valid? Currently yours states the first.

**Comment by kkirsche** [comment]
@MaxKorz pull request submitted with the fix. Thanks!

**Comment by kkirsche** [comment]
Sorry about the above non-sense, I misread where I was and thought I was in "Issues" not "PRs".

**Comment by mdo** [comment]
We've previously turned this down and I don't think we'll do it now either.

**Comment by MaxKorz** [comment]
Could you please explain me why?

**Comment by kkirsche** [comment]
I can't answer the why but I can share where this was originally passed on: #12140.

**Comment by cvrebert** [comment]
I guess `$enable-rounded` kinda takes care of this in v4.

**Comment by mclub198456** [comment]
Get

**Comment by mdo** [comment]
@cvrebert Yeah, I think so. Punting.

**Comment by mdo** [comment]
Thanks though!

**Pull request closed without merging**
