### PR TITLE
Add chips

### PR DESCRIPTION
**Pull request by njavid**

### CODE REVIEW

**Comment by XhmikosR** [comment]
Thanks for the contribution but please

1. before making a PR, make sure `npm test` passes locally
2. this needs docs

**Comment by patrickhlauke** [comment]
Also, it would be nice if you first filed an issue explaining what it is you'd like to add, and give an actual example/use case.

**Comment by XhmikosR** [comment]
I guess this is in response to #31033.

**Comment by njavid** [comment]
yes, I'm trying to solve this issue #31033.

**Comment by mdo** [comment]
This is an incomplete approach, lacking docs and examples, as well as being the wrong way to write CSS in Bootstrap. We use rem units, not pixels. We also don't style by element selector generally speaking, so that'd be an issue. Alongside that, I think we'd need to consider how these show up and how folks would interact with them. As it stands now, this isn't a compelling component to be added IMO. Thanks though!

**Pull request closed without merging**
