### PR TITLE
added the labels on every input field and removed the unused style tag

### PR DESCRIPTION
**Pull request by alkavats1**
### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [ ] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [ ] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

#### Live previews

- <https://deploy-preview-{your_pr_number}--twbs-bootstrap.netlify.app/>

### CODE REVIEW

**Comment by alkavats1** [comment]
Hi @julien-deramond  could you please review and merge this PR? It is pending since last week
Thanks :)

**Comment by julien-deramond** [comment]
Hi @alkavats1 
Appreciate the contribution to the project, but please be patient, we're all working on Bootstrap in our spare time.

**Review by mdo — CHANGES_REQUESTED** [review]
I'm inclined to leave these forms as they are—this is a basic visual check for us and requires no semantic value. But if someone on the team wanted to see these cleaned up, I'd do it properly and use a `for` attribute without wrapping the input with the label. Removing the style element makes sense though.

**Comment by alkavats1** [comment]
> I'm inclined to leave these forms as they are—this is a basic visual check for us and requires no semantic value. But if someone on the team wanted to see these cleaned up, I'd do it properly and use a `for` attribute without wrapping the input with the label. Removing the style element makes sense though.

Hi, @mdo Do you need any changes from my side for this PR?
Thanks

**Comment by mdo** [comment]
Nope. we're goin to leave as-is for now. Thanks though!

**Pull request closed without merging**
