### PR TITLE
Remove explicit use of aria-hidden for offcanvas when closed

### LINKED ISSUE #35577: Offcanvas navbar expand remaining aria-hidden
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Following PR #34273.

An offcanvas navbar with `.navbar-expand-${breakpoint}` can lead to a remaining `aria-hidden="true"`, if the offcanvas is closed and the navbar is expanded again. This edge case happen when resizing the window on desktop or rotating an ipad (for instance).

### Reduced test cases

https://codepen.io/florianlacreuse/pen/wvreVxN

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.3

### PR DESCRIPTION
**Pull request by patrickhlauke**
due to the `.offcanvas` styles already containing `visibility:hidden`, no need to add `aria-hidden` nor to explicitly set the `style=""` attribute when the offcanvas gets closed

Closes https://github.com/twbs/bootstrap/issues/35577

### CODE REVIEW

**Comment by XhmikosR** [comment]
Can you remove the dist files please?

**Review by ffoodd — CHANGES_REQUESTED** [review]
Looks like you commited dist files. We can take care of it if needed 👌

Edit: Oh, just saw previous comment!

**Comment by patrickhlauke** [comment]
urgh, stupid dist files...

**Review by ffoodd — APPROVED** [review]
LGTM 👌

**Comment by GeoSot** [comment]
@patrickhlauke it will need something more (maybe one more class like `.transitioning`) in order to achieve better transition during close. 



_Ps: I can help if you like 😃_

**Comment by patrickhlauke** [comment]
> @patrickhlauke it will need something more (maybe one more class like `.transitioning`) in order to achieve better transition during close.

Aha, that explains it. I was wondering why all of a sudden this was setting/removing actual style attributes separately rather than just relying on classes. Clearly I'm a bit rusty (and hadn't fully checked the impact visually). Yeah if you don't mind giving an assist, that'd be awesome.

**Comment by patrickhlauke** [comment]
Let me set this to draft in the meantime so it doesn't get accidentally merged prematurely

**Comment by GeoSot** [comment]
Please check the functionality & changes, and if we agree on these, I will 'tweak' the test

**Comment by patrickhlauke** [comment]
@GeoSot just tested, seems to work really well. If you don't mind tweaking the tests, that'd be great

**Comment by GeoSot** [comment]
@ffoodd  I would review it but I have also put my hands in here, so your review would help us :100:

**Review by ffoodd — APPROVED** [review]
I better aligned the CSS with our current code style. This is working fine so :shipit:

**Comment by GeoSot** [comment]
> I better aligned the CSS with our current code style. This is working fine so


@ffoodd  forgot the `&` :wink:

**Comment by ffoodd** [comment]
Oh my, thanks :D

**Pull request merged**
