### PR TITLE
Added a dark theme for the pagination.

### PR DESCRIPTION
**Pull request by aapljack**
Originating from issue [#29635](https://github.com/twbs/bootstrap/pull/29892)

Added CSS to support a dark version of the pagination.
Updated the documentation to support this change.

Demo: https://deploy-preview-29893--twbs-bootstrap.netlify.com/docs/4.3/components/pagination/#dark-color-scheme

### CODE REVIEW

**Comment by aapljack** [comment]
I know another user has submitted a PR similar to this one. I had already started this work when they also started working on the issue. Since my solution was slightly different, I went ahead and submitted what I had done.

**Review by jawadulhassan — APPROVED** [review]

**Comment by XhmikosR** [comment]
I think we need to revisit how we are going to proceed with this across all components. I think the nest approach might be to use CSS variables, but IE11 doesn't support them.

Otherwise if we end up doing this for all components, the CSS size will increase a lot more.

If anyone has any better solutions let us know.

**Comment by MartijnCuppens** [comment]
> I think we need to revisit how we are going to proceed with this across all components. I think the nest approach might be to use CSS variables, but IE11 doesn't support them.
>
> Otherwise if we end up doing this for all components, the CSS size will increase a lot more.

I agree, closing this.

**Comment by NicolasPereira** [comment]
Is this PR in the new bootstrap versions?

I looked in the documentation and didn't find it, I had to create my own css rule to meet my demand

**Pull request closed without merging**
