### PR TITLE
Fix for browsers not supporting sticky position

### PR DESCRIPTION
**Pull request by WinterSilence**

### CODE REVIEW

**Review by ffoodd — COMMENTED** [review]
There's no need for `@support` here : setting `position: fixed` then `sticky` would work the same, the latter only used in supporting browsers.

I'm not sure we need this however. Any thought, @twbs/css-review? 

We mention the potentially partial support in our docs, and I think the v5 browser support is complete, when comparing [Can I Use for `sticky` position](https://caniuse.com/css-sticky), isn't it?

**Comment by WinterSilence** [comment]
@ffoodd [it's not work only in IE](https://caniuse.com/css-featurequeries) and supported better than `position: sticky`

**Comment by XhmikosR** [comment]
We do not support IE, though.

**Comment by WinterSilence** [comment]
@XhmikosR and what? it's NOT work only in IE

**Comment by XhmikosR** [comment]
We don't support IE, thus we don't care if it works or not there. All of our supported browsers support this feature so this PR is redundant.

**Comment by WinterSilence** [comment]
@XhmikosR but in BS sources I'm see "bla-bla-bla sticky not supported by all browsers"

**Comment by ffoodd** [comment]
Yep, we may drop this sentence since it's a v4 leftover.

**Comment by XhmikosR** [comment]
Could be because the comment has now become outdated. Either way, we don't blindly apply changes like that.

**Pull request closed without merging**
