### PR TITLE
Update initial release announcement dead link

### PR DESCRIPTION
**Pull request by molly**
Removed the [dead link](https://dev.twitter.com/blog/bootstrap-twitter) to what was presumably once a release announcement for Bootstrap.

### CODE REVIEW

**Comment by patrickhlauke** [comment]
LGTM. @mdo ?

**Comment by molly** [comment]
Hold that thought—looks like they just changed the URL. [Archive.org](https://web.archive.org/web/20130307212454/https://dev.twitter.com/blog/bootstrap-twitter) confirms it's the same announcement as originally intended.

**Comment by cvrebert** [comment]
We should squash this before merging it.

**Comment by patrickhlauke** [comment]
Molly, could you squash the two commits into a single one (interactive rebase)? If not, we can take care of it at our end...

**Comment by cvrebert** [comment]
Thanks!

**Pull request merged**
