### PR TITLE
Prep for v4.2.0 release

### LINKED ISSUE #27862: List v4.2 in versions page and versions dropdown

### PR DESCRIPTION
**Pull request by mdo**
- Move 4.1 docs to 4.2
- Update versions everywhere to 4.1.3 with release script
- Manually bump the shorthand version in package.json
- Add 4.2 to the versions docs page

Closes #27862

### CODE REVIEW

**Review by XhmikosR — APPROVED** [review]
LGTM, verified there are no dist changes.

**Comment by XhmikosR** [comment]
OK I pushed a couple more patches. Should be OK, if not let me know. Otherwise just squash when merging.

**Comment by MartijnCuppens** [comment]
I've added the `4.1` version to the list of previous releases: https://github.com/twbs/bootstrap/pull/27867/commits/e1ea8c5c0d50bec6de98ac56da2ee689d0ddc257

**Review by coliff — COMMENTED** [review]
Should this also have:
For v3.4.x: https://getbootstrap.com/docs/3.4/
?

**Comment by mdo** [comment]
@coliff We added it before this PR, so it's not showing in the diff.

https://github.com/twbs/bootstrap/blob/12c4d3c248b49f1730c75fcf8fbcb4a97274ccf6/site/_includes/docs-navbar.html#L34-L44

**Pull request merged**
