### PR TITLE
Add `focusable="false"` to placeholder SVGs

### PR DESCRIPTION
**Pull request by ffoodd**
A simple fix to prevent IE11 and Edge prior to v38 from considering SVGs focusable.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Does it apply on v4-dev?

**Comment by ffoodd** [comment]
Oh indeed, I think it does — as well as my other PRs.
Let me check this, and I'll open PRs for v4 too once I know which are accepted in v5 :)

**Comment by XhmikosR** [comment]
Just keep in mind that we usually try to cherry pick patches in v4-dev from master. In this specific case cherry picking will fail, but better wait until a PR for a thing against master is addressed first.

**Comment by XhmikosR** [comment]
Also we don't backport everything, mostly fixes.

**Comment by ffoodd** [comment]
@XhmikosR Since docs markup didn't change that much, most of my current PRs could apply to v4 as well — and indeed since it switched from Jekyll to Hugo, `cherry-pick` will fail.

Just let me know if you prefer another PRs by myself or if one of you guys take care of it, if you choose to backport it :)

**Comment by XhmikosR** [comment]
Yeah, I'll ping you if needed :) Let's just wait until the PRs against master are sorted and we have a clear view of what needs to be backported.

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
I'd still like to hear @patrickhlauke's opinion about this before proceeding with merging the PR.

**Review by patrickhlauke — APPROVED** [review]
It's a non-controversial fix. fully approve 👍

**Comment by XhmikosR** [comment]
So, it seems we already have `focusable=false` in the v4-dev branch

**Pull request merged**
