### PR TITLE
Fix tooltip memory leak: destroy doesn't destroy $tip & $arrow references

### PR DESCRIPTION
**Pull request by nsteenbeek**
Memory leak detected by Chrome tools.

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 5758d19c44b4bc8aa5dc1b70e420dc31e0e42431
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/47903917

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by XhmikosR** [comment]
I wonder if we could add a test for this?

**Comment by ohana54** [comment]
I also encountered a memory leak which seems to originate from this line:
https://github.com/twbs/bootstrap/blob/master/js/tooltip.js#L185

Will this PR solve it? I'm not an expert on jQuery memory management.

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: dc216cec200d8fe3f0b140f3edab32592d14434e
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/53769232

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: ec64f72eb91d8fb8ff8fb7f759fe2406034c1dcd
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/53769677

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: bf14891e3a883bb418e6e466026079a917e2cde3
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/53770340

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: b769911a98e1fbef9a06388ead3b935824a2e848
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/53773163

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by nsteenbeek** [comment]
@ohana54 I did fixes to solve your memory leaks too.

**Comment by ohana54** [comment]
@nsteenbeek awesome thanks!

**Comment by XhmikosR** [comment]
@nsteenbeek: please squash the patches into one.

**Comment by nsteenbeek** [comment]
@XhmikosR: tried the squash (my first time), but don't know how to check whether it succeeded. Still see 7 commits at the top.

**Comment by XhmikosR** [comment]
Then it didn't succeed. :P

```
git fetch upstream master
git rebase -i upstream/master
```

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 89a350597cd587e563f553b31c32fde9c8f2546d
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/53805341

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by nsteenbeek** [comment]
I did a reset of the feature branch, then the pull-request was closed automatically :(.
So created a new clean one: https://github.com/nsteenbeek/bootstrap/pull/1.

**Comment by XhmikosR** [comment]
Err, that PR is not in this repo...

**Comment by nsteenbeek** [comment]
This is the right one: Fix tooltip memory leak: destroy doesn't destroy $tip & $arrow #16039.

**Pull request closed without merging**
