### PR TITLE
Fix accessibility of examples buttons

### PR DESCRIPTION
**Pull request by MewenLeHo**
### Description

Fix accessibility of 'Try it on StackBlitz' and 'Copy to clipboard' buttons.

### Motivation & Context

Svgs inside 'Try it on StackBlitz' and 'Copy to clipboard' buttons are pure decoration so they must be ignored by any assistive technology.

See [https://www.w3.org/TR/WCAG21/#non-text-content](https://www.w3.org/TR/WCAG21/#non-text-content) for more details.

### Type of changes

- [X] New feature (non-breaking change which adds functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

- <https://deploy-preview-37498--twbs-bootstrap.netlify.app/>

### CODE REVIEW

**Comment by MewenLeHo** [comment]
I am also currently wondering if adding `focusable="false"` to the `<svg>` elements could be useful since it may cause an accessibility issue in Internet Explorer?

**Comment by patrickhlauke** [comment]
`title` technically provides an accessible *description*, rather than an accessible *name*.

maybe a slicker way around it is to add `aria-label` to the `<button>` - then you can save yourself the `aria-hidden="true"` on the internal svg as well, since the `aria-label` on the parent will completely replace/override whatever's inside the button anyway?

``` html
<button ... aria-label="Try" title="Try it on StackBlitz">
  <svg class="bi"><use xlink:href="#lightning-charge-fill"/></svg>
</button>
```

as for `focusable="false"`, not sure if we still need to cater to IE since it's now been officially deprecated by Microsoft, and that was the only browser exhibiting this odd behaviour.

**Review by patrickhlauke — CHANGES_REQUESTED** [review]
See comment about adding the `aria-label` to the `<button>` and removing the `aria-hidden` as well

**Comment by patrickhlauke** [comment]
also, note that

> Svgs inside 'Try it on StackBlitz' and 'Copy to clipboard' buttons are pure decoration so they must be ignored by any assistive technology.

is perhaps not completely accurate. They're not pure decoration, they represent the content/label of the button... but that's probably splitting hairs

**Comment by MewenLeHo** [comment]
> ```
> <button ... aria-label="Try" title="Try it on StackBlitz">
>   <svg class="bi"><use xlink:href="#lightning-charge-fill"/></svg>
> </button>
> ```

Ok with your version and for your opinion about `focusable="false"` since IE is not listed anymore in the list of supported browsers on [.browserslistrc file](https://github.com/twbs/bootstrap/blob/v5.2.2/.browserslistrc)

However I think it will be better to keep the same content in the two attributes:

> ```
> <button ... aria-label="Try it on StackBlitz" title="Try it on StackBlitz">
>   <svg class="bi"><use xlink:href="#lightning-charge-fill"/></svg>
> </button>
> ```

**Comment by patrickhlauke** [comment]
depending on browser/assistive technology used, both the accessible name and description may be announced, resulting in an overly verbose announcement (though, at least with Chrome/NVDA and Chrome/Jaws, it seems that if both are exactly the same, it's only announced once). Will test some more later just to check...

**Comment by patrickhlauke** [comment]
> `title` technically provides an accessible _description_, rather than an accessible _name_.

I've actually just tested it, and it seems that consistently browsers use/expose `title` as an accessible *name* if it's the only thing present, rather than using it as a *description*

Long story short, after more testing (also in Firefox/Win and Safari/macOS), ignore my suggestion. This will be fine as is ;)

**Review by patrickhlauke — APPROVED** [review]

**Comment by patrickhlauke** [comment]
also, i'd note that those buttons were accessible even before this, but they did lead to an unnecessarily verbose announcement (along the lines of "image Try it, button, Try it on StackBlitz"). so this PR is more of a nice tweak ("Try it on StackBlitz, button")

**Pull request merged**
