### PR TITLE
Fix Modal documentation about _handleUpdate method + move to public scope

### PR DESCRIPTION
**Pull request by Johann-S**
Update the way to call ``_handleUpdate`` method

IMO this method should move to the public scope

Close : #21868

### CODE REVIEW

**Comment by vanduynslagerp** [comment]
The function `_handleUpdate ` is called [automatically on event `resize`](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/modal.js#L299).

Doing something that make the sidebar to appear will necessarily change the window size and therefore trigger the `resize` event and call the function automatically.

I think it's not meant to be public and the mention of the function should be removed from the doc instead.

Unless there is a scenario in which a sidebar can appear without triggering the resize event ?

**Comment by Johann-S** [comment]
Yes good catch I didn't see that 👍 

I'll update my PR to remove the mention of ``_handleUpdate`` thank you

**Comment by Johann-S** [comment]
~~Yes good catch I didn't see that 👍
I'll update my PR to remove the mention of _handleUpdate thank you~~

It seems @vanduynslagerp sidebar can appear without triggering resize event for example if we do this : 
``$('#firefoxModal').find('.modal-content').css('height', '900px');``

That's what the documentation said : 
> If the height of a modal changes while it is open, you should call `$('#myModal').data('bs.modal').handleUpdate()` to readjust the modal's position in case a scrollbar appears.

**Comment by vanduynslagerp** [comment]
Oh yeah right! Also if the content of the modal is updated it can change the height.
I don't know why I didn't think about that...

So yeah you're right the function should be public then.

**Pull request merged**
