### PR TITLE
Update NuGet docs to specify only .NET Framework projects are supported

### PR DESCRIPTION
**Pull request by supergibbs**
The newer nuget ContentFiles don't work as expected by users and it's causing confusion. Newer .NET Core/5 projects shouldn't use nuget.

### CODE REVIEW

**Review by XhmikosR — APPROVED** [review]

**Comment by supergibbs** [comment]
I removed query parameter. I think it redirects to the latest so we'll let MS handle that.

**Comment by XhmikosR** [comment]
It's a permanent redirect, so TBH I see no point in removing it. BTW, the missing trailing slash saves another redirect :P

**Comment by tbolon** [comment]
Fun changes and discussions :D. It always annoys me to redirect to a specific version, since the link will always refer to this specific .net version, and could cause strange reactions when you use a most recent one ("does this still apply?").

But do as you want, I was just afraid my comment was unseen ^^

**Comment by supergibbs** [comment]
Nice catch @XhmikosR! It says perm redirect but I suspect when v6 is out of beta, it'll default to that.

**Pull request merged**
