### PR TITLE
Added display heading responsive class

### PR DESCRIPTION
**Pull request by ItaloBC**
This allows to user display headings that will automatically shrink it's size (if the user opts to) using `.display-responsive`. This will only work on small screens (xs, sm).

### CODE REVIEW

**Comment by andresgalante** [comment]
Hi @ItaloBC Thanks a lot for your PR. 

This idea is interesting but really opinionated. By adding the `display-responsive` class a title would automatically change itself on smaller viewports. When dealing with responsive states Bootstrap usually adds responsive namespaces like `-md` `-xs` etc so we let the author decide what he wants in any given breakpoint. Maybe they don't want to make it smaller on small devices but larger. 

Having said that, the display headers does not support different sizes at different breakpoints at this moment and to be honest I would argue that they are unnecessary.

**Review by andresgalante — COMMENTED** [review]
Hi @ItaloBC Thanks a lot for your PR.

This idea is interesting but really opinionated. By adding the display-responsive class a title would automatically change itself on smaller viewports. When dealing with responsive states Bootstrap usually adds responsive namespaces like -md -xs etc so we let the author decide what he wants in any given breakpoint. Maybe they don't want to make it smaller on small devices but larger.

Having said that, the display headers does not support different sizes at different breakpoints at this moment and to be honest I would argue that they are unnecessary.

**Comment by ItaloBC** [comment]
Yeah, I missed the point @andresgalante. At least, the implementation should be responsive first, but from what I perceive `.display` sizing it's not a mobile first experience.

While it could be implemented the other way around, then it could collision with the `h1-h6` headings. And, you could replicate the `display` by just adding `font-size-light` as a class.

Maybe a helper class to make a heading responsive from the small screens to large would be better instead of a static `display` heading. That way the `h1-h2` headings would work as always on small screens, bu adding `display-sm/md/lg` class would make it larger on that viewport and higher.

If out shoot me out I'll stop.

**Comment by andresgalante** [comment]
Hi @ItaloBC as I mentioned before, I don't think I'd like to add responsive headers, but if @mdo likes the idea, I think the solution would be to add responsive prefixes to each display heading.

**Pull request closed without merging**
