### PR TITLE
Allow offcanvas to be initialized in open state

### LINKED ISSUE #33372: v5 Offcanvas: Not visible on page load with show class
Operating system and version: Windows 10
Browser and version: Firefox 86.0 and Chome 89.0.4389.82

I'm trying out the new offcanvas component, which is great, but when I have `show` as part of the initial classes, the menu doesn't open on page load. It may be something I'm doing wrong, but I think I've followed the setup correctly for the current Bootstrap from GitHub.

```html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="css/bootstrap.css">
        <title>Offcanvas test</title>
    </head>
    <body>
        <div id="app-menu" class="offcanvas offcanvas-start show">
            <h2>Offcanvas</h2>
        </div>
        <button class="btn" type="button" data-bs-toggle="offcanvas" data-bs-target="#app-menu">
            Open menu
        </button>
        <script src="js/bootstrap.bundle.js"></script>
    </body>
</html>
```

Expected behaviour: On load, the offcanvas is opened, and the document obscured by the overlay.

Actual behaviour: No offcanvas shown. Clicking the button the first time does nothing (it toggles the `show` class off), then the second time it shows the offcanvas and the document is obscured.

Moving the script tag to the top of the document or into the `head` seems to make no difference.

### PR DESCRIPTION
**Pull request by GeoSot**
According to [this](https://github.com/twbs/bootstrap/issues/33372) offcanvas should be able to initialized on shown state if it has the `show` class on its markup . 
I am not sure of this. Any Opinions?
(tests will be added after decision is made)

[Preview](https://deploy-preview-33382--twbs-bootstrap.netlify.app/docs/5.0/components/offcanvas/)
Closes #33372

### CODE REVIEW

**Comment by iainhallam** [comment]
May be worth noting the [current documentation](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.0/components/offcanvas.md#via-data-attributes) implies that this is possible on line 182:

> If you’d like it to default open, add the additional class `show`.

**Review by mdo — APPROVED** [review]
Ayy this looks good to me. I've updated the first example in the docs for this to put it to use. Now makes it much more dynamic inside the example.

**Comment by XhmikosR** [comment]
This needs some more work on the JS side for sure and the example blocks page scrolling now until the example is closed :P

**Comment by mdo** [comment]
How we looking here? :)

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
