### PR TITLE
examples: fix `.btn-block` instances

### PR DESCRIPTION
**Pull request by XhmikosR**
Regression of #31995

### CODE REVIEW

**Review by ffoodd — APPROVED** [review]
This fixes missed cases, however re-reading the initial PR, using `.w-100` as a simple replacement for `.btn-block` isn't mentionned in our docs nor in our migration guide.

Shouldn't it be?

**Comment by XhmikosR** [comment]
I guess it could, not sure why @mdo didn't mention it, but he might have just missed it :)

**Comment by XhmikosR** [comment]
BTW not sure if `w-100` should be added at the end or not. Let me know if you have a preference.

**Review by mdo — APPROVED** [review]
Hadn't mentioned `.w-100` because most of the situations I was thinking about were for multiple stacked buttons. Feel free to add something to the Migration docs for our last release.

**Comment by XhmikosR** [comment]
I'm unsure how to reword the current text, so please have a look @mdo in another PR or push it here :)

**Review by mdo — APPROVED** [review]

**Pull request merged**
