### PR TITLE
Simplify input groups by dropping `.input-group-prepend` and `.input-group-append`

### LINKED ISSUE #30104: The style is not strict enough   .input-group-prepend .btn+.btn
The text is translated using Google.

Description
There is no problem on the DEMO on getbootstrap.com, but it will affect the performance in the following usage. The performance is a pixel shift.

Where it was originally used
The case of an input-group double button.
Input-group of [Button addons](https://getbootstrap.com/docs/4.4/components/input-group/#button-addons) 3 and 4 examples.
An example of an input-group's [Segmented buttons](https://getbootstrap.com/docs/4.4/components/input-group/#segmented-buttons).

Show results
[Demo address](https://codepen.io/zhangchenglin/pen/Powvbqb)

Pictures are better than text

{9DA28FDD-7499-461D-AF29-F388A9F06012}_20200116120837

{21D6794D-4364-4BA8-81EF-3EC58A66FF85}_20200129134638

{E9964581-814E-4CD3-A2A6-762CAE5D9D43}_20200129135031

For network reasons, you cannot clone the complete warehouse and submit PR at will, so you can only give screenshots of the code that you think should be repaired.

<a class="d-block" target="_blank" href="https://github.com/twbs/bootstrap/blob/v4.4.1/scss/_input-group.scss#L83-L88">Bootstrap 4.4.1 /scss/_input-group.scss#L83-L88</a>
<a class="d-block" target="_blank" href="https://github.com/twbs/bootstrap/blob/master/scss/forms/_input-group.scss#L82-L87"> Bootstrap master /scss/forms/_input-group.scss#L83-L87</a>

{06DE0634-7B78-4B21-9ED6-9C70D1312AA1}_20200129180747

{7EF9A9EC-E081-4FC2-85F1-87D4B3CF1BC3}_20200129180845

PS:In this way, you cannot use the keyboard operation of dropdowns (the final confirmation has not been successful)

.

### PR DESCRIPTION
**Pull request by MartijnCuppens**
`_input-groups.scss` has become quite hard to maintain, mainly because of the nesting we have with `.input-group-prepend` and `.input-group-append`. It's actually pretty simple to remove this. This will also make our html look a lot simpler.

Before:
```html
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">@</span>
  </div>
  <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
</div>
```

After:
```html
<div class="input-group mb-3">
  <span class="input-group-text" id="basic-addon1">@</span>
  <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
</div>
```

Demo: https://deploy-preview-29885--twbs-bootstrap.netlify.com/docs/4.3/forms/input-group/

Also closes https://github.com/twbs/bootstrap/pull/30111, closes #30104 
See https://codepen.io/MartijnCuppens/pen/mdyZBoR

For the dropdown buttons some things needed to be changed in order to make this work because the `show` class was added to the (random) parent of the toggle button instead to the button itself. The way the dropdown menu is found is now changed.

While I was working on this, I discovered a bug which is explained in https://github.com/twbs/bootstrap/pull/30117. Please review this first because that PR also includes a test.

I've also added an additional example to test multiple dropdowns in a input group: https://deploy-preview-29885--twbs-bootstrap.netlify.com/docs/4.3/forms/input-group/#buttons-with-dropdowns 

To Do:

- [x] Change the way the dropdown menu is detected
- [x] Change the way active states are set to toggle buttons
- [x] Adjust existing tests

### CODE REVIEW

**Comment by alecpl** [comment]
Very nice. Thanks you.

**Comment by XhmikosR** [comment]
Definitely like this, reduces the final CSS size too 🎉

**Review by XhmikosR — APPROVED** [review]

**Review by ysds — COMMENTED** [review]
Some use cases are no longer supported, are they intentional?

v4 supported use cases: https://github.com/twbs/bootstrap/pull/25352

**Comment by MartijnCuppens** [comment]
@ysds, what use cases exactly? 

(I know the _input group ↔️ validation message_ thing is still an issue, but this is not something new?)

**Comment by MartijnCuppens** [comment]
Ping @ysds

**Comment by XhmikosR** [comment]
Just so we are safe, did you check the examples too @MartijnCuppens?

**Comment by MartijnCuppens** [comment]
@XhmikosR, no appearances of `input-group-prepend` or `input-group-append` left. Only the `btn-group`s are used in the examples.

**Comment by ysds** [comment]
@MartijnCuppens Please see dropdown menu's corner in [this netlify](https://deploy-preview-29885--twbs-bootstrap.netlify.com/docs/4.3/forms/input-group/#buttons-with-dropdowns):

image

That should be rounded.

And cases that have multiple dropdown menus:

- v4: https://codepen.io/fellows3/pen/oNgroro
- This PR: https://codepen.io/fellows3/pen/OJPeOer

image

**Comment by MartijnCuppens** [comment]
Just fixed that.

**Comment by ysds** [comment]
The 2nd issue (multiple active states with multiple dropdowns) still seems to occur.

**Comment by ysds** [comment]
The CSS side is LGTM. @XhmikosR Could you see the JS side?

**Comment by MartijnCuppens** [comment]
Please review https://github.com/twbs/bootstrap/pull/30117/files first, it includes a fix and test for the `prev()` function.

**Comment by mdo** [comment]
Punted to Alpha 2 for now, but would happily see it back to first alpha if the JS errors get fixed.

**Comment by MartijnCuppens** [comment]
This fails in IE because of the matches polyfill:
```
IE 11.0.0 (Windows 10.0.0) Dropdown data-api should fire hide and hidden event without a clickEvent if event type is not click FAILED
	Object doesn't support property or method 'matches' thrown
IE 11.0.0 (Windows 10.0.0) Dropdown data-api should fire hide and hidden event without a clickEvent if event type is not click FAILED
	Object doesn't support property or method 'matches' thrown
................................................
IE 11.0.0 (Windows 10.0.0) Dropdown data-api should ignore keyboard events for <input>s and <textarea>s within dropdown-menu, except for escape key FAILED
	Object doesn't support property or method 'matches' thrown
	Error: Expected true to equal false.
	    at <Jasmine>
	   at Anonymous function (js/tests/unit/js/tests/unit/dropdown.spec.js:1495:9 <- js/tests/unit/dropdown.spec.js:15745:11)
IE 11.0.0 (Windows 10.0.0) Dropdown data-api should ignore keyboard events for <input>s and <textarea>s within dropdown-menu, except for escape key FAILED
	Object doesn't support property or method 'matches' thrown
	Error: Expected true to equal false.
	    at <Jasmine>
	   at Anonymous function (js/tests/unit/js/tests/unit/dropdown.spec.js:1495:9 <- js/tests/unit/dropdown.spec.js:15745:11)
```

**Comment by XhmikosR** [comment]
@MartijnCuppens you can use our helper, or wait until #30377 lands :)

**Comment by MartijnCuppens** [comment]
The helper is used I guess. I don't really understand the reason why `next()` is failing and `prev()` is not

**Comment by Johann-S** [comment]
the JS looks good to me, nice work @MartijnCuppens 👍

**Review by Johann-S — APPROVED** [review]

**Pull request merged**
