### PR TITLE
Fix anchors, fix naming consistency

### PR DESCRIPTION
**Pull request by mattez**
I found non working anchors and some naming in consistency. I hope I fixed well. Have a nice day.

### CODE REVIEW

**Comment by mattez** [comment]
Have I done something wrong?
Probably yes. "All checks have failed" it is not good sign, isn't it.
But I don't know what is wrong. Please, if you know, give me a note.
Thank you very much.

**Comment by kkirsche** [comment]
@mattez this is due to a build issue that we are working to address in #17050

**Comment by mattez** [comment]
@kkirsche oh so it's not my foult, = im happy THANK YOU for your response. Good luck with that issue.

**Comment by hnrch02** [comment]
Thanks!

**Comment by mattez** [comment]
With pleasure. I love Bootstrap. A version 4 looks luxuriously smart. I help with what I can. Thank you!

**Pull request merged**
