### PR TITLE
Affix plugin w/ items with offsetTop = 0

### LINKED ISSUE #16449: v3.3.4: Affix plugin has problems handling items with offsetTop = 0
# Background

I have custom navbar in my app. Depending on configuration this navbar is either located at top of page, or its below user set header.

# Issue

If there's element taking height above affixed one, everything works, however if affix element is at top of page, click events will switch it between affix/affix-top.

This is because if affix isn't affixed and its `offsetTop` is 0, following line in getState will change it to 'top':

    if (offsetTop != null && scrollTop <= offsetTop) return 'top'

 Next click event will trigger getState again, this time changing state back off:

    if (offsetTop != null && this.affixed == 'top') return scrollTop < offsetTop ? 'top' : false

# Temporary fix

I have managed to fix this issue, by changing offsetTop to 1 if navbar has no element obove it (and making existing logic work).

# Proposed fix

because offsetTop == 0 is edge case, `getState` may check for it via running following check before all other checks:

    if (offsetTop === 0) return scrollTop === 0 ? 'top' : false

### PR DESCRIPTION
**Pull request by kkirsche**
Not sure how to test this change specifically so if anyone has any suggestions on testing this let me know and I'll add it. I wasn't sure if `offsetTop = 0;` could be achieved via `margin-top: 0; padding-top: 0;` or if it had to be done differently. I can add a test though if someone can provide some guidance on method of testing it.

Fixes #16449

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 14828281907e9dbc87176c292ef0f91332f1e23c
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/62543589

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by kkirsche** [comment]
Wanted to follow up on this and see if it was missing anything

**Comment by kkirsche** [comment]
Wanted to follow up on this and see if it was missing anything

**Comment by kkirsche** [comment]
Wanted to follow up on this and see if it was missing anything.

**Comment by kkirsche** [comment]
Wanted to follow up on this and see if it was missing anything.

**Comment by kkirsche** [comment]
Wanted to follow up on this and see if it was missing anything.

**Comment by kkirsche** [comment]
Wanted to follow up on this and see if it was missing anything or determine what this pull request is waiting on so I can ensure I follow up at appropriate intervals.

**Comment by mdo** [comment]
No need for the comments @kkirsche, we'll get to it when we can :grin:. I know it's shitty to hear nothing, but we're largely focused on v4 and swing back to this stuff when we can. And that's within the already narrow window of time we can put into things. Hold tight!

<3

**Comment by kkirsche** [comment]
@mdo Noted! Sorry about that :smiley: I'll hold off on the follow ups. I don't mind not hearing anything, I just wanna be clear on what the expectation from the core team so that I can follow what you all prefer.

If there is anything else I can do to help you guys out just let me know :smile:, I'm always looking for more ways to get involved.

**Comment by mdo** [comment]
Punting as a won't fix—v4 includes a new positioning library for our affix, tooltips, and popovers.

**Pull request closed without merging**
