### PR TITLE
Add .mailmap: reauthorize @zdroid commits

### PR DESCRIPTION
**Pull request by zlatanvasovic**
Refs #29685.

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
I'm not a fan of this, how are we going to determine what email addresses can be linked? We have over 1100 contributors, are we going to allow them all to add addresses to this list?

CC @XhmikosR

**Comment by zdroid** [comment]
Judging from the previous discussion: by request, and no (answers to your questions). mailmap is supposed to link only the written emails, not the others.

**Comment by XhmikosR** [comment]
>I'm not a fan of this, how are we going to determine what email addresses can be linked? We have over 1100 contributors, are we going to allow them all to add addresses to this list?

Not really. Just for the cases there's a discrepancy.

**Comment by zdroid** [comment]
@MartijnCuppens It's quite an extraordinary case though. The stats say I have [148 merged PRs](https://github.com/twbs/bootstrap/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+author%3Azdroid) out of [202 closed](https://github.com/twbs/bootstrap/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Azdroid).  Many PRs were merged manually aswell, so the number of "merged PRs" should be higher.

Considering GitHub's merge system in the past created a merge commit for every merge, those ~150 commits actually constitute 300 commits in repo's history, which is ~1.6% out of all commits. The percentage is even higher for v3 commits only.

**Comment by XhmikosR** [comment]
Merge commits don't count IIRC.

**Comment by zdroid** [comment]
Maybe you're right, I'm definitely not sure about that point. Still doesn't change the general point.

**Comment by XhmikosR** [comment]
What i said and also v3 differs from v4 and master branches. I don't think
github counts commits outside the main branch

**Comment by mdo** [comment]
Isn't this something that GitHub can address with multiple email addresses in account settings?

**Comment by zdroid** [comment]
@mdo The Google account associated with my previous email has been permanently deleted. I did try adding it to my GitHub account after your comment, and it seems my commits (such as https://github.com/twbs/bootstrap/pull/15477/commits/576230b92ae5a082eb8e058dc2fab7c67c99bd19) got properly recognized. I'd still give this time since my name isn't in contributors yet. May it be a problem with my email being impossible to verify (since it's deleted)?

**Comment by XhmikosR** [comment]
I'm personally not even sure if this will fix your issues. Because like I said before, the v3-dev branch is quite different from the master branch thus GitHub won't count the commits to that branch.

I'd suggest that you contact GitHub support first. I don't mind having this patch since it's the standard way, I just want to do it if it's really useful in your case since you are the only one who brought this issue up.

**Comment by zdroid** [comment]
@XhmikosR Thanks for the tip, I'll contact GitHub support about this.

**Comment by zdroid** [comment]
GitHub support confirmed email doesn't have to be verified, and all or at least most of my commits reappeared.

I'm closing this, thanks @mdo for the helpful suggestion.

**Pull request closed without merging**
