### PR TITLE
Fixes #15653 — Add comment which explains that how a responsive im...

### LINKED ISSUE #15653: Document that centering .img-responsive requires .center-block
(As opposed to `.text-center`)
Refs https://github.com/twbs/bootstrap/pull/15648#issuecomment-71180027

### PR DESCRIPTION
**Pull request by kkirsche**
Fixes issue #15653 — Add comment which explains that how a responsive image should be centered

Redo of #15657 which I couldn't get to rebase properly after all the merges were done last night.

cc: @mdo

### CODE REVIEW

**Comment by cvrebert** [comment]
Could you tweak the commit message to start with "Fixes #15653" so that GitHub's auto-issue-closing feature can work?

**Comment by kkirsche** [comment]
Amended and forced push. Sorry about that.

**Comment by mdo** [comment]
@kkirsche Thanks! Appreciate all the effort you've put into Bootstrap lately.

**Comment by kkirsche** [comment]
Of course. It's been my pleasure. I use Bootstrap so much that it's time I give back. I hope I can keep helping out and see where things end up down the line. My current goal is to get to top 10 contributors but that's just arbitrary. If a fix prevents someone from needing to open an issue, then that's all that matters. Thanks for being so open to the contributions and some of the questions I've had around rebasing, etc.

**Comment by cvrebert** [comment]
@kkirsche :metal:

**Comment by mdo** [comment]
@kkirsche Keep it up, we need the regulars around here to help us out. Takes so much time to dive in and out of the issues these days. Seeing consistent faces and being asked pointed questions is huge.

**Pull request merged**
