### PR TITLE
Remove zero border-radius on .jumbotron-fluid

### PR DESCRIPTION
**Pull request by vsn4ik**
See: http://v4-alpha.getbootstrap.com/components/jumbotron/#content

### CODE REVIEW

**Comment by cvrebert** [comment]
@vsn4ik This seems to be intentional. Per the docs:
> To make the jumbotron full width, **and without rounded corners**, add the `.jumbotron-fluid` modifier class

Please correct me if there's something I'm missing.

**Comment by vsn4ik** [comment]
@cvrebert Indeed, I had overlooked. Yet I think that the rounding must be processed variable `$enable-rounded`.

**Comment by cvrebert** [comment]
@vsn4ik The code uses the `border-radius` mixin, which takes care of that for us:
https://github.com/twbs/bootstrap/blob/2f257445c3d297077ce6dc06ff1b8559d36b6495/scss/mixins/_border-radius.scss#L3-L7

**Comment by vsn4ik** [comment]
@cvrebert Why did `.jumbotron-fluid` set `border-radius: 0`?

**Comment by cvrebert** [comment]
Because that's what @mdo wanted for some reason.
@mdo Care to give your reasoning?

**Comment by maxxyme** [comment]
OK, still no reason @mdo?
Because that doesn't really make sense to put some border-radius then remove it if you go -fluid.
http://v4-alpha.getbootstrap.com/components/jumbotron/

**Comment by mdo** [comment]
The intention here is that the jumbotron extends from one edge of your viewport to another—with no gaps of any kind on either side. Thus, there should be no rounded corners for that.

**Pull request closed without merging**
