### PR TITLE
hide captions for for smaller viewports

### PR DESCRIPTION
**Pull request by bassjobsen**
should close https://github.com/twbs/bootstrap/issues/18171

### CODE REVIEW

**Comment by bassjobsen** [comment]
possibly also consider to apply `sr-only()` to hide the caption? But reset it will make the code more complex

**Comment by patrickhlauke** [comment]
Maybe I'm missing something here, but: if captions convey information, why should they be hidden, ever?

Turning them into screen-reader only text on small screen size will, paradoxically, make the information accessible to screen-reader users while not making it accessible to any other user group. Why? Are non-AT-users not supposed to get the info?

**Comment by cvrebert** [comment]
There is a general problem with the caption text getting cut off if there's insufficient room for it.
Example from #18140: Compare:
small
Versus:
supersmall
(The only difference being the viewport width)
Note how the heading in the caption got cut off in the latter screenshot.

However, this isn't particular to XS screens per se, so I agree that this PR's hiding scheme isn't a great solution.

@mdo Could you give your reasoning for https://github.com/twbs/bootstrap/issues/18171#issuecomment-156784143 ?

**Comment by bassjobsen** [comment]
@patrickhlauke 
>non-AT-users not supposed to get the info?
Well non-AT-users can see the images of the carousel. But indeed i agree this make only sense when the information is only addtional to the images.
we shall wait for @mdo :)

**Comment by mdo** [comment]
My thought there was just how crazy they look with the captions overlaying things. Looking at the screenshots again, it'd be nice if the captions simply moved to the bottom of the images instead.

**Comment by iatek** [comment]
A workaround I've found is using CSS 3 `object-fit:cover` (no IE9, edge, etc..) which makes the img behave more like a background image so that it can be scaled properly along with the caption.

http://www.codeply.com/go/EaMgFMhff2

**Comment by mdo** [comment]
This can be optionally handled with display utilities. Example coming with #21298.

**Pull request closed without merging**
