### PR TITLE
V4 hamburger fix2

### PR DESCRIPTION
**Pull request by patrickhlauke**
successor to https://github.com/twbs/bootstrap/pull/20260

closes https://github.com/twbs/bootstrap/issues/20234

for comparison: current v4-dev (top) using the unicode character, and the CSS SVG background image (bottom)

> hamburglar

### CODE REVIEW

**Comment by patrickhlauke** [comment]
for comparison: current v4-dev (top) using the unicode character, and the CSS SVG background image (bottom)

> hamburglar

**Comment by patrickhlauke** [comment]
prototype fiddle to test out https://jsfiddle.net/nu5ejdy3/7/ - only issue seems to be Edge and IE11 rendering the svg a bit too...harshly. looks good in chrome/firefox though

**Comment by patrickhlauke** [comment]
rendering of the SVG icon in chrome, firefox, edge and IE11 on Win10

> hamburglar2

**Comment by cvrebert** [comment]
I believe the conclusion from #17222 was that SVGs shouldn't be base64-ed, since it increases their size.

**Comment by XhmikosR** [comment]
Agreed with @cvrebert, but just to verify, @patrickhlauke: isn't the base64 version larger?

**Comment by patrickhlauke** [comment]
fair enough, i'll admit to not knowing all the ins and outs of data URIs. optimized the source SVG and url-encoded it ... https://jsfiddle.net/nu5ejdy3/8/

**Comment by patrickhlauke** [comment]
force-pushed the change to encoding

**Comment by patrickhlauke** [comment]
@mdo @cvrebert any more thoughts on this?

**Comment by mdo** [comment]
Haven't had a chance to review much else with trying to wrap up the Alpha 3 stuff. Will peep when I can after that gets released.

**Comment by patrickhlauke** [comment]
ping @mdo

**Comment by patrickhlauke** [comment]
alternatively, there's a neat set of icons https://github.com/danklammer/bytesize-icons that we could look at using (also for other things like the X close icons)

**Comment by bardiharborow** [comment]
@patrickhlauke, aren't X close icons just `&times;` these days?

**Pull request merged**
