### PR TITLE
Removing extra bracket in introduction docs

### PR DESCRIPTION
**Pull request by KristofMorva**

### CODE REVIEW

**Review by patrickhlauke — APPROVED** [review]

**Comment by patrickhlauke** [comment]
hmm seems that travis-ci is hanging...been waiting for ages for the check to clear. @mdo ?

**Comment by KristofMorva** [comment]
@patrickhlauke I think it has just finished :)

**Comment by patrickhlauke** [comment]
Still showing me "continuous-integration/travis-ci — Waiting for status to be reported" ... until then i'm blocked from merging. ho hum, hopefully will shake itself out at some point and then i'll merge :)

**Comment by KristofMorva** [comment]
@patrickhlauke strange, for me both on GitHub and on Travis page it's passed; but hopefully it'll resolve itself ;)

**Comment by XhmikosR** [comment]
Travis is seriously broken sometimes. It doesn't even build this PR and we can't merge without it passing.

Only repo owners can, /CC @mdo.

**Review by mdo — APPROVED** [review]

**Pull request merged**
