### PR TITLE
fix width for flexbox 2011

### PR DESCRIPTION
**Pull request by efender**

### CODE REVIEW

**Comment by mdo** [comment]
Which versions of which browsers require this syntax?

**Comment by efender** [comment]
According to caniuse (http://caniuse.com/#feat=flexbox) they are Safari <=6, iOS Safari <= 6.1, Android Browser <= 4.3, Blackberry 7.
I tested on Windows Safari 5.1.7 (last version for Win), without width flexbox doesn't work properly.

**Comment by cvrebert** [comment]
We don't officially support any of those browsers: http://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#supported-browsers

**Comment by efender** [comment]
I see

**Pull request closed without merging**
