### PR TITLE
Throw error when tooltip/popover template has multiple top-level elements

### LINKED ISSUE #16219: bug when tooltip template has text (e.g. new line character) in between <div>s
When there is text in tooltip 'template' option (e.g. new line character), a bug is reported in jQuery. Tracing the bug leads to Tooltip.prototype.applyPlacement where on line 1500 $tip.offset(offset) is called and $tip contains 'text' nodes (which don't have offset, or at least ownerDocument.defaultView.getComputedStyle( elem, null ) doesn't want 'elem' to be 'text' when 'ownerDocument' is #document):

image

$tip: jQuery.fn.init[7]
0: div#tooltip981716.tooltip.fade.bottom.in
1: text
2: div#tooltip981716.tooltip-arrow.fade.bottom.in
3: text
4: div#tooltip981716.tooltip-inner.fade.bottom.in
5: text
6: div#tooltip981716.fade.bottom.in
length: 7
....

This is the error message:

image

And this is the state:
image

The best would be to skip the text elements or at least the documentation of Tooltip should state that not even eonls are allowed in between the `<div>`s

### PR DESCRIPTION
**Pull request by cvrebert**
Closes #16219.
CC: @hnrch02 @XhmikosR @patrickhlauke for review

### CODE REVIEW

**Comment by fat** [comment]
I wonder if we should enforce type checking on all options passed into our plugins?

**Comment by fat** [comment]
I think it would be cool to add some sort of convention for this to our v4 log.

Meanwhile, not sure if it's worth getting this alone into v3, but I'll leave it up to your judgement.

Code lgtm!

**Comment by XhmikosR** [comment]
Definitely. And we should finally switch to strict comparison operators. I
honestly see no downside and I have already suggested this from day 1 but
you rejected it back them.

**Comment by fat** [comment]
Sure, i'm happy to have it in v4 if you open a pr.

**Comment by XhmikosR** [comment]
Still haven't even checked out v4. I'm talking about the current version.

**Pull request merged**
