### PR TITLE
v4: Colors redux

### LINKED ISSUE #18119: v4: suggestion to introduce a color contrast function
for instance: http://compass-style.org/reference/compass/utilities/color/contrast/#function-contrast-color

Useful in among others `mixins/background-variants.scss`:

```
// Contextual backgrounds

// [converter] $parent hack
@mixin bg-variant($parent, $color) {
  #{$parent} {
    color: contrast-color($color,$gray-dark,$gray-lightest);
    background-color: $color;
  }
  a#{$parent} {
    @include hover-focus {
      background-color: darken($color, 10%);
    }
  }
}
```

See also: https://github.com/twbs/bootstrap/issues/18118

### LINKED ISSUE #19004: Form validation state colors aren't colorblind-friendly
> Changing these values for v3 isn't going to happen—it's quite a stark change for folks who simply want to upgrade to the latest. v4's colors can and will be changing though, so we can revisit then.

Issue #14744 was closed a year and a half ago to postpone an accessibility issue until v4. Due to the ongoing problem I propose reopening it and attempting to create colors that don't ruin the experience for the 96% of people with color vision but allow the 4% without to still use bootstrap-constructed forms.

### LINKED ISSUE #19792: Add card-specific color variables
There should be an easy way to customize the color of the `.card` background. 

Right now the colors are hard coded inside https://github.com/twbs/bootstrap/blob/1a6d0cc446259cf86d73bf7437f2ca3b095f6781/scss/_card.scss#L123-L141

Instead there should be a default similar to this:

``` scss
// Cards
$card-spacer-x:            1.25rem !default;
$card-spacer-y:            .75rem !default;
$card-border-width:        1px !default;
$card-border-radius:       $border-radius !default;
$card-border-color:        rgba(0,0,0,.125) !default;
$card-border-radius-inner: $card-border-radius !default;
$card-cap-bg:              #f5f5f5 !default;
$card-bg:                  #fff !default;
$card-primary-bg:          $brand-primary !default;
$card-success-bg:          $brand-success !default;
$card-info-bg:             $brand-info !default;
$card-warning-bg:          $brand-warning !default;
$card-danger-bg:           $brand-danger !default;

$card-link-hover-color:    #fff !default;
```

### LINKED ISSUE #22062: Accessibility - custom improvement - allow badge text color customisation
As it's possible to custom badge background color for default, danger, and all others. There may be also a variable for text color in each case. By this way, the user can ensure that the contrast ratio between font color and background is all time okay with WCAG requirements.

You can see a proposition here : 
https://github.com/Lausselloic/bootstrap/commit/ec75282e85c378216c5ccb300ef910aa93130acc

### LINKED ISSUE #22175: Stop using hex values for form state and alert colors
Color definitions for form states and alerts should derive from the 'general variable structure' where all other colors are defined. 

As often as we can, we should follow our convention of defining values off of our base variables. So for instance, `state-success`, `state-info`, `state-warning`, etc. should all modify the base value of `brand-success`, `brand-info`, `brand-warning`, etc. To ovoid creating new colors.

The Bootstrap framework should take the position of not assuming too much. Bootstrap should not assume that your form state and alert colors would differ from your established brand colors (as most instances they wouldn't). This would lighten the initial configuration of Bootstrap.

The following is a bad practice. It defines new colors outside of our main color definitions, and makes configuration more cumbersome:
```
$state-success-text:             #3c763d !default;
$state-success-bg:               #dff0d8 !default;
$state-success-border:           darken($state-success-bg, 5%) !default;
```
Instead we should have something like the following:
```
$state-success-text:             invert($brand-success) !default;
$state-success-bg:               darken($brand-success, 10) !default;
$state-success-border:           darken($state-success-bg, 5%) !default;
```

### PR DESCRIPTION
**Pull request by mdo**
This PR supersedes #22551 with a slightly different approach to enabling more color usage while continuing to support the theme approach that the `$brand-` variables enable.

### New colors

I've updated all the color variables, though I'm still not 100% happy with them. I'm struggling to find the right way to create a legit palette here. However, it's getting closer thanks to Material, Open Color, and more. My intent here is that you can swap all the variables easily with other common color palettes from major systems (iOS, Android, etc). As such it's important to have the right number of colors in place to build on. 

screen shot 2017-06-15 at 11 18 54 am

### Dual Sass color maps

In #22551 I was pushing heavily towards a single Sass map, but not everyone builds on Bootstrap with Sass, so that limits options for those adding vanilla CSS on top of our code. As such, it's entirely possible `.btn-blue` could become a purple button.

Now, we have two Sass maps, `$colors` and `$theme-colors`, though they're not entirely implemented right now. `$colors` is for _every_ color. `$theme-colors` is for a subset of those that you'd want to loop over to generate a customized color scheme. The intent is to use this theme Sass map to generate our alerts, buttons, backgrounds, etc.

screen shot 2017-06-15 at 11 23 35 am

### Grayscale

In addition to the two color maps, I've added a `$grays` Sass map and new variables. Instead of a few `$gray-light`, `$gray-dark`, etc variables, we have `$gray-100` through `$gray-900`. This provides greater flexibility, a consistent set of grays throughout, and the basis for future color updates. (Eventually every color should have all these shades.)

screen shot 2017-06-15 at 11 27 19 am

### Additional improvements

I'm after a number of things with a color update like this. First, I want more colors available to folks to pull from and more options to customize via CSS or Sass (our preferred method). Second, I want the tooling to be helpful, so color contrast functions and proper map values is important. Third, I want to provide more utilities for folks based on these colors (e.g., border color classes) while reducing component-based modifiers where appropriate (e.g., badge backgrounds can be `.bg-` classes).

### Todo

- [x] **Finalize color palette.** Please, any and all suggestions on how to build one well is welcome!
- [x] **Determine what needs to be in the `$theme-colors` map.** I've added foreground/background, but are there more? Should it be fewer?
- [x] Ensure we can easily add additional Sass maps for color shades in a future release.
- [x] Ensure `map-get` functions are in place for each Sass map (think I'm missing grays right now)
- [x] Improve customization docs.

---

- Fixes #18119 and fixes #22062 by adding badge color contrast function
- Fixes #22175 by removing alert, state, and table variables
- Fixes #19004 by improving color contrast
- Closes #19792 by moving away from component-specific variables

### CODE REVIEW

**Comment by Thomas--S** [comment]
This PR seems to be a very good approach to me. It unites the good things from the current system and the closed PR. Thanks!

My suggestions regarding the color palette:
- Rename blue and indigo to light blue and dark blue
- Split green into light green (e.g. `#00dd00`) and dark green (e.g. `#008700`)
- _Maybe_ add a brown color (e.g. `#8b4513`)

**Comment by bbmatt** [comment]
This seems a very logical approach, although I wonder whether the concept of percentages could be used rather than 100 through to 900?
From a design perspective, color percentage values are widely used - 10% grey, 20% grey etc.? 
Worth looking up the 60-30-10 Rule for design, as this would then align the colors with commonly accepted design concepts?

**Comment by IamManchanda** [comment]
@mdo This is a very good approach compared to old one! :+1:

**Comment by roooodcastro** [comment]
I think there should be a way to overwrite the way borders, shadows, hover, focus, etc are defined, fixing #21037.

#21670 defines variables for basically everything. I think adding those (or at least some) variables in this `$theme-colors` map would be a good solution.

**Comment by wilsonge** [comment]
Looks much better than the last approach. Thanks for listening to the concerns :)

**Comment by Pingendo** [comment]
@mdo IMHO a good starting point for  $theme-colors map would be to include primary-secondary-faded-inverse-info-success-warning-danger. I can't understand background-foreground meaning.

BTW color-yiq mixin and $sass-colors are super-usefull (Claps hands)

**Comment by gseregni** [comment]
@mdo IMHO a good starting point for $theme-colors map would be to include primary-secondary-faded-inverse-info-success-warning-danger. I can't understand background-foreground meaning.

BTW color-yiq mixin and $sass-colors are super-usefull (Claps hands)

**Comment by mdo** [comment]
> I can't understand background-foreground meaning

These _should_ be self explanatory—it's the foreground `color` and the `background-color`—but if they're not, we should revisit. It's meant to be a way to signal to theme builders and customizers that you can flip the dark text on light background into a light text on dark background.

**Comment by gseregni** [comment]
Ah ok. So putting foreground and background in $theme-colors maps ends up creating counterintuitive rules likes bg-foreground/bg-background. $body-bg and $body-color are not enough for that ?

**Comment by mdo** [comment]
Big update today—some breaking class name changes, updated `$theme-colors` Sass map, updated colors, and more. Here's a quick rundown of what's changed:

- Updated color scheme and the `$theme-colors` Sass map. I renamed the `foreground` and `background` options to `light` and `dark` with the intention of consolidating our various methods of referring to brightness class names. Instead of the many options for referencing these with dark and light, faded and inverse, and light and inverse, we have `light` and `dark`.

- Renamed `.bg-faded`to `.bg-light`, allowing all background utility classes are now generated from the newly updated `$theme-colors` Sass map. Renamed `.bg-inverse` to `.bg-dark` to match. 

- Updated badges to drop `.badge-default` and generate the modifier classes from the `$theme-colors` Sass map, adding new variants in the process.

- Similarly, updated alerts to use the `$theme-colors` Sass map, adding many new variants.

- Replaced `.navbar-inverse` with `.navbar-dark`—yes, again :sob:—and updated `.navbar-light` examples to use `.bg-light`.

- Replaced `.card-inverse` with `.card-dark` to match the navbar change.

- Added a new `$theme-color-interval` variable and `$theme-color-level` function for generating shades of any color in the `$theme-colors` Sass map. In the future we'll generate all the shades, `100` through `900` like our grays, to provide ready-made variables for folks.

Here's a brief look at some of the updates:

screen shot 2017-06-25 at 6 40 13 pm

screen shot 2017-06-25 at 6 40 21 pm

screen shot 2017-06-25 at 6 36 42 pm

screen shot 2017-06-25 at 6 35 30 pm

**Comment by mdo** [comment]
@bardiharborow Any idea what's up with tests here and this Babel plugin?

**Comment by Johann-S** [comment]
@mdo I suggest to clear travis cache for your branch and try to trigger a new build, everything is fine on `v4-dev` and I don't see why on this branch our build can fail for a JS reason

**Comment by misterdai** [comment]
@mdo don't know if it helps but the plugin it's complaining about, in the tests, is present in the `package.json` file but not `build/npm-shrinkwrap.json`.

**Comment by mdo** [comment]
Still more to do:

- [x] Clean up alert, state, and table Sass since we're generating this from the Sass map now (see #22175, #19792)
- [ ] Close #19004?
- [ ] Close #18119 for color function

Just pushed updates for tables and list groups. Still need a bit more refinement on these colors.

**Comment by mdo** [comment]
Removed the old `$gray-` variables in latest commits.

**Pull request merged**
