### PR TITLE
Create `scss-docs` shortcode to get some snippets from the Scss source files

### PR DESCRIPTION
**Pull request by MartijnCuppens**
This should be a little bit easier that creating a custom regex per case.

Usage in `.scss`:
``` scss
// scss-docs-start awesome-code
.my-awesome-code {
  // The best CSS in the world
}
// scss-docs-end awesome-code
```

In the docs files:
``` twig
{{< scss-docs name="awesome-code" file="scss/_variables.scss" >}}
```

I don't think the positive lookbehind syntax works in Hugo, so I replaced the comments in the end of the file, there are probably better ways to fix this (bump @XhmikosR)

TODO:
- [x] Check all occurrences of code snippets
- [x] Strip `!default` flags by default

### CODE REVIEW

**Comment by mdo** [comment]
Oh you brilliant son of a bucket, that's rad. This is fresh as hell.

**Comment by ffoodd** [comment]
I love this, it'll make things so much easier!

**Comment by MartijnCuppens** [comment]
Neither the positive lookbehind syntax nor grouping seem to be supported in Hugo regex, so the replacing the comments seems to be the way to go.

Ready for review!

**Comment by XhmikosR** [comment]
It's in my backlog 🙂

I'll check what's supported but this seems to do the job anyway.

**Review by mdo — APPROVED** [review]
This looks lovely to me, so adding an approval for whatever it's worth :).

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
