### PR TITLE
Update dependencies, including Babel to v6 and zeroUnits fix.

### LINKED ISSUE #18144: Follow-up on clean-css zeroUnits TODO
Refs https://github.com/twbs/bootstrap/pull/18081#issuecomment-152097011
Refs https://github.com/twbs/bootstrap/issues/14837#issuecomment-153325181

### LINKED ISSUE #18212: Upgrade Babel
Details: http://jamesknelson.com/the-six-things-you-need-to-know-about-babel-6/
Also: https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/user-handbook.md
CC: @XhmikosR

### PR DESCRIPTION
**Pull request by bardiharborow**
- jQuery to 3.1.1
- Tether to 1.3.7
- clipboard.js to 1.5.12
- Holder to 2.9.4
- jekyll-search to 1.0.5
- QUnit to 2.0.1
- Anchor to 3.2.2
- Babel to 6.0.0 and include `babel-plugin-transform-es2015-modules-strip` to replicate v5 `modules: ignore` behaviour (fixes #18212)
- grunt-contrib-cssmin to 1.0.2 and simply IE9 bugfix (fixes #18144)
- all other NPM dependencies to the latest version
- all Ruby gems to the latest version

### CODE REVIEW

**Comment by bardiharborow** [comment]
Hound warnings are fixed in #20446.

**Comment by mdo** [comment]
How many of these Hound issues are legit? 😆

**Comment by bardiharborow** [comment]
@mdo none of them :joy:. They should clear up once #20446 is merged. This PR overlaps with XhmikosR's #20288 quite significantly, so you may wish to merge that first and then I'll rebase this.

**Comment by mdo** [comment]
@bardiharborow Just merged that PR :D. Let's see if this gets updated and we can get it merged in, then deal with any overlap later.

**Comment by wolfy1339** [comment]
You will need to rebase the PR to get Hound to clear the issues

**Comment by bardiharborow** [comment]
@mdo it's all green now. 😄

**Comment by mdo** [comment]
😻 Thanks!

**Comment by bardiharborow** [comment]
@mdo, it appears there we side effects to this and now travis builds are crashing, which is very weird given that the build of the PR itself passed. Root cause is npm/npm#14042, something to do with me shrink-wrapping on a mac.

**Comment by bardiharborow** [comment]
@mdo, fix is at fc2a11d. I'm still none the wiser as to how the PR build passed but branch builds aren't.

**Pull request merged**
