### PR TITLE
Remove negative margins leftovers

### PR DESCRIPTION
**Pull request by MartijnCuppens**
... and fix the header height.

### CODE REVIEW

**Comment by XhmikosR** [comment]
It might still be worth reverting #30585, though. We should discuss this further.

**Review by XhmikosR — APPROVED** [review]

**Comment by MartijnCuppens** [comment]
> It might still be worth reverting #30585, though. We should discuss this further.

It would be easy to restore them if needed. I don't expect these were widely used since we only used them in responsive gutter example.

**Comment by XhmikosR** [comment]
@mdo WDYT?

**Review by mdo — APPROVED** [review]
I say :shipit:!

**Pull request merged**
