### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by JoyceBabu**
Should remove `data` not `class` on dispose

### CODE REVIEW

**Review by auvipy — COMMENTED** [review]
need rebase

**Comment by JoyceBabu** [comment]
Shall I rebase the `patch-1` branch to `bootstrap:v4-dev`?

I can see several commits in my `patch-1` branch that were not made by me. Is it because I have selected `Allow edits from maintainers` in this PR?

**Review by Johann-S — APPROVED** [review]
Good catch 👍

**Comment by Johann-S** [comment]
Your branch is now up to date 😉

**Pull request merged**
