### PR TITLE
Unit tests: Finish preparations for QUnit v2 upgrade

### PR DESCRIPTION
**Pull request by hnrch02**
Refs #15893

### CODE REVIEW

**Comment by hnrch02** [comment]
With this all points of http://qunitjs.com/upgrade-guide-2.x/ should be covered and we're safe to upgrade whenever QUnit 2 releases.

**Comment by cvrebert** [comment]
There were a couple more things actually, but I just added commits for those to this PR :smile:

**Comment by hnrch02** [comment]
But... But... I searched for all them. I should just grep the whole project in the future and not rely on the search in Sublime :disappointed:

**Comment by hnrch02** [comment]
Anyhow, thanks for adding what I missed, as you always do :heart:

**Pull request merged**
