### PR TITLE
Switch to jQuery slim version.

### PR DESCRIPTION
**Pull request by XhmikosR**
We don't use the extra features the normal build has.

See https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/

/CC @cvrebert @hnrch02 @dmethvin for thoughts.

### CODE REVIEW

**Comment by cvrebert** [comment]
👍

**Comment by hnrch02** [comment]
SGTM. Maybe we should add a note in the docs about the slim version?

**Comment by XhmikosR** [comment]
Personally, I'd like to know what are the plans for the slim version, i.e. do they plan to keep releasing it or not. Apart from that, we should probably mention that the slim version works fine with Bootstrap v4 at this point.

**Comment by dmethvin** [comment]
Usually once we add a build we don't take it away. If we did stop making it I would expect that to not happen until the next major version. 

I think it's great that you're using the slim build. Most users will end up using a full build but this makes it possible for them to use slim or their own custom build.

**Comment by calvinf** [comment]
This makes sense as long as the Bootstrap v4 website makes it easy and clear that either jQuery 3.0 or 3.0 slim builds can be used.

**Comment by XhmikosR** [comment]
Well I'm no good with writing docs. I'd rather merge this and address the
doc changes later with someone else's help for the docs.

**Comment by lorvent** [comment]
Personally i feel its better to use regular version.

even though you don't need functions like `$.ajax` those who uses bootstrap with server side languages needs them.

and if we download bootstrap through bower, if you ship slim version, people need to include regular version again.

and difference in size is just 6kb

**Comment by hnrch02** [comment]
@lorvent This only touches the jQuery files used in the docs/tests.

**Comment by lorvent** [comment]
oops...sorry about that

**Comment by auvipy** [comment]
what about jquery 3.1?

**Comment by XhmikosR** [comment]
Make a separate issue for that please.

**Comment by bardiharborow** [comment]
Just a heads up that this PR changes [_config.yaml](https://github.com/twbs/bootstrap/blob/v4-dev/_config.yml), which cascades to the example on [docs/getting-started/introduction.md](https://github.com/twbs/bootstrap/blob/v4-dev/docs/getting-started/introduction.md). I think changing that without clarifying further might be inadvisable.

**Comment by mdo** [comment]
Should we try to get this into Alpha 5? Seeing some conflicts preventing this from being merged.

**Comment by XhmikosR** [comment]
This is obsolete and I need to update it. I'll do it tomorrow probably.

**Comment by mdo** [comment]
Replaced by #21466.

**Pull request closed without merging**
