### PR TITLE
v4 — Use the body color for dropdown menu text in navbars

### LINKED ISSUE #17276: v4 - Navbar bg-primary dropdowns should get black font color
When a navbar has `.bg-primary` the dropdown should get a black font color.

Something like:
```
.bg-primary .dropdown-menu {
	color: #000;
}
```
Otherwise this leads to some problems:
img_2015 08 24_17h05m12s_009_
img_2015 08 24_17h06m06s_010_

### PR DESCRIPTION
**Pull request by kkirsche**
Fix #17276

### CODE REVIEW

**Comment by mdo** [comment]
We should be able to apply this to the `.dropdown-menu` itself, without scoping it to the navbar, no?

**Comment by kkirsche** [comment]
That's a good point. I hadn't fully considered that as my thought was in most cases it would inherit that. But you're right it makes more sense to be explicit about that. That update has been pushed

I think I got the right declaration order but I couldn't figure out if your guide was to have imports last or because it's visual use alphabetical within this section... Sorry if I got it wrong!

**Comment by mdo** [comment]
`color` comes after `font` and `line-height` properties :). See https://github.com/twbs/bootstrap/blob/v4-dev/scss/.scsslint.yml#L93 for the specifics. Some of the reasoning is highlighted at http://codeguide.co/#css-declaration-order.

**Comment by kkirsche** [comment]
OK. That's fixed. Is that just one of those things that is constantly looked at or just memorized over time?

**Comment by mdo** [comment]
Oh yeah, I've basically memorized it at this point since it's based on how I write CSS :p. You can lint it yourself with `grunt scsslint` though, too.

**Comment by cvrebert** [comment]
@kkirsche Update the commit message since this no longer touches navbar code?

**Comment by kkirsche** [comment]
Oops. Sorry about that @cvrebert

**Comment by kkirsche** [comment]
Rebased

**Pull request merged**
