### PR TITLE
Docs: Minor fixes in tables.

### PR DESCRIPTION
**Pull request by louismaximepiton**
Few fixes in tables. 

This leads me to other questions: 
- Why do we have [`Tab`](https://twbs-bootstrap.netlify.app/docs/5.2/components/navs-tabs/#javascript-behavior) javascript documentation inside [`List-Group`](https://twbs-bootstrap.netlify.app/docs/5.2/components/list-group/#javascript-behavior)? Seems like it was just a copy-paste.
- Why the [`Tab`](https://twbs-bootstrap.netlify.app/docs/5.2/components/navs-tabs/#methods) javascript methods aren't in a `<table>`?

### CODE REVIEW

**Review by julien-deramond — APPROVED** [review]
Modifications LGTM! They bring more consistency in the docs.

I don't have all the history to answer to your questions in the description. I let others respond.

**Comment by MadhavanBS** [comment]
> Few fixes in tables.
> 
> This leads me to other questions:
> 
> * Why do we have [`Tab`](https://twbs-bootstrap.netlify.app/docs/5.2/components/navs-tabs/#javascript-behavior) javascript documentation inside [`List-Group`](https://twbs-bootstrap.netlify.app/docs/5.2/components/list-group/#javascript-behavior)? Seems like it was just a copy-paste.
> * Why the [`Tab`](https://twbs-bootstrap.netlify.app/docs/5.2/components/navs-tabs/#methods) javascript methods aren't in a `<table>`?
> * Why the [`Tab`](https://twbs-bootstrap.netlify.app/docs/5.2/components/navs-tabs/#methods) javascript methods aren't in a `<table>`?

**Comment by mdo** [comment]
> * Why do we have [`Tab`](https://twbs-bootstrap.netlify.app/docs/5.2/components/navs-tabs/#javascript-behavior) javascript documentation inside [`List-Group`](https://twbs-bootstrap.netlify.app/docs/5.2/components/list-group/#javascript-behavior)? Seems like it was just a copy-paste.

I think just to indicate that list groups can be used with the Tab plugin. I think in v6, maybe v5.x, we could split the Navs & Tabs page into separate pages. Tabs is just about JS functionality and works with any of our navs and list groups as far as I know. I think there was a PR to add support for arbitrary elements but I can't recall. @GeoSot might remember.

> * Why the [`Tab`](https://twbs-bootstrap.netlify.app/docs/5.2/components/navs-tabs/#methods) javascript methods aren't in a `<table>`?

They definitely should be! Maybe open an issue to track, or tackle in a PR if you like :).

**Comment by mdo** [comment]
This PR also has some conflicts—can you update and we can merge?

**Review by mdo — APPROVED** [review]

**Pull request merged**
