### PR TITLE
Add PostCSS-RTLCSS approach to the documentation

### PR DESCRIPTION
**Pull request by elchininet**
### Description

This pull request modifies the [LTR and RTL at the same time](https://getbootstrap.com/docs/5.3/getting-started/rtl/#ltr-and-rtl-at-the-same-time) section of the documentation to explain how to achieve that goal using [PostCSS-RTLCSS](https://github.com/elchininet/postcss-rtlcss).

### Motivation & Context

Searching topics that included `PostCSS-RTLCSS` on the Internet, I found this [StackOverflow](https://stackoverflow.com/q/68866878/2035354) question asking how to achieve LTR and RTL in Bootstrap at the same time, and [the most voted answer](https://stackoverflow.com/a/71746320/2035354) mentioned `PostCSS-RTLCSS` as a better alternative to the instructions given in the documentation.

As I am the manintainer of the `PostCSS-RTLCSS` plugin, I opened [this discussion](https://github.com/orgs/twbs/discussions/39726) explaining the benefits of achieving `LTR and RTL at the same time` using `postcss-rtlcss` instead. Then as an outcome of the discussion, it was agreed to mention the plugin in the respective section in the documentation.

### Type of changes

- Documentation enhancement

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

- https://deploy-preview-39863--twbs-bootstrap.netlify.app/docs/5.3/getting-started/rtl/#ltr-and-rtl-at-the-same-time

### Related issues

https://github.com/orgs/twbs/discussions/39726

### CODE REVIEW

**Review by julien-deramond — APPROVED** [review]
Thanks for the PR @elchininet!
The explanation looks good to me and has the right level of information; not too much, but enough to understand how PostCSS RTLCSS could be embedded in one's project.
I'll let a native English speaker double-check the wording and also pinging @ffoodd for feedback (does it look OK to you too?).

**Comment by ffoodd** [comment]
Seems great! Thanks for the contribution.

The third point makes me wonder: could we move `rtl:remove` and `rtl:ignore` directives to their block version, to ease the move?

This shouldn't have any impact on our side.

**Review by ffoodd — APPROVED** [review]

**Comment by elchininet** [comment]
Hi @ffoodd,

>The third point makes me wonder: could we move rtl:remove and rtl:ignore directives to their block version, to ease the move?

What do you mean moving them to their block version?

I have plans of making this transparent for clients. As the intention of the RTLCSS directive is the same (do not create an RTL counterpart in the new stylesheet), what I want to achieve is that if someone uses a `remove` directive, this is translated to an `ignore` directive behind the scenes. If this is implemented in some moment, it is possible to remove the third point in the `Important things to take into account` callout warning.

But just let me know if you think that I should change that point or remove something from it at the moment.

Regards

**Comment by ffoodd** [comment]
My point is that moving directives as recommendend in your third point can be easily achieved un Bootstrap.

If we do it, would it ease your plugin usage?

**Comment by ffoodd** [comment]
Ah, got it too. Thanks, that's clearer 👌

**Pull request merged**
