### PR TITLE
Add Extend > Snippets docs page

### PR DESCRIPTION
**Pull request by mdo**
Exploring a new docs Extend page for capturing snippets of things folks would probably like to see in the core but aren't popular enough or important enough to make it into the main project.

---

### Components

- [x] #33285: Light buttons

### Utilities

- [x] Extended and responsive width/height
- [ ] Responsive borders
- [x] Responsive position

Preview: https://deploy-preview-33627--twbs-bootstrap.netlify.app/docs/5.1/extend/snippets/

### CODE REVIEW

**Comment by Kopyov** [comment]
@mdo use darker background on hover, not lighter. Similar to [list group items.](https://getbootstrap.com/docs/5.1/components/list-group/#contextual-classes)

**Comment by sadeghbarati** [comment]
> @mdo use darker background on hover, not lighter. Similar to [list group items.](https://getbootstrap.com/docs/5.1/components/list-group/#contextual-classes)

@Kopyov it's all about bootstrap mixins **[list-group](https://github.com/twbs/bootstrap/blob/f61a0218b36d915db80dc23635a9078e98e2e3e0/scss/mixins/_list-group.scss)**, **[buttons](https://github.com/twbs/bootstrap/blob/f61a0218b36d915db80dc23635a9078e98e2e3e0/scss/mixins/_buttons.scss)**

customize it based on your needs

```scss
@import "~/bootstrap/scss/functions";
@import "custom-var";

@import "~/bootstrap/scss/variables";
@import "~/bootstrap/scss/mixins";
@import "~/bootstrap/scss/utilities";

/* custom mixin */
@import "./mixins/buttons";
@import "./mixins/pagination";
/* custom mixin End */

@import "modify-theme";
@import "modify-utilities";

@import "~/bootstrap/scss/root";
@import "~/bootstrap/scss/reboot";
@import "custom-reboot";
@import "~/bootstrap/scss/type";
@import "~/bootstrap/scss/images";
@import "~/bootstrap/scss/containers";
@import "~/bootstrap/scss/grid";
@import "~/bootstrap/scss/tables";
@import "~/bootstrap/scss/forms";
@import "~/bootstrap/scss/buttons";
@import "~/bootstrap/scss/transitions";
@import "~/bootstrap/scss/dropdown";
@import "~/bootstrap/scss/button-group";
@import "~/bootstrap/scss/nav";
@import "~/bootstrap/scss/navbar";
@import "~/bootstrap/scss/card";
@import "~/bootstrap/scss/accordion";
@import "~/bootstrap/scss/breadcrumb";
@import "~/bootstrap/scss/pagination";
@import "~/bootstrap/scss/badge";
@import "~/bootstrap/scss/alert";
@import "~/bootstrap/scss/progress";
@import "~/bootstrap/scss/list-group";
@import "~/bootstrap/scss/close";
@import "~/bootstrap/scss/toasts";
@import "~/bootstrap/scss/modal";
@import "~/bootstrap/scss/tooltip";
@import "~/bootstrap/scss/popover";
@import "~/bootstrap/scss/carousel";
@import "~/bootstrap/scss/spinners";
@import "~/bootstrap/scss/offcanvas";
// Helpers
@import "~/bootstrap/scss/helpers";

// Utilities
@import "~/bootstrap/scss/utilities/api";

/* rtl:begin:ignore */
@import "./custom-theme";
/* rtl:end:ignore */

```

**Comment by sadeghbarati** [comment]
@mdo @XhmikosR 

Hi,

in **[Modal](https://getbootstrap.com/docs/5.1/components/modal/#fullscreen-modal)** component we have responsive classes **`modal-fullscreen-sm-down`**, **`modal-fullscreen-md-down`**, ...

how to do the same for **[Offcanvas](https://getbootstrap.com/docs/5.1/components/offcanvas/)**
just like **`navbar-expand{-sm|-md|-lg|-xl|-xxl}`**

**Comment by kriswillis** [comment]
I almost always add asterisks to the labels for required fields…
````css
label.required::after {
  content: '*';
  color: $danger;
}
````

**Comment by florianlacreuse** [comment]
@mdo Just to let you know, the text color of `btn-light-light` doesn't pass on WCAG AA test.
https://color.a11y.com/ContrastPair/?bgcolor=fefefe&fgcolor=7c7d7d

(Love the idea of adding these multiple snippets)

**Comment by mdo** [comment]
Closing as stale, gotta pick my battles 😬

**Pull request closed without merging**
