### PR TITLE
Harmonize usage of constants

### PR DESCRIPTION
**Pull request by Sparksx**
Use stored constants instead of strings for classes and selectors

### CODE REVIEW

**Review by MartijnCuppens — APPROVED** [review]
LGTM

**Comment by XhmikosR** [comment]
Not sure it's an improvement but at least it's consistent :)

**Comment by XhmikosR** [comment]
For what is worth, this increases the JS size. Not an issue with this patch per se, just generally using the constants as objects, since the minifier does not mangle the properties.

**Comment by XhmikosR** [comment]
I think at some point we'll need to revisit this altogether. I can't see how this is better than just plain strings for constants.

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
