### PR TITLE
Update scrollspy.md

### PR DESCRIPTION
**Pull request by Brianmanden**
Fixed minor grammatical error:

"... the best method get scroll ..."

=> 

"... the best method **to** get scroll ..."

### CODE REVIEW

**Review by MartijnCuppens — APPROVED** [review]
Thanks!

**Comment by MartijnCuppens** [comment]
@Brianmanden, could you make a new PR, this one was approved, but not yet merged?

**Comment by Brianmanden** [comment]
@MartijnCuppens Is it okay to reopen it instead ?

**Comment by MartijnCuppens** [comment]
Sure. I just don't know if that 'll work since you also deleted the branch

**Comment by Brianmanden** [comment]
Ahh .. ok. I´ll open a new one :)

**Pull request closed without merging**
