### PR TITLE
New examples screenshots

### PR DESCRIPTION
**Pull request by XhmikosR**
The images are PNG 8-bit optimized with optipng, zopfli and pngout.

### CODE REVIEW

**Comment by XhmikosR** [comment]
I'm gonna redo them in bigger resolution.

**Comment by mdo** [comment]
These also need to be done on a Mac, not a Windows machine. While Segoe is better than Arial, I prefer we use macOS's system font.

**Comment by XhmikosR** [comment]
I don't own a Mac, sorry. But compared to the obsolete current screenshots
we have, this is certainly better...

**Comment by andresgalante** [comment]
@XhmikosR Thanks for updating these. I'll generate the images on a mac and update the branch

**Comment by XhmikosR** [comment]
Cool, I'll resize/compress tomorrow then. Thanks!

**Review by mdo — DISMISSED** [review]
As soon as we can get macOS screenshots, this is good to go.

**Comment by XhmikosR** [comment]
Yeah, compressing them as we speak.

**Comment by XhmikosR** [comment]
@mdo: please check now. These are @andresgalante's screenshots, resized to 800x600, converted to 8-bit and compressed.

**Review by mdo — APPROVED** [review]

**Pull request merged**
