### PR TITLE
Add deprecation warning

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Add deprecation warning for `text-emphasis-variant()` mixin which will be dropped by https://github.com/twbs/bootstrap/pull/29267

### CODE REVIEW

**Review by bardiharborow — APPROVED** [review]
This is fine, provided #29267 merges.

**Review by mdo — APPROVED** [review]

**Comment by ELI7VH** [comment]
what do we use instead?

**Comment by MartijnCuppens** [comment]
@ELI7VH,

From `v5` you will be able to use the text utilities https://twbs-bootstrap.netlify.com/docs/4.3/utilities/colors/#color to colorize text and https://twbs-bootstrap.netlify.com/docs/4.3/helpers/colored-links/ for links with hover states.

**Comment by Eonasdan** [comment]
@MartijnCuppens doc links are dead. I got a theme using this and I'd like to fix it.

**Comment by MartijnCuppens** [comment]
I've just updated them. You can still use `text-emphasis-variant()` in `v4`, but make sure the 3th parameter is `true`.

**Comment by digitaldonkey** [comment]
It might be helpful to provide an alternative for BS 4.4+ when you add a deprecation warning. 
Links above do not provide an alternative for the **mixing**.

**Pull request merged**
