### PR TITLE
Replace lint-vars.sh script with a shell.js script. 

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
Only improvement we could make is support multiple directories passed; this would actually save us one call in our scripts.

**Comment by XhmikosR** [comment]
@mdo: this seems to work pretty nice :) https://travis-ci.org/twbs/bootstrap/jobs/306976447

**Review by Johann-S — APPROVED** [review]

**Review by mdo — CHANGES_REQUESTED** [review]
Script seems good! Those two variables should be used though :). I'll get a PR cut for that shortly.

**Comment by XhmikosR** [comment]
OK, just approve and I'll drop their removal and then merge :)

**Comment by mdo** [comment]
PR opened: #24891.

**Comment by XhmikosR** [comment]
All right, I'll rebase after that is merged.

**Review by mdo — APPROVED** [review]
Once those vars are cleared, good to go!

**Comment by XhmikosR** [comment]
```
Finding unused variables in "scss/"...
There's a total of 499 variables.
No unused variables found in "scss/".
Finding unused variables in "assets/scss/"...
There's a total of 8 variables.
No unused variables found in "assets/scss/".
```

BTW, the script's logic is pretty "dump" but it does the job for our case.

**Comment by mdo** [comment]
I'm seeing some issues with this breaking the `watch` task:

```
Finding unused variables in "scss/"...
There's a total of 501 variables.
Variable "$form-check-margin-bottom" is only used once!
Finding unused variables in "assets/scss/"...
There's a total of 8 variables.
No unused variables found in "assets/scss/".
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@4.0.0-beta.2 css-lint-vars: `node build/lint-vars.js scss/ assets/scss/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bootstrap@4.0.0-beta.2 css-lint-vars script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mdo/.npm/_logs/2017-12-20T02_24_10_664Z-debug.log
ERROR: "css-lint-vars" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@4.0.0-beta.2 css: `npm-run-all --parallel css-lint* css-compile* --sequential css-prefix* css-minify*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bootstrap@4.0.0-beta.2 css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mdo/.npm/_logs/2017-12-20T02_24_10_868Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...
```

Near as I can tell, there are no unused variables—just one that's used once.

**Comment by XhmikosR** [comment]
@mdo: it was working, wasn't it? :D

**Comment by mdo** [comment]
@XhmikosR I was confused by the output—see #25049.

**Pull request merged**
