### PR TITLE
Add coverall to follow our coverage

### PR DESCRIPTION
**Pull request by Johann-S**
Hey guys !

I want to add Coverall to our repository because it'll help us to follow our coverage by adding a badge in our README.md plus it'll add comments in PRs which will indicate if our coverage is lower than before.

@mdo if you're ok with that, please see : 
- https://coveralls.io/sign-up
- https://docs.coveralls.io/coveralls-notifications
- https://github.com/nickmerwin/node-coveralls#usage

Edit:

Currently we have that, but it's normal : 

image

/CC @XhmikosR @bardiharborow @cvrebert

### CODE REVIEW

**Review by XhmikosR — APPROVED** [review]
LGTM, but we should add the badge before merging :)

**Comment by Johann-S** [comment]
ping @mdo we need you 🙏 😆

**Comment by XhmikosR** [comment]
@Johann-S: I added this myself. Can you rebase?

**Comment by XhmikosR** [comment]
Oh, and add the badge in README too.

**Comment by Johann-S** [comment]
Thanks @XhmikosR, I added the badge 😉

**Comment by XhmikosR** [comment]
@Johann-S: can you change it to shields.io?

**Pull request merged**
