### PR TITLE
Increases clickable area of the close btn on modals

### PR DESCRIPTION
**Pull request by andresgalante**
On alerts we increase the clickable area of the close btns to make them easier to click on devices where the pointer is coarse and improve accessibility.

This PR does 2 things:

1- Introduces the same concept for modals.
1- Changes the `align-items` to `flex-start` so the close btn always stays on the upper right corner when the `modal-title` text wraps.

I am not sure if this should be a global change on _close.scss

What do you think?

### CODE REVIEW

**Comment by mdo** [comment]
Possible to see a quick demo of the before/after by chance?

**Comment by andresgalante** [comment]
@mdo sure! here is the bug:
https://codepen.io/andresgalante/pen/NvopBJ?editors=1100

- close btn "X" centers instead of  been top right
- the x btn click are is smaller than a finger.

Here is the solution:
https://codepen.io/andresgalante/pen/MvLpZw?editors=1100

- The close btn in the top right corner
- the click area is larger

What do you you think?

**Review by patrickhlauke — APPROVED** [review]

**Comment by patrickhlauke** [comment]
Seems fine to me. @mdo ?

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
LGTM too, but I too wonder if we should change `close` instead of this specific case. Close seems to be using float currently.

**Review by mdo — APPROVED** [review]

**Pull request merged**
