### PR TITLE
Fix pseudo paddings and height

### PR DESCRIPTION
**Pull request by MartijnCuppens**
It turns out the height of date inputs (https://github.com/twbs/bootstrap/issues/18842) are increased by the padding on the pseudo elements and the fixed height of `1.5rem` of the `::-webkit-inner-spin-button`.

I've now reset these paddings and height instead of hacking with the line-height.

Codepen to play with: https://codepen.io/MartijnCuppens/pen/wvBLzvb?editors=1100

### CODE REVIEW

**Comment by mdo** [comment]
Holy shit, is this really the cause of all that pain? No requirement for fixed heights on form controls now? :D

**Comment by ysds** [comment]
On iOS (Chrome/Safari) there still seems to be a problem.

**Comment by MartijnCuppens** [comment]
@ysds, do you mean this: https://github.com/twbs/bootstrap/pull/30353?

**Comment by ysds** [comment]
> @ysds, do you mean this: #30353?

yep :)

**Comment by MartijnCuppens** [comment]
FYI, this patch is unrelated to #30353.

**Comment by ysds** [comment]
BTW should add date input example on our docs like [color](https://twbs-bootstrap.netlify.com/docs/4.3/forms/form-control/#color) if we support those.

**Review by ysds — APPROVED** [review]
LGTM

**Pull request merged**
