### PR TITLE
Make btn-block responsive

### LINKED ISSUE #20617: Responsive .btn-block
I love the responsive float classes in v4, but I was wondering if a similar concept could be applied to the `.btn-block` class. Here is a demo page which, as an example, has paging buttons. Without the convenience of a `.btn-[size]-block` class, you end up duplicating markup. (I only made the smallest size for the sake of the example.)

http://codepen.io/peiche/pen/wzvEyJ

### PR DESCRIPTION
**Pull request by pvdlg**
Fixes #20617

Generate `btn-{breakpoint}-block` classes so the block level button style can be applied for each viewport below a given breakpoint.

Handling the vertical spacing in a responsible would have generated a lot of css (see [comment](https://github.com/twbs/bootstrap/issues/20617#issuecomment-272058702).

So I opted to get rid of the `margin-top` for consecutive `btn-block` and instead mentionned in the docs to use the [spacing utilities](https://v4-alpha.getbootstrap.com/utilities/spacing/).
It seems also more consistent with the changes in the alpha 6 that now relied more on the spacing utilities.

### CODE REVIEW

**Comment by bgentry** [comment]
While I would love to see this feature, this is not really implemented in the spirit of v4 responsive helpers. For my app I ended up adding a `.btn-block-sm-down` that only applies at certain sizes:

```scss
@include media-breakpoint-down("sm") {
  .btn-block-sm-down {
    display: block;
    width: 100%;
  }

  // Specificity overrides
  input[type="submit"],
  input[type="reset"],
  input[type="button"] {
    &.btn-block-sm-down {
      width: 100%;
    }
  }
}
```

Not sure if the name I chose or `.btn-sm-down-block` would be more appropriate 🤷‍♂️

**Comment by vanduynslagerp** [comment]
AFIAK most of the responsive utilities do not use `up`/`down`,  and are formatted like `<target>-<breakpoint>-<value>`. The remaining `up`/`down` have been removed in #22113.

For example in [Flex utilities](http://v4-alpha.getbootstrap.com/utilities/flexbox/#enable-flex-behaviors): `d-md-flex` (target is `display`, breakpoint is `md`, value is `flex`).
This PR follow the same pattern: `btn-md-block` (target is `btn`, breakpoint is `md`, value is `block`).
In your example `btn-block-sm-down` is equivalent to `.btn-sm-block` as implemented in this PR.

Or is there something I'm misunderstanding?

**Comment by bgentry** [comment]
@vanduynslagerp I think you're right that _most_ of the responsive utilities do not have up/down variants. That does seem to be the direction of Bootstrap v4 though.

For this specific feature, one of the most clear use cases is to enable `btn-block` on small screen sizes. How would one un-block the button at larger sizes if the only classes available were `btn-sm-block`/`btn-md-block`/etc?

**Comment by vanduynslagerp** [comment]
@bgentry, I understand now (sorry I'm a bit slow sometimes).
It indeed works differently than other utilities in which the style is applied only on breakpoint **larger or equals** to the specified breakpoint while this PR apply the `block` for breakpoint **smaller**.

In order to have a similar approach we could define:
- `btn-{breakpoint}-block` that would set a button as `block` for breakpoint greater or equals to the specified breakpoint
- `btn-{breakpoint}-unblock` (or better name?) that would reset the styles in order to remove the `block`ness for breakpoint greater or equals to the specified breakpoint

Then it would work similarly to the utility classes (i.e. if you want to hide a component only on small breakpoint you would use "`d-none d-md-block`" and if you want a button to be `block` only on small breakpoint you would use "`btn-block btn-md-unblock`"). In addition that would also allow to do the opposite: having a non `block` button on small breakpoint that becomes `block` on larger breakpoint with `btn-md-block`.

I thought the second scenario is fairly uncommon and that it would be easier to have only one class. Plus `btn-unblock` seems a bit weird...But yes, it makes the logic different than the rest of the components.

I really have no opinion on what approach is best. I'd be happy to change the PR if the consensus is that the second approach is better for consistency reasons.

**Comment by mdo** [comment]
Closing as stale and incomplete:

- Removed a variable, thus making this a breaking change
- Changed behaviors of defined margin to margin utilities, also somewhat a breaking change

**Pull request closed without merging**
