### PR TITLE
Add float in make-col-span() mixin, not make-col()

### LINKED ISSUE #17512: Mixin make-col() adds float: left when this is not included in make-grid-columns()
Semantic mixins should yield the same results as the Bootstrap generated grid classes. The float should probably be added in make-col-span().

### PR DESCRIPTION
**Pull request by jfarthing84**
Fixes #17512.

### CODE REVIEW

**Comment by cvrebert** [comment]
Huh. Seems like `make-col()` might be dead code.

**Comment by jfarthing84** [comment]
http://v4-alpha.getbootstrap.com/layout/grid/#example-usage

**Comment by mdo** [comment]
`make-col()` was intended to avoid a lot of duplication in responsive grid systems—putting the `min-height` and `padding` on the other mixin would duplicate that each time you added a new tier.

**Comment by mdo** [comment]
Coming at you with fresh mixins in #19099.

**Pull request closed without merging**
