### PR TITLE
include jquery + tether deps for npm package. include gulp. Add .babe…

### PR DESCRIPTION
**Pull request by danieldram**
Hi there, 
This is my first pull request, I tried my best to follow your guidelines so please let me know if I should redo anything or fix anything up. 

Our team here is attempting to use Bootstrap 4 with an Angular 2 build. We are also using ES6 module loading syntax and as a result, when we "import 'bootstrap'" it is missing the jQuery and Tether deps. Because there is no global scope we can attach these deps to, we ended up editing your source to require jquery and tether where required. We're using this unofficial version with hopes that in the future release of Bootstrap 4, the npm package will provide those deps instead so we can alway ensure we have the latest stable release.

I included a test example in the /public folder and included an app.js that gets compiled by a gulp build. I added these as I wasn't sure how else to to include a relevant test case for the need for the deps to be apart of v4. I can resubmit a new pull request without these codes if you are okay with what I've submitted so far.

Please let me know if you require anything else or any changes from me in order to make this a successful pull request.

Thanks!
Daniel

### CODE REVIEW

**Comment by cvrebert** [comment]
Please get rid of Gulp.

**Comment by danieldram** [comment]
Will do! Is there any other changes needed?

**Comment by cvrebert** [comment]
Probably. I'll have to check this out locally since this modifies so many files.

**Comment by danieldram** [comment]
Thanks for taking the time to check Chris! Let me know and I'll do them all together for you. Cheers!

**Comment by danieldram** [comment]
Hey Chris, just wanted to follow up if there anything else other than the gulp file that'd I have to remove to continue with this pull request or if you have any suggestions on what else I can do to achieve the same goal of having the deps tagged along for the npm package. Cheers!

**Comment by mdo** [comment]
Punting on this as a stale PR that conflicts with just about every JS file we have. :grin:

**Pull request closed without merging**
