### PR TITLE
Event handler: replace deprecated function & merge `new Event` with `new CustomEvent`

### PR DESCRIPTION
**Pull request by GeoSot**
Note: According to https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent `initEvent` is deprecated

### CODE REVIEW

**Comment by XhmikosR** [comment]
I made `evt` a const.

Not sure about the second patch, though.

**Comment by GeoSot** [comment]
> Not sure about the second patch, though.

I have my doubts too. However Cause of:
* https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent#properties
*  https://stackoverflow.com/a/40795249
* https://blog.logrocket.com/custom-events-in-javascript-a-complete-guide/

in addition with this code :
https://github.com/twbs/bootstrap/blob/640542e6060c365c2e9cad7543822cf3d83045ae/js/src/dom/event-handler.js#L307-L317


I am pretty sure, we are fine, and we were already forcing both event types to accept custom properties

**Comment by XhmikosR** [comment]
I honestly don't know if the second patch is safe... I mean, it does look so since we aren't passing any custom data, but are we sure 100%?

**Comment by GeoSot** [comment]
You may can run this test on console.
I think it will solve any possible  questions.

```js
function getEvent(event, args){ //copy of our code
 const evt = new Event(event, { bubbles:true, cancelable: true })

    // merge custom information in our event
    if (typeof args !== 'undefined') {
      for (const key of Object.keys(args)) {
        Object.defineProperty(evt, key, {
          get() {
            return args[key]
          }
        })
      }
    }
return evt
}

myEvent=getEvent('testCustomRandom',{
relatedTarget:'our implementation nails custom properties',
randomProp: true
})


document.addEventListener('testCustomRandom', ev=>console.log(ev, 'relatedTarg '+ ev.relatedTarget))

document.dispatchEvent(myEvent)

```

On customEvent, we don't use the details property to pass data
And on both events, we are force creating properties (getters). 
So seems to be fine

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
