### PR TITLE
Hide the Copy buttons in docs when Flash is not available

### PR DESCRIPTION
**Pull request by tarebyte**
From issue #16269.

Feedback welcome!

### CODE REVIEW

**Comment by cvrebert** [comment]
Could you remove the `ZeroClipboard.min.map` file?

**Comment by cvrebert** [comment]
Please fix the JS coding style errors that are making the Travis build fail (see the Travis log for details).

**Comment by cvrebert** [comment]
So, when Flash is unavailable, the first time the user presses a Copy button, all the Copy buttons will disappear?

**Comment by tarebyte** [comment]
@cvrebert the user never sees the copy button if flash is not supported

**Comment by cvrebert** [comment]
Great, was just making sure since I'm not too familiar with ZeroClipboard.

**Comment by tarebyte** [comment]
@cvrebert is there a way to optimize the JS so that you can't see the button appear and then dissapear?

This is what I run into sometimes.

copy-button

**Comment by cvrebert** [comment]
@tarebyte Not that I know of.

**Comment by cvrebert** [comment]
Just tested this out; LGTM.

**Comment by tarebyte** [comment]
:sparkling_heart:

**Comment by cvrebert** [comment]
Thanks for this improvement! <3

**Comment by XhmikosR** [comment]
@tarebyte @cvrebert: there was a reason we sticked to that older version. And that is that the newer versions do not work with IE < 9.

**Comment by XhmikosR** [comment]
Personally, I'd appreciate a CC before this kind of stuff.

**Comment by cvrebert** [comment]
Sorry about the CC; didn't know you were interested.

> And that is that the newer versions do not work with IE < 9.

In retrospect, we should have documented that better...

**Comment by XhmikosR** [comment]
Well... I don't see where one could document this. IE 8 support was there,
and I purposely skipped updating this. You should find more info maybe in
the PR that introduce ZeroClipboard.

Will you do the revert or do you want me to make a PR?

**Comment by cvrebert** [comment]
PR would be faster, since this is low on my priority list.

**Pull request closed without merging**
