### PR TITLE
Extended collapse panel example description.

### LINKED ISSUE #18857: Explain .panel-collapse class in docs
It is in an "accordian" example, not a "collapse" example, which is how I missed it.

Maybe mention it in the 'collapse' section as well.

Thanks
Andrew

### PR DESCRIPTION
**Pull request by Pvanhesteren**
Extended the collapse panel example description, which should resolve #18857.

Please let me know if you have any suggestions.

### CODE REVIEW

**Comment by saturdaywalkers** [comment]
The new documentation does explain the "panel-collapse" class. It is easily missed as it is only in the example HTML (i.e. not mentioned in the text). 

For example, something like:  "The div's to be collapsed (e.g. panel-body, or panel-body and panel-footer) need a wrapper div: <div class="panel-collapse">. See the example below.

**Comment by Pvanhesteren** [comment]
@saturdaywalkers, good point. I have updated the introduction according to your suggestion. Please let me know what you think :smile:

**Comment by aavmurphy** [comment]
Sorry for the delay. Looks good! Andrew.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Pull request closed without merging**
