### PR TITLE
Add `space-evenly` option for `justify-content`

### PR DESCRIPTION
**Pull request by ed1nh0**
`justify-content: space-evenly;`
The items are evenly distributed within the alignment container along the main axis. The spacing between each pair of adjacent items, the main-start edge and the first item, and the main-end edge and the last item, are all exactly the same.

[MDN justify-content](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content)

### CODE REVIEW

**Review by ffoodd — APPROVED** [review]
LGTM. @MartijnCuppens @mdo, any thought?

**Comment by XhmikosR** [comment]
What's the size diff? bundlewatch does not run for fork PRs.

**Comment by ffoodd** [comment]
Tested locally:
1. `bootstrap.css` increased from 21.75Kb to 21.83Kb
2. `bootstrap.min.css`, from 20.26Kb to 20.33Kb

Not sure about my procedure or environment since I also have a very little increase in reboot, which doesn't import utilities.

**Comment by XhmikosR** [comment]
Assuming you run `npm run dist` before comparing, both on master and on this branch, the comparison will be fair.

**Comment by ffoodd** [comment]
Re-run things and I think I forgot to run `dist` on `master`. Same things for reboot, fresh results for this PR:
- `boosted.css` increased from 21.79Kb to 21.83Kb (+0.04Kb)
- `boosted.min.css` from 20.29Kb to 20.33 Kb (+0.04Kb)

**Review by MartijnCuppens — APPROVED** [review]
Makes sense to add this, thanks!

**Pull request merged**
