### PR TITLE
Add margin-bottom to .progress

### PR DESCRIPTION
**Pull request by marcoscv-work**
For https://github.com/twbs/bootstrap/issues/22916

### CODE REVIEW

**Comment by afuno** [comment]
It seems to me it is superfluous. For these tasks there are corresponding helpers: https://v4-alpha.getbootstrap.com/utilities/spacing/

**Comment by marcoscv-work** [comment]
Spacing utilities are great! 💃

But I think we should care more the HTML markup changes between versions, if not the jump from BS3 to BS4 will be more complex.

Tanks!

**Comment by afuno** [comment]
@marcoscv-work There is nothing complicated in this migration. In addition, no one prevents you from rewriting this class in person. No need to spoil the logic of this version.

Do you know about migration Panel to Card? Again, this is purely my opinion. And this is a crazy idea. One should stick to one course. And the use of helpers - it's cool.

**Comment by marcoscv-work** [comment]
Ok guys! thanks a lot, PR closed! 👍

**Pull request closed without merging**
