### PR TITLE
Update browser support

### PR DESCRIPTION
**Pull request by mdo**
I'd like to be more aggressive in our browser support—this is a first pass at it. Looking at our compiled CSS, we've added a ton. :sob: This list has largely been out of date aside from the dropping of IE9/10. I'm thinking about this because of the number of flex properties that require vendor prefixing—it literally triples line of flex code you write. This knocks down some of it.

### CODE REVIEW

**Comment by mdo** [comment]
Fwiw, worst case scenario after merging something like this is that we have to support older browsers, which isn't a breaking change. On the flip side, wanting to drop older browsers is a breaking change.

**Comment by yasinkocak** [comment]
Drop older browsers

**Comment by Johann-S** [comment]
We are still in Alpha so breaking changes it's something which can happen, I'm in favor of dropping old browsers, maybe you'll find interesting information here : http://caniuse.com/#feat=flexbox

**Comment by lorvent** [comment]
eventhough i love dropping support for old browsers for obvious reasons,
we develop products and customers with old browsers will cry now.... (i really hope everyone ditches IE and moves to firefox/chrome)

**Comment by Superpencil** [comment]
To summarise caniuse as @Johann-S stated: 12.29% of current active internet users do not have working flexbox support, including the entire Indian subcontinent

**Comment by Mustafa-Online** [comment]
Supporting old browsers is a good thing in some aspects, especially Flex property, because it is the core of the framework now 😃

**Comment by mdo** [comment]
v3 will handle all the older browsers out there if you need to support them. We'll get a v3 quality of life update out after v4 ships. That's always been the plan :).

**Comment by andrerom** [comment]
@mdo Based on both support data and usage data in http://caniuse.com/#feat=flexbox, and considering the two years that has passed since alpha 1. Shouldn't this rather bump to `Explorer >= 11` and `Edge >= 14` for the beta?

**Comment by Herst** [comment]
@andrerom #21416 was when the decision for dropping IE9 but not IE10 was made. @mdo said in that thread that supporting IE10 hasn't been an issue at all.

**Pull request merged**
