### PR TITLE
Give better description of IE9 transparent click bug & workaround

### PR DESCRIPTION
**Pull request by cvrebert**
CC: @mdo for review

### CODE REVIEW

**Comment by XhmikosR** [comment]
Have you checked if clean-css changes that to `transparent`?

**Comment by cvrebert** [comment]
Apparently `clean-css@3.4.5` does rewrite it to `transparent`... :scream: 
Wanna file a bug? :sweat_smile:

**Comment by XhmikosR** [comment]
https://github.com/jakubpawlowicz/clean-css/issues/699

**Comment by XhmikosR** [comment]
On a side note, does that other comment we have in Gruntfile still apply?

```
        // TODO: disable `zeroUnits` optimization once clean-css 3.2 is released
        //    and then simplify the fix for https://github.com/twbs/bootstrap/issues/14837 accordingly
```

**Comment by cvrebert** [comment]
Yes, it does: https://github.com/twbs/bootstrap/blob/f564c683f776173c1dc828cc6095358c0fd4d74c/scss/_tables.scss#L118

**Comment by XhmikosR** [comment]
But it's commented out there :S

If we still need it, we should check clean-css' advanced properties toggling and set this off that way.

**Comment by cvrebert** [comment]
> But it's commented out there :S

Not anymore :smile: 7d766e4a94299f811e8eab522bfb128a350cca4a

**Comment by cvrebert** [comment]
Filed #18144 to track the zeroUnits TODO.

**Comment by cvrebert** [comment]
@XhmikosR Anyway, does this PR LGTY? It just updates the comment. We can open another issue for the clean-css problem.

**Comment by XhmikosR** [comment]
Yeah it's fine. Already tracking #18144; I'll see when I'll have some time to look into it.

**Comment by cvrebert** [comment]
Filed #18145 to track the clean-css problem.

**Pull request merged**
