### PR TITLE
Use color variables consistently

### PR DESCRIPTION
**Pull request by Kovah**
Replaces some raw colors with the appropriate color variables where it makes sense.
Examples:
- `#eee` will be replaced by `$gray-lighter` (#eceeef)
- `#333` will be replaced by `$gray-dark` (#373a3c)

The two colors `#fff` and `#ddd` are not replaced by a variable. In my opinion it would make sense to add a new variable for `#ddd` because it's widely used but I wanted to ask first. Also the naming of the variable needs to be discussed.
# 

Reference: #14840

### CODE REVIEW

**Comment by mdo** [comment]
Merged this manually given the conflicts. Only thing I took out was the `$code-color` change since that isn't meant to be red but a pink-ish color. Thanks!

**Comment by Kovah** [comment]
Great! 🎉 

Any idea how the many `#ddd`-like colors will be handled?

**Comment by mdo** [comment]
No clue honestly! 😆

**Comment by Kovah** [comment]
Okay haha! I will take a look at it, maybe I find a suitable solution for this. 😃

**Pull request merged**
