### PR TITLE
Docs: Add Callout to Stacks Helper page about limited flexbox gap support

### LINKED ISSUE #34737: Stacks with Gaps don't have gaps in all supported browsers (e.g. iOS 12)
The new Stacks helpers (https://getbootstrap.com/docs/5.1/helpers/stacks/) are neat, but they don't work in all Bootstrap-supported browsers due to using Flexbox Gap which doesn't have wide browser support. https://caniuse.com/flexbox-gap

iOS 12.5.4 screenshot

The Gap Spacing Utilities (https://getbootstrap.com/docs/5.1/utilities/spacing/#gap) are fine in iOS 12.5.4 since they use Grid Gap which is better supported.
iOS 12.5.4 screenshot

I wonder if there should be a compatibility warning added to the Stacks docs page.

### PR DESCRIPTION
**Pull request by coliff**
Fixes: #34737

Preview screenshot from localhost
localhost_9001_docs_5 1_helpers_stacks_(iPad Pro)

### CODE REVIEW

**Comment by XhmikosR** [comment]
If this only for one page, it doesn't need to be a partial

**Comment by coliff** [comment]
Do you think it's needed on the Gap utilities page too?
https://getbootstrap.com/docs/5.1/utilities/spacing/#gap
I personally don't think it's needed there as that section only talks about Grid gap (not flexbox gap)
cc @mdo

**Comment by XhmikosR** [comment]
I'll defer this to @mdo, but if it's only one place then we don't need the partial :)

**Comment by mdo** [comment]
Yeah we can skip the partial and do just the one page :)

**Review by mdo — APPROVED** [review]
Pre-approving for when the partial is removed :).

**Comment by mdo** [comment]
Thank you both!

**Pull request merged**
