### PR TITLE
v5: Add cursor util

### LINKED ISSUE #23709: Cursor pointer Utility
Hello, It will be nice if someone could add a class that let you point the cursor.
example:

```
.c-pointer {
 cursor: pointer;
}
```

### PR DESCRIPTION
**Pull request by mdo**
v5 version of #30562. Fixes #23709.

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
Gonna stick with my opinion in https://github.com/twbs/bootstrap/issues/23709#issuecomment-571290182. A lot of people want this, but no one seems to be able to define a use case for the `cursor-pointer` utility.

I'm afraid developers will just abuse this utility and add this class to elements which aren't focusable with keyboard navigation.

**Comment by mdo** [comment]
> A lot of people want this, but no one seems to be able to define a use case for the `cursor-pointer` utility.

Good point, just commented again on that issue.

**Comment by ffoodd** [comment]
I agree with @MartijnCuppens here. Cursors are usually good natively, and a very precious indicator of browser and OS interaction layer.

With these utilities, it'd be too easy to mess things up. If something is wrong with our cursors, those styles should belong to reboot.

Pointer events and user-select can be really helpful since they affect behaviour, but cursors can be really misleading.

**Comment by mdo** [comment]
Coming back to this after shipping the interactions and `role="button"` in v4.5, thinking this needs to be updated to include that instead, right?

**Comment by mdo** [comment]
Replaced by #31040.

**Pull request closed without merging**
