### PR TITLE
Allow individual grid classes to override `.row-cols`

### LINKED ISSUE #33530: Column CSS doesn't override row column default css when row-cols-[breakpoint]-[x] is used.
**OS:** Windows 10
**Browser:** Chrome, Firefox, Edge latest
**Version:** 5 beta 3

**Area:** Grid
**Apparent Problem:** Column CSS doesn't override row column default css when row-cols-[breakpoint]-[x] is used.
**My Expectation:** Column specific classes should always override row class
**Example:** [CodePen Example](https://codepen.io/Lacutah/pen/NWdddOG)

The current order of CSS appears to be wrong:
```
.row-cols-[x]
.col-[x]
.row-cols-[breakpoint]-[x]
.col-[breakpoint]-[x]
```
I would expect it to be:
```
.row-cols-[x]
.row-cols-[breakpoint]-[x]
.col-[x]
.col-[breakpoint]-[x]
```

### PR DESCRIPTION
**Pull request by lacutah**
closes #33530

### CODE REVIEW

**Comment by mdo** [comment]
As far as I can tell, I don't think this fixes the issue? https://codepen.io/emdeoh/pen/MWJBPBG?editors=1100

**Comment by lacutah** [comment]
> 
> 
> As far as I can tell, I don't think this fixes the issue? https://codepen.io/emdeoh/pen/MWJBPBG?editors=1100

That pen/editor isn't using the updated CSS this fix addresses? I updated:  https://codepen.io/Lacutah/pen/xxgaxQV

As a followup question / potential breaking but perhaps even better implementation:
I intentionally let ```row-cols-*``` override ```.col``` **because the existing documentation shows that** - however ```row-cols-*``` automatically applies column css to the direct children of the row. In effect, ```.col``` when nested in a ```.row-cols*``` does NOT override like the ```.col-*``` classes do and is actually redundant when used under ```.row-cols-*```.

The way I (could) see it, if you specify ```.col``` under a ```.row-cols-*``` row, it should **also** act as an override but currently doesn't. It would be more consistent with the idea that ```.row-cols-*``` is a default, but has a higher potential of being more of a breaking change because of the existing examples. The documentation should also be updated to indicate that all direct children of a ```.row-cols-*``` row automatically become columns (this is currently the case, but not obvious because of the documentation showing ```.col``` or a variant being used on each column...)

Should this proposed fix also address ```.col``` so it overrides the ```.row-cols-*```? I'd be happy to "correct" that and the examples as well.

**Comment by ffoodd** [comment]
Made two separate pens to help review:
1. Using alpha3: https://codepen.io/ffoodd/pen/WNpepvY
2. Using this PR: https://codepen.io/ffoodd/pen/PopYpZR

So I can confirm it fixes the issue.
@lacutah Please be patient as we're all volunteers here; and make sure to provide an easy way to check what you did :) Some PR get stuck because they require too much time to review.

**Review by ffoodd — APPROVED** [review]

**Comment by lacutah** [comment]
@ffoodd, - totally get it, honestly not trying to cause headache and am incredibly appreciative of all the hard work that happens! Projects like this make my job easier! Maybe I don't know where to look, but I have no way to see what's going on with all the volunteers nor an expectation of what a "normal" timeline is like on this project - all I knew is the (two) bugs / requests were hot for a minute, then crickets - so I "pinged" it LOL.

I look forward to helping out on other issues in the future, and if I can make it easier for you (all) by putting up codepens demonstrating the fixes, then I'm very happy to do so! We all benefit from open source every day - I think it's pawsome to be able to "give back" as well when I have the bandwidth!

XXX **Would you like me to create a separate bug or discussion regarding the potentially better implementation mentioned in my very long comment above?** I don't want to do the work if it's not wanted / going in the wrong direction.

**Comment by ffoodd** [comment]
A discussion is appropriate I guess 👌

**Review by mdo — APPROVED** [review]

**Comment by mdo** [comment]
> Made two separate pens to help review:
> 
> 1. Using alpha3: https://codepen.io/ffoodd/pen/WNpepvY
> 2. Using this PR: https://codepen.io/ffoodd/pen/PopYpZR

These two examples are amazing, super helpful in showing this bug. I'll likely want to include them in our blog post for v5.0.2!

**Comment by ffoodd** [comment]
> I'll likely want to include them in our blog post for v5.0.2!
Make sure to credit @lacutah for the initial pen :)

**Pull request merged**
