### PR TITLE
V4 dev backports and updates

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
It seems BrowserStack tests fail. I'm gonna restart them but if it persists we need to figure out why they fail.

**Review by MartijnCuppens — APPROVED** [review]

**Comment by XhmikosR** [comment]
@Johann-S can you check why Safari keeps failing on BrowserStack?

```
Mobile Safari 11.0.0 (iOS 11.0.1) modal should restore focus to toggling element when modal is hidden after having been opened via data-api FAILED
	toggling element is once again focused
	Expected: true
	Actual: false
	
............
Mobile Safari 11.0.0 (iOS 11.0.1) modal should not restore focus to toggling element if the associated show event gets prevented FAILED
	focus returned to toggling element
	Expected: true
	Actual: false
```

**Comment by XhmikosR** [comment]
@Johann-S I pinpointed the test failures to qunit 2.9.3. Can you check if we need to adapt those 2 tests and the changelog https://github.com/qunitjs/qunit/compare/2.9.2...master

For the time being I locked qunit to 2.9.2.

**Comment by Johann-S** [comment]
I don't see anything special in the new release of QUnit 😲 that's pretty weird our unit tests failed because of that

**Comment by XhmikosR** [comment]
I just pushed qunit to 2.9.3. Let's see if it will fail again.

**Comment by XhmikosR** [comment]
Yup, definitely fails @Johann-S

**Pull request merged**
