### PR TITLE
Update template.html

### PR DESCRIPTION
**Pull request by efender**
fix viewport for high pixel density displays

### CODE REVIEW

**Comment by cvrebert** [comment]
Explanation please?

**Comment by patrickhlauke** [comment]
Ideally, could you provide an example (with URL and screenshot) of where the current standard viewport meta causes problems on high-dpi devices, and what your proposed fix tries to achieve? I'm currently not aware of any issues (for instance, using a Bootstrap site on iPhone and MacBook with Retina display).

**Comment by efender** [comment]
**Android** 4.2.2
**Display:** 720px x 1280px, pixel ratio: 2
**Default bootstrap theme** (v3.3.2)
**Browsers:** Chrome, FF, Yandex browser, UC browser - last versions

**Expected:**
vertical orientation (720px) - extra small breakpoint (720px)
horizontal orientation (1280px) - large breakpoint (1280px)

**Actual:**
vertical orientation (720px) - extra small breakpoint (360px)
horizontal orientation (1280px) - extra small breakpoint (640px)

The snippet fixes it, for this device viewport will be:
```html
<meta name="viewport" content="width=device-width,initial-scale=0.5,minimum-scale=0.5">
```

Example: http://efender.ru/github/bs-fix-viewport/

**Comment by efender** [comment]
Sorry for close )

**Comment by patrickhlauke** [comment]
Unless I'm misunderstanding, you're trying to force the viewport's initial zoom to match physical pixel size? In that case, I'm afraid that goes against the whole point of using width=device-width, which instructs the browser to adopt what the browser/device manufacturer consider to be the "ideal viewport". This is the foundation of responsive web design, and trying to code actively against that (by effectively forcing a view that tries to set 1 css px = 1 device hardware pixel) is not the way to go.

**Pull request closed without merging**
