### PR TITLE
Handle non-empty whitespace textContent in Tooltip trigger

### PR DESCRIPTION
**Pull request by nwalters512**
If a Tooltip trigger has non-empty `textContent` that consists solely of whitespace, Bootstrap will remove the `title` but won't add an `aria-label` with the contents of `title`. Here's a reproduction of this: https://jsfiddle.net/nwalters512/7y8edzxr/7/. This is a poor experience for folks using screen readers, as they won't have any accessible label for the trigger.

This PR changes the JS to check the falseyness of `textContent.trim()` instead of `textContent` directly.

### CODE REVIEW

**Review by hebertcisco — COMMENTED** [review]
It was really helpful to use the `String.prototype.trim()` method to handle white space, it's the right thing to do.

**Comment by GeoSot** [comment]
Thank you, @nwalters512 . 
I am not sure is valid to auto-trim given strings, as it may be given on purpose (yes, of course, out of logic, as many other things I cannot understand myself)

As handy it may be, please try to add some tests to support your PR, and I would suggest making this change easy to applied everywhere. So probably, the best place is the TemplateFactory

**Comment by nwalters512** [comment]
@GeoSot I can try adding some tests! Re: your recommendation to make this change in `TemplateFactory`, it's not clear to me how that would work, as none of the existing code in `_fixTitle()` is touching that. It's also not clear to me how much of this is actually reusable - this "fix title" seems pretty specific to tooltips.

**Comment by GeoSot** [comment]
@nwalters51 I have understood your suggestion and the cause of the issue.
 I am sorry for the misleading answer as my previous comment was out of topic
 
 Many thanks for your help here

**Review by GeoSot — APPROVED** [review]

**Review by julien-deramond — APPROVED** [review]

**Pull request merged**
