### PR TITLE
Fixes #15405: Fix .dropdown-backdrop on navbar dropdowns for touch devices.

### LINKED ISSUE #15405: .navbar-nav dropdowns can only be closed by tapping their .dropdown-toggle on touch devices
On the mobile navbar, dropdowns are set to `position: static` to override the `absolute` position they normally have. However this prevents the dropdown from having a z-index. The z-index is necessary to ensure the dropdown's contents appear above the `.dropdown-backdrop` on mobile.

To fix, set the mobile dropdowns to `position: relative`;

``` scss
  @media (max-width: @grid-float-breakpoint-max) {
    // Dropdowns get custom display when collapsed
    .open .dropdown-menu {
      position: relative;
      …
    }
  }

### PR DESCRIPTION
**Pull request by elstgav**
Fixes #15405

### CODE REVIEW

**Comment by cvrebert** [comment]
The `position: relative` change causes the page to be shifted down when expanding a dropdown: https://github.com/twbs/bootstrap/issues/15405#issuecomment-76119649
In light of this bug, I don't think this PR is currently acceptable.

**Comment by cvrebert** [comment]
@elstgav Any thoughts regarding my comment?

**Comment by elstgav** [comment]
@cvrebert See my [comment in #15405](https://github.com/twbs/bootstrap/issues/15405#issuecomment-81960864)

**Comment by cvrebert** [comment]
Closing then. Thanks for the attempt though!

**Pull request closed without merging**
