### PR TITLE
Replace Lorem Ipsum placeholder text with more representative (or at least english language) text

### PR DESCRIPTION
**Pull request by patrickhlauke**

### CODE REVIEW

**Comment by XhmikosR** [comment]
The backport will be a PITA, but I like the changes from a quick look :)

**Comment by patrickhlauke** [comment]
> The backport will be a PITA, but I like the changes from a quick look :)

yeah i'm "happy" to do the backport myself. and yes, it'll be manual copy/paste job of the content. hard part i find is inventing some semi-meaningful yet meaningless filler content...

**Comment by patrickhlauke** [comment]
Got some more to tackle, will set to review once I think I got them all...

**Comment by XhmikosR** [comment]
Did you check the newly added files from RTL @patrickhlauke ?

**Comment by patrickhlauke** [comment]
@XhmikosR urgh, no i had not. ok...will go hunting later today

**Comment by patrickhlauke** [comment]
> Did you check the newly added files from RTL @patrickhlauke ?

apart from the cheatsheet which i didn't have when i started, don't think there's anything else to fix for now - can't really help with checking the arabic (?) content, could do with somebody fluent in the language to give it a double-check to see that it's not just complete gibberish (and that it's nothing offensive or whatever)

**Review by mdo — APPROVED** [review]

**Comment by patrickhlauke** [comment]
Just to draw attention here (as it may be lost in one of the commit messages) that for some of the more extensive chunks of lorem ipsum I instead used sentences from http://katyperryipsum.com/ (with the SFW option turned on) ... I assume that's acceptable.

**Pull request merged**
