### PR TITLE
[Fix #17371][V4] Deactivating dropdown links in nav tab

### LINKED ISSUE #17371: Dropdown items in nav tabs can get stuck in .active mode
bug bootstrap alpha v4 - http://v4-alpha.getbootstrap.com/components/navs/#javascript-behavior When you press a button/tab in the dropdown, try another tab and go back, you will see that the button/tab under the dropdown hasn't been deactivated. I was implementing this in a project and came across this bug.

EDIT: It's worse.. You can't even 'reactivate' the tab. So it's stuck on 'active' mode and won't change your content in the tab view

### PR DESCRIPTION
**Pull request by matt-hernandez**
This fixes issue #17371 

Unit tests are included. If there is any feedback, feel free to let me know.

### CODE REVIEW

**Comment by haBuu** [comment]
This bug happens with normal tab links also. Everytime you click a link, active class is added to it and it can't be clicked again because the active class is never removed. Meaning you can only visit every tab once.

**Comment by matt-hernandez** [comment]
@haBuu I'm trying to recreate the behavior you're talking about, but I can't seem to do it. Can you post a JS Fiddle or other example?

**Comment by haBuu** [comment]
https://jsfiddle.net/qz8a1ay5/

**Comment by twbs-lmvtfy** [comment]
Hi @haBuu!

You appear to have posted a live example (https://fiddle.jshell.net/qz8a1ay5/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 43, column 3 thru column 8: Start tag ```` body ```` seen but an element of the same type was already open.
* line 47, column 12 thru column 92: An element with ```` role=tab ```` must be contained in, or owned by, an element with ```` role=tablist ````.
* line 48, column 12 thru column 92: An element with ```` role=tab ```` must be contained in, or owned by, an element with ```` role=tablist ````.
* line 52, column 12 thru column 92: An element with ```` role=tab ```` must be contained in, or owned by, an element with ```` role=tablist ````.
* line 53, column 12 thru column 92: An element with ```` role=tab ```` must be contained in, or owned by, an element with ```` role=tablist ````.
* line 57, column 12 thru column 92: An element with ```` role=tab ```` must be contained in, or owned by, an element with ```` role=tablist ````.
* line 58, column 12 thru column 92: An element with ```` role=tab ```` must be contained in, or owned by, an element with ```` role=tablist ````.
* line 63, column 1 thru column 7: Saw an end tag after ```` body ```` had been closed.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by matt-hernandez** [comment]
@haBuu I think this is what you were going for: https://fiddle.jshell.net/a_matt_appeared/uvcos7q7/

This is better, but still not working.

In this case, I'm not sure if this behavior will be supported by v4 out of the box. From what I understand, navs are meant to be static objects where there is only one `.nav-tabs` or `.nav-pills` per group of tabs.

The use of `.nav-pills` in this fiddle is more like pagination, and we have three copies. I don't think this is what the BS team intends them to be for.

But if you have an example where this worked in v3, post it.

**Comment by twbs-lmvtfy** [comment]
Hi @matt-hernandez!

You appear to have posted a live example (https://fiddle.jshell.net/a_matt_appeared/uvcos7q7/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 57, column 3 thru column 8: Start tag ```` body ```` seen but an element of the same type was already open.
* line 95, column 1 thru column 7: Saw an end tag after ```` body ```` had been closed.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by matt-hernandez** [comment]
Updated fiddle to satisfy @twbs-lmvtfy 

https://fiddle.jshell.net/a_matt_appeared/uvcos7q7/

**Comment by haBuu** [comment]
Here is a working v3 version. http://jsfiddle.net/qz8a1ay5/5/

**Comment by twbs-lmvtfy** [comment]
Hi @haBuu!

You appear to have posted a live example (http://fiddle.jshell.net/qz8a1ay5/5/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 46, column 9 thru column 87: An element with ```` role=tab ```` must be contained in, or owned by, an element with ```` role=tablist ````.
* line 47, column 9 thru column 87: An element with ```` role=tab ```` must be contained in, or owned by, an element with ```` role=tablist ````.
* line 51, column 9 thru column 87: An element with ```` role=tab ```` must be contained in, or owned by, an element with ```` role=tablist ````.
* line 52, column 9 thru column 87: An element with ```` role=tab ```` must be contained in, or owned by, an element with ```` role=tablist ````.
* line 56, column 9 thru column 87: An element with ```` role=tab ```` must be contained in, or owned by, an element with ```` role=tablist ````.
* line 57, column 9 thru column 87: An element with ```` role=tab ```` must be contained in, or owned by, an element with ```` role=tablist ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by matt-hernandez** [comment]
@cvrebert Any feedback on this?

**Comment by cvrebert** [comment]
@matt-hernandez Not from me. @fat is the one to run this by.

**Comment by mdo** [comment]
Would love a review here from someone :).

/cc @Johann-S @bardiharborow (please tell me to stop pinging y'all if this gets too annoying 😆)

**Comment by Johann-S** [comment]
For me everything is fine @mdo (and that's ok to ping me don't worry 😃)

**Review by bardiharborow — APPROVED** [review]

**Review by Johann-S — APPROVED** [review]

**Comment by mdo** [comment]
<3 thanks everyone

**Pull request merged**
