### PR TITLE
refine deprecated holder.js color syntax

### PR DESCRIPTION
**Pull request by m5o**
* refine deprecated holder.js color syntax
  * remove `#55595c:#373a3c` which is only used once
* harmonize with all other holder.js examples

### CODE REVIEW

**Comment by XhmikosR** [comment]
Is this the only case?

**Comment by XhmikosR** [comment]
Please check the preview, it seems broken here https://deploy-preview-27400--twbs-bootstrap4.netlify.com/docs/4.1/components/card/#image-overlays

**Review by XhmikosR — CHANGES_REQUESTED** [review]
Please revert the `p` removal.

**Comment by m5o** [comment]
> Is this the only case?

yes

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
