### PR TITLE
Add .row-cols-{sm/md/lg/xl}-none

### PR DESCRIPTION
**Pull request by ZhangChengLin**
Add .row-cols-{sm/md/lg/xl}-none 
Meeting the need when quantity is no longer needed

### CODE REVIEW

**Comment by XhmikosR** [comment]
Thanks, but we don't need 2 PRs.

**Comment by zhangchenglin** [comment]
> Thanks, but we don't need 2 PRs.

yes
 
This is for 2 different branches. I see that the structures of v4 and v5 are different, so two PRs at different positions were submitted.
And I don't know the way I use, can they merge into one PR.

**Comment by XhmikosR** [comment]
We can cherry pick the patch if we decide we want to backport it.

**Comment by zhangchenglin** [comment]
> We can cherry pick the patch if we decide we want to backport it.


The network is very slow. It took me 18 minutes to refresh and see your information. Thank you, I got it.

**Pull request closed without merging**
