### PR TITLE
Docs: update documentation js examples, using es6

### PR DESCRIPTION
**Pull request by GeoSot**
edit: 
Ref: https://github.com/twbs/bootstrap/issues/32096

### CODE REVIEW

**Comment by mdo** [comment]
@GeoSot Is there anyway we can lint these snippets? I believe we have an issue open to suggest this, but I'm not sure of how we could accomplish it off the top of my head.

**Comment by rabuckley** [comment]
> Is there anyway we can lint these snippets?

A few thoughts:

As mentioned in https://github.com/twbs/bootstrap/issues/32096, [eslint-plugin-markdown](https://github.com/eslint/eslint-plugin-markdown) looks promising. The equivalent for HTMl seems to be [eslint-plugin-html](https://github.com/BenoitZugmeyer/eslint-plugin-html). Without trying, *these seem the best solution*.

Alternatively a regex something like:

```regex
```js((.|\n)*)```
```

should(?) match JS code blocks in markdown.

And for HTML:

```regex
<script>((.|\n)*?)<\/script>
```

could work with a bit of tweaking.

You could then run the matched strings through ESLint to flag issues. (See https://eslint.org/docs/developer-guide/nodejs-api#linter)

**Comment by GeoSot** [comment]
I made a try, but any suggestions here are welcome, as I don't have the expertise

**Comment by rabuckley** [comment]
Had a quick look through and LGTM. The linter seems to work pretty well too.

The `<!-- eslint-skip -->`  comments will be outputted into the site - not really an issue but might be nice to avoid if there's a way?

**Review by mdo — APPROVED** [review]
Love it, thanks for this!

**Pull request merged**
