### PR TITLE
replace static vars for _type.scss

### PR DESCRIPTION
**Pull request by yordis**
### Testing Notes

- Verify http://localhost:9001/docs/4.3/content/typography styles are being applied correctly

Related to #30494

### CODE REVIEW

**Comment by ffoodd** [comment]
I don't think this is the way to go for CSS properties, but I'd like @MartijnCuppens and @mdo opinion. Let me explain myself!

In this PR, the generated output will be bigger thant the original one; and custom properties don't make any sense to me in that particular case.

Custom properties are *not* similar to Sass variables, they can't be a simple replacement. Using them like you did in here only helps users that don't want to compile code through Sass, and doesn't solve any issue. This results in a code bloat in generated output.

**As of now, I think the goal should be to decrease file size.** Thoughts, anyone?

**Comment by XhmikosR** [comment]
> **As of now, I think the goal should be to decrease file size.** Thoughts, anyone?

Definitely! 💯

**Comment by ffoodd** [comment]
@XhmikosR Are we able to run the Bundlesize action on PR like this one? Would definetely help :)

**Comment by XhmikosR** [comment]
You can see the result in tests https://github.com/twbs/bootstrap/pull/30495/checks?check_run_id=550704973#step:10:9

**Comment by MartijnCuppens** [comment]
> Custom properties are not similar to Sass variables, they can't be a simple replacement. Using them like you did in here only helps users that don't want to compile code through Sass, and doesn't solve any issue. This results in a code bloat in generated output.

Yup, I agree. Gonna close this.

**Pull request closed without merging**
