### PR TITLE
Docs: Add link to Korean translation

### PR DESCRIPTION
**Pull request by gitaeks**
[repository] : https://github.com/kimsQ/bs4-translation
[site] : http://bootstrap4.kr

### CODE REVIEW

**Comment by cvrebert** [comment]
CC: @hnrch02 @juthilo

**Comment by hnrch02** [comment]
The translation seems rather incomplete on some pages. Not sure if that was intended or not. Other than that I don't quite know what I'm supposed to comment on here 😁

**Comment by gitaeks** [comment]
@hnrch02 , While studying BS4, I have created BS4 korean translation website to make some contributions to BS4 community. 
Currently the website construction is completed and now actual translations are in progress. I am expecting a week for the translations to be completed.
I will post more comments when the translations are finished.

**Comment by mdo** [comment]
I'd honestly advise against translating the docs right now. We're still in alpha and I have a couple PRs open that significantly change key pages. I've no problem linking to it if it's clearly labeled work in progress or potentially out of date; don't want y'all to waste time and effort.

**Comment by gitaeks** [comment]
I understood.
Currently, I'm continuously studying BS4, and I will finish the translation task when the v4.0.0 release is imminent.

 I marked 'Translation progress' and 'alpha'  condition as below.
If our Korean translation website is linked in the BS4 official document, it will be an honor for us as BS users.

image


http://bootstrap4.kr/

**Comment by mdo** [comment]
If you can resolve the conflict, I'll get this merged :).

**Comment by mdo** [comment]
Closing for now given conflicts. Please feel free to open a new PR if it's good to go! <3

**Pull request closed without merging**
