### PR TITLE
v5: Drop hover query

### PR DESCRIPTION
**Pull request by mdo**
We deprecated it a long time ago, so should be good to clear this out.

- [x] Delete deprecated Sass code
- [x] Add to migration docs page

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
@mdo, why did you keep the `hover` and `hover-focus` mixins here?

**Comment by mdo** [comment]
For simplicity's sake perhaps? Can't remember exactly, other than the fact that I believe we use them in a handful of places right now. We can likely get rid of them though if you think it's an improvement.

**Comment by MartijnCuppens** [comment]
A hover mixin which just prints a `:hover` block feels a bit useless. I think we can also drop the `hover-focus` mixin, this might be a little shorter but I guess we'll end up pretty fast with a mixed usage of the mixin and just css.

**Comment by XhmikosR** [comment]
Note to self, this needs a proper rebase.

**Comment by mdo** [comment]
Just pushed another commit that should have tests passing shortly. Should be ready for review after that, @twbs/css-review.

**Review by MartijnCuppens — APPROVED** [review]
I just rebased & removed some additional documentation about why we used to have the hover mixin: https://getbootstrap.com/docs/4.3/getting-started/browsers-devices/#sticky-hoverfocus-on-ios

LGTM now

**Review by ysds — CHANGES_REQUESTED** [review]

**Review by ysds — APPROVED** [review]

**Comment by ysds** [comment]
LGTM 👍

**Pull request merged**
