### PR TITLE
Add two new meta tags for Algolia

### PR DESCRIPTION
**Pull request by XhmikosR**
@s-pace: here it is. Can you tell me what we need to change in our JS file with these in place?

Note that `docs_version` isn't our full version since usually we only need to change paths for major/minor versions, see https://github.com/twbs/bootstrap/blob/v4-dev/_config.yml#L38

### CODE REVIEW

**Comment by s-pace** [comment]
This is perfect, we will not crawl the v3 since they have another dedicated config and that the layout is not the same.

PR pending ^

**Comment by XhmikosR** [comment]
So @s-pace, do we still need to use the `facetFilters` and pass the version there too?

**Comment by s-pace** [comment]
Yes you do @XhmikosR

**Comment by XhmikosR** [comment]
So, how is this gonna work, @s-pace? Say we release 4.3 and we change paths again or not. Will your tool grab this automatically?

**Comment by XhmikosR** [comment]
Thanks for the help @s-pace!

We'll test this after you merge your PR in https://twb-bootstrap4.netlify.com/

**Review by mdo — APPROVED** [review]

**Comment by s-pace** [comment]
Nice, please ping https://github.com/algolia/docsearch-configs/pull/684 once you are live. 🙏

**Comment by XhmikosR** [comment]
Will do, thanks!

**Pull request merged**
