### PR TITLE
Upgrade to normalize.css v4.2.0.

### LINKED ISSUE #20384: <select multiple> overflows
Operating system and version: Ubuntu 14.04
Browser and version: Chrome 52.0.2743.82

Options overflow on multiple selects if there are at least 5 options.
http://codepen.io/anon/pen/GqGdbw
https://s3.amazonaws.com/upload.screenshot.co/33f65bef97

If am not mistaken it is caused by the overflow: visible; declaration set by normalize.css on selects. Possible solution is to upgrade it to the latest version, the declaration was removed in this commit: https://github.com/necolas/normalize.css/commit/e4a7827199b61e1cdcabe807044b3a2384bba924.

### PR DESCRIPTION
**Pull request by bardiharborow**
Fixes #20384. We probably need to merge this fix in even if we do end up going with #20388.

### CODE REVIEW

**Comment by bardiharborow** [comment]
Simply copy-pasting the library caused Hound to explode, so I went and fixed the comment style. It's still complaining about vendor prefixes and property ordering, but most of those issues were present last time around anyway and it may not even be possible to fix them.

**Comment by wolfy1339** [comment]
This proves there is a problem in the configuration file with Hound (`exclude_file` option in `.hound.yml ` doesn't exist according to Hound docs) and SCSSLint as `_normalize.scss` isn't ignored for some rules

**Comment by bardiharborow** [comment]
Okay, so `ignore_file` is only for `jshint`, not `scss`. For `scss` you need an `exclude` in `scss/.scss-lint.yml`. I've pushed a new commit which fixes this.

**Comment by wolfy1339** [comment]
Keep it as-is, we don't want comments in our outputted CSS (except for License/Copyright headers)

**Comment by vanillajonathan** [comment]
Might also need to update Normalize to 5.0 to resolve issue #21060

**Pull request merged**
