### PR TITLE
Move node-sass to npm script and drop Ruby Sass.

### PR DESCRIPTION
**Pull request by bardiharborow**
This PR moves node-sass to a NPM script.

Per #20332, I've also dropped Ruby Sass support:

> Compile Sass files with node-sass **(no more Ruby options)**

### CODE REVIEW

**Comment by hnrch02** [comment]
Do we know if libsass finally achieved feature parity with sass? A comparison in output for the unminified file would be handy, I think. (Unless this has already been examined and I'm OOTL.)

**Comment by bardiharborow** [comment]
Bootstrap [already uses libsass by default](https://v4-alpha.getbootstrap.com/getting-started/build-tools/#switching-sass-compilers), so this doesn't change that. The only [differences](http://pastebin.com/7kGeVhBX) in the output between libsass and Ruby Sass are to do with how whitespace is treated (I had to use `--ignore-blank-lines` to avoid diffing hundreds of added lines.) As for whether this will disrupt anyone, I posted a heads up on Slack and haven't heard any complaints.

**Review by mdo — APPROVED** [review]
Let's do it! Looks like tests are failing for some linting issues, otherwise looks good to me!

**Comment by bardiharborow** [comment]
@hnrch02 did you have any further concerns or shall we LGTM?

**Review by Johann-S — APPROVED** [review]

**Review by hnrch02 — APPROVED** [review]
Seems like I was just out of the loop on ruby Sass 😄  LGTM!

**Pull request merged**
