### PR TITLE
[Fix #18154][V4] Add test unit to check logic of ignoreBackdropClick

### LINKED ISSUE #18154: Add unit test for modal ignoreBackdropClick logic
The mistake that was fixed by #18146 ought to have caused a unit test failure, but somehow didn't, implying a gap in the test coverage.

### PR DESCRIPTION
**Pull request by Johann-S**
Hi,

Closes #18154

### CODE REVIEW

**Comment by Johann-S** [comment]
Travis failed on `rvm install 2.2`

**Comment by cvrebert** [comment]
Reopened https://github.com/travis-ci/travis-ci/issues/5092

**Comment by Johann-S** [comment]
FYI all tests passed on my environnement

**Comment by Johann-S** [comment]
Maybe this PR https://github.com/twbs/bootstrap/pull/18903 had fixed the issue so I can rebase to try to run again all tests @cvrebert ?

**Comment by cvrebert** [comment]
@Johann-S Go for it :smile:

**Comment by Johann-S** [comment]
All tests passed :smile:

**Review by bardiharborow — APPROVED** [review]

**Comment by mdo** [comment]
<3<3<3

**Pull request merged**
