### PR TITLE
[Close #16482] Add border-radius to theme's navbar-inverse

### LINKED ISSUE #16482: border-radius: @nav-border-radius missing from .navbar-inverse in theme.less
theme.less has border-radius: @navbar-border-radius; on .navbar-default [line 116].
However, in .navbar-inverse [line 132 of theme.less] the border-radius: @navbar-border-radius; is missing.

I was able to fix the issue by adding border-radius: @navbar-border-radius after line 134 on theme.less

What this is doing is when you go below the first breakpoint, .navbar-inverse loses the rounded corners, whereas navbar-default keeps them.

As an example, you can use this page...you'll the dark navbar lose the rounded corners when resizing.
http://getbootstrap.com/examples/theme/

### PR DESCRIPTION
**Pull request by kkirsche**
[Close #16482] Add border-radius to theme's navbar-inverse

### CODE REVIEW

**Comment by mdo** [comment]
Oh, btw, little protip: you don't need the `[Close #1234]` in the title—just the description field **or** the commit :). It being in the title does nothing on GitHub.

**Comment by kkirsche** [comment]
Ah cool. Thanks :)

**Comment by secorrales** [comment]
@kkirsche , @mdo Thanks for adding this in. I know it's a minor issue, but it's nice that it was added so quickly.  I'll read the documentation so I can find out what I need to do to submit a fix myself next time.

**Comment by kkirsche** [comment]
@secorrales No prob! You can read about contributing [here](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md). Feel free to also jump on getbootstrap.slack.com if you have any questions while working on a fix :+1:

**Pull request merged**
