### PR TITLE
apply selected borders style to :checked radio or checkbox

### PR DESCRIPTION
**Pull request by caub**

### CODE REVIEW

**Comment by ffoodd** [comment]
You're not supposed to use `.form-control` on radio buttons and checkboxes, but `.form-check`. Please [read our docs for checks and radios](https://getbootstrap.com/docs/5.0/forms/checks-radios/).

`:checked` styles [are handled](https://github.com/twbs/bootstrap/blob/6633845901672cb642c0975e6fea3d1a1fa20058/scss/forms/_form-check.scss#L50).

Please ensure you're fixing an issue before submitting a PR— thanks for opening this, though, appreciate the effort!

**Comment by caub** [comment]
@ffoodd yea, but .form-check doesn"t work with floating forms, see: https://jsfiddle.net/caub/2fLsrbkx/

**Comment by ffoodd** [comment]
Please open an issue for  form-check supporting floating labels, but this is not the good way to handle this.
And as per our contirbution guidelines, please at least explain what you're trying to solve when submitted a PR.

**Comment by caub** [comment]
@ffoodd Thanks ok, is it clear enough with https://github.com/twbs/bootstrap/issues/33828 ? (maybe a bit succint, but I'm sure you'll understand the point)

**Pull request closed without merging**
