### PR TITLE
Re-order popover elements in docs

### PR DESCRIPTION
**Pull request by kkirsche**
X-Ref #13969

### CODE REVIEW

**Comment by mdo** [comment]
Kinda makes sense to do it this way anyway given CSS's top, right, bottom, left shorthand order.

**Comment by kkirsche** [comment]
Ah this is right, top, bottom, left. if you want I can adjust it to match the order though or if you wanted to adjust it as you have write ability. I hadn't thought about that but it would make the most sense.

**Comment by mdo** [comment]
Oh my bad, whatever, it's fine lol.

**Comment by kkirsche** [comment]
Haha, no worries. Figured I'd clarify and double check :+1:

**Pull request merged**
