### PR TITLE
Fix `Manipulator.offset()`

### LINKED ISSUE #32496: Scrollspy: highlights wrong navigation item when a page is reloaded.
- Operating system and version : Windows 10
- Browser and version: Chrome latest

https://codepen.io/debobuiz/pen/ZEpempL

**Issue:** Please refer the screenshot. I have scrolled the page to Item 1. But in the navbar, "Item 3" is highlighted.

image

**How to reproduce the issue:**
When the page is opened initially, things will be fine. Scroll the page to item 3 or item 4. Then right-click and "reload frame" in the codepen.io preview section. Now, when you scroll the page through various items, the correct item will not be highlighted in the navbar.

### PR DESCRIPTION
**Pull request by alpadev**
fixes https://github.com/twbs/bootstrap/issues/32496, closes https://github.com/twbs/bootstrap/pull/32341

## Background
`Manipulator.offset()` is using `getBoundingClientRect()` that returns top/left values **relative** to the viewport. The current implementation uses `document.body.scrollTop` and `document.body.scrollLeft` to get the scroll position of the viewport. (Both returning 0 in current Chrome and FF)

This used to work with older browsers but since then got changed to `document.documentElement.scrollTop` and `document.documentElement.scrollLeft`. The currently proposed way to get those values (according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY#notes)) is to use `window.pageYOffset` and `window.pageXOffset`.

## TBD

- Should we also add fallbacks for `window.pageYOffset` and `window.pageXOffset` mentioned on the [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY#notes) page?

- Not sure about the test cases. Maybe someone got a better idea how to implement them.

Preview: https://deploy-preview-33603--twbs-bootstrap.netlify.app/docs/5.0/components/scrollspy/

Example of #32496 using the fix: https://codepen.io/-alpa-/pen/MWpVooG

### CODE REVIEW

**Comment by GeoSot** [comment]
Alpa, sure is better than before. However check the [preview](https://deploy-preview-33603--twbs-bootstrap.netlify.app/docs/5.0/components/scrollspy/). It fails to initialize in proper element after refresh

**Comment by PetersOtto** [comment]
Is that Issue really fix? I have the same behavior than before. [https://github.com/twbs/bootstrap/issues/32496](https://github.com/twbs/bootstrap/issues/32496)

Perhaps I do something wrong but I thing the issue is not done.

**Comment by harnishdesign** [comment]
Issue is still in bootstrap v5.0.1. #32496  have available finally any fixed?

**Review by GeoSot — APPROVED** [review]

**Comment by alpadev** [comment]
@arcanisgk how is that related?

**Comment by GeoSot** [comment]
@alpadev Correct me if I am wrong, but Manipulator methods `offset` & `position` are used only on scrollSpy, So they maybe can be moved to it

**Review by mdo — APPROVED** [review]

**Comment by XhmikosR** [comment]
@alpadev regarding your OP TODO

1. I don't think our supported browsers don't support `scrollY` so we should be safe
2. Not sure about the tests, I trust you, @rohit2sharma95 and @GeoSot :)

If you don't have further changes, we could include this in v5.0.2

**Comment by XhmikosR** [comment]
Forgot to mention that if we already use `pageYOffset`/`pageYOffsetY`, we could probably use that here too and switch to the other in a separate PR.

**Comment by XhmikosR** [comment]
@alpadev it seems we are getting random BrowserStack failures:

```
Mobile Safari 12.1.1 (iOS 12.3.1) Manipulator offset should not change offset when viewport is scrolled FAILED
	Error: Timeout - Async function did not complete within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL) in node_modules/jasmine-core/lib/jasmine-core/jasmine.js (line 7741)
	<Jasmine>
```

Maybe we need some timeout?

**Comment by arcanisgk** [comment]
It seems to me not to be completely random, it simply tries to execute at the same time as the resizing/changing the orientation of Mobile, it is not that it needs a time out I think it needs to know the status of the viewport.

**Comment by XhmikosR** [comment]
By random I mean it doesn't always happen as you can see by the current test status :)

Anyway, if anyone has any patches, please make a new PR.

**Comment by arcanisgk** [comment]
I am almost certain that the event is intercepted in the rotation of a Mobile device:

```javascript
var supportsOrientationChange = "onorientationchange" in window,
    orientationEvent = supportsOrientationChange ? "orientationchange" : "resize";

window.addEventListener(orientationEvent, function() {
    alert('HOLY ROTATING SCREENS BATMAN:' + window.orientation + " " + screen.width);
}, false);
```

**Comment by XhmikosR** [comment]
@arcanisgk could you make a PR please? We keep hitting the CI failure but it's not 100% reproducible.

**Comment by arcanisgk** [comment]
@XhmikosR Hello, I'm sorry to tell you that I don't have the slightest idea what "PR" is; The most I have achieved in github is to create a personal repository upload a library and publish it to be distributed in composer, I would like to help more but I do not have enough knowledge to support them.

**Pull request merged**
