### PR TITLE
Simplify theme color usage

### LINKED ISSUE #27338: It is not possible to properly set $link-color variable in user-land config.
In your `_variables.scss`
```scss
$link-color:                theme-color("primary") !default;
```
Your docs (https://getbootstrap.com/docs/4.1/getting-started/theming/#variable-defaults) says

> However, when overriding across Sass files, your overrides must come before you import Bootstrap’s Sass files.

But it is impossible to just change `$key` for `theme-color()` function, before import `_variables.scss`, because theme-color expects `$theme-colors` that declared in `_variables.scss`.
It turns out a vicious circle.
I know i can just use a variable instead of function call, but it is a bit confusing. Why you use `theme-color("primary")` instead of just `$primary`?

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Use variables instead of function. 

Fixes #27338. (I've made a new ticket about the deprecation of the function (#27377), because that wasn't really what the ticket was about originally)

### CODE REVIEW

**Comment by XhmikosR** [comment]
So this is backward compatible, right, @MartijnCuppens ?

**Comment by mdo** [comment]
Yeah per @XhmikosR I wonder if this counts as backward compatible. It's not a huge change, and wondering if we just save it for what comes next @XhmikosR? But also this diff is pretty small and the functions use the variable anyway, so probably safe?

**Comment by XhmikosR** [comment]
I think this is OK because it's an internal-only change in _variables.scss. The removal of the function, if it happens, it'll be a separate branch.

Just waiting for @MartijnCuppens's confirmation to be safe :)

**Review by mdo — APPROVED** [review]

**Comment by MartijnCuppens** [comment]
We're on the same level here, this merge would be pretty safe. The removal of the functions is not in the scope of this PR.

**Pull request merged**
