### PR TITLE
Removed xs from visibility classes

### PR DESCRIPTION
**Pull request by simPod**
We're removing xs from class names, so I removed it for visibility utilities.

### CODE REVIEW

**Comment by mdo** [comment]
We'll need to do a bit more here to avoid the `.hidden-down` business—that should just be `.hidden` because `xs` is `0`.

**Comment by simPod** [comment]
You are right. What about this one?

**Comment by simPod** [comment]
But I wonder that it's a bit weird and non-intuitive. I would suppose that `.hidden` would hide the element for all screensizes and we would have a class for hidding the element just for `xs`, eg. `.hidden-xs`

**Comment by mdo** [comment]
This is unneeded now since #22113 merged.

**Pull request closed without merging**
