### PR TITLE
v5: Updated About and Brand pages

### LINKED ISSUE #31092: v5 docs: brand guidelines need update (and question about the brand colors explanation)
obviously, https://v5.getbootstrap.com/docs/5.0/about/brand/ needs to show the new logo, rather than the old one.

however, skimming over them, I also stumbled across this part https://v5.getbootstrap.com/docs/5.0/about/brand/#colors

> Our docs and branding use a handful of primary colors to differentiate what is Bootstrap from what *is in* Bootstrap. In other words, if it’s purple, it’s representative of Bootstrap.

I'm not quite sure this has ever been obvious to me while going over the docs. Is that actually still the case?

/cc @mdo

### LINKED ISSUE #31144: Update the remaining assets SVG to use the new logo
* bootstrap-outline.svg
* bootstrap-punchout.svg
* bootstrap-solid.svg

### PR DESCRIPTION
**Pull request by mdo**
Fixes #31144, fixes #31092.

Updated this to remove some intended changes. This should be good to go now.

Preview: <https://deploy-preview-31248--twbs-bootstrap.netlify.app/docs/5.0/about/brand/>

### CODE REVIEW

**Comment by patrickhlauke** [comment]
xref #31092 (it closes the core issue there, but the question about the "if it’s purple, it’s representative of Bootstrap" bit still remains currently)

**Comment by XhmikosR** [comment]
A couple of comments:

1. there are 404s
2. the SVGs don't use the svgo.yml we have in build folder AFAICT

**Comment by XhmikosR** [comment]
Are we sure want to backport it? I thought only v5+ would use the new logos.

**Comment by mdo** [comment]
This should be good to go now.

**Comment by XhmikosR** [comment]
@mdo it seems we need `img-fluid` in the logos now

image

**Comment by XhmikosR** [comment]
Or the width/height attributes are currently wrong :)

**Comment by mdo** [comment]
Fixed that @XhmikosR :).

**Comment by XhmikosR** [comment]
Perfect, I'll rebase the branch later and merge it :)

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
