### PR TITLE
Fix documentations component form example

### PR DESCRIPTION
**Pull request by vsn4ik**

### CODE REVIEW

**Comment by andresgalante** [comment]
Hi @vsn4ik 
Why would you want to change that `select` for an `input`?
It makes sense the list the states on a `select`

**Comment by vsn4ik** [comment]
@Hi @andresgalante!
Because by an example we show the flexibility of the grid.
Do not use a heavier element (`<select><option>...</option>...</select>`).

**Comment by mdo** [comment]
We'll leave it as-is—it's helpful to show various elements respond to the grid.

**Comment by vsn4ik** [comment]
@mdo, but the example `<select id="inputState" class="form-control">Choose</select>` is not a correct html element.

**Comment by patrickhlauke** [comment]
@vsn4ik good catch. Fixing it https://github.com/twbs/bootstrap/pull/23912

**Pull request closed without merging**
