### PR TITLE
Integrate postcss-flexbugs-fixes into build

### LINKED ISSUE #18569: .card flex rules break in Internet Explorer 10-11
The card flex shorthand rule is:

```css
.card {
   flex: 1 0 0;
}
```

In Internet Explorer, the `flex-basis` rule of 0 causes the cards to ignore the `flex-grow` rule and size based on horizontal content-width.

Replacing the rule with:

```css
.card {
  flex: 1 0 1px;
}
```

fixes the issue in IE and still works as expected in other browsers (cards grow to fill the container but maintain equal width in relation to each other.)

### PR DESCRIPTION
**Pull request by cvrebert**
Fixes #18569.
See https://github.com/luisrudge/postcss-flexbugs-fixes
@mdo SGTY?

### CODE REVIEW

**Comment by mdo** [comment]
Seems fine to me. We'll want to document that IE bug a bit more though no? Is there no way to keep a hack inline for it?

**Comment by cvrebert** [comment]
> Is there no way to keep a hack inline for it?

@mdo Not that I'm aware of. The alternative is to be constantly vigilant when writing our CSS to:
* [Never use the `flex` shorthand with less than 2 values](https://github.com/philipwalton/flexbugs/blob/master/README.md#6-the-default-flex-value-has-changed)
* [Never use unitless `0` as the 3rd value in `flex` shorthand; always use `0%` instead](https://github.com/philipwalton/flexbugs/blob/master/README.md#4-flex-shorthand-declarations-with-unitless-flex-basis-values-are-ignored)

(Or always use the longhand properties instead of the `flex` shorthand property.)

**Comment by cvrebert** [comment]
Or you could declare IE10-11 unsupported for Flexbox. They have many Flexbox bugs; see https://github.com/philipwalton/flexbugs/blob/master/README.md

**Comment by mdo** [comment]
Hmm, we could to the first bullet you mention, but not the second (unless we disable our linter for unitless values). Maybe we try that instead to avoid an extra dependency?

**Comment by cvrebert** [comment]
I suppose we could ask/PR SCSS-Lint to (1) add a new rule for the 1st bullet and (2) add the ability to exempt certain properties from the `ZeroUnit` rule. But that's 2 birds in the bush versus a bird in the hand.

**Comment by slavanga** [comment]
Please also keep in mind that a lot of people compile Bootstrap with apps like Codekit or Prepros. They won't be able to use postcss-flexbugs-fixes.

**Comment by cvrebert** [comment]
I note that the same argument could have been made about Autoprefixer a while ago. Being chained to slow-moving GUI tools in the hyper-fast-paced web frontend ecosystem doesn't strike me as the wisest decision.

**Comment by cvrebert** [comment]
Filed https://github.com/brigade/scss-lint/issues/702 and https://github.com/brigade/scss-lint/issues/703
So now we're at the mercy of someone being generous enough to implement those, if we go the SCSS-Lint route.

**Comment by cvrebert** [comment]
Going with this for now.

**Pull request merged**
