### PR TITLE
Fix dropdown docs about autoclose and esc key.

### LINKED ISSUE #35756: Dropdown autoClose="false" close on ESC, but shouldn't
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

According to the documentation example on:
https://getbootstrap.com/docs/5.1/components/dropdowns/
Setting autoClose="false" and pressing ESC shouldn't close the dropdown. But actually it closes by pressing ESC button.
See also the example "Manual Close" on
https://getbootstrap.com/docs/5.1/components/dropdowns/#auto-close-behavior

### Reduced test cases

See also the example "Manual Close" on
https://getbootstrap.com/docs/5.1/components/dropdowns/#auto-close-behavior

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

5.1.3

### PR DESCRIPTION
**Pull request by florianlacreuse**
Fixes #35756.

### CODE REVIEW

**Review by ffoodd — APPROVED** [review]
Nice, thanks!

@patrickhlauke @GeoSot Is my answer in the linked issue correct? If so, this PR should land, IMHO 🙂

**Review by patrickhlauke — APPROVED** [review]

**Comment by patrickhlauke** [comment]
LGTM

**Comment by GeoSot** [comment]
According to our js code, ESC event is independent of `autoClose` option, so we are fine

**Comment by florianlacreuse** [comment]
Thanks for the quick review and merge.

**Pull request merged**
