### PR TITLE
Add pointer event utilities

### PR DESCRIPTION
**Pull request by MartijnCuppens**
To make it easier to remember I chose the `dead` & `alive` class names 😉

Docs: https://deploy-preview-30185--twbs-bootstrap.netlify.com/docs/4.3/utilities/interactions/#pointer-events

### CODE REVIEW

**Comment by ysds** [comment]
I think that class names are not clear since abstract. The priority of adding utilities is not high, I moved this to alpha2.

**Comment by XhmikosR** [comment]
Agreed on the name. We need something better, not sure what though :P

**Comment by MartijnCuppens** [comment]
Alternatives:
- `pe-none`/`pe-auto`
- `pointer-events-none`/`pointer-events-auto`
- `you-shall-not-click`/`click-me-please`

**Comment by mdo** [comment]
> * `pe-none`/`pe-auto`

This is my vote. I can't think of anything else that would be confused with this, and it fits with our other shorthand notations.

**Review by XhmikosR — APPROVED** [review]

**Review by ysds — APPROVED** [review]

**Pull request merged**
