### PR TITLE
Number.parseFloat: function repeated access

### PR DESCRIPTION
**Pull request by yyjiugui**
Number.parseFloat function repeated access

### CODE REVIEW

**Review by julien-deramond — APPROVED** [review]
Good catch! Thanks for your PR :)

**Comment by julien-deramond** [comment]
@GeoSot I let you double-check :)

**Comment by GeoSot** [comment]
On first view I was ready to approve, but I got in seconds thoughts. 
Short answer, better stay as already is :


<br>

**Explanation:**

According to https://developer.mozilla.org/en-US/docs/Web/CSS/transition-duration, 
is valid to have the value `transition-duration: 3s, 1s;`

So I changed offcanvas css to :
image

Built the assets and added some hard-way debug helpers
image

Browsed to my local documentation offcanvases and opened one....
The results are not so encouraging
image

Unfortunately, it can bee seen that the results without the `parseFloat`, may be strings, and on my as it depends on me, is better not to mess js mathematical calculations, involving strings

**Comment by yyjiugui** [comment]
Hello, I would like to ask, how can I fully test the code after I change the code to ensure that it will not affect other modules.

**Comment by XhmikosR** [comment]
Yeah, this is intentional for the aforementioned reason.

**Comment by GeoSot** [comment]
> Hello, I would like to ask, how can I fully test the code after I change the code to ensure that it will not affect other modules.

A nice question. :love_you_gesture: 

For this scenario, I suppose we would need to `index.spec.js` and add a new testCase.
The testCase should contain an element (to the `fixture.innerHtml`), having given style with a like `transition-duration: 0.3s, 1s;` .
After this, we would need to call `getTransitionDurationFromElement` using the HTMLelement we created, and to test that the result will be a float value (0.3)

We would be glad to accept a PR containing this test

**Pull request closed without merging**
