### PR TITLE
add support for ol in tab plugin

### LINKED ISSUE #17754: Tab plugin should use a class selector instead of a ul tag selector
Hello. I want to use `<ol>` instead of `<ul>`, but in the `Tab` plugin tag name is hardcoded.
https://github.com/twbs/bootstrap/blob/master/js/tab.js#L28
```js
var $ul      = $this.closest('ul:not(.dropdown-menu)')
```

### PR DESCRIPTION
**Pull request by maxbeatty**
fixes #17754 by applying #17933 to v4

### CODE REVIEW

**Comment by mdo** [comment]
Anyone have feedback on the Hound errors here? Would love to unblock this PR and get it merged.

**Comment by Johann-S** [comment]
It seem's Hound prefer ES6 JavaScript and it's happened in others PR, I think we should allow ES5 in our JS Units in Hound

**Comment by bardiharborow** [comment]
@mdo, it's all green. Hound is just mad again. It's the issue we discussed today about the tests being es5.

**Comment by maxbeatty** [comment]
I tried to fix similar hound violations in #20174 and found that phantomjs needs to be updated before the unit tests can follow the styleguide

**Comment by bardiharborow** [comment]
@maxbetty, see, the tests need to be es5 because they need to run on non-es6 browsers, so we can either transpile them (more tooling and complexity) or leave them as es5. The linter just needs to be fixed, something that I'm working on. This PR is good to go.

**Pull request merged**
