### PR TITLE
Fix input group border radii

### LINKED ISSUE #25110: Missing border radius on input group with validation feedback
With new beta 3 and using the new input-group stuff, inputs inside input-groups with some validation feedback after them are missing the border-radius.

formbug
red circle: without border-radius
green circle: with border-radius

This is an example from the [bootstrap documentation](https://getbootstrap.com/docs/4.0/components/forms/#custom-styles)

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Fixes https://github.com/twbs/bootstrap/issues/25110 by requiring a `.has-validation` class on input groups with validation (tooltips/feedback).

Closes https://github.com/twbs/bootstrap/pull/31666

Preview:
https://deploy-preview-31953--twbs-bootstrap.netlify.app/docs/5.0/forms/input-group/
https://deploy-preview-31953--twbs-bootstrap.netlify.app/docs/5.0/forms/validation/#server-side
https://deploy-preview-31953--twbs-bootstrap.netlify.app/docs/5.0/forms/validation/#tooltips

### CODE REVIEW

**Review by mdo — APPROVED** [review]
Damn, what a doozy of a PR. Props for a fairly elegant solution here.

**Comment by mdo** [comment]
This could be backported, yeah? Technically not a breaking change if we added to v4.6.0 since we're adding a class that fixes a longstanding bug.

**Comment by MartijnCuppens** [comment]
Hmm, this is still not the solution we wanted, there are still some issues like these:
image

I think we'll need a JS solution so that we can move the validation messages out of the `input-group`.

**Comment by MartijnCuppens** [comment]
Ok, nevermind, I think I nailed it now 😄

> This could be backported, yeah? Technically not a breaking change if we added to v4.6.0 since we're adding a class that fixes a longstanding bug.

Indeed, we're adding a class to fix the issue. That's not a breaking change since it was already broken 😛

**Comment by ffoodd** [comment]
LGTM! Shouldn't this be added to the migration guide? Or backporting it to v4 means this is not needed?

**Review by ffoodd — APPROVED** [review]

**Comment by mdo** [comment]
> LGTM! Shouldn't this be added to the migration guide? Or backporting it to v4 means this is not needed?

I think it'd be helpful to mention in Migration because people _want_ this to be a bugfix or breaking change.

**Comment by MartijnCuppens** [comment]
Updated the migration guide and opened #31962 to backport this to v4

**Pull request merged**
