### PR TITLE
Bump markdown-it to ^3.0.7

### PR DESCRIPTION
**Pull request by kkirsche**
Bump markdown it to 3.0.7

3.0.7 / 2015-02-22

Match table columns count by header.
Added basic CLI support.
Added \v \f to valid whitespaces.
Use external package for unicode data (punctuation).

### CODE REVIEW

**Comment by cvrebert** [comment]
When updating dependencies, the https://github.com/twbs/bootstrap/blob/master/test-infra/npm-shrinkwrap.json file needs to be updated too, via the [`update-shrinkwrap`](https://github.com/twbs/bootstrap/blob/a1fd86cdf9dca0f0d11ae895a92debe6a05b1163/Gruntfile.js#L496) Grunt task.

**Comment by kkirsche** [comment]
Noted for the future @cvrebert — it is currently though correct with 
```json
...
"markdown-it": {
      "version": "3.0.7",
...
```

**Comment by cvrebert** [comment]
I wouldn't normally do a patch-level version bump unless it had changes that were relevant to us, but what the hell.

**Comment by kkirsche** [comment]
Noted for the future. Thanks for the info about the dependencies.

**Comment by cvrebert** [comment]
Other random note:
Definitely not mandatory, but when making changes that don't affect the client-side JS unit tests, try to include `[skip sauce]` as a line in the commit message to skip the Sauce Labs tests, since those tests can be flaky and can take a while to run.

**Comment by kkirsche** [comment]
Ah ok. Thank you for the info on that. That type of thing is helpful :+1:

**Pull request merged**
