### PR TITLE
[Closes #16447] Manually add license to bootstrap.less

### LINKED ISSUE #16447: Include license to bootstrap.less
The MIT license header currently only is added to `dist/css/bootstrap.css`. If `less/bootstrap.less` is directly used (with the less compiler), no license statement ends up in the generated file. I propose to also add the MIT license header to `less/bootstrap.less`.

### PR DESCRIPTION
**Pull request by kkirsche**
[Closes #16447] Concat. license to bootstrap.less

~~EDIT: WIP~~ Fixed and verified

### CODE REVIEW

**Comment by mdo** [comment]
Problem is this needs to be added without compilation, as in without our Gruntfile. The original bug report —I think—is mentioning that if you use a regular compiler, there's no license.

**Comment by kkirsche** [comment]
Ah, sorry, I misunderstood that. I'll add it in manually instead then I guess unless you have an alternative solution which I could implement?

**Comment by cvrebert** [comment]
I agree that manual is probably the way to go here.

**Comment by mdo** [comment]
Manual works for me.

**Comment by kkirsche** [comment]
@mdo / @cvrebert Fixed

**Comment by kkirsche** [comment]
Wanted to follow up on this

**Comment by XhmikosR** [comment]
This causes duplicate license headers in the dist CSS files.

**Comment by cvrebert** [comment]
Yes, the part of the Gruntfile that previously added the license header needs to be killed.

**Comment by XhmikosR** [comment]
I ended up just running grunt-usebanner for the theme files only.

**Comment by kkirsche** [comment]
Oops. Sorry about that

**Pull request merged**
