### PR TITLE
added text-gray-dark class

### PR DESCRIPTION
**Pull request by eddyerburgh**
Added a utility class .text-gray-dark. See #19842

### CODE REVIEW

**Comment by cvrebert** [comment]
The premise for why this class would be useful seems reasonable enough.
But this should probably use `$body-color` instead and perhaps be named something like `.text-color-default`.
@mdo Thoughts?

**Comment by eddyerburgh** [comment]
Ok, I'll update the request if @mdo agrees

**Comment by RyanZim** [comment]
@mdo ping?

**Comment by mdo** [comment]
If the class is using the specific variable and value, it makes sense to not use the `$body-bg`. If the classes were `.text-body`, then maybe, but that's an unclear utility.

**Pull request merged**
