### PR TITLE
Fix modal background shift when overflow-y: scroll

### LINKED ISSUE #15718: Add support for modals with forced scrollbars (`overflow-y: scroll`)
Scrollbar showing/hiding and the related *"layout jumping"* is usually percieved pretty negatively by users. This is less issue on static web pages, however with dynamic pages or *single-page web applications* (e.g. AngularJS based) it becames very uncomfortable and distracting.

To workaround this a standard solution is to force browsers to always show vertical scrollbar by setting `overflow-y: scroll` on `<body>` element. However this is incompatible with Bootstrap's modal dialog as it checks for scrollbar presence only by checking that the [content height is bigger than the viewport](https://github.com/twbs/bootstrap/blob/master/js/modal.js#L250).

I would like Bootstrap to support forced scrollbars (i.e. change the [detection when the scrollbars are shown](https://github.com/twbs/bootstrap/blob/master/js/modal.js#L250)).

JS-Bin to demonstrate the current state of things: http://jsbin.com/johobubafa/1/

### PR DESCRIPTION
**Pull request by trask**
Fixes #15718

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 8c2b2df2e55e09854e982e4f4b077cb7c5c326c7
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/49410422

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
If you could add a relevant visual test (https://github.com/twbs/bootstrap/tree/master/js/tests/visual), that'd be much appreciated.

**Comment by kkirsche** [comment]
@cvrebert what does Bootstrap use for visual tests? I just want to research it a bit more for my own use and maybe I could try to add a test for this or for a future PR of my own.

**Comment by cvrebert** [comment]
@kkirsche There's no visual test framework. The visual tests are just a collection of examples that are supposed to be manually ("visually") tested/checked by humans.

**Comment by cvrebert** [comment]
@trask So, any chance you can add the requested test?

**Comment by trask** [comment]
@cvrebert Sorry for the delay, went to test today, and the issue was indirectly fixed in master a few days ago by 16479e9051614696df3d21acd9d482018da17045 (yay!)

**Comment by kkirsche** [comment]
Nice. Thanks for your work though @trask.

**Pull request closed without merging**
