### PR TITLE
download page: add Yarn

### PR DESCRIPTION
**Pull request by matbrgz**

### CODE REVIEW

**Comment by XhmikosR** [comment]
The thing with this is I don't think it should be a separate section personally.

**Comment by Johann-S** [comment]
But this sections is called `Package managers` to it should list all the package managers we support 🤔 

https://getbootstrap.com/docs/4.1/getting-started/download/#package-managers

**Comment by XhmikosR** [comment]
That's true. It just doesn't make a lot of sense to me but anyway.

**Review by XhmikosR — APPROVED** [review]

**Comment by MatheusRV** [comment]
> The thing with this is I don't think it should be a separate section personally.

I fully understand your consideration, NPM and Yarn are pretty much the same thing, but we have to recognize that many developers want ease by using ctrl + c and ctrl + v to add Bootstrap to their projects.

**Pull request merged**
