### PR TITLE
Make easier to replace carousel controls glyphicon

### PR DESCRIPTION
**Pull request by Seb33300**
Make easier to use others glyphicon class instead of glyphicon-chevron-*
Like glyphicon-triangle-_, glyphicon-menu-_, etc...

### CODE REVIEW

**Comment by mdo** [comment]
Hmm, maybe. This changes the specificity for a lot of folks in that a single class was used before and now we have a parent element in the selectors. I don't feel too comfortable changing this just yet since it could really annoy folks when any of their specific overrides for those icons get nullified by a change like this.

**Comment by Seb33300** [comment]
Do you have an example of an override which will be nullified by this change? 
`.carousel-control.left .glyphicon` or `.carousel-control .glyphicon-chevron-left` are equivalent.

Maybe, we can also keep the old syntax and only add the new one?

**Comment by mdo** [comment]
> Maybe, we can also keep the old syntax and only add the new one?

I'm meh on that since it just adds bloat without a strong justification. I get that a more generic class is easier to work with, but it's not a necessary change for v3. For now I'm punting on this. Thanks though!

**Pull request closed without merging**
