### PR TITLE
NuGet: Use license expression

### PR DESCRIPTION
**Pull request by vanillajonathan**
Use a SPDX license expression to specify MIT instead of pointing to the LICENSE file.

Reference: https://docs.microsoft.com/en-us/nuget/reference/nuspec#license

### CODE REVIEW

**Comment by julien-deramond** [comment]
Thanks for the PR. Got a few questions here.

Atm when we go to https://www.nuget.org/packages/bootstrap/ we have a ["License info" link](https://www.nuget.org/packages/bootstrap/5.1.3/License).

I suppose that with this PR we would have we would have the equivalent of what we can see in https://www.nuget.org/packages/Newtonsoft.Json/13.0.2-beta1 with a "[MIT](https://www.nuget.org/packages/bootstrap/5.1.3/License) license". If we click on this [MIT](https://www.nuget.org/packages/bootstrap/5.1.3/License) link we can see that some information are missing.

Wouldn't be the same with your proposal? How do we add for example what we currently have in our license? for example:
```
Copyright (c) 2011-2021 Twitter, Inc.
Copyright (c) 2011-2021 The Bootstrap Authors
```

Seems interesting to use the SPDX format but I'd say it's important that we can keep all existing info.

**Comment by vanillajonathan** [comment]
I don't know. But this is the way other packages do it too, including Microsoft:
Example https://www.nuget.org/packages/System.Net.Http.Json and https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/

**Comment by supergibbs** [comment]
Looks good to me, except the license file would change. The copyright info is displayed on nuget.org which is just the dates right now. If you want to show:
```
Copyright (c) 2011-2021 Twitter, Inc.
Copyright (c) 2011-2021 The Bootstrap Authors
```
we can update the .nuspec files accordingly

**Comment by mdo** [comment]
We should simplify to The Bootstrap Authors for everywhere IMO—we can drop the Twitter mention after ~10 years of them having nothing to do with it lol.

**Review by supergibbs — COMMENTED** [review]
I can't officially approve, but looks good to me

**Comment by supergibbs** [comment]
@vanillajonathan Actually noticed something, `.nuspec` files should remove `<file src="LICENSE.txt" target="" />`

**Comment by vanillajonathan** [comment]
@supergibbs Done!

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
Not sure if we need to backport this to v4-dev.

**Pull request merged**
