### PR TITLE
Remove role unnecessary

### PR DESCRIPTION
**Pull request by adammacias**
I used [validator.w3.org](https://validator.w3.org/nu/?doc=http%3A%2F%2Fgetbootstrap.com%2F) and it show that...

validate1

### CODE REVIEW

**Comment by cvrebert** [comment]
CC: @patrickhlauke

**Comment by patrickhlauke** [comment]
IE doesn't expose `<header>` properly without the `role`, so unfortunately that'll have to stay. see http://html5accessibility.com/ and https://connect.microsoft.com/IE/feedback/details/804723/html5-structural-elements-not-exposed-via-accessibility-api

**Comment by adammacias** [comment]
Ok @patrickhlauke :cry:  my bad :smile:

**Comment by patrickhlauke** [comment]
no worries, always good that people are vigilant...it forced me to have another look as to why we have them in the first place :)

**Pull request closed without merging**
