### PR TITLE
Add `loading="lazy"` in images

### PR DESCRIPTION
**Pull request by XhmikosR**
TODO:

- [ ] See if we should skip lazy loading some of the images
- [ ] Decide if we want to backport this to v4-dev
- [x] This is blocked due to <https://github.com/validator/validator/issues/699>; we could ignore the error, but there's no need to hurry IMHO

Preview: <https://deploy-preview-30199--twbs-bootstrap.netlify.com/>

### CODE REVIEW

**Comment by XhmikosR** [comment]
Is it just me, or this doesn't work on Chrome 80? I mean, I go to https://deploy-preview-30199--twbs-bootstrap.netlify.com/ and I see all images loaded at once.

**Comment by patrickhlauke** [comment]
> Is it just me, or this doesn't work on Chrome 80? I mean, I go to https://deploy-preview-30199--twbs-bootstrap.netlify.com/ and I see all images loaded at once.

it does seem to work, but to see the effect you likely need to emulate a slow network device and choose a page with lots of images beyond the current viewport. chrome applies some heuristics based on estimated connection speed etc to determine how lazy it can be with loading. saw some of the effects when trying to view https://deploy-preview-30199--twbs-bootstrap.netlify.com/docs/4.3/examples/ while simulating a slow mobile network on a smartphone device

**Comment by XhmikosR** [comment]
Indeed, thanks for the hint. I thought it would apply regardless of the network connection or device, but apparently it doesn't.

**Comment by patrickhlauke** [comment]
> Chrome’s lazy-loading implementation is based not just on how near the current scroll position is, but also the connection speed.

https://addyosmani.com/blog/lazy-loading/

**Comment by XhmikosR** [comment]
@mdo @MartijnCuppens can you guys check the images I added lazyload and let me know if you are OK with it? Or if I missed any other images.

After tomorrow's dependabot run, we'll have the new vnu.jar version in master.

**Comment by MartijnCuppens** [comment]
I'm ok with it. I think you covered all the images, the examples and readme can be skipped.

**Review by MartijnCuppens — APPROVED** [review]

**Pull request merged**
