### PR TITLE
add cursor classes

### PR DESCRIPTION
**Pull request by elyasmotazedy**
cursor-help
cursor-wait
cursor:-crosshair
cursor-not-allowed
cursor-zoom-in
cursor-grab

### CODE REVIEW

**Review by XhmikosR — CHANGES_REQUESTED** [review]
Please read our contribution guidelines. You are not supposed to include any dist files.

**Comment by patrickhlauke** [comment]
personally, i'm strongly averse to "let's just reflect every possible CSS thing in a ready-made class". if an author really needs it, it takes only a few seconds to make their own custom CSS class additions.

**Comment by XhmikosR** [comment]
Yeah, agreed.

**Comment by XhmikosR** [comment]
We are going to pass at this, thanks for the contribution.

**Pull request closed without merging**
