### PR TITLE
Add embed-responsive-21by9

### PR DESCRIPTION
**Pull request by adammacias**
Added `.embed-responsive-21by9` for [component responsive embed](http://getbootstrap.com/components/#responsive-embed)

### CODE REVIEW

**Comment by mdo** [comment]
Why 21x9?

**Comment by cvrebert** [comment]
Presumably http://en.wikipedia.org/wiki/21:9_aspect_ratio , although it's technically a misnomer.

**Comment by adammacias** [comment]
21x9 is a format that is becoming popular, mainly monitors and TVs **ultrawide**, like the 1x1, maybe we can add this format too, used on sites like Vine and Instagram.

Preview: http://codepen.io/adammacias/pen/mJEXyo/

**Comment by twbs-lmvtfy** [comment]
Hi @adammacias!

You appear to have posted a live example (http://codepen.io/adammacias/pen/mJEXyo.html), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 18, column 5 thru line 18, column 95: ```` & ```` did not start a character reference. (```` & ```` probably should have been escaped as ```` &amp; ````.)
* line 18, column 5 thru line 18, column 104: ```` & ```` did not start a character reference. (```` & ```` probably should have been escaped as ```` &amp; ````.)
* line 18, column 5 thru line 18, column 173: Attribute ```` webkitallowfullscreen ```` not allowed on element ```` iframe ```` at this point.
* line 18, column 5 thru line 18, column 173: Attribute ```` mozallowfullscreen ```` not allowed on element ```` iframe ```` at this point.
* line 25, column 5 thru line 25, column 95: ```` & ```` did not start a character reference. (```` & ```` probably should have been escaped as ```` &amp; ````.)
* line 25, column 5 thru line 25, column 104: ```` & ```` did not start a character reference. (```` & ```` probably should have been escaped as ```` &amp; ````.)
* line 25, column 5 thru line 25, column 173: Attribute ```` webkitallowfullscreen ```` not allowed on element ```` iframe ```` at this point.
* line 25, column 5 thru line 25, column 173: Attribute ```` mozallowfullscreen ```` not allowed on element ```` iframe ```` at this point.
* line 32, column 5 thru line 32, column 95: ```` & ```` did not start a character reference. (```` & ```` probably should have been escaped as ```` &amp; ````.)
* line 32, column 5 thru line 32, column 104: ```` & ```` did not start a character reference. (```` & ```` probably should have been escaped as ```` &amp; ````.)
* line 32, column 5 thru line 32, column 173: Attribute ```` webkitallowfullscreen ```` not allowed on element ```` iframe ```` at this point.
* line 32, column 5 thru line 32, column 173: Attribute ```` mozallowfullscreen ```` not allowed on element ```` iframe ```` at this point.
* line 39, column 5 thru line 39, column 148: Attribute ```` webkitallowfullscreen ```` not allowed on element ```` iframe ```` at this point.
* line 39, column 5 thru line 39, column 148: Attribute ```` mozallowfullscreen ```` not allowed on element ```` iframe ```` at this point.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by adammacias** [comment]
Sorry, fixed the preview: http://codepen.io/adammacias/pen/mJEXyo/

**Comment by cvrebert** [comment]
> used on sites like Vine and Instagram.

@adammacias I can't seem to find any evidence of this. Have any sources you can link to?

**Comment by mdo** [comment]
@cvrebert I think he was talking about the 1:1 ratio for that.

**Comment by adammacias** [comment]
Yes @mdo ! :) 

I added 1:1 ratio and improved this...

before: `padding-bottom: 56.25%`
after: `padding-bottom: percentage((9 / 16)); // 56.25%`

**Comment by mdo** [comment]
> Can I commit the dist and docs with grunt prep-release or only core team can do this?

No sweat on asking—and you don't need to do that. That's for when we're finally ready to formally release a new version.

**Comment by mdo** [comment]
Punting to v4.

**Comment by adammacias** [comment]
:+1: thanks

**Pull request closed without merging**
