### PR TITLE
Separate font-family setting for SVG (#24673)

### PR DESCRIPTION
**Pull request by Herst**
Workaround for #24673. See <https://crbug.com/781344> for details.

### CODE REVIEW

**Comment by XhmikosR** [comment]
I'm not sure we should do this. I mean, it's clearly a browser bug, isn't it? If the bug report is closed for whatever reason without a fix, then it would make sense to do this.

**Comment by Herst** [comment]
Fair enough and in any case the users making use of SVGs with a lot of text it in can add such a fix to their CSS.

That said, should this not be fixed soon though then it might be worth adding a note about it to the documentation. Others might be surprised like I with by a sudden performance drop in their application after switching to Bootstrap 4. I thought at first that Bootstrap's new button styling, flex box or `calc()` usage might be to blame.

**Comment by Herst** [comment]
@mdo, @cvrebert should you decline this patch, would <https://crbug.com/781344> be a possible candidate for the Wall of Bugs and [the Bootstrap meta bug](https://crbug.com/536263)?

**Comment by patrickhlauke** [comment]
i'd say yes to the wall of bugs

**Comment by Herst** [comment]
Closed in favor of #24751.

Still the workaround is worth to keep in the back of one's head if dealing with dynamic animated/interactive SVG content because even if a fix were to land in three weeks then it's not going to reach general Chrome users until March 2018.

**Pull request closed without merging**
