### PR TITLE
Make .bg-variant adjust :focus color in addition to :hover color

### PR DESCRIPTION
**Pull request by monoblaine**
Similar to #16047

### CODE REVIEW

**Comment by mdo** [comment]
Sounds reasonable.

**Comment by patrickhlauke** [comment]
wondering if this also needs a selector for ``.focus`` class (which is applied programmatically in certain situations, where the actual element cannot be natively focused). Otherwise LGTM

**Comment by mdo** [comment]
We only use `.focused` for our button behaviors, not sure that applies here.

**Comment by mdo** [comment]
Let's :shipit: as-is.

**Comment by patrickhlauke** [comment]
:+1:

**Pull request merged**
