### PR TITLE
Remove Internet Explorer leftovers.

### PR DESCRIPTION
**Pull request by XhmikosR**
**Untested!**

There are more cases in _modal.scss but I thought someone else should tackle those.

### CODE REVIEW

**Comment by XhmikosR** [comment]
BTW maybe we should leave these? On the other hand we removed a few IE specific CSS stuff already.

The idea was if one wanted to support IE, they could add the prefixes and the polyfills. So I'm not sure which way to go. But we should be consistent.

**Comment by patrickhlauke** [comment]
It would be nice if a site didn't completely break/explode in IE11. so walking the fine line of not trying to patch things to work in IE11, but have it at least present content in a semi-sensible way...

**Comment by XhmikosR** [comment]
Yeah, I don't know myself either. Because if we are going the way you suggest, which is fine by me, we should actually revert a couple of changed that have landed on master.

**Comment by Herst** [comment]
But at least nobody needs to care about IE10: #25100

**Comment by XhmikosR** [comment]
Yeah, the discussion is for IE 11.

**Comment by ray73864** [comment]
Would love to have used Bootstrap 5 when it comes out, but the lack of IE11 support would be a deal-breaker for me unfortunately.

In our business, all our stores log onto a series of terminal servers (our admin people log onto another one), a store might have 5 thin clients and all 5 are logged onto the same user, the unfortunates of Chrome, Firefox, etc... is that they don't support session-profiles, only user-profiles, so with 5 logged into the same user, the first one to open Chrome/FF sets the lock on the profile and both require kludges to get them to be semi-useful.

We have in the past attempted Chrome, but it's never been 100% successful. IE on the other hand supports user-session profiles, so each logged in session has a slightly separate way of using the browser (especially from the task-manager POV).

If there was a stylesheet + polyfills for V5 that allow it to continue to work on IE11 that would be super-awesome, then I could get rid of jQuery completely.

**Comment by XhmikosR** [comment]
Closing since we are going to keep IE 11 support for v5.

**Pull request closed without merging**
