### PR TITLE
Separate btn-link colors from link

### PR DESCRIPTION
**Pull request by GeoSot**
I would like to be able to separate link colors from btn-link colors, so to be able to choose different values for each

### CODE REVIEW

**Review by MartijnCuppens — APPROVED** [review]
LGTM

**Comment by GeoSot** [comment]
@MartijnCuppens  can we pass this change on v4 too?

**Comment by MartijnCuppens** [comment]
Hi @GeoSot,

We're blocking all new features for `v4` and will add them in `v5`.

**Comment by tomsommer** [comment]
Why not `text-decoration` as well then?

**Comment by MartijnCuppens** [comment]
@tomsommer, I don't mind adding that as well, feel free to open a PR.

**Pull request merged**
