### PR TITLE
Use instead of import

### PR DESCRIPTION
**Pull request by roythearsonist**
Uses proper sass, as the import is going to removed eventually

### CODE REVIEW

**Comment by XhmikosR** [comment]
Thanks, but as it has been discussed plenty of times, we are not going to switch to Dart Sass specific usage for the time being.

**Comment by theblobscp** [comment]
ok

**Comment by gaborszita** [comment]
I understand that the Bootstrap team doesn't want to switch to Dart Sass specific usage, however, me personally would like to use `@use` instead of `@import`, since the Sass team discourages using `@import`. For this reason, I will be (or at least try) using `@use` in my projects, but I'm running into some issues.

Whenever I try to use `@use` instead of imports, I get this error:

```
Error: ("primary": #0d6efd, "secondary": #6c757d, "success": #198754, "info": #0dcaf0, "warning": #ffc107, "danger": #dc3545, "light": #f8f9fa, "dark": #212529) isn't a valid CSS value.
   ╷
94 │ $theme-colors-rgb: map-loop($theme-colors, to-rgb, "$value") !default;
   │                             ^^^^^^^^^^^^^
   ╵
  node_modules/bootstrap/scss/_variables.scss 94:29  @use
  sass/source/main.scss 10:1                         root stylesheet
```

Is this an issue that is "unfixable" and I have to use `@import`? I hope not...

@theblobscp, since you're the one who created this PR, were you able to get this working for yourself? What am I doing wrong?

**Comment by theblobscp** [comment]
I'm not sure if I can help you, I don't have the code that caused this

**Pull request closed without merging**
