### PR TITLE
Provide V4 JSBin template in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by kkirsche**
provide V4 JSBin template for users to use when sending bug reports. Should help users in situations like #17134

### CODE REVIEW

**Comment by hnrch02** [comment]
@cvrebert @mdo Maybe we can use the Bootstrap JS Bin account for this?

**Comment by kkirsche** [comment]
Wanted to follow up here and see if there was anything needed from me to keep this moving forward?

**Comment by mdo** [comment]
Tests fail for some reason. We never got around to the Bootstrap JS Bin thing being a reality as far as I know. Any update there @cvrebert?

**Comment by cvrebert** [comment]
@mdo Still blocked on https://github.com/jsbin/jsbin/issues/2518 . I'll try pinging it.

**Comment by mdo** [comment]
I'm fine doing this for now. Hopefully we can do the vanity thing in the future.

**Comment by kkirsche** [comment]
Thanks.

**Pull request merged**
