### PR TITLE
Jan 3 dist build

### PR DESCRIPTION
**Pull request by mdo**
Making a quick `npm run dist` to capture the latest changes.

### CODE REVIEW

**Review by MartijnCuppens — APPROVED** [review]

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
@mdo: I didn't merge this because there are more changes. Please fetch, do npm i and redo this.

**Comment by XhmikosR** [comment]
@mdo you pushed again directly...

**Comment by mdo** [comment]
Ah damnit, just went into autopilot. Sorry about that! I can revert if anything looks off.

**Comment by XhmikosR** [comment]
I didn't verify your v4-dev push but I'd feel much safer if you enforced the limitations for admins too. You can always shift the limitations for you if needed.

**Comment by MartijnCuppens** [comment]
Even though this change is quite harmless, I totally agree with @XhmikosR here.

**Pull request closed without merging**
