### PR TITLE
badge accessible in high contrast mode

### PR DESCRIPTION
**Pull request by julians300**
This PR gives a transparent border to badges so they give better context in high contrast mode.

Before

Screen Shot 2019-10-03 at 10 20 08 PM
Screen Shot 2019-10-03 at 10 20 34 PM

After

Screen Shot 2019-10-03 at 10 20 14 PM
Screen Shot 2019-10-03 at 10 20 38 PM

Preview: <https://deploy-preview-29490--twbs-bootstrap.netlify.app/docs/5.0/components/badge/>

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
This will indent each badge with one pixel. Maybe there's any way to detect when we're in high contrast mode?

**Comment by patrickhlauke** [comment]
these could be scoped to just `-ms-high-contrast:active` media query - would still result in the indent, but only in HC mode.

note that Windows HC is quite unique in that it munges/reinterprets/overrides a site's CSS. also, HC likely doesn't currently work with a lot of other components (not tested, but off the top of my head thinking any fancy checkbox/radio button/form control constructs that use clever "faked" CSS / rely on background images and borders. https://github.com/twbs/bootstrap/issues/26892 + https://github.com/twbs/bootstrap/issues/21269

related https://developer.paciellogroup.com/blog/2016/12/windows-high-contrast-mode-the-limited-utility-of-ms-high-contrast/ and http://www.gwhitworth.com/blog/2017/04/how-to-use-ms-high-contrast/

**Comment by XhmikosR** [comment]
Unless we do this across the codebase, I don't think it makes sense to do it just for one component.

**Comment by MartijnCuppens** [comment]
> This will indent each badge with one pixel. Maybe there's any way to detect when we're in high contrast mode?

Seems I was wrong about this, the border just adds a px.

I'm ok with this change, as long as we add a comment in the source code since this is not self-explanatory.

**Comment by mdo** [comment]
I'm inclined to leave this or scope it to high contrast mode only. Could be skipped entirely if we figure out the right theme/color scheme approach.

**Comment by patrickhlauke** [comment]
adding some more resources:

* https://sarahmhigley.com/writing/whcm-quick-tips/
* https://www.w3.org/2019/09/Meetup/speaker-melanie.html

would be good to have a run through the entirety of Bootstrap to see what needs to be tweaked. it should be possible to make things work ok in high contrast without affecting the non-high-contrast look and feel

**Pull request closed without merging**
