### PR TITLE
enforce lowercase class name in .stylelintrc

### PR DESCRIPTION
**Pull request by coliff**
`"selector-class-pattern": "^[a-z]+([a-z0-9]?|[a-z0-9\\-]*[a-z0-9])$"`

I think this could be a useful addition, to prevent the use of a class name against the projects guidelines - mixed case or using underscores etc.
REF: http://codeguide.co/#css-classes

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
I think `^[a-z][a-z0-9\\-]*[a-z0-9]$` should do the job?

**Comment by MartijnCuppens** [comment]
@coliff, can you add an exception to `_syntax.scss`?

**Comment by XhmikosR** [comment]
I believe this regex needs more work, so don't merge this yet.

**Comment by XhmikosR** [comment]
OK, it seems the regex was fine after all: https://regex101.com/r/m7ynnv/3

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
