### PR TITLE
alert.js: Avoid calling jQuery('#'), it's a syntax error in jQuery 3.0

### PR DESCRIPTION
**Pull request by dmethvin**

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: dd77ecc8174426d0d2b91fb9e1025ed649cf2aac
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/134788284

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
@dmethvin Is there a plausible scenario where this could occur that doesn't involve user error?

**Comment by XhmikosR** [comment]
I wonder if this is the same error `$('a[href*=#]`.

**Comment by dmethvin** [comment]
>  Is there a plausible scenario where this could occur that doesn't involve user error?

I'm honestly not sure but since it was happening in a unit test I assumed it might be done by users as well.

> I wonder if this is the same error $('a[href*=#].

No, although that is also an invalid CSS selector. Special characters in attribute values must be quoted, per the spec.

**Comment by XhmikosR** [comment]
>No, although that is also an invalid CSS selector. Special characters in attribute values must be quoted, per the spec.

Agreed, it's just that it stop working in a patch version build so it was a little unexpected :/

Now, about this PR, do you think you can add a test for this case?

**Comment by dmethvin** [comment]
> Now, about this PR, do you think you can add a test for this case?

It was failing an existing test case before this PR, so I figured that fixing that one was enough. The failing test [has this markup](https://github.com/twbs/bootstrap/blob/209288a199ab2974192c829a0aec89d0c71e4f3f/js/tests/unit/alert.js#L51).

**Comment by XhmikosR** [comment]
Oh, cool. Then I have no objection in merging this. @cvrebert push the button if you agree.

**Comment by cvrebert** [comment]
The current v3 docs don't use the `<a class="close" href="#" data-dismiss="alert">` markup anywhere. v3.0.0's docs had it in one place, where the live demo and the syntax-highlighted code were out of sync 😢 

On account of compatibility paranoia, I'm okay with merging this.

**Pull request merged**
