### PR TITLE
eslint-fix

### PR DESCRIPTION
**Pull request by sendilkumarn**
fix as per #19908

### CODE REVIEW

**Comment by cvrebert** [comment]
@sendilkumarn Travis build failed with your change; see https://travis-ci.org/twbs/bootstrap/jobs/133966843#L327

**Comment by sendilkumarn** [comment]
@cvrebert  Think some config mismatch. I will check this one. Running with global- no errors.

**Comment by sendilkumarn** [comment]
problem is 

`grunt-eslint` has to be updated. 

But when we update `grunt-eslint` to latest **18.1.0** which is having `eslint 2.0.0 ` will fail arrow functions return statement (refer)[https://github.com/eslint/eslint/issues/1493]

**Comment by cvrebert** [comment]
Yes, updating the rules without also updating ESLint isn't going to work.
Can't speak to the validity of the arrow functions thing since I haven't tried upgrading to v2 yet.
Anyway, I think a more thorough approach is needed for getting our ESLint up-to-date. I'll start looking into it tonight.
We appreciate your effort though!

**Pull request closed without merging**
