### PR TITLE
Update to support multiple targets for tabs

### LINKED ISSUE #19964: Support multiple targets for tabs
Bootstrap 3 supports multiple targets for tab controls - http://stackoverflow.com/questions/19719653/control-multiple-tab-contents-with-one-nav-tabs 

Bootstrap 4 does not support this, yet, but it is a useful feature. I have added a basic workaround for time being:

file: /js/src/tab.js

line: 116
`
 target = $(selector)[0]
`
to 
`
target = $(selector)
`

line: 138
`
this._activate(target, target.parentNode, complete)
`
to
`
for (i=0; i<target.length; i++) {
    this._activate(target[i], target[i].parentNode, complete);
}
`

### PR DESCRIPTION
**Pull request by amos-whitewolf**
Support multiple targets for tabs, fixes #19964

### CODE REVIEW

**Review by Johann-S — CHANGES_REQUESTED** [review]
Hi @amos-whitewolf, thank you for your PR ! 👍 

Can you add a unit test for your change please ?

**Comment by XhmikosR** [comment]
@Johann-S: maybe you add a test?

**Comment by XhmikosR** [comment]
@amos-whitewolf: can you rebase and also take care of the unit test?

**Comment by XhmikosR** [comment]
Closing due to lack of response. You can comment here and we can re-open the PR, if you decide to resume working on the requested changes.

*This is an automated reply*

**Comment by RaneMstSage** [comment]
Is there any update on this?

**Comment by dvmuccillo** [comment]
If the op replies and take care of the reviews, doens't this need a update on docs or an example to show when this use case is important or why bs support it?
Sorry if i missed some point that explain this.

**Comment by RaneMstSage** [comment]
> If the op replies and take care of the reviews, doesn't this need a update on docs or an example to show when this use case is important or why bs support it?
> Sorry if i missed some point that explain this.

Yeah, that's what I was looking for as well. As I am trying to use it break up news articles with other content, that are all linked via panels.

**Pull request closed without merging**
