### PR TITLE
Add possibility to define custom border color for disabled form controls

### PR DESCRIPTION
**Pull request by tu4mo**

### CODE REVIEW

**Review by MartijnCuppens — APPROVED** [review]
LGTM, good call making it `null` by default. Thanks @tu4mo!

**Comment by XhmikosR** [comment]
@MartijnCuppens: I assume we don't want this backported?

**Comment by MartijnCuppens** [comment]
Nope

**Comment by tu4mo** [comment]
I'd be happy to make another PR for 4-dev if you'll have it. @MartijnCuppens

**Pull request merged**
