### PR TITLE
updating readme

### PR DESCRIPTION
**Pull request by edwinfrc**

### CODE REVIEW

**Comment by edwinfrc** [comment]
working with readme

**Comment by edwinfrc** [comment]
working with repositorio github can i  pull request of changes

**Comment by edwinfrc** [comment]
you review the code

**Comment by edwinfrc** [comment]
send something changes

**Comment by Johann-S** [comment]
Please don't test on public repos! By doing so, you've notified 7,000 people watching this project that you're testing something. Not helpful to anyone 😟

**Comment by patrickhlauke** [comment]
@mdo could we please block this user from the project. he's been warned. twice.

**Pull request closed without merging**
