### PR TITLE
Make use of jekyll-toc's `no_toc_section` class.

### PR DESCRIPTION
**Pull request by XhmikosR**
TODO:

* [x] Update to the stable jekyll-toc version when it's out
* [x] Verify all ToCs are fine

### CODE REVIEW

**Comment by XhmikosR** [comment]
This actually works pretty well, waiting for the stable version to be released. No more hiding ToC entries. :)

**Comment by XhmikosR** [comment]
Update to v0.8.0 stable. Please confirm all looks good.

**Comment by XhmikosR** [comment]
OK, now that I check out the preview it seems it broke again.

**Comment by XhmikosR** [comment]
Hmm it seems only the preview is broken. Locally it's fine.

**Review by mdo — APPROVED** [review]
Didn't pull the changes, but if this simplifies a bit of CSS while cleaning up the TOC, I'm in :).

**Pull request merged**
