### PR TITLE
add docsearch

### PR DESCRIPTION
**Pull request by maxiloc**
Following my comment in #22711, I made this PR using the snippet I gave you so you can have
a look at how it looks.

zt79ksphmt

Happy to have your feedback on this.

### CODE REVIEW

**Comment by mdo** [comment]
Dope! Thanks for tackling this!

My only question is how can we hook this up so that it searches and navigates to the local docs when in development? I've grown quite accustomed to searching for pages when working on Bootstrap, and I imagine others might be confused when they jump to the production site. Any thoughts?

**Comment by maxiloc** [comment]
@mdo I updated the PR so the search also redirect correctly when in development mode.
Tell me if that works for you.

**Comment by mdo** [comment]
I cherry picked the commits from here and have them in #22716 now. Woot! Thanks so much @maxiloc. Let me know how I can help ensure the index stays up to date (I can add it to our shipping checklist). Also take a look at that PR—I've tweaked the design a bit and would love your input.

**Comment by maxiloc** [comment]
Hey I have just checked the new design of the search, I am having some style issues with the dropdown. Is that expected ? Happy to help on this if needed.

image

Regarding the updates of the index, what we can propose is to run a reindex every 30min, would that work for you ?

**Comment by mdo** [comment]
Hmm, I'm not seeing that in Chrome or Safari on my end. Do you have the latest `dist` files built?

**Comment by maxiloc** [comment]
I pulled again, I don't have that anymore.

**Comment by mdo** [comment]
Commits were `cherry-pick`ed into my other branch, which just merged, so we're good to go!

**Pull request closed without merging**
