### PR TITLE
Improve build/zip-examples.js

### PR DESCRIPTION
**Pull request by XhmikosR**
* remove favicons meta tags
* copy the two brand images we use in the examples

`sh.sed` has the same limitations as the `sed` tool, hence this solution. Not perfect but does the job.

https://github.com/shelljs/shelljs#sedoptions-search_regex-replacement-file--file-

>Also, like unix sed, ShellJS sed runs replacements on each line from the input file (split by '\n') separately, so search_regexes that span more than one line (or include '\n') will not match anything and nothing will be replaced.

### CODE REVIEW

**Review by mdo — APPROVED** [review]
Tested locally

**Comment by XhmikosR** [comment]
I added one more patch which combines the dist and the assets folder, let me know what you guys think.

**Comment by XhmikosR** [comment]
@MartijnCuppens friendly ping

**Review by MartijnCuppens — APPROVED** [review]
Tested locally, LGTM

**Pull request merged**
