### PR TITLE
v4 - Accordion example should use cards

### PR DESCRIPTION
**Pull request by kkirsche**
Partial Fix: ~~#17157~~ #18375

~~Additional code needed to get cards to butt up against each other as expected.~~ 
Original (V3) isn't butted up against each other

Result:
screen shot 2015-08-20 at 3 36 08 pm

### CODE REVIEW

**Comment by hkdobrev** [comment]
You could use `.card-text` to better show the usage of cards as many people would copy from this example.

**Comment by kkirsche** [comment]
To me card text doesn't look right. If that's what people suggest I can but I personally don't find that to look like what I'd expect from an accordion.

**Comment by atu-record** [comment]
+1

**Comment by ryannealmes** [comment]
Hey guys,

I am playing around with v4 and noticed that the funcitonality for accordian doesn't quite match the existing functionality. It seems that the accordian does not collapse open cards when you click on another card.

See [fiddle](https://jsfiddle.net/aswognd9/) for example.

http://v4-alpha.getbootstrap.com/components/collapse/#accordion-example

Am I missing something? Maybe a setting?

Thanks.

**Comment by twbs-lmvtfy** [comment]
Hi @ryannealmes!

You appear to have posted a live example (https://fiddle.jshell.net/aswognd9/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 101, column 1 thru column 7: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 63, column 3 thru column 65: Unclosed element ```` div ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment]
Different issue and there's a PR to address it I believe.

**Comment by kkirsche** [comment]
Thanks, @mdo

**Pull request merged**
