### PR TITLE
Update Example Footers.

### PR DESCRIPTION
**Pull request by bhamodi**
This PR updates the footer examples and keeps them consistent.

### CODE REVIEW

**Comment by bhamodi** [comment]
@cvrebert - good to go?

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by XhmikosR** [comment]
LGTM

**Comment by bhamodi** [comment]
:shipit:

**Comment by arashataei** [comment]
Ok.     ....  What is LGTM
On Oct 27, 2015 6:32 AM, "Baraa Hamodi" <notifications@github.com> wrote:

[image: :shipit:]

—
Reply to this email directly or view it on GitHub
<https://github.com/twbs/bootstrap/pull/17879#issuecomment-151354700>.

**Pull request merged**
