### PR TITLE
Don't bind validation to form controls

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Alternative solution for https://github.com/twbs/bootstrap/pull/29228. This PR doesn't bind the `.is-valid` and `.is-invalid` classes to the form control.

Issue: https://codepen.io/browner12/pen/zgjKbJ?editors=1000
Solution: https://codepen.io/MartijnCuppens/pen/ExYyXBy?editors=1100

CC @browner12 

Closes https://github.com/twbs/bootstrap/pull/29228

### CODE REVIEW

**Comment by browner12** [comment]
Okay, so instead of binding to `.form-control .is-valid`, we are now just binding to `is-valid`, correct?

I'm okay with that solution, but it seems like this is probably a breaking change since we're becoming less specific, so it can only go to 5?

**Comment by MartijnCuppens** [comment]
We're switching from `.form-control.is-valid ~ .valid-feedback` to `.is-valid ~ .valid-feedback`. Since `~` only targets siblings, it's pretty safe to merge without introducing breaking changes IMO.

**Comment by browner12** [comment]
I would agree the risk is **extremely** low. Wasn't sure what our threshold is in this project.

**Review by ysds — APPROVED** [review]
@mdo Do you have any concerns?

**Review by mdo — APPROVED** [review]
No concerns here!

**Pull request merged**
