### PR TITLE
don't <kbd> all the things

### PR DESCRIPTION
**Pull request by PixnBits**
don't wrap individual &lt;kbd&gt;s with another &lt;kbd&gt;

### CODE REVIEW

**Comment by PixnBits** [comment]
Oh, nested was intentional: https://github.com/twbs/bootstrap/commit/f18bff0a7c10fe7afe4276029e9eda15e1f0c227

but at first I didn't see any visual differences, and it looked like a mistake (hence this PR)

image

vs. the un-nested

image

Maybe an explicit mention of nesting &lt;kbd&gt; instead?

**Comment by PixnBits** [comment]
Thoughts, @cecchi? (original commit author, per blame)

**Comment by patrickhlauke** [comment]
i'd say it's just a preference/quirk, not a deal breaker, semantically...

**Comment by cecchi** [comment]
I'm fine with it either way. I think I just added it to the docs to show that it's supported. Nested kbd's are occasionally useful things to have and probably make more sense visually as one "block". Some kind of entirely different styling might be more appropriate, however. I'll leave that call up to you guys.

**Comment by mdo** [comment]
Closing out for now then :).

**Pull request closed without merging**
