### PR TITLE
Collapse module supports multi-target

### LINKED ISSUE #17643: Collapse.js v4 only toggles one target?
http://www.bootply.com/1lBIRBwnA0 
This example, using Bootstrap v3, properly shows the two hidden rows when clicking the first plus button.

The same markup using the v4 source only toggles the _first_ row.

### PR DESCRIPTION
**Pull request by pvdlg**
Fixes #17643

This PR allow an `<a>` or `<button>` element to toggle multiple `collapse` area.
It preserve the ability to have a `collapse` being toggled by multiple `<a>` or `<button>`.

It relies on #21654 to handle collapse targets mo easily and efficiently (all the commits of #21654 are included here).

### CODE REVIEW

**Comment by Johann-S** [comment]
You made great work on this PR but IMO you shouldn't create a PR which tackle two differents issues and based on an other PR which isn't merged

**Comment by vanduynslagerp** [comment]
I agree @Johann-S. The thing is I have some time to spend on Bootstrap these days but I won't have that much soon. Therefore I couldn't really wait to make this PR, so I made the decision to include the commits of another one.

This PR relies #21654, and not using it would ends up writing more or less the same code twice, and handle a potentially complicated merge after, so it was better to include it.

That said, the PR include the actual commits of #21654 (same commits ID) which means that once #21654 is merged, the diff on this PR (#21692) will only show the commits actually related to collapse multi-target.

**Comment by nimmolo** [comment]
@vanduynslagerp from reading through the diffs it seemed these changes also support multi-target for tab.js - Is this the case?  for me it's not working with format   `data-target="#target1, #target1_aux"`

Here's my html, will put up a codepen if requested.

```
<a class="nav-link active" data-target="#target1, #target1_aux" data-toggle="tab" role="tab">Target 1</a>
<a class="nav-link" data-target="#target2, #target2_aux" data-toggle="tab" role="tab">Target 2</a>

<div id="myTabContent1" class="tab-content">
    <div class="tab-pane fade in active" id="target1" role="tabpanel">
        <p>Content 1.</p>
    </div>
    <div class="tab-pane fade" id="target2" role="tabpanel">
        <p>Content 2.</p>
    </div>
</div>

<div id="myTabContent2" class="tab-content">
    <div class="tab-pane fade in active" id="target1_aux" role="tabpanel">
        <p>Content 1.</p>
    </div>
    <div class="tab-pane fade" id="target2_aux" role="tabpanel">
        <p>Content 2.</p>
    </div>
</div>
```

**Comment by vanduynslagerp** [comment]
@nimmolo this PR does not add multi target support for tabs, only for collapse.
I saw your comment [here](https://github.com/twbs/bootstrap/issues/19964#issuecomment-276019764).
I can make another PR in a similar fashion that would allow multi-target for tabs.
That said issue #19964 is currently in the milestone [v4.1 ideas](https://github.com/twbs/bootstrap/milestone/37) so it might not lands right away or at all.

**Comment by nimmolo** [comment]
@vanduynslagerp I see. 

I'm definitely in favor, tabs with multi-target worked in BS 3. In my use case, targets are in different rows, but should appear together - the tabs take up part of the first row.

**Comment by vanduynslagerp** [comment]
@nimmolo I created a PR for multi-target tabs here #21882

**Comment by Johann-S** [comment]
Close because superseded by #22713
thank you for this awesome work 👍

**Pull request closed without merging**
