### PR TITLE
Update normalize.css to v4.0.0.

### LINKED ISSUE #19613: Update normalize.css to 4.0.0
Not sure what's the case with v4. I haven't followed the changes closely regarding reboot.

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @mdo @cvrebert: not sure if we are going with this or not, but decided to make a branch to test things.

Fixes #19613 (if merged)

### CODE REVIEW

**Comment by mrmlnc** [comment]
From Normalize 4 were deleted [styles for tables](https://github.com/necolas/normalize.css/commit/02c5c7adbbec1707900fde86068405735c733b42). 

```css
table {		
  border-collapse: collapse;		
  border-spacing: 0;		
}
```

**Before update Normalize to v4.0.0**
image


**After update Normalize to v4.0.0**
image

**Information**

  * OS: Windows 10 (build 1511)
  * Browser: Chrome 49.0.2623.87 m

**Comment by XhmikosR** [comment]
I'm aware of the changes. This is just for discussion with the rest of the team.

**Comment by mdo** [comment]
I'm probably more in favor of leaving it at v3.0.3 given the changes it'd require throughout v3 to support the upgrade. Minimizing change in v3 should be top priority.

**Comment by XhmikosR** [comment]
Cool, I'm closing the relevant issues and leave this for v4-dev (if it applies there).

**Pull request closed without merging**
