### PR TITLE
Docs: replace CSS by utilities in examples

### PR DESCRIPTION
**Pull request by julien-deramond**
### Description

* 890506513fe02c1d10b5dfddc0fba61fcad36008: Drop `.opacity-50` and `.opacity-75` definition since those utilities already exist
* 146c5963546e6181a2bc5b09c84c1e5560282091: Remove unused `.card-img-right`.
* b3421e152c4daf57b985064fe6ed6378838ee64d: Use `.lh-1` and `.lh-sm` when possible.
* 1ece9c4c3300d6a5d926ccdcc8e600962b4b1c3a: Move `.rounded-4`, `.rounded-5` and `.rounded-6` rules directly within `site/layouts/_default/examples.html` so that several examples can use those extended rounded utilities. Remove `border-radius` definitions when possible in CSS files and replace them by `.rounded-*`.
* 4979bcb384f2215123aec99d4cf447ccb0fb8756: Replace `.nav-underline` by `.nav-scroller` in order to share common definitions of `.nav-scroller` and `.nav-scroller .nav` in the default example HTML file.
* 9ee29fefc391a50f3783a24035720e386aeea6f7: Extract the `.mb-1` rule of `.blog-post-title`.
* 069f102fd3f8392e5a4561528158acdd825e7b46: Remove unused `.carousel-item > img` rule for carousels examples (there is no more ``). Use `.fw-*` utilities when possible.
* 106067d91089ea5bae4e4c4533a57437f4f8fa86: Use several utilities for cheatsheet examples.
* d0d94c034d6a1fcd7209d42bb6ee34505231917c: Use some utilities for `.nav-masthead .nav-link` in cover example.
* 6ef8f96eba310a30c5c6d608cef0dad0b9dc7bf9: Dashboard example refactoring
* 90577d469c89d916fa723072fa2c8ac820951173: Multiple minor modifications for the Dropdown example
* d2e36849faa72dd4365f34309019697c09805489: Fix linting issues due to the previous commit so I chose to drop the ids and create `.w-000px` classes instead in Dropdown example
* 24f02854e8fd9481d46ebe26cee8acdceb3bacbf: Features example refactoring
* 8d3332eb578d2bbd943a80a305c04c552a917504: Headers example refactoring
* b574af420735ea32bd230b6fce5a2eac4d2af09c: List groups example refactoring
* 202af505da4c23de0b1503fb2b67e446194e8f2b: Sidebars example refactoring
* 9b8744a96b95a08268d70e5ce45db4bc0793c799: Sign-in example refactoring
* ca4dba18dea7afee5b942ab7b07e974bf38bf103: Starter template refactoring
* 6cde9998c223e397974f887fe3cd67692d982982: And finally some fixes mainly for RTL examples because I've apparently forgotten them at the beginning :innocent: 

#### Checklist

- [x] `blog.css` / `blog.rtl.css`
- [x] `carousel.css` / `carousel.rtl.css`
- [x] `cheatsheet.css` / `cheatsheet.rtl.css`
- [x] `form-validation.css`
- [x] `cover.css`
- [x] `dashboard.css` / `dashboard.rtl.css`
- [x] `dropdowns.css`
- [x] `features.css`
- [x] `grid.css`
- [x] `headers.css`
- [x] `heroes.css`
- [x] `list-groups.css`
- [x] `modals.css`
- [x] `navbar-top-fixed.css`
- [x] `navbar-top.css`
- [x] `navbar.css`
- [x] `offcanvas.css`
- [x] `pricing.css`
- [x] `product.css`
- [x] `sidebars.css`
- [x] `signin.css`
- [x] `starter-template.css`
- [x] `sticky-footer.css`
- [x] `sticky-footer-navbar.css`

### Motivation & Context

Following [this comment](https://github.com/twbs/bootstrap/pull/35649#discussion_r786267865), this change will reduce the amount of specific CSS used by Bootstrap examples.

### Types of changes

- Refactoring (non-breaking change)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_

### Live previews

For non-regression testing:
* [Blog example](https://deploy-preview-35699--twbs-bootstrap.netlify.app/docs/5.1/examples/blog/)
* [Blog RTL example](https://deploy-preview-35699--twbs-bootstrap.netlify.app/docs/5.1/examples/blog-rtl/)
* [Carousel example](https://deploy-preview-35699--twbs-bootstrap.netlify.app/docs/5.1/examples/carousel/)
* [Carousel RTL example](https://deploy-preview-35699--twbs-bootstrap.netlify.app/docs/5.1/examples/carousel-rtl/)
* [Cheatsheet example](https://deploy-preview-35699--twbs-bootstrap.netlify.app/docs/5.1/examples/cheatsheet/)
* [Cheatsheet RTL example](https://deploy-preview-35699--twbs-bootstrap.netlify.app/docs/5.1/examples/cheatsheet-rtl/)
* [Cover example](https://deploy-preview-35699--twbs-bootstrap.netlify.app/docs/5.1/examples/cover/)
* [Dashboard example](https://deploy-preview-35699--twbs-bootstrap.netlify.app/docs/5.1/examples/dashboard/)
* [Dashboard RTL example](https://deploy-preview-35699--twbs-bootstrap.netlify.app/docs/5.1/examples/dashboard-rtl/)
* [Dropdowns example](https://deploy-preview-35699--twbs-bootstrap.netlify.app/docs/5.1/examples/dropdowns/)
* [Features example](https://deploy-preview-35699--twbs-bootstrap.netlify.app/docs/5.1/examples/features/)
* [Headers example](https://deploy-preview-35699--twbs-bootstrap.netlify.app/docs/5.1/examples/headers/)
* [List groups example](https://deploy-preview-35699--twbs-bootstrap.netlify.app/docs/5.1/examples/list-groups/)
* [Modals example](https://deploy-preview-35699--twbs-bootstrap.netlify.app/docs/5.1/examples/modals/)
* [Offcanvas Navbar example](https://deploy-preview-35699--twbs-bootstrap.netlify.app/docs/5.1/examples/offcanvas-navbar/)
* [Sidebars example](https://deploy-preview-35699--twbs-bootstrap.netlify.app/docs/5.1/examples/sidebars/)
* [Sign-in example](https://deploy-preview-35699--twbs-bootstrap.netlify.app/docs/5.1/examples/sign-in/)
* [Starter template](https://deploy-preview-35699--twbs-bootstrap.netlify.app/docs/5.1/examples/starter-template/)

### CODE REVIEW

**Comment by julien-deramond** [comment]
@ffoodd I suppose that you will be the reviewer of this PR at the end. For the moment I've gathered the modifications in separate commits so it will be easier to review. Do you want me to rather create 1 PR per type of modification or do I let it as it is in order to have a global overview of the modifications as well? What would be better to facilitate your review(s)?

**Comment by ffoodd** [comment]
Keep a single PR: we may drop individual commits if needed but will eventually squash everything to a single commit on `main`. 👌

**Comment by XhmikosR** [comment]
Love this so far, I appreciate the cleanup!

**Review by ffoodd — APPROVED** [review]
I just compared most of the examples without noticing anything. Seems good to me, thanks a lot!

**Review by mdo — APPROVED** [review]
Awesome work and very well organized here, thanks so much!

**Pull request merged**
