### PR TITLE
Replace bootstrap.css png with svg, shorten svg base64 url()s

### PR DESCRIPTION
**Pull request by tshinnic**
The desire in issue #18065 was to replace the single existing embedded
.png image with an equivalent SVG image, to go along with the other six
existing embedded SVG images.  An SVG image was duly produced.

Discussion regarding reducing the size of that `url()` embedded image
ensued, with a suggestion to try url-encoding.  In investigating that
it was realized that much of the SVG string was overhead which could be
discarded.  Experimentation found that url-encoding of SVG text would
_increase_ the size of the embedded `url()` strings.  In addition the
SVG texts were put through an `svgo` optimizer to drop some more chars.

The single .png image is replaced with a new SVG image, optimized and
base64 encoded.

The previously existing 6 SVG images were examined, minimized (unneeded
overhead metatext taken out), optimized, and base64 encoded.

All this combined reduces `dist/css/bootstrap.css` by 2448 bytes, and
`dist/css/bootstrap.min.css` by 2456 bytes.

Additionally, some left-over commented-out code is deleted from `scss/_forms.scss`.  I believe this was commented out in the process of turning the form icons into SASS variables?

### CODE REVIEW

**Comment by tshinnic** [comment]
I will be closing PR #18071 as this PR covers much more ground.  Some comments in there may be useful review.  More commentary and examples are found in [this codepen](http://codepen.io/tshinnic/pen/MaXNeZ)

At the end of all this work, the chief argument for the change is the CSS file size reduction due to the various minimizations/optimizations.

Below are display comparisons of the various icons and usages, before and after the changes:

**`_variables.scss`**:   $form-icon-success , $form-icon-warning , $form-icon-error
**`_forms.scss`**:        .form-control-success , .form-control-warning , .form-control-error
 &nbsp; &nbsp; before: &nbsp; &nbsp; before_form_control  &nbsp; &nbsp; &nbsp;  after: &nbsp;  &nbsp; after_form_control

.

**`_custom-forms.scss`**:  
.c-checkbox input:checked ~ .c-indicator 
.c-checkbox input:indeterminate ~ .c-indicator 

 &nbsp; &nbsp; before: &nbsp; &nbsp; before_checkbox_none &nbsp; &nbsp; &nbsp;  after: &nbsp;  &nbsp; after_checkbox_none
 &nbsp; &nbsp; before: &nbsp; &nbsp; before_checkbox_indeterminate &nbsp; &nbsp; &nbsp;  after: &nbsp;  &nbsp; after_checkbox_indeterminate
 &nbsp; &nbsp; before: &nbsp; &nbsp; before_checkbox_checked_hilited &nbsp; &nbsp; &nbsp;  after: &nbsp;  &nbsp; after_checkbox_checked_hilited
 &nbsp; &nbsp; before: &nbsp; &nbsp; before_checkbox_checked &nbsp; &nbsp; &nbsp;  after: &nbsp;  &nbsp; after_checkbox_checked
 &nbsp; &nbsp; before: &nbsp; &nbsp; before_checkbox_hilited &nbsp; &nbsp; &nbsp;  after: &nbsp;  &nbsp; after_checkbox_hilited

.

.c-radio input:checked ~ .c-indicator 
 &nbsp; before: &nbsp;before_radio_unchecked
&nbsp;  after: &nbsp;  &nbsp; after_radio_unchecked

 &nbsp; before: &nbsp;before_radio_checked_active
&nbsp;  after: &nbsp;  &nbsp; after_radio_checked_active

 &nbsp; before: &nbsp;before_radio_stacked_checked
&nbsp;  after: &nbsp;  &nbsp; after_radio_stacked_checked

.

.c-select 
 &nbsp; before: &nbsp; &nbsp; before_select  &nbsp; &nbsp; after: &nbsp;  after_select

All of these screen captures were taken in FireFox on Win10.

**Comment by tshinnic** [comment]
Regarding the CI / hound error messages: suggestions on how to proceed?  It's been too long since I've done that kinda magic.  How to modify/replace the commit?  Or just add another commit that fixes the oversight?

**Comment by wolfy1339** [comment]
In your local repository, edit the file then do ```git add .```, git commit --ammend then git push -f

**Comment by tshinnic** [comment]
@wolfy1339 Thank you.  Fixed fixes faxed and tacked!

Is the "This branch has conflicts..." just something that happens that the happy committers will deal with?  Wish I could 'see' what the conflicts are...  :frowning:

**Comment by tshinnic** [comment]
Ah, someone changed `_variables.scss` `$form-icon-error` to `$form-icon-danger`.  Hmm, a180a3362a42978de298a78300b3e39e36a45bf1 but with a spurious description?  What to do, who to do it?

**Comment by mdo** [comment]
Punting for #17222.

**Pull request closed without merging**
