### PR TITLE
Another pass at fixing floating labels disabled colors

### PR DESCRIPTION
**Pull request by mdo**
Alternate fix to #38159.

Will need to deprecate the `$form-floating-label-height` variable with this solution, or use it some other way, but it works without using the `:has()` selector. Approach here remaps the `opacity` value to an `rgba()` alpha channel, so we can just style based on background or a generated element. With this we could probably simplify more, but open to ideas.

### CODE REVIEW

**Comment by jonnysp** [comment]
unfortunately does not work in textarea without the form-floating-label-height after the height adjustment

**Comment by mdo** [comment]
Pushed another commit to fix that.

**Comment by jonnysp** [comment]
the label can be across the entire width and at the very top.
grafik

**Comment by mdo** [comment]
I didn't take the label all the way to the top because it can interfere with the shadow when shadows are enabled. Full width or auto width could be possible, will have to experiment.

**Comment by jonnysp** [comment]
this looks😎 good to me 👌

**Comment by mdo** [comment]
This fixes a few things for us, so going to merge as-is and we can ship and iterate.

**Pull request merged**
