### PR TITLE
Update modal.js

### PR DESCRIPTION
**Pull request by bbars**
Sometimes click on elements inside modal bosy passes through backdrop that causes modal close (try to place noUiSlider into Modal). So i've used mousedown && mouseup to handle backdrop click.

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 1eaa17023c8e20a09f692009f7f2862d8d88a27b
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/71280818

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
> (try to place noUiSlider into Modal).

JS Fiddle example please?

**Comment by bbars** [comment]
[Here is an example](http://jsfiddle.net/1cexx0tp/).
Of course, i understand, that it's a problem with nouiSlider. But these changes also improves backdrop-click-close action: you can prevent modal from being closed (accidental click) by moving you pointer into modal's body.

**Comment by twbs-lmvtfy** [comment]
Hi @bbars!

You appear to have posted a live example (http://fiddle.jshell.net/1cexx0tp/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 78, column 6 thru line 78, column 86: Attribute ```` name ```` not allowed on element ```` div ```` at this point.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by patrickhlauke** [comment]
What browsers/OSs are you experiencing the problems in? I just briefly tried that fiddle in both Chrome and Firefox on Windows, and saw no problems with the modal closing at any point when clicking around on the slider.

**Comment by cvrebert** [comment]
X-Ref: #14287

**Comment by cvrebert** [comment]
@bbars Also, this breaks the test suite; see https://travis-ci.org/twbs/bootstrap/jobs/71280763 and https://github.com/twbs/bootstrap/tree/master/js/tests

**Comment by patrickhlauke** [comment]
Ah, now I see. You mean the problem is if I click on the slider, move the mouse outside of the modal, and only then release the mouse button...

**Comment by bbars** [comment]
@patrickhlauke, yes, that's what I mean.

**Comment by cvrebert** [comment]
@bbars So, do you plan to update the testcases?

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Pull request closed without merging**
