### PR TITLE
Use z-index 3 to show focus state on all sides of input

### LINKED ISSUE #17001: Border color for input group on focus highlighted unevenly on right
I'm having the same problem which can be seen in BS documentation:
http://getbootstrap.com/components/#input-groups-buttons

Click on the right example "Search for...".  Notice how the blue border/outline on the right side is covered up.  The left example doesn't really have this problem.

screen shot 2015-08-17 at 8 48 00 pm

The blue comes from .form-control:focus { border-color, outline, webkit-box-shadow, box-shadow }  at least on my page.

My site is: http://www.morphmarket.com and you'll see the same issue on its search input and the middle button too.  I messed with Chrome inspector for a while, but this is beyond me -- and when I saw the docs had the same problem, I figured I could create an issue.   Thanks!

### PR DESCRIPTION
**Pull request by kkirsche**
Fixes #17001

JSBin with fix: http://jsbin.com/gifexipibu/edit?html,css,output

### CODE REVIEW

**Comment by kkirsche** [comment]
Travis, please restart tests

Failed to:
`The command "if [ "$TWBS_TEST" = validate-html ] && [ $TWBS_DO_VALIDATOR -ne 0 ]; then ./test-infra/s3_cache.py download rubygems; fi" failed and exited with 1 during .`

**Comment by jplehmann** [comment]
@kkirsche thanks so much for the fast fix!  That did solve the problem with the search input, although the border around buttons on the right look a little off -- this may be next to impossible to address. But this is acceptable to me.

screen shot 2015-08-18 at 9 21 49 am

For me the buttons on the right looked even worse, but I don't really need highlighting on those as much so I turned it off.
```
        #search-submit:focus, .advanced-search-button:focus {
          outline:0px !important;
          -webkit-appearance:none;
          box-shadow: none;
        }
    }
```

**Comment by kkirsche** [comment]
Essentially, if they are the same z-index the first item will not have the right focus. If the input is higher, the input will always have all sections of focus while the button will have 3. Vice versa, if the button is highest, the button will always have 4 but the input will always have 3

**Comment by cvrebert** [comment]
Filed bug regarding Travis error: #17011

**Comment by kkirsche** [comment]
Travis error fixed via: #17012

**Comment by kkirsche** [comment]
Travis restart

**Comment by cvrebert** [comment]
Won't do any good. You'd need to rebase to pick up the updated .travis.yml

**Comment by kkirsche** [comment]
@cvrebert good point. Just rebased to pull that in

**Comment by MohammadYounes** [comment]
I think you also need this to address the button focus:


```css
.input-group-btn:last-child > .btn:focus {
    z-index: 3;
}
```

input-group-btn-focus

**Comment by MohammadYounes** [comment]
Or better, only the focused element should get a higher z-index:

http://jsbin.com/cediwiqiko/2/edit?html,css,output

**Comment by mdo** [comment]
Looking at this again, I do believe we'd need to limit the `z-index` increase to be on focus for buttons and inputs, so we don't cause another bug for the buttons being behind on focus. Maybe that's already handled elsewhere though? It's been awhile since I looked at this :grin:.

**Comment by mdo** [comment]
Proper fix on `focus` coming in #18253.

**Pull request closed without merging**
