### PR TITLE
Optimize `fixed-*`, `.sticky*-top` classes

### PR DESCRIPTION
**Pull request by WinterSilence**
This solution based on [Mozilla manual](https://developer.mozilla.org/en-US/docs/Web/CSS/position#performance_accessibility)

### CODE REVIEW

**Review by ffoodd — COMMENTED** [review]
Promoting an element to its own layer might be done another way, mainly with `contain` which is dedicated to this.

`will-change` is supposed to indicate a property that will change, which is not the case here. It also opens the door to some memory issue, this property is not without performance drawbacks.

Another way could be `backface-visibility`, for example. If this is an issue, it needs a deeper understanding of what's going on.

**Comment by WinterSilence** [comment]
@ffoodd as I'm already say that' Mozilla solution. From debugger `will-change: transform`  create single layer for element, `will-change: position` not create

**Comment by WinterSilence** [comment]
@ffoodd [csswg.org post same info](https://drafts.csswg.org/css-will-change/#example-7225dcbc)

**Comment by XhmikosR** [comment]
Thanks for the patch but we'll pass on it for the reasons @ffoodd outlined above.

**Pull request closed without merging**
