### PR TITLE
V4 dev backports

### PR DESCRIPTION
**Pull request by XhmikosR**
Preview: <https://deploy-preview-30592--twbs-bootstrap.netlify.com/>

TODO:

- [x] Verify the dashboard changes are OK
- [x] Verify the a11y color changes in docs

### CODE REVIEW

**Review by Johann-S — APPROVED** [review]

**Comment by XhmikosR** [comment]
@MartijnCuppens can you confirm the dashboard and the a11y changes are OK and if so approve?

**Comment by MartijnCuppens** [comment]
Spotted 1 missing color change (`<!doctype html>` color), also fixed the commit message of this commit:
image

**Review by MartijnCuppens — APPROVED** [review]
:shipit:

**Comment by XhmikosR** [comment]
I actually didn't backport the whole #29208 only https://github.com/twbs/bootstrap/pull/29208/commits/9b97dc640f1f3777a7a60d5729f9ffecb4c7005e

**Comment by MartijnCuppens** [comment]
Ow, ok, shouldn't we just ditch the # than?

**Comment by XhmikosR** [comment]
It was referring to the commit hash, not sure why it wasn't highlighted.
I'll check it out later.

**Comment by MartijnCuppens** [comment]
> It was referring to the commit hash, not sure why it wasn't highlighted.

It wasn't highlighted because it was prefixed with `#`, fixed that in the latest push.

**Comment by XhmikosR** [comment]
> It wasn't highlighted because it was prefixed with `#`, fixed that in the latest push.

Duh! Thanks!

**Pull request merged**
