### PR TITLE
Fix custom checkboxes and radio buttons to wrap like native counterparts

### PR DESCRIPTION
**Pull request by mendozagioo**
This fix the issue #18020

### CODE REVIEW

**Comment by mendozagioo** [comment]
This fix the issue [18020](https://github.com/twbs/bootstrap/issues/18020)

**Comment by cvrebert** [comment]
Please don't commit `/dist/`, `/docs/dist/`, or `Gemfile.lock` files. They just lead to merge conflicts.

**Comment by mendozagioo** [comment]
I'm so sorry let me fix

**Comment by twbs-rorschach** [comment]
Hi @mendozagioo!

Thanks for wanting to contribute to Bootstrap by sending this pull request!
Unfortunately, your pull request seems to have some problems:
* [Changes must be made to the original Sass or Less source code file(s), not just the compiled CSS file(s).](https://github.com/twbs/rorschach/blob/master/docs/css.md)

You'll need to **fix these mistakes** and revise your pull request before we can proceed further.
Once you've fixed these problems, you can either ask the maintainers to re-open this pull request, or you can create a new pull request.
Thanks!

(*Please note that this is a [fully automated](https://github.com/twbs/rorschach) comment.*)

**Pull request closed without merging**
