### PR TITLE
Add container option to our Dropdowns

### PR DESCRIPTION
**Pull request by Johann-S**
Add container option to our Dropdowns

For those who wants to try : https://codepen.io/Johann-S/pen/EwoPYo

Fixes : #24251

### CODE REVIEW

**Comment by danijelGombac** [comment]
I was try this changes and it works fine, only the position of the dropdown is wrong on the first click. When you click again the position is ok.

**Comment by danijelGombac** [comment]
First click: translate3d(1625px, 406px, 0px)
Second click: translate3d(1642px, 406px, 0px)

**Comment by Johann-S** [comment]
Seems related to Popper.js :worried: 
/CC @FezVrasta

**Comment by Johann-S** [comment]
I'm able to reproduce what's described by @danijelGombac on this CodePen : https://codepen.io/Johann-S/pen/WZdrKj

**Comment by tmorehouse** [comment]
One caveat... if someone specifies a container when the dropdown is inside a collapsible navbar.  Would need to have a guard in there to prevent the dropdown from being re-parented in that case.

**Comment by Johann-S** [comment]
Good catch @tmorehouse ! :+1: 
I'll enable that feature only for dropdowns not in a navbar

**Comment by danijelGombac** [comment]
If you use this option with dropdown inside modal, the dorpdown position is wrong when scrolling modal.

**Comment by Johann-S** [comment]
You can call `update` of our Dropdown plugin it will update the position of your Dropdown 👍

**Comment by danijelGombac** [comment]
This happen when dropdown is inside overflow. Try open modal and dropdown.

https://codepen.io/danijelGombac/pen/OxZxZM

**Comment by Johann-S** [comment]
Not sure it's related to Bootstrap here @danijelGombac because it's Popper.js which handle the position

**Comment by danijelGombac** [comment]
Yes the problem is in Popper.js. It can't handle two overflow container if the first container is not position static.

https://codepen.io/danijelGombac/pen/OxZxZM

**Comment by Johann-S** [comment]
maybe @FezVrasta will have time to take look at this issue :smile:

**Comment by danijelGombac** [comment]
I hope. There could be also problems with tooltips and popover inside modal and table-responsive.

**Comment by Johann-S** [comment]
I made an issue to track that : https://github.com/FezVrasta/popper.js/issues/459

**Comment by Johann-S** [comment]
I found a solution to fix that @danijelGombac :+1:

**Comment by danijelGombac** [comment]
@Johann-S 

Why not apply this config option only when config.parent was used?

**Comment by Johann-S** [comment]
yep you're right seems better with that way !

**Comment by Johann-S** [comment]
done @danijelGombac :+1:

**Comment by tmorehouse** [comment]
Just thinking ARIA and tab order.

Will re-parenting to the body change the tab order of the menu items, since the menu items are no longer siblings of the menu trigger button?

**Comment by patrickhlauke** [comment]
indeed. unless focus is moved into the dropdown when it's opened and then kept there, this would be quite a broken experience for kbd users. (in the example in codepen, simply add some other focusable elements to the page to see the problem). so (just going by the example posted in the starter, not tried the actual code in this PR) i'd say no to this...

**Comment by tmorehouse** [comment]
The only way would be to test the focus order (simulating tab presses) before opening/reparenting and trapping tab/shift-tab to move focus to the correct items, but that would be really tricky and probably really buggy.

**Comment by tmorehouse** [comment]
WAI-ARIA recommends focusing the first item in dropdown menus when first opened, so that screen reader users are "inside" the dropdown, and that tabbing while inside the menu would close the menu and tab to the next document focusable item. Moving between menu items while opened is only handled by cursor up/down/left/right (although this doesnt work well for form controls (especially textarea)

This is what we have done in the Bootstrap-Vue implementation of Bootstrap V4 dropdowns (at the moment)

**Comment by patrickhlauke** [comment]
> WAI-ARIA recommends...

but these are not menus in the WAI-ARIA sense, merely generic expand/collapse dropdowns (as they can contain more than simply menu items). see https://getbootstrap.com/docs/4.0/components/dropdowns/#accessibility

**Comment by tmorehouse** [comment]
@patrickhlauke yeah, I've seen that section before, and it is why we haven't implemented forms inside dropdowns (yet), as the native Bootstrap V4 implementation is not as intuitive to some screen reader users.

We are thinking of adding n option to change from role `menu` to role `popup` when the dropdown contains form elements (other than standard acceptable menu items), and change from keyboard navigation (up/down) to pure tab only navigation.  Although this switch might be confusing to keyboard users (but not to screen-reader users).

**Comment by tmorehouse** [comment]
But back to the re-parenting discussion,  I think moving the menu to somewhere else in the body will be confusing to keyboard users (due to the possibility of getting "lost" in the document when tabbing around).

**Comment by patrickhlauke** [comment]
> We are thinking of adding n option to change from role `menu` to role `popup`

assuming you mean `dialog`, that was actually something i considered not long ago...making the trigger elements `aria-haspopup="dialog"` and treating the dropdown itself as a form of non-modal dialog (including managing the focus to remain inside it, possibly)

**Comment by tmorehouse** [comment]
Yep, meant to say 'dialog'.

**Comment by Johann-S** [comment]
I updated my Codepen : https://codepen.io/Johann-S/pen/EwoPYo
with the keyboard navigation fixed :+1:

**Comment by danijelGombac** [comment]
@Johann-S The tab key not working how it should. When tab is pressed the menu close.

**Comment by patrickhlauke** [comment]
keyboard navigation fixed how? see https://codepen.io/patrickhlauke/pen/ZaQzMR ... tab to open the dropdown, then tab again - focus moved to the "foo" links. and yes as noted, once user eventually gets to the dropdown itself, tab closes the menu.

i think the reparenting of the dropdown is not a good idea, as it just adds too many complications (in our current implementation)

**Comment by Johann-S** [comment]
Yep and change the behavior on how our Dropdowns work on TAB adds a lot of complexicity :worried: 
So we are stuck for this issue https://github.com/twbs/bootstrap/issues/24251

**Comment by FezVrasta** [comment]
I added some information useful to provide a workaround for #24251 and that could possibly replace the most basic usages of this very own PR

**Comment by tmorehouse** [comment]
Would some of the Popper.js overflow modifiers fix this? https://popper.js.org/popper-documentation.html#modifiers..preventOverflow

**Comment by tmorehouse** [comment]
I think PR #24976 provides a better solution without the need for re-parenting the `.dropdown-menu`, taking @FezVrasta 's idea (`position: static`) suggestion, and adding in Popper's `boundariesElement` modifier.

**Comment by Johann-S** [comment]
closed because https://github.com/twbs/bootstrap/pull/24976 is better :+1:

**Pull request closed without merging**
