### PR TITLE
Fix bug #16980

### PR DESCRIPTION
**Pull request by phmasek**
Added a check if there are more than one tab active, make the one with highest index inactive.

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 7c089f353acc00c508f478b4b1e1fd7797fd925d
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/82766255

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Pletron** [comment]
Seems like an unsuccessful test in something unrelated to my fix.

**Comment by cvrebert** [comment]
@twbs-savage Retry

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 7c089f353acc00c508f478b4b1e1fd7797fd925d
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/82779437

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
@twbs-savage Retry

Bloody Sauce...

**Comment by cvrebert** [comment]
@twbs-savage Retry

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 7c089f353acc00c508f478b4b1e1fd7797fd925d
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/82780525

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
@Pletron Please add a relevant unit test to the test suite. See https://github.com/twbs/bootstrap/tree/master/js/tests for details.

**Comment by Pletron** [comment]
@cvrebert There is an issue with creating a unit test for this particular bug fix. The fix addresses an issue that can only be replicated when running a `.click()` event. However, running such an event is not possible in the test suite (see image). The workaround is to run `$('#tab-button').bootstrapTab('show')`, but this does not replicate the issue.

click is not a function


I can write the unit test with the workaround, but it is completely obsolete for this purpose. What do you suggest?

**Comment by cvrebert** [comment]
Use `.trigger('click')` instead of `.click()`
Example: https://github.com/twbs/bootstrap/blob/79cdd66bbb53b8b55c4151c0b425062519f5a2e8/js/tests/unit/tab.js#L203

**Comment by Pletron** [comment]
ah sorry, need to redo to change coding convention.

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 5d60ee559ae42c360957badadcfe219ffd344e0f
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/82788162

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 6386cf2f14853b3231b4540996b05d6bbdbb3cde
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/82790083

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Pletron** [comment]
@twbs-savage Retry

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 7c089f353acc00c508f478b4b1e1fd7797fd925d
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/82789931

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
Hmm, actually, sounds like this involves transitions, in which case a unit test won't work because the test suite runs with transitions disabled. Guess this will need to be a manual visual test (https://github.com/twbs/bootstrap/blob/master/js/tests/visual/tab.html ) instead.

**Comment by Pletron** [comment]
Yeah, tried it there with the existing code through the console and it works fine. How would you suggest that I write the test there?

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 7c089f353acc00c508f478b4b1e1fd7797fd925d
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/82793802

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
Add another section to `/js/tests/visual/tab.html` with a set of tabs and a button with a click handler that runs `$('#myTab1 > :eq(1) a').click();$('#myTab1 > :eq(0) a').click();`.

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 8c1bfd76c3cd6b533094c586e69257e83a1fb6f4
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/82800632

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
Sauce failure is due to an unrelated Sauce error.

**Comment by Pletron** [comment]
@cvrebert Yes, seems like issues with Sauce. Anything more I can do here?

**Comment by cvrebert** [comment]
No, just needs code review now.
CC: @fat

**Comment by cvrebert** [comment]
Sorry, got the PR numbers mixed up.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Pull request closed without merging**
