### PR TITLE
Docs: fix some ARIA Authoring Practices Guides broken links

### PR DESCRIPTION
**Pull request by julien-deramond**
Backport of https://github.com/twbs/bootstrap/pull/36488 to v4.

### Live previews

* [Breadcrumb - Accessibility](https://deploy-preview-36490--twbs-bootstrap.netlify.app/docs/4.6/components/breadcrumb/#accessibility)
* [Collapse - Accessibility](https://deploy-preview-36490--twbs-bootstrap.netlify.app/docs/4.6/components/collapse/#accessibility)
* [Navs - Regarding accessibility](https://deploy-preview-36490--twbs-bootstrap.netlify.app/docs/4.6/components/navs/#regarding-accessibility)
* [Navs - JavaScript behavior](https://deploy-preview-36490--twbs-bootstrap.netlify.app/docs/4.6/components/navs/#javascript-behavior)

### CODE REVIEW

**Comment by romodog** [comment]
how im geetting text in there

________________________________
Från: Julien Déramond ***@***.***>
Skickat: den 3 juni 2022 07:50
Till: twbs/bootstrap ***@***.***>
Kopia: Subscribed ***@***.***>
Ämne: [twbs/bootstrap] Docs: fix some ARIA Authoring Practices Guides broken links (PR #36490)


Backport of #36488<https://github.com/twbs/bootstrap/pull/36488> to v4.

Live previews

  *   Breadcrumb - Accessibility<https://deploy-preview-36488--twbs-bootstrap.netlify.app/docs/5.2/components/breadcrumb/#accessibility>
  *   Collapse - Accessibility<https://deploy-preview-36488--twbs-bootstrap.netlify.app/docs/5.2/components/collapse/#accessibility>
  *   Nav & Tabs - Regarding accessibility<https://deploy-preview-36488--twbs-bootstrap.netlify.app/docs/5.2/components/navs-tabs/#regarding-accessibility>
  *   Nav & Tabs - JavaScript behavior - Accessibility<https://deploy-preview-36488--twbs-bootstrap.netlify.app/docs/5.2/components/navs-tabs/#accessibility>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/twbs/bootstrap/pull/36490

Commit Summary

  *   1f7e598<https://github.com/twbs/bootstrap/pull/36490/commits/1f7e5980fafc5263483fa27552a7bb40ddc993f8> Docs: fix some ARIA Authoring Practices Guides broken links

File Changes

(3 files<https://github.com/twbs/bootstrap/pull/36490/files>)

  *   M site/content/docs/4.6/components/breadcrumb.md<https://github.com/twbs/bootstrap/pull/36490/files#diff-41eb9e2fceec7dd49a9444886f8704839e7b7e3928822f2ad6178dd258458dce> (2)
  *   M site/content/docs/4.6/components/collapse.md<https://github.com/twbs/bootstrap/pull/36490/files#diff-eaf93a69b9c055f43f64ed6e84e1779726ec009452f97ca43ec32892a1392d68> (2)
  *   M site/content/docs/4.6/components/navs.md<https://github.com/twbs/bootstrap/pull/36490/files#diff-d58d2b25e7b65e548040189bca943c06c6f2d18eeb22cc5c27791f5baf672f05> (4)

Patch Links:

  *   https://github.com/twbs/bootstrap/pull/36490.patch
  *   https://github.com/twbs/bootstrap/pull/36490.diff

**Comment by romodog** [comment]
seriusly is there someone fucking with me agian?

________________________________
Från: Julien Déramond ***@***.***>
Skickat: den 3 juni 2022 07:50
Till: twbs/bootstrap ***@***.***>
Kopia: Subscribed ***@***.***>
Ämne: [twbs/bootstrap] Docs: fix some ARIA Authoring Practices Guides broken links (PR #36490)


Backport of #36488<https://github.com/twbs/bootstrap/pull/36488> to v4.

Live previews

  *   Breadcrumb - Accessibility<https://deploy-preview-36488--twbs-bootstrap.netlify.app/docs/5.2/components/breadcrumb/#accessibility>
  *   Collapse - Accessibility<https://deploy-preview-36488--twbs-bootstrap.netlify.app/docs/5.2/components/collapse/#accessibility>
  *   Nav & Tabs - Regarding accessibility<https://deploy-preview-36488--twbs-bootstrap.netlify.app/docs/5.2/components/navs-tabs/#regarding-accessibility>
  *   Nav & Tabs - JavaScript behavior - Accessibility<https://deploy-preview-36488--twbs-bootstrap.netlify.app/docs/5.2/components/navs-tabs/#accessibility>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/twbs/bootstrap/pull/36490

Commit Summary

  *   1f7e598<https://github.com/twbs/bootstrap/pull/36490/commits/1f7e5980fafc5263483fa27552a7bb40ddc993f8> Docs: fix some ARIA Authoring Practices Guides broken links

File Changes

(3 files<https://github.com/twbs/bootstrap/pull/36490/files>)

  *   M site/content/docs/4.6/components/breadcrumb.md<https://github.com/twbs/bootstrap/pull/36490/files#diff-41eb9e2fceec7dd49a9444886f8704839e7b7e3928822f2ad6178dd258458dce> (2)
  *   M site/content/docs/4.6/components/collapse.md<https://github.com/twbs/bootstrap/pull/36490/files#diff-eaf93a69b9c055f43f64ed6e84e1779726ec009452f97ca43ec32892a1392d68> (2)
  *   M site/content/docs/4.6/components/navs.md<https://github.com/twbs/bootstrap/pull/36490/files#diff-d58d2b25e7b65e548040189bca943c06c6f2d18eeb22cc5c27791f5baf672f05> (4)

Patch Links:

  *   https://github.com/twbs/bootstrap/pull/36490.patch
  *   https://github.com/twbs/bootstrap/pull/36490.diff

**Comment by patrickhlauke** [comment]
@romodog if you have something tangible to contribute, go ahead. if you're just going to leave random nonsensical comments here, they will be deleted. now cool your jets or you will be reported.

**Review by patrickhlauke — APPROVED** [review]

**Comment by patrickhlauke** [comment]
backport of https://github.com/twbs/bootstrap/pull/36488

**Pull request merged**
