### PR TITLE
Update _floating-labels.scss

### PR DESCRIPTION
**Pull request by jonnysp**
add "pointer-events none" to pseudo-element
same as #37359

### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

#### Live previews

Before
https://deploy-preview-38008--twbs-bootstrap.netlify.app/docs/5.3/forms/floating-labels/

After
https://deploy-preview-38023--twbs-bootstrap.netlify.app/docs/5.3/forms/floating-labels/

### CODE REVIEW

**Comment by julien-deramond** [comment]
Thanks for this PR @jonnysp. Indeed sounds better with this modification.
However don't you think the rendering is a bit frustrating with the readonly floating label? It sounds like you can select the label's text but when you try you can't.

**Comment by jonnysp** [comment]
that is correct. the input cannot be focused when it is selected with the mouse, in the upper half area. on firefox and chrome an edge.

it is not for the read only label.

**Comment by jonnysp** [comment]
Recording 2023-02-16 at 14 47 02

**Comment by XhmikosR** [comment]
@mdo @patrickhlauke regarding this.

We better be consistent here and make sure we still follow a11y best practices.

**Comment by patrickhlauke** [comment]
the problem isn't present on the current https://getbootstrap.com/docs/5.3/forms/floating-labels/ ... so I'm wondering what changes were introduced that caused the problem in the first place.

there's also something funky happening with disabled form fields https://deploy-preview-38023--twbs-bootstrap.netlify.app/docs/5.3/forms/floating-labels/#disabled

image

**Comment by julien-deramond** [comment]
FYI there was a conflict between several fixes on the floating labels between the v5.2.3 and v5.3.0-alpha1. Some use cases are broken in https://twbs-bootstrap.netlify.app/docs/5.3/forms/floating-labels/ (issues and PRs exist for that).
This PR is something else just to improve the clicking area but I admit it's a bit difficult to review without having the other fixes merged before.

IMHO the main issue that I can see here in this PR is about the readonly rendering where we can see the "selection" cursor when the labels are hovered even if we can't select their text (which is not the case in our _main_ branch):



The other use cases seemed to be enhanced when I looked at it the other day with an extended clickable area (possible to click on the upper area of the input to "enable" the input).

**Comment by patrickhlauke** [comment]
> FYI there was a conflict between several fixes on the floating labels between the v5.2.3 and v5.3.0-alpha1.

yeah sorry, what I meant is: i understand that, and am wondering if it's worth investigating how to resolve those conflicts at source, rather than trying to now just patch this one aspect with `pointer-events` on the floating label in this PR

**Pull request closed without merging**
