### PR TITLE
karma: stop excluding polyfill.js from istanbul

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by Johann-S** [comment]
I don't understand why do we need to remove that 🤔 we still have some polyfills

**Comment by XhmikosR** [comment]
It seems the custom coverage thresholds are no longer needed.

**Comment by Johann-S** [comment]
oh yeah saw that on Coveralls, how is it possible ? 🤔

**Comment by XhmikosR** [comment]
We have removed some polyfills.

**Comment by XhmikosR** [comment]
@Johann-S LGTY? The reason the file was excluded was the inline ignore comment. Arguably, the whole file could probably go away later see #32017

**Comment by Johann-S** [comment]
yep LGTM 👍 and indeed we should check if we still need those polyfills

**Review by Johann-S — APPROVED** [review]

**Pull request merged**
