### PR TITLE
Adds ARIA list and ARIA listitem to Carousel example

### LINKED ISSUE #23721: Suggestion: ARIA list on Carousel
There has been discussion, and incorrectly implemented ARIA listbox was removed in issues #22061 and #22543 by @patrickhlauke 

I would like to suggest the ARIA `list` https://www.w3.org/TR/wai-aria/roles#list and `listitem` https://www.w3.org/TR/wai-aria/roles#listitem roles to the `.carousel-inner` and `.carousel-item`.

Pull request to follow.

### PR DESCRIPTION
**Pull request by thejimbirch**
If accepted, would close #23721

### CODE REVIEW

**Comment by Johann-S** [comment]
I think you should update the doc component too

**Comment by thejimbirch** [comment]
@Johann-S The doc component is updated also.

**Comment by XhmikosR** [comment]
@patrickhlauke: looks good to you?

**Comment by patrickhlauke** [comment]
sorry, currently away for a week, not had a chance to review...

**Comment by XhmikosR** [comment]
Ah, no worries. Have a look when you are back :)

**Comment by clearyusc** [comment]
@examples

**Comment by XhmikosR** [comment]
ping @patrickhlauke

**Comment by thejimbirch** [comment]
Hi,

This was my first PR into this project, and it has been a while.  If I need to update anything, please let me know.

Thanks for all you guys do!
Jim

**Comment by patrickhlauke** [comment]
sorry @thejimbirch my fault. i'm currently swamped with day-job stuff, so haven't had a chance to review. it's not you, it's me. i'll carve out some time to make sure it's all ship-shape and ping you if there's anything that may need tweaking.

**Comment by davidrodbor** [comment]
ok

 

De: Patrick H. Lauke [mailto:notifications@github.com] 
Enviada em: terça-feira, 23 de janeiro de 2018 21:41
Para: twbs/bootstrap <bootstrap@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [twbs/bootstrap] Adds ARIA list and ARIA listitem to Carousel example (#23722)

 

sorry @thejimbirch <https://github.com/thejimbirch>  my fault. i'm currently swamped with day-job stuff, so haven't had a chance to review. it's not you, it's me. i'll carve out some time to make sure it's all ship-shape and ping you if there's anything that may need tweaking.

**Comment by XhmikosR** [comment]
@patrickhlauke: can you have a quick look? If it looks OK I'll fix the conflicts and merge.

**Comment by XhmikosR** [comment]
Ping @patrickhlauke

**Comment by XhmikosR** [comment]
Ping @patrickhlauke :)

**Comment by thejimbirch** [comment]
It's been almost a year, methinks he is not coming.

**Comment by mdo** [comment]
Closing as stale. Happy to revisit in the future though, so please open an issue and we can discuss. <3

**Comment by patrickhlauke** [comment]
apologies...this is mainly because carousel is such a contentious/specific widget that doesn't have one good/true way to make accessible. hoping to get somewhere closer to a good consensus position now that ARIA practices has at least one proposed reference implementation https://www.w3.org/TR/wai-aria-practices-1.1/#carousel

**Pull request closed without merging**
