### PR TITLE
0% > 0 for col-offset

### PR DESCRIPTION
**Pull request by efender**

### CODE REVIEW

**Comment by mdo** [comment]
Why would `$size` be less than `0` at any point?

**Comment by efender** [comment]
It be not less 0, but it may be 0 and we have "0px" instead of flat "0"

now:
```css
margin-left: 0px;
```
after
```css
margin-left: 0;
```

**Comment by mdo** [comment]
This is already handled by our build tools: https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L956-L958.

**Comment by efender** [comment]
But other people may build css from SCSS by their tools.

**Pull request closed without merging**
