### PR TITLE
docs: IE9 gradient.

### PR DESCRIPTION
**Pull request by XhmikosR**
before:
old

after:
new

/CC @mdo @cvrebert: the branch needs some cleanup before it's merged but I opened it for feedback.

### CODE REVIEW

**Comment by mdo** [comment]
Does Autoprefixer really not give us that?

**Comment by XhmikosR** [comment]
I don't see it there. I'll have a close look later again.

**Comment by XhmikosR** [comment]
How about borrowing the compass mixin?

**Comment by hnrch02** [comment]
@mdo Apparently not https://github.com/postcss/autoprefixer/issues/240.

**Comment by cvrebert** [comment]
I guess someone could try extracting a plugin for it from cssgrace (https://github.com/cssdream/cssgrace/blob/a81be90a944b7da7c0db366ba0de1aee6098b035/lib/index.js#L303 ).

**Comment by XhmikosR** [comment]
The thing is that it's only used in one place. Not sure it's worth adding a new mixin.

Other than that, I don't like my solution 100%. I'll tweak it later.

**Comment by XhmikosR** [comment]
All right, I tried splitting this up.

/CC @mdo @cvrebert @hnrch02

**Pull request merged**
