### PR TITLE
Updated callouts design for v5

### PR DESCRIPTION
**Pull request by mdo**
Screen Shot 2019-08-03 at 7 21 15 AM

### CODE REVIEW

**Comment by XhmikosR** [comment]
Can someone confirm the contrast ratio is OK now?

**Comment by XhmikosR** [comment]
Another point is this might look weird when we have a code snippet in a callout (for example yellow bg and light gray for the code block). But it's your call.

**Comment by ysds** [comment]
https://codepen.io/anon/pen/dxZEXz Please click the glasses icon at the bottom left, and check the "Contrast".

**Comment by mirorauhala** [comment]
Just leaving this here. I like this tool because it calculates the colors that are accessible. Makes it so much easier to work with accessible colors.

https://accessible-colors.com/

**Pull request closed without merging**
