### PR TITLE
[css] Fix breaking layout breaking error in code block

### PR DESCRIPTION
**Pull request by wackerm**
### Problem: Code block does not break long lines
[see miminal example](https://jsbin.com/dabopijehi/edit?html,output)

Was before:
`word-break: break-word;`
Should be (in my Opinion):
`word-wrap: break-word;`

### CODE REVIEW

**Comment by wackerm** [comment]
This change could/should also be done with current master...

The break-word option for word-break ist not supported by all browsers (for e.g. Firefox), [see ](https://developer.mozilla.org/de/docs/Web/CSS/word-break#Browserkompatibilit%C3%A4t), the break-word option with word-wrap is supported by all major browsers [see](https://developer.mozilla.org/de/docs/Web/CSS/word-wrap#Webbrowserkompatibilit%C3%A4t) and does fix the issue.

**Comment by XhmikosR** [comment]
Please retarget against master.

**Comment by wackerm** [comment]
Done:  retarget to master branch

**Comment by XhmikosR** [comment]
Friendly ping @twbs/css-review

**Review by MartijnCuppens — APPROVED** [review]

**Comment by XhmikosR** [comment]
Should this be backported to v4?

**Comment by wackerm** [comment]
I think that would be great since not everyone will upgrade existing v4 projects...
Shall i submit this patch as new PR against v4?

**Comment by XhmikosR** [comment]
Nah, if we are going to backport it, I'll cherrypick it.

**Comment by MartijnCuppens** [comment]
> Should this be backported to v4?

Yup, it's a bug

**Pull request merged**
