### PR TITLE
Switch to the Coveralls Action

### LINKED ISSUE #29457: Fix Coveralls Action
After we switched to GitHub Actions CI, the branch isn't passed on coveralls.

One way I've been experimenting is using `COVERALLS_GIT_BRANCH: "${{ github.ref }}"` but this results in `refs/head/branch` instead of `branch`, so it needs further manipulation.

There's an official action for coveralls, but it seems it leaves comments even when the setting on coveralls is disabled.

I'll try to find a solution soon.

### PR DESCRIPTION
**Pull request by XhmikosR**
This is the official way of using Coveralls with Actions. Also this brings back Coveralls for PRs.

~~Requires #29458 to be merged.~~

Fixes #29457

### CODE REVIEW

**Comment by mdo** [comment]
> * Remove the repo secret (`COVERALLS_REPO_TOKEN `) before merging this

Will that break the new integration? If not, let's keep tests from failing and remove afterwards maybe?

**Comment by XhmikosR** [comment]
This will only break for PRs or branches that might still use the old way. For master we won't have any problem. For v4-dev, I will cherry pick it in #29482 after this PR is merged.

**Comment by XhmikosR** [comment]
We are also getting rid of one devDependency BTW.

**Comment by XhmikosR** [comment]
Ping @mdo

**Comment by XhmikosR** [comment]
There's currently a [bug](https://github.com/coverallsapp/github-action/issues/5) which I really hope gets fixed soon because we end up with comments on PRs.

I've already switched to this action in a few of my other projects, it works well apart from the aforementioned issue.

I guess we can live for a while with a few comments?

**Comment by XhmikosR** [comment]
@mdo I really want to move forward with this. Can you get someone from GH to look into helping upstream to solve the extra comments issue https://github.com/coverallsapp/github-action/issues/5?

**Comment by XhmikosR** [comment]
This is blocked until the extra comments issue is solved

**Comment by XhmikosR** [comment]
The comments issue seems [fixed](https://github.com/coverallsapp/github-action/issues/5#issuecomment-553555754) so it should be OK to switch to this.

**Comment by XhmikosR** [comment]
@mdo you can remove the `COVERALLS_REPO_TOKEN` secret.

**Review by Johann-S — APPROVED** [review]

**Pull request merged**
