### PR TITLE
Docs accessibility fixes

### PR DESCRIPTION
**Pull request by XhmikosR**
IMO we should backport these.

@patrickhlauke: there are probably more color and general accessibility issues, but I try to solve the issues in batches. There's one thing that bugs me:

>This form does not contain a submit button, which creates issues for those who cannot submit the form using the keyboard. Submit buttons are INPUT elements with type attribute "submit" or "image", or BUTTON elements with type "submit" or omitted/invalid.

For the search form.

Preview: https://deploy-preview-29208--twbs-bootstrap.netlify.com/

### CODE REVIEW

**Comment by XhmikosR** [comment]
A few more syntax highlighting colors that fail right now:

1. #0a8 `.nc`
2. #099 `.cp`
3. #3aa `.sr`

Any suggestions welcome.

**Comment by MartijnCuppens** [comment]
Darkening the colors should be ok, I just did that in 200b0c0e80c70d7da4b686f08cc6d048608381ae

**Comment by XhmikosR** [comment]
@MartijnCuppens: not quite there yet :P The ratio seems to be 4.49 for `.cp` and `.nc` at least.

I personally use the https://squizlabs.github.io/HTML_CodeSniffer/ bookmarklet.

**Comment by MartijnCuppens** [comment]
I used Chrome's built-in colorpicker which can behave a little buggy it seems. Changed the values now

**Comment by XhmikosR** [comment]
I'll go through the pages tomorrow and see what else is left. I'm still not sure how to proceed with the search form.

**Comment by XhmikosR** [comment]
@patrickhlauke: friendly ping :)

**Comment by XhmikosR** [comment]
Alright, here's the list of the remaining syntax highlighting related issues:

* `mf`: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.79:1. Recommendation: change text colour to `#3e1900`.
* `mh`: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.79:1. Recommendation: change text colour to `#3e1900`.
* `mi`:This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.79:1. Recommendation: change text colour to `#3e1900`.
* `nd`: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.38:1. Recommendation: change text colour to `#00003e`.
* `nf`: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.98:1. Recommendation: change text colour to `#32003e`.
* `nn`: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 1.8:1. Recommendation: change text colour to `#00323e`.

They seem a little tricky since they are dark already

**Comment by XhmikosR** [comment]
Alright, I found a [pretty decent tool](https://github.com/Tanaguru/Contrast-Finder) so I'll go through this tomorrow and use the closest colors.

**Comment by XhmikosR** [comment]
I think this can be reviewed. We haven't heard from @patrickhlauke, so I guess we'll tackle the remaining stuff later.

@MartijnCuppens I changed the colors you changed, let me know if you agree with the new ones
@mdo @ysds please also have a look at the changes

**Review by MartijnCuppens — APPROVED** [review]
We better define the contrast color in `theme-colors.yml` instead of checking if the name is light or warning. Not sure if that should be tackled in this PR. If not, this LGTM

**Comment by XhmikosR** [comment]
How do you mean exactly? I think it would be better if we tackled it in a separate PR later, just don't forget about it.

For the time being, I just want another approval from @mdo or @ysds or @patrickhlauke

**Comment by XhmikosR** [comment]
Ping @mdo for review

**Comment by XhmikosR** [comment]
This looks good from my tests so far.

We need to double check these though:

```
.bd-callout-info { @include bs-callout-variant($bd-info); }
.bd-callout-warning { @include bs-callout-variant($bd-warning); }
.bd-callout-danger { @include bs-callout-variant($bd-danger); }
```

**Review by patrickhlauke — APPROVED** [review]

**Comment by patrickhlauke** [comment]
few more bits of low contrast i stumbled across while looking over https://deploy-preview-29208--twbs-bootstrap.netlify.com/ (some of these part of our core BS styles though, so not specifically documentation i guess)

non-text-content-low-contrast
2to1
3 4to1-4to1
4 4to1
4 4to1-2
4to1

**Comment by patrickhlauke** [comment]
the search form is probably tricky, as it's not really a form as such that you submit, but rather that you type in and get your results right away/supposed to select from the dropdown...bit of a quirky one.

i'd note though that there as well though, contrast starts to get quite low (around 4.3:1)

Annotation 2019-09-16 202637

**Comment by XhmikosR** [comment]
Yeah this doesn't fix all of the issues. I'll try to tackle the rest in
separate PRs.

**Pull request merged**
