### PR TITLE
Add a `gh` shortcode

### PR DESCRIPTION
**Pull request by XhmikosR**
WIP; I might end up changing the shortcode to accept named parameters too.

### CODE REVIEW

**Comment by ffoodd** [comment]
Very nice idea, it'll help a lot!

**Comment by mdo** [comment]
Very into it :)

**Comment by XhmikosR** [comment]
All right, I'll update the docs to use the shortcode as is, and we can always tweak it later :)

**Comment by XhmikosR** [comment]
After working on this a bit, I'm not sure having one shortcode is better. I'll revisit this, maybe by separating the shortcodes or going back to the original implementation, which has its limitations, but it's shorter to type.

**Comment by mdo** [comment]
Removing from v5.0.0 for now to help prioritize.

**Comment by XhmikosR** [comment]
Going to drop this. If anyone wants to take this up, feel free to CC me :)

**Pull request closed without merging**
