### PR TITLE
CSS: `$prefix` to the whole assets

### PR DESCRIPTION
**Pull request by louismaximepiton**
### Description

Changed `bs-` to `#{$prefix}`.

### Motivation & Context

Feel like it will ease the work on some forks for folks since they won't need to change every `bs-` in the scss files if they use a different prefix.
Following the additions done in https://github.com/twbs/bootstrap/pull/35857 in assets/brand for example.

### Type of changes

- [x] Refactoring (non-breaking change)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

- <https://deploy-preview-39617--twbs-bootstrap.netlify.app/>

### Related issues

NA

### CODE REVIEW

**Comment by julien-deramond** [comment]
I haven't looked at the details of this PR yet (thanks @louismaximepiton btw) but was there a technical reason @twbs/css-review for having `--bs` in `site/assets/scss/` instead of using the prefix? Seems to be there voluntarily.

**Comment by ffoodd** [comment]
Docs aren't initially meant to be customized, I guess. I think we had this discussion when we first introduced custom properties in the docs.

**Comment by julien-deramond** [comment]
I'll try to look at it asap but the original idea of the PR `bs-` to `#{$prefix}` is interesting. Even if our doc is not meant to be customized, since it is compiled in this same project, having `#{$prefix}` could help while searching for patterns. But I might missing something here.

**Review by julien-deramond — APPROVED** [review]
Based on mdo's feedback, let's continue with the same approach in our doc. Thanks @louismaximepiton for your PR. LGTM!

**Pull request merged**
