### PR TITLE
Update devDependencies

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by XhmikosR** [comment]
This seems to break Travis CI for some reason.

**Comment by cvrebert** [comment]
Wacky, considering that https://travis-ci.org/twbs/bootstrap/builds/46017809 passed...

**Comment by XhmikosR** [comment]
Yeah, I saw that but it keeps failing for some reason :/

**Comment by cvrebert** [comment]
Trying to fix with #15507.

**Comment by XhmikosR** [comment]
Seems to still fail. Did you update Jade recently?

**Pull request merged**
