### PR TITLE
WebKit styles fix for form-control-plaintext

### PR DESCRIPTION
**Pull request by astrahov**

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/)/[JS Bin](https://jsbin.com/) or [Stackblitz](https://stackblitz.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

*This is an automated reply*

**Comment by astrahov** [comment]
OS X: 10.14.6
Chrome: 77.0.3865.75
Bootstrap: 4.3.1

1. Click to plaintext field

https://codepen.io/alexstrakhov/pen/jONjxva

**Comment by MartijnCuppens** [comment]
Not sure if we should set an alternative focus state here. @patrickhlauke, what do you think?

**Comment by florianlacreuse** [comment]
See #29442

**Comment by ysds** [comment]
Since accessibility reason, focusable elements should have focus style like blue focus ring. The `:focus-visible` pseudo-class would solve the uncomfortable style of the time the target element is clicked, but it is not yet available. https://caniuse.com/#search=%3Afocus-visible

So closing this.

**Pull request closed without merging**
