### PR TITLE
Override margins and paddings on navbar-brand elements

### LINKED ISSUE #19349: .navbar-brand with non-anchor element isn't vertically centered
This issue is one issue that can be fixed in two different ways that somewhat make it seem like it's two different issues :cat: 

If we look at the `.navbar-brand` on the [docs](http://v4-alpha.getbootstrap.com/components/navbar/#brand) you'll see this pretty vague statement:

> The .navbar-brand can be applied to most elements, but an anchor works best

The `working best` part shows up immediately in the examples below because the `h1.navbar-brand` element is not vertically aligned:

image

There are two ways to solve this:

1. Always reset and setup the margins paddings etc. for the `.navbar-brand`-elements or

2. Make a mention about the users needing to change the CSS if other elements that `a` are being used, sort of like how the v3 version mentions [overriding CSS when using images](http://getbootstrap.com/components/#navbar-brand-image)

### PR DESCRIPTION
**Pull request by kevinkucharczyk**
closes #19349

### CODE REVIEW

**Comment by cvrebert** [comment]
For future reference, including "fixes #NNN" in the commit message (see https://help.github.com/articles/closing-issues-via-commit-messages/ ) would be appreciated.

**Comment by mdo** [comment]
Rather than do this, shouldn't we just encourage the use of margin utilities?

**Comment by kevinkucharczyk** [comment]
@mdo yeah, perhaps that might be the better solution. I'm okay with closing this PR without a merge.

However, this does raise a question: should Bootstrap require users to add additional classes (which, for some, could be seen as counter-productive and markup-polluting) or should it just work in the majority of cases?

**Comment by mdo** [comment]
Updated the docs to include an example for this in back in c8bd62b214add34ab133cb11241d528ef3402ef0.

**Pull request closed without merging**
