### PR TITLE
Remove hover states on background utilities

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Ref https://github.com/twbs/bootstrap/issues/28444. (going to trigger the fixes thing in the deprecation PR for `v4`)

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
@XhmikosR, I was thinking about doing another PR for `v4-dev` to add the deprecation warning, but this will be a commit that will not be present in the `v5` branch, is that a problem?

**Comment by XhmikosR** [comment]
No, but since we haven't merged `v4-dev-new`, you can push it there. BTW, are you sure we won't be able to cherry pick it?

**Comment by XhmikosR** [comment]
BTW, we still need to add here backport or v4 labels since we need to track the changes somehow.

**Comment by MartijnCuppens** [comment]
In `v5` we remove the mixin, in `v4` we throw a deprecation warning, it's different.

**Comment by XhmikosR** [comment]
Ok then just reference the issue somehow in the v4 project so that we don't
miss it in the release notes.

**Review by mdo — APPROVED** [review]

**Pull request merged**
