### PR TITLE
Tighten bundlesize limits.

### LINKED ISSUE #28007: Make bundlesize limits tighter

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #28007

### CODE REVIEW

**Comment by XhmikosR** [comment]
We could go even tighter, not sure though.

**Review by Johann-S — APPROVED** [review]

**Review by MartijnCuppens — APPROVED** [review]
These limits should be ok, decreasing them further would probably cause failing tests when any changes are done.

**Comment by XhmikosR** [comment]
See, the thing is that I'd rather have build failures and us bump the limit then than get a change that's causing a .5KB change like it recently happened. Remember, this is gzip size.

I'll think about it a bit more.

**Comment by mdo** [comment]
We can probably knock down Reboot's limits, too, right? We seem way under for that.

**Comment by XhmikosR** [comment]
Yeah, I was thinking about that also @mdo. We could go to 2KB there.

**Comment by XhmikosR** [comment]
OK, limits updated.

**Review by mdo — APPROVED** [review]

**Pull request merged**
