### PR TITLE
Dropdown keyboard fixes

### LINKED ISSUE #32954: dropdown keyboard fixes
BTW does it make sense to open the dropdown but not select the first/last element depending on the arrow key?

I feel like it's an extra key. But that's for later too. :)

_Originally posted by @XhmikosR in https://github.com/twbs/bootstrap/pull/32750#issuecomment-770921055_

### PR DESCRIPTION
**Pull request by sijusamson**
Fixes #32954

### CODE REVIEW

**Comment by patrickhlauke** [comment]
Purely checking the behavior here, this seems to do what it sets out to do - go to https://deploy-preview-33161--twbs-bootstrap.netlify.app/docs/5.0/components/dropdowns/, set focus to a dropdown, and use cursor up/down; this opens the menu *and* sets focus to the first focusable element.

@twbs/js-review to have a proper look at the JS code changes themselves

**Comment by rohit2sharma95** [comment]
@sijusamson Your branch needs rebase :slightly_smiling_face:

**Comment by alpadev** [comment]
Since this PR seems to be stalled. Closing this in favor of #34052

**Comment by sijusamson** [comment]
> Since this PR seems to be stalled. Closing this in favor of #34052

Well may i know why this PR was stalled? 
I am going to rebase it. @alpadev

**Comment by alpadev** [comment]
You didn't add any tests yet. Patrick mentioned about the arrow keys like two weeks ago and there was no reply from your side. How I should know you're still on it?

**Comment by sijusamson** [comment]
> You haven't added any tests yet. Patrick mentioned about the arrow keys like two weeks ago and there was no reply from your side. How I should know you're still on it?

For tests,i was working on it. And regarding Patrick's comments, he didnt ask to change anything, and moreover he asked for a review from js team. 
Correct me if i am wrong here.

**Comment by XhmikosR** [comment]
Guys, no need to argue here. It's clearly a misunderstanding. @alpadev went with the quickest approach.

We have so many issues that you will always have a chance to work on something else @sijusamson :) Just remember to always add tests please.

**Comment by sijusamson** [comment]
> Guys, no need to argue here. It's clearly a misunderstanding. @alpadev went with the quickest approach.
> 
> 
> 
> We have so many issues that you will always have a chance to work on something else @sijusamson :) Just remember to always add tests please.

Sure @XhmikosR. I will take care about testing from next time onwards.

**Comment by alpadev** [comment]
Yeah sorry, I wasn't to take it away or anything. It's just there were no updates from your side within the last 3 months. The branch had merge conflicts, lacked tests and the behaviour that was asked in the issue wasn't fully implemented.

When Patrick mentioned it, there was no response whatsoever, like asking if this should be changed or something.

I figured you are busy or don't care anymore, that's why I just did it.

**Comment by sijusamson** [comment]
> Yeah sorry, I wasn't to take it away or anything. It's just there were no updates from your side within the last 3 months. The branch had merge conflicts, lacked tests and the behaviour that was asked in the issue wasn't fully implemented.
> 
> 
> 
> When Patrick mentioned it, there was no response whatsoever, like asking if this should be changed or something.
> 
> 
> 
> I figured you are busy or don't care anymore, that's why I just did it.

No worries. Well, i should have responded too. Anyways i will take up some new issues.

**Pull request closed without merging**
