### PR TITLE
Make accordion icon rotation more natural

### PR DESCRIPTION
**Pull request by inwardmovement**
Preview: https://deploy-preview-33292--twbs-bootstrap.netlify.app/docs/5.0/components/accordion/

### CODE REVIEW

**Comment by mdo** [comment]
Hmm, I’ve come back to this a couple times and I’m not sure one way or another. Any references for what makes this more natural versus what’s there currently?

**Comment by inwardmovement** [comment]
This feels more natural to me as it's a clockwise rotation, but I guess in the end it's pretty subjective indeed.

In Microsoft or Google UIs I found both rotations are used (but I'm not sure they are designed like this on purpose, maybe it's a detail they don't care much about).

I feel generally "clockwise" is more intuitive as we see it everyday on clocks/watches.
Clockwise ≈ forward/develop, counter-clockwise ≈ backward/collapse ?

**Comment by alecpl** [comment]
It could use `rotateX(180deg)` transition, so there's no discussion about the rotation anymore ;)

**Comment by mdo** [comment]
I'm fine merging this—I agree going with clockwise makes sense.

**Pull request merged**
