### PR TITLE
Fix docs for heading sizes

### PR DESCRIPTION
**Pull request by TiGR**
Sizes here were from v3. Fixed these to correspond with v4.

Should rem sizes be also added to docs?

### CODE REVIEW

**Comment by tomlutzenberger** [comment]
The v4-dev branch has been copied to master and the former master is now v3-dev.
Not sure if it is already fixed yet.

**Comment by TiGR** [comment]
@tomlutzenberger Are you sure about that? I can't see v4 in master, master is v3.

```
$ git describe master --tags
v3.3.7-5-g7e2741e
$ git describe v4-dev --tags
v4.0.0-alpha.4-2-g34291cc
```

I kinda messed up this pull request because tried to merge it on master, and everything went loose.

**Comment by tomlutzenberger** [comment]
Well, at least that was @mdo's plan less than 24hrs ago.
Oh sh***... I'm sorry about that :disappointed: 
Do you work from CLI or do you use a GUI for Git? The latter makes it easy to see how many commit the upstream master is ahead.

**Comment by mdo** [comment]
There have been no changes to `master`—it's just no longer the default branch. v4 fixes should be submitted against v4-dev, and v3 fixes should be submitted against v3-dev.

**Pull request closed without merging**
