### PR TITLE
Suggest alternative approaches for .hidden and .show in migration docs

### PR DESCRIPTION
**Pull request by lamby**
Signed-off-by: Chris Lamb chris@chris-lamb.co.uk

### CODE REVIEW

**Comment by PauloFrancaLacerda** [comment]
.h, .s
:)

**Comment by lamby** [comment]
> .h, .s

Hm? I don't see that on this branch.

**Comment by Lemmmy** [comment]
I would recommend `.invisible` first.

**Comment by takuhii** [comment]
.visible and .obscure ?

**Comment by leetskills** [comment]
What about the `hidden` attribute?

**Comment by mdo** [comment]
Added @leetskills's suggestion, clarified the usage of those new options, and fixed some Markdown formatting in 72d68ba. Merged—thanks!

**Pull request merged**
