### PR TITLE
Move the linkinator test in `npm t`.

### PR DESCRIPTION
**Pull request by XhmikosR**
Only thing I'm not sure about is running these in parallel. Some more testing should help decide.

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
> Only thing I'm not sure about is running these in parallel.

What could be a problem here?

**Comment by XhmikosR** [comment]
The whole thing being slower compared to running the tests sequentially :P

I doubt it, but I could use more testing from others.

**Comment by XhmikosR** [comment]
Can someone test this?

**Comment by Johann-S** [comment]
it works fine to me 👍

**Review by MartijnCuppens — APPROVED** [review]

**Pull request merged**
