### PR TITLE
Drop Bower support

### PR DESCRIPTION
**Pull request by tkrotoff**
Bower is deprecated.

screen shot 2017-08-19 at 19 09 46

See https://github.com/bower/bower/issues/2298

Dropping Bower will allow to split Bootstrap in multiple npm packages, see https://github.com/twbs/bootstrap/issues/23557#issuecomment-323519254 and following comments.

Ping @XhmikosR

### CODE REVIEW

**Comment by XhmikosR** [comment]
@tkrotoff: maybe [this](https://github.com/twbs/bootlint/blob/master/bower.json) solution would be better?

@mdo: please chime in; it is sort of a breaking change but Bower seems to be absolete nowadays, so it would be better if we provided a proper npm way to do things as we discussed in #23557

**Comment by mdo** [comment]
Asked Twitter to weigh in :D. I'm unsure on overall usage—I don't think Bower ever had install stats like npm does on their packages. Hard to know how used it is.

**Comment by jerguslejko** [comment]
I vote: "drop it".

**Comment by rowdyrabouw** [comment]
Drop it vote!

**Comment by auvipy** [comment]
drop it

**Comment by zacharysohovich** [comment]
Drop it

**Comment by chyvak1831** [comment]
keep it

**Comment by dfosco** [comment]
If it means Bootstrap having multiple npm packages, I'm all in for dropping bower.

**Comment by zacharysohovich** [comment]
@chyvak1831 I feel like the argument for dropping is there. Do you have an argument for keeping it?

**Comment by Arseur** [comment]
I happen to use Bootstrap via Bower but would be happy to hear of a better way to proceed.

**Comment by dRagonsRage** [comment]
Keep it

**Comment by alexdreptu** [comment]
Drop it. There's no need for it to exist anymore. It's better for everyone to focus entirely on npm.

**Comment by igghera** [comment]
Drop it

**Comment by cto1** [comment]
Drop it

**Comment by cba85** [comment]
Drop it like it's hot

**Comment by ernitishkumar** [comment]
Dracarys

**Comment by mubeen-inamdar** [comment]
Drop it

**Comment by cvrebert** [comment]
Drop it. It's been abandoned and practically superseded by npm for a while now.

**Comment by XhmikosR** [comment]
So @mdo it seems most people are in favor of this. Only concern is VS?

**Review by XhmikosR — APPROVED** [review]

**Comment by christopherdarling** [comment]
Drop it

**Comment by mgwoolf** [comment]
Drop it

**Comment by jloosli** [comment]
Drop it

**Comment by UlisesCabrera** [comment]
Drop it

**Comment by dw-roth** [comment]
drop

**Comment by blikblum** [comment]
Drop

**Comment by curtsheller** [comment]
Drop It!

**Comment by nesk** [comment]
Drop it. Multiple npm packages would be great!

**Comment by alex-page** [comment]
Drop it +1

**Comment by lednhatkhanh** [comment]
Drop it

**Comment by vladimirmartsul** [comment]
Drop it

**Comment by tkrotoff** [comment]
@XhmikosR @cvrebert About bower.json `@$% Not a Bower package... ^&*` like in Bootlint can you explain how this works?

**Comment by cvrebert** [comment]
@tkrotoff That's just blatantly invalid JSON to make it clear that Bootlint deliberately doesn't support Bower.

**Comment by PhillipMwaniki** [comment]
Keep it.

**Comment by myorangeca** [comment]
keep it

**Comment by kanhaic** [comment]
Drop it npm is better.

**Comment by ph1p** [comment]
Drop it.

**Comment by kvz** [comment]
There's so many fundamental issues with bower that, even if it causes breakage in cases, even for myself, I'd vote drop it. We'll fix those cases and move the whole ecosystem to brighter future with npm catering to all our packaging needs. If twbs sets this example I'm sure many will follow suit 👍❤️

**Comment by tkrotoff** [comment]
@XhmikosR @cvrebert git rewrote history and kept bower.json with `@$% Not a Bower package... ^&*` in it.

**Comment by michaelsnook** [comment]
I vote drop. 

Bower is kind of dead to me nowadays.

**Comment by xpose2000** [comment]
Keep. I still use bower.

**Comment by benmann** [comment]
I'd decide based on the workload it creates to still support Bower. It's always nice to keep backwards compatibility, however if it involves some serious work on your end and is possibly blocking a more modular approach (which could likely be achieved with Bower as well?!) I'd say go with npm/yarn instead.

**Comment by tkrotoff** [comment]
Bootstrap 3 will continue to be available with Bower. This only applies to v4. If you have an old project, this changes nothing.
If you create or upgrade a project to cutting edge Bootstrap 4, it does not make sense to rely on a deprecated tool for your project.

And Bower is deprecated, *really*:

- [Bower website](https://bower.io/) displays the deprecation notice
- same for the README:

screen shot 2017-08-21 at 12 12 17

- and even when installing Bower:
```
$ npm install bower
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained,
we recommend Yarn and Webpack for *new* front-end projects!
Yarn's advantage is security and reliability,
and Webpack's is support for both CommonJS and AMD projects.
Currently there's no migration path,
but please help to create it: https://github.com/bower/bower/issues/2467
```
<br><br>
To all people who replied "Keep it", why?

**Comment by wrakky** [comment]
Does dropping Bower also mean that all the compiled code in `dist/` and `js/dist/` can be removed and ignored from the repo or is there still a reason to include it?

**Comment by Johann-S** [comment]
We use our dist files for our documentation too, so they'll stay if we drop Bower

**Comment by benmann** [comment]
> Bootstrap 3 will continue to be available with Bower. This only applies to v4. If you have an old project, this changes nothing.

As we're also advising people to use yarn/webpack for **new** projects, this sounds like a neat solution. 👯

**Comment by smilingpeanut** [comment]
I vote for keeping Bower support.

**Comment by liederer** [comment]
Please drop it.

**Comment by robertpetras** [comment]
Drop it.

**Review by mdo — APPROVED** [review]

**Pull request merged**
