### PR TITLE
Feature Request - New Width Classes 

### LINKED ISSUE #31289: Feature Request - New Width Classes
`width: fit-content` -> `w-fit` would be great

Other options:

`width: min-content` -> `w-min`
`width: max-content` -> `w-max`

Could add the same for height, but not sure it's as useful.

### PR DESCRIPTION
**Pull request by Segolene-Alquier**
This PR implements the feature requested in this issue: https://github.com/twbs/bootstrap/issues/31289
We just reopened [this PR](https://github.com/twbs/bootstrap/pull/31485) (it seemed no one was working on it at the moment) and we took into account the comments made in it.

Me & @mattvgn made the following changes:
- add min-content, max-content and fix-content to width / max-width / min-width
- modify documentation accordingly

Let us know if we need to change anything, we'd be glad to do it 🤓

https://deploy-preview-31943--twbs-bootstrap.netlify.app/docs/5.0/utilities/sizing/

Fixes #31289

### CODE REVIEW

**Comment by Segolene-Alquier** [comment]
I'm not sure about all the diff files since we only modified two. 🧐
I had some issues coming from prettier linter. Do you think this is where it comes from?

**Comment by MartijnCuppens** [comment]
Hi @Segolene-Alquier!

- Please don't commit dist files.
- I'm not sure what `w-fit-content` does exactly without parameters, is there any documentation available somewhere?

**Comment by Segolene-Alquier** [comment]
> Hi @Segolene-Alquier!
> 
> * Please don't commit dist files.
> * I'm not sure what `w-fit-content` does exactly without parameters, is there any documentation available somewhere?

Hi @MartijnCuppens,

- Just fixed the committed dist files issue, sorry about that! 🙈
- Regarding the fit-content property on width, here are some articles we found on the topic:
https://css-tricks.com/almanac/properties/w/width/#fit-content
https://stackoverflow.com/questions/30704073/what-is-the-difference-between-css-fit-content-and-max-content

Let us know if it's clear enough for you or if you see any changes that should be done 🤓

**Comment by MartijnCuppens** [comment]
Thanks for the links!

I'm ok with adding these classes as width utilities, but I'm unsure if they'll be used a lot in `max-width` and `min-width`.

**Comment by Segolene-Alquier** [comment]
It was suggested in [this PR](https://github.com/twbs/bootstrap/pull/31485) to add the property to `max-width` and `min-width` but I'm not sure either 🧐

**Comment by ffoodd** [comment]
It was a question, not a suggestion 🙃

I'm not used to these keywords and this need some research or feedback from people already using it.

**Comment by mattvgn** [comment]
> I'm not used to these keywords and this need some research or feedback from people already using it.

I was able to find that using [this tool](https://www.chromestatus.com/metrics/css/timeline/popularity/161) : 

Capture d’écran 2020-10-29 à 14 17 16

Indeed this is quite niche but it's different for max-content and min-content

Capture d’écran 2020-10-29 à 14 22 18
Capture d’écran 2020-10-29 à 14 22 38

I don't know how to geed feedback on that, do you have any idea ?

**Comment by mattvgn** [comment]
Hello, any news on this ? What should we do based on the data we found ? @MartijnCuppens

**Comment by mdo** [comment]
Given our utilities are customizable through the API, I feel like we don't need these classes in the default set of utilities. Thinking we skip this, but perhaps offer a list somewhere of additional utilities folks may want to include? Not sure how much that makes sense, but open to suggestions!

**Comment by XhmikosR** [comment]
@ffoodd @MartijnCuppens it seems we also have #31485 which adds the same utilities but lacks docs. Feel free to close on of the two.

**Comment by mdo** [comment]
I'm still of the opinion we can hold on these additional utilities. Thoughts on skipping for now @MartijnCuppens and @ffoodd?

**Comment by ffoodd** [comment]
IMHO it depends on our grid usage for our own grid—if we follow [@MartijnCuppens suggestion to use custom properties](https://github.com/twbs/bootstrap/pull/31813#issuecomment-717128028), adding `width` utilities will be required.

**Comment by mdo** [comment]
That PR won't be seeing any changes to how grid columns work I'm afraid. Too late to make those kind of changes, and personally I think too much of a departure from our existing grid.

**Comment by mdo** [comment]
Going to close this out as stale and remove from v5.3.0 consideration. Apologies for any wasted time and effort here! <3

**Comment by gravelld** [comment]
Here's an example use case: https://stackoverflow.com/a/78322642/28190

With a `.list-inline` inside `.row >.col` inside a dropdown, we needed to use `max-width: fit-content !important` on the children of the `.row`s (and also the surrounding `.dropdown-menu`).

**Pull request closed without merging**
