### PR TITLE
Collapse with flex elements - simple approach

### LINKED ISSUE #22600: Using collapse on display:flex elements ie: row
I found this same problem in closed #20442, and I was wondering if it will be revisited for beta. Since row is `display:flex`, and `collapse.show` sets `display:block`, the displayed row is off.

```
<div class="container">
    <div class="row">
        <h4 class="col">
        <a href="#details" data-toggle="collapse">
            <span>Expand</span>
        </a>
      </h4>
    </div>
    <div id="details" class="row collapse" aria-expanded="false">
        <div class="col-6">
            <h3>Text</h3>
        </div>
        <div class="col-6">
            <h3>Text</h3>
        </div>
    </div>
    <div class="row" aria-expanded="true">
        <div class="col-6">
            <h3>Text</h3>
        </div>
        <div class="col-6">
            <h3>Text</h3>
        </div>
    </div>
</div>
```

http://codeply.com/go/UuAQvoRMiC

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Fixes #22600 

Simple solution instead of #22758. This solution doesn't add a display property to an element when it's visible.

Demo: https://codepen.io/MartijnCuppens/pen/jzNyyy

cc @Johann-S @mdo @XhmikosR

### CODE REVIEW

**Comment by Johann-S** [comment]
It's a pretty smart solution ! 👍 I'll close my PR 😉

**Comment by andresgalante** [comment]
Agreed, this is smart, great job @MartijnCuppens

**Review by XhmikosR — APPROVED** [review]
LGTM

**Review by mdo — APPROVED** [review]

**Comment by Johann-S** [comment]
Hi @robbieaverill please open a new issue, I you think we should mention that on our migration docs

**Comment by Johann-S** [comment]
I think we should make a section from 4.0 to 4.1, can you open a new issue and explain the breaking change you found

**Comment by robbieaverill** [comment]
Thanks @Johann-S, see https://github.com/twbs/bootstrap/issues/27385

**Pull request merged**
