### PR TITLE
Use named constants for magic numbers

### PR DESCRIPTION
**Pull request by cvrebert**
Mostly `KeyboardEvent.which` and `MouseEvent.which` values.

/fyi @XhmikosR @hnrch02

### CODE REVIEW

**Comment by XhmikosR** [comment]
Much better, nice!

**Comment by patrickhlauke** [comment]
Great stuff

**Comment by hnrch02** [comment]
Nice improvement. Would've been great to use [`KeyboardEvent.key`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) but support is apparently wonky.

**Comment by cvrebert** [comment]
Actually, I have a patch in the works to use `.key` if it's available. I just need to write the tests.

**Pull request merged**
