### PR TITLE
Use `--bs-border-width` for some components

### LINKED ISSUE #37326: The alert borders ignore border-width
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The alert borders use `--bs-alert-border` which explicitely sets, both, the width and the style of the border to `1px` and `solid`, respectively. In particular, it doesn't make use of `--bs-border-width` so utilities like `.border-2` have no effect.

### Reduced test cases

From bootstrap.css, we find: `--bs-alert-border: 1px solid var(--bs-alert-border-color);` and `.border-2` simply sets: `--bs-border-width: 2px;` which has no effect in the alert.

My workaround was a class `.alert-border` setting `--bs-alert-border: var(--bs-border-width) solid var(--bs-alert-border-color);` although it should probably have `--bs-border-style` instead of `solid`, but there are no utilities to set that variable.

### What operating system(s) are you seeing the problem on?

Windows, Android, Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.2.1

### PR DESCRIPTION
**Pull request by jonnysp**
### Description

Use border-width classes on some components
to combine utility borders (border-1, boder-2, ...) on these.
like "card border-2", "alert border-4" , ...

### Motivation & Context

Fixes #37326

### Type of changes

adds variable border-width to some components.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [ ] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [ ] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

#### Live previews

- https://deploy-preview-{your_pr_number}--twbs-bootstrap.netlify.app/

### CODE REVIEW

**Comment by mdo** [comment]
@jonnysp Can you check linter errors and bundle watch? (Bump the later by .25kb increments)

**Comment by mdo** [comment]
Thanks!

**Comment by rxbracho** [comment]
Thank you for closing the bug #37326, I assume it is fixed but not yet in 5.2.2 so I will continue with my workaround.  Do I understand correctly that this fix, which included that bug, is slated for 5.3.0?  If so, I will wait, thank you.  BTW, I placed a comment in that original bug, responding to the request for a CodePen.

**Comment by zackd** [comment]
seeing some issues where variables are not working with calc() e.g.
`margin-left: calc($input-border-width * -1);`


using interpolation fixes this: 
`margin-left: calc(#{$input-border-width} * -1);`

**Comment by jonnysp** [comment]
> seeing some issues where variables are not working with calc() e.g. `margin-left: calc($input-border-width * -1);`
> 
> using interpolation fixes this: `margin-left: calc(#{$input-border-width} * -1);`

I can't see any problems here.
can you describe this in more detail.

**Comment by julien-deramond** [comment]
@zackd If there are any issues, please [create a new one](https://github.com/twbs/bootstrap/issues/new?assignees=-&labels=bug&template=bug_report.yml&title=Provide+a+general+summary+of+the+issue) and add a link to this PR (or any other elements) in the description. It's easier for us to track things.

**Comment by zackd** [comment]
@jonnysp so the source scss is `margin-left: calc($input-border-width * -1);`
and the _generated_ css is `margin-left: calc($input-border-width * -1);` .. which obviously is not valid
changing the scss to `margin-left: calc(#{$input-border-width} * -1);` 
outputs css like `margin-left: calc(1px * -1);` .. which I assume is what is intended 

If this looks like an genuine issue I'll create a ticket ...

**Comment by jonnysp** [comment]
the generated is  https://github.com/twbs/bootstrap/blob/0d27f3c284f1b2450e6aee5c61e7040a30c8e190/dist/css/bootstrap.css#L2746

**Pull request merged**
