### PR TITLE
Improve steps for documentation building

### PR DESCRIPTION
**Pull request by hkdobrev**
In Boostrap v4 without running `bundle install`, `jekyll serve` would not work. In addition to Rouge one should also install required Jekyll plugins. I also had errors for missing `celluloid`.

I've also ran `grunt grunt update-gemfile-lock`, let me know if I should revert this.

Closes #17051.

### CODE REVIEW

**Comment by XhmikosR** [comment]
This seems obsolete now. Maybe do a rebase to see the remaining changes against v4-dev. Note that I have skipped celluloid 0.16.1 on purpose because it requires a removed `timers` version.

/CC @glebm @cvrebert

**Comment by mdo** [comment]
Closing for now. Please open a new PR or comment here if there's anything we missed. Thanks! <3

**Comment by hkdobrev** [comment]
Thanks guys! I think you should mention using `bundle install` for the dependencies as you are using a Gemfile and instructions for dependencies mentioned in the README can get out of the date. I can open a PR for that.

**Comment by XhmikosR** [comment]
I have an issue opened for that part. Please make a new pull request and CC
me.

**Pull request closed without merging**
