### PR TITLE
SSR friendliness improvements

### PR DESCRIPTION
**Pull request by TCB13**
Further improvements to https://github.com/twbs/bootstrap/pull/34989 in order to work in Angular's SSR / pre-rendering as described at https://github.com/twbs/bootstrap/pull/34989#issuecomment-1507443744 and https://github.com/twbs/bootstrap/pull/34989#issuecomment-1507612188.

Also updated the dist files to make it easier to use. Until this is merged anyone can use this fixes:
````
npm install "https://github.com/TCB13/bootstrap.git#jo-ssr-friendly" --save
````

### CODE REVIEW

**Comment by TCB13** [comment]
Also update the code to be on v5.2.3.

**Comment by XhmikosR** [comment]
Thanks for the PR but this is no go. First of all, your patches should be clean, you included 524 patches.

Secondly, the approach from #34989 isn't the best one, see the comments there.

**Comment by TCB13** [comment]
> Thanks for the PR but this is no go. First of all, your patches should be clean, you included 524 patches.

Yes I merged the last the last stable version into the branch. About the way this was approached, the thing is that this keeps being pushed and bootstrap doesn't still work in SSR contexts.

**Comment by XhmikosR** [comment]
Well, we have a branch which needs a proper rebase for starters.

Secondly, the lint approach does not cover all the cases last time I had a look.

That being said, you are welcome to propose a clean approach with the least changes and we can discuss it there. #34989 needs to close because is abandoned.

**Comment by TCB13** [comment]
> That being said, you are welcome to propose a clean approach with the least changes and we can discuss it there. #34989 needs to close because is abandoned.

Well, I was trying to revive #34989 . 

> Secondly, the lint approach does not cover all the cases last time I had a look.

Does it need to? I guess we don't really need to cover 100% of the cases, just make it so bootstrap can be used on pre-rendering contexts like Angular's or vue-prerender. An headless browser will not click on buttons and expand menus, it just needs to load the page, save the HTML and move on. 

With that said, the problem isn't that objects such as `document` are required but that Bootstrap will call them right away on load. I understand why it does it but for pre-rendering purposes a simple way of telling Bootstrap to NOT register any even listeners or run additional code would be enough.

**Pull request closed without merging**
