### PR TITLE
Update devDependencies

### PR DESCRIPTION
**Pull request by XhmikosR**
Notes:
1. I simply disabled `latedef` for collapse.js. We could refactor the code instead
2. Only issue left is https://github.com/twbs/bootstrap/commit/0820da3f52b83415a694ba181d7bbc5e3dd2cc68#commitcomment-16466850

TODO:
- [x] Change the instructions for bundle if we go with this approach.
- [x] Clean up env globals
- [x] Caching doesn't seem to work with trusty image
- [x] Fix the qunit failure

/CC @cvrebert @patrickhlauke (for the validation fixes)

### CODE REVIEW

**Comment by XhmikosR** [comment]
@cvrebert: the custom caching seems to fail with the Trusty image. We probably need to install something manually.

**Comment by cvrebert** [comment]
> the custom caching seems to fail with the Trusty image

Try deleting the `sudo pip install` line entirely. Looks like Trusty might have our boto dependency preinstalled (albeit an older but potentially-still-compatible version).

**Comment by XhmikosR** [comment]
Let's see.

**Comment by cvrebert** [comment]
> Should I add 4 and 5 or just keep 0.12 then?

`¯\_(ツ)_/¯`
Depends on what we're willing to support. I'm just saying that we're locked into `0.12` as a lower bound for BS3 at this point. The upper bound is presently undefined.

**Comment by XhmikosR** [comment]
@cvrebert: it just keeps failing. Feel free to push here if you have any ideas.

**Comment by cvrebert** [comment]
We should probably switch to Travis' built-in caching.

**Comment by XhmikosR** [comment]
Should we use bundle in master too?

**Comment by XhmikosR** [comment]
@cvrebert: I added bundle, switched to Travis cache. **If** it finishes without errors, it should be good to go.

**Comment by XhmikosR** [comment]
Oh, and we'll need to change the instructions for bundle if we go with this approach.

**Comment by XhmikosR** [comment]
On a side note, I don't see any caches on Travis. Must be after the Trusty change.

**Comment by XhmikosR** [comment]
So, it works but it I just feel Travis is so slow these days. Plus we get one failure in qunit tests, which I don't get :/

**Comment by XhmikosR** [comment]
Updated. Still getting that qunit failure on Travis but I don't get it locally.

**Comment by XhmikosR** [comment]
So, any feedback @cvrebert?

**Comment by XhmikosR** [comment]
OK, so I cannot figure out why the qunit tooltip fails. Here's what I get locally:

```
Running "qunit:files" (qunit) task
Testing js/tests/index.html

Starting test suite
================================================

√ All tests passed in "alert plugin" module
√ All tests passed in "alert" module
√ All tests passed in "button plugin" module
√ All tests passed in "button" module
√ All tests passed in "carousel plugin" module
√ All tests passed in "carousel" module
√ All tests passed in "collapse plugin" module
√ All tests passed in "collapse" module
√ All tests passed in "dropdowns plugin" module
√ All tests passed in "dropdowns" module
√ All tests passed in "modal plugin" module
√ All tests passed in "modal" module
√ All tests passed in "scrollspy plugin" module
√ All tests passed in "scrollspy" module
√ All tests passed in "tabs plugin" module
√ All tests passed in "tabs" module
√ All tests passed in "tooltip plugin" module
.........................................
Math.round($tooltip.offset().left):  203
Math.round($target.position().left + $target.width() / 2 - $tooltip[0].offsetWidth / 2):  203
√ All tests passed in "tooltip" module
√ All tests passed in "popover plugin" module
√ All tests passed in "popover" module
√ All tests passed in "affix plugin" module
√ All tests passed in "affix" module
OK
>> 469 assertions passed (4321ms)

Done, without errors.


Execution Time (2016-03-07 12:22:55 UTC)
qunit:files  6.4s  █████████████████████████████████████████████████ 100%
Total 6.4s
```

**Comment by cvrebert** [comment]
Aside from the weird QUnit failure, these changes look fine.

**Comment by cvrebert** [comment]
I'll try to look up which env vars we can kill later today.

**Comment by XhmikosR** [comment]
I don't want to merge it with the qunit failure though. But I'm out of ideas since I cannot reproduce it on my machine.

**Comment by cvrebert** [comment]
Have you tried not upgrading `grunt-contrib-qunit`?

**Comment by XhmikosR** [comment]
All dependencies are the latest available in this branch.

**Comment by XhmikosR** [comment]
Wait, I misread. Let me check the old qunit.

**Comment by cvrebert** [comment]
Testing whether npm@3 makes a difference: https://travis-ci.org/twbs/bootstrap/jobs/114228161

**Comment by XhmikosR** [comment]
I'm gonna update qunit itself too just in case.

**Comment by cvrebert** [comment]
Tried forcing the phantomjs npm package to download its own phantomjs binary (v2.1.1); didn't make a difference; tests still passed locally.

Perhaps it's Linux-specific. Either a bug in phantom or maybe that test relies on font sizes and Trusty has a slightly different font.

**Comment by XhmikosR** [comment]
The thing is, that it seems bad to me to have that failing test in master regardless of how much I'd like to merge this. Still trying to isolate the cause.

**Comment by XhmikosR** [comment]
So it seems this passes https://travis-ci.org/twbs/bootstrap/builds/114229261

**Comment by cvrebert** [comment]
Great! Can you squash the downgrade into bf9ca54 so we simply never upgrade it in the first place?

**Comment by XhmikosR** [comment]
Will do, I just wanted to leave it like that in case your fix in https://travis-ci.org/twbs/bootstrap/builds/114231056 works.

**Comment by cvrebert** [comment]
Nope, my experiment failed.

**Comment by XhmikosR** [comment]
Rebased, mentioned it in the commit message. Feel free to merge or push here your env vars cleanup.

**Comment by XhmikosR** [comment]
I also update uglifyjs for customizer since there was a security release some time ago.

**Comment by cvrebert** [comment]
Removed the now-unnecessary S3 env vars.

**Comment by cvrebert** [comment]
Travis hasn't added caching support to their Trusty image: https://github.com/travis-ci/travis-ci/issues/4997

**Comment by XhmikosR** [comment]
That explains why builds have been so slow :/

What do you want to do about that? Should I try another approach for java?

**Comment by XhmikosR** [comment]
@cvrebert: so can we get this in after Travis is done?

**Comment by cvrebert** [comment]
:shipit:

**Pull request merged**
