### PR TITLE
Remove firefox workaround for `::file-selector-button` margin

### PR DESCRIPTION
**Pull request by emilio**
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1673895,
this workaround shouldn't be necessary in FF83+.

TODO:
- [x] Remove workarounds for `.form-control-sm` & `.form-control-lg`

Preview: https://deploy-preview-32064--twbs-bootstrap.netlify.app/docs/5.0/forms/form-control/#file-input

### CODE REVIEW

**Comment by XhmikosR** [comment]
We support Firefox >= 60

https://github.com/twbs/bootstrap/blob/0766a096055a4f34c795e77f0e5c024310d20ef4/.browserslistrc#L7

**Comment by emilio** [comment]
That pseudo-element is Firefox 82+, see the above bug.

**Comment by emilio** [comment]
cc @MartijnCuppens

**Comment by MartijnCuppens** [comment]
@emilio, this will be added to FF83 beta 9 I assume? Can we test it somewhere, because I can only download beta 8 from https://www.mozilla.org/en-US/firefox/channel/desktop/?

**Comment by emilio** [comment]
@MartijnCuppens yes, it should be in 83b9, but you can also test it on a Nightly build from https://nightly.mozilla.org

**Comment by MartijnCuppens** [comment]
LGTM in Nightly (Dutch preview):
image

In FF82, there will be a little more padding, but that's acceptable imo:
image

**Review by MartijnCuppens — APPROVED** [review]

**Comment by ffoodd** [comment]
Just to be sure @MartijnCuppens, following up @XhmikosR comment: I assume this screenshot is the intended look & feel for Firefox < 83?

Capture d’écran de 2020-11-05 16-49-38

**Comment by emilio** [comment]
That'd be FF <82, I guess.

**Comment by ffoodd** [comment]
≤ 82, < 83 :)

**Comment by MartijnCuppens** [comment]
> I assume this screenshot is the intended look & feel for Firefox < 83?

For FF ≤ 81, yup!

**Pull request merged**
