### PR TITLE
Add note: floats don't mix with miscellaneous modules

### LINKED ISSUE #25829: .float-right doesn't work inside a .row
The button in the HTML below ([codepen.io](https://codepen.io/anon/pen/aYOQxL)) remains left-aligned despite the `float-right` class.

``` html
<!DOCTYPE html>
<html>
<head>
  <title>.float-right issue</title>
  <link rel="stylesheet" href="css/bootstrap.css">
  <style>.row { background-color: #ff8621; }</style>
</head>
<body>
  <div class="container">
    <div class="row">
      <button class="btn btn-primary float-right">To the right!</button>
    </div>
  </div>
</body>
</html>
```

Firefox 58.0.2, linux/amd64

### PR DESCRIPTION
**Pull request by Varunram**
Closes #25829. Could change where we place the sentence, open to suggestions (I just thought creating a new section with caveats would be bad).

### CODE REVIEW

**Comment by danijelGombac** [comment]
I use it with grid system, but i need to add d-block clearfix to row. It's seems to work fine. But i can't use flex utility.

**Comment by mdo** [comment]
> I use it with grid system, but i need to add d-block clearfix to row. It's seems to work fine. But i can't use flex utility.

You shouldn't be doing that. If you're reverting to floats, you should just avoid the grid entirely and roll your own custom stuff. Try out the flexbox approach more before jumping to that.

**Comment by danijelGombac** [comment]
@mdo 

I am trying few days play with flexbox, but without a result. The problem is that flex item can't be in two flexbox line.

https://codepen.io/danijelGombac/pen/yKoXGB

**Comment by mdo** [comment]
Yeah, for stuff like that, you're relying on float's ability to collapse against content around it. If you changed your markup a bit, it wouldn't be an issue. Also, you could (depending on browser support you need) use grid layout.

**Comment by danijelGombac** [comment]
@mdo 

I tried different markup, but without a good result. On mobile i need the sequence of card 1,2,3. For now i leave floats, I don't want to use a grid layout (browser support), thanks.

**Pull request closed without merging**
