### PR TITLE
Fix `modal.js`, issue #34755

### LINKED ISSUE #34755: Toggling between Modals does not work correctly.
Apparently this is a problem that arose as of version 5.1.0

### Steps to reproduce the problem

1. Open [https://getbootstrap.com/docs/5.1/components/modal/](https://getbootstrap.com/docs/5.1/components/modal/#toggle-between-modals).
2. Go to section [Toggle between modals](https://getbootstrap.com/docs/5.1/components/modal/#toggle-between-modals).
3. Click the button `Open first modal`.
4. In modal 1, click on the button `Open second modal`.
5. In modal 2, click on the button `Back to first`.
6. **The problem occurs.** Modal 2 does not close and modal one is not seen.

### Conditions in which it occurs

**Browser:** Chrome.
**OS:** Android and Windows.
**Bootstrap version:** 5.1.0

### PR DESCRIPTION
**Pull request by WinterSilence**
fix #34755
- `.modal.show` is not documented selector and changed to `.show[aria-modal]` 
- close opened modal only on `show`

### CODE REVIEW

**Comment by XhmikosR** [comment]
We need a test case please, otherwise this can happen again without anyone noticing.

**Comment by WinterSilence** [comment]
@XhmikosR sorry, I'm never wrote js tests before - can't help. Important moment - check opened dialog on showing modals.
It's worked fine without any additional code before #34701. I'm think `data-bs-dismiss="modal"` must be returned to example.

**Comment by GeoSot** [comment]
Hey @WinterSilence . Thank you for your effort 😃 
Can you explain what are you trying to achieve by this MR? 

We may need to notice down that #34755 is solved by #34701 (the issue is happening in 5.1.0)

**Comment by WinterSilence** [comment]
@GeoSot nope, #34701 report about problem created by your #34755 , I'm fix your "fix"

**Comment by GeoSot** [comment]
> @GeoSot nope, #34701 reported about problem created by your #34755 , I'm fix your "fix"

As I see #34755 is fixed (check the comments). And please try to be more talkative in order to help me understand what to do with this MR

**Comment by WinterSilence** [comment]
@GeoSot nope, you display version before your PR. yes, in my version all work fine))

**Comment by XhmikosR** [comment]
I don't get what this PR is supposed to fix. #34701 is fixed already in main. Also, unless there's a clear test case added we can't just merge this.

**Comment by WinterSilence** [comment]
@XhmikosR
> nope, #34701 reported about problem created by your #34755 , I'm fix your "fix"

you understand this?

**Comment by XhmikosR** [comment]
Sorry, I don't.

**Comment by WinterSilence** [comment]
@GeoSot merge it please, you fix not correct

**Comment by GeoSot** [comment]
Guys as you can see on #34755, the fix has been merged, and will be released in v5.1.1e

**Comment by Iftimasum1** [comment]
Yes

**Comment by Iftimasum1** [comment]
Yes

**Comment by WinterSilence** [comment]
@GeoSot don't see v5.1.1

**Comment by Sun3** [comment]
@GeoSot Looking forward to v5.1.1 being released.

**Pull request closed without merging**
