### PR TITLE
Update Holder.js to v2.8.2.

### LINKED ISSUE #17354: Update Holder.js
Notes:
1) Make sure the images show up when we use a percentage
~~2) See why there's a difference in the images' background-color (happens with current version too compared to v4-dev)~~

### PR DESCRIPTION
**Pull request by XhmikosR**
Only issue I see is that for example for some images I see the Alt text instead of the dimensions. I'll need to look more into it, we might need to pass the `literal` option.

Fixes #17354.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Scratch that: it seems the new version correctly uses the `text` value we specify while the old one didn't. So this is in fact the intended behavior.

Regardless, please review.

/CC @cvrebert

**Comment by cvrebert** [comment]
Perhaps we might consider dropping Holder in favor of using SVG to simplify things, since we've dropped IE8?

**Comment by XhmikosR** [comment]
It might be a good idea using SVGs but at this point this is just easier :P

**Comment by cvrebert** [comment]
Well, it would also solve #17217.

@mdo Any thoughts here?

**Comment by XhmikosR** [comment]
That is another issue that I personally don't consider it relevant so much.

But feel free to make that change if you think it's worth doing it now.

**Comment by mdo** [comment]
I had been using base64-ed spacer GIFs basically awhile back and found them to be quite helpful for limiting external dependencies in our examples and code snippets. Down the line I'd be open to it, though until then it'd be nice to keep Holder up to date.

**Comment by cvrebert** [comment]
Okay, filed #17478 to track ditching Holder in the future.
As for this PR: @XhmikosR :shipit:

**Pull request merged**
