### PR TITLE
Add SRI hashes for jQuery and Tether in docs

### LINKED ISSUE #18665: Use SRI for jQuery and Tether

### PR DESCRIPTION
**Pull request by cvrebert**
Fixes #18665.

### CODE REVIEW

**Comment by cvrebert** [comment]
Currently blocked on https://github.com/validator/validator/issues/151

**Comment by cvrebert** [comment]
Now blocked on https://github.com/jzaefferer/grunt-html/issues/86 instead.

**Comment by XhmikosR** [comment]
@cvrebert: maybe just ignore the warning and remove it with the next grunt-html update.

**Comment by cvrebert** [comment]
@XhmikosR Yeah, good idea.

**Pull request merged**
