### PR TITLE
Change file permissions to 644

### PR DESCRIPTION
**Pull request by XhmikosR**
I wonder if I should do the same for remaining 2 files:

* build/change-version.js
* build/ship.sh

For ship.sh it might be an issue, but I don't use the script myself.

### CODE REVIEW

**Comment by XhmikosR** [comment]
I wonder if I should do the same for remaining 2 files:

* build/change-version.js
* build/ship.sh

For ship.sh it might be an issue, but I don't use the script myself.

**Review by MartijnCuppens — APPROVED** [review]

**Comment by XhmikosR** [comment]
How about the other 2 files that have 0755?

**Comment by MartijnCuppens** [comment]
The two files are still executable if permissions are switched to `664`.

**Comment by XhmikosR** [comment]
Alright, I'll change the other two files tomorrow too, assuming you tried them yourself.

**Comment by MartijnCuppens** [comment]
> Alright, I'll change the other two files tomorrow too, assuming you tried them yourself.

Yup, I did

**Pull request merged**
