### PR TITLE
tip method in popover.js can be removed

### PR DESCRIPTION
**Pull request by huang-x-h**
Popover is extend Tooltip, the tip function can use tootltip's tip, so we can remove the tip function definition in popover to reduce the js filesize

tip function definition in tooltip.js https://github.com/twbs/bootstrap/blob/master/js/tooltip.js#L405-L407

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 91b384399c3c7c299466c595235640f336b3fc15
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/48714495

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
LGTY, @XhmikosR @hnrch02 ?

**Comment by hnrch02** [comment]
:shipit:

**Comment by XhmikosR** [comment]
:+1:

**Pull request merged**
