### PR TITLE
Expands 'rounded' classes

### PR DESCRIPTION
**Pull request by Parth-Gupta10**
This PR adds first 2 features proposed in issue #31784 .

The following changes were made in scss/_utilities.scss -

1. Classes` rounded-top-left`, `rounded-top-right`, `rounded-bottom-left`, `rounded-bottom-right` were added to implement rounding of 1 corner only.
2. `$spacers` was added in `values` of `rounded` class to implement size increments for rounding more akin to the margin/padding sizes (0-5).

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
> Classes rounded-top-left, rounded-top-right, rounded-bottom-left, rounded-bottom-right were added to implement rounding of 1 corner only.

Not sure if this is a common use case. Ping @twbs/css-review 

> $spacers was added in values of rounded class to implement size increments for rounding more akin to the margin/padding sizes (0-5).

I wouldn't expect more border radii utilities are generated when I change the `$spacers` variable tbh.

**Comment by Parth-Gupta10** [comment]
@MartijnCuppens Ok, so should I close this PR or you will still look into it as a possible feature ? I worked on it only after seeing issue #31784

**Comment by Parth-Gupta10** [comment]
@twbs/css-review @MartijnCuppens  Please reply

**Comment by MartijnCuppens** [comment]
Gonna close this for the reasons mentioned above.

**Pull request closed without merging**
