### PR TITLE
Dropdown key events handling fix - v5

### LINKED ISSUE #30510: Dropdowns: key events are not propagated from inactive and disabled dropdowns
Hi,

key events are not propagated from dropdown when it is inactive or disabled.

Reduced test case on JS Bin: https://jsbin.com/hoharusisa there is ESC key handler attached to the document element.

1. Click on ESC - nothing happens.
2. Click on ESC - handler is invoked.

Event propagation is disabled in the https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js#L455 just after initial checks which are finishing the event handling, but in following lines there are further check which potentially could finish the handling. Propagation should be stopped after those checks.

Similar finding was created for v3: #15065 It was found as valid issue: https://github.com/twbs/bootstrap/issues/15065#issuecomment-77530943 however it was never fixed.

Thanks ans Regards,
Łukasz

### PR DESCRIPTION
**Pull request by luktom**
Please see #30510 for details. Two new unit tests added. "npm run test" was finished without errors.

It was needed to add following fix from v4: #28912. After this cyclomatic complexity of `dataApiKeydownHandler` was higher than allowed in your ESLint configuration, so I extracted `_isDropDownCommand` method.

Additionally I fix some by catch error of variables assignment in "should ignore keyboard events for <input>s and <textarea>s within dropdown-menu, except for escape key" test.

Fixes #30510

### CODE REVIEW

**Comment by XhmikosR** [comment]
Thanks for the PR.

That being said, the ESLint issue is just a warning that could be tackled in a separate commit or PR.

**Comment by XhmikosR** [comment]
@luktom can you fetch upstream and rebase please?

**Comment by luktom** [comment]
@XhmikosR conflicts with master resolved.

**Comment by XhmikosR** [comment]
@luktom can you try a proper rebase + squash and not a merge commit?

**Comment by XhmikosR** [comment]
Closing due to lack of response. If you can, please make a new clean PR later.

**Pull request closed without merging**
