### PR TITLE
Fix tab.js Problem

### PR DESCRIPTION
**Pull request by dercodercom**
I'm using Tab.js with remove function and get an error "TypeError: container is undefined [more info]", with this check the error is fixed.

Fixes: #27522

### CODE REVIEW

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
@dercodercom: can you share a codepen demonstrating this issue? The fix does make sense in general, but we need to see when it actually fails.

**Comment by Johann-S** [comment]
agree with @XhmikosR

**Comment by dercodercom** [comment]
@XhmikosR the test link: https://codepen.io/anon/pen/mpYPaQ if you close a non-selected tab, the error comes.

**Comment by Johann-S** [comment]
weird use case 🤔 

Anyway, we need a unit test

**Comment by XhmikosR** [comment]
@dercodercom: can you add a unit test as per @Johann-S's comment above?

**Comment by twbs-closer** [comment]
Hey there!

We're automatically closing this issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own. Closed issues that remain inactive for a long period may get automatically locked.

Don't worry though; if this is in error, let us know with a comment and we'll be happy to reopen the issue.

Thanks!

(*Please note that this is an [automated](https://github.com/twbs/no-carrier) comment.*)

**Comment by XhmikosR** [comment]
@Johann-S: maybe we should reconsider for this?

**Comment by Johann-S** [comment]
ping @dercodercom

**Comment by twbs-closer** [comment]
Hey there!

We're automatically closing this issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own. Closed issues that remain inactive for a long period may get automatically locked.

Don't worry though; if this is in error, let us know with a comment and we'll be happy to reopen the issue.

Thanks!

(*Please note that this is an [automated](https://github.com/twbs/no-carrier) comment.*)

**Comment by Johann-S** [comment]
Yep we should add a unit test here, if @dercodercom cannot I'll try to do that

**Comment by XhmikosR** [comment]
He hasn't responded for a long time so if you could tackle this that'd be awesome :)

**Comment by Johann-S** [comment]
@XhmikosR the job is done here, if you want to take a look 😉

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
