### PR TITLE
Update _form-range.scss

### PR DESCRIPTION
**Pull request by WinterSilence**
Fix `appearance` attribute for `.form-range`

### CODE REVIEW

**Comment by mdo** [comment]
Why is this needed?

**Comment by WinterSilence** [comment]
@mdo 
> The `-moz-appearance` and `-webkit-appearance` properties are non-standard versions of this property, used (respectively) by Gecko (Firefox) and by WebKit-based (e.g., Safari) and Blink-based (e.g., Chrome, Opera) browsers to achieve the same thing. Note that Firefox and Edge also support `-webkit-appearance`, for compatibility reasons.

https://developer.mozilla.org/en-US/docs/Web/CSS/appearance

**Comment by XhmikosR** [comment]
This is not needed. We use autoprefixer which handles the prefixes for our supported browsers.

**Comment by WinterSilence** [comment]
@XhmikosR it's doesn't work with pseudo-elements like as `-webkit-slider-runnable-track` and etc.

**Comment by XhmikosR** [comment]
Sorry, doesn't work don't really help me understand why we need to manually add a prefix. This should not be needed and if it's needed you should report it to autoprefixer.

**Comment by WinterSilence** [comment]
@XhmikosR my mistake, forgot that I was using the changed settings

**Pull request closed without merging**
