### PR TITLE
Add search to the documentation

### PR DESCRIPTION
**Pull request by pixelastic**
Hello Bootstrap team,

I've always wanted to be able to easily search inside the Bootstrap documentation, so I've added the feature.

Desktop search screencast

You can see it live and test it here: [https://bootstrap.algolia.com/](https://bootstrap.algolia.com/) (it of course includes smaller [screen](https://raw.githubusercontent.com/pixelastic/sov/master/pull_requests/bootstrap/phone.gif) [versions](https://raw.githubusercontent.com/pixelastic/sov/master/pull_requests/bootstrap/tablet.gif) as well).

This pull request uses [Algolia](https://www.algolia.com/) API to index and search the documentation. It includes both the indexing code (using our Jekyll plugin) as well as the front-end code to display the results.
## Benefits for the end user
- Search in the whole documentation (CSS, JavaScript, Components), with typo-tolerance
- Fast results (your search index is replicated in 13 regions worldwide, it is fast no matter where the user is)
- Instant access to the documentation at the first keystroke, in a few milliseconds
- Directly scroll to the relevant part of the page
- Responsive integration, available on all viewports
## How it works

We've created a free account for you that hosts the documentation. When a user does a search, it uses the Algolia API to retrieve the most relevant results from the documentation and display them in a dropdown.

This uses [Typeahead](https://github.com/twitter/typeahead.js/tree/v0.10.5)  v0.10.15 for the dropdown, [Hogan](https://github.com/twitter/hogan.js) v3.0.2 for the templates and the [Algolia Client](https://github.com/algolia/algoliasearch-client-js) v3.7.5 for the calls to the API. The indexing is done using the [Algolia Jekyll plugin](https://github.com/algolia/algoliasearch-jekyll) v0.4 (more on this later).
## Testing the pull request locally

If you want to test the PR locally, you can do the following:

``` sh
$ git clone -b feature/algolia-search git@github.com:algolia/bootstrap.git
$ cd ./bootstrap
$ bundle install
$ npm install
$ grunt docs
$ jekyll serve
```

Note that we've added a `Gemfile` to avoid any dependency version issue.
## Updating the index

The Jekyll plugins adds a new command to jekyll: `jekyll algolia push`. This will read the generated HTML files from a `jekyll build`, extract each `<p>` paragraph and `<h1> - <h6>` header and index them in Algolia. You'll basically have to re-run this command everytime you push a new version to `gh-pages`.

This will need your admin API key as the `ALGOLIA_API_KEY` environment variable. I'll give you full and unlimited access to your dashboard so you can find it there.

``` sh
ALGOLIA_API_KEY=[YOUR_ALGOLIA_ADMIN_KEY] jekyll algolia push
```
## Tweaking

The Jekyll plugin default settings are configured for indexing a blog. We had to tweak it a bit for the Bootstrap documentation. The `algolia.settings` key in `_config.yml` are the Algolia settings we think provides the most relevant results. What every option does is explained in [our documentation](https://www.algolia.com/doc#Settings) but I'm also available to give more context if any of them is not clear enough.
## Records

Here is an example of what a record looks like:

``` json
{
  "objectID": "components_145",
  "type": "page",
  "url": "/components/#navbar-forms",
  "title": "Components",
  "slug": "components",
  "h2": "Forms",
  "h1": "Navbar",
  "tag_name": "p",
  "raw_html": "<p>As a heads up, <code>.navbar-form</code> shares much of its code with <code>.form-inline</code> via mixin. <strong class=\"text-danger\">Some form controls, like input groups, may require fixed widths to be show up properly within a navbar.</strong></p>",
  "text": "As a heads up, <code>.navbar-form</code> shares much of its code with <code>.form-inline</code> via mixin. Some form controls, like input groups, may require fixed widths to be show up properly within a navbar.",
  "unique_hierarchy": "Components > Navbar > Forms",
  "css_selector": "div:nth-of-type(7) > p:nth-of-type(5)",
  "css_selector_parent": "#navbar-forms",
  "weight": {
    "page": 2,
    "tag_name": 0,
    "number_of_words": 1
  },
  "codes": [
    "navbar-form",
    "form-inline"
  ]  
}
```

Most of the keys are self-explanatory. Some of them are used to calculate the relevance of a record, others are used for the display in the dropdown templates.

Each record contains its `raw_html` version as well as a sanitized `text` version. As we are indexing both `<p>` and `<h1-6>`, the `tag_name` key tells us what kind of node each record is. The `h1`, `h2`, ..., `h6` keys are the parent headings of the records. The `unique_hierarchy` field is a concatenation of those fields, symbolising where the record is in the TOC.

`css_selector` and `css_selector_parent` are two unique CSS selector that target respectively the record itself, and its closest parent heading. We actually do not use `css_selector` in this PR, because the generated doc adds `<div>` markup (for copy-pasting snippets) that breaks them. Instead, we use the `css_selector_parent` to scroll the page to the closest parent heading.

`weight` and `codes` are custom attributes that are not part of the plugin, but that we could add using the `custom_hook_each` hook for this specific implementation. `weight` is an attribute used in our custom ranking to break ties between several records. `codes` contains all the class and method found in `<code>` examples of the records, giving us better results when searching for `navbar btn`, for example.
## About Algolia

At Algolia we provide a hosted search API and support community websites like [Hackernews search](https://hn.algolia.com/), [CDNJS](https://cdnjs.com/), [GrowthHackers](https://growthhackers.com/), [Product Hunt](http://www.producthunt.com/) or the [Laravel documentation](http://laravel.com/docs/5.1) with free plans. We only ask for a "powered by Algolia". This pull request adds it to the search results.

If you want to move forward with this implementation, I'll send you the free and unlimited credentials to your Algolia dashboard as mentionned above.

I'm available for any questions you may have or any more information you would need.

### CODE REVIEW

**Comment by Shipow** [comment]
:+1:  I'm already using it everyday! :)

**Comment by jmeiss** [comment]
:+1: Wow nice! Would love to use it! Thanks for the PR

**Comment by Johann-S** [comment]
nice PR and job ;)

**Comment by karliky** [comment]
:+1: Really impressive!

**Comment by tzi** [comment]
:+1: Awesome!

**Comment by pixelastic** [comment]
Seems like the `validate-html` Travis test is failing with error `>> Error: Command failed: /bin/sh -c jekyll -v` and I'm not sure how to make `jekyll` available. I thought it would be picked from the `Gemfile`.

**Comment by cvrebert** [comment]
@pixelastic Instead of adding a Gemfile, please add the dependency to https://github.com/twbs/bootstrap/blob/master/test-infra/S3Cachefile.json#L10 and https://github.com/twbs/bootstrap/blob/master/.travis.yml#L25

**Comment by pixelastic** [comment]
@cvrebert Done. I've amended the commit and forced push. Travis seems to be ok now.

**Comment by pixelastic** [comment]
Just realized the forced push was not intercepted by Travis. Sorry about that, I'll simply add new commit if this need more tweaks.

**Comment by jdmagic21** [comment]
Thank you for this! I was looking and I couldn't not find something like this. They should have added this from the beginning or organized their documentation better.

**Comment by mdo** [comment]
On the surface this seems rad—I'd love to have some kind of search—but am I right in seeing that this adds three additional JS files, adding an additional 88kb to every one of our docs pages? That sounds rather outrageous for one feature.

**Comment by sbouaked** [comment]
really cool :+1:

**Comment by pixelastic** [comment]
Thanks @mdo for taking the time to review it.

I've made a few changes to limit the filesize:

- All three dependencies (Typeahead, Hogan and Algolia client) are loaded as one request from the CDN instead of three.
- The Hogan templates are included in the js file instead of the HTML, so they can be cached, and not re-downloaded on every page.

So we end up with only two js files, with a total size of 34kb (we're talking gzipped size here), which does not seem that big an overhead for the feature it's adding.

[According to webpagetest](http://www.webpagetest.org/video/compare.php?tests=150730_CK_P6Y%2C150730_KG_P6Z&thumbSize=200&ival=500&end=visual) this has no impact on the time to render, the search input is only displayed at the end.

WPT comparison

**Comment by epantera** [comment]
:+1: Great ! Thanks for the feature

**Comment by mdo** [comment]
34kb still sounds like a lot of JS for one feature, particularly when all of Bootstrap's plugins come in at about the same size (and are not gzipped, I believe). How will folks in China, who already struggle to load jQuery even from a CDN—see #16886—handle this?

**Comment by StevenBlack** [comment]
@mdo the `Built with Bootstrap` section on the home page is 800k+ worth of thumbs alone (currently Vogue, Lyft, Newsweek, and Riot). 

The `Getting Started` page currently weighs 1.1 MB of which 100k+ is Javascript.

Point being, we could have a long conversation about a the relative merits of 34k in so many other areas.

**Comment by adammacias** [comment]
I liked idea! But maybe more interesting to use some as [Simple-Jekyll-Search](https://github.com/christian-fei/Simple-Jekyll-Search). It works with less `JS` and one file `.json` and is more fast for Bootstrap! Look this [demo](http://christian.fei.ninja/Simple-Jekyll-Search/)

**Comment by pixelastic** [comment]
Regarding your concern with the CDN in China, JSdelivr is actually accessible from China.

To be able to better understand and compare numbers, I've done this table of the main JS assets:

| file                     | size (minify + gzip) | 
| ----                     | ----- | 
| widgets.js               | 35kb  | 
| jquery.min.js            | 33kb  | 
| __search dependencies__  | 27kb  | 
| docs.min.js        | 16kb  | 
| __docs.min.js + search code__ | 17kb  | 
| bootstrap.min.js         | 9.6kb | 

The total file size increase is only 28kb.

@mdo: What would be an acceptable filesize for you? Just need to know what I'm aiming for.

**Comment by jbpionnier** [comment]
:+1: very nice !

**Comment by mdo** [comment]
> @mdo the Built with Bootstrap section on the home page is 800k+ worth of thumbs alone (currently Vogue, Lyft, Newsweek, and Riot).
> 
> The Getting Started page currently weighs 1.1 MB of which 100k+ is Javascript.
> 
> Point being, we could have a long conversation about a the relative merits of 34k in so many other areas.

Yeah, I've been looking at all this as part of v4 and a lot will change there, especially the breakdown of content across more pages. I've just pushed some of the changes from there to v3's docs to:

- Use smaller, local screenshots for the Expo on the homepage. See #16922.
- Remove the Twitter `widgets.js` entirely. It was only used for Tweet/Follow buttons, but 100kb for two buttons is fucking ridiculous. See #16921.
- Redesigned the site footer as a small bonus to justify removing all that crap :D.

We've got a lot of work to do, but the first step there is acknowledging we can do better. Adding another 30-40kb of JS *on top* of all that simply because there's already a ton there isn't a reason to ship something.

@pixelastic Honestly, none at all, but that sounds like a pipe dream. As @adammacias mentions, the Jekyll simple search plugin is likely the best foot forward—and I've already implemented that in v4's docs. Adding it to v3's wouldn't be too bad if memory serves.

**Comment by pixelastic** [comment]
Do you have a url where I can have a look at the v4 docs? I'm curious as how the search is working. From what I saw from the readme, it only searches inside the page titles (and not the content).

**Comment by kkirsche** [comment]
@pixelastic v4 is still Private at the moment. It should release as a public beta sometime in August.

**Comment by mdo** [comment]
Yeah, that search plugin seems much more limited than this, but it saves on the dependency and page load side of things.

**Comment by jimaek** [comment]
@mdo Regarding loading the files from China we have a related page on our new website (under construction) http://lb.jimaek.svc.tutum.io/features/cdn-in-asia-and-china
http://lb.jimaek.svc.tutum.io/features/network-map
So there will be no problems.

**Comment by kayyyy** [comment]
+1 I missed this search :)

**Comment by jumichot** [comment]
+1 would love to see it live :)

**Comment by maximeprades** [comment]
very cool :+1: cc @pelletier

**Comment by GiantCowFilms** [comment]
**+1** Nice addition

**Comment by sleicester** [comment]
Nice addition, I can see this saving a ton of time when referencing the doc site!

**Comment by redox** [comment]
:+1:

**Comment by mrblackus** [comment]
:+1:

**Comment by theofidry** [comment]
:+1:

**Comment by ZeBigDuck** [comment]
:+1:

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Pull request closed without merging**
