### PR TITLE
Use popper to align dropdown menu instead of using css with important

### PR DESCRIPTION
**Pull request by Johann-S**
Remove the use of `important` in css because it's a bad practice and now we have Popper 🎆 
@FezVrasta any feedbacks on this PR ? And thank you for your help 👍

### CODE REVIEW

**Comment by Johann-S** [comment]
@FezVrasta any feedbacks on this PR ? And thank you for your help 👍

**Comment by FezVrasta** [comment]
Umh, does it actually work? I thought Popper.js would freak out if you change the `right: 0` property to  `auto`

**Comment by Johann-S** [comment]
Yes it works very well

**Comment by FezVrasta** [comment]
Umh, I'm not so confident, but if you tested it, great.

**Comment by Johann-S** [comment]
As you can see : https://codepen.io/Johann-S/pen/mmGrJe

**Comment by FezVrasta** [comment]
👍

**Pull request merged**
