### PR TITLE
Reverse spinners modifier class

### LINKED ISSUE #38053: A modifier class to inverse the behaviour of any spinner
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I suggest having a modifier class that whenever added to any spinner reverses its behavior, whether it is a small spinner, growing spinner, or border spinner. Adding this class to a spinner-border makes it rotate in the other direction, while adding it to a spinner-grow makes it shrink instead of growing.

### Motivation and context

The issue https://github.com/twbs/bootstrap/issues/37989 was opened for a very similar feature request. Yet, it was closed as it only suggests one new base class, and just for the spinner-border. A discussion about it was in the related pull request https://github.com/twbs/bootstrap/pull/37990 where a modifier class for all spinners was suggested.

### PR DESCRIPTION
**Pull request by ChellyAhmed**
### Description

modifier class to reverse the behaviour of all spinners

### Motivation & Context

This pull request responds to the issue https://github.com/twbs/bootstrap/issues/38053 introducing a modifier class "reverse" that reverses the behavior of the spinner (regardless of its color or size).
With the introduction of this class, the spinner-border will simply rotate in the opposite direction, while the spinner-grow will shrink instead of grow.

### Type of changes
A new feature, along with an update for the documentation.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [X] My code follows the code style of the project _(using `npm run lint`)_
- [X] My change introduces changes to the documentation
- [X] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

#### Live previews

You can check an example in the updated section of the documentation in the live preview:
- <https://deploy-preview-38054--twbs-bootstrap.netlify.app/docs/5.3/components/spinners/#reverse-modifier-class/>

### Related issues

Closes https://github.com/twbs/bootstrap/issues/38053
The related issue also refers to another closed issue: https://github.com/twbs/bootstrap/issues/37989 with a referring closed pull request: https://github.com/twbs/bootstrap/pull/37990

### CODE REVIEW

**Comment by julien-deramond** [comment]
TBH I'm not really convinced for now by the need to have a counterclockwise direction animation for the spinner.

**Comment by KouthairKebaili** [comment]
That's understandable, and there may be cases where a counterclockwise direction animation for a spinner is not necessary or appropriate. Ultimately, the design of the spinner should be driven by the specific needs of the website or application where it will be used.

However, there may be some cases where a counterclockwise direction animation could be beneficial. For example, if the spinner is being used to indicate a process that is running backwards or to undo an action, a counterclockwise direction could be more intuitive for users. Additionally, for accessibility purposes, counterclockwise motion is often more comfortable and natural for left-handed users.

Ultimately, the decision to use a counterclockwise direction animation for a spinner should be based on the needs of the specific use case and the preferences of the designer or developer. If the designer or developer feels that a counterclockwise animation could be beneficial or add value to the design, it may be worth considering.

**Comment by ChellyAhmed** [comment]
Thank you @KouthairKebaili and @julien-deramond for responding.
I also tend to believe that it is always a good idea to offer users the possibility to choose the behavior of any spinner they use.
I also wanted to highlight the fact that I had accidentally included a commit that unnecessarily changes a file. Hence, I added a new commit to revert these unwanted changes.

**Comment by julien-deramond** [comment]
Thanks for this PR @ChellyAhmed but rather than treating only the reverse spinners case specifically, we're going to provide animation helpers/utilities (more info https://github.com/twbs/bootstrap/issues/38150). So I'm closing this PR.

**Comment by ChellyAhmed** [comment]
Thank you @julien-deramond for your responsiveness. I will try to work on it relating to the issue https://github.com/twbs/bootstrap/issues/38150 to get the best possible outcome.

**Pull request closed without merging**
