### PR TITLE
Make translation of custom file input text easier

### PR DESCRIPTION
**Pull request by cvrebert**
Implements #18922.
@mdo LGTY?

### CODE REVIEW

**Comment by mdo** [comment]
Looks good, but we should also document it a bit.

**Comment by cvrebert** [comment]
@mdo Added docs. Any further feedback?

**Comment by cvrebert** [comment]
@mdo Good to ship?

**Comment by mdo** [comment]
:shipit: Don't forget to add it to the ship list too pls :D.

**Pull request merged**
