### PR TITLE
Tell clean-css to inline source files into sourcemap

### PR DESCRIPTION
**Pull request by cvrebert**
Bootstrap v3 fix for #19063.
@jmervine @jdorfman Please test this. If you can confirm the fix, then I'll try to get 3.3.7 shipped ASAP.

### CODE REVIEW

**Comment by jdorfman** [comment]
@cvrebert checking

**Comment by jdorfman** [comment]
@cvrebert ran `grunt dist` and uploaded them: https://maxcdn.bootstrapcdn.com/debug/fix-19063-v3/css/bootstrap.min.css

I am going to post it to [bootstrapcdn#629](https://github.com/MaxCDN/bootstrap-cdn/issues/629) and see what they say since I don't have Windows 10.

**Comment by jmervine** [comment]
@jdorfman I have a windows 10 vm if you need me to test something. I'm gonna be traveling through Monday though, so it might have to be early next week.

**Comment by jdorfman** [comment]
@jmervine cool. I am downloading/installing Windows 10 from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by XhmikosR** [comment]
@cvrebert: while at it how about we take care of that comment too?

```js
// TODO: disable `zeroUnits` optimization once clean-css 3.2 is released
//    and then simplify the fix for https://github.com/twbs/bootstrap/issues/14837 accordingly
```

**Comment by jdorfman** [comment]
@XhmikosR are you able to test this:  https://maxcdn.bootstrapcdn.com/debug/fix-19063-v3/css/bootstrap.min.css

I am think it fixes the issue people are reporting but I want to make sure.

**Comment by XhmikosR** [comment]
Yeah, confirmed it works for me on Windows 10 64-bit with Firefox 48.0b6 64-bit.

**Comment by jdorfman** [comment]
@XhmikosR hop on slack, want to triple check before @cvrebert merges this for bootstrapcdn#629

**Comment by XhmikosR** [comment]
I'm gonna rebase and merge this when I'm back at home later if no one beats me to it.

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 079b48b89116a2e86a498bf5da7b0cd337cde96c
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/144037808
Docs preview: http://preview.twbsapps.com/c/${commitSha.sha}

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Pull request merged**
