### PR TITLE
Updated jQuery to v2.2.1

### PR DESCRIPTION
**Pull request by ameya-pandilwar**
Fix for #19296

### CODE REVIEW

**Comment by cvrebert** [comment]
You will also need to update the jQuery URLs in the `/docs/examples` HTML files.

**Comment by cvrebert** [comment]
And also update the `/js/tests/vendor/jquery.min.js` file.

**Comment by ameya-pandilwar** [comment]
Updated the remaining references and the `jquery-min.js` in `/js/tests/vendor/` directory

**Comment by XhmikosR** [comment]
@ameya-pandilwar: please fetch v4-dev, rebase and squash.

**Comment by ameya-pandilwar** [comment]
@XhmikosR could you tell me the exact commands to do so?
I tried rebasing my feature branch on top of the latest v4-dev but I'm unable to make it work. Thanks!

**Comment by XhmikosR** [comment]
https://help.github.com/articles/syncing-a-fork/

**Comment by XhmikosR** [comment]
Closing in favor of https://github.com/twbs/bootstrap/pull/19407.

**Pull request closed without merging**
