### PR TITLE
Refs #17201: Use Tether as a non-window global variable

### PR DESCRIPTION
**Pull request by karolyi**

### CODE REVIEW

**Comment by cvrebert** [comment]
Unless I'm mistaken, this won't work. The browser will throw `ReferenceError: Tether is not defined`.

**Comment by karolyi** [comment]
See https://github.com/twbs/bootstrap/issues/18647#issuecomment-247882258

**Comment by karolyi** [comment]
or to be on the actually creative side, I can update the pull request with tooltip being invoked with `jQuery` and `Tether`, and then do an `if (Tether === undefined || window.Tether === undedined)` ...

**Comment by cvrebert** [comment]
`Tether === undefined` will throw a `ReferenceError` exception in the non-webpack case if Tether is unavailable.

**Comment by cvrebert** [comment]
Properly fixing this for all the dependencies (i.e. #17201) seems like a better use of our time.
Thanks though.

**Comment by karolyi** [comment]
@cvrebert see my last commit, that is a temporary fix, until you get the es6 imports right.

**Pull request closed without merging**
