### PR TITLE
Update _sizing.scss

### PR DESCRIPTION
**Pull request by dospuntocero**
breakpoints added for responsive width and heights

### CODE REVIEW

**Comment by mdo** [comment]
Thanks, but I don't see us needing this right now.

**Comment by RomainLanz** [comment]
May you reconsider this?

**Comment by daviian** [comment]
Spacers include breakpoints as well, so IMHO width and height should also include that capability.

**Comment by oliverdorn** [comment]
I would also appreciate this!

**Comment by sebastianbrosch** [comment]
Would be very useful!

**Comment by Sorgrum** [comment]
Would love this as well.

**Comment by hypnocyst** [comment]
I'm surprised this isn't a feature. It should be.

**Comment by bluecaret** [comment]
@mdo Why not? Why is this not needed? If your going to outright ignore something at least give a reason. These are useless without this. There are a lot of times I want column like sizing but just for a single element where the padding and margins on columns are inappropriate.

**Comment by mauril26** [comment]
Did I miss something.? (No comments since 2017)
How are you doing to "solve" this situations.?

**Comment by blackmonkey** [comment]
I just realized that we can use the col-* classes to fix this issue, e.g.

- w-lg-25 (width: 25% only on large+ devices): col-lg-3
- w-md-50 (width: 50% only on large+ devices): col-md-6
- w-sm-75 (...): col-sm-9
- w-100 (would be like w-xs-100): col-12
- width 25% except on large+ devices, and 16% on large+ devices: col-3 col-lg-2

**Pull request closed without merging**
