### PR TITLE
Add grunt-contrib-htmlmin.

### PR DESCRIPTION
**Pull request by XhmikosR**
Only used for the GitHub docs.

```
Running "htmlmin:dist" (htmlmin) task
Minified _gh_pages/about/index.html 18.37 kB → 15.38 kB
Minified _gh_pages/browser-bugs/index.html 17.47 kB → 14.48 kB
Minified _gh_pages/components/index.html 298.71 kB → 258.74 kB
Minified _gh_pages/css/index.html 305.7 kB → 277.57 kB
Minified _gh_pages/customize/index.html 142.77 kB → 125.54 kB
Minified _gh_pages/getting-started/index.html 67.7 kB → 62.09 kB
Minified _gh_pages/index.html 11.84 kB → 9.97 kB
Minified _gh_pages/javascript/index.html 199.8 kB → 179.11 kB
Minified _gh_pages/migration/index.html 25.08 kB → 19.61 kB
```

I skipped the examples on purpose since many people seem to copy paste those. Let me know your thoughts.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@mdo @cvrebert: apparently, those validation errors we got in this branch [were correct](https://github.com/twbs/bootstrap/commit/9f2589501562b86ddb6c58a1beb3193acca2f4e3). I don't get how the validator didn't catch them in master...

So, I think this branch is completely safe. I removed the task from the validation target.

**Comment by mdo** [comment]
What's the deal on white-space sensitive components then? How does `inline-block` react with this kind of stuff?

**Comment by hnrch02** [comment]
@mdo https://github.com/twbs/bootstrap/pull/15294#issuecomment-65710152. `conservativeCollapse ` always collapses whitespace to 1 space (and never removes it entirely). See https://github.com/kangax/html-minifier#options-quick-reference

**Comment by XhmikosR** [comment]
Yeah, it keeps the whitespace so it's pretty much safe.

**Comment by kkirsche** [comment]
@cvrebert you are correct about paragraphs. W3C Validator returns:

__No p element in scope but a p end tag seen.__

for 

```html
<p> <div class=highlight>(...stuff...)</div> <h3 id=js-noconflict>No conflict</h3> </p>
```

**Comment by mdo** [comment]
Sorry I missed that the white-space stuff was all settled. Is there another bug in this to address still?

**Comment by XhmikosR** [comment]
@mdo: it should be OK as far as I'm concerned.

**Comment by mdo** [comment]
Cool, I'm okay to see this ship then if the white-space problem has been completely addressed. <3

**Pull request merged**
