### PR TITLE
Remove `role="main"` from `main` element.

### PR DESCRIPTION
**Pull request by XhmikosR**
This was needed for Internet Explorer 11.

### CODE REVIEW

**Review by bardiharborow — DISMISSED** [review]
About time...

**Comment by XhmikosR** [comment]
Putting this on hold until we have a consensus about IE support.

**Review by patrickhlauke — COMMENTED** [review]
I'd say keep it, as it's a very small concession that can make a big difference for users that still have to use IE11 with AT. but not overly fussed tbh

**Comment by XhmikosR** [comment]
We need to come to a consensus about IE support. When this happens, we'll decide how we proceed.

**Comment by MartijnCuppens** [comment]
I agree with @XhmikosR, we must be strict which will make it way easier for us to make decisions about things.

**Comment by XhmikosR** [comment]
Closing since we are going to keep IE11 support in v5.

**Pull request closed without merging**
