### PR TITLE
Don't run Google Analytics locally.

### LINKED ISSUE #28351: Stop Allowing Google to use its "Backdoor" script loader
I use [Dan Pollock's hosts file](https://someonewhocares.org/hosts/) to block Google Analytics but they found a way around it. I've seen this on the Telegram website and now I'm seeing it on Bootstrap while helping with the Hugo dev:

https://www.reddit.com/r/privacy/comments/8clrzn/google_your_backdoor_to_the_internet/

The way this works is Google uses a backdoor script loader as explained above—it's base64 encoded—the specific script Bootstrap tried to load on my machine while working doing development was this one here: https://www.google.com/js/bg/4mrRnEPnWo81qWPG8_xcGP85HCscbg1O2YUrIewxQYY.js

This script loader relies on the fact many may have explicitly blocked google analytics and it uses the technique to get around the block in a most uncouth way. If you'd like a HAR file showing the requests I will reproduce this for you—if you can commit to an investigation and fix for this cross-domain JS script loader.

### PR DESCRIPTION
**Pull request by coliff**
This is for the Hugo docs.
Refs #28351

### CODE REVIEW

**Comment by XhmikosR** [comment]
@coliff : can you rebase against the upstream twbs:v4-dev-xmr-hugo-2 branch?

BTW does this fix #28351 completely?

**Comment by XhmikosR** [comment]
Nvm, I don't think it resolves #28351.

**Comment by XhmikosR** [comment]
Oh, and please remove the `resolve` from your commit message while at it.

**Comment by coliff** [comment]
hey @XhmikosR - sorry not got back to this yet. Do I need to do anything now?

**Comment by XhmikosR** [comment]
@coliff: yeah, all of the above :)

**Comment by XhmikosR** [comment]
Not sure how to proceed with this honestly. I personally have no issue with this, nor with the analytics running.

But I still need to above things fixed in order to merge it.

/CC @MartijnCuppens @Johann-S @mdo for thoughts.

**Comment by mdo** [comment]
Rebase here got messed up.

**Comment by XhmikosR** [comment]
Yeah but do you want this change? I will take care if it myself, I'm just
not sure 100% I want this. Both ways are Ok to me

**Comment by mdo** [comment]
> Yeah but do you want this change? I will take care if it myself, I'm just not sure 100% I want this. Both ways are Ok to me

I can't see what the diff is easily, but based on the title here, I'm good not running Google Analytics on localhost while doing development.

**Comment by XhmikosR** [comment]
The diff is just the last patch, the rest will go away with a proper rebase. @coliff I will make the changes, but it'd be nice if you could take care of the comments yourself.

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
