### PR TITLE
Autoprefixer callout in Build tools docs

### LINKED ISSUE #18238: Mention Autoprefixer in the "Build tools" docs

### PR DESCRIPTION
**Pull request by mdo**
Fixes #18238.

Just now saw this was assigned to @cvrebert, but this should suffice I think. Chris, feel free to suggest edits if this isn't what you had in mind.

### CODE REVIEW

**Comment by cvrebert** [comment]
We should also mention Autoprefixer in the descriptions in the "Using Grunt" section alongside the existing "Uses Sass" verbiage.

**Comment by mdo** [comment]
How's that looking @cvrebert?

**Comment by cvrebert** [comment]
I added one more. Looks good now.

**Comment by mdo** [comment]
<3

**Pull request merged**
