### PR TITLE
Collapse: Fix multiple `id`s calls

### LINKED ISSUE #38974: Collapse with multiple target stopped working in 5.3.0
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Until v5.2.3, the collapse plugin allowed a button to control several targets.
e.g. `data-bs-target="#hello,#world"`

Since v.5.3.0, it only appears to work with a single selector.  With multiple selectors, there are no errors, but no collapsing

I did read https://getbootstrap.com/docs/5.3/migration/ to see if this was an intentional change.

### Reduced test cases

5.2.3 - https://codepen.io/fisharebest/pen/dyQgwGr
5.3.0 - https://codepen.io/fisharebest/pen/GRwYPjR

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.3.0

### PR DESCRIPTION
**Pull request by louismaximepiton**
### Description

With `git bisect`, it seems the breaking change appeared from https://github.com/twbs/bootstrap/pull/37438.
The only change in here was that the `parseSelector` was applied in any case and not on some specific cases anymore. Reverting this change.

### Motivation & Context

Break some (wrong?) use cases.

### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

- <https://deploy-preview-38989--twbs-bootstrap.netlify.app/>

Tried it with the minimal code:
```html
<button data-bs-toggle="collapse" data-bs-target="#hello,#world">
  collapse
</button>

<div id="hello" class="collapse">HELLO</div>
<div id="world" class="collapse">WORLD</div>
```

### Related issues

Closes #38974.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Nice git bisecting!

Confirmed it fixes #38974. @GeoSot LGTY?

**Comment by XhmikosR** [comment]
As for the tests, yeah, ideally we should have one, because apparently it's not covered by the existent tests :)

**Review by Parasuramragu — COMMENTED** [review]
its an clear review in this program 
I had checked the program in this compailer in this program and i have check the program in VS Code

**Review by julien-deramond — APPROVED** [review]
Nice analysis 💪 LGTM!

**Pull request merged**
