### PR TITLE
Simplify ScrollSpy config

### PR DESCRIPTION
**Pull request by GeoSot**
I tried to extract a `basicJQueryInterface` to be used by other components too

### CODE REVIEW

**Comment by GeoSot** [comment]
@rohit2sharma95 , @XhmikosR 
any thoughts on this?

**Comment by rohit2sharma95** [comment]
Your idea is to move the `jQueryInterface`'s code to utils? There are few plugins that use their own interface within `jQueryInterface` :thinking: 
https://github.com/twbs/bootstrap/blob/548be2ed6604ddfc8488cd4a793c6271c2caf485/js/src/carousel.js#L563-L567

There is also a function `defineJQueryPlugin` in the utils (if it can be extended instead of writing a new function):
https://github.com/twbs/bootstrap/blob/548be2ed6604ddfc8488cd4a793c6271c2caf485/js/src/util/index.js#L203-L204

**Comment by XhmikosR** [comment]
Yeah, I'm not sure about this either. We shouldn't overdo it with unnecessary abstractions. So what's the plan here exactly?

**Comment by GeoSot** [comment]
I saw that most of them use the same functionality. So I think it could be moved as a separate function outside the component. At least for the 6 of them for the beginning.  Small size improvements as keeping one pattern. (now all have different pattern of usage)

**Comment by XhmikosR** [comment]
Please finish with your suggestion so that we can see if it's worth doing it :)

**Comment by GeoSot** [comment]
Ok. I will try to give them, same shape for start, and in a second MR I will apply the next idea

**Comment by GeoSot** [comment]
I could start standardizing a bit the configs and the interfaces, and maybe then we can discus the 'one same function'.  Does this sound better?

**Review by rohit2sharma95 — APPROVED** [review]

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
