### PR TITLE
Fixed Syntax Error found in: https://github.com/twbs/bootstrap/issues…

### PR DESCRIPTION
**Pull request by pdohmen91**
…/19324

### CODE REVIEW

**Comment by pdohmen91** [comment]
Hope this is ok. Just searched for an easy Fix for my first Commit in here.

**Comment by patrickhlauke** [comment]
Unfortunately, https://github.com/twbs/bootstrap/issues/19324 isn't valid (the placement of the `&` is correct). Thanks though!

**Comment by pdohmen91** [comment]
Ok. No Problem. Do you have some recommendations of some docs to get more easy an understanding of the code and the structure how it works?

**Comment by patrickhlauke** [comment]
https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md is a good starting point (including https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#code-guidelines). there's not much more beyond that, i'm afraid...

**Pull request closed without merging**
