### PR TITLE
Make meaning of tooltip's 'selector' option more clear in Bootstrap 3

### PR DESCRIPTION
**Pull request by shaedrich**
Based on #4215
Backport changes made to docs v4 to v3 (#27573)

### CODE REVIEW

**Comment by XhmikosR** [comment]
v3 isn't in active development, not sure if we should bother merging this at all.

**Comment by shaedrich** [comment]
Not wrong, but it is still in use by a huge amount of websites.

**Comment by shaedrich** [comment]
Oh, did I chose the wrong branch? Which one will result in being reflected in the live website?

**Comment by XhmikosR** [comment]
The default branch, which is v4-dev and already has this.

**Comment by shaedrich** [comment]
No, I mean for v3 which is as well on the live website: https://getbootstrap.com/docs/3.4/

**Comment by XhmikosR** [comment]
It won't be live because we won't cut a new release like I said.

**Comment by shaedrich** [comment]
So we v3 adherents have to stuck with confusing information in your information. Sad but it can't be helped. Thanks a lot.

**Comment by XhmikosR** [comment]
Well, we have to draw the line somewhere. It can't be supported forever. We only released 3.4.0 due to the security issues, and we need to move forward.

**Comment by shaedrich** [comment]
This was not a code change. But you still have the docs live. This was why I changed this,

**Comment by XhmikosR** [comment]
We have v1.0.0 docs live too.

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
Anyway, I'm gonna merge it but I doubt it'll be live.

**Comment by shaedrich** [comment]
Thank you, @XhmikosR. And sorry if I was disrespectful at any point of our conversation.

**Comment by XhmikosR** [comment]
All good, it's just that we need to stop bothering with the old releases at some point. I will deploy this one last time and hopefully we won't ever need to bother with 3.x.

**Comment by shaedrich** [comment]
Okay, cool. Thanks a lot. This was just one thing which was bugging me every time I read this section of the docs.

**Pull request merged**
