### PR TITLE
v4: Forms cleanup

### PR DESCRIPTION
**Pull request by mdo**
This branch aims to overhaul a decent amount of forms styles and documentation with the hopes of getting it near final. It's still WIP and has a few more todos (noted below).

#### Quick screenshot

screen shot 2016-02-09 at 1 06 30 am

#### Changes

- #17498, #18130: Removes horizontal padding on `.form-control-label` so it avoids overriding grid-based form layouts and renders correctly in stacked forms.
- #18515: Add `.form-control-{sm/lg}` classes to match small and large input classes, namely for vertical alignment of label and input in horizontal form groups.
- #18702: Updates form validation docs to include basic examples for situations in which you'd want to use each state.
- #18703: Drops `.text-help` for `.form-control-feedback`, designed specifically to only display temporary form validation feedback text _in addition to_ normal help text.
- #18704: Updates form validation docs to include examples of validation feedback text alongside always-present form field help text.

#### Todos
- [x] #17248, #17266, #19277: Fieldsets vs divs in form groups
- [x] #18390: Consider renaming .radio and .checkbox 
- [x] #18573: Consider renaming .form-control-label for it's more contextual use cases (e.g., only horizontal/grid forms and not necessary with radios/checkboxes as shown in #18389).
- ~~#19004: Color contrast and color blindness on validation colors~~ _Punting on this for another time_
- [x] #19139: Validation states on custom forms (needs select menus and file inputs)—maybe cherry-pick that PR into this one?
- [x] #19771: Form control sizing not applying to `<select>`s.

### CODE REVIEW

**Comment by petetnt** [comment]
There's also this (again) https://github.com/twbs/bootstrap/issues/19004 but that would require revisiting all the `$brand`-colors

**Comment by mdo** [comment]
@petetnt I'll add it to the todo list and see what I can do :).

**Comment by patrickhlauke** [comment]
Note https://github.com/twbs/bootstrap/pull/19277 which supersedes https://github.com/twbs/bootstrap/pull/17266

**Comment by mdo** [comment]
Decent update to this today:

- Renamed `.radio` and `.checkbox` to `.form-check`.
- Renamed `.radio-inline` and `.checkbox-inline` to `.form-check-inline`. Thought about trying to connect those classes more, but they're too different.
- Fixed #19771 so that form control sizing classes work on `<select>`s again.

Have some more fiddling to do yet, but getting there.

**Comment by mdo** [comment]
Got the bulk of this done, but still have more changes to do as follow-up.

**Comment by niftylettuce** [comment]
I see a lot of stuff is commented out, not sure where the issue is regarding this?

Screenshot:

screen shot 2016-07-17 at 4 58 32 am

**Pull request merged**
