### PR TITLE
Add License FAQ point RE: doc code examples

### PR DESCRIPTION
**Pull request by kkirsche**
[X-Ref #16470] Add License FAQ point RE: doc code examples

### CODE REVIEW

**Comment by cvrebert** [comment]
I don't think this is legally sound.

**Comment by kkirsche** [comment]
Are there any resources which we may be able to use to validate the legality either way @cvrebert?

**Comment by cvrebert** [comment]
Besides the texts of the licenses themselves or consulting a lawyer, I don't know.
I personally don't get what the theory would be for it being legal though.

**Comment by kkirsche** [comment]
I can understand your view on that @cvrebert. My reasoning was more like so:

Yes the license itself may not, but I don't think the issue here is the license itself so much as how it is applied to the code itself. In the readme it says, "Code released under the MIT license. Docs released under Creative Commons." you could make the argument that code implies all code in the repository where docs could mean just the formal documentation. Since you don't formally define what you guys mean by "docs" I think it'd be possible to argue it as a legal use.

Currently, if it is illegal to use any of the docs under CC, that means you cannot use any of the example websites, etc. So does that mean the templates the docs recommend people use are illegal as well?

**Comment by kkirsche** [comment]
Want to follow up on this but not sure of the next steps for this PR due to the legal nature and me not being a lawyer. Thoughts?

**Comment by kkirsche** [comment]
Want to follow up on this but not sure of the next steps for this PR due to the legal nature and me not being a lawyer. Thoughts?

**Comment by mdo** [comment]
Honestly I have no idea how to proceed. It sounds like we should relicense, but that's a huge ordeal.

**Comment by kkirsche** [comment]
@mdo is the re-license process simply (I say simply as in this is "only" one step, not in regards to the simplicity / ease of the task) to get written consent from all contributors to those file(s) or is there more to the process than this?

**Comment by mdo** [comment]
That's the one (big) step, yup.

**Comment by kkirsche** [comment]
@mdo how was the move to MIT done in the past? While I was aware that there was a shift I hadn't paid close attention to the actual process at that time.

Ultimately, I ask because if you decide you would like to re-license, I would be interested in helping with the process, I just want to understand what the process looks like. 

If you are up in the air though about whether you would like to re-license, feel free to ignore this comment until you all make a decision regarding that as the process isn't as important if there isn't a reason to go through it.

**Comment by juthilo** [comment]
For the change from Apache to MIT, we had a giant spreadsheet that had all the email addresses from `git log` to track responses and a Google web form that we emailed to all of them. Took a lot of time and (while only two people or so said No to the change) not everyone was happy about suddenly getting emails from us.

So I'd be very careful with kind of doing it all again (if only for a subset of contributors).

**Comment by kkirsche** [comment]
I can certainly understand that @juthilo — and I appreciate your explanation about the process of doing something like this.

Ultimately — if this is something that would like to be done, let me know. Otherwise I think this is something that can and should be addressed when releasing V4 to ensure everything is appropriately licensed up front.

**Comment by cvrebert** [comment]
Given the current licensing state, we can't apply this PR for the foreseeable future.

**Comment by kkirsche** [comment]
Since V4 is new documentation I don't follow @cvrebert

**Comment by cvrebert** [comment]
> Since V4 is new documentation

It's not new; it's just the v3 docs with many changes applied.
Also, we aren't accepting pull requests targeted at v4 currently. Those will have to wait until v4.0.0-alpha is publicly released.

**Comment by kkirsche** [comment]
Ah ok. Thanks for clarifying. If this is something the team changes their mind on though let me know as I would love to see it re licensed

**Pull request closed without merging**
