### PR TITLE
Higher priority for .btn-primary

### PR DESCRIPTION
**Pull request by Yahasana**
`.btn-primary` should has higher priority than `.btn-secondary`

### CODE REVIEW

**Comment by Yahasana** [comment]
it'll be easier to change the secondary state to primary by just toggle `btn-primary` class through js. now i have to remove the `btn-secondary` then add `btn-primary`

**Comment by Starsam80** [comment]
@Yahasana Did you try using [`$.toggleClass('btn-primary btn-secondary')`](https://api.jquery.com/toggleclass/)?

**Comment by Yahasana** [comment]
```html
<button class="btn btn-secondary">default</button>
```
```js
$el.toggleClass("btn-primary") ==> 
    <button class="btn btn-secondary btn-primary">primary</button>
```
again return to default state
```js
$el.toggleClass("btn-primary") ==> 
    <button class="btn btn-secondary">default</button>
```
```js
$el.toggleClass('btn-primary btn-secondary') ==>
    <button class="btn">incorrect button</button>

**Comment by Yahasana** [comment]
BTW, in BS 3.x `btn-primary` has higher priority than `btn-default`. why don't keep this rule in v4

**Comment by Yahasana** [comment]
@Starsam80 after a second thought, you are right. `$el.toggleClass('btn-primary btn-secondary')` works. but `$el.toggleClass('btn-primary')` is 💯 clean

**Comment by mdo** [comment]
> why don't keep this rule in v4

These classes are individual modifier classes that aren't intended to be stacked on top of one another. Use one or the either. There was no rule for this in v3 either; just kind of happenstance that one was before the other.

**Pull request closed without merging**
