### PR TITLE
Offcanvas example: transition the transform

### PR DESCRIPTION
**Pull request by XhmikosR**
This is more efficient.

Opening this so that we don't forget about it.

### CODE REVIEW

**Review by MartijnCuppens — APPROVED** [review]

**Comment by XhmikosR** [comment]
Not sure about removing `visibility`. Let's put it on hold for now.

**Comment by ysds** [comment]
Please see #25524 for why `visibility` is necessary.

**Comment by XhmikosR** [comment]
OK, I added back visibility.

**Comment by ysds** [comment]
These changes increase the file size, but it will be more efficient in the future.

**Comment by XhmikosR** [comment]
We need to promote the best practices.

**Comment by ysds** [comment]
If I am not misunderstanding your comment, I agree with these changes.

**Comment by XhmikosR** [comment]
Yeah, we say the same thing :)

**Pull request merged**
