### PR TITLE
Reset text/font properties more thoroughly for tooltips+popovers

### LINKED ISSUE #15925: Tooltips and popovers still inherit `font-style` and others
In Bootstrap v3.3.1 many of the font settings were properly reset for tooltip/popover content via https://github.com/twbs/bootstrap/commit/2862c30320e8a1c0499f4bd83141e0c6cd959f1e. I'm glad the decision was made in this direction, to reset font/text back to defaults within the content — but the implementation was incomplete. For example, we noticed already that a popover within `font-style: italic` text has its contents still italic. So https://github.com/twbs/bootstrap/issues/15046 does not seem fully resolved yet.

In case it's helpful, here's a LESS snippet (including a link that could lead you to a [relevant reference](http://dev.w3.org/csswg/css-pseudo-4/#first-line-styling)) that I used for resetting fonts in a non-Bootstrap project:

```
.reset-text(@fontsize) {    // used to avoid unwanted inheritance of text-related styles from a parent
    // most of this list is based on properties first-line applies to [NOTE: hasn't been exhaustively reviewed]
    // see https://developer.mozilla.org/en-US/docs/Web/CSS/::first-line (and W3C spec) for more details
    font-style: normal; font-variant: normal; font-weight: normal; line-height: normal;
    font-size: @fontsize;
    // font, font-family omitted
    color: black;
    word-spacing: normal; letter-spacing: normal; text-decoration: none; text-transform: none;
    text-shadow: none;
    
    // some other properties added in as well
    text-indent: 0;
    text-align: left; text-align: start;
}
```

Note that the snippet above is not exhaustive (it likely covers only the properties we used/anticipated in this particular app and/or predates more properties being added to the spec) but hopefully a more thorough start — not to mention perhaps the idea to encapsulate all the reset in a reusable LESS mixin is valuable.

### PR DESCRIPTION
**Pull request by cvrebert**
Fixes #15925.
Note: This changes the Tooltip `line-height` from `1.4` to `@line-height-base` (`1.428571429`)
Also enhances the explanatory comments a bit.

### CODE REVIEW

**Comment by mdo** [comment]
This seems like overkill honestly. In Primer, we've gotten away with around half this reset: https://github.com/primer/primer/blob/master/scss/_tooltips.scss. It doesn't cover the same amount of things as Bootstrap might encounter, but it's worked out well so far.

**Comment by cvrebert** [comment]
I grant you that `font-kerning`, `text-indent`, `font-variant`, and `text-emphasis` are more on the paranoid side. Would removing those alleviate your concerns?

Other than those, all this PR adds compared to Primer is:
```css
line-break: auto;
word-break: normal;
word-spacing: normal;
```
which are more vanilla/common properties; I am thinking that hypothetical bugs caused by the lack of these 3 resets would end up being deemed legit bugs? So might as well just fix them now.

**Comment by mdo** [comment]
Sure, let's roll with those.

**Comment by cvrebert** [comment]
@mdo Okay, revised. LGTY?

**Comment by mdo** [comment]
Yup, :shipit:.

**Pull request merged**
