### PR TITLE
JS: use rollup to set BS version in js files

### PR DESCRIPTION
**Pull request by GeoSot**
### Description

Trying to minimize the changes between different BS versions, we can set a standard string (`__BS_VERSION__`) inside javascript files and, delegate the replacement job to `rollup`, while it creates the dist files

The same can be done at `css` files, using `postcss-replace` https://www.npmjs.com/package/postcss-replace

### Type of changes

- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] All new and existing tests passed

#### Live previews

https://deploy-preview-37494--twbs-bootstrap.netlify.app/

* open console and type `bootstrap.Alert.VERSION`. You will receive the proper version

### Related issues
rel #35010
rel #37516

### CODE REVIEW

**Review by mdo — DISMISSED** [review]
Love it! Just gotta find something to update for Sass—thinking a variable maybe? Unsure.

**Comment by ffoodd** [comment]
What about using [the banner output option in Rollup](https://rollupjs.org/guide/en/#banner)? Or is the banner mandatory in source files too?

**Comment by GeoSot** [comment]
>What about using [the banner output option in Rollup](https://rollupjs.org/guide/en/#banner)? Or is the banner mandatory in source files too?
We can omit the too, I suppose, or make another trick. I will experiment on another PR 😉

**Comment by ffoodd** [comment]
FWIW in a current project, banner isn't in source files but only in dist files.

I used Terser's format argument with the `preamble` option to output the banner from the terser command in `package.json`, and postcss-banner to do the same from the postcss config file. The main drawback for CSS is that I needed to import `package.json` in PostCSS config file to access its variables.

Works pretty well for now 👌

**Comment by GeoSot** [comment]
@ffoodd can you make a PR with your thoughts? I would like to check it, as in my mind seems a fine solution too, and will help a lot to automate our releases

**Comment by ffoodd** [comment]
I'll try to!

**Comment by XhmikosR** [comment]
Alternatively we could just drop the version from the src files?

**Comment by XhmikosR** [comment]
NVM, forgot we have it in code too, except for the license.

**Comment by XhmikosR** [comment]
So, the thing with this patch is that is a breaking change for anyone building Bootstrap JS. Now, rollup will be required for them, otherwise `foo.VERSION` will return `__BS_VERSION__`.

**Comment by XhmikosR** [comment]
IMHO opinion we should just keep using our release-version script but instead tweak it/limit the files it touches.

**Comment by GeoSot** [comment]
Nice catch. We can keep it only in the base component, and remove the banners from all the js files. as they are appended during build

**Comment by XhmikosR** [comment]
Even if it's one file, it's a breaking change. I don't want to add yet another dependency for people to consume the files at this point.

Like I said, we can easily tweak the release-version script and limit the files it touches. This should be a good intermediate solution IMHO.

**Comment by GeoSot** [comment]
> Like I said, we can easily tweak the release-version script and limit the files it touches. This should be a good intermediate solution IMHO.

The same thing we are talking about. Removing all the banners and keep the version info only in the base-component file. so we will need to touch only one scss and one js file

**Pull request closed without merging**
