### PR TITLE
Dismissable alert close button padding

### LINKED ISSUE #24469: Dismissible alert - long text overlaps close button
Not sure i understand why close button now has absolute positioning in Beta2, but now if text in alert is too long, it overlaps close button. I think we need to add extra right padding to dismissible alert to ensure text and button are always visible.

Image

### PR DESCRIPTION
**Pull request by MattJLeach**
I have increased the y padding for the alert and made the padding for the close button the same all round.

Fixes #24469

### CODE REVIEW

**Comment by andresgalante** [comment]
Hi @MattJLeach Thanks a lot for trying to fix this.

The solution you are proposing adds a huge padding on the left or the alert. I don't think this is valid solution.

**Comment by MattJLeach** [comment]
Would you prefer to have increased padding on the right and keep the left the same as it is now? The only reason I increased both was to keep the text in the centre.

**Comment by andresgalante** [comment]
@MattJLeach I think the padding should go on the parent, not on the close icon, as I describe here #24469

**Comment by andresgalante** [comment]
Hi @MattJLeach, I am going to close this PR in favor of #24481

Thanks a lot for taking the time to make a contribution

**Comment by MattJLeach** [comment]
Sounds good @andresgalante. Thanks for the feedback on my PR. I'll keep an eye out for any other issues I can help with but comment and discuss before doing an actual PR first.

**Comment by andresgalante** [comment]
Thanks man, feel free to send as many PRs as you can, it'll be my pleasure to review them.

**Pull request closed without merging**
