### PR TITLE
Fix new stylelint-config-recess-order issues

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@julien-deramond LGTY?

**Comment by julien-deramond** [comment]
> @julien-deramond LGTY?

I don't know if it must be rebased onto something or if there's a missing dep bump, but you got a "Lint" error in the workflow:

```
scss/_nav.scss
  173:5  ✖  Expected "flex-basis" to come before "flex-grow"  order/properties-order

scss/_navbar.scss
  143:3  ✖  Expected "flex-basis" to come before "flex-grow"  order/properties-order

✖ 2 problems (2 errors, 0 warnings)

ERROR: "css-lint-stylelint" exited with 2.
```

**Comment by XhmikosR** [comment]
Yeah that's normal, it will work after #40895

**Comment by julien-deramond** [comment]
In that case, yeah, no problem with this modification :)

**Comment by XhmikosR** [comment]
My point is if any of the behavior changes because some properties were overridden, https://github.com/stormwarning/stylelint-config-recess-order/issues/385

**Review by julien-deramond — APPROVED** [review]
LGTM for when https://github.com/twbs/bootstrap/pull/40895 will be merged

**Pull request merged**
