### PR TITLE
docs(forms): switch to aria-describedby

### PR DESCRIPTION
**Pull request by ffoodd**
### Description

`aria-labelledby` is wrongly used here since it overrides existing `label`: either we add `label`'s `id` as the first value in `aria-labelledby`, or we switch to `aria-describedby` as done in this PR.

In both cases, I think the callout before should mention this difference between the two attributes. 

Friendly ping @patrickhlauke as you may have another recommendation. :)

### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] I have updated the documentation accordingly
- [ ] ~~I have added tests to cover my changes~~
- [x] All new and existing tests passed

#### Live previews

- <https://deploy-preview-{your_pr_number}--twbs-bootstrap.netlify.app/>

### CODE REVIEW

**Review by patrickhlauke — APPROVED** [review]
Yup, agree, that's wrong. any other places where we might have the same oversight?

**Comment by ffoodd** [comment]
I checked the forms page without luck but didn't check examples or cheatsheet.

**Comment by patrickhlauke** [comment]
ah, now i remember where that came from... https://github.com/twbs/bootstrap/pull/37587

I was actually not convinced by that PR myself, but it was merged anyway. I would still say that the assertion at the basis of that PR is...debatable. I would suggest just wholesale reverting that PR, to be honest.

**Comment by patrickhlauke** [comment]
i.e. also remove the paragraph that says authors should use `aria-labelledby` ...

**Comment by julien-deramond** [comment]
Friendly ping @hannahiss and @aniort. Might be interested in the topic.

**Comment by patrickhlauke** [comment]
> I would propose to add label's id as the first value, since using `aria-labelledby` for mandatory information could be a good idea...?

While I understand the "could be a good idea" part, I personally think this ends up being massively overengineered for what it actually is/does (particularly for a generic example in our documentation). It's been generally accepted practice to use `aria-describedby` to link additional info and instructions for a form field. The nuance of "if this is mandatory, it should be in the accessible label, not in the accessible description" is one that I'd say should be left up to authors to decide. Any more information on the original assertion that `aria-labelledby` is better supported than `aria-describedby`?

**Comment by patrickhlauke** [comment]
> Please don't revert totally https://github.com/twbs/bootstrap/pull/37587 because the first part (in input-group) is still needed.

ah yes, good point. agree, that part is non-controversial and correct

**Comment by ffoodd** [comment]
Agreed, if it's that much important it should probably be in `<label>`, not passed as a potentially wrong label override.

**Comment by ffoodd** [comment]
I just reverted the callout changes from #37587, and also improved labels in select sizing examples—which previously mentioned class names…

**Pull request merged**
