### PR TITLE
Fix mixed-content warnings caused by CarbonAds.

### PR DESCRIPTION
**Pull request by bardiharborow**
Related to #20283.

### CODE REVIEW

**Comment by FezVrasta** [comment]
Wouldn't better let the browser decide the protocol? `//engine.carbon...`

**Comment by cvrebert** [comment]
Are we sure that CarbonAds supports HTTPS?

> Wouldn't better let the browser decide the protocol?

[The Protocol-relative URL technique is now an anti-pattern.](https://twitter.com/paul_irish/status/588502455530311680?lang=en)

**Comment by FezVrasta** [comment]
Thanks I didn't know, btw yes, it supports https as far I know

**Comment by bardiharborow** [comment]
I should also mention that the way Carbon ads are being inculded causes them to be picked up by Adblock Plus despite them being included in the [Acceptable Ads list](https://adblockplus.org/forum/viewtopic.php?f=12&t=42309).

**Comment by FezVrasta** [comment]
This is due to the `carbonads-container` class.

As you see, removing it, the AD is displayed correctly:
http://rosskevin.github.io/bootstrap-material-design/

**Comment by bardiharborow** [comment]
@FezVrasta I've [raised this issue with ABP](https://adblockplus.org/forum/viewtopic.php?f=12&t=42309&p=157435#p157435).

**Comment by mdo** [comment]
Alternate fix in 4a63dc6.

**Pull request closed without merging**
