### PR TITLE
Added page-label

### PR DESCRIPTION
**Pull request by Alpine418**
Added page-label to get a non-anchor text. E.g. used between the next/previous buttons for "Page 2 of 5".

HTML example for docs (not part of the pull request):

```html
<ul class="pagination">
  <li class="page-item">
    <a class="page-link" href="#">Previous</a>
  </li>   
  <li class="page-item">
    <span class="page-label">Page 2 of 5</span>
  </li>
  <li class="page-item">
    <a class="page-link" href="#">Next</a>
  </li>
</ul>
```

### CODE REVIEW

**Comment by XhmikosR** [comment]
@twbs/css-review: the PR author has deleted their fork thus this will need manual actions to merge it.

So, please decide if we need this, if not just close the PR.

**Comment by rjgamer** [comment]
Would be nice to implement it. Sorry for deleting my fork.

What should I do?

**Comment by XhmikosR** [comment]
Unfortunately, we can't do anything with this PR since the fork was deleted. You can make a new PR based on the latest v4-dev if you want.

**Comment by rjgamer** [comment]
I will do this. Sorry again!

**Comment by rjgamer** [comment]
New PR created: https://github.com/twbs/bootstrap/pull/27601

**Pull request closed without merging**
