### PR TITLE
Parameterize @breadcrumb-separator

### PR DESCRIPTION
**Pull request by dancek**
This puts the breadcrumb separator into a variable, making it easy to use any other separator besides the default / . The compiled CSS is not changed, so this does not cause any issues with the default value.

### CODE REVIEW

**Comment by mlt** [comment]
How one would use let's say fontawesome icon as a separator? I tried to pass enquoted html code to this variable and I got it verbatim. Can it be generalized?

**Comment by dancek** [comment]
@mlt You need to set font-family to FontAwesome (iirc) and look up the char code (iirc the FA docs mention it, but if all else fails, check the FA css).

It's doable, but I can't check the specifics right now.

**Comment by mlt** [comment]
@dancek Thank you for getting back so promptly! I got thick unicode symbol I wanted.

Being a noob to twbs and sass, I often hesitate between setting a parameter/variable vs overriding the block by writing all the selector stuff and what goes there myself. Hence I asked a Q here (that probably belongs elsewhere :innocent:) . It seems that, if a separator character is to be parameterized, so should be a font. Otherwise, instead of leveraging this, I'd have to write a similar block to define a font. Then why would I need a parameter for the separator, if it just can go into the same block?

**Comment by dancek** [comment]
@mlt I agree that in your use case, changing the separator character via Bootstrap parameter makes no sense unless the font is also a parameter. Not sure how common a use case it is, but I think a PR for parameterizing the font would make sense.

Note that I've written this PR over 3 years ago and I haven't even used Bootstrap in over a year :)

**Pull request merged**
