### PR TITLE
Use HTTPS to load grunt-sed

### PR DESCRIPTION
**Pull request by ncksllvn**
Issue #17445

### CODE REVIEW

**Comment by XhmikosR** [comment]
@cvrebert: should we backport grunt-sed to v4?

**Comment by cvrebert** [comment]
My current thought is to replace it with a small npm script in the Bootstrap repo.

**Comment by XhmikosR** [comment]
Indeed it should be doable and not so hard to implement. Maybe make a new
issue to track this?

**Comment by mdo** [comment]
Should this be merged @cvrebert?

**Comment by cvrebert** [comment]
Negatory.

**Comment by cvrebert** [comment]
@XhmikosR Opened #18338 for tracking that

**Pull request closed without merging**
