### PR TITLE
V4 dev backports and updates

### PR DESCRIPTION
**Pull request by XhmikosR**
Preview: <https://deploy-preview-30836--twbs-bootstrap.netlify.app/>

### CODE REVIEW

**Comment by XhmikosR** [comment]
@twbs/css-review I pushed a temp patch after dist. Can you check if the IE/Edge workarounds are still fine?

**Comment by XhmikosR** [comment]
So, can someone from @twbs/css-review check my comment above please? https://github.com/twbs/bootstrap/pull/30836#issuecomment-629967644

The "Temp commit is here: https://github.com/twbs/bootstrap/pull/30836/commits/593a63c2c7a28e64b511788ce99214922c67fcc0

**Comment by ffoodd** [comment]
About the floating labels example, I'm a bit confused: there's an old patch for IE that seems to… break the example.

If I remove it, the example works fine in IE11 (tested on BrowserStack, W7 & W10). 
However the Edge patch seems required. Both were introduced in #25919, but [MDN compatibility table](https://developer.mozilla.org/en-US/docs/Web/CSS/:placeholder-shown#Browser_compatibility) seems clear: IE10 & 11 did support their vendor version.

I'd be in favor of removing it (but should probably be another PR, souldn't it?).


For the `.text-break` class, I think `overflow-wrap` should be `word-wrap`. Am I right, @mdo?

**Comment by XhmikosR** [comment]
>I'd be in favor of removing it (but should probably be another PR, souldn't it?).

Yup, thanks for having a look.

> For the `.text-break` class, I think `overflow-wrap` should be `word-wrap`. Am I right, @mdo?

I just reverted #30074 here.

**Review by MartijnCuppens — APPROVED** [review]

**Pull request merged**
