### PR TITLE
Minor alignment fixes

### PR DESCRIPTION
**Pull request by entozoon**

### CODE REVIEW

**Comment by mdo** [comment]
Thanks, but these are fine as-is. The primary reason I align things like this across lines is for editing multiple lines at once; it's unlikely you'll need or want to edit these at the same time.

**Comment by entozoon** [comment]
@mdo Not to be a nitpick nelly, but I noticed the same changes were later made and approved :(
https://github.com/twbs/bootstrap/commit/54908a95a87b592d81df3231823979c75917d57a#diff-0a2f34e035b36da00e5ac44b48a707df
(I'm just hoping to contribute more and more)

**Comment by mdo** [comment]
Sorry about that @entozoon. I was rushing through things the last few days and decided against this with the Hound errors. I later fixed it for a more comprehensive PR and didn't swing back to this. Please do keep contributing! <3

**Comment by entozoon** [comment]
No problem, will do! :)
Thanks for the reply

**Pull request closed without merging**
