### PR TITLE
Stop oversized images in .card-img-* from overflowing the card's boundaries

### PR DESCRIPTION
**Pull request by simeon**
Images in cards using card-img-top or card-img-bottom ~~via src="" (instead of data-src="")~~ would overflow past the bounds of the card if the image width was too large.  Now they will at most be equal to the width of the card.

### CODE REVIEW

**Comment by cvrebert** [comment]
FYI, `data-src` is a [Holder.js](https://github.com/imsky/holder)-ism. The fact that `data-src` was ever shown in the docs code snippets was a bug (#18558).
So you're really just talking about oversized images in general.

**Comment by cvrebert** [comment]
Seems like it might be better to `@include img-fluid` instead, but I'm not too familiar with the Cards code.

**Comment by simeon** [comment]
@cvrebert I looked into it and you're right. Using @include img-fluid(block); would do the same job with a better "grammer".  I've updated my commit to reflect that.

**Comment by cvrebert** [comment]
Have you tested this out when Flexbox is enabled (`$enable-flex: true;`)?

**Comment by simeon** [comment]
@cvrebert  Yup, I just recompiled with Flexbox enabled and it's all good.

**Comment by cvrebert** [comment]
CC: @mdo for final review

**Comment by mkroeders** [comment]
Have this issue also, so to counter it I did an .img-fluid on the img. . Which did not solve it for me, a width: 100% was needed for me.

I checked when you use $enable-flex: true; the width: 100% is needed otherwise the .img-fluid is enough.

**Comment by mdo** [comment]
This was addressed with the use of utilities in #20667, but I didn't check out the flex variation. If that's still a problem, can one of y'all open an issue with a test case that confirms that behavior? <3

**Pull request closed without merging**
