### PR TITLE
v4 - Move collapse js away from panels to cards

### LINKED ISSUE #17170: Move collapse js away from panels to cards
Panels still exists it seems in collapse instead of cards unless I'm misreading it:

https://github.com/twbs/bootstrap/blob/v4-dev/js/src/collapse.js#L59

### PR DESCRIPTION
**Pull request by kkirsche**
Fix #17170 

Probably cc fat?

### CODE REVIEW

**Comment by cvrebert** [comment]
@kkirsche Could you please rebase this?

**Comment by kkirsche** [comment]
@cvrebert rebased

**Comment by kkirsche** [comment]
The failure here is unrelated to the change made:

```
Running "scsslint:src" (scsslint) task
Running scss-lint on src
scss/_reboot.scss:286 [W] PropertySortOrder: Properties should be ordered box-sizing, -webkit-appearance
Warning: Task "scsslint:src" failed. Use --force to continue.
Aborted due to warnings.
```

**Comment by cvrebert** [comment]
@kkirsche `× 4 tests failed in "collapse" module` when I test it locally.
(There are some other failures, but those are also present in `v4-dev` :unamused: )

**Comment by kkirsche** [comment]
@cvrebert noted. I'll look at those probably next week. Traveling for work this week so may be a bit before I can tackle making those fixes

**Comment by dalabarge** [comment]
Would it be possible to also have this be a configurable selector using `data-selector` or something? Having JS rely upon hard-coded HTML class names makes it more difficult to use semantic class names and then use SCSS to mixin the appropriate styles. Just spent an hour or so trying to get this working before reading the source and realizing it was selecting child elements of `.panel` (now `.card`) instead of just collapsing the elements matching `$(parent).find('.collapse.in')`. What's the reason we're sticking to making this plugin dependent upon any specific HTML class name?

**Comment by cvrebert** [comment]
@dalabarge That's still on the roadmap. This is just a quick fix until we can get around to implementing that.
See #17021:
> #### Collapse
> * Make accordion feature of collapse plugin independent of panels?: twbs/bootstrap#10966

**Comment by fat** [comment]
yeah this is great - do you mind just  poppin `ACTIVES` selector onto the default object while you're at it so people can change?

**Comment by fat** [comment]
(otherwise lgtm)

**Comment by mdo** [comment]
Would love to get this merged into Alpha 5. Was @fat's feedback addressed?

**Comment by Johann-S** [comment]
My PR https://github.com/twbs/bootstrap/pull/18400 do the same things but is up to date and apply changes to ``js/tests/visual/modal.html`` which use Collapse too.

**Comment by mdo** [comment]
Merged #18400 to address this. Thanks though @kkirsche!

**Comment by kkirsche** [comment]
Course. Thanks for considering this

**Pull request closed without merging**
