### PR TITLE
Use pseudo-class too for disabled check/radio

### LINKED ISSUE #29739: Check/radio doesn't consider disabled fieldset
As disabled attribute is used instead of :disabled pseudo-class, check/radio inputs are not rendered as disabled when they are contained in a disabled fieldset (see: https://jsfiddle.net/o17mLfda/1/).

### PR DESCRIPTION
**Pull request by jeromelebleu**
In order to consider check/radio inputs inside a disabled fieldset, this first use the :disabled pseudo-class. By the way, the URL of the relevant issue on M$ Edge seems broken or needs at least an account to track its progress...

fixes #29739

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
Maybe we could link to https://github.com/twbs/bootstrap/issues/28247 instead?

**Review by MartijnCuppens — CHANGES_REQUESTED** [review]
This should also be changed in `_form-file.scss`

**Comment by jeromelebleu** [comment]
Thanks for the link and the review. I have updated the patch to use the suggested workaround for Edge instead to keep only the `:disabled` pseudo-class for the ruleset. However, I don't have Edge to validate that it is still working on it. Could someone check that please?

**Comment by ysds** [comment]
I am not a fan of such CSS hack 😕. I think the previous change (both `:disabled` and `[disabled]` ) is better.

**Comment by jeromelebleu** [comment]
@ysds I agree with you, besides it seems to come out of nowhere... I have switched to this hack as it has been tested on Edge and implemented in other projects regarding #28247, and because I cannot confirm that using both `:disabled` and `[disabled]` will work on it too. But it is as you want for sure.

**Comment by MartijnCuppens** [comment]
I agree with @ysds here

**Comment by ysds** [comment]
I want to include this to 4.4.1 if we can work quickly.

**Comment by jeromelebleu** [comment]
I have made changes accordingly, if someone can confirm that it is working on Edge please.

**Comment by ysds** [comment]
I created a PR for v4: #29762

**Comment by ysds** [comment]
So no longer need to rush this PR :)

**Comment by ysds** [comment]
I checked the following test cases:

- Current (master) https://codepen.io/fellows3/pen/jOENWQe
- After https://codepen.io/fellows3/pen/xxbKZyb

**Review by ysds — APPROVED** [review]

**Review by MartijnCuppens — APPROVED** [review]

**Pull request merged**
