### PR TITLE
Re-add flex-grow to .navbar-collapse

### LINKED ISSUE #32383: .navbar-collapse block occupies 100% width. This causes space issue to other elements placed outside the navbar-collapse block.
- OS: Windows 10
- Browser: Chrome latest

The code in bootstrap-4 uses the following, This works fine

```css
.navbar-collapse {
  flex-basis: 100%;
  flex-grow: 1;
  align-items: center;
}
```

The code in bootstrap-5 uses the following. This causes the words in the btn block that is placed outside the nav-collapse block to break.

```css
.navbar-collapse {
    align-items: center;
    width: 100%;
}
```

bootstrap5-bug

### PR DESCRIPTION
**Pull request by mdo**
Fixes #32383. Replaces #32794.

Turns out the other PR didn't fix things without additional changes, but this _should_ by replacing `width: 100%` with `flex-grow: 1`. Will need to verify with other navbars that nothing is broken.

Demo: https://codepen.io/emdeoh/full/xxEoNKN

### CODE REVIEW

**Comment by XhmikosR** [comment]
Confirmed https://codepen.io/XhmikosR/pen/NWReGay

Unsure if it causes any side effects, though.

**Review by ffoodd — APPROVED** [review]
LGTM, compared branch to main for navbar docs and examples without noticing anything.

**Comment by satya013** [comment]
View it on GitHub don't send notification to mail

**Comment by jonnysp** [comment]
that doesn't look good to me 

grafik

**Comment by ffoodd** [comment]
@jonnysp please open a new issue with a reduced test case please, we won't dig up a merged PR.

**Pull request merged**
