### PR TITLE
Merge lint scripts

### PR DESCRIPTION
**Pull request by XhmikosR**
It seems ESLint is faster for me this way, stylelint is slower though.

Note that you should remove the `.cache` directory prior to making any tests.

/CC @twbs/team

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
I'm ok with this. Personally I would prefer `\"**/*.{css,scss}\"` (not sure if the curly brackets need to be escaped) instead of `\"**/*.scss\" \"**/*.css\"`

**Comment by XhmikosR** [comment]
Merge those, good call.

**Review by MartijnCuppens — APPROVED** [review]

**Comment by XhmikosR** [comment]
@Johann-S can you try this too?

**Comment by Johann-S** [comment]
It works well for me too 👍

**Pull request merged**
