### PR TITLE
Remove unneeded "Edge Legacy" mention in Range docs

### PR DESCRIPTION
**Pull request by coliff**
Edge Legacy is dead and unsupported so no need to mention here.

### CODE REVIEW

**Review by ffoodd — APPROVED** [review]
Agreed, otherwise we should mention IE11 which also supports filling progress track.

**Comment by Leoking78** [comment]
> Agreed, otherwise we should mention IE11 which also supports filling progress track.

**Comment by Leoking78** [comment]
> Agreed, otherwise we should mention IE11 which also supports filling progress track.

**Comment by Leoking78** [comment]
> Agreed, otherwise we should mention IE11 which also supports filling progress track.

**Comment by Leoking78** [comment]
> Agreed, otherwise we should mention IE11 which also supports filling progress track.

**Review by Leoking78 — APPROVED** [review]

**Comment by Leoking78** [comment]
> Agreed, otherwise we should mention IE11 which also supports filling progress track.

**Comment by Leoking78** [comment]
> Agreed, otherwise we should mention IE11 which also supports filling progress track.

**Comment by Leoking78** [comment]
> Agreed, otherwise we should mention IE11 which also supports filling progress track.

**Comment by Leoking78** [comment]
> Agreed, otherwise we should mention IE11 which also supports filling progress track.

**Review by mdo — APPROVED** [review]

**Pull request merged**
