### PR TITLE
Explictly add `cursor:pointer` to dropdown menu items

### LINKED ISSUE #25350: <button> menu items inside dropdown have cursor: default
With beta.3 Bootstrap brought back `cursor: pointer` for buttons. However when having menu items using `<button>` tags inside dropdown they still use `cursor: default` (see this [example from docs](https://getbootstrap.com/docs/4.0/components/dropdowns/#menu-items)). I believe it is a bug and menu items should also have `cursor: pointer`.

### PR DESCRIPTION
**Pull request by patrickhlauke**
Follow-up to #25082

Closes #25350

### CODE REVIEW

**Comment by XhmikosR** [comment]
@patrickhlauke: Isn't there any way to inherit this?

**Comment by mdo** [comment]
Our v4 release is tomorrow morning, punting this to our next release.

**Comment by patrickhlauke** [comment]
> @patrickhlauke: Isn't there any way to inherit this?

inherit it from where? unless we add opinionated `button { cursor: pointer; }` or similar, i think explicitly defining it makes more sense. would also cover weirder scenarios where authors use some arbitrary element like `<span role="button" tabindex="0">` or whatever in their menus

**Comment by XhmikosR** [comment]
I thought we set this at a higher level, yeah. If not, your PR seems good to me. But the final decision is on @mdo :)

**Comment by MaPePeR** [comment]
The same problem exists with Buttons in List Groups ([example from docs](https://getbootstrap.com/docs/4.0/components/list-group/#links-and-buttons)).

**Comment by mdo** [comment]
I think we'll go for #25598.

**Pull request closed without merging**
