### PR TITLE
Prevent pointer-events on disabled anchor dropdown-item

### LINKED ISSUE #26695: Inconsistency between disabled anchors
Hi, I've noticed and was wondering whether there was a conscious decisions for:

`a.btn.disabled` having `pointer-events: none;`

https://getbootstrap.com/docs/4.1/components/buttons/#disabled-state

But anchors inside a Menu Item / split-button do not, and still have a pointer.

https://getbootstrap.com/docs/4.1/components/dropdowns/#disabled

I've also noticed that if we remove the `href` from an anchor (which makes the browser treat the anchor as non-interactable), the `disabled` style is actually overridden by:

```
a:not([href]):not([tabindex]) {
    color: inherit;
    text-decoration: none;
}
```

That's quite annoying.

I'd be happy to submit a PR to change both of these, if they weren't intentional decisions, otherwise I'll just override locally.

### PR DESCRIPTION
**Pull request by howardcox**
Fixes #26695

### CODE REVIEW

**Comment by andresgalante** [comment]
Why are you qualifying the selector?

You could add this under:

```scss
&.disabled,
  &:disabled {
```
on line 137. Or am I missing something?

**Review by andresgalante — APPROVED** [review]
Hi @howardcox I've just patched your PR to have the desired result without the qualifying the selector.

Thanks a lot!

**Comment by andresgalante** [comment]
Right, but even if `dropdown-item` is a btn I don't how it hurts to have the pointer events none there.

cc/ @patrickhlauke am I missing something?

**Comment by howardcox** [comment]
Can this get merged at some point? It's missed 4.1.2 and 4.1.3

**Comment by XhmikosR** [comment]
Ping @patrickhlauke

**Comment by jquense** [comment]
I'd expect `list-group-item` to also have this for consistency yeah?

**Comment by howardcox** [comment]
Ok e8ac9ca adds this to `_list-group.scss` too

**Comment by XhmikosR** [comment]
Ping @patrickhlauke

**Review by patrickhlauke — APPROVED** [review]

**Pull request merged**
