### PR TITLE
Add transition to property-blacklist

### PR DESCRIPTION
**Pull request by MartijnCuppens**
In each PR, we need to check manually if the `@transition` mixin is used instead of the `transition` property. By adding this stylelint rule, the `css-lint` command will take care of this.

### CODE REVIEW

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
@MartijnCuppens: there are more instances of transition in docs.

**Comment by MartijnCuppens** [comment]
Changed it.

The stylelint check also happens on the custom css files. There are several ways we can handle this:
1. Leave it as it is now (Add `/* stylelint-disable-next-line property-blacklist */` above the transition declaration)

2. Also add this query in the css files:
```css
@media screen and (prefers-reduced-motion: reduce) {
  .selector {
    transition: none;
  }
}
```
3. Change stylelint config in `site/docs/4.1/examples/.stylelint`

Which way do you want to go with this?

**Comment by XhmikosR** [comment]
Hmmm... not sure to be honest.

@andresgalante @mdo  thoughts?

**Comment by XhmikosR** [comment]
Oh, and @MartijnCuppens jump on Slack if you want :)

**Review by mdo — APPROVED** [review]

**Review by XhmikosR — APPROVED** [review]
Thanks!

**Pull request merged**
