### PR TITLE
V4 dev backports and updates

### PR DESCRIPTION
**Pull request by XhmikosR**
Refs #31823

### CODE REVIEW

**Comment by XhmikosR** [comment]
This should restore the ES5 enforcement in tests @Johann-S

**Comment by XhmikosR** [comment]
I left js/dist.index.js for the time being, although it does seem unused. We should revisit later if we need it and remove it if not.

**Comment by mdo** [comment]
> I left js/dist.index.js for the time being, although it does seem unused. We should revisit later if we need it and remove it if not.

I see this is covered in #31823, so maybe we slate for v4.6.0? Do we need to warn folks at all?

**Review by mdo — APPROVED** [review]

**Comment by XhmikosR** [comment]
> I see this is covered in #31823, so maybe we slate for v4.6.0? Do we need to warn folks at all?

I intentionally kept index.js in v4-dev, since I can't be 100% sure if this will break something. But the sourcemap was outdated and moot for sure, hence why I decided to remove only that here :)

**Pull request merged**
