### PR TITLE
Explicitly document existing de facto policy of supporting ESR Firefox

### PR DESCRIPTION
**Pull request by cvrebert**
Refs #17237.
CC: @twbs/team for discussion

### CODE REVIEW

**Comment by kkirsche** [comment]
Not a team member, but I think this makes sense. Stating this explicitly should help limit the number of issues which are created that reference antiquated versions of Firefox or, will give us something which can be quickly and easily referenced when new issues arise as to why they won't be or shouldn't be addressed.

**Comment by cvrebert** [comment]
@kkirsche Actually this loosens the existing written policy, which is "latest version only, except for IE".

**Comment by kkirsche** [comment]
Sorry I misunderstood that. I was basing mine mostly off your comment in the other thread. So that's my fault. Thanks for pointing that out!

**Comment by XhmikosR** [comment]
Looks good to me.

**Comment by hnrch02** [comment]
LGTM. This reminds me of #14981, this hasn't been changed in v4 (yet).

**Comment by cvrebert** [comment]
<3

**Pull request merged**
