### PR TITLE
Optimizes bootstrap dropdown

### PR DESCRIPTION
**Pull request by digitaltsai**
My use case is that I have a page with thousands of elements on the page and using a performance profile, I determined this was a bottleneck for my performance.

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 239cb25f80d8a929d70684fabb1a4f67da17b93e
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/113566995

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by digitaltsai** [comment]
I checked the build logs for the failure, and it looks like windows 7 IE8 is failing. After looking at the screenshot though, it seems like it's failing for other things not related to the dropdown.

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: b2abe81cfc41f905f823eb11fc71d117659f6f47
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/113570151

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by deviprsd21** [comment]
@digitaltsai Function/Method calls are always expensive performance wise, `$.each` and `forEach` use function calls, if the array is **small** there won't be any much difference in performance but if it is **large, function calls will slow it down**. As generally suggested, it is better to use `for` loop for simple arrays, and is considered a good choice.

**Comment by digitaltsai** [comment]
@deviprsd21 Thanks for the suggestion. I've changed it to use `for` loops instead of `$.each` now.

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 59590f13a00d48976097d33257cfa5c8343c88a4
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/119378139

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Pull request closed without merging**
