### PR TITLE
Cancel event when collapse is in transition

### PR DESCRIPTION
**Pull request by au-phiware**
As discussed in issue #15932

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: a65644a46bc55a653995f93ad5e0f02219bbc100
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/52241343

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by kkirsche** [comment]
I believe this will need to be refactored or the tests will need to be refactored before this could go into review to be merged. :smiley: Let us know though if you have questions about how to run the tests locally, etc. :+1:

**Comment by cvrebert** [comment]
@au-phiware This seems to be breaking the test suite: https://travis-ci.org/twbs/bootstrap/builds/52241437

**Comment by au-phiware** [comment]
Yes, my apologies, the event object is not always available so there just needs to be a null check around calling preventDefault.

I am running the fixed code in my organisation but haven't found the time to update this pull request ...I shall endeavor to *make* the time tomorrow.

Cheers

**Comment by au-phiware** [comment]
@cvrebert sorry, it took me so long to get around to fixing this.

**Comment by cvrebert** [comment]
Could you post an example demonstrating the usage of this fix?

**Comment by cvrebert** [comment]
@twbs-savage Retry

**Comment by au-phiware** [comment]
Certainly @cvrebert, here's and example of a before and after:

Before, double clicking the button causes the state of button/checkbox to be out of sync with the collapse: http://jsfiddle.net/kjm1k8Lb/3/

After, the collapse is only expanded when the button is active (or when the checkbox is checked): http://jsfiddle.net/kjm1k8Lb/4/

**Comment by twbs-lmvtfy** [comment]
Hi @au-phiware!

You appear to have posted a live example (http://fiddle.jshell.net/kjm1k8Lb/3/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 39, column 135: Bad value ```` button ```` for attribute ```` role ```` on element ```` label ````.
* line 44, column 66: Element ```` div ```` is missing one or more of the following attributes: ```` role ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @au-phiware!

You appear to have posted a live example (http://fiddle.jshell.net/kjm1k8Lb/4/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 434, column 135: Bad value ```` button ```` for attribute ```` role ```` on element ```` label ````.
* line 439, column 66: Element ```` div ```` is missing one or more of the following attributes: ```` role ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
(Sidenote: My reading of [the spec](https://html.spec.whatwg.org/multipage/dom.html#wai-aria) seems to confirm that `<label role="button">` is indeed invalid. FYI @patrickhlauke.)

**Comment by fat** [comment]
nah i dont want to get into the business of messing with people events. stopping propagation in particular can have lots of unexpected sideeffects for peoples programs.

I think there are better workaround then this. 

Thanks for the pr though :+1:

**Comment by au-phiware** [comment]
I can appreciate your point of view, I will continue to work with my fork on my project. Mainly because this is two bootstrap components that are interacting badly with each other. And the workaround that I tried felt extremely clumsy... I would be interested in your solution :)

**Pull request closed without merging**
