### PR TITLE
Update normalizeDataKey to match the spec

### PR DESCRIPTION
**Pull request by MisatoTremor**
See https://html.spec.whatwg.org/multipage/dom.html#dom-dataset

### CODE REVIEW

**Comment by XhmikosR** [comment]
This is not right, because currently we add the hyphen after we call this.

**Comment by MisatoTremor** [comment]
Afaik this does not happen.
The `Manipulator` functions use `normalizeDataKey` as is and would result in wrong attribute names if ever called with key names as coming from a DOMStringMap (`dataset`).
I know that internal calls to these functions already use camel-case, but that would make this function obsolete at best.
My thought was that this function exists as a safe guard to ensure valid attribute names (as the Manipulator could be used by plugin authors etc.) and should at least function as such.

**Comment by XhmikosR** [comment]
https://github.com/twbs/bootstrap/blob/639c405c6510a286a3cfcfd6d733d28d0e7baf92/js/src/dom/manipulator.js#L34

**Comment by XhmikosR** [comment]
You will need to adapt tests then.

**Review by Johann-S — APPROVED** [review]
Nice catch @MisatoTremor 👍 
LGTM 👍

**Comment by XhmikosR** [comment]
Thanks!

**Pull request merged**
