### PR TITLE
Add HTMLHint to the build

### LINKED ISSUE #20297: Add HTMLHint to the build
https://github.com/yaniswang/HTMLHint

Refs #20295.

### PR DESCRIPTION
**Pull request by cvrebert**
Fixes #20297.
CC: @XhmikosR @hnrch02

### CODE REVIEW

**Comment by XhmikosR** [comment]
What happened to grunt-html? Unless there's a good reason, I'm not in favor of this. grunt-html is kept up to date with the latest vnu.jar markup.

**Comment by cvrebert** [comment]
This is in addition to grunt-html, not as a replacement.

**Comment by XhmikosR** [comment]
Oh, OK. In that case I guess it's OK.

Is the config you used strict enough?

**Comment by hnrch02** [comment]
👍

**Comment by cvrebert** [comment]
> Is the config you used strict enough?

Strict enough for what?

I enabled every available rule that looked appropriate for us.

**Comment by XhmikosR** [comment]
OK if you think it's what we need. I didn't go through all options myself
that's why I asked.

**Comment by tomlutzenberger** [comment]
@cvrebert Did you notice any changes/improvements since you added HTMLHint?

**Comment by cvrebert** [comment]
No, since we already complied with it after your PR.

**Pull request merged**
