### PR TITLE
changed order of  _variables.scss and _custom.scss call in bootstrap.scss

### PR DESCRIPTION
**Pull request by sergej2705**
because `_custom.scss` can refer to variables from `_variables.scss`, but a error will be thrown if `custom` is called before `variables`

### CODE REVIEW

**Comment by mdo** [comment]
The purpose of that file isn't for custom CSS exactly, but for variable overrides without modifying the source files. I think I need to change the name for clarity, but see the comment at the top of the custom file:

```
// Copy variables from `_variables.scss` to this file to override default values
// without modifying source files.
```

**Comment by sergej2705** [comment]
You didn't get my point... I will clarify it.

In `_variables.scss` there is following declaration:
```scss
$spacer:   1rem !default;
// ...
$headings-margin-bottom: ($spacer / 2) !default;
```

If I want to customise `$headings-margin-bottom` I will add it to `_custom.scss`. It may look like:
```scss
$headings-margin-bottom: $spacer;
```
right so far?

Compiling `bootstrap.scss` now throws the Error

    `Undefined variable: "$spacer".	$headings-margin-bottom: $spacer;`

that's why the `_variables.scss` should be included before `_custom.scss`.

**Comment by cvrebert** [comment]
But if, say, you wanted to customize `$spacer`, then if `_variables` was included before `_custom`, wouldn't `$headings-margin-bottom` get calculated using the old default `$spacer` value?

**Comment by sergej2705** [comment]
Indeed `$headings-margin-bottom` would be calculated with the "old" value of `$spacer`, but there should be a solution where both problems should be considered.

**Pull request closed without merging**
