### PR TITLE
Check if Dependabot changed /dist folder

### LINKED ISSUE #37479: Add a CI action on every Dependabot branch, checking for dist files references
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

After https://github.com/twbs/bootstrap/pull/37463  (and probably some more), it would be handy having an automation, and run a check on every Dependabot branch for dist files differences, minimizing the possibility of future conflicts and mistakes

### Motivation and context

Save some reviewing time & minimize the potential of slipped mistakes

### PR DESCRIPTION
**Pull request by jynsy**
### Description

My change will check if Dependabot updated /dist folder. If it did, then the workflow job will fail. If it didn't, then no workflow job regarding this will appear whatsoever.

### Motivation & Context

Conflict appeared because Dependabot changed the /dist folder.

### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [ ] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### Related issues

Closes #37479

### CODE REVIEW

**Comment by julien-deramond** [comment]
Thank you for this PR @erikasby.

I think this is not what's expected in the issue.
This PR generates an error if a Dependabot branch modifies dist files.

> and run a check on every Dependabot branch for dist files differences

However, if I understand the context correctly, the idea would rather be to run `npm run dist` for each branch generated by Dependabot, and to compare the generated dist files to the one in the main branch. We expect no modification.

**Comment by erikasby** [comment]
Oh, okay, sorry. Just to make sure I understand it correctly.

As I understand you want me to just edit the bundlewatch.yml file and add additional step after `npm run dist` something like this just to show the differences of /dist folders for dependabot branches:
```yaml
- name: Dependabot /dist folder check
     if: ${{ github.actor == 'dependabot[bot]' }}
     run: git diff origin/main origin/${GITHUB_HEAD_REF} dist/
```

**Comment by julien-deramond** [comment]
It's not really related to the bundlewatch action even if the content would be almost the same to prepare the environment.
As a first step, I think you could make your modification in a separate isolated `.yml`. And we'll discuss later on with the rest of the core team (except if they have some inputs right now) if we try to merge your `.yml` with one of the other `.yml`s to maybe save some resources (not run `npm run dist` 2 times).

On my side, I was thinking of something like this:
1. Checkout PR branch
2. Set up Node.js
3. Install npm dependencies with `npm ci`
4. Run dist with `npm run dist`

_(so until this 4th step, it's, as you saw, basically the same thing as `bundlewatch.yml`)_

5. Compare `dist` content to _main_ branch dist content
   a. If the content is the same: job's green
   b. If the content is different: it's an error, and if possible the diff is displayed in the console in the corresponding action so we don't have to run it locally
   
What do you think?

**Comment by XhmikosR** [comment]
I don't see the point in this change? It's unrelated to what the linked issue describes. Also, do note that this can become very noisy. Unsure if we really want it.

**Pull request closed without merging**
