### PR TITLE
added disabled state for custom form elements

### PR DESCRIPTION
**Pull request by janhocevar**

### CODE REVIEW

**Comment by patrickhlauke** [comment]
Pro-tip: you can update a PR by pushing changes to it, without the need to open/close lots of separate ones...

Also, it would be nice to have a bit of a description of what your PR is about (e.g. a use case that's currently not sufficiently addressed by Bootstrap, and perhaps even a quick demo of what your proposed patch adds).

/cc @mdo

**Comment by janhocevar** [comment]
the title kinda says what this PR does. custom form elements (checkbox and radio button) have grayish background, so this is replaced by default white background, and if input is disabled, grey background colour is added with not-allowed cursor along with it.

**Comment by mdo** [comment]
I swear I had disabled states in this already... will have to double check on that before I merge here. Swear I wrote something somewhere :).

**Comment by mdo** [comment]
Also #17921.

**Comment by mdo** [comment]
Fix coming in #18771. Thanks though!

**Pull request closed without merging**
