### PR TITLE
all thumbnails as been fixed

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by Johann-S — CHANGES_REQUESTED** [review]
Can you reduce the image size please ? 
Currently we have : width: `800px` and height: `600px`

And with your PR we'll have : width: `1366px` and height: `768px`

**Comment by aicoutos** [comment]
@Johann-S  all thumbnails fixed at 800x600 https://github.com/twbs/bootstrap/pull/23049/commits/67fd83c005692d25cd73689de6559b988d75d2e3

**Review by Johann-S — APPROVED** [review]

**Review by skmedix — CHANGES_REQUESTED** [review]
Some of your thumbnails have scrolls. It's a detail, but still.

**Comment by aicoutos** [comment]
@skmedix all thumbnails without scroll https://github.com/twbs/bootstrap/pull/23049/commits/7042c4eaf131714b0903c53884997ee877bd0708

**Comment by mdo** [comment]
I'll redo all these with the latest from v4-dev on a Mac for the better font rendering. Thanks though!

**Pull request closed without merging**
