### PR TITLE
fix: remove overflow:hidden from progressbar (issue: 37821)

### LINKED ISSUE #37821: Progress bar text doesnt handle the 0% case
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

If you create a progress bar where the progress is not very far (ie 0%) the inner descriptive text will not be displayed. 
```
<div class="progress">
  <div class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">I want to be seen!</div>
</div>
```
This *has* come up before. Most recently(?) it was https://github.com/twbs/bootstrap/issues/24538 (fixed for 4.0 release).

As shown below with the test cases the issue where text will not display appears to have been introduced via 4.4.0.

### Reduced test cases

This issue can be seen in (uses bootstrap 5.2.3)
https://jsfiddle.net/apw74tx9/2/

I did some looking at older versions of bootstrap and this appears to have been working in 4.3.1
https://jsfiddle.net/3c6uL5hj/

But not the 4.4.0 release
https://jsfiddle.net/6pfuokv7/1/

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.3

### PR DESCRIPTION
**Pull request by alenap93**
### Description

This PR reverts changes made with https://github.com/twbs/bootstrap/pull/29629 for IE (with v5 we dropped the support). If percentage of progressbar is low (ie: 0%), the progressbar do not show labels (or cut it), therefore i have removed the overflow:hidden.

### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### Related issues

Closes https://github.com/twbs/bootstrap/issues/37821

### CODE REVIEW

**Comment by patrickhlauke** [comment]
not quite sure about this. without the overflow rule, even in chrome etc, the text ends up being there (contrary to what https://github.com/twbs/bootstrap/issues/29622 says ... it just happens that the 0% bar was getting overlapped/covered by the following progress bars)

so, without overflow, you end up with this sort of thing (on a single progress bar)

screenshot showing a 0% progress bar from the docs, with the "0%" text showing very faintly in white over light gray of the empty progress bar track

not sure if that's of any use to anybody without additional work on making the label text visible?

**Comment by patrickhlauke** [comment]
wondering what the actual use case is you're trying to support by removing the `overflow:hidden` ... or if it's just intended as a "we probably don't need this CSS rule, so can remove it"?

**Comment by alenap93** [comment]
@patrickhlauke I know that with this configuration we violate some laws of accessibility contrast, but the intent is to remove the overflow and delegate the right color to the developer based on the use case...

**Comment by patrickhlauke** [comment]
but my point is: if we delegate making it look/work properly to developers anyway (for them to set a proper text color to make it actually usable by anybody), we can also delegate to developers that they remove the `overflow:hidden`, no?

**Comment by julien-deramond** [comment]
Instead of modifying the default behavior, we could add something into the "Labels" section in the documentation to explain that by default it's like this and that the behavior can be overriden by the end-user if needed without breaking accessibility (depending on the use case)

**Comment by patrickhlauke** [comment]
also, to be clear: i'm not coming at this necessarily from an accessibility point of view, but just a general "this looks objectively broken otherwise" point of view

**Comment by alenap93** [comment]
Just for completeness, the actual behaviour with 1% (the % is cut off):

screen

**Comment by mdo** [comment]
It's also important to note we have to test against two versions of the progress bar, since we implemented a new one in v5.3.0. Just calling out so we confirm both situations.

**Comment by patrickhlauke** [comment]
> two versions of the progress bar

the only difference structurally comes for the multiple progress bars, which now use a tweaked overall container, but this won't affect the presentation of the label inside each progress bar itself.

**Comment by patrickhlauke** [comment]
I would suggest this alternative: keep the default as is, but document how authors that do explicitly want to opt into the "text overflows the progress bar" can achieve it https://github.com/twbs/bootstrap/pull/37921

**Comment by mdo** [comment]
Closing for suggested PR.

**Pull request closed without merging**
