### PR TITLE
Collapse animate option

### PR DESCRIPTION
**Pull request by wnr**
See #18127.

Open questions:
- If a collapsable element of an accordion has animations disabled, should the others also ignore animations when the elements is shown/hidden? See the visual tests for collapse.
- Should the element still emit all events if it is not animated? Such as show/hide.

### CODE REVIEW

**Comment by cvrebert** [comment]
> Should the element still emit all events if it is not animated? Such as show/hide.

Yes, since that's how our other widgets work when transitions are disabled globally.

**Comment by wnr** [comment]
> Yes, since that's how our other widgets work when transitions are disabled globally.

Okay, then I made the right guess :)

**Comment by wnr** [comment]
Any update?

**Comment by cvrebert** [comment]
@wnr Do you happen to be familiar with `git rebase`?

**Comment by wnr** [comment]
Yes, do you want me to squash?

**Comment by cvrebert** [comment]
Yes, and please also remove the `dist/` file changes.

**Comment by wnr** [comment]
I have now removed the `dist/` changes and squashed the commits. The build seems to be failing due to not being able to download ruby correctly.

**Comment by cvrebert** [comment]
Yes, we're aware: https://github.com/travis-ci/travis-ci/issues/5092

**Comment by cvrebert** [comment]
CC: @fat for review

**Comment by wnr** [comment]
Any progress?

**Comment by davidknezic** [comment]
Any chance this will be merged into v4? There has been no activity for almost a year now.

**Comment by vanduynslagerp** [comment]
FYI, if and when merged, #21589 would bring a solution to this issue by allowing to set the transition directly in CSS (via the variable `$transition-collapse` or a custom class)
For example setting `$transition-collapse: none` would have the effect of having no transition. The `transitionEnd` would be still triggered so show/hide would still work as expected.

By creating custom classes it would also be possible to set a different transition duration on different element.
For example:
`.no-transition {
    transition: none !important;
}
.fast-transition {
    @include transition(height .15s ease);
}`
This way you can have a collapsible area without transition and another one with a 150ms transition.

**Pull request closed without merging**
