### PR TITLE
[FIX] Docs site was not loading theme images because of URL path used.

### PR DESCRIPTION
**Pull request by bitsapien**
This PR relates to issue #23928

### CODE REVIEW

**Comment by XhmikosR** [comment]
Did you try the latest master? `baseurl` is defined there.

**Comment by bitsapien** [comment]
@XhmikosR Yes I'm using `master`. 

`baseurl` is set correctly to `""`. But, our assets for docs do not live at `getbootstrap.com/`, instead they live at `getbootstrap.com/docs/3.3/`. Which is why having a `site.baseurl` does not make sense there.

**Comment by XhmikosR** [comment]
@bitsapien: do we have any other cases like this? It's been a long time since I actually worked on v3 and its docs so I'm not sure.

**Comment by bitsapien** [comment]
@XhmikosR The footer links for `Examples` and `About` also throw a `404` on the same page. Will push the changes in a moment.

**Comment by mdo** [comment]
Works on my machine 😜. (jk i fixed it)

**Pull request closed without merging**
