### PR TITLE
Better handling of remote content with transitions

### PR DESCRIPTION
**Pull request by joshreed**
Currently, remote content, unless loaded really quickly, or already cached in-browser, will not always show the (CSS) transitions, which is a nuisance.

This change makes it so that the "in" class is not added to the modal until loaded even is triggered (if applicable). This seems to work well, though if there are suggestions on a better/preferred alternative implementation, I'm certainly flexible.

Additionally, I did not add any Unit tests, because I didn't see any examples of how you would be handling remote/ajax requests in your tests? This change will only be applicable in situations where the "remote" option is set. I am assuming the best way would be to "mock" the request; if you have any suggestions, I would be happy to add test cases. All existing tests still passed when I ran the suite.

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 1b52b3b318c1194d80d87fcc27f61acd874d9bf3
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/91480067

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by joshreed** [comment]
Is there any way that I can solve the @twbs-savage issue where it times out after trying to connect for 10 minutes? Is that an issue with the code or with the continuous integration process? To me it seems like the latter.

**Comment by joshreed** [comment]
Added an "Issue" for this PR: https://github.com/twbs/bootstrap/issues/18275

**Comment by cvrebert** [comment]
You can ignore @twbs-savage for now; the bot is having some problem communicating with Travis. We need to look into it.

Closing this per https://github.com/twbs/bootstrap/issues/18275#issuecomment-157228086

**Pull request closed without merging**
