### PR TITLE
docs: Add `role="switch"` to switches

### LINKED ISSUE #34818: Add role="switch" to switches in example code?
I’ve just been reading this good article by @argyleink about building a switch component
https://web.dev/building-a-switch-component/#overview

I see it uses `role=switch`. Think this should be added to the Switch Bootstrap docs example code?
https://getbootstrap.com/docs/5.1/forms/checks-radios/#switches

Let me know, I’d be happy to open a PR for it.

### PR DESCRIPTION
**Pull request by coliff**
Fixes: #34818

### CODE REVIEW

**Review by ffoodd — DISMISSED** [review]
Seems good to me, according to @patrickhlauke's recommandation 👌

Thanks!

**Comment by coliff** [comment]
The accessibility tests are failing with this error:

```
"file:/home/runner/work/bootstrap/bootstrap/_site/docs/5.1/forms/checks-radios/index.html":571.3-571.92: error: Element "input" is missing required attribute "aria-checked".
"file:/home/runner/work/bootstrap/bootstrap/_site/docs/5.1/forms/checks-radios/index.html":575.3-575.100: error: Element "input" is missing required attribute "aria-checked".
"file:/home/runner/work/bootstrap/bootstrap/_site/docs/5.1/forms/checks-radios/index.html":579.3-579.102: error: Element "input" is missing required attribute "aria-checked".
"file:/home/runner/work/bootstrap/bootstrap/_site/docs/5.1/forms/checks-radios/index.html":583.3-583.117: error: Element "input" is missing required attribute "aria-checked".
```

So it's suggesting we add `aria-checked="false"` to switches which are off and `aria-checked="true"` to switches are which are on. So this would have to be done with JavaScript. As such I think this PR can't be merged as it is.

**Comment by patrickhlauke** [comment]
yes this seems to be a shortcoming of the validator, as you don't need `aria-checked` for native `<input type="checkbox">`

https://www.w3.org/TR/html-aria/#docconformance

> Authors SHOULD NOT use the aria-checked attribute on input type=checkbox elements.
>
> [...]
>
> Note: The HTML checked attribute can be used instead of the aria-checked attribute for menuitemcheckbox, option or switch roles when used on type=checkbox.

**Comment by XhmikosR** [comment]
Patrick, could you please chime in the upstream issue? Maybe it's just an
issue with the validator and not the specs

**Comment by patrickhlauke** [comment]
yeah, i did after posting the comment here https://github.com/validator/validator/issues/1221#issuecomment-910024715

**Comment by XhmikosR** [comment]
This is weird, now we no longer get the errors but the issue wasn't fixed upstream :S

No idea what's happening...

**Review by patrickhlauke — APPROVED** [review]

**Comment by XhmikosR** [comment]
BTW I'll temporarily downgrade vnu in this branch to see if the errors show
up again. Then I'll revert and merge.

**Pull request merged**
