### PR TITLE
Complete the tabindex="-1" attribute in the JavaScript behavior example

### PR DESCRIPTION
**Pull request by ZhangChengLin**
### Description
Complete some attributes required in the example js. If non-essential items do not need to appear in the example, some attributes in the relevant examples should be deleted to express more concisely.

### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [x] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

- <https://deploy-preview-38620--twbs-bootstrap.netlify.app/docs/5.3/components/navs-tabs/#javascript-behavior>
- <https://deploy-preview-38620--twbs-bootstrap.netlify.app/docs/5.3/components/navs-tabs/#using-data-attributes>

### CODE REVIEW

**Comment by ZhangChengLin** [comment]
class="tab-content" in child elements of
 tabindex="0"


No processing is done in the js code, so there is no need to change the value of 0.

**Comment by ffoodd** [comment]
There's no need for `tabindex` on `button`: you description mentions attribute deletion but you only add some.

Closing this as it seems inacurrate.

**Comment by mdo** [comment]
@patrickhlauke Didn't we remove all these negative tabindex values awhile back?

**Comment by patrickhlauke** [comment]
`tabindex="-1"` is added dynamically by JS on initialisation, so all those manual additions are unnecessary. as it already says in the documentation:

> When the JavaScript plugin is initialized, it will set tabindex="-1" on all inactive tab controls.

**Comment by Mattnificent** [comment]
The tabindex=-1 is making the bs nav tabs less accessible.  The user should be able to tab to the... tabs.  But the user cannot, as tabindex=-1.

**Comment by patrickhlauke** [comment]
@Mattnificent per the recommended ARIA pattern, no...a tabbed interface only has a single tab stop, the currently active tab. User then changes tabs with cursor keys. as documented.

**Pull request closed without merging**
