### PR TITLE
Fixed affixes with offset-bottom when html,body{ height:100% }

### PR DESCRIPTION
**Pull request by seven7seven**
When using html,body { height: 100%; }, the affix plugin got confused of the document's height. 

This resulted in flickering of the affix back and forth, incorrect classes and basically just a very sad affix.

See:
- https://github.com/twbs/bootstrap/issues/7414 
- http://stackoverflow.com/questions/18379800/boostrap-3-affix-plugin-stops-working-when-body-100

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 472e4453d83fc0935a5a2fa6736992b176e8762d
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/61432256

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
@seven7seven JavaScript code changes must include a unit test (or visual test, if a unit test is impossible) for the bug that they fix. See https://github.com/twbs/bootstrap/tree/master/js/tests for more info.

**Comment by cvrebert** [comment]
Also, please don't include `/dist/` or `/docs/` files in the pull request; they cause spurious merge conflicts.

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Pull request closed without merging**
