### PR TITLE
navbar-default like thumbnail at https://v4-alpha.getbootstrap.com/ex…

### PR DESCRIPTION
**Pull request by ghost**
…amples/screenshots/sticky-footer-navbar.jpg

### CODE REVIEW

**Comment by gijsbotje** [comment]
i noticed that all of the thumbnails have gray navbars, but all the examples have `.navbar-dark` and some `.navbar-light`, not `.navbar-default`
I think it would be a better idea to update the thumbnails and leave the code as is

**Comment by aicoutos** [comment]
all thumbnails as been fixed https://github.com/twbs/bootstrap/pull/23049

**Comment by Johann-S** [comment]
So should I close this PR ?

**Comment by gijsbotje** [comment]
i guess when that pr is merged this pr is irrelevant

**Comment by mdo** [comment]
It's `-light` and `-dark`. I'll update the screenshots before we ship.

**Pull request closed without merging**
