### PR TITLE
Support multiple carousel indicators

### PR DESCRIPTION
**Pull request by bentrm**
This allows to add multiple `carousel-indicators` to `carousel` containers. 

It's a nice feature as it allows to add indicators to each of the slides caption riding with the carousel without worrying about where to put `.active` with each slide (effectively making it easier to work with templating engines).

It's also helpful if you would like to put multiple indicators into the carousel itself. One may use it to have an indicator at the top and bottom of a full page carousel, for example.

### CODE REVIEW

**Comment by Johann-S** [comment]
Maybe you should share with us a live example of your feature ? 😃

**Comment by bentrm** [comment]
banner

@Johann-S, of course! I used it to place the indicator on each slides caption which itself is displaced from the center.

**Comment by Johann-S** [comment]
Sure that's fine 👍

**Comment by Johann-S** [comment]
any advice on this feature @mdo ? or @XhmikosR ?
It seems pretty usefull and a nice to have for me

**Comment by XhmikosR** [comment]
If it doesn't break the existent behavior, I don't see why not to add it 👍

**Comment by XhmikosR** [comment]
@Johann-S: do we want this? If so we should rebase it.

**Comment by XhmikosR** [comment]
@Johann-S: I rebased this but it seems unit tests are failing.

**Comment by Johann-S** [comment]
yep, maybe @bentrm can fix that conflict ?

**Comment by XhmikosR** [comment]
Closing due to lack of response. You can comment here and we can re-open the PR, if you decide to resume working on the requested changes.

*This is an automated reply*

**Pull request closed without merging**
