### PR TITLE
Deprecate size mixin

### PR DESCRIPTION
**Pull request by MartijnCuppens**
I guess someone who uses mixins will also know the `width` and `height` properties 😃

### CODE REVIEW

**Comment by jackmu95** [comment]
@MartijnCuppens It sill has the benefit to only provide one "size" (e.g. `@inlcude size(500px);` to get:

```css
width: 500px;
height: 500px;
```

**Comment by jackmu95** [comment]
@MartijnCuppens Valid point.

**Comment by MartijnCuppens** [comment]
Ping @mdo

**Review by ysds — APPROVED** [review]
If I'm allowed to review on behalf of @mdo,  I will gladly approve these changes.

**Review by mdo — APPROVED** [review]

**Pull request merged**
