### PR TITLE
Replace the deprecated `color-adjust` with `print-color-adjust`

### LINKED ISSUE #36259: autoprefixer: Replace color-adjust to print-color-adjust.
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.

_form_check.scss, line 28

color-adjust: exact; // Keep themed appearance for print

has to be

print-color-adjust: exact; // Keep themed appearance for print

in the future i think. it is depreceated.

### Reduced test cases

no test link

### What operating system(s) are you seeing the problem on?

Windows, macOS, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.1.3

### PR DESCRIPTION
**Pull request by AdrianCurtin**
https://developer.mozilla.org/en-US/docs/Web/CSS/print-color-adjust

This fixes issues with autoprefixer ^10.4.6
(https://github.com/postcss/autoprefixer/releases/tag/10.4.6)
Which throw warnings for use of color-adjust CSS

Fixes #36259

### CODE REVIEW

**Comment by mdo** [comment]
There's no need to update the dist files, that happens on release. Can you revert those changes?

**Comment by AdrianCurtin** [comment]
@mdo done

**Comment by mbrodala** [comment]
By now this is a duplicate of #36258 so it can be closed IMO.

**Comment by mdo** [comment]
> By now this is a duplicate of #36258 so it can be closed IMO.
> 
> 
> 
> (Not sure if a PR for 4.x is necessary or if a backport is possible though.)

They're separate, so we'll leave both PRs.

**Comment by XhmikosR** [comment]
@mdo: I'm not sure we can apply this in v4 due to our supported browsers.

**Comment by AdrianCurtin** [comment]
@[XhmikosR](https://github.com/XhmikosR)
If this is the case and you want to leave it in, you should use an older version of autoprefixer, otherwise the warning will be treated as an error in production

**Comment by XhmikosR** [comment]
It's not an error, it's a warning. And we can't control the tools the consumers of the package use.

**Comment by AdrianCurtin** [comment]
@XhmikosR , I guess that its not specifically an error, but because its somewhat common to enable "treat warnings as errors" it does affect a lot of automatic deployments. It's true that you can't control what tools other users use, but you can control which tools that you use. So if you want to update the prefixer in v5, but not in v4, that's another way to get around these warnings.

https://caniuse.com/?search=print-color-adjust

Currently the only web browsers which *really* used only color-adjust appear to have been earlier builds of firefox for which 48-97, during which print-color-adjust enjoyed partial support. Other browsers do not support color-adjust or require the webkit prefix. 

So maintaining this to support old versions of firefox eschews support of that functionality in Edge, Chrome, Safari etc

**Review by XhmikosR — APPROVED** [review]

**Comment by jrochkind** [comment]
>  It's not an error, it's a warning. And we can't control the tools the consumers of the package use.

I am using bootstrap 4 via the ruby gem, which used to be a supported/recommended path to using bootstrap 4. The bootstrap 4 ruby gem has a dependency on `autoprefixer-rails`.  So autoprefixer is not a tool I chose to use, it's in fact one bootstrap did control. 

While my current setup doesn't cause any builds to fail, I now get this autoprefixer warning in all my build output. Which is a bit annoying. 

I don't think I have a way to remove autoprefixer from my app, as it's a bootstrap dependency; I guess I could lock to an older version that doesn't produce this warning. 

If anyone has any other ideas for eliminating this warning from my use of bootstrap 4 via ruby gem, I'd be interested in hearing them.

**Comment by kvnloughead** [comment]
I have the same issue as @jrochkind and would be glad for a way to suppress this warning

**Comment by rodrigo-arias** [comment]
@XhmikosR thanks for merging this fix, any plans to release a patch version for Bootstrap 4?

**Comment by XhmikosR** [comment]
Yeah, we will release a new version soon, maybe this week.

**Comment by Lmarquez1983** [comment]
I had the same problem. However, I tried to install bootstrap bootstrap@5.2.0-beta1, but then I had a problem with the localhost, which doesn't open the project even with not presenting errors in compiling. Now, I uninstalled bootstrap and tried to reinstall it, but still have the same autoprefixer error.

I tried also overriding autoprefixer, but still get the 6:29521 error. Does someone knows a way to get around it?

**Comment by ryanb** [comment]
@XhmikosR any update on when this will be released? Thanks for your work on it.

**Comment by rodrigo-arias** [comment]
This was also fixed in [Bootstrap v4.6.2](https://github.com/twbs/bootstrap/releases/tag/v4.6.2)

**Comment by julien-deramond** [comment]
@jrochkind IMO you can create an issue in https://github.com/twbs/bootstrap-rubygem

**Pull request merged**
