### PR TITLE
Resolve #26262: Add deprecated warning

### LINKED ISSUE #26262: Remove .text-hide mixin from documentation or mark as deprecated
Shouldn't be this page http://getbootstrap.com/docs/4.1/utilities/image-replacement/ removed or marked as deprecated? I think it could be confusing for new users.

### PR DESCRIPTION
**Pull request by Varunram**
I could modify the text if needed, dunno what other content should be in here apart from "This class is deprecated".

Fixes #26262.

### CODE REVIEW

**Comment by wolfy1339** [comment]
You will want to add a `@warn This component is deprecated and will be removed in a future version of bootstrap`

**Comment by XhmikosR** [comment]
@wolfy1339: it's already there. https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_text-hide.scss#L10

Although arguably we shouldn't show it like we do, see #26237 and #26242

**Comment by mdo** [comment]
@XhmikosR I think @wolfy1339 means the text should match in the docs to explain why/when/etc, which I agree with. @Varunram, can you make that copy edit to match the Sass deprecation warning?

**Comment by Varunram** [comment]
@mdo Done, thanks!

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
