### PR TITLE
accessibility - add aria-disabled on all disabled links

### PR DESCRIPTION
**Pull request by Lausselloic**
quick fix on documentation to add tabindex="-1" and aria-disabled="true" on visually disabled link

cc @patrickhlauke  for validation

### CODE REVIEW

**Review by XhmikosR — DISMISSED** [review]
Please rebase your branch and drop any unrelated patches.

**Comment by Lausselloic** [comment]
Yes sorry, haven't seen that my PR was corrupted. Think latest one was good

**Review by patrickhlauke — APPROVED** [review]
looks good to me. strangely, i could have sworn we did something like this already not so long ago?

**Comment by Lausselloic** [comment]
Yes we already did it : https://github.com/twbs/bootstrap/pull/28051

**Comment by XhmikosR** [comment]
@patrickhlauke: yeah for examples only it seems 8eb8b8d3da7cd852a489879752166e013fdd3ace

**Comment by patrickhlauke** [comment]
ah i see, this washes up stuff we missed previously. as you were :)

**Pull request merged**
