### PR TITLE
Introduce $tooltip-padding & $tooltip-padding-x vars

### PR DESCRIPTION
**Pull request by cvrebert**
In the name of not hardcoding particularly random pixel values.

### CODE REVIEW

**Comment by JulianNorton** [comment]
Why not EM instead of PX? That way it'd be proportional with the font size.

**Comment by cvrebert** [comment]
@JulianNorton Feel free to open a new issue about that. Right now I'm just introducing a variable for the existing value.

**Comment by cvrebert** [comment]
@mdo Any thoughts on the naming here?

**Comment by mdo** [comment]
Should we be more explicit in the variable name and go with `$tooltip-padding-y` for that `-3px` value?

**Comment by cvrebert** [comment]
@mdo `-3px` is used for padding in both horizontal and vertical directions in various cases; see the code.

**Comment by mdo** [comment]
Ah, sorry, I should've clarified.

Those `margin`s and `padding`s might use the same `3px` value, but they're not related to one another. The `margin-top: -3px` and what not is to distance the tooltip from the content it's initialized from—so they don't touch. This is mostly a problem with nav links, buttons, etc.—anything that has a solid background or border.

So, we can likely implement three variables here instead of just those two and give folks a bit more customization in the process. One for the offset, one for the vertical padding, and one for the horizontal padding. That make sense?

**Comment by cvrebert** [comment]
OK, will update this accordingly

**Comment by cvrebert** [comment]
@mdo LGTY now?

**Pull request merged**
