### PR TITLE
add "will-change" property

### PR DESCRIPTION
**Pull request by marcobiedermann**
Using `postion: fixed` on an element causes a lot of repaint on scrol. Adding `will-change: transform` will promote the element to it's own layer which improves the framerate.

[Article](https://aerotwist.com/blog/bye-bye-layer-hacks/) by @paullewis about `will-change`

### CODE REVIEW

**Comment by cvrebert** [comment]
This would probably be more appropriate for Bootstrap v4 (the `v4-dev` branch) than Bootstrap v3. I'm doubtful we'd want to take the potential stability risk, given that v3 is in maintenance mode.

Also, this sounds morally equivalent to the `translateZ` hack, which we tried before but had to revert due to browser bugs and due to new stacking contexts being unintuitive in some cases. See https://github.com/twbs/bootstrap/pull/13649

**Comment by cvrebert** [comment]
CC: @mdo

**Comment by marcobiedermann** [comment]
@cvrebert Yes, you are right. But this is the "right" way to promote an element to it's own layer. Adding `translateZ` is more of a hack

**Comment by cvrebert** [comment]
Closing for v3 due to aforementioned stability concerns.
You can try proposing this change for v4 though.

**Pull request closed without merging**
