### PR TITLE
Overlay fix after hide modal

### PR DESCRIPTION
**Pull request by jcalijurio**
Fix scroll after overlay two or more extensive modals.

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: e3af2e895396f97b384bb5d2fa3368ea69e76182
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/50526132

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
We don't support multiple open modals, which is what you seem to be referring to:

> ## [Overlapping modals not supported](http://getbootstrap.com/javascript/#modals)
> Be sure not to open a modal while another is still visible. Showing more than one modal at a time requires custom code.

**Comment by jcalijurio** [comment]
Whats is the impediment for the next version has support for overlapping?
Is a good feature for many developers.

Thanks.

**Comment by cvrebert** [comment]
It's thought that it would increase the complexity (especially of the JavaScript) too much. We already have enough trouble with current simple version as it is.
Also, some folks think nested modals make for bad UX.
X-Ref: #4182, #11872

**Pull request closed without merging**
