### PR TITLE
Use en-dash instead of hyphen in license between years

### PR DESCRIPTION
**Pull request by kkirsche**
English grammar states that an en-dash should be used, not a hyphen between two years.
## Examples of each

**em-dash**: —
**en-dash**: –
**hyphen**: -
## Em-dash

An em-dash is typically used as a stand-in for a comma or parenthesis to separate out phrases—or even just a word—in a sentence for various reasons (i.e. an appositive). Examples where an em-dash should be used:
- School is based on the three R’s—reading, writing, and ’rithmetic.
- Against all odds, Pete—the unluckiest man alive—won the lottery.
- I sense something; a presence I've not felt since—
## En-dash

An en-dash is used to connect values in a range or that are related. A good rule is to use it when you're expressing a "to" relationship. Examples where an en-dash should be used:
- in years 1939–1945
- pages 31–32 may be relevant
- New York beat Los Angeles 98–95
- When American English would use an em-dash – following British and Canadian conventions.
## Hyphen

A hyphen is used to join words in a compound construction, or separate syllables of a word, like during a line break, or (self-evidently) a hyphenated name.
- pro-American
- cruelty-free eggs
- em-dash
- it's pronounced hos-pi-tal-it-tee
- Olivia Newton-John

### CODE REVIEW

**Comment by kkirsche** [comment]
Build fails due to NPM:

```shell
Loading "cssmin.js" tasks...ERROR
>> Error: Cannot find module 'pako/lib/zlib/messages'
Loading "uglify.js" tasks...ERROR
>> Error: Cannot find module 'pako/lib/zlib/messages'
Warning: Task "cssmin:minifyCore" not found. Use --force to continue.
```

**Comment by juthilo** [comment]
Build fixed

**Comment by kkirsche** [comment]
Thanks @juthilo

**Comment by cvrebert** [comment]
Personally, I'd prefer to keep the file as plain ASCII text.

**Comment by kkirsche** [comment]
To my knowledge the en-dash is valid ASCII though I could be wrong. From ISO 8859-1:

DEC	OCT	HEX	BIN	Symbol	HTML Number	HTML Name	Description
150	226	96	10010110	–	&#150;	&ndash;	En dash

**Comment by cvrebert** [comment]
Take a gander at http://en.wikipedia.org/wiki/ASCII#ASCII_printable_code_chart
ASCII only has 0x2D, the [hyphen-minus](http://en.wikipedia.org/wiki/Hyphen-minus), as far as dashes go.

**Comment by kkirsche** [comment]
Ah ok. I was looking at http://www.ascii-code.com/ which shows it under extended ASCII code / ISO 8859-1.

Thanks for the additional info.

**Comment by kkirsche** [comment]
What are your thoughts of using the hyphen shortcuts (- for hyphen, -- for en-dash, and --- for em-dash) common in applications such as Microsoft Office? I can understand and respect the desire to keep it within the standard printable ASCII

**Comment by cvrebert** [comment]
Doesn't seem particularly worth it to me. But I don't know how the rest of the team feels obviously.

**Comment by mdo** [comment]
How important is the ASCII aspect of license files? Could we not rename it to LICENSE.md and do whatever we want?

**Comment by cvrebert** [comment]
It's tradition basically; ASCII plaintext is readable everywhere. Although I have seen exceptions when the author's name contains non-ASCII characters and they don't wish to transliterate their name.

> Could we not rename it to LICENSE.md and do whatever we want?

If we really want the nice dash, might as well just keep it as LICENSE and use UTF-8.
Is using the pedantically-correct dash worth the inevitable [mojibake](http://en.wikipedia.org/wiki/Mojibake) that will result in a few folks seeing e.g. "Copyright (c) 2011â€“2015 Twitter, Inc" though?

**Comment by mdo** [comment]
I'm fine leaving it as-is. Not a huge issue :).

**Comment by listrophy** [comment]
Just want to jump in and mention that the printable ASCII set doesn't even cover all of English, much less other languages (latin-based or otherwise). For example, "naïve" or "née" or "vis-à-vis."

Since neglecting accents does not render words unreadable—just semantically incorrect—saying "ASCII plaintext is readable everywhere" is accurate (almost) only for English text.

I'm not saying you change policy here... just want to inform in case something similar comes up another time.

**Comment by cvrebert** [comment]
That's a writability problem rather than a readability problem though.

**Comment by ssokolow** [comment]
@listrophy: Actually,  every English spell-checker I've ever used insists that the accented versions are invalid and suggests the accents be stripped.

(For French loanwords like "fiancé/fiancée" where both forms are still valid English, "English pronunciation intuition" seems to be in the process of phasing out the masculine form so the "ee" suffix can take the place of the "é" as a pronunciation guide.)

**Comment by StevenBlack** [comment]
@ssokolow just checking your hypothesis here on Mac OSX Yosemite.

Every English dictionary I have, and every spell checker I've tried in a number of text-friendly apps seem to refute the claim that "*Every...accented versions are invalid and suggests the accents be stripped.*"

Also my personal experience of decades reading both domestic and international publications, as well as the style guides I have at-hand, indicate that the phasing out of accented words in English is not, in fact, happening at all.

**Comment by ssokolow** [comment]
Thank you for the contrasting data points. I'll keep them in mind in the future.

However, to clarify, I was very careful to say that it was every spell-checker that I personally have used. The last Macintosh I ever used was a Mac SE running System 7 when I was a very young child and, at that age, I had no interest in writing.

The underlying point I'd intended to convey was that the un-accented forms are perfectly valid English (though, as you've now pointed out, not the preferred forms according to various style guides). 

Also, please take note that I'm speaking from a viewpoint that, given their rarity in day-to-day common usage (likely, due to a lack of easy ways to type combining diacritics when using Windows with a US ASCII layout), the accented forms will probably go away eventually because, based on the following evidence, common usage tends to drag formal usage along, kicking and screaming:
* Not even formal English uses the words ye, thou, thee, thy, or thine anymore.
* ...nor does it use "mine" in place of "my" before a word that begins with a vowel, despite still using "an" in place of "a" under the same conditions.
* The misuse of tragedy to mean something other than "a literary work in which the hero can't escape their downfall" is so widely accepted that it's not uncommon for an individual to be unaware of the original meaning.

(I don't like that "to whom" seems to be dying out in common speech, given that "to who" feels like "a apple", but I can see the rationale. It's extra complexity that appears to impart no additional expressiveness to the language relative to what is inferred from context... just like the distinction between "ye" and "you" or the "-th" conjugation for verbs used with a 3rd-person singular pronoun.)

**Comment by listrophy** [comment]
@ssokolow These reasons might be good enough for a Windows-using English speaker, but what about the billions of people in the world who are not? And to bring the conversation back to Bootstrap, what about the (tens of? hundreds of?) thousands of non-English speakers who use this project? Are they to be rendered second-class for the sake of convenience?

**Comment by ssokolow** [comment]
Irrelevant to my point.

1. You responded to a comment about keeping the license-related text, which is in English, in ASCII plaintext for maximum compatibility when feasible.
2. I referenced Windows because, last I checked, Windows had something like 95% of the market share in the English-speaking world... which makes its lack of support for combining diacritics a significant shaping force in how English words are spelled in day-to-day writing.

**Comment by patrickhlauke** [comment]
Ok folks, at the risk of sounding like a party pooper...let's get back on track here. This issue is about a minus/hyphen vs a dash. We're not here to discuss general character encoding, grammar, non-english languages being second class, or anything grander than: should that one hyphen be replaced.

**Pull request closed without merging**
