### PR TITLE
Allow create grid classes with half size

### PR DESCRIPTION
**Pull request by Hightrack**
In order to be more flexible while implementing a design, this pull request create optional classes for grid with half size.

For example:
push-sm-2-5 is a push with size 2,5 columns
col-sm-4-5 is a column with size 4-5 columns

It is optional and only will be created if the variable $enable-grid-classes-half-size is true.

This will allow to center elements using grid.

### CODE REVIEW

**Comment by cvrebert** [comment]
Approximate duplicate of #17524.

**Comment by tomlutzenberger** [comment]
@Hightrack If you double the columns from 12 to 24, you're more flexible and have the same effect.

**Comment by Hightrack** [comment]
No, because you must change your HTML source code if you were using another bootstrap template. Change $columns from 12 to 24 is not useful.

**Comment by tomlutzenberger** [comment]
Of course you have to change all your HTML.
But who would change something like this in mid-development?

**Pull request closed without merging**
