### PR TITLE
tabs - accessibility issue when using ul/li semantic

### LINKED ISSUE #30338: tabs - accessibility issue when using ul/li semantic
Hello,

I just face a small accessibility error on tabs with content when using ul/li semantic and `role="tablist"` as explain as default on documentation https://getbootstrap.com/docs/4.4/components/navs/#javascript-behavior

By setting `role="tablist"` onto the `ul` element, remove it's defaut html5 role `list` and so `li`'s children are now orphan (aXe and other accessibility tools are raising an error)

I've seen the great job about keyboard handler by @patrickhlauke on https://github.com/twbs/bootstrap/pull/28927 but nothing about that semantic warning

There's two options : 
1. Just replace `ul` and `li` by `div` element and keep the current 3 levels tablist->li->tab in documentation
2. Clearly simplify tabs usage and keep as simple as possible like the one with nav
```
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Home</a>
    <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Profile</a>
    <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Contact</a>
  </div>
</nav>
```

by the way at time developer can avoid that error by not using `ul/li`

Let me know if I could help by making a PR on V4 and or V5

### PR DESCRIPTION
**Pull request by Lausselloic**
fix #30338 add aria-role presentation on li element when ul element has role tablist and remove dropdown from visual tests as they've been removed from doc

### CODE REVIEW

**Comment by XhmikosR** [comment]
Why does this target v4-dev specifically? Isn't the issue present in master?

**Comment by Lausselloic** [comment]
I'll take a look on v5

**Comment by XhmikosR** [comment]
We generally target the master branch and then backport stuff in v4-dev. Not sure if the patch will apply clean going from master to v4-dev (probably not), so it should be OK for this specific case.

Generally we target master and cherry pick or apply manually what's needed for v4-dev.

**Comment by Lausselloic** [comment]
thanks for this info for other PR I will target the master

**Comment by ffoodd** [comment]
FYI related #30382 (for v5) is approved by @patrickhlauke :)

**Comment by ffoodd** [comment]
@XhmikosR It's been merged in v5, I guess it can be merged in v4 too :)

**Comment by XhmikosR** [comment]
Yeah, still waiting for @patrickhlauke approval, because this isn't a cherry pick.

**Review by patrickhlauke — APPROVED** [review]

**Pull request merged**
