### PR TITLE
Fix headers conflicting with `pre`

### LINKED ISSUE #23252: `::before` from headings overlap previous element
See the gif for a demonstration.

Opening the issue to track this.

A potential fix would be to reduce height and margin-top.

/CC @Johann-S

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Fixes #23252. This sets `pointer-events: none;` on the heading-elements and `pointer-events: auto;` on the direct child. All content in the heading-elements is wrapped in spans by jQuery.

### CODE REVIEW

**Comment by mdo** [comment]
Does #23244 not handle this well enough?

**Comment by XhmikosR** [comment]
@mdo you probably meant #23256, which does not fix the issue as I mentioned there.

As for this, @MartijnCuppens this has nothing to do with **M**icro**s**oft. Unless you mean something else with "ms".

Also, please skip the generated files.

Other than that this is the proper fix so 👍

**Review by XhmikosR — CHANGES_REQUESTED** [review]
After removing the generated files and rebasing skipping @mdo's patch completely, we can merge this

**Comment by mdo** [comment]
Cleaned up and superseded with #23259.

**Pull request closed without merging**
