### PR TITLE
docs: Add Russian translation

### PR DESCRIPTION
**Pull request by Hkr32**
Russian translation for Bootstrap 4

### CODE REVIEW

**Comment by XhmikosR** [comment]
@Hkr32 if you have disabled the option for maintainers to edit your PR, please enable it and not disable it again. I see no way of updating the branch right now.

**Comment by Hkr32** [comment]
@XhmikosR, where can I change this? Everything is default.

**Comment by XhmikosR** [comment]
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

image

There should be a button to update the branch here, but there isn't.

**Comment by Hkr32** [comment]
image

**Comment by XhmikosR** [comment]
Not sure why you don't have the option there. You should see something like this:

image

Anyway, some weirdness is happening, that's for sure.

**Comment by Hkr32** [comment]
image
image

**Comment by Hkr32** [comment]
image
Maybe you need to update the data?

**Comment by XhmikosR** [comment]
Like I said there's no button present.

Anyway, no big deal, but you should update your branch.

**Review by mdo — APPROVED** [review]

**Pull request merged**
