### PR TITLE
Update alignment __tables.scss

### PR DESCRIPTION
**Pull request by a21ns1g4ts**
This change align  the content of table row to vertical alignment
**Before**
before
**After:** 
after

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
`vertical-align: top` will be the desired behaviour in many cases, so I'm not eager to merge this.

Maybe we can change the value to a variable, like `$table-cell-vertical-align`, which can be changed?

**Comment by Atiladanvi** [comment]
Yes the alignment needs to be changed
I think the behavior of alignment of rows could be switchzes by a new class. [ .table-cell-bottom .table-cell-middle ... ]. What you think about this ?

**Comment by MartijnCuppens** [comment]
We already have align utilities which can be used (https://getbootstrap.com/docs/4.3/utilities/vertical-align/).

Maybe we should remove the alignment on `td,th` so we can use the utility classes on the tables? (see https://codepen.io/MartijnCuppens/pen/MMqbbg?editors=1100)

**Comment by Atiladanvi** [comment]
Good ! this solve the issue. You can request a Pr ?

**Comment by MartijnCuppens** [comment]
PR updated, demo see: https://deploy-preview-28990--twbs-bootstrap.netlify.com/docs/4.3/content/tables/#vertical-alignment

**Comment by XhmikosR** [comment]
@MartijnCuppens can you make a new PR with your patch?

**Comment by MartijnCuppens** [comment]
Done https://github.com/twbs/bootstrap/pull/29039

**Pull request closed without merging**
