### PR TITLE
Remove indiscriminate outline suppression for tabindex="-1" elements

### PR DESCRIPTION
**Pull request by patrickhlauke**
instead, only apply outline suppression if the browser wouldn't normally apply the focus outline, using the (currently experimental) `:focus-visible` pseudo-class

Closes https://github.com/twbs/bootstrap/issues/28425

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
This will add the focus ring back everywhere since this property is not yet supported (https://caniuse.com/#search=focus-visible). Don't know if that's an issue?

**Comment by patrickhlauke** [comment]
> This will add the focus ring back everywhere

everywhere there's a `tabindex="-1"` and the element is then focused programmatically - either because, say, it's an in-page anchor, or because it was invoked via `focus()` JS method. unless i missed anything, only our modal dialogs (which have an explicit `outline: 0` already) fall into the latter category.

**Comment by patrickhlauke** [comment]
but yes, the `:focus-visible` part is speculative/future-compatible (as per the comment in the scss)

**Review by MartijnCuppens — APPROVED** [review]
Aight, fine by me

**Pull request merged**
