### PR TITLE
Patch dropdown.js

### PR DESCRIPTION
**Pull request by GeoSot**
Refactor after #35973

### CODE REVIEW

**Review by mdo — APPROVED** [review]
Thank you!

**Comment by XhmikosR** [comment]
Please don't merge this yet @mdo

**Comment by mdo** [comment]
@XhmikosR Okay to merge now?

**Comment by GeoSot** [comment]
@louismaximepiton can you check it , too please?

**Review by louismaximepiton — COMMENTED** [review]
It looks good to me !

**Pull request merged**
