### PR TITLE
Alert dismissal change

### PR DESCRIPTION
**Pull request by EricWarnke**
Changed the alert dismissal from remove() to hide(). It's kind of wonky if one wants to show that alert again and it's completely missing from the DOM.

### CODE REVIEW

**Comment by fat** [comment]
there are a handful of better ways to handle to this problem.

If you don't want to use "hide" yourself, you should just store a reference to the alert - we don't kill that.

Here's a simple example: http://jsbin.com/sodunowuho/1/

**Comment by twbs-lmvtfy** [comment]
Hi @fat!

You appear to have posted a live example (http://jsbin.com/sodunowuho/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness
* line 11, column 3: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by fat** [comment]
good looking out twbs-bot

**Comment by navarr** [comment]
@fat While that works, it just doesn't make sense that bootstrap is removing an element from the DOM.  I'm impressed that this is being revisited three years later, but nobody has stated why removing the object from the dom is the preferable solution to hiding it.

I feel like most people (in fact, everyone prior that had commented on this issue) agree that hiding should be the default, with removing from dom available either through bootstrap options or dev intervention.

It's the difference between having to intercept default functionality and change it, and having to listen for default functionality and perform additional functionality.

**Comment by kkirsche** [comment]
Personally I don't mind the removal and never have. Rather than a default behavior change I'd rather just see a hide or remove option so it decides what to do based on what you tell it.

**Comment by mdo** [comment]
Few thoughts on it:

- Keeping alerts around dirties the DOM. Keep that stuff lean and clean whenever possible.
- Dismissable alerts are removed by users, so they've acknowledged (or ignored lol) the alert and want it gone. Theoretically, there's no more need for that alert.
- Removing the alert programmatically should likely happen after some kind of validation event. Have some form error states? Check on keystroke and remove it. No need for it after that either.
- Hiding means you're showing the same thing to users again. Something about that tells me you might want to revisit something that's prompting a user with the same exact alert.

That's coming from someone who's not writing much JS mind you, but look at it from a user experience and designer point of view.

**Comment by navarr** [comment]
@mdo An immediate thought is a warning or info level alert caused by JavaScript.  The user does something wrong, you show an alert.  They click the X, they do the same thing, and .. suddenly there's no alert to re-show.

It is not the CSS framework's job to keep the DOM clean.  Only to render it as the code says, is my opinion, personally.

**Comment by osuritz** [comment]
Yeah my similar use case was imagine a delete button for a record. That button is associated with a modal to confirm the deletion. Use dismisses (thus canceling the delete operation). Now if they click the same delete button, the same dialog should presented.

**Comment by patrickhlauke** [comment]
@navarr 

> It is not the CSS framework's job to keep the DOM clean

However, Bootstrap is more than just a CSS framework, as clearly the issue you're having here is how Bootstrap's JavaScript components behave.

**Pull request closed without merging**
