### PR TITLE
Add equal column mixin

### PR DESCRIPTION
**Pull request by cfxd**
~~Add equal column mixin so that we can do `@include make-col-eq` instead of having to extend the `.col` class or use it in markup.~~

Make the `make-col` mixin default to equal columns when not providing a column size.

### CODE REVIEW

**Comment by mdo** [comment]
I think I can dig this. Put together a little Codepen: https://codepen.io/emdeoh/pen/JjRbXYr.

Since this only changes the mixin, I don't see any problems for us. Wondering if we need to update any docs?

**Comment by cfxd** [comment]
Do you need me to make edits to that codepen? It looks like what I have in mind.

I can add a quick note for the docs with a note about the default behavior.

**Comment by mdo** [comment]
No codepen edits needed. Just some docs updates I think to mention the behavior. Not sure where myself just yet, so feel free to suggest!

**Comment by cfxd** [comment]
Ok, thank you! Added a docs edit and rebased 👍🏻

**Review by mdo — APPROVED** [review]

**Review by ffoodd — APPROVED** [review]
LGTM, pretty nice idea 👌

**Pull request merged**
