### PR TITLE
Update navbar-dark

### PR DESCRIPTION
**Pull request by shirohana**
I adding text-color to nav-link inside navbar-dark.
It's helpful for me to show social links in navbar (๑• ω •๑)

### CODE REVIEW

**Comment by XhmikosR** [comment]
1. Squash your patches
2. Make sure tests pass

**Comment by mdo** [comment]
Can you provide some screenshots of what this adds? Not so sure I want to add the variance to the utilities from the navbar scheme—those values should be immutable.

**Comment by Shirohana** [comment]
Oops, I dropped my repo (´・ω・｀)
I'll fork and pull request again.
This is my first time of pull request (>﹏<)

result like follows

**Comment by Shirohana** [comment]
New pull request!
https://github.com/twbs/bootstrap/pull/18078

**Comment by kkirsche** [comment]
No need to make duplicates @Shirohana — you can push to this branch in the future to update it.

That said, I'm not in favor of it for the use case described. This encourages users to not follow company brand guidelines:
* https://www.facebookbrand.com
* https://about.twitter.com/company/brand-assets
* https://developers.google.com/+/branding-guidelines?hl=en

**Comment by Shirohana** [comment]
I'm sorry that I caused distress :(
My English isn't good and I'm a newbie on Git.
I'll trying my best and complete the pull request :D

**Comment by Shirohana** [comment]
It seems I'm too disrespect of them....
I'm so sorry (╥﹏╥)

**Comment by XhmikosR** [comment]
https://github.com/twbs/bootstrap/pull/18078

**Pull request closed without merging**
