### PR TITLE
Update grunt-html

### PR DESCRIPTION
**Pull request by XhmikosR**
- [x] We'll probably need to tweak Travis to use OpenJDK 8 before this is merged
- [ ] And backport this to v3

/CC @cvrebert @patrickhlauke

### CODE REVIEW

**Comment by XhmikosR** [comment]
From a quick look, I had to switch to `java` for the travis project. I'm experimenting with other solutions but they seem to be slower.

If anyone has any ideas please let me know.

**Comment by cvrebert** [comment]
If only https://github.com/travis-ci/travis-ci/issues/4090 was implemented.. :disappointed:

**Comment by XhmikosR** [comment]
So, should I switch to `java` in the meantime? It also seems unlikely that Travis will update to OpenJDK 8 as the default for now so we either switch to `java` or require sudo and install it ourselves; the latter would be a lot slower, I suspect.

**Comment by cvrebert** [comment]
Yes, I agree. Guess we'll have to invoke `nvm` ourselves, which won't be too hard.

**Comment by XhmikosR** [comment]
All right, I'll get to it this evening.

**Comment by XhmikosR** [comment]
@cvrebert: Seems to fail in `nvm`. Any ideas?

**Comment by cvrebert** [comment]
@XhmikosR Try this matrix:
```yaml
matrix:
  - NODE_VERSION=5 TWBS_TEST=core
  - NODE_VERSION=4 TWBS_TEST=core
  - NODE_VERSION=5 TWBS_TEST=validate-html
  - NODE_VERSION=5 TWBS_TEST=sauce-js-unit
```

**Comment by XhmikosR** [comment]
Thanks @cvrebert, that seems to fix it the first build.

I thought I'd need a `&&` or something but apparently not.

Now, there are issues due to caching and the different node.js versions...

**Comment by cvrebert** [comment]
Looks like we'd need https://github.com/travis-ci/travis-ci/issues/4393

**Comment by cvrebert** [comment]
Looks like we may have to stick with `language: node_js` and accept the slowness of installing JDK8 ourselves.

**Comment by XhmikosR** [comment]
All right I'll give it a go later unless you beat me to it. In that case
just commit on this branch.

**Comment by XhmikosR** [comment]
@cvrebert: this doesn't seem to work either yet :/ Maybe I'm missing something...

**Comment by cvrebert** [comment]
Seems to be working, but OpenJDK would probably be simpler and faster to install than Oracle Java.

**Comment by XhmikosR** [comment]
@cvrebert: so we only need `openjdk-8-jre`?

**Comment by XhmikosR** [comment]
@cvrebert: I tried `openjdk-8-jre` but doesn't seem to work.

**Comment by XhmikosR** [comment]
@cvrebert: can you check again now? It seems using the Trusty image works fine.

**Comment by cvrebert** [comment]
LGTM

**Comment by XhmikosR** [comment]
All right, I'll clean up the branch and merge. Can you backport it to v3?

**Comment by cvrebert** [comment]
Ok.

**Pull request merged**
