### PR TITLE
Escape selectors to support HTML5 ID spec 

### PR DESCRIPTION
**Pull request by Hiws**
This is a *rough* draft, of a possible simple solution to support HTML5 ID's in combination with the various JS plugins.

This allows the user to use non-alpha characters as the first character in the ID, which is currently not possible.

Basic example of what will be possible:
```html
<a class="nav-link" data-toggle="tab" href="#1-tab">Tab 1</a>

<div class="tab-pane fade" id="1-tab">
  Content
</div>
```

I've tested `Modals`, `Tabs`, `Scrollspy`, `Carousel` and `Collapse` locally via the docs, and it appears to function correctly, but will definitely need more testing to ensure it works across supported browsers and environments.
My knowledge of all the ways the plugins above can be used is limited, which is why I'd love some input whether the current draft makes sense.

The selector is escaped using the built-in `CSS.escape`, function. However, I don't *think* this is supported in Legacy Edge. So a different solution might be needed here.

Alternatives to native `CSS.escape`:

- https://github.com/mathiasbynens/cssesc - Standalone function (with more features?)
- https://github.com/mathiasbynens/CSS.escape - A direct polyfill
- Write a standalone function specific to Bootstrap

### CODE REVIEW

**Comment by Johann-S** [comment]
simple curiosity, do you know if it would work with selector containing several ID, something like: `#test, #test2` ?

**Comment by Hiws** [comment]
@Johann-S 
Are you asking whether `CSS.escape('#test, #test2')` would work?
If so, then not to my knowledge. Unless you striped out `test` and `test2` (without the `#`) and escaped them separately and placing it back.

**Comment by Johann-S** [comment]
I was asking about your changes.
It seems a lot of work for just a letter before an ID 🤔 BTW it was the case in v4 too

**Comment by Hiws** [comment]
Well, it isn't really limited to a letter, could be anything (from my understanding of the HTML5 spec).
```html
<div id="#👌-id">
```

I forgot to link it to the issue (#31099) that caused me to look into it.
Wanted to give it a try, to see if it was possible to do without having to add a *ton* of extra work, which it does for the cases i (limited) testing of the mentioned plugins.

But yeah, if more work needs to be done to make it work properly, like with `#foo, #far`. 
Then it's probably not worth handling this edge case, since the workaround is rather simple (start `id` with an alpha character)

**Pull request closed without merging**
