### PR TITLE
Adds a note about limitations on content being larger than the image

### PR DESCRIPTION
**Pull request by helmutgranda**
In the event that the content is larger than the image, the content will continue to be displayed outside the image itself. There are some workarounds but they apply only to browsers that support this option and IE11 is not one of them.

This pull request should fulfill the need in issue https://github.com/twbs/bootstrap/issues/27189

### CODE REVIEW

**Comment by XhmikosR** [comment]
There's a typo in the filename of the new file you added. Also, why do we need this to be a new include if it's used only once?

**Comment by helmutgranda** [comment]
@XhmikosR  Thanks for the feedback, at first I thought I was following best practices by adding the data to an external file but it seems like that is not necessary.

**Comment by XhmikosR** [comment]
@MartijnCuppens: LGTY?

**Comment by MartijnCuppens** [comment]
LGTM:
image

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
