### PR TITLE
Prevent breadcrumb separator from getting underlined on hover when not using <ol> markup

### LINKED ISSUE #18733: Breadcrumbs :hover showing underline under separator when using <div> instead of list
Showing underline under a seperator

### PR DESCRIPTION
**Pull request by cvrebert**
Uses wacky IE hack explained in the answers to http://stackoverflow.com/questions/8820286/how-to-remove-only-underline-from-abefore
Fixes #18733.
Closes #18740.

### CODE REVIEW

**Comment by cvrebert** [comment]
Getting some obvious questions out of the way:

(1) No, the IE hack cannot be simplified to:
```css
.breadcrumb-item:hover::before {
  text-decoration: underline;
  text-decoration: none;
}
```
It must be 2 separate rules.

(2) Yes, the IE hack does survive minification unscathed.

**Comment by cvrebert** [comment]
CC: @mdo @patrickhlauke for review

**Comment by mdo** [comment]
Hmm, how was this not a problem in v3? Wonder if it's a problem of using `float`s as well?

**Comment by cvrebert** [comment]
@mdo Because v3 required using `<ul>` or `<ol>` markup for breadcrumbs. v4 lets you use a plain `<div>`; and indeed, the bug doesn't occur in v4 when using an `<ol>`.

**Comment by cvrebert** [comment]
@mdo Any further feedback?

**Comment by mdo** [comment]
Taking a look at a few ideas this weekend.

**Comment by mdo** [comment]
Ah, shit, I understand what's going on now. It's because the `::before` is within the `.breadcrumb-item`, not actually before it. Rough.

**Pull request merged**
