### PR TITLE
Incorporate quick start guide for v4 alpha.

### PR DESCRIPTION
**Pull request by meetbryce**

### CODE REVIEW

**Comment by XhmikosR** [comment]
I don't see the gain from this being that the alpha will be stable sooner or later. But maybe it's only me.

**Comment by cvrebert** [comment]
I tend to agree with @XhmikosR. Or at least this should just update the existing "Quick start" section instead.

**Comment by meetbryce** [comment]
I was originally going to update the existing section but hesitated given
it could end up being left in after the alpha is done.

If people prefer it in the existing I'll re fork and do it that way.
On Wed, 9 Sep 2015 at 6:27 am, Chris Rebert <notifications@github.com>
wrote:

> I tend to agree with @XhmikosR <https://github.com/XhmikosR>. Or at least
> this should just update the existing "Quick start" section instead.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap/pull/17523#issuecomment-138688949>.
>
-- 
Cheers,
Bryce York

**Comment by mdo** [comment]
Yeah, any start stuff should be right in the docs :).

**Pull request closed without merging**
