### PR TITLE
Upgrade to babel 6.0

### LINKED ISSUE #18212: Upgrade Babel
Details: http://jamesknelson.com/the-six-things-you-need-to-know-about-babel-6/
Also: https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/user-handbook.md
CC: @XhmikosR

### PR DESCRIPTION
**Pull request by bastienmoulia**
Add `babel-preset-es2015` and `babel-plugin-transform-es2015-modules-umd` to package.json to generate ES2015 JS files
Edit Gruntfile with the new configuration for babel
Add require.js for QUnit tests because with babel 6 modules can’t be directly loaded
Remove autostart for QUnit to wait for require.js loading
Replace `Util.getUID()` by `document.getElementById()` in tests because `Util` is not reachable anymore

Close #18212

### CODE REVIEW

**Comment by wolfy1339** [comment]
Can you squash the commits?

**Comment by bastienmoulia** [comment]
@wolfy1339 I just did it

**Comment by XhmikosR** [comment]
@bastienmoulia: please take care of the lint issues.

**Comment by bastienmoulia** [comment]
@XhmikosR I don't see how, all files in error are in the dist folder generated by Babel.

**Comment by XhmikosR** [comment]
@bastienmoulia: then try updating the hound configuration.

**Comment by mdo** [comment]
This was addressed by @bardiharborow in #20555. Thanks though!

**Pull request closed without merging**
