### PR TITLE
File chooser size

### LINKED ISSUE #28769: Small/large file chooser
Right now, it looks like there aren't small or large file choosers. That's problematic, when you want to use the file chooser in a form, where all other fields are small. In the end, it looks rather ugly.

Or is there something, that I've missed or overlooked?

I already opened this ticket, but they say, that it's a bootstrap issue: https://github.com/bootstrap-vue/bootstrap-vue/issues/3285

### PR DESCRIPTION
**Pull request by Zedicius**
Add size option classes for form file input.

Closes #28769

https://deploy-preview-30040--twbs-bootstrap.netlify.com/docs/4.3/forms/file/#sizing

### CODE REVIEW

**Comment by Zedicius** [comment]
<details>
<summary>Details</summary>



</details>

<details>
<summary>Details</summary>



</details>

**Comment by Zedicius** [comment]
https://deploy-preview-30040--twbs-bootstrap.netlify.com/docs/4.3/forms/file/#sizing

**Comment by MartijnCuppens** [comment]
Styling should be applied to `.form-file-text`, see the slight difference in heights:

image

**Review by MartijnCuppens — APPROVED** [review]
Fixed the sizing issue, LGTM now.

**Review by MartijnCuppens — APPROVED** [review]

**Pull request merged**
