### PR TITLE
State Edge support instead of IE 11 as latest

### LINKED ISSUE #17055: Microsoft Edge support for v4
The supported browsers section doesn't reference Microsoft Edge.

### PR DESCRIPTION
**Pull request by kkirsche**
Fix #17055

### CODE REVIEW

**Comment by hnrch02** [comment]
Isn't it called Microsoft Edge and not Internet Explorer Edge?

**Comment by kkirsche** [comment]
Technically. I've seen it written both ways. If there is a preference for one I can write it as such. As there's a range I don't necessarily see it as a new or different thing just the next version

**Comment by kkirsche** [comment]
I think of their docs which use a slash since they are essentially the same just rebranded https://msdn.microsoft.com/en-us/library/hh772401(v=vs.85).aspx

**Comment by patrickhlauke** [comment]
The official name is Microsoft Edge, yes

**Comment by kkirsche** [comment]
@patrickhlauke changing it now

**Comment by kkirsche** [comment]
Fixed

**Comment by hnrch02** [comment]
I don't think it's fair to call it "just a rebrand", they are catching up pretty fast to other browser both performance-wise and with standards compliance.

**Comment by kkirsche** [comment]
That's besides the point though @hnrch02 to this actual PR in all honesty whether we agree or not doesn't really matter on the semantics

**Comment by hnrch02** [comment]
Fair enough, do we have any data backing up the claim that we support Edge here?

**Comment by kkirsche** [comment]
@hnrch02 what data would you like? I can provide screenshots of the v4 docs in edge if that's helpful.

**Comment by hnrch02** [comment]
Running the JS test suite was what I was thinking about.

**Comment by kkirsche** [comment]
@hnrch02 if that's the case I can't provide that since the test suite doesn't load in edge

screen shot 2015-08-19 at 5 42 45 pm

**Comment by kkirsche** [comment]
Works — I hadn't extracted stuff:

screen shot 2015-08-19 at 5 44 36 pm

**Comment by hnrch02** [comment]
Nice, thanks - LGTM.

**Comment by kkirsche** [comment]
Course. Sorry for the misunderstanding with Edge. Not to say it's bad, it's not. I just looked at the rebrand of the same thing from an overall brand perspective not to functionality. Minor change to icon, use of name Edge to keep the iconic E logo instead of spartan. It may have been an unfair or not fully qualified statement on my part. Thanks for understanding :+1:

**Comment by hnrch02** [comment]
All good :bowtie:

**Comment by impulz** [comment]
I think it would be good to list IE11 and Edge as different browsers since they are using a different  redering engine. Edge is using EdgeHTML while IE11 is using MSHTML and it seems that Microsoft will add new platform features only to Edge. However both browsers are present in Windows 10 (IE11 for legacy reasons). Source: http://dev.modern.ie/platform/faq/what-is-microsoft-edgehtml

Maybe IE+Edge support should also be considered "Partially Supported"  (at least for now) due to issues like #17073

**Comment by kkirsche** [comment]
While I can understand that A.) the first part is opinion and not worth any of our argument about honestly. It's a different product. Plain and simple. B.) I would go with supported as bugs don't mean it's not supported it means the documentation isn't up to 100% where it needs to be yet as this is an alpha not a final release

**Pull request merged**
