### PR TITLE
Add Algolia search to docs

### LINKED ISSUE #21125: Searching for "tabs" on v4 docs site doesn't return nav page
Go to https://v4-alpha.getbootstrap.com/getting-started/introduction/ and search for "tabs"
Expected: https://v4-alpha.getbootstrap.com/components/navs/ is returned
Actual: "Sorry, there are no results for that search."

### LINKED ISSUE #21170: v4 - Improve Docs Search
The current search in v4 docs only looking for Page Titles, not the actual content. Due to the structure change and ease of usability, I recommend improving the search to all **content and code**.  So it will be easier to look for a specific element. 

There are some search providers like Agolia and Swiftype.  I hope it will be easier to integrate those. 

On version 3, I was  (most of the people may be) using the Browser Search CTRL + F. Since in new version, all sections are different page, its impossible to do that too :(

### LINKED ISSUE #21382: Add search bar button in Doc.
- Operating system and version (Ubuntu 15.04)
- Browser and version (Chrome)

When suggesting a feature, include:

-Why it's important to Bootstrap?
  I need to only particular class details eg. form-control etc.

image

### PR DESCRIPTION
**Pull request by mdo**
This PR is a WIP effort to replace the [Jekyll simple search plugin](https://github.com/christian-fei/Simple-Jekyll-Search) for an Algolia based one. This was originally proposed in #16901 for the v3 docs, but I punted on it like an idiot. Good news though, it's making a comeback for v4.

- [x] Drop old Jekyll search plugin
- [ ] Implement basic Algolia autocomplete functionality
- [ ] Customize JS to use Bootstrap classes and templates
- [ ] Move Algolia search and any custom CSS to `docs/assets/` as needed
- [ ] Update config to index `<h2>`s, `<h3>`s, and more from our pages

/cc @pixelastic

---

Fixes #21382, fixes #21125, fixes #21170, improves #15403, fixes #9309 (hah), fixes #3866 (lol).

### CODE REVIEW

**Comment by mdo** [comment]
@pixelastic Is there a reference guide somewhere for all the options you have in your PR's `_config.yml`? I'm unsure exactly what each does, and adding it wholesale to this PR results in JS errors when searching.

**Comment by mdo** [comment]
All of this could be moot given DocSearch, but I didn't feel like waiting for that to start experimenting at least. Will jam on some other bits while I wait to hear back though.

**Comment by maxiloc** [comment]
Hi @mdo.

You indeed have the choice between the PR of @pixelastic or going with DocSearch.
There is a few advantages of using DocSearch:

- the snippet to insert is very small.
- you don't have to manage an algolia account, we can still give you access if needed (it can be useful to use algolia search analytics)
- we monitor the index, meaning that if something goes wrong we know about it and we fix it.

In case you want to go with DocSearch, I bootstrapped the config for you, It should be good relevance wise but we can tweak if you see something that we could improve.

To implement it, you just have to use the following snippet:

```
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.css" />
<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: '48cb48b22351bc71ea5f12f4d1ede198',
  indexName: 'bootstrap-v4',
  inputSelector: '#search-input',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

If want to tweak the look and feel you can either override the complete css file or override a few css rules.

One thing to note is that right now the results will redirect to `https://v4-alpha.getbootstrap.com/`.

When the v4 website goes to production, we will need to update the [DocSearch config](https://github.com/algolia/docsearch-configs/commit/157f3256011f7d624ec1f334a7da6795b3e9c5d6#diff-f485ed8cd796ace78ba5ce7a674ec00c)

Feel free to ping me if you have any question regarding DocSearch.

**Comment by mdo** [comment]
Closing for #22715 for now.

**Comment by pixelastic** [comment]
I have to agree with @maxiloc here. DocSearch will be a better solution for you here. 

The main difference is that DocSearch is live on many popular documentations websites already and we've been able to improve it with all the feedback we receive. As a result, it can handle more use-cases than the Jekyll plugin. On the other hand the Jekyll plugin is still officially a v0. We do have a v1 in a branch, but it has never been officially released, so I cannot really ask you to use a beta version on Bootstrap docs.

The other important difference is that (by default) DocSearch is a web crawler. Meaning that it can only index content that is publicly available online, and will run every 24h. To workaround that, we also provide a Docker image, that can be run against a local server, from the commandline. If that's what you'd like to setup, I suggest we continue this discussion in #22715.

**Pull request closed without merging**
