### PR TITLE
wip: adds `$nav-link-*` vars

### PR DESCRIPTION
**Pull request by zalog**
This PR adds a new vars for `$nav-link-*`'s:
```
$nav-link-font-size:                null !default;
$nav-link-font-style:               null !default;
$nav-link-font-weight:              null !default;
$nav-link-color:                    $primary !default;
$nav-link-hover-color:              darken($primary, 15%) !default;
```

This PR depends on https://github.com/twbs/bootstrap/pull/30622

### CODE REVIEW

**Comment by zalog** [comment]
I think we also need to add hover and active states as well. What do you think?

**Comment by MartijnCuppens** [comment]
> I think we also need to add hover and active states as well. What do you think?

Any suggestions theming wise?

**Comment by zalog** [comment]
I'll come back here soon, this days.

**Comment by zalog** [comment]
Removed wip and rebased.

**Comment by ffoodd** [comment]
LGTM.

FWIW, I'd go with the active state too — even if the active state should not rely on color only (but this is another topic to tackle in Bootstrap and/or examples, I guess).

**Comment by mdo** [comment]
Closing for #31035.

**Pull request closed without merging**
