### PR TITLE
Enable ESLint and JSCS in Hound

### PR DESCRIPTION
**Pull request by ameya-pandilwar**
Fix for #19114

### CODE REVIEW

**Comment by cvrebert** [comment]
I believe you'll also need to specify the custom paths to our `.eslintrc` and `.jscsrc` files.

**Comment by XhmikosR** [comment]
@ameya-pandilwar: please squash the patches.

**Comment by ameya-pandilwar** [comment]
@XhmikosR done. squashed 'em!

**Comment by XhmikosR** [comment]
@cvrebert: :shipit:

**Comment by XhmikosR** [comment]
This needs a fetch and rebase.

**Pull request closed without merging**
