### PR TITLE
Fix XSS in Alert, Carousel, Collapse, Dropdown and Modal

### PR DESCRIPTION
**Pull request by innabauman**
(cherry picked from commit 29f9237)

### CODE REVIEW

**Comment by Johann-S** [comment]
No need to cherry pick this commit because at the end of our v3.4 it will be in v3-dev

**Comment by carltongibson** [comment]
@Johann-S: I think the question is When will there be a v3.4? This XSS vulnerability was fixed almost exactly a year ago but there's no release for it. 

Users are having to do things like this to work around it.

**Comment by rmirre** [comment]
The sad thing is that select developers from twbs seem to _want_ to fix it, or have floated a v3.4 release. But for whatever reason, that release/fix never sees the light of day. I understand the focus to v4, but updating for larger enterprises is not a simple thing. We have fixed this vulnerability on our installation, but will still get flagged as our version number is associated with this XSS vulnerability. The user below essentially touches on the pain we feel with our IT department, and I am sure many other teams can relate.

https://github.com/twbs/bootstrap/issues/25679#issuecomment-402962532

Kudos though to @innabauman for the fix and PR for the rest of the community though 👏

**Pull request closed without merging**
