### PR TITLE
Fixes modal positioning on android (#26760)

### PR DESCRIPTION
**Pull request by jvitela**
When address bar is hidden, sometimes the visual position of the controls is out of sync with its logical position.

### CODE REVIEW

**Comment by jvitela** [comment]
@MartijnCuppens, @mdo Can somebody review this changes? They've been sitting here for a while :-(

**Comment by mdo** [comment]
I don't have an Android on me at this time to test unfortunately. Anyone else?

**Comment by XhmikosR** [comment]
@mdo: You can use Browser Stack.

@MartijnCuppens: can you review please?

**Comment by MartijnCuppens** [comment]
@jvitela, can you also add this fix for `.modal-backdrop`?

**Comment by MartijnCuppens** [comment]
This is better, but now I see the backdrop isn't stretching at the bottom when address bar is hidden. Can you check if you can fix this @jvitela?

**Comment by jvitela** [comment]
Using **viewport units** for sizing `.modal-backdrop` solves the resizing issues and also eliminates the undesired effect of the modal jumping up and down after the address bar appears/disappears.

**Comment by mdo** [comment]
@MartijnCuppens If you confirmed latest changes fix your issues, this looks good to me. I don't have an Android phone right now to test myself.

**Comment by MartijnCuppens** [comment]
Nope, `height: 100vh` will make the modal scrollable if the address bar is shown. I'll check tomorrow if there's something we can do about this.

**Comment by MartijnCuppens** [comment]
Something went wrong here, we're looking into it

**Pull request closed without merging**
