### PR TITLE
Embed responsive tweaks

### LINKED ISSUE #25906: Variable ratios for responsive embeds
Since colors, spacers, sizes, ... are generated based on map I think it would be just as suitable to introduce a `$embed-ratios` variable.

See [this gist](https://gist.github.com/c0defre4k/9699b11263ca6df239be3962eb1d0e01) for an implementation example,

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Fixes #25906.

With this PR it's possible to add aspect ratio's.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@MartijnCuppens: if you could split the `calc` change to a separate PR that would be better.

**Comment by XhmikosR** [comment]
Are you sure it doesn't? I was hoping it'd fix #26284 since that's the only other place I could find us using `percentage`.

**Comment by MartijnCuppens** [comment]
It doesn't, see https://codepen.io/MartijnCuppens/pen/ZqXzbL

**Review by XhmikosR — APPROVED** [review]

**Review by mdo — APPROVED** [review]

**Comment by martinbean** [comment]
@MartijnCuppens What‘s the syntax for this? In a **_variables.scss** file (that I include in my Sass file before Bootstrap) I have this:

```scss
$embed-responsive-aspect-ratios: (
  (4 3)
);
```

But when I run Sass, I get this error:

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

```
  $embed-responsive-aspect-ratio-y: nth($embed-responsive-aspect-ratio, 2);
                                   ^
      $n: Invalid index 2 for a list with 1 elements.
   ╷
32 │   $embed-responsive-aspect-ratio-y: nth($embed-responsive-aspect-ratio, 2);
   │                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
```

I’m having to manually re-add the 4:3 ratio because the fix hasn’t been pushed to npm yet, and I have sites with collapsed images now where their front-end assets have been built and deployed.

**Pull request merged**
