### PR TITLE
Fix link decoration handling in Bootstrap SCSS files

### LINKED ISSUE #39204: Fix $link-decoration and $link-hover-decoration conditionals
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

https://github.com/twbs/bootstrap/pull/30262 and https://github.com/twbs/bootstrap/commit/7fc4037a02910fa7590fa9e21387fb6e3d325755 introduced a bug.

```
scss/_buttons.scss
  32,20:   text-decoration: if($link-decoration == none, null, none);
  45,22:     text-decoration: if($link-hover-decoration == underline, none, null);
scss/_card.scss
  94,22:     text-decoration: if($link-hover-decoration == underline, none, null);
scss/_dropdown.scss
  183,20:   text-decoration: if($link-decoration == none, null, none);
  192,22:     text-decoration: if($link-hover-decoration == underline, none, null);
scss/_list-group.scss
  80,20:   text-decoration: if($link-decoration == none, null, none);
scss/_nav.scss
  30,20:   text-decoration: if($link-decoration == none, null, none);
  38,22:     text-decoration: if($link-hover-decoration == underline, none, null);
scss/_navbar.scss
  71,20:   text-decoration: if($link-decoration == none, null, none);
  77,22:     text-decoration: if($link-hover-decoration == underline, none, null);
scss/_pagination.scss
  35,20:   text-decoration: if($link-decoration == none, null, none);
  43,22:     text-decoration: if($link-hover-decoration == underline, none, null);
```

It seems the above attempts to make the link decoration DRY by not including this text-decoration property when the value matches the a particular value.

For example, a `.nav-link`'s `text-decoration` property would already be set to `underline` by default, so set it to none here, and a redundant `text-decoration` property will not be generated. However, this does not take into account other values: only underline and none are options. The `$link-hover-decoration` condition is even worse: when set to `underline`, it overrides it with `none`, otherwise its set to `null` and therefore not generated.

This could be fixed with adjusted condition logic:

```
text-decoration: if($link-decoration == none, null, $link-decoration);
@if ($link-hover-decoration != underline) { text-decoration: $link-hover-decoration;}
```

### Reduced test cases

https://codepen.io/jcandan/pen/PoXOwzK

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.2

### PR DESCRIPTION
**Pull request by layenis**
### Description

This commit refactors the handling of link decorations in _buttons.scss, _card.scss, _dropdown.scss, _list-group.scss, _nav.scss, _navbar.scss, _pagination.scss files. The `text-decoration` property is now correctly applied based on the conditions specified by $link-decoration and $link-hover-decoration variables.

### Motivation & Context

This change is required to fix issues related to the handling of link decorations in Bootstrap SCSS files introduced by another fix.

The original implementation attempted to optimize the handling of link decorations by excluding the text-decoration property under specific conditions. However, this led to incorrect behavior due to incomplete consideration of all possible values for $link-decoration and $link-hover-decoration.

This fix addresses these issues by ensuring proper handling of the text-decoration property based on specified conditions. Specifically, it ensures that the text-decoration property is correctly applied according to the values of $link-decoration and $link-hover-decoration, thereby resolving visual inconsistencies or unexpected rendering of link decorations.

### Type of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [X] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

#### Live previews

- <https://deploy-preview-39934--twbs-bootstrap.netlify.app/>

### Related issues

Closes #39204

### CODE REVIEW

**Comment by XhmikosR** [comment]
Please make sure lint passes.

**Comment by XhmikosR** [comment]
@mdo: this changes the look in many places, please have a look (see the docs preview for example).

**Comment by XhmikosR** [comment]
If it's going to be so big of a change, maybe we should postpone it until later.

**Review by julien-deramond — CHANGES_REQUESTED** [review]
Thanks for submitting a PR @layenis 
I haven't looked at the changes in the code, but there's something off just by looking at the main page of our documentation:
Screenshot 2024-05-06 at 07 13 49
Screenshot 2024-05-06 at 07 13 43
Screenshot 2024-05-06 at 07 13 38

These elements are not meant/designed to be underlined, and should stay as they were by default.

**Comment by mdo** [comment]
Closing given the issues mentioned.

**Pull request closed without merging**
