### PR TITLE
Allow users to customize focus and active button states.

### PR DESCRIPTION
**Pull request by flachware**
This enhancement of the buttons mixin allows the user the following adjustments in `_variables.scss`:

- Adjust the percentages of the `:focus` and `:active` state color function
- Either 'lighten' or 'darken' the states by using a positive or negative value
- Mix 'lighten' and 'darken' states

### CODE REVIEW

**Comment by andresgalante** [comment]
Hi @johanneskrtek Thanks for sending this PR and giving it another shot.

To me having variables that get inserted into mixins are hard to understand.

@mdo mentioned that the focus stays as is, and I agree with him, I don't see the need to change it. But I'll let him decide on this PR.

**Comment by johanneskrtek** [comment]
Hi @andresgalante, thanks for your review!

We could also pass `$btn-focus-bg-lightness` etc. as regular arguments to the mixin and do the color manipulation later, if that helps. This way we would not have to rely on global variables. Does that sound better to you?

If you think the focus and hover states should not be configurable at all, well, that’s another story. Imho users will either patch the Bootstrap mixin code then or move the button/button mixin code into their own source code and run the mixin with modified values there (in case they need to modify the states).

**Comment by mdo** [comment]
Going to punt on this for now. We'll wait for more feedback on the mixins before adding all the params.

**Comment by sekmo** [comment]
I think it would be a great addition! What's the current state? :-)

**Pull request closed without merging**
