### PR TITLE
Draft:: Move static DATA_KEY() to base-component

### PR DESCRIPTION
**Pull request by GeoSot**
Extract static method DATA_KEY() to base-component
(With a tricky way I can admit, according to [this](https://stackoverflow.com/a/55577230))

### CODE REVIEW

**Comment by sebaaaay** [comment]
> Extract static method DATA_KEY() to base-component
> (With a tricky way I can admit, according to [this](https://stackoverflow.com/a/55577230))

**Comment by rohit2sharma95** [comment]
@GeoSot It is not guaranteed that you will get the same name of the class after minification.
For example, after minification Dropdown may be changed to any random (and probably short) name.

**Comment by GeoSot** [comment]
@rohit2sharma95 What a pity. You are right. I've made a quick check on the preview and damn........

**Comment by sebaaaay** [comment]
Hallo, wollen wir ein gemeinsames Projekt starten? Hast du ein bisschen
Arbeit für mich? └|∵|┐♪(＾∇＾)ﾉ♪

GeoSot <notifications@github.com> schrieb am Fr., 12. Feb. 2021, 09:18:

**Comment by rohit2sharma95** [comment]
But it is an internal thing and used to map the instances with the DOM element. So whatever the data key name is, the instances will still be mapped and it will not break anything IMO.
@alpadev WDYT?

/CC @XhmikosR

**Comment by XhmikosR** [comment]
Not sure about this one TBH. The new tests I like so feel free to split those to a separate PR @GeoSot :)

**Comment by alpadev** [comment]
> But it is an internal thing and used to map the instances with the DOM element. So whatever the data key name is, the instances will still be mapped and it will not break anything IMO.
> @alpadev WDYT?
> 
> /CC @XhmikosR

Your concern about minification is indeed valid. In theory if the minified names of the constructor functions stayed unique it shouldn't be a problem. Had a look at the minified code tho and it looks like the minifier partly reuses the same letters 🙁.

image


Without the support for multiple instances per element, it's likely that this would still continue to work as expected, but could become flaky at some point.

Also, there would be another change to the code neccessary. In places like https://github.com/GeoSot/bootstrap/blob/32343ac194a6f279a3180ba5553aa342ce494154/js/src/button.js#L48
or
https://github.com/GeoSot/bootstrap/blob/32343ac194a6f279a3180ba5553aa342ce494154/js/src/button.js#L72
we can't simply rely on the scoped variable anymore but would have to use the static field as well.

I like the idea in general but I share @XhmikosR's concern.

**Comment by rohit2sharma95** [comment]
Thanks, @alpadev, for the explanatory comment. 
@GeoSot, Can you please move the tests to the separate PR.
:heart:

**Pull request closed without merging**
