### PR TITLE
Added $card-cap-color variable in .card-header and .card-footer

### PR DESCRIPTION
**Pull request by afuno**
If the theme is light, and header is dark, it is unreadable. Give the
opportunity to change the text color.

### CODE REVIEW

**Comment by BhaveshSGupta** [comment]
I can help with this one

**Comment by mdo** [comment]
I don't see this as being needed. Headers and footers appear fine for me with the inverse modifier.

screen shot 2017-03-18 at 4 35 14 pm

**Comment by afuno** [comment]
@mdo I wrote that it is necessary when the content is light, and the header is dark. On your screenshot, the content and header are dark.

**Comment by mdo** [comment]
@afuno Please provide an example with https://jsbin.com and I can revisit <3.

**Comment by afuno** [comment]
@mdo https://jsbin.com/sazoziwuhi/edit?html,css,output

**Pull request closed without merging**
