### PR TITLE
Scope anchorjs to immediate children

### LINKED ISSUE #16129: AnchorJS should not be active in live examples
For example, it's currently active on the example panel titles in http://getbootstrap.com/components/#panels-alternatives
CC: @XhmikosR

### PR DESCRIPTION
**Pull request by mdo**
Fixes #16129.

/cc @cvrebert @XhmikosR

### CODE REVIEW

**Comment by XhmikosR** [comment]
Does that cover all cases? Also, I was waiting for https://github.com/bryanbraun/anchorjs/pull/33, but if you think this covers all the cases we can go with it.

**Comment by mdo** [comment]
It covers enough of it I think. I don't especially want this on our callouts, for example. And we don't really neat docs sections, just some of the examples. Should be enough (I do this on Primer, too).

**Comment by XhmikosR** [comment]
Cool, then :shipit:

**Comment by XhmikosR** [comment]
@mdo: for some reason I don't see any anchors in current master?

**Comment by XhmikosR** [comment]
OK, I confirmed it; this just breaks anchor-js. We should have tested it before merging it...

**Pull request merged**
