### PR TITLE
Make .btn in .btn-toolbar float:left too

### LINKED ISSUE #16276: `.btn-toolbar .btn-group {float: left}` prevents btn left of btn-group
Consider the following markup:

```
<div class="btn-toolbar">
 <button class="btn">Left button</button>
 <div class="btn-group">
   <button class="btn">LB</button>
   <button class="btn">RB</button>
 </div>
 <button class="btn">Right button</button>
</div>
```

One would expect "Left button" to appear left of the button group, but the reverse is true because of the `.btn-toolbar .btn-group {float: left}` in `button-groups.less`. See http://www.bootply.com/slYNLprbgV to reproduce.

### PR DESCRIPTION
**Pull request by cvrebert**
Fixes #16276.

### CODE REVIEW

**Comment by mdo** [comment]
:shipit:

**Comment by mdgeek** [comment]
Unfortunately, this "fix" breaks the layout of our applications.

**Comment by mdo** [comment]
Sorry about that. Not much we can do given CSS's nature—a single property can work for some folks and not for others. Hope the fixes on your end aren't too intense <3.

**Comment by md5** [comment]
@mdo Should this same change have been made in `v4-dev`? I'm still seeing `btn-group` in a `btn-toolbar` floating to the left of a preceding button in V4: https://github.com/twbs/bootstrap/blob/6e7d450/scss/_button-group.scss#L41

**Pull request merged**
