### PR TITLE
Testing Savage's commit status feature

### PR DESCRIPTION
**Pull request by expendable123**
DO NOT MERGE!

### CODE REVIEW

**Comment by cvrebert** [comment]
(I'm running a test)

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 21bbdfc3a54468e7beec93c2a1c60e548c6d9d10
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/59828085

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 21bbdfc3a54468e7beec93c2a1c60e548c6d9d10
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/59828085

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: a220d3fe22dda532481f7b3224f26d5c94cb532d
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/59831671

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 42192256762ac2f97916fbd8e7dca484cf7f4514
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/59834707

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: d39fdaf5ed3ac0a1b98be1e44e4adf1702b4da69
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/59837327

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Pull request closed without merging**
