### PR TITLE
Show the other navbar items on small screens too.

### PR DESCRIPTION
**Pull request by XhmikosR**
Do not merge until we have 3 approvals :)

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
The navbar was misaligned on desktop, so I removed the margin with `.mt-md-0`. Not sure if we even need the margin on mobile.

**Comment by XhmikosR** [comment]
Yeah, that was a typo on my side. Not sure either, there's a padding-bottom in the top navbar already.

**Comment by MartijnCuppens** [comment]
I just removed it, the padding does the trick.

**Review by Johann-S — APPROVED** [review]
LGTM 👍

**Review by MartijnCuppens — APPROVED** [review]

**Comment by XhmikosR** [comment]
@mdo: LGTY?

**Comment by XhmikosR** [comment]
@mdo: friendly ping :)

**Comment by XhmikosR** [comment]
@mdo: LGTY?

**Review by mdo — APPROVED** [review]
Oh this looks dope. Sorry to have delayed so bad!

**Pull request merged**
