### PR TITLE
Meteor: Switch to manual installation instructions for v4

### PR DESCRIPTION
**Pull request by marvinmarnold**
Accurate Meteor install instructions

### CODE REVIEW

**Comment by cvrebert** [comment]
I would much prefer to have us fix the Meteor packaging integration instead of documenting a workaround.
@dandv @splendido Can we get `meteor add twbs:bootstrap@=4.0.0-alpha.2` working properly? (I don't have Meteor, so I can't check whether it's actually currently broken.)

**Comment by marvinmarnold** [comment]
@cvrebert AFAIK, its [not possible to install Meteor packages directly from Github](https://forums.meteor.com/t/how-to-install-meteor-package-direct-from-github/1693). Unless I'm mistaken, you'll have to push all changes to Atmosphere for `meteor add` to work.

**Comment by cvrebert** [comment]
That's why we're using autopublish.meteor.com, as setup in #15716.

**Comment by marvinmarnold** [comment]
Not sure if [this file](https://github.com/nate-strauser/meteor-x-editable-bootstrap/blob/master/package.js#L16) should be updated, found it in a pull request. Or if [package.js](https://github.com/twbs/bootstrap/blob/master/package.js#L9) should be edited directly in the twbs repo. 

Either way, the version number should be consistent with `meteor add twbs:bootstrap@VERS.ION.NUMBER`

But I could also be wrong given I'm not familiar with the Bootstrap build process or Atmosphere's autopublish feature.

**Comment by splendido** [comment]
@cvrebert with the current webhook setup we're getting triggers for autopublish.meteor.com only for proper releases. Pre-releaes do not trigger the webhook.
So far, normal releases have been correctly auto-pulished [as you can see on Atmosphere](https://atmospherejs.com/twbs/bootstrap)

Btw, I manually published the two alpha releaes for v4 even if there's no way to see them on atmosphere.
@marvinmarnold you can run `meteor show --show-all twbs:bootstrap` to see all available versions:

```shell
Versions:                                     
  3.3.1         November 28th, 2014           
  3.3.1_1       December 11th, 2014
  3.3.1_2       December 12th, 2014
  3.3.2         January 26th, 2015
  3.3.4         March 16th, 2015
  3.3.5         June 16th, 2015
  3.3.6         November 24th, 2015
  4.0.0-alpha   August 25th, 2015
  4.0.0-alpha2  December 30th, 2015
```

the latest alpha version is missing a dot before the final 2: it's my fault.
But I'm not sure the meteor versioning would permit a third dot in the version string thogh...

In any case `meteor add twbs:bootstrap@4.0.0-alpha2` is working flawlessly

**Comment by marvinmarnold** [comment]
thanks @splendido, i reverted to original install style with correct repo name in 9579e9ec45ca11a416ddb50c1bbace2d82b4e108

**Comment by cvrebert** [comment]
> But I'm not sure the meteor versioning would permit a third dot in the version string thogh...

@splendido Really? It's just vanilla SemVer. Could you please confirm whether Meteor would accept `4.0.0-alpha.2`? Having the Meteor version number be different from that of the other packages is annoying when it comes to updating it.

**Comment by splendido** [comment]
@cvrebert I've just checked again the naming rules for packages and eventually published `twbs:bootstrap@4.0.0-alpha.2`.
There's no need to use a different version number inside _package.js_!

I'm sorry for the annoyance.

**Comment by cvrebert** [comment]
@splendido Yay! Wonderful. Thanks!

**Comment by cvrebert** [comment]
Closing this since now no change is necessary.

**Comment by darkdeath69** [comment]
Stop plz



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=6.0.5.9&pv=5.1.1&source=email_footer_2]

**Comment by splendido** [comment]
As for the _autopublish_ of pre release versions, since I saw you're using git tags only for releases and pre-releases, would you mind change the settings for the webhook to `Create` in place of `Release` (see [this screenshot](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki/How-to-manually-set-up-web-hooks#tags))?

This should be enough to trigger autopublish.meteor.com also for pre-releases.

**Comment by cvrebert** [comment]
@splendido Erm, it's already set to `Create`...

**Comment by darkdeath69** [comment]
stop



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=6.0.5.9&pv=5.1.1&source=email_footer_2]


On Tue, Jan 05, 2016 at 2:24 AM, Luca Mussi < notifications@github.com [notifications@github.com] > wrote:
As for the autopublish of pre release versions, since I saw you're using git tags only for releases
and pre-releases, would you mind change the settings for the webhook to Create in place of Release (see this screenshot
[https://github.com/MeteorPackaging/autopublish.meteor.com/wiki/How-to-manually-set-up-web-hooks#tags] )?

This should be enough to trigger autopublish.meteor.com also for pre-releases.

—
Reply to this email directly or view it on GitHub
[https://github.com/twbs/bootstrap/pull/18720#issuecomment-168943016] .[https://github.com/notifications/beacon/ALtWf_WJxPnEsb5X39TMT24qmGPqgKUOks5pW4NhgaJpZM4G8mrr.gif]

**Comment by splendido** [comment]
correct. My brain is still on holiday :-(

I had to publish alpha versions manually because the `package.js` file was wrong at that time (see the [log for 4.0.0-alpha publish attempt](https://autopublish.meteor.com/log/Abko2gBGMjxYAd7Zb) and the [log for 4.0.0-alpha.2 publish attempt](https://autopublish.meteor.com/log/) if you wish...).

Now everything should be fine!

**Pull request closed without merging**
