### PR TITLE
Horizontal Scrolling Tooltip Misalignment (#15590)

### PR DESCRIPTION
**Pull request by ghost**
Proposal for resolving an issue with horizontal scrolling affecting the placement of tooltips.  Please see issue #15590.

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: abc628bcb826b10250e6c76e3a4eaf9003b7d6dc
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/47310090

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
@benkennedysnc Seems to be breaking the following unit test: https://github.com/twbs/bootstrap/blob/8a1efe91df296e62bc560e51b462e9d51d31a988/js/tests/unit/tooltip.js#L627

**Comment by benkennedysnc** [comment]
@cvrebert Odd.  I will investigate further.  $('document').width() also works in this case.  It looks like we just need to grab the container width.

**Comment by cvrebert** [comment]
@twbs-savage Retry

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: fc34b884beacfd5bfbb7257fc0cae2b7599ea985
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/48684368

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
Seems like removing the padding option like that might defeat the purpose of that particular unit test... Not completely sure though.

**Comment by fat** [comment]
@benkennedysnc i'm going to close this pr for now. we're going to be replacing our positioning engine in v4, which might address this problem for you. 

meanwhile, if you want this in a v3 patch release - could you repopen a pr which includes a unit test demonstrating the issue you are trying to fix? thanks!

**Pull request closed without merging**
