### PR TITLE
update readme add icons to title

### PR DESCRIPTION
**Pull request by ibrataha8**
### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [ ] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [ ] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

#### Live previews

- <https://deploy-preview-{your_pr_number}--twbs-bootstrap.netlify.app/>

### CODE REVIEW

**Comment by julien-deramond** [comment]
Thanks for this PR @ibrataha8 but we prefer to let the README as it is now.

**Comment by ibrataha8** [comment]
@julien-deramond You didn't appreciate my effort. It seems good, doesn't it? As a beginner, don't I have the right to share my ideas?

**Comment by julien-deramond** [comment]
> As a beginner, don't I have the right to share my ideas?

Yes, you are very welcome to share your ideas, and everyone is.

For your next PRs in this repository, please fill out the "Description" and "Motivation" fields in the PR. Otherwise, we can't know what are the justifications for your changes, and what are your ideas.

> It seems good, doesn't it?

IMHO it doesn't feel good since by adding emojis for each title in the README file, you are also modifying the anchors URLs; for example `README.md#bootstrap-5` becomes `README.md#bootstrap-5-🅱%EF%B8%8F` and so potentially breaks already used URLs by folks.

Still IMHO, I believe that having titles without emojis remains more accessible.

The rest of the core team is also notified, so if they think this PR brings some value they can reopen it.

**Comment by ibrataha8** [comment]
@julien-deramond  I only seek to rectify what I can, with the help of God's guidance. Any mistakes are mine, and any influence from the devil. I seek refuge in God from forgetting Him and strive to be a bridge that leads you to paradise, not a means to be thrown into the fire.

**Pull request closed without merging**
