### PR TITLE
GA: Anonymize IPs and use https.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Review by coliff — CHANGES_REQUESTED** [review]
The script in this PR isn't loading async and is slower than the one used in production now. I would suggest change move to:
```<script>
  window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
  ga('create', 'UA-146052-10', 'getbootstrap.com');
  ga('set', 'anonymizeIp', true);
  ga('send', 'pageview');
</script>
<script async src="https://www.google-analytics.com/analytics.js"></script>```

**Comment by XhmikosR** [comment]
I don't see where you see it's not loaded async.

The only change I did was to add the anonymize IP setting. So, it's whatever it was before.

**Comment by coliff** [comment]
ah, sorry- I had just quickly checked the first few diffs in this PR which were on the old Bootstrap 1.x docs which were/are using a much older analytics snippet so had wrongly assumed the same was used for all the docs. I think it's all good now 👍

**Comment by XhmikosR** [comment]
Yeah, those are left as is for now, since, you know, it's just ancient docs.

**Review by mdo — APPROVED** [review]

**Pull request merged**
