### PR TITLE
Use explicit imports in our javascript source files 

### LINKED ISSUE #36665: use explicit path with imports (add .js)
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

the ESM version of bootstrap only exist as a minified bundle...
i only want to import the files that is needed eg: `import from '_CDN_/js/src/button.js'` but that's impossible in browser cuz you are still using a build script to resolve the path the NodeJS style. true ESM scripts requires file paths to be strict and explicit. it also makes the path resolver faster as it dose not have to guess what file you wanted to import with `import './foo'` (is it a dir with a index file? is it foo.js or something else?)

resolving path's remotly without extension is hard cuz client can't simply guess the full path

### Reduced test cases

```html
<script type="module">
import * as x from 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/js/src/util/component-functions.js'
</script>
```

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.*

### PR DESCRIPTION
**Pull request by GeoSot**
closes #36665

ref: #31944

### CODE REVIEW

**Comment by jimmywarting** [comment]
hi, any particular reason why this is still a draft?

**Review by julien-deramond — APPROVED** [review]
_Just added a small comment regarding a line-break._

I didn't manage to reproduce locally exactly the same behavior as what's described in the issue but I understand what's the issue and this PR corresponds well to what's expected so LGTM!

@XhmikosR You have more experience than me regarding this kind of topic so if you want to check this PR as well :)

**Comment by XhmikosR** [comment]
Yeah, this is something xo kept warning about in my xo branch, but never got to fix it myself. Thanks @GeoSot!

**Comment by XhmikosR** [comment]
Has anyone tested this and confirmed it fixes the problems people mentioned? Just quickly reviewing some PRs here.

**Comment by julien-deramond** [comment]
> Has anyone tested this and confirmed it fixes the problems people mentioned? Just quickly reviewing some PRs here.

On my side I didn't manage to reproduce locally exactly the same behavior as what's described in the issue so I can't confirm with certitude that it fixes the issue. I think it does but not 100% certain.

**Comment by XhmikosR** [comment]
Let's try it I guess since it doesn't look like it can cause any breakage.

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
