### PR TITLE
Fixes #30503 to replace renamed position utility

### LINKED ISSUE #30503: Possible error in documentation
Hi,

When browsing the documentation for the latest version 4.4, I came across an unused class in one of the exemples for the navbar.

The External content exemple contains the `pos-f-t` class which no longer exists in bootstrap:
```html
<div class="pos-f-t">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4">
      <h5 class="text-white h4">Collapsed content</h5>
      <span class="text-muted">Toggleable via the navbar brand.</span>
    </div>
  </div>
  <nav class="navbar navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>
```

I took a look at the commit history, and found one stating that it has been renamed to `position-fixed`.

Thank you

### PR DESCRIPTION
**Pull request by mdo**
Fixes #30503

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
The navbars still seems to be broken: https://deploy-preview-30505--twbs-bootstrap.netlify.com/docs/4.4/components/navbar/

I think we better use the `.fixed-top` class here? I also spotted some margin hacks, I think we can get rid of them too:
https://github.com/twbs/bootstrap/blob/93d745e4ed02019ab39a98c9c418a76c9540a036/site/docs/4.4/assets/scss/_component-examples.scss#L222-L242

**Comment by XhmikosR** [comment]
@mdo friendly ping 🙂 BTW this doesn't seem to apply to master, right?

**Comment by mdo** [comment]
Indeed! Updated to use `.fixed-top` and nuked the `.position-fixed` override styles.

**Review by MartijnCuppens — APPROVED** [review]
> BTW this doesn't seem to apply to master, right?

Nope, `pos-f-t` doesn't seem to be present anymore

**Pull request merged**
