### PR TITLE
Added focus state to .btn-link

### LINKED ISSUE #29891: Focus state removed from btn-link:focus ruleset
## How to reproduce
1. Set focus on an element with the `.btn-link` class

## Expected Behavior
There will be a visual indicator that the element has received focus.

## Actual Behavior
The element does not have a visual indicator for the focus state.

## Other Info
- Operating system and version: Any
- Browser and version: Any

## Cause
Focus states are set using the `box-shadow` property which has a value of `none` in the `.btn-link:focus` declaration block.

### PR DESCRIPTION
**Pull request by timdujardin**
Closes #29891 

Preview: <https://deploy-preview-30036--twbs-bootstrap.netlify.com/docs/4.3/components/buttons/#examples>

### CODE REVIEW

**Comment by XhmikosR** [comment]
Isn't v4 affected by this? If so, we better backport this.

**Comment by XhmikosR** [comment]
Moving this to v5. @patrickhlauke please have a look :) Also, @ysds @MartijnCuppens

**Comment by patrickhlauke** [comment]
isn't the point of `.btn-link` that it's a button, but will look like a link? which is does by showing the underline?

**Review by MartijnCuppens — APPROVED** [review]
We will need some kind of focus indication when https://github.com/twbs/bootstrap/pull/30389 lands

**Pull request merged**
