### PR TITLE
Add support and docs for color input

### PR DESCRIPTION
**Pull request by mdo**
As shown in Safari:

Screen Shot 2019-07-16 at 3 22 15 PM

- [x] Add new `.form-control-color` modifier class to limit the width
- [x] Add basic code example
- [ ] Document styling details, browser support, etc

/cc @twbs/css-review 

Preview: <https://deploy-preview-29059--twbs-bootstrap.netlify.com/docs/4.3/forms/form-control/#color>

### CODE REVIEW

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
Perhaps we shouldn't document browser support? I mean, we'd need to cover macOS, Linux and Windows for each of the browsers.

**Comment by MartijnCuppens** [comment]
I 've added rounded corners to the swatches and fixed the paddings in Firefox. I've also added the a fix which removes padding from webkit browsers in reboot.

**Comment by XhmikosR** [comment]
Should we add cursor pointer?

**Comment by XhmikosR** [comment]
Or a title or something. I feel like it's not clear one can interact with it.

**Comment by MartijnCuppens** [comment]
Yeah, that might be a good idea. Shall we add it with the `$enable-pointer-cursor-for-buttons` variable? 
https://github.com/twbs/bootstrap/blob/dd383ff27b9058c12c2c6d4d6fb0b40413836f2d/scss/_buttons.scss#L14

**Comment by XhmikosR** [comment]
>Should we add cursor pointer?
>Or a title or something. I feel like it's not clear one can interact with it.

@patrickhlauke: what do you think about this?

**Comment by MartijnCuppens** [comment]
Btw, I don't think we need to document what the color picker will look like, browsers might change this anytime.

I would add something about browser support (IE) though.

**Comment by XhmikosR** [comment]
I definitely agree with the above. See https://github.com/twbs/bootstrap/pull/29059#issuecomment-521980988

**Comment by MartijnCuppens** [comment]
Ok, I've changed the copy to a notice about IE not supporting color inputs.

**Review by MartijnCuppens — APPROVED** [review]

**Pull request merged**
