### PR TITLE
Progress bar text

### PR DESCRIPTION
**Pull request by gijsbotje**
the label was cutoff at 0% due to the flex properties
this restores the `text-align: center;` and changes the flex direction and changes align-items to justify-content

fixes: #24538

### CODE REVIEW

**Review by andresgalante — APPROVED** [review]
@gijsbotje thanks!
Just a thought: although `width` works to set the width of the bar, since now the direction is set to `columns` would it be cleaner to use `flex-basis` instead?

**Comment by gijsbotje** [comment]
@andresgalante i guess you can do it either way, doesn't really make a difference.
as the width or flex-basis would be set using inline styling i would maybe mention it in the documentation so people know they can do it either way
do you want me to add that to the docs?

btw: wasn't that allready possible?

**Comment by andresgalante** [comment]
@gijsbotje nope, leave it as is. Not worth mentioning since it just works either way. Thanks a lot for fixing this one.

**Comment by gijsbotje** [comment]
fine with me :)
so it's up to @mdo ?

**Review by mdo — APPROVED** [review]

**Pull request merged**
