### PR TITLE
Don't run postcss for `dist/css/*.min.css` files.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
I think I will rename the scripts to `css-postcss` too, later, so don't merge yet.

**Comment by mdo** [comment]
I take it our minified files are minified after postcss is run on the non-minified CSS files?

**Comment by XhmikosR** [comment]
We use the non minified files as input to clean-css anyway.

**Comment by XhmikosR** [comment]
@mdo: ping

**Comment by XhmikosR** [comment]
@Johann-S @mdo: ping

**Review by Johann-S — APPROVED** [review]

**Pull request merged**
