### PR TITLE
Remove now unnecessary -ms-viewport and -ms-overflow-style directives

### LINKED ISSUE #21780: Scrollbar bug on Windows 10 with IE 11, HiDPI Monitor
Hi guys

I encountered a bug on Windows 10 with Internet Explorer 11 and Bootstrap v4.0.0-alpha.6.
The scrollbar is visible and hidden randomly if I resize the window.
Let me start with two GIFs which demonstrate the issue on a page without any elements except the html structure and body:
bootstrap_v4_scrollbar_bug_my_app
As you can see, on some sizes the scrollbars are visible and on other sizes they are hidden.

The second GIF demonstrates the problem on https://v4-alpha.getbootstrap.com itself:
bootstrap_v4_scrollbar_bug_getbootstrap_com_v4
Same problem. The only difference there is that the scrollable distance is shorter. That's because the vertical scrollbar is needed. If I remove elements until it fits vertically, the scrollable distance is the same comparing to GIF 1.

## Workaround
If I change the viewport width to auto, everything behaves as expected.
```css
@-ms-viewport {
  width: auto;
}
```

## Tests
I tested this on two computers with HiDPI displays:

 Type | Windows Version | Resolution | Scaling | Issue
------|---------------------|-------------|---------|------
Desktop|Windows 10 Pro Insider Preview 1607 Build 15007 |3840x2160|200%|Yes
Tablet - Microsoft Surface|Windows 10 Pro 1511 Build 10586 |2736x1824|200%|Yes

...and on two computers without HiDPI displays:

 Type | Windows Version | Resolution | Scaling | Issue
------|---------------------|-------------|---------|------
Desktop|Windows 10 Pro 1607 Build 14393|1920x1200|100%|No
Notebook|Windows 10 Pro 1607 Build 14393 |1920x1080|100%|No

As you can see, it happens only with HiDPI displays.

**To clarify, I don't have that issue with Edge, only with IE!**

I hope I provided enough details!

### PR DESCRIPTION
**Pull request by patrickhlauke**
Edge/Mobile appears to have moved support for `-ms-viewport` behind a flag at some point, instead supporting meta viewport directives (verified just now with an actual Nokia/Win10/Edge device).
Removing this altogether also fixes issues in IE11 on high-dpi displays - see https://github.com/twbs/bootstrap/issues/21780

Closes #21780

### CODE REVIEW

**Comment by patrickhlauke** [comment]
I believe the only browser that really fully supported and needed the `-ms-viewport` was IE11/Win8 Mobile. And that's now obsolete (in fairness, even Win10 Mobile isn't looking so hot in recent years)

**Comment by patrickhlauke** [comment]
Also confirming that removing this stuff fixes the IE11/high-dpi bug (tested on my Surface Pro 2017 with IE11)

**Review by MartijnCuppens — APPROVED** [review]
I don't have the devices available to test this, but it looks like you did some solid research and I like to see these -ms-hacks removed

**Review by mdo — APPROVED** [review]
Woohoo, awesome! Do we mention anything about this in our docs that'd need updating?

**Comment by XhmikosR** [comment]
So, just to confirm, none of these is needed for IE 11?

**Comment by patrickhlauke** [comment]
> So, just to confirm, none of these is needed for IE 11?

no, and in fact *removing* these fixes problems in IE https://github.com/twbs/bootstrap/issues/21780

**Comment by patrickhlauke** [comment]
@mdo sorry, missed this question

> Do we mention anything about this in our docs that'd need updating?

no, at least doing a search across all the docs didn't have anything that jumped out at me...

**Pull request merged**
