### PR TITLE
Fix XSS in Alert, Carousel, Collapse, Dropdown and Modal

### PR DESCRIPTION
**Pull request by Johann-S**
Fix some XSS in our plugins

Related to : #20184

### CODE REVIEW

**Comment by Johann-S** [comment]
Wrong branch I should target : `v3.4.0-dev`

**Comment by XhmikosR** [comment]
@Johann-S: v3-dev is the one you want. Eventually v3.4.0 should be merged to v3-dev.

**Comment by Johann-S** [comment]
@mdo use this branch for this new release so I'll make my PR to this branch and let him decide 😃

**Comment by XhmikosR** [comment]
Like I said, v3-dev has patches that shouldn't be ignored. So target that branch and @mdo should merge the other branch there when done.

**Pull request closed without merging**
