### PR TITLE
V4 dev herodevs never ending support links and page

### PR DESCRIPTION
**Pull request by edezekiel**
### Description

Update Bootstrap Docs with HeroDevs Never-Ending Support Links and more info about end of life status for Bootstrap 3 and 4.

### Motivation & Context

Introduces Never-Ending Support for Bootstrap.

### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

- <https://deploy-preview-39750--twbs-bootstrap.netlify.app/>

^Link is broken, it appears that live deploy may not be functional for the v4-dev branch.

### CODE REVIEW

**Comment by jwcalles** [comment]
@mdo here are the additions to the v4 docs that we discussed. There was some confusion on our end if this is the correct branch for the PR, so if this is not correct we will await your instructions on where is the correct place. 

This PR adds the banner on the top of the v4 docs pointing users to the newly added "End of Life Status" page with some options for those still using v3 or v4 of bootstrap. 

@edezekiel  and our team are happy to make changes/edits as requested by you and your team.

**Comment by mdo** [comment]
@jwcalles @edezekiel Sorry for the delay! Our old docs versions aren't automatically previewed or pushed out to production anymore, so it's a manual process. We can merge these things into v4-dev and v3-dev, but then we'd have to build the files and manually add them to the `gh-pages` branch.

**Review by mdo — COMMENTED** [review]
Few things to review after testing locally. Will continue to see if I can get v4-dev running locally so we can build this and then push it to production.

**Comment by mdo** [comment]
Review comments and more addressed in #39783. Closing for that new branch that we can ideally use for future updates.

**Pull request closed without merging**
