### PR TITLE
Docs: Optimize *.png with zopflipng -m

### PR DESCRIPTION
**Pull request by scop**
Before: 24352 bytes
After:  24236 bytes

### CODE REVIEW

**Comment by XhmikosR** [comment]
I have already optimized the images myself with zopfli so I find it strange that you have different output.

What was the options you used?

**Comment by XhmikosR** [comment]
So, unless I can reproduce the same results, I'm against this going in @cvrebert.

**Comment by scop** [comment]
As said in the commit message, this was done with the `-m` option. zopflipng is the one that ships with zopfli 1.0.1.

**Comment by XhmikosR** [comment]
You mention it in the commit message, not the PR.

Anyway, my zopfli version is older and I don't have the -m switch.

**Comment by scop** [comment]
The title of the PR does mention `-m` too.

**Comment by XhmikosR** [comment]
Right.

**Comment by XhmikosR** [comment]
All right, I managed to get better compression with `zopflipng -m --lossy_transparent --iterations=1000`.

**Comment by XhmikosR** [comment]
Thanks for bring this into my attention.

I created a branch with better results.

**Pull request closed without merging**
