### PR TITLE
Base text direction support for Bootstrap v4 JS widgets

### PR DESCRIPTION
**Pull request by ashensis**
The BTD support is provided for Tooltip and Popover widgets since only these ones create their HTML markup dynamically.
(Referenced issue #20378)
Bootstrap widgets would provide BTD basing on 'textdir' option been passed to widget constructor.
Alternatively BTD may be specified decoratively as 'data-textdir' attribute of corresponding html element.

Allowed values of 'textDir' attribute are: "ltr" (left-to-right), "rtl" (right-to-
left) and "contextual" (meaning that either 'ltr' or 'rtl' value is used depending on
the first strong(Arabic/Hebrew or English) character of string been displayed.

This PR complements the #19555 which provides the GUI mirroring for Bootstrap 
widgets.
As a whole, current feature alongside with #19555 constitute the full fledged Bidi 
support for Bootstrap widgets.

### CODE REVIEW

**Comment by wolfy1339** [comment]
Please exclude dist files

**Comment by ashensis** [comment]
@wolfy1339  Sorry, I don't follow. Could you please point me out exactly which files should be removed?

**Comment by wolfy1339** [comment]
All the files in the dist directory, all generated css, js, map files etc

**Comment by ashensis** [comment]
1. Deleted all 'dist' folders, including that under 'doc'
2. Fixed build style warnings

**Comment by wolfy1339** [comment]
I didn't meen to delete literally, just remove your changes. So take the latest dist from before your first commit and you should be fine

**Comment by ashensis** [comment]
Original 'dist' folders have been restored

**Comment by mdo** [comment]
Closing as stale.

**Pull request closed without merging**
