### PR TITLE
Docs: use `<button>` for dropdown/popover examples, explain preference over `<a>` for dropdowns, tweak collapse prose

### LINKED ISSUE #37426: Enhance dropdown link examples
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

[Dropdown documentation > Single Button](https://getbootstrap.com/docs/5.2/components/dropdowns/#single-button) shows the example of the dropdown link which uses `<a>` instead of `<button>`.

```html
<a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
  Dropdown link
</a>
```

IMHO I don't think of any use cases where it could be actual links.

As discussed with @patrickhlauke we might want to reinforce the idea (you can use it, doesn't mean you should).

We could add an info callout here but remove in all the documentation the examples where we use `<a>`s instead of `<button>`s.

### Motivation and context

Prefer the approach with buttons so this one is rather propagated in websites rather than the `<a>` approach.

### PR DESCRIPTION
**Pull request by patrickhlauke**
### Description

* Expand dropdowns prose to explain that `<button>` is recommended/preferred. Change subsequent example to use `<button>`
* Remove unnecessary `role="button"` from `<button>` elements in collapse unit tests
* Tweak modal examples to use `<button>` for popovers inside modal, and for the modal trigger itself
* Tweak the prose/explanation for the collapse component

### Motivation & Context

Closes https://github.com/twbs/bootstrap/issues/37426

### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

#### Live previews

- <https://deploy-preview-37432--twbs-bootstrap.netlify.app/docs/5.2/components/dropdowns/>
- <https://deploy-preview-37432--twbs-bootstrap.netlify.app/docs/5.2/components/modal/>

### CODE REVIEW

**Comment by julien-deramond** [comment]
The changes LGTM and make this part of the documentation clearer.

However I'm wondering it we shouldn't also modify the following things:
- There are two `<a class="dropdown-toggle"`s in [js/tests/unit/dropdown.spec.js](https://github.com/twbs/bootstrap/blob/main/js/tests/unit/dropdown.spec.js) that are not here especially IMO to test the behavior of links.
- There are some `<a class="dropdown-toggle"`s in [site/content/docs/5.2/examples/headers/index.html](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.2/examples/headers/index.html) and in [site/content/docs/5.2/examples/sidebars/index.html](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.2/examples/sidebars/index.html)
- There are tons of `<a class="dropdown-toggle"` used in combination with `.nav-link`. Don't we need to change them as `<button>`s and tweak the style? That's how we use them in our own doc header.

**Comment by patrickhlauke** [comment]
@julien-deramond sorry, wasn't quite finished with this. was just too tired last night, but wanted to at least make a start - hence the draft ;)

**Comment by julien-deramond** [comment]
> @julien-deramond sorry, wasn't quite finished with this. was just too tired last night, but wanted to at least make a start - hence the draft ;)

My bad. Hadn't seen the draft 😇

**Comment by patrickhlauke** [comment]
the dropdowns with `.nav-link` are currently stylistically problematic, yes.

taking https://getbootstrap.com/docs/5.2/components/navbar/#supported-content as an example, changing the control to `<button class="btn btn-link nav-link dropdown-toggle">...</button>` gets us close, but the vertical text alignment is off

screenshot of the navbar, with the dropdown using a button, with the text in the button not aligning with the other links

*that* is, i think, one of the main reasons why for some components/patterns, authors still use an `<a href="..." role="button">` at the moment...because the alternative just doesn't work out of the box

**Review by GeoSot — APPROVED** [review]

**Review by mdo — APPROVED** [review]
Nicely done!

**Pull request merged**
