### PR TITLE
Update jQuery version check and jQuery dependency version range

### LINKED ISSUE #16834: Bootstrap v3 is not compatible with jQuery 3.0
[jQuery 3.0 and jQuery Compat 3.0 Alpha Versions Released](http://blog.jquery.com/2015/07/13/jquery-3-0-and-jquery-compat-3-0-alpha-versions-released/)

I have not tested everything but Modals are broken because of this major change:

> #### Major changes
> ###### Simplified .show() and .hide() methods
>  If you have elements in a stylesheet that are set to display: none, the .show() method will no longer override that. So the most important rule for moving to jQuery 3.0 is this: Don’t use a stylesheet to set the default of display: none and then try to use .show() – or any method that shows elements, such as .slideDown() and .fadeIn() – to make it visible.

JSBin jQuery v1.11.1 http://jsbin.com/sokiyuzepi/1/edit?html,output
JSBIN jQuery v3.0.0 alpha http://jsbin.com/xuteferejo/1/edit?html,output

### PR DESCRIPTION
**Pull request by cvrebert**
Closes #16834.
CC: @XhmikosR @hnrch02 for review

### CODE REVIEW

**Comment by XhmikosR** [comment]
:shipit:

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 3f1377418a932ffed6deff9b52583e422b229e57
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/146311640
Docs preview: http://preview.twbsapps.com/c/${commitSha.sha}

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by hnrch02** [comment]
:shipit:

**Comment by YidingW** [comment]
:shipit:

**Comment by Martii** [comment]
Hate to be the bearer of some potentially bad news... but when we switch to jQuery 3.0.0 or 3.1.0 modal dialog boxes fail to launch in the UI. Works fine in 2.2.4 of jQuery.

**Comment by cvrebert** [comment]
@Martii Post a JS Bin testcase please.

**Comment by Martii** [comment]
I'm seeing if the "newer" props listed at http://v4-alpha.getbootstrap.com/components/modal/#live-demo would affect this. I'm not sure where it's failing between the dependency of *jQuery* and *boostrap* just yet but since I'm the maintainer for dep updates we haven't been able to migrate to v3.x of jQuery using bootstrap v3.3.6.

**Comment by Martii** [comment]
@cvrebert 
I also see the live demo link I reference is using an even older version jQuery... so that invalidates the success of the demo since it's not using v3.x.

Generated source for that url:
``` html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
```

**Comment by XhmikosR** [comment]
The docs aren't the latest from git. If you think you have an issue post a
jsfiddle.

**Comment by Martii** [comment]
@XhmikosR 
I prefer gists and one can just click the raw button... since you say the docs are invalid I have no real way of telling if we are missing a html property for jQuery 3.x compatibility... so the issue to be created would be to update the docs first so I can see if an attribute may be missing on our end. I can strip out the live demo source and update jQuery there and see if it works first which is the most logical course of action.

**Comment by XhmikosR** [comment]
Development doesn't happen on a live site. Use the appropriate git branch
to test the development progress.

On Jul 25, 2016 02:37, "Marti Martz" <notifications@github.com> wrote:

@XhmikosR <https://github.com/XhmikosR>
I prefer gists and one can just click the raw button... since you say the
docs are invalid I have no real way of telling if we are missing a html
property for jQuery 3.x compatibility... so the issue to be created would
be to update the docs first so I can see if an attribute may be missing on
our end. I can strip out the live demo source and update jQuery there and
see if it works first which is the most logical course of action.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/twbs/bootstrap/pull/20338#issuecomment-234810333>, or mute
the thread

**Comment by Martii** [comment]
@cvrebert 
Ah I see now... you are fixing the incompatibility using jQuery 3.x in this PR... e.g. the current release of *bootstrap* is a little too strict on a compatibility check and throws an error which makes it a flaw in *bootstrap*. Nice find/work btw and thank you. I will look forward to a *bootstrap* 3 release that has this issue fixed... and hopefully the documentation from the maintainers can reflect things a little better/recent in the future.

Ref:
``` sh-session
Timestamp: 07/24/2016 06:20:01 PM
Error: Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3
Source File: http://localhost:8080/redist/npm/bootstrap/dist/js/bootstrap.js
Line: 1
```

**Comment by cvrebert** [comment]
Manually confirmed (in OS X Chrome & Firefox) that the modals work fine with jQuery 3.1.0.

**Pull request merged**
