### PR TITLE
feat(css): add `.card-bg`

### PR DESCRIPTION
**Pull request by zalog**
I think this is a feature opposite to `.card-img-overlay` because the way that our `.card` height is computed.

So, in this pr, our card has:
- his parent height relative to content, not to image like `.card-img-overlay`
- a 100% width&height background on the back of the card body content

But, because our `.card` has more childrens than `.card-body`, I think we should introduce a new `+ .card-bg-overlay` or something like that.

What do you guys think?

Here we have a simple demo, and a [pen](https://codepen.io/zalog/full/oqgPJv/), of course :).

bootstrap card-bg

### CODE REVIEW

**Comment by andresgalante** [comment]
sorry :( Miss clicked on close while reviewing it

**Review by andresgalante — COMMENTED** [review]
Hey @zalog, thanks for the PR.

I think that what happens with the overflowing text on `.card-img-overlay` is a problem.

@mdo I know that on #24285 we decided not to take actions, but should we change `card-img-overlay` instead of introducing a new feature?

@zalog this PR will need docs if it gets merge

**Comment by zalog** [comment]
I'd vote too for not introducing a new feature, but I think that both cases are common. Perhaps, parent height computed by the childrens with text, are more common?

I can tackle whatever we decide.

**Comment by mdo** [comment]
Coming back to this real late. Any chance we can get a demo added to the docs? No sweat if not, I can add one myself after I review this. I agree that the overlay behavior is less than ideal currently.

**Comment by zalog** [comment]
Ok, I'll come back to this soon.

**Comment by XhmikosR** [comment]
@zalog: ping

**Comment by MartijnCuppens** [comment]
I think it's better to just use a background image for these scenarios (like @mdo mentioned here: https://github.com/twbs/bootstrap/issues/24285#issuecomment-337945556). We will still have the issue that the image will be stretched as long as we don't use `object-fit` (which we can't use because of IE we support).

**Pull request closed without merging**
