### PR TITLE
Update gems.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
I'm thinking, we could get rid of the redirect layout. It's only supposed to be seen when JavaScript is disabled.

**Review by Johann-S — APPROVED** [review]
I'm not the best in Ruby and you know our docs better than me 😄

**Comment by XhmikosR** [comment]
@mdo: what do you think about removing the redirect layout?

**Comment by mdo** [comment]
@XhmikosR If it's unused, remove it.

**Pull request merged**
