### PR TITLE
use callout without custom jekyll plugin

### PR DESCRIPTION
**Pull request by m5o**
* use callout without custom jekyll plugin

:link: https://github.com/twbs/bootstrap/pull/25319

### CODE REVIEW

**Review by mdo — APPROVED** [review]
It's more verbose, but I appreciate the removal of a plugin.

**Comment by m5o** [comment]
@mdo What do you think of write the trailing as an one-liner:

```liquid
{% endcapture %}{% include callout.html content=callout type="danger" %}
```

**Comment by XhmikosR** [comment]
@mdo: I'd like to review the build-related PRs, so please CC me.

I'll test this and the other one that I haven't tested and comment when I have some time.

**Comment by XhmikosR** [comment]
Haven't had the time to test this one and #25334, but have you seen any changes in build time?

I'm not sure what to expect since Ruby is just slow for some cases.

**Comment by m5o** [comment]
@XhmikosR Can I support or help you with something to push this thought the finish line?

**Comment by XhmikosR** [comment]
@m5o: I haven't forgot about it, I just haven't got the time to review your PRs yet.

Bear with me, and I'll get to it soon-ish :)

**Comment by m5o** [comment]
@XhmikosR I'am very close to present a solution to get rid of the last custom plugin for building the toc. This PR is currently blocking me. I have to do minor markup change in the callout includes and don't want to do it twice. Please don't forget me :o)

**Comment by XhmikosR** [comment]
I won't. But personally, I'm against dropping the Jekyll plugin for TOC.

We will never build on GH automatically so it makes no sense. What it makes sense is to try to speed things up if possible.

**Pull request merged**
