### PR TITLE
Separate container classes from `$enable-grid-classes` option

### LINKED ISSUE #34933: Switching to CSS Grid should keep container classes
The optional CSS grid introduced in version 5.1.0 does not include container classes. I think that the best solution to this issue is to create a separate option _$enable-containers_ because sometimes developers don't need any kind of grid but need containers.

### PR DESCRIPTION
**Pull request by mdo**
Fixes #34933.

This introduces a new global option, `$enable-container-classes`, to separately toggle the inclusion of `.container-*` classes in our compiled CSS. Our containers are still useful when opting into the new CSS grid layout, so we don't want to exclude those when flipping over.

### CODE REVIEW

**Review by ffoodd — APPROVED** [review]
LGTM 👌

**Comment by XhmikosR** [comment]
@mdo is this supposed to go into 5.1.2 or 5.2.0? The linked issue is added in 5.1.2, that's why I'm asking.

**Comment by rromanchuk** [comment]
@mdo i'm sort embarrassed but maybe this is related.  After enabling this option to play with css grids, i'm trying to just reproduce any standard grid example, with css grids, hello world level stuff. 


```scss
$enable-grid-classes: false;
$enable-cssgrid: true;

@import 'bootstrap/scss/bootstrap';
```
After i enabled I thought i had a sass compiler/config error, because the page looks like a style reset. But then noticed the css grids were indeed working.

I've been searching the internet for an hour trying to find an actual `<html>` document with `$enable-cssgrid: true;`  just as a sanity test.  Just snippets, snippets everywhere

```html  
<div class="grid">
  <div class="g-col-4">.g-col-4</div>
  <div class="g-col-4">.g-col-4</div>
  <div class="g-col-4">.g-col-4</div>
</div> 
```

It would be really nice if there was an index.html like https://getbootstrap.com/docs/5.1/examples/starter-template/ with `$enable-grid-classes: false;` `$enable-cssgrid: true;`   Sounds like i just lost my `.container` selector and i've been trying to re-invent them with grid classes lol

**Comment by rromanchuk** [comment]
I just made the edit in `_containers.scss` ....  🤣 🤣 🤣 🤣   I'm going pretend the last the last hour never happened.   I was close to a full existential crisis just framing 3 divs with breakpoints

**Pull request merged**
