### PR TITLE
Improvements to stateful button JS docs

### PR DESCRIPTION
**Pull request by cvrebert**
- Mark stateful button feature as deprecated.
- Document that `$(...).button('reset')` is async; addresses #16362.

### CODE REVIEW

**Comment by HEdingfield** [comment]
Sorry to ask here, but I couldn't find the info anywhere else: why is the stateful button being deprecated and what's it being replaced with? I use these pretty extensively...

**Comment by cvrebert** [comment]
See the thread mentioned in the commit message, but to add some more detail:
The feature doesn't do very much, there are some reasonable edge cases that don't seem possible to satisfy simultaneously, and it complicates the implementation of the main checkboxes/radios part of the buttons plugin. It will not have a replacement; it's being straight-up removed in Bootstrap v4. We recommend writing your own tiny trivial snippet of JavaScript instead.

For the avoidance of doubt: We intend to retain the rest of the buttons plugin (checkboxes, radios, single-toggle) in v4.

**Comment by scottdorman** [comment]
@cvrebert With this piece of the buttons plugin being removed in v4, are there any recommendations for a replacement that we can use now instead of using what's currently in v3?

**Comment by heralder99** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

heralder@naver.com 님께 보내신 메일 <Re: [bootstrap] Improvements to stateful button JS docs (#16430)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by cvrebert** [comment]
> *We recommend writing your own tiny trivial snippet of JavaScript instead.*

**Pull request merged**
