### PR TITLE
Examples: Remove unnecessary `id`/`aria-labelledby` from cheatsheet accordions

### LINKED ISSUE #37591: Accordion: Missing role on `.accordion-collapse` ?
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I don't really what's the best here, but I think we should either add a `role="region"` or remove our `aria-labelledby="*"` from our `.accordion-collapse`.

### Motivation and context

There is one reason that made me think of this, and several things that make me struggle on the solution to choose, I'll try to present them here.

### Reason

Some observations on aXe DevTools inside my browser. It raises this:
image

### Add `role="region"`

I must admit that my heart is going to this solution since W3C seems to recommand it in their example page ([here](https://www.w3.org/WAI/ARIA/apg/example-index/accordion/accordion.html)). 

That said, it seems that several front-end framework/design system encourage to use this solution everytime such as [Material Angular](https://material.angular.io/cdk/accordion/overview) and [Adobe](https://opensource.adobe.com/spectrum-css/accordion.html).

As an alternative maybe we could use a `<section>` as well as in [Aditus](https://www.aditus.io/patterns/accordion/).

### Remove `aria-labelledby="*"`

On the other side, I could find several sources on web that doesn't implement the `role="region"`. I feel like it's more personal projects, but there are also some front-end frameworks that display it such as [Getuikit](https://getuikit.com/docs/accordion).

If we remove this one, maybe we should add a paragraph to mention that this role depends on the content whether it's significant or not ?

### PR DESCRIPTION
**Pull request by patrickhlauke**
### Description

Explicit labelling (which then would also benefit from a `role="group"` or similar role) is only optional, and not really appropriate just for a cheatsheet

https://www.w3.org/WAI/ARIA/apg/patterns/accordion/

### Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

#### Live previews

- https://deploy-preview-37718--twbs-bootstrap.netlify.app/docs/5.3/examples/cheatsheet/

### Related issues

Closes #37591

### CODE REVIEW

**Review by ffoodd — APPROVED** [review]
Makes sense!

**Comment by louismaximepiton** [comment]
Thanks a lot for introducing this to Bootstrap ! Should I try to backport it to the documentation as well ?

**Comment by patrickhlauke** [comment]
@louismaximepiton don't think there's any need, as the documentation doesn't do that, nor does it mention it at all. it's out of scope for having any lengthy explanation.

**Comment by patrickhlauke** [comment]
oh, balls, the docs actually do it. i missed it when doing a find/replace though, which is worrying. sorry, i'll get a PR to fix the docs themselves as well.

**Pull request merged**
