### PR TITLE
Bump `$dark` to `$gray-900`

### PR DESCRIPTION
**Pull request by ffoodd**
On the road to #30548 , trying to increase contrasts wherever `$dark` is used.

https://deploy-preview-30550--twbs-bootstrap.netlify.com/docs/5.0/utilities/colors/

FWIW, I really prefer this.

### CODE REVIEW

**Review by MartijnCuppens — APPROVED** [review]
`$gray-900` is the same color as the text color, makes sense to switch. WOuld like to have another approval from @mdo for this.

**Comment by mdo** [comment]
I believe I made it 800 because then the border could be 900. This thought was fleshed out more thoroughly in #30342. I could pull those border/bg utils changes from there and push them to a new PR?

**Comment by MartijnCuppens** [comment]
> I could pull those border/bg utils changes from there and push them to a new PR?

Yup, any reasons not to continue with this then?

**Comment by ffoodd** [comment]
Friendly ping @mdo :)

**Comment by Lightingtalks** [comment]
> On the road to #30548 , trying to increase contrasts wherever `$dark` is used.
> 
> https://deploy-preview-30550--twbs-bootstrap.netlify.com/docs/4.3/utilities/colors/
> 
> FWIW, I really prefer this.

**Comment by mdo** [comment]
Would the color contrast issues be moot with #30468? I'd like to leave the gray as-is for now as I'm trying to find the right balance of background and border utilities.

**Comment by ffoodd** [comment]
@mdo Should be in cases where we generate both background and color—however, it'll be by using black instead of gray (meaning we should fallback to black more frequently).

We may merge (or at least check again) the other one first. It might worth not bumping this gray and prefer to ensure there's no isolated component using gray  inappropriately?

**Comment by mdo** [comment]
> We may merge (or at least check again) the other one first. It might worth not bumping this gray and prefer to ensure there's no isolated component using gray inappropriately?

👍

**Comment by mdo** [comment]
Screw it, let's :shipit: :D.

**Review by mdo — APPROVED** [review]
Slating for Alpha 3!

**Comment by ffoodd** [comment]
Great 🎉

**Pull request merged**
