### PR TITLE
Use consistent arrow class

### LINKED ISSUE #28028: Popover/tooltip arrow class names are not consistent
For the arrow inside of the popover, the `.arrow` class is used, while `.arrow` isn't a standalone component. We don't do that anywhere else in our css. A better name would be something like `.popover-arrow`. This will be something we can look in to for `v5`, since this is a breaking change.

Edit: We should do the same with the tooltips.

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This changes the name of the `.arrow` class to:
- `.popover-arrow`
- `.tooltip-arrow`
for arrow and tooltip respectively.

Fixes #28028

Thanks!

### CODE REVIEW

**Comment by XhmikosR** [comment]
This is a breaking change, shouldn't go in 4.3.

**Comment by Johann-S** [comment]
I agree with @XhmikosR

**Comment by XhmikosR** [comment]
@Johann-S @MartijnCuppens actually this PR targets the no jQuery branch which will be a major version bump.

**Comment by XhmikosR** [comment]
But being it has changes from v4-dev, we need the jQuery branch to be rebased against the latest v4-dev first and then this one.

**Comment by MartijnCuppens** [comment]
Yup, that's why I added the `v5` and `on-hold` labels

**Comment by XhmikosR** [comment]
We can merge this if the no jQuery branch is rebased.

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
