### PR TITLE
docs: use the `twitter` Jekyll variable everywhere

### PR DESCRIPTION
**Pull request by wenzhixin**

### CODE REVIEW

**Review by XhmikosR — CHANGES_REQUESTED** [review]
Thanks but there are a few more cases in getting-started/introduction.md

**Comment by wenzhixin** [comment]
OK, I will update all cases.

**Comment by wenzhixin** [comment]
Done

**Comment by XhmikosR** [comment]
Thanks!

**Review by XhmikosR — APPROVED** [review]

**Pull request merged**
