### PR TITLE
generalize dropdowns / drop role="menu"

### PR DESCRIPTION
**Pull request by patrickhlauke**
as `role="menu"` is a very specific (and strict) ARIA pattern for
desktop-like application menus, and our dropdowns are often used
as pure navigation dropdowns, this change abandons ARIA menus for
a more open-ended and light-weight approach
(see http://heydonworks.com/practical_aria_examples/#submenus and
http://www.w3.org/WAI/tutorials/menus/flyout/#improve-screen-reader-support-using-wai-aria)
note that in dropdown.js, switched to now target `.dropdown-menu`
instead of `role["menu"]` - this also prevents bootstrap scripts
from "bleeding" into non-bootstrap components on the same page.
also removed the `role=["listbox"]` part, which appears to be
vestigial/unused (only place in bootstrap that uses that
role are carousels, and their key handling is done separately)

for further context, see also discussion on #16179

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 5fd7bc1554d492bdd5794d35fce515fe951439a6
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/65057753

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by patrickhlauke** [comment]
to be clear, the dropdown.js script will still work if a dev manually wants to add all the `role="menu"` stuff to their markup (because they ARE actually making a desktop-like web application where the menu contains actions, rather than links/navigation). this change only generalizes the script (so it looks for `.dropdown-menu` rather than `role"menu"`). however, for clarity in the documentation examples, it assumes the more common use case of developers using dropdowns for navigation.

**Comment by yatil** [comment]
BTW: Some description on the challenges of using application menus are described on this [W3C Menus tutorial page](http://www.w3.org/WAI/tutorials/menus/application/).

**Comment by mdo** [comment]
Nice! Love the simpler markup without all those attributes. Also, don't forget to at this to the ship list @patrickhlauke <3.

**Comment by patrickhlauke** [comment]
@mdo already added to shiplist after i merged it :)

**Comment by mdo** [comment]
Oh shit what, totally missed that reference <3. Sorry!

**Comment by patrickhlauke** [comment]
:+1: :shipit:

**Pull request merged**
