### PR TITLE
Clean up v4 printing documentation

### PR DESCRIPTION
**Pull request by davidjb**
Replace inline html with markdown, rewording, and cleanup.

### CODE REVIEW

**Comment by cvrebert** [comment]
Hmm, looks like we lost the Chrome workarounds at some point somehow. Will have to check whether that was intentional or not.

**Comment by cvrebert** [comment]
Looks like it got derped up in 86af1f39abbff7ef06b94d23951408ca27f81cdc when manually merging from v3 into v4.

**Comment by cvrebert** [comment]
Merged as c9f5f13fd9bde4b745bf135478750cbe1a97a834.
Thank you!

**Comment by davidjb** [comment]
Awesome, I thought I remembered reading those workarounds.

**Pull request closed without merging**
