### PR TITLE
Fix: avoid ignore plain text in input-group-$size

### LINKED ISSUE #29605: form-control-plaintext ignores input-group-$size
Bug reports must include:

- macOS 10.14.6 (18G95)
- Chrome Version 77.0.3865.120 (Official Build) (64-bit)
- Compare the difference here:

```html
<div class="container">
  <div class="row">
    <div class="col">
      <div class="input-group input-group-sm">
        <div class="input-group-prepend">
          <button class="btn btn-primary">Button</button>
        </div>
        <input class="form-control" value="hello world" readonly />
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="input-group input-group-sm">
        <div class="input-group-prepend">
          <button class="btn btn-primary">Button</button>
        </div>
        <input class="form-control-plaintext" value="hello world" readonly />
      </div>
    </div>
  </div>
</div>
```

You'll see that the `.form-control-plaintext` has issues with both width and sizing. The fix is to add `.form-control-sm` to `.form-control-plaintext`.

### PR DESCRIPTION
**Pull request by mendozagioo**
Fixes #29605

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
Issue: https://codepen.io/MartijnCuppens/pen/dyPoOKM
Fix: https://codepen.io/MartijnCuppens/pen/KKwpNBx

It seems the inputs aren't aligned due to the border. Is this issue also present in master?

**Comment by ysds** [comment]
@MartijnCuppens Dropped in #28972

**Comment by mendozagioo** [comment]
Hey @MartijnCuppens, in master branch is worst, the input is out of line. The problem here is that `form-control-plaintext` class is considered just for remove border and color but not is considered to use like child of `input-group` class. The fix, just it add `form-control-plaintext` class to be used inside of `input-group` class

**Comment by MartijnCuppens** [comment]
This PR need some additional tweaks to fix the issues with the border. Not sure if it's worth fixing this if we drop this if we drop this in master anyway.

\CC @twbs/css-review

**Comment by mdo** [comment]
> This PR need some additional tweaks to fix the issues with the border. Not sure if it's worth fixing this if we drop this if we drop this in master anyway.

It is indeed not worth it :).

**Pull request closed without merging**
