### PR TITLE
Fix node_modules path

### PR DESCRIPTION
**Pull request by MartijnCuppens**
On the getting started with theming page http://getbootstrap.com/docs/4.1/getting-started/theming/#importing, the path to the `node_modules` folder is wrong.

This is the file structure:
```
your-project/
├── scss
│   └── custom.scss
└── node_modules/
    └── bootstrap
        ├── js
        └── scss
```

So if we start from `scss/custom.scss`, we need to add `../` to get to the `node_modules` folder.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Well, that's not always true because one might have added the parent folder in the includes.

That being said, I'm OK I guess.

**Comment by MartijnCuppens** [comment]
@XhmikosR, what do you mean? Is there a way this works with the proposed [file structure](http://getbootstrap.com/docs/4.1/getting-started/theming/#file-structure)?

**Comment by XhmikosR** [comment]
Yes it can work if you add the parent folder in the compiler's include
path. But anyway, the common thing would be your way for most people.

**Review by Johann-S — APPROVED** [review]
No concerns about that change

**Pull request merged**
