### PR TITLE
Nav Tabs use single variable to style `$nav-tabs-link-hover-border-co…

### PR DESCRIPTION
**Pull request by pat270**
…lor` and `$nav-tabs-link-active-border-color`

I think it's easier to customize Nav Tabs hover and active state if we can pass in the border colors through one variable instead of a few.

### CODE REVIEW

**Review by andresgalante — COMMENTED** [review]
Hi @pat270 Good point. I understand why mdo wanted to hide the option to change the border bottom, but sometimes users want to change the bottom border to be for example white and make the tab look open on hover. This PR gives more control to the user.

Would it make it easier to understand if we make the variables:

```scss
$nav-tabs-link-hover-border-color: $gray-200;
$nav-tabs-link-hover-border-bottom-color: $nav-tabs-border-color;
```

@mdo @pat270 What do you think?

**Comment by pat270** [comment]
Hey @andresgalante, I still favor the single variable because designers tend to change every aspect of a component. Personally, I don't think I will encounter many situations where I will only need to change the `border-bottom-color`, but I'm good with whatever you guys decide. Either fix makes it a lot easier to style via variables. Thanks!

**Review by andresgalante — APPROVED** [review]
@pat270 I agree, either way is good. Unless @mdo thinks a border bottom variable is better, I am ok to merge it this way.
Thanks a lot 😄

**Review by mdo — APPROVED** [review]
I can dig it

**Pull request merged**
