### PR TITLE
Replace Sass division with multiplication and custom divide() function

### LINKED ISSUE #34353: Sass / deprecation for branch 4
Sass / deprecation was fixed in branch 5.
Is the the deprecation expected to be resolved in branch 4 as well?

I know this means switching from libsass to dart, but there are projects that directly import bootstrap4 scss sources

_Originally posted by @castellinosoftware in https://github.com/twbs/bootstrap/issues/34051#issuecomment-868634798_

### PR DESCRIPTION
**Pull request by mdo**
Fixes #34353. Replaces #34386.

~~@XhmikosR I removed the RFS changes from that other PR for now. Want to take a stab at porting it to this branch?~~

- [x] Add RFS changes in separate commit

### CODE REVIEW

**Comment by XhmikosR** [comment]
@mdo it seems on v4-dev we are using rfs 8.x. I'll try to see if I can cut a new 8.x release with the Dart Sass fix and then push here any patches.

That being said, I recall we still had some issues with the rounding on main. Are those sorted? If not, I'd wait until we fix everything before backporting.

**Comment by mdo** [comment]
I think everything has been sorted? We may have lost 1-2 decimals but I haven't heard any rounding bugs since we shipped the last release.

**Review by ffoodd — DISMISSED** [review]
💪👌

**Comment by XhmikosR** [comment]
@mdo I created an upstream branch https://github.com/twbs/rfs/commits/v8.x. Feel free to backport the divide fix with a PR. Just keep in mind that in the upstream 8.x branch we don't test dart Sass.

**Comment by mdo** [comment]
Pulled the latest in from that branch, thanks @XhmikosR! Just rebased and force pushed. Should be good to go.

**Comment by arcanedev-maroc** [comment]
@mdo Is it ok using `0.5` instead of `.5` ? 

I think it's considered as a "good practice" and also we're used to see float numbers with a `0` before the dot :eyes:

**Comment by darrinmn9** [comment]
really sorry to nag/comment, is the only thing left on this fix to convert `* .{decimal} -> * 0.{decimal}` for these commits?

**Comment by mdo** [comment]
Stylistically, we don't include leading `0`s in any of our CSS values, so no need to revisit those :).

**Comment by evanfuture** [comment]
Hi, just wondering if this will move ahead, it's been getting stale, and it seems like an important thing.  I'll reference the above Merge request comment (from petrsiegl):

> There is minor problem with scss compilation and bootstrap. V4 bootstrap uses division symbol / which is deprecated in sass and causes warnings. The fix should be available soon (twbs/bootstrap#34571). Until it is merged, there will be unfortunately warnings on compilation. They can be silenced by sass --quiet flag, but that disables other warnings as well.

**Review by ffoodd — DISMISSED** [review]
LGTM, what would be missing now?

**Comment by XhmikosR** [comment]
@ffoodd This is NOT ready due to RFS,please do not approve things like that because I might then accidentally merge stuff :)

**Comment by ffoodd** [comment]
Latest comments involving RFS felt accurate and up-to-date :D What's missing?

**Comment by XhmikosR** [comment]
@ffoodd the backported version doesn't have the division fix. We need an upstream patch against the https://github.com/twbs/rfs/commits/v8.x branch.

**Comment by XhmikosR** [comment]
Someone needs to do the work and provide an upstream PR, because the patch cannot be cherrypicked unfortunately.

**Comment by cdubz** [comment]
Thanks @XhmikosR -- I have opened https://github.com/twbs/rfs/pull/421 to backport.

**Comment by XhmikosR** [comment]
@mdo do we need me to cut a new rfs 8.x version? It'd be nice to do, I just need to make sure we use the `previous` tag on npm. Then I will update this PR with the proper link to the upstream release.

**Comment by mdo** [comment]
@XhmikosR Yeah, let's cut a new minor release. Thanks!

**Comment by XhmikosR** [comment]
@mdo done https://github.com/twbs/rfs/releases/tag/v8.1.0 (and npm also as `previous`)

**Review by ffoodd — COMMENTED** [review]
Nice, thanks @cdubz for your invaluable help!

**Review by XhmikosR — APPROVED** [review]

**Comment by evanfuture** [comment]
Nice work all, it was a pleasure to keep track of this in the background.  Thank you!

**Comment by cdubz** [comment]
Thanks to everyone who helped with this! One follow up question I haven’t been able to figure out myself — are new versions of 4.x still released or would one need to use the `4.x-dev` branch to take advantage of this change?

**Comment by XhmikosR** [comment]
They are supported, we'll be in the next version.

**Comment by tmm1** [comment]
Any ETA on new 4.6.1 or 4.7.0?

**Comment by richardlawley** [comment]
As an FYI, upgrading to 4.6.1 caused me some issues in a project which also used Font Awesome 4.6.1, related to the use of the divide function introduced in this PR.  The symptom was that the compiled CSS output was containing font-size with the unit as "remrem", e.g.

```
.dropdown-header {
  display: block;
  padding: 0.5rem 1.5rem;
  margin-bottom: 0;
  font-size: 0.74375remrem;
  color: #6c757d;
  white-space: nowrap;
}
```

(NB, the sizes might be slightly different due to coming from my project with overridden font sizes, but the issue persists in a clean project too).

This problem has occurred because Font Awesome have borrowed an earlier implementation of your divide function (source for FA6 isn't public at the moment so I can't link to it, but it contains the license agreement from BS too), and depending on the order of including FA & BS files, one will redefine the function.

I think it's a bit dangerous defining a function with such a common name - especially with the current dart sass slash deprecation, you may well encounter other libraries becoming incompatible because of a globally namespaced function with a common name!

I've worked around this in my own project by including FA first (though this likely means that something in FA may break) and reported it as a FA bug since they borrowed code from here (https://github.com/FortAwesome/Font-Awesome/issues/18408)

**Comment by mdo** [comment]
Thanks for the heads up @richardlawley. Keep us posted if FA needs additional updates from us. Nothing about the deprecation has been ideal and has definitely soured my view of Sass (along with some other limitations we're running into). We'll aim to do better in each release and iron out some issues in v6 :).

**Pull request merged**
