### PR TITLE
Added a new style table-outer-bordered

### PR DESCRIPTION
**Pull request by stanleyxu2005**
Added a new style to add 1px border to table outer only. https://github.com/twbs/bootstrap/issues/15789

### CODE REVIEW

**Comment by kkirsche** [comment]
I would recommend a comment similar to what already exists so it is clear what this does.

E.g.:

```css
// Outer Bordered version
//
// Add borders around the outside of the table.
```

I would also recommend adding an example to the docs for this.

**Comment by stanleyxu2005** [comment]
@kkirsche I've updated code in my repository, but I have no idea how to update this PR. Could you kindly help me?

**Comment by kkirsche** [comment]
@stanleyxu2005 What you want to do is make the updates to stanleyxu2005/bootstrap in the patch-1 branch (https://github.com/stanleyxu2005/bootstrap/tree/patch-1). All changes made in the patch-1 branch will be automatically added to the pull request.

To switch branches, in the bootstrap directory on your machine type:
```shell
git fetch
git checkout patch-1
```

Online through Github's site you'd want to make sure you are in the correct branch with this button:
screen shot 2015-02-12 at 11 40 22 am

Hope this helps

**Comment by stanleyxu2005** [comment]
@kkirsche Ops. Maybe I should start it over...

**Comment by kkirsche** [comment]
You merged patch-1 into itself. If you did your changes in master, you would need to merge master into patch-1

**Comment by cvrebert** [comment]
No biggie, we can easily fix the commit on our end. The important question is whether or not @mdo wants this feature.

**Comment by mdo** [comment]
We won't be adding any new features or variations to existing ones in v3. Maybe come v4. Thanks though!

**Comment by sanspace** [comment]
@mdo @cvrebert @stanleyxu2005 Was this included in v4? I couldn't find it in the docs.

**Pull request closed without merging**
