### PR TITLE
Enabled ESLint and JSCS in Hound

### PR DESCRIPTION
**Pull request by ameya-pandilwar**
Fix for #19114
Closes #19299

### CODE REVIEW

**Comment by ameya-pandilwar** [comment]
@XhmikosR - I am always running into problems while rebasing. I sync the fork but whenever I rebase my feature branch, I somehow screw up. I would appreciate if you could tell me the exact steps to **fetch and rebase**

**Comment by XhmikosR** [comment]
```
git rebase - origin/v4-dev
```

Assuming you have set up upstream right.

**Comment by XhmikosR** [comment]
@cvrebert: If we have the checks in hound, shouldn't we stop checking those in Travis? It doesn't take long, sure, but it's just duplicate tasks.

**Comment by cvrebert** [comment]
Meh. Hound's support for ESLint & JSCS is still in beta. And what if Hound got shut down or became flaky?
(My feelings aren't strong, but anyway that's my 2¢.)

**Comment by cvrebert** [comment]
@ameya-pandilwar Merged as 122d9e5. Thanks!
Also, for future reference, utilizing https://help.github.com/articles/closing-issues-via-commit-messages/ in commit messages is preferred.

**Pull request closed without merging**
