### PR TITLE
Adjust `SAFE_URL_PATTERN` regex for use with test method of regexes.

### LINKED ISSUE #33124: <img> inside HTML tooltip is only displayed every other hover.
Reproduction:

https://jsfiddle.net/3k4cL51w/

Steps:

The `Test` button has a tooltip with `data-bs-html="true"` on it and an `` tag in the title. When you hover your mouse multiple times over the button, you will see that the the image in the tooltip will only be shown every other hover.

I tested this on Ubuntu 20.04 on Firefox and Chromium.
It worked on 5.0 beta 1, the issue only started appearing after I upgraded to 5.0 beta 2.

### LINKED ISSUE #33134: Add CSP URLs to the docs & more details for other CSP implementation methods
https://github.com/twbs/bootstrap/pull/32832

https://github.com/twbs/bootstrap/issues/25394

PR 32832 provides a section for CSP in the docs but it is lacking CSP URLs developers could plug into their code to enable bootstrap assets. 

For anybody who wants to see the results of that documentation PR 32832 here is the online version:

https://getbootstrap.com/docs/5.0/customize/overview/#csps-and-embedded-svgs

With this documentation PR 32832 there is no reference to CSP URLs that you can plug into your CSP configurations or where in the CSP configurations to put them (script-src, frame-src, etc). You are just linking to the code documentation page for each element?

I was hoping bootstrap could provide something like this:

https://content-security-policy.com/examples/

https://stripe.com/docs/security/guide#content-security-policy

https://developers.google.com/recaptcha/docs/faq#im-using-content-security-policy-csp-on-my-website.-how-can-i-configure-it-to-work-with-recaptcha

Using bootstrap provided CSP URLs and plugging them in is much easier than locally hosted assets, inline images, etc. CSP provided URLs is by far the easiest and quickest way to get CSP protection for your site. 

Following what Stripe and Google does in this case is a best practice by providing bootstrap provided CSP URLs to the public to handle the assets for you. 

I wouldn't know where to begin on where to actually download the images/svgs from and then figure out where to put them locally and then how to reference them in my code. There is no guidance for how to do that in the current docs. Maybe add more details for developers who may want to reference them locally or provide more details on some of the other methods like inline images in addition to using bootstrap provided CSP URLs. Because some developers might want to change the colors of the assets or change the asset images altogether or something.

### PR DESCRIPTION
**Pull request by nikonthethird**
Recently, the method used to check attributes in the sanitizer has been switched from `match` to `test`.

The `test` method on regexes however behaves different than the `match` method on strings in the presence of the global modifier (g).
See [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test) for an example where the same input returns true, then false.

This modifier causes issues when the same template is sanitized multiple times, which happens when hovering over tooltips containing an `` tag for example.

This PR also adds a unit test for sanitizing the same template twice.

This fixes #33124.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Thank you for catching this and for adding a test case too!

That's a recent regression, and must also apply to v4-dev, so I'll backport it manually after this lands.

I'll take a closer look later today.

**Comment by XhmikosR** [comment]
@nikonthethird your patch totally makes sense. But just to be safe, I don't suppose we could have any other issues? Not sure why the regex had the global flag specified in the first place...

**Comment by XhmikosR** [comment]
BTW I feel like we should report this to eslint-config-xo. It shouldn't have auto-fixed the regex since it had the global flag.

**Comment by nikonthethird** [comment]
@XhmikosR, yes, the global flag should not have been on the regex from the start, I agree.

The regex was copied from Angular 7 according to the source comment above it, and [Angular still has the regex with the global flag on it](https://github.com/angular/angular/blob/8b0cccca457801aa57427effc28c3dfe6b037c29/packages/core/src/sanitization/url_sanitizer.ts). But they are using the `match` method.

**Comment by XhmikosR** [comment]
Yeah, agreed. Thanks for the clarification and especially for the test case.

I'll merge it and backport it to v4-dev in the next days. 4.6.0 isn't affected since I landed this after releasing it.

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
Ah, it seems that we don't fully cover the sanitizer in the v4-dev branch.

@nikonthethird could you have a look at backporting this manually and adding a test there too?

**Comment by nikonthethird** [comment]
@XhmikosR ok, I'm on it.

**Pull request merged**
