### PR TITLE
Added sizing and spacing based on viewport

### PR DESCRIPTION
**Pull request by galczo5**
Solution for https://github.com/twbs/bootstrap/issues/26779

### CODE REVIEW

**Comment by XhmikosR** [comment]
Please make sure all CI is green.

**Comment by galczo5** [comment]
I'm not sure what I should do. I've added some scss and output size check failed. Should I change value of check value or try to minimalize my code?

**Comment by XhmikosR** [comment]
Yeah, then maybe this shouldn't be added at all. Or if we do really want this feature we will bump the limits.

**Comment by mdo** [comment]
Thanks, but I've turned this down before and will do so again. We don't need responsive variations for everything and this just adds too much CSS.

**Comment by galczo5** [comment]
No problem :) I've been thinking about this for few hours today and you guys have right. In bootstrap there is too many utilities.

**Pull request closed without merging**
