### PR TITLE
Fix color-adjust with autoprefixer 10.4.6

### PR DESCRIPTION
**Pull request by amirhossein-karimi**
autoprefix, updated, and having trouble `color-adjust`.

[autoprefixer respository change log](https://github.com/postcss/autoprefixer/blob/main/CHANGELOG.md)
[developer.mozilla print-color-adjust description](https://developer.mozilla.org/en-US/docs/Web/CSS/print-color-adjust)

### CODE REVIEW

**Review by mdo — APPROVED** [review]

**Comment by zlach** [comment]
This is still broken for me

**Comment by mbrodala** [comment]
@zlach What does this mean exactly?

**Comment by zlach** [comment]
> @zlach What does this mean exactly?

Oh, sorry, I just meant that after doing an npm install bootstrap on my React project (node v16.15.0) I still get a warning on npm start

`WARNING in ./node_modules/bootstrap/dist/css/bootstrap.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/bootstrap/dist/css/bootstrap.css)
Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning

(2482:3) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.

webpack compiled with 1 warning`

**Comment by jrochkind** [comment]
Thanks! Any chance of a backport to Bootstrap 4 as a bugfix?  

This is mainly an issue for autoprefixer complaints, but it's very annoying, and I'm not sure if there's a good way for bootstrap 4 users to work around with a local override.

**Comment by peterlobster** [comment]
I'm with @zlach. After applying the patch, the error kept coming up...

```
[vite:css] Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
```

**Comment by mbrodala** [comment]
Well, the fix simply wasn't relased yet. :sweat_smile:

**Comment by lapc18** [comment]
The issue is still happening... No matter workarounds, it kept the warning.

**Comment by lapc18** [comment]
To fix it temporarily:

1. Remove your "node_modules" folder
2. Remove your "package-lock.json" file
3. Add to your "package.json" file: `
"overrides": {
    "autoprefixer": "10.4.5"
  }
`
4. Finally, run: `npm i --save-exact`



Some details:

- React version: `^18.1.0`
- Bootstrap: `^5.1.3`
- cra-template: `npx create-react-app my-app --template typescript`
- Node version: `v16.14.2`
- NPM version: `8.6.0`
- env: `macOS Monterey v12.3.1 | intel processor`


Hope it works for u!

**Comment by andrewnleon** [comment]
These steps did the trick for me as well thanks dude
Remove your "package-lock.json" file
Add to your "package.json" file: "overrides": { "autoprefixer": "10.4.5" }
Finally, run: npm i --save-exact

**Comment by rodrigo-arias** [comment]
@Aminat-Okunuga thanks for this fix, any plans to replicate it for Bootstrap 4?

**Comment by Magiccamera** [comment]
Add to your "package.json" file: "overrides": { "autoprefixer": "10.4.5" }
Finally, run: npm i --save-exact
npm ERR! Override for autoprefixer@^10.4.7 conflicts with direct dependency
changed to: "overrides": { "autoprefixer": "^10.4.7" }
installs fine, but still get autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
Somewhat irritated may abandon using react bootstrap altogether, I only wanted it for the Navbar

**Comment by zulnam** [comment]
Hi. Any eta on when 5.2.0 is being released? Workaround doesn't seem to work for me.

**Pull request merged**
