### PR TITLE
.collapsing.width animation

### PR DESCRIPTION
**Pull request by zalog**
Animation on x-axis for `.collapse.width` elements.
Demo: http://codepen.io/zalog/pen/KMWRwL

### CODE REVIEW

**Comment by cvrebert** [comment]
Please explain in more detail.

**Comment by zalog** [comment]
Of course. If we use div.collapse.width then the js animation will move on width. By default it's on height.
Please take a look at this demo: http://codepen.io/zalog/pen/KMWRwL

I hope it helps :)

**Comment by twbs-lmvtfy** [comment]
Hi @zalog!

You appear to have posted a live example (http://codepen.io/zalog/pen/KMWRwL.html), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 10, column 3: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 12, column 3: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by zalog** [comment]
Of course. If we use div.collapse.width then the js animation will move on width. By default it's on height.
Please take a look at this demo: http://codepen.io/zalog/pen/KMWRwL

I hope it helps :)

**Comment by mdo** [comment]
Nice, I really want to see this added to Alpha 4. It'll need a new class and some docs, but I can tackle that soon I think.

**Comment by zalog** [comment]
@mdo any news here?
Need some help?

**Comment by mdo** [comment]
@zalog I don't recall exactly what was in my head last time I peeped this. Biggest thing that'd help get this merged though is some docs and a live example of it in action. Otherwise I have to pull it down, document it, etc myself (which means I'll get to it only after v4 fully ships :p).

**Comment by zalog** [comment]
I rebased this branch and made some changes on my old [pen](https://codepen.io/zalog/pen/KMWRwL).

Questions related to that pen:
- I'm not sure what use cases we shoud document in our bootstrap documentation. Please take a look at my pen on the "Fluid child collapse" example. That's a natural dynamic expectation... but definitly not look good at all :)
- Do you think we should put an effort on "Navbar width collapse"? It's the only use case that I can think about related to `.collapsing.width`.
Please do not get in deep on this, it's just quick sketch.

The js file, collapse.js, was ready for collapsing width: [here](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/collapse.js#L53) and [here](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/collapse.js#L269). Perhaps we can get some ideas and feedback from who wrote that piece of code :)

**Comment by andresgalante** [comment]
Hi @zalog, this is a good idea but animating `height` and `width` is not performant since they requiere a repaint.

`transform` scale3D will not only avoid the repaint but also trigger hardware accelation

**Comment by zalog** [comment]
@andresgalante thanks&agree, we don't want repaint.

I think we have to come with a solution that does not resize the content, like [here](https://codepen.io/brundolf/full/evvdYM/). I'll think about it.

**Comment by andresgalante** [comment]
@zalog something I've done is to trigger a fade and then a scale. So, first we fade the content and then we scale the container. If times are sync smartly it looks good.

I don't know if it'll work here or how to implement it, but it's an idea :)

**Comment by XhmikosR** [comment]
Closing since this is not the most performant solution.

**Pull request closed without merging**
