### PR TITLE
Fix logo alignment for IE

### PR DESCRIPTION
**Pull request by MartijnCuppens**
The stack logo is misaligned in IE because IE doesn't handle `height: auto` all too well. With `preserveAspectRatio` we can align the SVG content within, which looks the same visually.

I also added a fix for newlines being added by IDEs each time an SVG is edited.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Can you try adding `align-items-center` to the parent row? IE shows the image shrunk and I believe it will look better this way as long as we can make IE behave.

From my quick testing the only way I found to make IE work is to add width and height in the CSS, but this might break responsive.

**Comment by XhmikosR** [comment]
Oh, and the newlines patch shouldn't be in this branch nor in the repo IMO. Not all SVG files are minified completely.

**Comment by MartijnCuppens** [comment]
> Oh, and the newlines patch shouldn't be in this branch nor in the repo IMO. Not all SVG files are minified completely.

Webstorm (and probably other IDEs) automatically respects the `.editorconfig` and add a EOF newline on save. So whenever I want to edit the SVGs I need to temporary disable it.

> Not all SVG files are minified completely.

Could be, but adding this won't do harm in any case.

**Comment by XhmikosR** [comment]
>Could be, but adding this won't do harm in any case.

True, but I'd rather have the newlines at the end for the files that are not completely minified. I can add a `chomp` or `trim` around the SVG includes in Hugo to remove any newlines anyway.

Either way this change does not belong in this branch.

**Comment by Maruda1986** [comment]
x

**Review by ysds — APPROVED** [review]
LGTM in the case.

**Comment by MartijnCuppens** [comment]
Dropped the newlines patch

**Pull request merged**
