### PR TITLE
add center-table class to center a table

### PR DESCRIPTION
**Pull request by bcullman**
center-block won't center a table, wrapping a table with a div with class center-block also does not center a table.

This is because center-block sets display:block. For tables, this needs to be display:table

Create center-table class here that can be used to center a table.

### CODE REVIEW

**Comment by supergibbs** [comment]
What about instead adding a `table.center-block` selector that overrides the `display` property? Then `.center-block` just works instead of adding more class names.

**Comment by cvrebert** [comment]
We're no longer accepting new features into Bootstrap v3. But please feel free to open a PR for this against the [`v4-dev`](https://github.com/twbs/bootstrap/tree/v4-dev) branch for Bootstrap v4. Thanks!

**Comment by bcullman** [comment]
Since display:block no longer applies, it seems somewhat misleading to use a class called "center-block"

**Comment by cvrebert** [comment]
Superseded by #17580.

**Pull request closed without merging**
