### PR TITLE
Shipping v3.4.0

### PR DESCRIPTION
**Pull request by mdo**
Oh hey, it's been awhile since we shipped a v3.x release. While it's no longer our focus with v4 being out and stable, we can still get some wins by shipping some quality of life updates. Here's what's included in this update.

- 29f9237, 13bf8ae fixed XSS issue in Alert, Carousel, Collapse, Dropdown, Modal and Tab components.
- 48f1482 added a `.row-no-gutters` class.
- 7011e27 removes the double border on `<abbr>` elements.
- 1802075 adds some system fonts, though we may want to remove these considering the older browser and OS support.
- 4f4592c and subsequent commits reorganized the v3 docs CSS to use Less.
- 1d83280 added a dropdown to the docs nav for newer and previous versions.
- 059969b updates the docs to use a new baseurl, `/docs/3.4`, for that versioning life when we deploy to GitHub Pages.

There's a bit more in here yet, but those are the highlights thus far. Still have some more to come I think, but wanted to have this open for tracking purposes.

TODO:

- [x] Fix any 404s and useless redirects
- [x] Remove customizer's gist creation
- [ ] Fix docs search
- [ ] Verify everything is good with the builds
- [ ] Verify sourcemaps work
- [ ] Fix Browser tests
- [ ] Rebase the branch against master

### CODE REVIEW

**Comment by XhmikosR** [comment]
@mdo: do we want CI to pass?

If so, I'll have a look in the next days.

**Comment by XhmikosR** [comment]
@mdo: please make a dist here before merging.

**Comment by XhmikosR** [comment]
I made https://github.com/twbs/bootstrap/tree/v3.4.0-dev-rebased which is rebased. I haven't verified if all is good. But we could switch the PR to that branch if there's no issue.

**Comment by mdo** [comment]
Biggest blocker here is failing tests. Anyone have any insights? Been years since we've dug into this build tooling, but if we can figure that out, we can likely do a release.

**Comment by Johann-S** [comment]
@mdo there are unit test which fail on some browser, I'm on it

**Comment by XhmikosR** [comment]
Spent a few hours today, made some progress so we should have this soon :D

**Comment by XhmikosR** [comment]
TODO:

- [ ] Verify everything is good with the builds
- [ ] Something is wrong with the sourcemaps; each time I run the build task they get modified. My guess is we need to feed one of the tools the existent map files
- [ ] Rebase the branch against master
- [ ] Fix Browser tests

**Comment by Johann-S** [comment]
I have two unit tests which fail locally but I'm near the end too

**Comment by XhmikosR** [comment]
@mdo: docs search seems broken, at least locally.

**Comment by XhmikosR** [comment]
I backported my patches for search from v4 in my WIP v3 branch. There are some issues though:

* the index is for 3.4 which doesn't exit on Algolia
* the results might need some styling

**Pull request merged**
