### PR TITLE
Make check label cursor customizable

### PR DESCRIPTION
**Pull request by GaryPEGEOT**
Use a cursor pointer on custom form labels to indicate that the element is "clickable"

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
@patrickhlauke, is this a good idea?

**Comment by patrickhlauke** [comment]
this is a constant debate. by default browsers don't show do it. this would be an opinionated change. 
we already had lengthy back and forths about setting `cursor:pointer` for buttons, and in the end resorted to making a new variable for it. we could create a new variable, or rename/expand the current `$enable-pointer-cursor-for-buttons` to cover more "browsers don't normally do this, but it's clickable, so we're forcing a different cursor". but i personally wouldn't go for this, as some users may fear that clicking on the label when it shows a hand cursor may actually take them somewhere else/out of the form altogether (like it's a link or something)

**Comment by GaryPEGEOT** [comment]
> 
> 
> this is a constant debate. by default browsers don't show do it. this would be an opinionated change.
> we already had lengthy back and forths about setting `cursor:pointer` for buttons, and in the end resorted to making a new variable for it. we could create a new variable, or rename/expand the current `$enable-pointer-cursor-for-buttons` to cover more "browsers don't normally do this, but it's clickable, so we're forcing a different cursor". but i personally wouldn't go for this, as some users may fear that clicking on the label when it shows a hand cursor may actually take them somewhere else/out of the form altogether (like it's a link or something)

On the other hand, right now some user don't know they can click on the switch / checkbox, so an option might be interesting to let people decide if they want it to be displayed as a cursor, WDYT ?

**Comment by patrickhlauke** [comment]
there's a lot of things users don't know ... there's a fine line between helping users vs diverging too much from what browsers do by default on all other sites...

there's no right or wrong around this question (despite strong opinions one way or another like https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b) ... so having a variable strikes a certain balance at least

**Comment by GaryPEGEOT** [comment]
@patrickhlauke  what's the prefered way? Create a new variable or rename & expand the current one?

**Comment by MartijnCuppens** [comment]
I wouldn't use a new `$enable-*` variable here but just add a `$custom-control-cursor` variable which is `null` by default.

**Comment by XhmikosR** [comment]
This targets the wrong branch.

**Comment by GaryPEGEOT** [comment]
> 
> 
> This targets the wrong branch.

Ok, so which one should I use ? (It's my first "contribution")

**Comment by XhmikosR** [comment]
The master branch is the default branch.

**Comment by GaryPEGEOT** [comment]
> 
> 
> The master branch is the default branch.

@XhmikosR neither the file nor the class exist on the master branch.

**Comment by XhmikosR** [comment]
Maybe this is only v4 specific then. In that case I'd say I'm against it since it can be a breaking change.

**Comment by GaryPEGEOT** [comment]
@XhmikosR the default value is null, as of the actual behavior, so I don't see how it is a BC.

**Comment by XhmikosR** [comment]
Yeah, I already edited my comment.

**Comment by mdo** [comment]
Custom forms are no longer custom in v5, which is why these styles don't appear there. They're all consolidated into the default form controls so we have a single set of forms. I'm good with the null variable here.

**Comment by XhmikosR** [comment]
@mdo: does this patch apply in master, though?

**Review by MartijnCuppens — APPROVED** [review]
Let's do this

**Pull request merged**
