### PR TITLE
Drop `color()`, `theme-color()` & `gray()` functions 

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Drop `color()`, `theme-color()` & `gray()` functions  in favor of variables. The functions just called a `map-get()` of a map where just the variables were defined. 

Also the `theme-color-level()` now accepts any color you want instead of only `$theme-colors` colors. The first value now is a variable instead of the `$theme-colors` key.

TODO:
- [x] Document breaking change in migration guide
- [x] Rename `theme-color-level()` to `color-level()`

https://deploy-preview-29083--twbs-bootstrap.netlify.com/docs/4.3/getting-started/theming/

### CODE REVIEW

**Comment by mdo** [comment]
> Also the `theme-color-level()` now accepts any color you want instead of only `$theme-colors` colors.

Should this function be renamed to `color-level()` then?

**Comment by MartijnCuppens** [comment]
> Should this function be renamed to color-level() then?

Definitely

**Comment by ysds** [comment]
@mdo Do you have any plans for #28268?

**Comment by mdo** [comment]
@ysds Yes, I would like to see that come back. The idea isn't to provide those classes to everyone though—just the variables and functions. The classes are purely there for docs presentation.

**Comment by ysds** [comment]
@mdo OK, thanks 👍 

@MartijnCuppens Can you confirm the changes in the `migration.md`? Other than that, LGTM!

**Comment by MartijnCuppens** [comment]
Yup, it looks ok

**Review by ysds — APPROVED** [review]

**Comment by MartijnCuppens** [comment]
I just spotted some unwanted changes in `migration.md`, gonna fix that first

**Pull request merged**
