### PR TITLE
Enable stylelint for Hound

### LINKED ISSUE #24225: Fix Hound Sass checking
- [x] We probably need to disable `scss` since we are using stylelint now
- [ ] Hound doesn't work with our stylelint config, see #24234

~I already contacted the Hound people; we might be doing something wrong or their stylelint implementation doesn't work for Scss files. If it's the later we'll need to move away from Hound (at least) for scss files.~ Already did this.

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #24225

### CODE REVIEW

**Comment by XhmikosR** [comment]
I'm not sure if this is even needed.

/CC @gylaz

**Comment by XhmikosR** [comment]
@gylaz: see here the error that Hound is throwing? I was right to assume that Hound's stylelint config doesn't cover Scss checking.

**Comment by gylaz** [comment]
@XhmikosR I opened https://github.com/houndci/linters/pull/157 to add `stylelint-config-recommended-scss` plugin. Is there any other plugin you anticipate will be needed?

**Comment by XhmikosR** [comment]
@gylaz: thanks! I think we need more packages for scss linting to work, at least in our case here.

https://github.com/twbs/bootstrap/blob/347b3ac1c01ee9996daf542fb816a7dc34923d8a/package.json#L108-L112

**Comment by XhmikosR** [comment]
Scratch that, spoke too soon. I think your PR adds the only missing package. :)

**Comment by XhmikosR** [comment]
Thanks @gylaz!

**Comment by gylaz** [comment]
@XhmikosR I just deployed the new plugin and re-ran checks for this PR. Looks like there's a config error?

**Comment by XhmikosR** [comment]
I think it's the other issue I mentioned yesterday. Your stylelint packages
are old. Can you update all of them ?

**Comment by gylaz** [comment]
Opened this PR: https://github.com/houndci/linters/pull/159. Will report back once it's merged and deployed.

**Comment by XhmikosR** [comment]
@gylaz: isit normal we don't get any errors here even with all the plugins installed on Hound? Is it because the base branch v4-dev doesn't have Hound enabled?

**Review by Johann-S — APPROVED** [review]

**Comment by XhmikosR** [comment]
It worked!

**Pull request merged**
