### PR TITLE
Added justify-content evenly

### PR DESCRIPTION
**Pull request by ed1nh0**

### CODE REVIEW

**Comment by XhmikosR** [comment]
Same here, group your changes into one branch/PR.

**Comment by ed1nh0** [comment]
I was trying that, but...

```
remote: Permission to twbs/bootstrap.git denied to ed1nh0.
fatal: unable to access 'https://github.com/twbs/bootstrap.git/': The requested URL returned error: 403
```

**Comment by XhmikosR** [comment]
Yeah, that's not your fork, that's the upstream.

**Comment by ed1nh0** [comment]
My bad. I already fixed it. You can close this. Thank you.

**Pull request closed without merging**
