### PR TITLE
Make the tooltip-viewport example work

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @mdo @cvrebert

### CODE REVIEW

**Comment by cvrebert** [comment]
Won't this be relevant again once #17297 is fixed?

**Comment by XhmikosR** [comment]
Might be if that was the intention.
I know for sure that currently it's not linked from any page nor it works
due to JS errors regarding tether.

**Comment by cvrebert** [comment]
Seems like it could at least be a good visual test, if not an example, once it's fixed.

**Comment by XhmikosR** [comment]
@cvrebert: I think I fixed it by just loading tether too. Please check.

**Comment by XhmikosR** [comment]
So, what should I do with this @cvrebert?

**Comment by cvrebert** [comment]
:ship: it.

**Pull request merged**
