### PR TITLE
feat: keep contrast on `.table-dark`

### PR DESCRIPTION
**Pull request by zalog**
In case we change `$body-bg` to a dark color, we have to keep table contrast relevant.

### CODE REVIEW

**Comment by mdo** [comment]
I think I'm good with this. The dark styles aren't straight up inverse/reverse of our body styles like some other places. Thoughts @andresgalante?

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
@MartijnCuppens: LGTY?

**Review by MartijnCuppens — APPROVED** [review]
Looks good!

**Comment by zalog** [comment]
Tnks for your time, guys.

**Pull request merged**
