### PR TITLE
V4 without jquery

### PR DESCRIPTION
**Pull request by aTable**
I was using the updated Alert docs as a guide and modernized the button, carousel and collapsible JavaScript docs. 

Working my way through them so I thought I'd create this PR to track progress

### CODE REVIEW

**Comment by Johann-S** [comment]
You chose the wrong target, your PR should target : `v4-without-jquery` not `v4-dev` and your local branch is outdated, please update and create a new PR thanks 👍

**Comment by aTable** [comment]
My mistake! Although can you be more specific? I knew something wasn't right but it was late at night..

image

I thought this was the correct target. And did you want me to merge v4-dev into v4-without-jquery?

**Comment by Johann-S** [comment]
Can you rebase your branch please ? Or can you create a new PR from `v4-without-jquery` up to date ?

Because currently I can't merge your PR because of there are irrelevant commits

**Comment by aTable** [comment]
How's this looking now? =)

**Comment by Johann-S** [comment]
It's the same

image

you made just one commit, not 62 😆

**Review by Johann-S — DISMISSED** [review]
you have to use `git rebase` to update your local branch

**Comment by aTable** [comment]
> Or can you create a new PR from v4-without-jquery up to date ?

Can you clarify what you want? I thought I did this but looks like I'm wrong.

**Comment by Johann-S** [comment]
@aTable if you followed this to create your PR: https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md#pull-requests

You created a `upstream` remote, so to update your branch you have to do:
```shell
git pull upstream v4-without-jquery --rebase

**Comment by XhmikosR** [comment]
Rebased

**Comment by aTable** [comment]
The assistance is much appreciated. Thanks

**Pull request merged**
