### PR TITLE
Add side modals

### LINKED ISSUE #24718: Drawer, sidebar, offcanvas nav
Does the navbar in BS4 have an option whereby the hamburger menu slides from right to left, also pushing the content to the left too, instead of top to bottom?

### LINKED ISSUE #27033: Feature request: side Modals
I was recently working on a project where I themed a Bootstrap modal as a side drawer. I made an implementation that is compatible with the modal sizing classes. Maybe this is something that's nice to have in Bootstrap by default?

Demo: https://codepen.io/MartijnCuppens/pen/OwwjWV?editors=1100

ezgif-2-21a3fc9652

PR incomming...

### PR DESCRIPTION
**Pull request by mdo**
This PR adds two new modifier classes to our `.modal` component, `.modal-left` and `.modal-right`. It uses these two classes to create offcanvas drawers for navigation, content, and more. I've included two slightly different examples for now: a nav component and a list group component. I'm thinking a new example (perhaps a sidebar shopping cart or additional dashboard layout) could help show more of this off, too.

Still needs more work, but wanted to capture the idea from comments in #29017.

**Source:** https://bootstrap-menu.com/detail-modal.html by @vosidiy

Fixes #27033, fixes #24718.

---

**Demo:** https://deploy-preview-31285--twbs-bootstrap.netlify.app/docs/5.0/components/modal/#sidebar-modals

Screen Shot 2020-07-12 at 10 50 47 AM

---

This could also probably be backported—thoughts?

TODO:

- [ ] Allow customizing side modals transition?
- [ ] Nuke the off canvas example or adapt it to use this solution?
- [ ] Fix the right padding issue

### CODE REVIEW

**Comment by alecpl** [comment]
Bug: For me on Firefox the right-side modal has `padding-right: 16px` (for page scrollbar).

These look like a common mobile menus, so it's probably good to have them. However, I once build a multi-level menu system based on popovers, which are imo better suited for that than modals. On desktop it looked like normal popover, but on phones it was styled to look like your `.modal-right` (with some javascript to add backdrop layer, etc.).

**Comment by polRk** [comment]
SCROL BUG on iOS.

**Comment by michael-roth** [comment]
I found the following differences compared to Offcanvas component (#29017), I guess there should only be one in the future?

Maybe this is helpful for your decision.

**Bottom**
- no implementation of bottom Modal yet

**Backdrop**
- backdrop is animated in Modal component but not yet in Offcanvas
- disabling backdrop for Modal works with data-backdrop="false" but body is not scrollable nor otherwise interactive
  - Offcanvas has option: data-body="scroll" and the page can be used as if the Offcanvas were not open

**Layout**
- Modal has its own header and footer

**JS**
- Offcanvas does not have a dispose method

**Nesting**
```
Bootstrap only supports one modal window at a time. 
Nested modals aren’t supported as we believe them to be poor user experiences.
```
- Only one Offcanvas can be opened at the same time as well but that is an open point in https://github.com/twbs/bootstrap/pull/29017#issuecomment-551128164 (4.) I think

**Comment by mdo** [comment]
With some updates, this is ready for review. I've fixed the right side modal glitch (transition was choppy, solution was separate `.modal-right.show` and `.modal-right.fade` declarations) and added examples of a slide-in and a fade.

Scroll bug on iOS is an existing bug with modals.

Firefox, not seeing an issue on latest for macOS.

**Comment by mdo** [comment]
Thinking I’d like to try to backport this to v4.

**Comment by XhmikosR** [comment]
Pushed a few updates, I will squash/clean up the patches later. One thing I notice is that when closing the sidebar, it's closed immediately; the transition seems off a bit.

**Review by ffoodd — DISMISSED** [review]
LGTM

**Comment by XhmikosR** [comment]
I still don't think this is ready due to my comment above :/

**Comment by ffoodd** [comment]
You're right, I've been to quick on trying this.

**Comment by XhmikosR** [comment]
BTW there is a white thingy at the bottom on mobile. Can also be seen when long pressing in the overlay area

**Comment by mdo** [comment]
@MartijnCuppens @ffoodd Should we rename these classes to `.modal-start` and `.modal-end` ahead of the RTL feature shipping?

**Comment by ffoodd** [comment]
I guess so, if we all agree with logical class names in RTL PR.

**Comment by mrlife** [comment]
@mdo Do you think backport will make the cut for 4.6?

**Comment by MartijnCuppens** [comment]
Just checked this and it looks like the padding issue (https://github.com/twbs/bootstrap/pull/31285#issuecomment-657991512) is still present.

**Comment by HamedFathi** [comment]
Please consider the `Bottom` side too. It helps us to simulate `Material BottomSheet` too.
To be honest, [Offcanvas as component](https://github.com/twbs/bootstrap/pull/29017) was complete and amazing. In contrast, this issue is much more incomplete.

**Comment by XhmikosR** [comment]
I don't know if #29017 is a breaking change, it probably is due to at least the `z-index` change. Otherwise, I'm in between this myself.

#29017 feels like a cleaner solution, we are not mixing up the components. I will try to rebase #29017 in the next days; it probably won't be too easy because we have landed a few breaking changes already, but it's worth a try.

**Comment by HamedFathi** [comment]
@XhmikosR 

> #29017 feels like a cleaner solution, we are not mixing up the components.

We are on the same page. #29017 really is a perfect and reliable component.

**Comment by rohit2sharma95** [comment]
Found padding-right in the right modal here: https://deploy-preview-31285--twbs-bootstrap.netlify.app/docs/5.0/components/modal/#sidebar-modals

That creates unnecessary space on the right side.

space-in-right-modal

**Google Chrome** - Version 87.0.4280.66 (Official Build) (64-bit)
**Ubuntu** - 20.10

**Comment by ghiscoding** [comment]
@rohit2sharma95 I see this too, it is actually caused by the scrollbar width and mine is thicker and so my margin is worst than yours. I'm not sure if this is intended, probably not.

**Comment by Gaslan** [comment]
When the right modal opened `modal-open` class is added to body and body's overflow is set to `hidden`. So there is no need to add right-padding to modal because scrollbar is not seen when modal is opened.

**Comment by vanillajonathan** [comment]
The classes are currently named `.modal-left` and `.modal-right`. Should they be named that, or should they be named `.modal-start` and `.modal-end` instead? #32330 #30980

**Comment by XhmikosR** [comment]
Closing this one on favor of #29017.

**Pull request closed without merging**
