### PR TITLE
New Theming docs page

### LINKED ISSUE #22891: _custom.scss alternatives
Now that `_custom.scss` has been remove in https://github.com/twbs/bootstrap/pull/22821, I wonder how builds with custom colors and the likes could be made. My build so far was

1) Clone `twbs/bootstrap` to a temporary location
2) Copy my `_custom.scss` into the `scss` directory
3) Run npm build scripts
4) Copy the compiled .css and .js files to my project

The PR mentions it was nuked "in favor of relying on imports from package manager directories" but I have a hard time following? Anyone care to explain?

### PR DESCRIPTION
**Pull request by mdo**
This new docs page is intended to answer questions for where to put custom CSS (see #22891), how to customize and extend Sass maps and variables, and more. Ideally it'll replace the Options page. Much more still to come, but would love early feedback.

Closes #22891.

### CODE REVIEW

**Comment by mdo** [comment]
Still needs something to solve #23418 and #23450.

**Comment by tkuther** [comment]
I think the new doc isn't clear enough at this part:

> For example, to modify an existing color in our `$theme-colors` map, add the following to your custom Sass file:
> ￼ $theme-colors: (
> ￼   "primary": $red,
> ￼   "danger": $orange
> ￼ );

Where in my custom.scss would I put this? If I put this before the `@import bootstrap/scss/variables;` I also need to define $red and $orange first (because they are defined in _variables.scss which I import later on)

If I put it after the `@import bootstrap/scss/variables;`, $red and $orange are defined, but my $theme-colors override won't work because it's !default in _variables.scss which requires it to be redefined before the import.

**Comment by mdo** [comment]
@tkuther Does the variable section cover that for you? Might just need another link to refer back to that section to connect Sass maps to that section since it's not immediately clear maps and variables are connected.

https://github.com/twbs/bootstrap/blob/0071bf52798515877bf1797e4332a11d92f1f7bb/docs/4.0/getting-started/theming.md#L62-L79

**Comment by tkuther** [comment]
@mdo it does cover it, sure.

I'm just saying the example isn't clear because it reads "add following to your custom Sass file", but it actually requires two lines more to get it working that way. A link back to the variable defaults section would be enough to make it more clear, or even provide a full example like
```
$red: #f44336;
$orange: #ff9800;

$theme-colors: (
￼ "primary": $red,
￼ "danger": $orange
￼ );
```
I guess that could avoid some head scratching.

**Comment by mdo** [comment]
Moved away from those variables—they were meant to pull from the included color variables in Bootstrap, but I can see the confusion. Moved to hex values.

**Pull request merged**
