### PR TITLE
v5: Tweak some colors

### PR DESCRIPTION
**Pull request by mdo**
Attempts to make green and cyan more accessible. Here's current/old and the new from this PR:

old

new

You'll also note I was playing with some padding and border-radius here. Might still share that soon.

### CODE REVIEW

**Comment by patrickhlauke** [comment]
could also go the other way with the green, with black text and something like #43CB62 ?

i like the cyan

**Review by MartijnCuppens — APPROVED** [review]
Looks neat!

**Comment by XhmikosR** [comment]
I think we should mention the change in migration and assuming everyone is fine with the new green it should be good to go :)

**Review by ffoodd — APPROVED** [review]
♥️

**Pull request merged**
