### PR TITLE
Update package.json.

### PR DESCRIPTION
**Pull request by XhmikosR**
1. Use the same jQuery version in jspm
2. Update the files to only include the source and dist folders

Rationale: the end user doesn't need to run our tests or anything; they just get the src and dist files.

### CODE REVIEW

**Comment by mdo** [comment]
I can't recall anything specific, but based on the contents of the `files`, I feel like there's been an assumption that we should have the build files in our packaged content. We'll want to be careful about making this change for folks. Maybe we ask for more input?

**Comment by XhmikosR** [comment]
The thing is, that it's pretty hard to keep this working right.

Whoever wants to build using our scripts should get the git source. The npm package is just for the dist files.

We could try keeping this sort of working, but not everything worked before (docs and any scripts that depend on it, etc), but IMO it's just cleaner this way.

**Review by Johann-S — APPROVED** [review]

**Comment by XhmikosR** [comment]
So, what do we do with this? I still believe this is the right approach instead of a half butchered solution we have now.

**Comment by bardiharborow** [comment]
> The thing is, that it's pretty hard to keep this working right.

Indeed, but IIRC the few times we've broken building from the npm package, a flood of users have come out of the woodwork to complain. I don't really have an opinion either way about removing tests, but `.babelrc`, `.eslintignore`, `js/.eslintrc.json` and `build/` doesn't seem like too much of a overhead for the userbase that'd we'd be disturbing by removing this. It kind of like `_custom.scss` all over again, where any movement from us will end up breaking someone's workflow, and is that really worth it? Thoughts?

**Comment by XhmikosR** [comment]
Their workflow should not have depended on our scripts. This is honestly
the first time I see such an issue.

You use an npm package, you use your scripts.

It's not a matter of overhead here. It's a matter of things being broken
and no one noticing because, like i said, it's something non-standard.

**Comment by mdo** [comment]
I think I'd prefer to leave it for now and we can get some input from folks.

**Comment by XhmikosR** [comment]
I'm sorry, but I'll have to insist. Currently, it's broken. And it's just bad practice.

```

C:\Users\xmr\Desktop\package>npm test

> bootstrap@4.0.0-beta.2 test C:\Users\xmr\Desktop\package
> npm-run-all dist js-test docs-compile docs-lint bundlesize


> bootstrap@4.0.0-beta.2 dist C:\Users\xmr\Desktop\package
> npm-run-all --parallel css js


> bootstrap@4.0.0-beta.2 css C:\Users\xmr\Desktop\package
> npm-run-all --parallel css-lint* css-compile* --sequential css-prefix* css-minify*


> bootstrap@4.0.0-beta.2 js C:\Users\xmr\Desktop\package
> npm-run-all js-lint* js-compile js-minify


> bootstrap@4.0.0-beta.2 css-lint-docs C:\Users\xmr\Desktop\package
> stylelint --config build/.stylelintrc --syntax scss "assets/scss/*.scss" && stylelint --config docs/4.0/examples/.stylelintrc "docs/**/*.css"


> bootstrap@4.0.0-beta.2 css-lint C:\Users\xmr\Desktop\package
> stylelint --config build/.stylelintrc --syntax scss "scss/**/*.scss"


> bootstrap@4.0.0-beta.2 css-compile C:\Users\xmr\Desktop\package
> node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 scss/bootstrap.scss dist/css/bootstrap.css && node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 scss/bootstrap-grid.scss dist/css/bootstrap-grid.css && node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 scss/bootstrap-reboot.scss dist/css/bootstrap-reboot.css


> bootstrap@4.0.0-beta.2 js-lint C:\Users\xmr\Desktop\package
> eslint js/ && eslint --config js/tests/.eslintrc.json --env node build/


> bootstrap@4.0.0-beta.2 css-compile-docs C:\Users\xmr\Desktop\package
> node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 assets/scss/docs.scss assets/css/docs.min.css

An output directory must be specified when compiling a directory
npm Rendering Complete, saving .css file...
Wrote CSS to C:\Users\xmr\Desktop\package\dist\css\bootstrap.cssERR!
 Wrote Source Map to C:\Users\xmr\Desktop\package\dist\css\bootstrap.css.map
code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@4.0.0-beta.2 css-compile-docs: `node-sass --output-style expanded --source-map true --source-map-contents true --precision 6 assets/scss/docs.scss assets/css/docs.min.css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap@4.0.0-beta.2 css-compile-docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xmr\AppData\Roaming\npm-cache\_logs\2017-11-07T05_39_50_653Z-debug.log
Rendering Complete, saving .css file...
Wrote CSS to C:\Users\xmr\Desktop\package\dist\css\bootstrap-grid.css
Wrote Source Map to C:\Users\xmr\Desktop\package\dist\css\bootstrap-grid.css.map
Rendering Complete, saving .css file...
ERROR: "css-compile-docs" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@4.0.0-beta.2 css: `npm-run-all --parallel css-lint* css-compile* --sequential css-prefix* css-minify*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap@4.0.0-beta.2 css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xmr\AppData\Roaming\npm-cache\_logs\2017-11-07T05_39_51_267Z-debug.log
ERROR: "css" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@4.0.0-beta.2 dist: `npm-run-all --parallel css js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap@4.0.0-beta.2 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xmr\AppData\Roaming\npm-cache\_logs\2017-11-07T05_39_51_435Z-debug.log
ERROR: "dist" exited with 1.
npm ERR! Test failed.  See above for more details.
```

**Comment by XhmikosR** [comment]
This is with the current v4-dev after doing `npm pack` and trying the pack in a new dir.

**Comment by Johann-S** [comment]
Just a comment ".babelrc" do not exist in our current repository, now it's `.babelrc.js` and this file shouldn't be shipped in our release because some of our user will try to compile our source files with our `.babelrc.js` which is a bad practice because they don't have for example the same build tools

**Comment by XhmikosR** [comment]
Yeah, exactly my point. No one should use our scripts directly from package.json.

**Comment by XhmikosR** [comment]
@mdo @bardiharborow: I will merge this later today or tomorrow.

It's the right thing to do and the previous solution shouldn't exist in the first place.

**Comment by Johann-S** [comment]
For example those issues are related to the presence of our `.babelrc` file in our distributed package :   
- https://github.com/twbs/bootstrap/issues/23662
- https://github.com/twbs/bootstrap/issues/23620

**Review by mdo — APPROVED** [review]

**Comment by mdo** [comment]
Add a note to the migration docs and the ship list highlights, please.

**Comment by pamtbaau** [comment]
The [Build tools](http://getbootstrap.com/docs/4.0/getting-started/build-tools/) docs explicitly mention the build scripts. Docs should be updated with alternatives.

**Comment by mdo** [comment]
I think at most we need to rewrite some of the text there to make it clear this is build tools for Bootstrap docs development. It’s clear to me, but maybe it needs some clarification. Nothing else content wise needs to change.

**Pull request merged**
