### PR TITLE
Migrate to SASS division

### LINKED ISSUE #34051: Sass deprecation warning: Using `/` for division is deprecated
dart-sass has deprecated `/` in favor of `math.div`. Compiling https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss now results with many sass warnings.

```
368 │ $navbar-padding-horizontal:        floor(($grid-gutter-width / 2)) !default;
    │                                           ^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss 368:43  @import

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($grid-gutter-width, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div
```

### PR DESCRIPTION
**Pull request by rohrlaf**
Fixes #34051

SASS will introduce a breaking change with Slash as Division: https://sass-lang.com/documentation/breaking-changes/slash-div

Running the migrator twice, as `_rfs.scss` contains nested division, will use the new functionality:

```sh
$ npx sass-migrator division **/*.scss
```

### CODE REVIEW

**Comment by XhmikosR** [comment]
Please read our contribution guidelines and don't commit any dist files. As for the `@use` change, @ffoodd @mdo we don't use it anywhere else right now.

**Comment by ffoodd** [comment]
If I recall correctly previous discussions, using `@use` will break Libsass compatibility, which is both a BC and a pain for most of our users.

**Comment by rohrlaf** [comment]
> Please read our contribution guidelines and don't commit any dist files. As for the `@use` change, @ffoodd @mdo we don't use it anywhere else right now.

Okaya, why not add them to `.gitignore`? As they were not ignored, I thought you might need them for distribution in the VCS.

> If I recall correctly previous discussions, using `@use` will break Libsass compatibility, which is both a BC and a pain for most of our users.

Totally forgot about this, you are right. `node-sass` is still quite popular and runs on LibSass. I will close this PR, as this is no real feasible fix for now.

**Comment by mmarton** [comment]
https://www.npmjs.com/package/node-sass

> Warning: LibSass and Node Sass are deprecated. While they will continue to receive maintenance releases indefinitely, there are no plans to add additional features or compatibility with any new CSS or Sass features. Projects that still use it should move onto Dart Sass.

keeping the source cross compatible with deprecated tools is nice, but blocks progress

**Comment by ffoodd** [comment]
@rohrlaf We want out dist files ton ne distributed and that's the simplest way. Discussions are still opened regarding this strategy but we already had plenty and always chose to keep this way.

@mmarton Well we work for out users, not for their tools. This Sass strategic change might help but we're not there yet.

**Pull request closed without merging**
