### PR TITLE
Update jQuery to v3.6.0.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@rohit2sharma95 this is a tricky one and not sure yet if it's a regression in jQuery or just a change due to the fix for https://github.com/jquery/jquery/issues/4382. Maybe we need to adapt these 2 tests? The breakage seems to occur only on IE, though.

**Comment by XhmikosR** [comment]
It seems to be a bug in jQuery v3.6.0, see https://github.com/jquery/jquery/issues/4859. Closing this for now.

**Comment by coliff** [comment]
Do you know if the jQuery 3.6.1 update fixes the issue?

**Comment by XhmikosR** [comment]
Judging by the linked issue milestone, this isn't fixed in 3.6.1...

**Pull request closed without merging**
