### PR TITLE
Added border-radius

### PR DESCRIPTION
**Pull request by yasinkocak**

### CODE REVIEW

**Comment by neilhem** [comment]
@yasinkocak why not add border-radius using variable `$enable-rounded: true`?

**Comment by cvrebert** [comment]
@neilhem It does save a line of code on each usage.

**Comment by cvrebert** [comment]
We already have this mixin, it's just in a different file:
https://github.com/twbs/bootstrap/blob/2db8b5f36d7517a43dd462c65dcabf26df859456/scss/_mixins.scss#L5

@mdo Is there a reason the `border-radius` mixin isn't in `mixins/_border-radius.scss` ?

**Comment by mdo** [comment]
Nope, I added those because I hate all the small mixin files we have and didn't feel like digging them up at the time several months ago :D.

**Comment by cvrebert** [comment]
Addressed in 3137eec3706e8d5d3b03d7943e0693d19e9c4791.

**Pull request closed without merging**
