### PR TITLE
Add callouts about using light colors ideally on a dark background

### PR DESCRIPTION
**Pull request by patrickhlauke**
would be even better to show those buttons on a dark background, but i assume that'd require a lot more logic behind the scenes (to only show the outline buttons that are contrasty enough against white on a white background, and the others on a dark background)

### CODE REVIEW

**Comment by ffoodd** [comment]
With #30044 merged a few days ago, it might be quite trivial to handle  backgrounds (but would require to use some kind of containers to apply backgrounds). However the callout **si* a good idea :)

**Review by ffoodd — APPROVED** [review]

**Comment by patrickhlauke** [comment]
Just realised we should probably do the same for https://v5.getbootstrap.com/docs/5.0/helpers/colored-links/ ... i'll add another commit here

**Comment by mdo** [comment]
Would be very nice to add a background element around them if needed based on the contrast colors. A callout like this feels unnecessary IMO, but I'm down for whatever.

**Comment by patrickhlauke** [comment]
let's do callout just now, and then somebody cleverer than me can work out how to do a conditional bit of light vs dark background

**Comment by XhmikosR** [comment]
@patrickhlauke this needs a manual backport, can you do it please and ping me?

**Comment by patrickhlauke** [comment]
@XhmikosR done - https://github.com/twbs/bootstrap/pull/32054

**Pull request merged**
