### PR TITLE
create mixin for .form-inline

### PR DESCRIPTION
**Pull request by andreiduca**
Move code from .form-inline class into .form-inline-layout() mixin in
less/mixins/forms.less so it can be safely used in less/navbar.less

Refs #19430

### CODE REVIEW

**Comment by cvrebert** [comment]
Please exclude the `dist/` and `docs/` files from your pull request.

**Comment by andreiduca** [comment]
Reverted dist/ and docs/. Sorry about that :)

**Comment by XhmikosR** [comment]
@andreiduca: please also squash the patches.

**Comment by mdo** [comment]
I'm inclined to punt on this for v3 as it's more than a critical bug fix—it's an architectural change that adds a new mixing and moves code across files.

**Comment by cvrebert** [comment]
Closing per @mdo.

**Pull request closed without merging**
