### PR TITLE
Add positions utilities class

### PR DESCRIPTION
**Pull request by CVarisco**
I apologize if I'm wrong yet. #19289

Utility class features.
Inspiration #18476

Thanks

### CODE REVIEW

**Comment by cvrebert** [comment]
CC: @mdo for review

**Comment by mdo** [comment]
These classes are in the wrong place. If you want, please open a new PR against the `_position.scss` utility file.

**Comment by CVarisco** [comment]
@mdo Sure! I will create a new PR !
Thanks 🙂

**Comment by bryankang** [comment]
@CVarisco @cvrebert @mdo 

For completeness, I suggest considering breakpoint infixes as done in [`_display.scss`](https://github.com/twbs/bootstrap/blob/v4-dev/scss/utilities/_display.scss). Use cases may be rare, but they do exist. It does feel a bit flunky since positioning is heavily reliant on `top|right|bottom|left` properties, so html and css seem a bit too coupled. What do you guys think?

**Comment by bryankang** [comment]
Also to be consistent with `_display.scss`, I believe it should be `.pos-static { position: static; }`. Ideally it would just be a `p`, but that could be mistaken for padding.

**Comment by CVarisco** [comment]
@bryanbraun 
I understand what you mean, I choosed `.pos-X` to don't write so much.
However, I will wait a little bit to get the best tip.
After that, I will create a PR 🙂

**Comment by StephenHogsten** [comment]
This was closed, but it doesn't look like the breakpoints classes were ever added.  Was there a reason this was left out, or was it just forgotten (or am I just missing something)

**Pull request closed without merging**
