### PR TITLE
Docs: (subjectively) nicer looking accordion example

### PR DESCRIPTION
**Pull request by patrickhlauke**
the use of `.btn-link` currently just looks a bit odd, subjectively (as in v5 we now force the underline to always be there, while in v4 at least it was only on hover/focus).
`.btn-light` seems more fitting

### CODE REVIEW

**Comment by patrickhlauke** [comment]
Current look in v5:

> accordion-current

After change:

> accordion-light

**Comment by ysds** [comment]
I suggest more additional classes :)
* Add a `p-0` to the `.card-header`
* Add a `p-3` and `rounded-0` to the button

Before:
image


After:
image

**Comment by patrickhlauke** [comment]
the example with more classes does look good. wonder though if it will obscure the point of the example?

**Comment by mdo** [comment]
There's a PR to make a dedicated accordion component at #30042. Maybe we explore that?

**Comment by XhmikosR** [comment]
I think this PR with the suggestions @ysds made is good to land way before #30042

**Comment by patrickhlauke** [comment]
Added extra classes as suggested by @ysds

**Comment by patrickhlauke** [comment]
Also squeaked in a tiny clarification in the accessibility note there about what bootstrap doesn't support (the *optional* keyboard interactions)

**Comment by patrickhlauke** [comment]
any more thoughts on this?

**Review by mdo — APPROVED** [review]

**Pull request merged**
