### PR TITLE
Docs: fix old/broken example capture and typo

### PR DESCRIPTION
**Pull request by patrickhlauke**

### CODE REVIEW

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
@patrickhlauke feel free to push the wording change to my `v4-dev-xmr` branch :)

**Comment by patrickhlauke** [comment]
> @patrickhlauke feel free to push the wording change to my `v4-dev-xmr` branch :)

does that mean cherry-picking and then pushing? or do i need to do anything more involved / making a manual change? happy to, just want to make sure i don't mess it up.

**Comment by patrickhlauke** [comment]
oh...seems you may have already done it?

**Comment by XhmikosR** [comment]
Cherry picking doesn't always work so we do some stuff manually. I back
ported this already manually :)

**Pull request merged**
