### PR TITLE
Visual/manual test for checkbox/radio button kbd behavior

### PR DESCRIPTION
**Pull request by patrickhlauke**
Ref https://github.com/twbs/bootstrap/pull/19192

### CODE REVIEW

**Comment by cvrebert** [comment]
I had added a much-less-detailed test in https://github.com/twbs/bootstrap/commit/ad1e98d094468279da541de6b695681b169da8b3#diff-68e57df141d1c583e7dab6ee2784bd0d
Could you remove that old text as part of these changes?

**Comment by cvrebert** [comment]
Otherwise, LGTM.

**Comment by patrickhlauke** [comment]
sorry, i could have sworn i had done the fetch/merge dance before doing this. fixed now, removed your shorter explanation.

**Pull request merged**
