### PR TITLE
Refactor pagination classes to avoid tag selectors & child selectors

### PR DESCRIPTION
**Pull request by cvrebert**
Refs https://github.com/twbs/bootstrap/issues/17484#issuecomment-138061549

I'm open to better names for the classes. I used `.page` and `.page-link`.

TODO: Add notes to the v4 migration docs once we've settled on the exact class names.

### CODE REVIEW

**Comment by mdo** [comment]
More explicit classes here for the children elements would be much better—`.page` is too vague. The pattern we have in our nav classes right now is `.nav-item` and `.nav-link`, so perhaps we can utilize the `-item` part here?

**Comment by cvrebert** [comment]
So, `.pagination-item`, despite the slight verbosity?

**Comment by cvrebert** [comment]
@vsn4ik Erm, but the declarations inside the `.page-link { ... }` differ depending on which kind of child it is, so that consolidation doesn't seem valid, unless I'm missing something.

**Comment by cvrebert** [comment]
@mdo So, should I rename it `.pagination-item` despite the slight verbosity?

**Comment by cvrebert** [comment]
@mdo Okay, renamed to `.page-item`. Any further feedback?

**Pull request merged**
