### PR TITLE
Support jQuery v3 in Bootstrap v4

### LINKED ISSUE #19433: jQuery 3.0 in Bootstrap v4
As the title says, can you add support for jQuery 3.

### PR DESCRIPTION
**Pull request by cvrebert**
Fixes #19433.
CC: @hnrch02 @XhmikosR @patrickhlauke for review

---

TODO:
- [x] #20182
- [x] #20019

### CODE REVIEW

**Comment by XhmikosR** [comment]
Definitely like this!

I remember though, there were some issues with 3.x alpha. Do those still exist?

**Comment by XhmikosR** [comment]
On a side note, can't we use the slim version? We'd need to switch CDNs to jQuery's one for this though.

**Comment by cvrebert** [comment]
What is this slim version you speak of?

**Comment by XhmikosR** [comment]
https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/

Apparently, they haven't added it yet to downloads

**Comment by cvrebert** [comment]
I have no objection to switching to https://code.jquery.com/jquery-3.0.0.slim.min.js

**Comment by XhmikosR** [comment]
@cvrebert: so it seems the slim build is on Google CDN it's just not shown in the frontend.

https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.slim.min.js

**Comment by XhmikosR** [comment]
@cvrebert: you also missed `docs/assets/js/vendor/jquery.min.js`.

**Comment by cvrebert** [comment]
> I remember though, there were some issues with 3.x alpha. Do those still exist?

jQuery Team fixed https://github.com/jquery/jquery/issues/2828, and they backpedaled a bit on the breaking change to `.show()`/`.hide()`.
#20019 would apply to v4 too, but I'm not sure it's valid; I've asked for clarification.
All our unit tests pass, but obviously any further testing would of course be helpful.

I read through https://jquery.com/upgrade-guide/3.0/ and nothing else seemed applicable.
jQuery Migrate 3 (https://jquery.com/upgrade-guide/3.0/#jquery-migrate-plugin ) didn't flag anything when running the test suite.

**Comment by cvrebert** [comment]
> you also missed docs/assets/js/vendor/jquery.min.js.

Indeed, I'll add a note to regenerate the docs before merging.

**Comment by XhmikosR** [comment]
All right, so it seems we can merge this and check the slim build after that. For 3.x I guess we still need to stick to 1.x branch, right?

**Comment by cvrebert** [comment]
> you also missed docs/assets/js/vendor/jquery.min.js

Good catch. Fixed.

> For 3.x I guess we still need to stick to 1.x branch, right?

For the docs at least, yeah, because IE8.
Making 3.x compatible with 3.x (without changing the default) is #16834.

**Comment by cvrebert** [comment]
Looks like we still have some heisenbugs. There are [a couple failures on Sauce](https://travis-ci.org/twbs/bootstrap/jobs/140727666):
* https://saucelabs.com/jobs/ccea00610cc84b4ba60a5a9a3cbf8351
* https://saucelabs.com/jobs/f86f9002665a460a86e744b632a16be0

**Comment by XhmikosR** [comment]
Yeah, I saw those too but I thought it was just Saucelabs to blame.

Better wait until everything is sorted.

**Comment by cvrebert** [comment]
Ok, build is green after rebasing since #20198.

**Comment by cvrebert** [comment]
Since all the close buttons in the v4 docs use `<button>` instead of `<a>`, I think we can ignore #20019 for v4.
Does that sound good to folks?

**Comment by XhmikosR** [comment]
If that's true, it makes sense, yeah.

**Comment by XhmikosR** [comment]
Should I go ahead and make a PR with the slim version?

**Comment by cvrebert** [comment]
👍

**Pull request merged**
