### PR TITLE
Update dropdown.js to allow referenceElement

### PR DESCRIPTION
**Pull request by 719media**
This is in reference to

https://github.com/twbs/bootstrap/issues/24916

This allows for the dropdown to be affixed to any element, with the special considerations of "toggle" (default) and "parent".

### CODE REVIEW

**Review by Johann-S — APPROVED** [review]
LGTM 👍 

Any other feedbacks @XhmikosR or @bardiharborow ?

**Comment by XhmikosR** [comment]
I'm not familiar with Popper.js's API, so it's your call @Johann-S, as long as it's not a breaking change.

**Review by Johann-S — CHANGES_REQUESTED** [review]
few points : 
- Add a visual test in `dropdown.html` 
- Add an example in our documentation

**Comment by 719media** [comment]
I made an example for this and data-offset in the documentation. I wasn't sure how best to show an example of data-boundary or data-flip, so I did not do those

**Comment by Johann-S** [comment]
That's ok for the documentation part 👍 

But can you add a test in : https://github.com/twbs/bootstrap/blob/v4-dev/js/tests/visual/dropdown.html ?

**Comment by XhmikosR** [comment]
Please fix the lint errors too.

**Comment by 719media** [comment]
Visual test committed

**Review by Johann-S — APPROVED** [review]

**Pull request merged**
