### PR TITLE
Add back cursor: pointer for .btn-link

### PR DESCRIPTION
**Pull request by jeffbowen**
https://github.com/twbs/bootstrap/commit/232e86d0b4e1a4ff0dc3aa4e6d75c14a54fa8ac8 makes total sense but buttons with class `.btn-link` should still display a cursor.

### CODE REVIEW

**Comment by jeffbowen** [comment]
[CONTRIBUTING.md](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md) said to open PRs against master. If I should PR against v4-dev instead, let me know.

**Comment by Herst** [comment]
I did all my PRs which got accepted against `v4-dev` I guess `CONTRIBUTING.md` is outdated just like `README.md` was when [until recently it still mentioned people switching to Bootstrap 3](https://github.com/twbs/bootstrap/pull/23797).

**Comment by andresgalante** [comment]
@jeffbowen Do it to `v4-dev`

**Comment by Johann-S** [comment]
yes please open it on `v4-dev`

**Pull request closed without merging**
