### PR TITLE
Match `Backdrop` class name

### PR DESCRIPTION
**Pull request by liroyleshed**
Match class name `Backdrop`.

### CODE REVIEW

**Comment by XhmikosR** [comment]
There's another couple of instances in OffCanvas, please change those too.

**Comment by XhmikosR** [comment]
@liroyleshed just for the future, you do not need to close an existent PR, just update your branch...

**Comment by liroyleshed** [comment]
@XhmikosR Say thanks instead.

**Comment by liroyleshed** [comment]
@XhmikosR Rewrite your guidelines. Nobody owns you their fucking time.

**Comment by liroyleshed** [comment]
I'm starting an open-source competitor, everybody is welcome to join. ✌️❤️

**Comment by mdo** [comment]
@liroyleshed Throwing a peace sign and a heart there at the end seems pretty antithetical to your attitude in your previous two comments. @XhmikosR was just trying to be helpful, just as you are by contributing PRs. If a helpful suggestion sets you off like that, please do take your time and efforts elsewhere. ✌🏻❤️

**Pull request closed without merging**
