### PR TITLE
add responsive sizing

### PR DESCRIPTION
**Pull request by sabrown84**
Responsive Display Headings #22104

Is this what you mean @sunyang713 ?

### CODE REVIEW

**Comment by sunyang713** [comment]
not quite, your change decreases the sizes of the headings overall. I like how large they are when I’m on a desktop, but I’d like them to be smaller on mobile.

**Comment by sunyang713** [comment]
actually sorry I might be completely wrong. does ‘$display-size-base’ change with the size of the screen?

**Comment by sabrown84** [comment]
Yea I did change the overall size and place a base-sizing that changes with the screen sizes.

**Comment by mdo** [comment]
This doesn't make them responsive, it just makes them based on a particular variable. Responsive typography would mean we change the particular values of those variables based the viewport (e.g., `3rem` for `lg` and `2rem` for `md`).

For now, I'm going to say we pass on this change. I do think we need to improve the display headings, but probably not like this.

**Comment by sabrown84** [comment]
Ok I understand. Thank you.

**Comment by abdussami-tayyab** [comment]
What's the recommended way to fix this, for now?

**Pull request closed without merging**
