### PR TITLE
Rewritten scrollspy without jquery

### PR DESCRIPTION
**Pull request by alekitto**
Related to #23586

### CODE REVIEW

**Comment by alekitto** [comment]
@Johann-S any news on this?

**Comment by Johann-S** [comment]
@alekitto can you rebase please ?

**Comment by alekitto** [comment]
@Johann-S done, but I can't test it on IE at the moment

**Comment by Johann-S** [comment]
Did you take a look to our coverage code on the scrollspy plugin ? Is it greater than 80% ?

**Comment by alekitto** [comment]
Coverage reports 84.8% of lines covered

**Comment by Johann-S** [comment]
Thank you @alekitto 👍

**Pull request merged**
