### PR TITLE
Responsive sticky top

### LINKED ISSUE #28311: Sticky based on viewport
Would be lovely with the possibility to add the "sticky-top" class based on viewport.
Like for an example: sticky-top, sticky-sm-top, sticky-md-top, sticky-lg-top sticky-xl-top, and same for sticky-bottom.

Couldn't find this as a feature request, so here it is.

The good thing is, it wouldn't break any existing sites :)

### PR DESCRIPTION
**Pull request by jahanzaibsuleman07**
This is solution for creating responsive sticky top class which closes https://github.com/twbs/bootstrap/issues/28311.

Opened a new PR with a reference from a closed PR (https://github.com/twbs/bootstrap/pull/28352)

cc: @mdo @MartijnCuppens

### CODE REVIEW

**Review by MartijnCuppens — APPROVED** [review]
Looks good to me, need another approval just to be sure.

**Comment by ysds** [comment]
> need another approval 

from @mdo 😉

**Comment by jahanzaibsuleman07** [comment]
> Looks good to me, need another approval just to be sure.

sure, thanks!

**Comment by jahanzaibsuleman07** [comment]
> > need another approval
> 
> from @mdo

Sure, thanks @ysds.
@mdo : could you please review this PR? Thank you!

**Comment by XhmikosR** [comment]
Since bundlesize doesn't run for forked PRs, can someone check manually if bundlesize passes?

We need to fix this so that bundlesize runs in forks too.

**Comment by XhmikosR** [comment]
Nvm it's fine, I tested it manually. I'll add it in my TODO to see if we can run bundlesize in forks.

**Comment by MartijnCuppens** [comment]
Yeah, it looks fine

**Pull request merged**
