### PR TITLE
Update _utilities.scss with new .text-normal, .text-bold and .text-italic classes

### PR DESCRIPTION
**Pull request by racheldomingo**
I added a new section called Style, which has three new classes called text-normal, text-bold and text-italic (#18001)

### CODE REVIEW

**Comment by mdo** [comment]
Unsure about these—why not just use `<em>` or `<strong>` for those two?

**Comment by celluj34** [comment]
What if I want to programmatically change a text's styling? Can I change <em> to <span>? With classes I can just use jQuery.

**Comment by mdo** [comment]
What's the use case for changing those things? I can't think of many instances where I'd want to swap classes like that to affect only the weight or style (e.g., errors on form fields I could see doing bold and red, but that should be on the error class).

Personally I think this goes too far into utility classes.

**Comment by celluj34** [comment]
I disagree. I will concede that it's a 'slippery slope' type problem, e.g., where do you stop for utility classes.

However, you can't say that there's 0 use cases for something like this, when there are classes for `uppercase`, `lowercase`, and `capitalize`.

**Comment by mdo** [comment]
I never said there were 0 use cases—I said I can't think of many and asked for suggestions. I should've clarified why I closed this, but the slippery slope is the major reason.

**Comment by McGiogen** [comment]
We're using angular with bootstrap and this class could be really useful when you have an html block normal that you want style as italic or bold following the value of a variable.
Imagine you have 
```html
<div some-attributes>somelongandcomplexhtml</div>
```

Now you can do only
```html
<div ng-if="!isItalic" some-attributes>somelongandcomplexhtml</div>
<em ng-if="isItalic"><div some-attributes>somelongandcomplexhtml</div></em>
```

With those classes you should be able to write it more easily and readable as
```html
<div ng-class="{'text-italic': isItalic}" some-attributes>somelongandcomplexhtml</div>
```

**Pull request closed without merging**
