### PR TITLE
Added button subsection to the component section

### PR DESCRIPTION
**Pull request by vanillajonathan**

### CODE REVIEW

**Comment by patrickhlauke** [comment]
Lovely, thanks

**Comment by vsn4ik** [comment]
Already exist on 86 (90) line.

**Comment by vanillajonathan** [comment]
@vsn4ik You're right. Sorry, I missed that. The documentation on the website is outdated.

**Comment by patrickhlauke** [comment]
Oops, apologies for not checking this further and merging. I'll unmerge...

**Pull request merged**
