### PR TITLE
Update bundle.js in tests/integration

### PR DESCRIPTION
**Pull request by rohit2sharma95**
Use `Array.prototype.concat()` instead of direct spreading nodelist.

I am not sure if it should be done in [this file](https://github.com/twbs/bootstrap/blob/main/js/tests/integration/bundle-modularity.js) also @XhmikosR 

Ref: https://github.com/twbs/bootstrap/pull/32227#issuecomment-731785066

### CODE REVIEW

**Comment by XhmikosR** [comment]
@rohit2sharma95 good catch! Yes, please change the other instance too.

It seems I caused this regression [here](https://github.com/twbs/bootstrap/commit/46c037410b8c7eaab3cf50a5cf44093aa2fd41f4#diff-bca2597346dc6857e7359f8ae54bae1cf7b1ce3dfd87cf654c85478cdf681520) and never noticed it until a couple of days ago :/

What I don't get is why this worked when I changed the script to `dist/js/bootstrap.bundle.js`.

PS. Do you have an account on our Slack? If not, feel free to join and DM me :)

**Comment by rohit2sharma95** [comment]
Tooltip is working after you changed the path of the script because it is being initialized here:
https://github.com/twbs/bootstrap/blob/5a8cd9526d1e7098119b688632a974d29aba6b59/js/tests/integration/index.html#L67-L69 

And carousel seems working on my local machine 🤔

**Comment by rohit2sharma95** [comment]
It is being done in #31178 though
Ref: https://github.com/twbs/bootstrap/pull/31178#discussion_r512668334

**Comment by XhmikosR** [comment]
Yeah, but it shouldn't be sneaked it like that :)

I'd rather merge it separately. I'll have a look tomorrow.

**Pull request merged**
