### PR TITLE
Strip $ from copied shell commands.

### LINKED ISSUE #20800: "$" shell prompt should be excluded when using the docs' clipboard Copy buttons
Copying from the Docs shouldn't copy `$` for `npm install bootstrap@4.0.0-alpha.4` installation instructions.

### PR DESCRIPTION
**Pull request by bardiharborow**
Fixes #20800.

### CODE REVIEW

**Comment by mdo** [comment]
What if we instead used CSS to render the `$` at the beginning of the line with `::before`?

**Comment by patrickhlauke** [comment]
Alternatively, use `user-select:none` on the `<span>` around the $ ?

**Comment by patrickhlauke** [comment]
i.e. add this to _syntax.scss (assuming that class isn't used for other stuff)
```
.gp {
    color: #009;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

**Comment by bardiharborow** [comment]
@patrickhlauke, this is about the copy button, rather than manually selecting the text, however that suggestion will work if we go the `::before` path.

mdo, that would be a better solution, I was just taking the easy way out. I suspect I'll end up adding a `shell` flag of some kind to `highlight` that looks something like `.highlight-shell::before { content: '$', user-select: none; }`. I'll probably get around to this tomorrow.

**Comment by mdo** [comment]
> I suspect I'll end up adding a shell flag of some kind 

I think there's a class in there for the language that you can already utilize?

**Comment by bardiharborow** [comment]
@mdo, oh, yeah, duh. I've pushed a commit. However this causes problems on multi-line blocks like the [NuGet section](https://v4-alpha.getbootstrap.com/getting-started/download/#nuget), because I can't `::before` each line. Not sure where to go from here.

**Comment by bardiharborow** [comment]
@mdo, I've just split the NuGet section into two parts. It's probably not the ideal solution though.

**Pull request merged**
