### PR TITLE
v4 - fix html lint error on dashboard example page

### PR DESCRIPTION
**Pull request by dmbaughman**
Wrapping collapsible navbar contents with `<div id="navbar">...</div>` to satisfy the `aria-controls="navbar"` reference on the toggle button.

### CODE REVIEW

**Comment by dmbaughman** [comment]
Verified fix locally using `grunt htmlmin`.

**Comment by cvrebert** [comment]
CC: @patrickhlauke

**Comment by patrickhlauke** [comment]
Unless I'm missing something, that example is currently fundamentally broken anyway - I can't seem to actually have the hamburger menu appear at all. Looking at just the code though, I'd say that the `<div id="navbar">` should not include the `<a class="navbar-brand" href="#">Project name</a>`.

If this is just to satisfy the linter, I'd say take that link outside of the `<div>` and let's merge...but this will need revisiting/fixing properly.

**Comment by dmbaughman** [comment]
Yeah, I assumed that this example needs a lot of rework, but since I'm not sure what it's supposed to look like I limited my PR to just fix the linting error.

My mistake on the link, I'll fix that.

**Comment by dmbaughman** [comment]
Fixed

**Comment by cvrebert** [comment]
> If this is just to satisfy the linter, I'd say take that link outside of the `<div>` and let's merge...but this will need revisiting/fixing properly.

Yeah, mdo already acknowledged in #17072 that the examples still need a bunch of love and it's on his todo list.

**Comment by cvrebert** [comment]
Merged as bf31c8b9d9fc48501c642f8ec58abf5dcda7aafa. Thanks!

**Pull request closed without merging**
