### PR TITLE
background-variant button hover

### PR DESCRIPTION
**Pull request by zalog**

### CODE REVIEW

**Comment by cvrebert** [comment]
@zalog Please describe your change using complete sentences.

**Comment by zalog** [comment]
Hi @cvrebert, sorry I thought it is obvious.
``a.bg-primary`` has some background hover effect why not button html tag to?
Please take a look at this demo: http://codepen.io/zalog/pen/grWNJR

**Comment by Francismori7** [comment]
You are misusing buttons. `a.btn.btn-primary` as well as `button.btn.btn-primary` both work properly.

See http://codepen.io/anon/pen/kXwbab

**Comment by cvrebert** [comment]
Well, the `.bg-*` classes aren't really meant to be combined with the `.btn` classes. Like in Francis' example, you can/should simply use `.btn-primary` instead of `.bg-primary`.

On the other hand, the validity of just `<button class="bg-primary">` is less clear, but again using the btn classes would seem to make more sense.
The `<a>`-specific code in `.bg-*` is meant for inline text links as opposed to button-ish links.

**Comment by zalog** [comment]
Thanks @Francismori7, I know that :) It's just about ``.bg-*``.
In my previous example, I've simply used ``.btn`` class to reset that ``button`` default borders.
Sorry if I was unclear.

So let's assume:
- the need of a inline button with some javascript actions attached, not a anchor link
- we don't use ``button-variant`` or import ``_buttons.scss``
- our new class ``@include bg-variant('.bg-facebook', #3c5ba0);``

**a)** - ```<p>Lorem Ipsum is simply <a href="#" role="button" class="bg-facebook">printing</a> and typesetting</p>```

**b)** - ```<p>Lorem Ipsum is simply <button class="bg-facebook">printing</button> and typesetting</p>```

A or B? :)

But, as you Chris said, on the other hand, nor ``button.bg-*`` or ``a.bg-*`` seems to be valid.

**Comment by mdo** [comment]
Passing on this—I don't think anyone would expect this change when using the background utils.

**Pull request closed without merging**
