### PR TITLE
Flexbox enable navbar

### LINKED ISSUE #18875: Flexbox navbar elements wrap onto new line instead of inline
Meta list: #18467

[Test case](http://jsbin.com/jeyudiw/edit?html,css,output) 

It appears that there is not an implementation for nav items that responds to `$enable-flex: true;`.  This may not be in-scope, but wanted to mention it.

NOTE that it is not based on compiled css with `$enable-flex: true;` as that doesn't exist in `dist`.   Nonetheless, I see the same behavior in a flex enabled scenario.  Here's a screenshot of the same thing rendered with `$enable-flex: true;`:

test_ _bootstrap_material_design

### PR DESCRIPTION
**Pull request by rosskevin**
Resolves #18875.  Flex enable the navbar with backward compatibility change to mixins `pull-left` and `pull-right`.

### CODE REVIEW

**Comment by cvrebert** [comment]
@rosskevin This has merge conflicts.

**Comment by rosskevin** [comment]
Merge conflict fixed.

**Comment by cvrebert** [comment]
CC: @mdo for review
(I can handle the squashing if this gets approved.)

**Comment by mdo** [comment]
Not the direction I'd like to see this go, and the changes to the float utilities doesn't make any sense to me right now. Punting and planning to revisit with work in #20937. Thanks though!

**Pull request closed without merging**
