### PR TITLE
Update devDependencies.

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @cvrebert for JSCS

### CODE REVIEW

**Comment by cvrebert** [comment]
Looks like we should enable `requireSpacesInForStatement` in JSCS. No other interesting changes in the JSCS upgrade.

**Comment by cvrebert** [comment]
Also, the shrinkwrap needs to be updated.

**Comment by XhmikosR** [comment]
Yeah I left it out on purpose, I'll update it along with the change you
suggested.

**Comment by XhmikosR** [comment]
Updated. I had to work around a JSCS warning in the last patch.

**Comment by cvrebert** [comment]
:shipit:

**Pull request merged**
