### PR TITLE
Indent the last element, for example

### PR DESCRIPTION
**Pull request by alexeymelekhov-dev**
Indent the last element, for example, for the `<p>` tag

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
I was thinking for a more global approach on this. We could add for example a `.content` class in which the margins of the last elements (`ul`, `p`,...) are removed:
```
.content {
  > :last-child {
    margin-bottom: 0;
  }
}
```
This class could then be used for as well cards, alerts or other components.
Toughts @twbs/css-review?

**Comment by mdo** [comment]
@MartijnCuppens Yeah, something like that for more typographic control (larger `margin-top` on headings, enhanced lists, etc) could be really cool. I think there was a PR or issue somewhere, maybe from you even lol?

I'm unsure about a general content class yet for removing bottom margins though—that doesn't really feel like a content thing. That feels like a common product/UI issue more than a (marketing, editorial, blog) content thing.

**Comment by MartijnCuppens** [comment]
> I think there was a PR or issue somewhere, maybe from you even lol?

We once talked about that here: https://github.com/twbs/bootstrap/issues/26716. Bulma has a `.content` class which adds top margins and prevents the last element from adding an additional bottom margin: https://bulma.io/documentation/elements/content/#sizes

> I'm unsure about a general content class yet for removing bottom margins though—that doesn't really feel like a content thing. That feels like a common product/UI issue more than a (marketing, editorial, blog) content thing.

I do use a custom `.content` class a lot myself, mostly for just removing the bottom margin if I can't add a utility class to the last `<p>` or `<ul>` tag. I wasn't sure about the name either (also used `.body` in the past), but I haven't found a better name so far.

**Comment by mdo** [comment]
Per the conversation here, let's punt this to a separate effort. Arbitrary margin changes like this are a recipe for unintended consequences. We should avoid them where possible.

**Pull request closed without merging**
