### PR TITLE
Fixes #17265 - Make sure that global module names are capitalized in

### LINKED ISSUE #17265: Capitalize global module names in UMD builds
It seems that babel by default is lowercasing all module names, which is causing errors when trying to use the UMD builds in global environment.

Popover.js is requiring global.Tooltip

``` javascript
(function (global, factory) {
  if (typeof define === 'function' && define.amd) {
    define('Popover', ['exports', 'module', './tooltip'], factory);
  } else if (typeof exports !== 'undefined' && typeof module !== 'undefined') {
    factory(exports, module, require('./tooltip'));
  } else {
    var mod = {
      exports: {}
    };
    factory(mod.exports, mod, global.Tooltip);
    global.Popover = mod.exports;
  }
})(this, function (exports, module, _tooltip) { ... });
```

But tooltip.js is only defining global.tooltip ...

``` javascript
(function (global, factory) {
  if (typeof define === 'function' && define.amd) {
    define('Tooltip', ['exports', 'module', './util'], factory);
  } else if (typeof exports !== 'undefined' && typeof module !== 'undefined') {
    factory(exports, module, require('./util'));
  } else {
    var mod = {
      exports: {}
    };
    factory(mod.exports, mod, global.Util);
    global.tooltip = mod.exports;
  }
})(this, function (exports, module, _util) { ... });
```

This is fixable by leveraging the getModuleId option in the grunt babel:umd configuration as you can see [here](https://github.com/vejersele/bootstrap/blob/bugfix/babelModuleNames/Gruntfile.js#L103). If you want I can open a pull request ...

### PR DESCRIPTION
**Pull request by skrivle**
Fixes #17265

### CODE REVIEW

**Comment by twbs-rorschach** [comment]
Hi @vejersele!

Thanks for wanting to contribute to Bootstrap by sending this pull request!
Unfortunately, your pull request seems to have some problems:
* [Changes must be made to the original JS source code file(s), not just the generated concatenated JS file(s).](https://github.com/twbs/rorschach/blob/master/docs/js.md)

You'll need to **fix these mistakes** and revise your pull request before we can proceed further.
Once you've fixed these problems, you can either ask the maintainers to re-open this pull request, or you can create a new pull request.
Thanks!

(*Please note that this is a [fully automated](https://github.com/twbs/rorschach) comment.*)

**Comment by vejersele** [comment]
Hmm can someone reopen this pull request? I made changes to the grunt file in order to fix the generated output. No changes to the source files are needed in this case ... Thanks!

cc: @fat @cvrebert

**Comment by cvrebert** [comment]
@vejersele Please exclude `/dist/js` files from the pull request. Thanks.

**Comment by vejersele** [comment]
Any idea why the build failed? Seems like a configuration issue on the server ...

**Comment by cvrebert** [comment]
@vejersele https://github.com/rvm/rvm/issues/3559

**Comment by AStoker** [comment]
Updates to this?

**Comment by mdo** [comment]
Closing per #17265. Thanks though!

**Pull request closed without merging**
