### PR TITLE
Docs/examples: remove misleading jumbotron-heading classname

### PR DESCRIPTION
**Pull request by patrickhlauke**
Closes https://github.com/twbs/bootstrap/issues/28737

### CODE REVIEW

**Comment by XhmikosR** [comment]
@patrickhlauke: `git fetch --prune && git rebase i origin/master`

**Comment by patrickhlauke** [comment]
(oops, helps if i point it to the right base)

**Comment by XhmikosR** [comment]
The process is master -> then cherry picked to v4-dev in batches.

**Comment by luckylichi** [comment]
静音
 
---Original---

**Comment by patrickhlauke** [comment]
too many bizarre conflicts trying to re-rebase...closed this in favour of a fresh one https://github.com/twbs/bootstrap/pull/28741

**Pull request closed without merging**
