### PR TITLE
Workaround for MS Edge does not update  disabled control's style

### LINKED ISSUE #28247: The `disabled` property value of the custom radio button is not reflected in the display on Microsoft Edge
On Microsoft Edge, on changing the `disabled` property value of a custom radio button from JavaScript, the display of radio button is not updated. The display of radio button is updated correctly on  Firefox (65), Chrome (72.0.3626.96), IE11 (11.590.17134.0).

OS: Windows 10 (1803)
Browser: Microsoft Edge (42.17134.1.0)

Sample: https://codepen.io/4dn-oss/pen/KJeOdz

Expected Behavior: Every time the 'disable/enable' button is clicked, radio buttons will be disabled/enabled.
Result: On Microsoft Edge, radio buttons are always displayed as if it is enabled.

### PR DESCRIPTION
**Pull request by ysds**
Fixes #28247 

Before: https://codepen.io/anon/pen/VgEmwV
After: https://codepen.io/anon/pen/PVyGLv

This PR targets the components of the Bootstrap. However, if bootstrap team prefer to fix every situation, it can also add the following CSS to the `_reboot.scss`.
```scss
[disabled] ~ _ {}
```

### CODE REVIEW

**Comment by mdo** [comment]
@MartijnCuppens I haven't tested or reviewed this myself, but likely a candidate for v4 and then bringing back into v5.

**Review by MartijnCuppens — APPROVED** [review]
I really dislike the attribute selector but if it's the only solution we should do this. We'll revert this again once Edge has switched to Chromium.

**Comment by mdo** [comment]
Does the attribute selector cover the psuedo class for all browsers?

**Comment by ysds** [comment]
The `[disabled]` and `:disabled` are theoretically different, so we should test on actually devices. I've tested in:

- [x] macOS 10.14.2 Chrome 72.0.3626.109
- [x] macOS 10.14.2 Firefox 65.0.1
- [x] macOS 10.14.2 Safari 12.0.2 (14606.3.4)
- [x] macOS 10.14.2 Opera 58.0.3135.65
- [x] iOS 12.1.4  Chrome 72.0.3626.101
- [x] iOS 12.1.4  Firefox 15.0 (13894)
- [x] iOS 12.1.4  Safari
- [x] iOS 12.1.4  Edge 42.10.3
- [x] Windows 10 1809 Chrome 72.0.3626.109
- [x] Windows 10 1809 Firefox 65.0.1
- [x] Windows 10 1809 IE 11
- [x] Windows 10 1809 Edge 44.17763.1.0
- [x] Android 8.1.0 Nexus 5X Chrome 72.0.3626.105
- [x] Android 8.1.0 Nexus 5X Firefox 65.0.1
- [x] Android 8.1.0 Nexus 5X Edge 42.0.2.3330

**Comment by XhmikosR** [comment]
Change the base branch to master. If it's supposed to be backported in 4.x, mark it or something and we'll cherry pick it when we cut the release.

**Pull request merged**
