### PR TITLE
Don't create empty attributes

### LINKED ISSUE #15359: How to avoid tooltips adding `title` & `data-original-title` attributes to DOM?
In Bootstrap Tooltip.js you can use HTML data attributes to define title of the tooltip
````html
<button data-toggle="tooltip" data-placement="left" title="Tooltip on left">Button</button>
````
And then using Javascript intialize it
````js
  $('[data-toggle="tooltip"]').tooltip()
````

We have a requirement where we need tooltips without modifiying the HTML (using data attributes). The tooltips are shown in the WYSIWYG [Summernote](https://github.com/summernote/summernote) editor and we don't want the user change them using the HTML editor.

So we initialize the tooltips using only Javascript. The title and the placement are specified using JS and not HTML.
````js
  $('[data-toggle="tooltip"]').tooltip({ 'placement': 'left' , 'title' : 'Toolt on left'})
````

It works. Shows the tooltip as expected but it changes the HTML adding this attributes to the element 
```html
data-original-title="" title=""
```

Do you know why this happen? Do you know if we can avoid this feature and not modifiy the HTML after the tooltip is shown? If not, can we work in a PR to avoid this feature?

Thanks

### PR DESCRIPTION
**Pull request by Henni**
This fixes #15359 by applying the changes proposed by @melissamanrique at https://github.com/twbs/bootstrap/pull/15360#issuecomment-67184355.

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: ec67f3800ed4110ccbb92c91d95253f63807b796
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/70033199

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Henni** [comment]
Fixed indentation issues and squashed commits

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 513b3021ae604bfc766a1ff4f4c87093e2f32e18
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/70036678

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
@Henni [The unit test suite is failing](https://travis-ci.org/twbs/bootstrap/builds/70036675). See https://github.com/twbs/bootstrap/tree/master/js/tests for info on how to run the tests yourself so you can debug your problem.

**Comment by Henni** [comment]
@cvrebert thanks for the info.
I'll test it.

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 204d489b399fbc43a5aefb4fc9822dcfd1177503
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/70134009

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 204d489b399fbc43a5aefb4fc9822dcfd1177503
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/70134009

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Henni** [comment]
I reduced the fix to a change from an `||` to an `&&`.
Instead of checking if an title exists **or** the original-title object isn't already set, both should be the case.

But there's still one issue:
Destroying the tooltip with `.tooltip('destroy')` doesn't remove the `original-title`. So it's not possible to reinitialize the tooltip afterwards.
I'll fix this if you agree that this is wrong behavior.

Also I don't remove the `title` after it was moved to `original-title` as this would break a test.
test-tooltipemptytitle
Should this stay this way, or should the test be modified?

**Comment by Henni** [comment]
Why did the travis fail this time? My test suite didn't show any errors.

**Comment by cvrebert** [comment]
CC: @fat for review

**Comment by cvrebert** [comment]
> Why did the travis fail this time? My test suite didn't show any errors.

@Henni Looks like the third-party cross-browser testing service timed out, probably for unrelated reasons. Don't worry about it for now.

**Comment by cr2a-graphique** [comment]
i need it !

**Comment by fat** [comment]
ha, prett intersting jquery creates a useless attribute.

i think the better fix would be `$e[0].getAttribute('data-original-title')` - which we already fixed in v4 https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tooltip.js#L389

**Comment by mdo** [comment]
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Pull request closed without merging**
