### PR TITLE
Allow configurable opacity variable for placeholder-state (non-focused, empty) floating-label input label

### PR DESCRIPTION
**Pull request by josefdlange**
Some folks implementing Bootstrap may wish for the placeholder state's label of a `.form-floating` input to have some lighter opacity than 100%. 

The tradeoff is accessibility concerns (label too light may be hard to read) vs. user confusion (regarding whether the placeholder text is text already-filled-into the form field or if it is a label).

By allowing this to be configured via a SCSS variable, Bootstrap can empower developers to make this choice themselves while retaining its existing default value.

Let me know if there are any other steps needed to bring this up to par, or if I've missed anything in the contribution guidelines!

Edit: also, apologies for the verbose title. Couldn't think of anything more succinct offhand.

### CODE REVIEW

**Comment by josefdlange** [comment]
Hi gang! Is there something I can do to help make this visible for consideration? It's a fairly small change though I would understand if there's something more necessary or API change concerns etc!

**Comment by julien-deramond** [comment]
> Hi gang! Is there something I can do to help make this visible for consideration? It's a fairly small change though I would understand if there's something more necessary or API change concerns etc!

We're finalizing the v5.2.2. We will probably look at it for the v5.3.0. On my side, I haven't had the time yet.

**Comment by josefdlange** [comment]
Thanks for the followup! I'll be sure to keep an eye on this PR for when the time comes.

**Comment by josefdlange** [comment]
I see now that there's a merge conflict with `_variables.scss` -- both in terms of the literal lines of code, and, glancing at the changes, maybe a philosophical conflict? I'd love some guidance on the team's preferred way to proceed here. Let me know and I'll set aside some time to look into the conflicting change and see how we're interwoven (or not, hopefully!)

**Comment by mdo** [comment]
Given we're likely rewriting a bit of the floating forms to fix some background styling—in particular around disabled fields—introducing the ability to change the `opacity` will lead to problems where textarea content is somewhat visible through the label. Changing the `color` is a better move for folks IMO.

**Pull request closed without merging**
