### PR TITLE
Pass docs version to search and use the new search index.

### LINKED ISSUE #26224: Update DocSearch in v4.1 docs
Need to follow up on some changes I believe to our DocSearch config to add indexing and results for our new features.

https://github.com/algolia/docsearch-configs/pull/313

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #26224.

### CODE REVIEW

**Comment by mdo** [comment]
Hey @maxiloc, is there any chance we could test these changes out with a new/test index? We have our new docs release out yesterday and it has a different URL. Hoping to test this PR's changes to how we're going to handle indexing multiple versions.

**Comment by s-pace** [comment]
👋 @mdo,

Sure thing.

Let's use algolia/docsearch-configs#313 in order to fine tune your config

**Comment by XhmikosR** [comment]
So, @mdo, after we merge this, we just need to rebuild the 4.1.0 docs; the old versions should keep working since they use the old index.

How do you want to proceed? Maybe we should cut a 4.1.1 soon?

**Comment by mdo** [comment]
Let's rebuild the v4.1.0 docs tomorrow night (I'm driving back from a weekend vacation tomorrow) and then focus on getting v4.1.1 out the door in the coming weeks. I'm reviewing issues/PRs now for that.

**Comment by mdo** [comment]
@XhmikosR I don't want to go back and rebuild, but we'll need to sort out asset paths still. Let me look at that, but this is probably safe to merge regardless of that.

**Comment by XhmikosR** [comment]
@mdo: agreed. If you have any proposal about the assets, feel free to CC me.

**Comment by mdo** [comment]
I gave in on the rebuild—here's what I've done tonight in the `gh-pages` branch:

- Checked out the `v4.1.0` tag
- Cherry-picked this PR's two commits
- Re-ran `npm run dist` and `npm run docs-github`
- Found and replaced instances of the old search form to apply the new `data-docs-version` attribute
- Copy-pasta-ed the new `docs.min.js` over

You can see this all at https://github.com/twbs/bootstrap/commit/b378b85d65df0069fa0d67f510f2478e911e3c4e.

**Comment by mdo** [comment]
Well, tried that for a minute, but got this error:

```
AlgoliaSearchError {name: "AlgoliaSearchError", message: "Index not allowed with this API key", debugData: Array(1), statusCode: 403, stack: "AlgoliaSearchError: Index not allowed with this AP…docsearch.js@2/dist/cdn/docsearch.min.js:2:79868)"}
```

**Comment by XhmikosR** [comment]
Weird, because it worked for me when I made this PR.

I'll try again later and let you know.

**Comment by XhmikosR** [comment]
Yup, confirmed, it no longer works.

@s-pace: did you guys change something? Because we definitely didn't :P

**Comment by XhmikosR** [comment]
@s-pace: https://github.com/twbs/bootstrap/pull/26247/files#diff-46c8392b35c53245a29c9639d92674f0R126

I thought the index name was `bootstrap`? Did it change to `bootstrap-v4`?

**Comment by s-pace** [comment]
Indeed, you better use `bootstrap` but check the credentials (5990ad008512000bba2cf951ccf0332f):

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: '5990ad008512000bba2cf951ccf0332f',
  indexName: 'bootstrap',
  inputSelector: '### REPLACE ME ####',
  algoliaOptions: { 'facetFilters': ["version:$VERSION"] },
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

- Add a search input in your page if you don't have any yet. Then update the inputSelector value in JS snippet to a CSS selector that targets your search input field.

- Replace $VERSION with the version you want to search on.
   The list of possible version is hardcoded in the config.
   So as of today you have: `4.1`

  For example if you want to refine the search to the version "4.1" just specify: 
```js
'facetFilters': ["version:4.1"]
```

**Comment by XhmikosR** [comment]
@s-pace All right, I changed the API key to the one above and it works again for 4.1. But for 4.0 I get no results.

@mdo: sorry for the trouble, but you'll have to do the cherry picking and stuff one more time when we are done here, because I decided to move the search code outside of application.js. :)

**Comment by s-pace** [comment]
@XhmikosR for 4.0 you will need to use `bootstrap-v4 ` as we agreed. But I can merge both of them :)

**Comment by mdo** [comment]
I didn't try changing the v4.0 docs—I only did this for the v4.1 docs.

**Comment by mdo** [comment]
Okay, great—I'll try again tonight doing the same process.

**Comment by mdo** [comment]
Btw, thank you both for the patience and help doing this. Appreciate it all :).

**Comment by mdo** [comment]
Ayyy just cherry-picked the latest and pushed it up—see 275026bb42653b8ceea89225f0a987bd3aca78e5. Looks good!

**Comment by XhmikosR** [comment]
@mdo: so do we merge this?

**Review by mdo — APPROVED** [review]

**Comment by XhmikosR** [comment]
@mdo: I can't merge because Sauce Labs test is failing for some reason.

**Pull request merged**
