### PR TITLE
Change custom file markup

### LINKED ISSUE #25497: Feature/Enhancement: The CSS of custom file input is unnecessarily dumbed-down and limiting.
There are multiple things to this that I will discuss below. (And none of my suggestions break browser compatibility).

## CSS `attr()` function for the "Browse" text
Why do we need to keep translations for the "Browse" text in CSS? Such limiting workaround is unnecessary, since we can use the **well-supported** `attr()` function (it is **not** experimental technology if you are using it with a `content` property - [proof](https://developer.mozilla.org/en-US/docs/Web/CSS/attr)) for example like this:

```SCSS
.custom-file-label {
 // ...

  &::after {
    // ...
    content: attr(data-button);
  }
```

And then in HTML:
```HTML
<div class="custom-file">
  <input type="file" class="custom-file-input" id="id">
  <label class="custom-file-label" data-button="My browse text" for="id">My file text</label>
</div>
```

## HTML5's `<label>` _is allowed_ to contain other tags such as `<span>`
Proof [here](https://www.w3.org/TR/html5/sec-forms.html#the-label-element) and [here (see the "permitted content" section on top)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label).

With this knowledge we are able to do tons of things, such as:

### Text truncation
What I was able to do is this:
text truncation in practice

I achieved this in my custom project with this code: (note the added `<span>` tag)
```HTML
<div class="custom-file">
  <input type="file" class="custom-file-input" id="id">
  <label class="custom-file-label" data-button="My browse text" for="id"><span>Some looooooooooooooooooooooooooooong text</span></label>
</div>
```

(the SCSS code below extends Bootstrap's code)
```SCSS
.custom-file-label {
        display: flex;
        flex-direction: row;

        span {
            text-overflow: ellipsis;
            white-space: nowrap;
            overflow: hidden;
            padding-right: 20px;
        }

        &:after {
            content: attr(data-button);
            position: relative;
            margin: #{-$input-padding-y} #{-$input-padding-x} 0 auto;
         }
    }
```

### "Browse" button as a regular element
We can **ditch the `::after` element completely** and instead use a `<span>` tag to display the button. This allows us, for example, to use an SVG icon in place of the "Browse" text. (`<svg>` is permitted content of both `<label>` and `<span>` - see proof above.)

--------------------------------------------------------------------
These are just examples of what is possible with the custom file input component, without breaking compatibility. **If one thing should be included, it is the `attr()` CSS function.** The rest are just suggestions that you may or may not use.

### LINKED ISSUE #26933: Custom file LABEL text overlapping neighbouring HTML elements on Firefox
On Firefox 63 (but not on Chrome 70, Edge 44 nor Safari 12), the text in the "custom-file-label" LABEL element seems to invisibly overlap the neighbouring button INPUT element and prevents from clicking on it:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
  </head>
  <body>
    <div class="form-row" style="width: 400px">
      <div class="form-group col">
        <div class="custom-file">
          <input type="file" class="custom-file-input" id="browser">
          <label class="custom-file-label" for="browser">long_filename.txt</label>
        </div>
      </div>
      <div class="form-group col">
        <input type="button" value="Load" class="btn btn-primary">
      </div>
    </div>
  </body>
</html>
```

### LINKED ISSUE #28389: custom-file-border-radius-after is not customizable
When the border width for input fields is more than 1px, the radius of the `custom-file-border` label after is not correct.
This PR introduces a way to customize that radius with a new variable: `$custom-file-border-radius-after`

screenshot 2019-03-01 at 09 20 58
screenshot 2019-03-01 at 09 26 33

### PR DESCRIPTION
**Pull request by ysds**
Please see https://github.com/twbs/bootstrap/pull/28511#issuecomment-474381351.

By changing the markup of custom file, remove the way of translating button labels by CSS, and support a long file name. Now, you can change the button label by HTML.

And for fix #28389, move the border to the each children of the `.custom-file-label`. Another way by `overflow: hidden` is suddested (https://github.com/twbs/bootstrap/pull/28388#issuecomment-468898020), but it does not round the inside of the corner.

I also added the `transition` to` .custom-file-text` and `.custom-file-button` for focused border color animation.

Closes #25497
Closes #26933
Closes #28388
Closes #28389

Preview: https://deploy-preview-28696--twbs-bootstrap.netlify.com/docs/4.3/components/forms/#file-browser

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
Maybe we should also include an example wit a longer placeholder to demonstrate the truncation?

**Comment by ysds** [comment]
I checked the SCSS again and confirmed that there are no problem, I updated the PR comment and remove the WIP.

@MartijnCuppens Could you add the example? if you are okay with that 🙏

**Review by MartijnCuppens — APPROVED** [review]
Done

**Comment by XhmikosR** [comment]
Wouldn't make more sense to use the grid in this and the previous example? That way we won't have those long forms.

**Comment by mdo** [comment]
I think I’m good with this, but does it come at the cost of a screen reader announcing the button text since it’s in the label?

**Comment by patrickhlauke** [comment]
@mdo had a super-cursory check with NVDA and Jaws on Win (Chrome/Firefox/IE), and it seems to behave no different from the current implementation, unless i'm missing something?

**Comment by mdo** [comment]
Hadn’t compared to current behavior, so just wanted to ask the question to see if this a regression or area for improvement for us. If you’re good with it @patrickhlauke, I’m good here.

**Comment by patrickhlauke** [comment]
it seems appropriate to me (not extensively tested/compared to native clean unaltered file input, but these are notoriously icky - particularly in Firefox/NVDA - and just checking the above seemed good for me)

**Review by patrickhlauke — APPROVED** [review]

**Review by mdo — APPROVED** [review]
<3, thanks @ysds!

Btw, I sent you a note to the email on your GitHub profile. You have some fantastic contributions to Bootstrap and we’d love to have you join our team officially if you’ll accept! No pressure either way.

**Comment by alecpl** [comment]
Thanks. I suggest small improvements. Set line-height/font-weight on the `.custom-file-label` element instead of both spans inside. And use `.custom-file-label > *` selector to assign some common styles like display, padding, border and transition.

**Comment by MartijnCuppens** [comment]
> Set line-height/font-weight on the .custom-file-label element instead of both spans inside.

Might indeed be a nice improvement.

> And use .custom-file-label > * selector to assign some common styles like display, padding, border and transition.

I don't mind using the universal selector in case we gain a lot of improvement by it. Since we know what the classes of the children will be (`.custom-file-text` & `.custom-file-button`) I don't think it's worth adding another selector to add common styles here.

**Pull request merged**
