### PR TITLE
Lint Docs HTML Files

### PR DESCRIPTION
**Pull request by tomlutzenberger**
This commit fixes the following:
- Missing closing tags
- Unescaped special characters
- Lower-cased tag parameters
- Single quote usage

### CODE REVIEW

**Comment by tomlutzenberger** [comment]
In order to apply those changes to v4, do I need do create a second PR based on the v4-master?

**Comment by patrickhlauke** [comment]
Super, thanks. yes, i think doing a second PR is the simplest way to go about it...

**Comment by tomlutzenberger** [comment]
You're welcome.
Alright!

**Comment by twbs-savage** [comment]
**Tests failed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 4c459bd6cf0f63e1a7ea67c99dc7db9b069545e6
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/144478624
Docs preview: http://preview.twbsapps.com/c/${commitSha.sha}

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
@patrickhlauke Friendly reminder: set labels and milestone when merging PRs 😄

**Pull request merged**
