### PR TITLE
Add text-underline Utility class, closing #23880

### PR DESCRIPTION
**Pull request by PascaleBeier**
Adding a Decoration block for utilites and adding .text-underline

Can be used to add the other text-decoration utilties.

### CODE REVIEW

**Comment by andresgalante** [comment]
sorry @PascaleBeier but I wouldn't like to see this merged. We need to take really good care about not turning utility classes a 1:1 reflection of every CSS property.

**Comment by PascaleBeier** [comment]
@andresgalante I guess one had to decide where to draw the line right? Interesting to see.

**Comment by Johann-S** [comment]
Agreed with @andresgalante but it's @mdo who will have the final word

**Comment by mdo** [comment]
I don't see us adding this one, but I would consider a `.text-decoration-none` or `.no-underline` utility added for that use case. Far more common than adding an underline via class.

**Pull request closed without merging**
