### PR TITLE
Improve disabled state close button

### PR DESCRIPTION
**Pull request by dejakob**
Add 
`not-allowed: cursor`
and
`user-select none`
to the close button in order to give the user feedback it is disabled

### CODE REVIEW

**Comment by patrickhlauke** [comment]
we abandoned the `not-allowed` cursor quite a few versions back because it's non-standard and, subjectively, very disruptively ugly on windows.

**Comment by mdo** [comment]
@patrickhlauke Thoughts on the `user-select: none` addition?

**Comment by patrickhlauke** [comment]
the `user-select:none` part is good...sorry, should have mentioned that at the time

**Comment by mdo** [comment]
Closing for ##31641.

**Pull request closed without merging**
