### PR TITLE
Sync code shown with code actually used

### PR DESCRIPTION
**Pull request by heikojansen**
Remove class and attributes from buttons which are not expected to trigger dropdowns.
Code used to render the examples is correct but code shown was not.

### CODE REVIEW

**Comment by Johann-S** [comment]
If you remove `data-toggle="dropdown` Dropdown won't work because of that selector : https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js#L63

`.dropdown-toggle` is usefull because it add the arrow next to the button to show it's a Dropdown

and `aria` attribute is for accessibility so it's usefull too

**Comment by heikojansen** [comment]
Sorry for not providing a more detailed description. Yes, the class and attributes are required, but not on two button elements within the _same_ split button instance (".btn-group"). Please review once more.

**Comment by Johann-S** [comment]
Please provide a CodePen to demonstrate what you explained because if I remove what you suggested Dropdown don't works

**Comment by acshef** [comment]
@heikojansen is saying that for a split button, the NON-DROPDOWN side doesn't need the extra attributes.

image

**Comment by Johann-S** [comment]
Understood thank you @acshef for the explanation 👍

**Comment by heikojansen** [comment]
Thanks @acshef for the screenshot. Would have done that next, too, but was on holiday yesterday.
I'll try to provide more context, next time around...

**Pull request merged**
