### PR TITLE
README.md: show brotli size too

### PR DESCRIPTION
**Pull request by XhmikosR**
This was something @MartijnCuppens suggested some time ago on Slack.

My only concern is that gzip is the defacto compression used. We could probably keep both sizes in README.md as a middle solution?

Also, not sure if we should backport this or not.

/CC @mdo @ffoodd @MartijnCuppens @Johann-S

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
> My only concern is that gzip is the defacto compression used. We could probably keep both sizes in README.md as a middle solution?

Sounds good

> Also, not sure if we should backport this or not.

BS4 doesn't support Brotli, so backporting doesn't feel right.

**Comment by XhmikosR** [comment]
> BS4 doesn't support Brotli, so backporting doesn't feel right.

That's unrelated 😛

**Comment by XhmikosR** [comment]
Another solution would be to maybe add a separate table with the dist files and their sizes?

**Comment by MartijnCuppens** [comment]
> BS4 doesn't support Brotli, so backporting doesn't feel right.
> That's unrelated 😛

I mean IE, woops.

**Comment by XhmikosR** [comment]
> 
> 
> > BS4 doesn't support Brotli, so backporting doesn't feel right.
> > That's unrelated 😛
> 
> I mean IE, woops.

Yeah, but we don't care about that here. It's a useful metric and servers do fall back to gzip.

**Comment by XhmikosR** [comment]
So, to summarize, we can check for both gzip and brotli in bundlewatch and show both in README.md.

@mdo WDYT?

**Comment by mdo** [comment]
Sounds reasonable to me!

**Comment by XhmikosR** [comment]
How about just showing both in README.md for starters? What we use in bundlewatch shouldn't matter a lot.

**Review by mdo — APPROVED** [review]

**Pull request merged**
