### PR TITLE
Update docs assets

### PR DESCRIPTION
**Pull request by XhmikosR**
I only left out holder.js since it results in black background. (@imsky)

/CC @cvrebert

### CODE REVIEW

**Comment by imsky** [comment]
I'll look into what's going on

**Comment by imsky** [comment]
@XhmikosR holder 2.9.2 should have this fixed. i tested it with a local build of bootstrap docs

**Comment by XhmikosR** [comment]
Thanks I will have a look as soon as possible!

**Comment by imsky** [comment]
@XhmikosR hold on, there's an issue with the BS docs code

**Comment by imsky** [comment]
@XhmikosR PR opened: https://github.com/twbs/bootstrap/pull/19336

**Comment by XhmikosR** [comment]
Thanks I see now why it failed. I'll merge it when I'm at home.

**Pull request merged**
