### PR TITLE
Change location of modal backdrop to fix z-index issue

### LINKED ISSUE #16148: Modal behind backdrop when parent is position:relative with z-index
When I use 3.4 to load a modal, the modal is covered by the backdrop. After removing all the customized css and leaving only the bootstrap css, the problem remains. Changing 3.4 to 3.2 instantly solve the problem. The modal is used within an ng-view partial.

### PR DESCRIPTION
**Pull request by thomasphorton**
Fixes #16148

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 7ca5c9b2cc1017e079e3e6a7fe6746302d6789a0
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/61411330

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
We just switched it back from the parent to the body (see #15881). So I don't think this is an option.

**Comment by thomasphorton** [comment]
Hm- I'll dig in and check that this isn't causing any regressions. I hadn't considered why that change was made, just too focused on the bug in front of me. I'll update when I get more info.

**Comment by thomasphorton** [comment]
Unrelated to that, what's up with that failed travis build? Is that something I caused?

**Comment by cvrebert** [comment]
No. Transient network error when it tried to install Jekyll:
```
ERROR:  Could not find a valid gem 'jekyll' (= 2.5.3), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ETIMEDOUT: Connection timed out - connect(2) 
```
I'll force a rebuild.

**Comment by thomasphorton** [comment]
@hnrch02 

Do you mind giving a little more explanation as to why you moved from prepending to `this.$element` to appending to `this.$body`?

By moving it further away from the `.modal` element, we're creating a window where the z-index context can change, which can break the modal experience.

My solution is to create the `.modal-backdrop` element as a sibling to `.modal` to minimize that window. It seems to work, but I can't verify that I'm not causing a regression because I'm not clear on what you were trying to fix when you made your change.

Thanks!

**Comment by leftclickben** [comment]
:+1: to what @thomasphorton is asking.

**Comment by cvrebert** [comment]
@thomasphorton See the example from #15136: http://jsfiddle.net/6dad98ry/
If you open the modal, open Collapsible Group Item 2, and then scroll down, you'll notice that the gray backdrop behind the modal doesn't extend to the bottom of the page; there's a white section it doesn't cover.

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://fiddle.jshell.net/6dad98ry/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 15, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.1
* line 19, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.1

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
The interactive modal test (https://github.com/twbs/bootstrap/blob/master/js/tests/visual/modal.html ) also includes the same accordion demo.

**Comment by thomasphorton** [comment]
Awesome, I think we're in business then. I just verified it on localhost. Is there anything you need from me to prove it?

**Comment by cvrebert** [comment]
@hnrch02 Ping.

**Comment by hnrch02** [comment]
What #15881 did was revert the changes from #14724 (as the description reads). The backdrop has always (as far back as I can remember anyways) been appended to the body. #14724 changed it to the `.modal` element which caused #15136. Anyway, technically #16148 isn't a regression from 3.3.2 to 3.3.4 but a problem that exists since the inception of the modal plugin and was only temporarily fixed as a side-effect by #14724.

I don't see any problem with this solution right now, although I admittedly didn't do any heavy testing. Maybe @fat can way in also.

**Comment by fat** [comment]
Technically this hasn't existed since the inception of the modal plugin - but *has* existed since we decided we wanted the modal's dialog to overflow and scroll (the dialog in the past had it's own overflow which made this all much less of a pain in the ass).

There are a few different hacks to get this working – but we've found it hard landing on one for a generic use case.

In some cases Foo works best, but in others Baz works, etc.

imho, what we really need is a better set of unit tests to attack the problem…

Meanwhile, for this particular p4, i'm of the opinion that we shouldn't be merging anymore js in v3. As far as i'm concerned v3.x is done. And all work should be going towards finishing v4.

**Comment by thomasphorton** [comment]
@fat that sounds good, give me access to v4 and I'll get cracking! :wink: 

Are you sure you don't want to drop this in? Work's already done and it seems like it would minimize user pain. I'm fine either way.

**Comment by fat** [comment]
heh we're trying to get an alpha out ASAP :+1: cranking, i promise <3

**Comment by mdo** [comment]
Punting to v4.

**Pull request closed without merging**
