### PR TITLE
Drop support for Node.js 8.

### PR DESCRIPTION
**Pull request by XhmikosR**
By the time v5 stable will be out, 8 will be EOL (December 2019).

TODO:

- [x] Adapt master protection rules before merging this

### CODE REVIEW

**Comment by XhmikosR** [comment]
Notes:

1. in order to make Netlify use Node.js 10, we need to use a `.nvmrc` file. Adding this file might have other implications which I'm not 100% sure since I don't use nvm myself
2. we need to remove Node.js 8 from the master protection rules before merging this

**Comment by XhmikosR** [comment]
I dropped the .nvmrc addition. Maybe netlify will properly read the engines version after this is merged on master. If not we add the .nvmrc file then.

**Review by mdo — APPROVED** [review]

**Comment by XhmikosR** [comment]
@mdo: if we merge this, I need Node.js 8 removed from the master branch protection rules :)

@Johann-S: I assume you agree?

**Comment by mdo** [comment]
Done!

**Review by Johann-S — APPROVED** [review]

**Pull request merged**
