### PR TITLE
Focus on first error in forms

### PR DESCRIPTION
**Pull request by MewenLeHo**
### Description

Focus on first error in forms

### Motivation & Context

After submit, and if the submitted form contains errors, it is convenient to set the focus to the first element that contains an error to achieve better accessibility for persons with disabilities.
(https://www.w3.org/WAI/tutorials/forms/notifications/#listing-errors).

### Type of changes

- [x] New feature (non-breaking change which adds functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

* https://deploy-preview-37323--twbs-bootstrap.netlify.app/docs/5.2/forms/validation/#server-side

### CODE REVIEW

**Comment by GeoSot** [comment]
**/cc @patrickhlauke **  If this behavior is fine to your eyes, we are fine to merge it :+1:

**Comment by patrickhlauke** [comment]
personally, i'm not sure i'd make that an automatic behaviour. authors may decide to do something else with their forms - maybe they want to bring up an alert/modal, or maybe show a big listing of all the errors in the form and move focus there?

i'd make it an opt-in behaviour at least.

**Comment by GeoSot** [comment]
As it is only for our documentation examples and not something in the core code, I think it is fine.
Do you agree on this @patrickhlauke ?

**Comment by patrickhlauke** [comment]
ah sorry, it's just aimed at examples and docs?

would that not give devs the impression that this is something that comes with bootstrap core out of the box, though?

**Comment by GeoSot** [comment]
It's not something users can see, it adds clearly to our docs User experience

**Comment by patrickhlauke** [comment]
> It's not something users can see, it adds clearly to our docs User experience

but they will ... they'll see it in action on the docs, and assume that this comes as standard when they use bootstrap?

**Comment by MewenLeHo** [comment]
> but they will ... they'll see it in action on the docs, and assume that this comes as standard when they use bootstrap?

So should I remvove it from the code example and add a paragraph in the doc instead?

**Comment by XhmikosR** [comment]
Agreed, we could have a separate example of something maybe?

**Comment by mdo** [comment]
Down for a separate example. Going to close this out for now, but if anyone wants to open a new PR for that, we'll happily review it. Thanks!

**Comment by MewenLeHo** [comment]
Thank you all for your comments.

Just a question for @mdo, what do you mean exactly by a 'separate example'?
Another js example after the current starter JavaScript example (maybe in a new section?) or a complete form example inside the 'Examples' page?

I am struggling to find the better option between the two.

**Comment by MewenLeHo** [comment]
Did you get a chance to look over my latest question @mdo? Thanks a lot :)

**Pull request closed without merging**
