### PR TITLE
Move to BrowserStack

### PR DESCRIPTION
**Pull request by Johann-S**
Related to our internal discussion about moving away from Sauce Labs to BrowserStack

- [x] Register us on BrowserStack here: https://www.browserstack.com/open-source
- [x] Add 2 new env vars in Travis `BROWSER_STACK_USERNAME` and `BROWSER_STACK_ACCESS_KEY`
- [x] To fill those vars, you'll found that here https://www.browserstack.com/accounts/automate
- [x] Add BrowserStack badge
- [x] Fix mobile testing
  - [x] Android
  - [x] iOS
- [ ] When we are all done, remove the old Sauce Labs Travis variables

### CODE REVIEW

**Comment by Johann-S** [comment]
@XhmikosR it's up to date 😉
You can provide to BrowserStack this URL (which contain their logo): https://github.com/twbs/bootstrap/tree/v4-dev-jo-browserstack

**Comment by XhmikosR** [comment]
Thanks, I'll adapt the docs

**Comment by Johann-S** [comment]
I have to add the BrowserStack badge

**Comment by XhmikosR** [comment]
Ok, so tests are up and running on BrowserStack. We need to fix a couple of issues we have and we make the switch.

**Comment by Johann-S** [comment]
@XhmikosR everything is done and works well, do you want to review a last time ?

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
I'm thinking, don't remove the Sauce Labs Travis vars yet because some PRs might be behing the main branch and use that. But it's your call.

**Comment by Johann-S** [comment]
You're right, I'll wait a bit before removing Sauce Labs var

**Pull request merged**
