### PR TITLE
Docs: add/unify advice on contextual colors and accessibility

### PR DESCRIPTION
**Pull request by patrickhlauke**
- add callout warning about conveying meaning to assistive technologies when using color modifiers
- use more generalised callout text where already present

### CODE REVIEW

**Comment by cvrebert** [comment]
Perhaps we could use Jekyll's `include` directive rather than having the same text copypasta'd in multiple places?

**Comment by patrickhlauke** [comment]
Don't know anything about Jekyll, but this http://wolfslittlestore.be/2013/10/rendering-markdown-in-jekyll/ seems to put a spanner in the works unless the fragment's already in HTML?

**Comment by cvrebert** [comment]
We're already using [custom Jekyll plugins](https://github.com/twbs/bootstrap/tree/v4-dev/docs/_plugins), so we might as well add the one from the post you linked to.

**Comment by patrickhlauke** [comment]
I'll need somebody to either give me some massive pointers...or do it before I break everything ;)

**Comment by parker24j** [comment]
parkerj.org/twbs/bootstrap. https://live.blockcypher.com/btc/address/1AWLGkNTFgaDKyLxXtszPChd2yX54uBrRm/

**Comment by cvrebert** [comment]
I'll take a crack at the Jekyll plugin.

**Comment by patrickhlauke** [comment]
i had a few attempts at doing the jekyll plugin thing. however, it ended up giving me all sorts of annoying side effects (like complaining about `%endmarkdown` in the getting started download.md file), and needed to be unnecessarily hacked (to make sure the includes were grabbed explicitly from `docs/_includes`). decided to go the slightly more wordy, but perfectly legit route of 
```
{% capture my-include %}{% include test.md %}{% endcapture %}
{{ my-include | markdownify }}
```
instead. closing this in favor of the successor PR https://github.com/twbs/bootstrap/pull/19255

**Pull request closed without merging**
