### PR TITLE
v4 - Use "@if not $bool" expression

### PR DESCRIPTION
**Pull request by vsn4ik**

### CODE REVIEW

**Comment by XhmikosR** [comment]
Seems pretty straightforward to me. I wonder if we need to put parenthesis around the check though. I remember there were [some](https://github.com/sass/libsass/issues/355) issues in the past.

/CC @mdo

**Comment by glebm** [comment]
The parenthesis issue has been fixed since libsass 3.1

**Comment by XhmikosR** [comment]
Then one more reason to merge this as is :+1:

**Comment by mdo** [comment]
Nice! I meant to go look for the syntax for this and never got around to it. Thanks!

**Pull request merged**
