### PR TITLE
Update QUnit to v1.17.0.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by cvrebert** [comment]
Seems like we should do it now, otherwise it just means consulting more changelogs again later.

**Comment by XhmikosR** [comment]
Feel free to do those changes then (or anyone else).

**Comment by cvrebert** [comment]
QUnit 1.17.0 is now out, with a fix for #15582.

**Comment by XhmikosR** [comment]
Updated to 1.17.0.

**Comment by XhmikosR** [comment]
So, should we just merge this for the time being or do you want to make the API call changes now?

**Comment by cvrebert** [comment]
Working on making the API changes...

**Comment by XhmikosR** [comment]
Thanks @cvrebert!

**Pull request merged**
