### PR TITLE
Docs: style clipboard button on `:focus`, not just `:hover`

### PR DESCRIPTION
**Pull request by patrickhlauke**

### CODE REVIEW

**Comment by patrickhlauke** [comment]
current look (when focused in Chrome)

current

after this change

after

**Review by ffoodd — APPROVED** [review]

**Comment by XhmikosR** [comment]
Please do not merge yet. I want @mdo to have a look.

**Review by XhmikosR — DISMISSED** [review]
See comment

**Review by mdo — APPROVED** [review]
Man I hate Chrome’s focus styling lol. Looks good  other than that!

**Pull request merged**
