### PR TITLE
Minor grammar improvements

### PR DESCRIPTION
**Pull request by Pvanhesteren**
Fixed some grammar issues to improve the documentation.

### CODE REVIEW

**Comment by patrickhlauke** [comment]
i'd say these are borderline appropriate, common (albeit perhaps colloquial) uses. not fussed either way though.

**Comment by Pvanhesteren** [comment]
@patrickhlauke, are you suggesting that this PR is unnecessary? It is not of much help, but every improvement helps improve the project documentation, no?

**Comment by patrickhlauke** [comment]
i'm personally passing on this, but leaving it here for @mdo and others to decide ;)

**Comment by Pvanhesteren** [comment]
@XhmikosR, I noticed you have put this PR on hold. Is anything required from my side? Please let me know how I can help out :smile:

**Comment by cvrebert** [comment]
Accepted the "unwantedly" change.
Rejected the "barebone" change since it sounds weird to my ear.
Supporting example: "He was a prominent member of the barebones Parliament, [...]" – http://www.dictionary.com/browse/barebones

**Pull request closed without merging**
