### PR TITLE
Allow to use Tab.js with list-group

### PR DESCRIPTION
**Pull request by Johann-S**
Allow Tab.js selector to accept ``list-group``

Ref : #20620

### CODE REVIEW

**Comment by mdo** [comment]
Hell yeah, thanks!

**Comment by Johann-S** [comment]
You're welcome 😀👌

**Comment by vanduynslagerp** [comment]
Is there really a point in supporting `list-group` with tabs ? As there is already [vertical navs](https://v4-alpha.getbootstrap.com/components/navs/#vertical).

As far as I can tell both achieve the same thing.

The original issue #20620 mention "an example from v3". I think it's intended in v4 to offer vertical nav for this case while in v3 list-group were the way to go.

**Comment by Johann-S** [comment]
It's the result of this discussion #20620, because we think (@mdo and myself) that it's better to allow Tab.js to work with every lists provided by BS

**Comment by Johann-S** [comment]
Due to this comment : https://github.com/twbs/bootstrap/issues/21755#issuecomment-274511517

Allow to use this structur of ``.list-group`` : 
```html
<div class="list-group">
  <a href="#home" class="list-group-item active" data-toggle="tab">Home</a>
  <a href="#profil" class="list-group-item list-group-item-action" data-toggle="tab">Profil</a>
</div>

**Pull request merged**
