### PR TITLE
Remove anchor focus override within dropdown menu

### PR DESCRIPTION
**Pull request by arizzitano**
The dropdown styles explicitly remove the browser's default focus outline for links within the menu, which [hurts accessibility](http://www.outlinenone.com/) as it ~~violates [WCAG 2.0 AA section 2.4.7](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#navigation-mechanisms-focus-visible)~~ [edit: technically, the focus highlight background color prevents it from failing]. Without the focus outline, keyboard-only users cannot orient themselves within a dropdown menu, which can be especially troublesome if the implementor has also applied a focus trap.

This PR removes the override, enabling the browser to apply its own native focus outline to links within the dropdown menu. The outline will only appear if a link has `:focus`, so **mouse users will see virtually no change**.

Suggestions welcome -- happy to amend as necessary!

### Screenshots
Before | After
|------|------|
image | image

### CODE REVIEW

**Comment by patrickhlauke** [comment]
to clarify, no: the current situation does not fail wcag 2 2.4.7 as there is a visible focus indication (the background color applied to focused dropdown item). you can argue about whether or not the focus indication itself could be stronger, but as it stands it does nominally pass 2.4.7

**Comment by arizzitano** [comment]
I updated the description accordingly, but I stand by the override removal. It's entirely reasonable for users to expect a focus outline on links, since that's a browser default. Is there a reason for keeping the override?

**Comment by andresgalante** [comment]
I don't know about wcag 2 2.4.7, but I think that a focus ring can be stronger.

**Comment by tmorehouse** [comment]
I too agree that the current dropdown focus background is rather light, and depending on screen contrast is almost invisible.  I have had keyboard only users complain about the inability to tell which dropdown item they have focused (screen readers users are OK with it).

We have added a box shadow with a large spread to darken the focus highlight.  Non keyboard users didn't like the focus ring we applied, so we went with a darker background.

**Comment by arizzitano** [comment]
Just to be clear, this native focus ring will not show up for non-keyboard users. It only appears when focus is applied via the keyboard (or programmatically), and doesn't affect the hover state at all.

**Review by patrickhlauke — APPROVED** [review]

**Comment by patrickhlauke** [comment]
LGTM. @mdo ?

**Comment by patrickhlauke** [comment]
Closes https://github.com/twbs/bootstrap/issues/23329

**Comment by tmorehouse** [comment]
This addresses link dropdown items, but not button dropdown items.

**Pull request merged**
