### PR TITLE
[Fix #15781] Fix modal hangs

### LINKED ISSUE #15781: Modal window hangs when the button is clicked many times
Hello!

There is an occasional bug in modal windows. If the user clicks fast and often on the button to open a modal window, it may hang. I attached a picture of it. This modal window cannot be closed.

There isn't any error messages in Chrome Console (see screenshot).

Also the same bug was reproduced with IE10.

Google Chrome version is 40.0.2214.93 m.

modal_bug_1

modal_bug_2

### PR DESCRIPTION
**Pull request by Johann-S**
Hi,

This commit fix modal hangs from #15781 when user
click a lot on the button to toggle the modal and the modal cannot be closed.
Fixes #15781.

### CODE REVIEW

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 53e9b1b811d45f3c44ea520c390187fca4a5a77c
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/51622035

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
Please explain what hangs you're referring to.

**Comment by cvrebert** [comment]
CC: @fat

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 5feb6fba618188f9d23925d966676def6a6e6321
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/53154147

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Johann-S** [comment]
Sorry I failed a bit on my rebase

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 82306e6fe5fd7b0570ea4f1e1c698b32146dfb88
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/53154586

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by cvrebert** [comment]
@hnrch02 Happen to have any insight here, or should we just wait for fat?

**Comment by cvrebert** [comment]
@twbs-savage Retry

**Comment by twbs-savage** [comment]
**Tests passed.** Automated cross-browser testing via Sauce Labs and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: a5975cee1fe5ed95e07ab9d65d47d3826fde8eff
Build details: https://travis-ci.org/twbs-savage/bootstrap/builds/53155254

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Johann-S** [comment]
This fix prevents having multiple ``modal-backdrop`` added while having the backdrop still visible

**Comment by hnrch02** [comment]
Can you please retest #15781 and more specifically the claim from https://github.com/twbs/bootstrap/issues/15781#issuecomment-73763142 with the code from latest master? Now that the backdrop is appended to the body again I can't reproduce.

**Comment by Johann-S** [comment]
The modal can be dismissed but they are no backdrop because they are to much backdrop added to the body

**Comment by hnrch02** [comment]
I hear that but I'm unable to reproduce the behavior you describe. I rapidly click on the trigger and the modal works fine. No excess backdrops.

**Comment by Johann-S** [comment]
Yes I can't reproduce it when I click a lot on the button to toggle the modal but I can produce the behavior with the autoclicker I made.

``
$(function () {
  var nb = 105;
  function test() {
    var i = 0;
    while(i<nb) {
      $('#btnModal').click();
      i++;
    }
    console.log('done');
  }
  $('.js-popover').popover();
  $('.js-tooltip').tooltip();
	test();
})
``

**Comment by cvrebert** [comment]
@Johann-S That's not a completely realistic example since the user can't click the button when the backdrop is down, whereas your JS code can.

**Comment by Johann-S** [comment]
Yes that's true, I made this PR before the PR of @hnrch02 which fix what I want to fix by removing ``adjustBackdrop``

**Comment by hnrch02** [comment]
@Johann-S So you are saying that this has been fixed?

**Comment by Johann-S** [comment]
Yes exactly

**Comment by hnrch02** [comment]
Then I'll close this.

**Pull request closed without merging**
