### PR TITLE
Fix event propagation from inactive and disabled dropdowns (#30510)

### PR DESCRIPTION
**Pull request by luktom**
Please see #30510 for details. Two new unit tests added. "npm run test" was finished without errors.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Thanks for the PR but the default repo branch is master. Everything should
target the master branch and we backport it as needed.

**Review by Johann-S — APPROVED** [review]

**Comment by Johann-S** [comment]
Would you mind @luktom to backport that in our `v5` ? By doing another PR which target our `master` branch

**Comment by luktom** [comment]
@XhmikosR sorry, I thought you already moved to master with v5 development and my bug is reproducible on v4. I know that "Contribution" page says that you should make your PRs to master but as stable version is v4 and v5 is in master I was confused.

@Johann-S sure, I will do it.

**Comment by XhmikosR** [comment]
I'm gonna merge this for now and add it to the v5 project until we have a PR against master too, thanks @luktom!

**Comment by luktom** [comment]
> I'm gonna merge this for now and add it to the v5 project until we have a PR against master too, thanks @luktom!

@XhmikosR please find a PR for master here: #30529.

**Pull request merged**
