### PR TITLE
Add bundlesize.

### LINKED ISSUE #23009: Explore adding bundlesize
Could be rad to see something like https://github.com/siddharthkp/bundlesize in our CI status. It's easy for compiled code to get outta hand with small changes. Could help with that.

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #23009.

So, the sizes bundlesize reports are the gzip ones. I went with pretty strict values and separate entries, but we can always change them if needed.

Now, in order for the GitHub integration to work, @mdo needs to take care of https://github.com/siddharthkp/bundlesize#2-build-status

### CODE REVIEW

**Comment by XhmikosR** [comment]
Oh, it seems bundlesize doesn't work on node.js 4 so we might want to bump the minimum version to 6 or run bundlesize only on node 8.

**Comment by Johann-S** [comment]
Not against moving to node 6 plus node 4 maintenance will end in April 2018

**Comment by XhmikosR** [comment]
Should I also add the CSS files?

**Comment by Johann-S** [comment]
IMO @mdo would be interested to have our CSS file too

**Review by bardiharborow — APPROVED** [review]
Looks good. Happy to drop Node.js v4 given that it's in maintenance. v8 is about to hit LTS, so we'll be testing on both current LTS versions.

**Comment by XhmikosR** [comment]
@mdo: will you add https://github.com/siddharthkp/bundlesize#2-build-status or should I merge now?

**Review by Johann-S — APPROVED** [review]

**Comment by mdo** [comment]
Added env variable to Travis

**Pull request merged**
