### PR TITLE
Add baseof.html layout to docs

### PR DESCRIPTION
**Pull request by NotWoods**
For #28479

Adds a base layout used by most other layouts. Also adds a base "redirect" layout to avoid some duplication.

---

Biggest sticking point here is `body_override`. 

Seems like hugo doesn't like having an attribute defined like this:

```
<body {{ block "body_attribute" . }}{{ end }}>
```

Since this is used just for the class attribute, you could add a class override like this:

```
<body class="{{ block "body_class" . }}{{ end }}">
```

But then you have `<body class="">` on most pages. The issue indicates that you may want to add a body class for most pages anyways, so if this is a preferable approach let me know.

Preview: <https://deploy-preview-31608--twbs-bootstrap.netlify.app/>

TODO:

- [x] Test release-zip-examples just in case

### CODE REVIEW

**Comment by XhmikosR** [comment]
@NotWoods Thanks for the PR. Can you rebase this please?

@regisphilibert could you also have a quick look please?

**Comment by XhmikosR** [comment]
> But then you have `<body class="">` on most pages. The issue indicates that you may want to add a body class for most pages anyways, so if this is a preferable approach let me know.

Indeed, I'd like to always have a body class, but maybe we should tackle that later. My idea was to has a body class automatically generated based on the layout used and page's file path (with slashes and the extension removed).

I think your patch is a good start and can land as is for now :)

**Comment by XhmikosR** [comment]
BTW it seems the example.html is left out.

**Comment by NotWoods** [comment]
I changed it around to use a block for the class, and that can be expanded upon later to generate a class name from the page path. `example.html` is intentionally left out because the layout is unique and doesn't share much with the other pages.

**Comment by XhmikosR** [comment]
> I changed it around to use a block for the class, and that can be expanded upon later to generate a class name from the page path. `example.html` is intentionally left out because the layout is unique and doesn't share much with the other pages.

I'll revert the change since it doesn't make sense to have this unless it's ready.

About examples, I still think we could reuse some of the partials, but I'll leave this to explore later. Like scripts.html and try to generate the placeholder inline CSS from Sass instead of manually hardcoding its output.

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
I'll do a little more testing later and merge this. Thanks for your contribution(s)!

**Comment by XhmikosR** [comment]
@NotWoods can you apply this against my v4-dev-xmr-hugo branch too please? The only difference is the meta viewport tag and the fact that we don't include footer.html in the docs layout.

**Comment by NotWoods** [comment]
#32192

**Pull request merged**
