### PR TITLE
allow to specify the backdrop parent for the modal component

### PR DESCRIPTION
**Pull request by Johann-S**
Hi everybody!
I hope you're doing well, I wish you the best for this new year!

A small PR, to allow to specify the root element for the modal backdrop, it can be useful for users who use Bootstrap with Gatsby for example

Edit: The build failed on something I didn't changed, that's strange 🤔

### CODE REVIEW

**Comment by GeoSot** [comment]
Hello @Johann-S :smiley: 

Can you please help me to understand how can it help Gatsby users? 

We had another PR trying to introduce a modal option, defining `rootParent` and inherit it to backdrop.  I believe this option would be more handy, without exposing backdrop `rootParent` option.  

In case I am right and we provide the modal `rootParent` option, does this PR add any value to functionality?


_Ps: would appreciate your help/response on https://github.com/twbs/bootstrap/pull/34989#issuecomment-979846014_

**Comment by Johann-S** [comment]
Hey :)

Finally after some tests on my project, it's because of purgeCSS remove `.modal-backdrop` added by our JS.
So feel free to close that PR if it's not useful 👌

**Comment by XhmikosR** [comment]
So, do we need this after all?

**Comment by Johann-S** [comment]
Nope I don't think it's useful at all 😆

**Pull request closed without merging**
