### PR TITLE
Docs: Remove mention about Safari's limited support flexbox gap

### PR DESCRIPTION
**Pull request by coliff**
### Description

This callout was added a while ago and Safari has supported this for a while. It's safe to remove now.

### Motivation & Context

Having this callout may cause unnecessary concern.

### Type of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would change existing functionality)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [ ] My code follows the code style of the project _(using `npm run lint`)_
- [ ] My change introduces changes to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

#### Live previews

- https://deploy-preview-40844--twbs-bootstrap.netlify.app/docs/5.3/helpers/stacks/

### CODE REVIEW

**Comment by julien-deramond** [comment]
Unfortunately, according to our [`.browserslistrc`](https://github.com/twbs/bootstrap/blob/main/.browserslistrc), we're still supposed to support Safari 12. Based on the data from https://caniuse.com/flexbox-gap only, flexbox gap is only supported starting from Safari 14, though I haven't manually verified this.

Unless I've overlooked something, we have two options here:
* We label this PR for v6, which aligns with our future update of [`.browserslistrc`](https://github.com/twbs/bootstrap/blob/main/.browserslistrc)
* We close this PR and either mention this decision or cherry-pick your commit in [#37309](https://github.com/twbs/bootstrap/pull/37309) for v6.

**Comment by coliff** [comment]
> Unfortunately, according to our [`.browserslistrc`](https://github.com/twbs/bootstrap/blob/main/.browserslistrc?rgh-link-date=2024-09-18T01%3A44%3A45Z), we're still supposed to support Safari 12. Based on the data from [caniuse.com/flexbox-gap](https://caniuse.com/flexbox-gap) only, flexbox gap is only supported starting from Safari 14, though I haven't manually verified this.
> 
> Unless I've overlooked something, we have two options here:
> 
> * We label this PR for v6, which aligns with our future update of [`.browserslistrc`](https://github.com/twbs/bootstrap/blob/main/.browserslistrc?rgh-link-date=2024-09-18T01%3A44%3A45Z)
> * We close this PR and either mention this decision or cherry-pick your commit in [#37309](https://github.com/twbs/bootstrap/pull/37309) for v6.

I think rewording the callout could be a better option then. Perhaps something like 'Support for gap utilities with flexbox isn't available in Safari prior to 14.5, so consider verifying your intended browser support. Grid layout should have no issues. [Read more](https://caniuse.com/flexbox-gap).'

The main issue I have is that it says "...was **recently** added to Safari"

**Comment by julien-deramond** [comment]
> I think rewording the callout could be a better option then.
> [...]
> The main issue I have is that it currently says "...was recently added to Safari" which is no longer the case.

Great, let's proceed with this option. I'll leave it to you to modify the PR. Once it's updated, I'll review and merge it. Then I'll drop the paragraph entirely in https://github.com/twbs/bootstrap/pull/37309 so we don't forget for v6.

**Review by julien-deramond — APPROVED** [review]
Thanks for the enhancement @coliff 🙏

**Pull request merged**
