### PR TITLE
Fix `<legend>` wrapping bug

### LINKED ISSUE #29712: Flex container doesn't display correctly next to a legend
Since #28917, the `legend` element is no longer rendered with `display: block` but it has `float: left` instead. There is at least an issue when displaying a grid just next to `legend` as it is rendered at the right and not under (see: https://jsfiddle.net/du95trv3/2/). I let you see what is the best way to fix that, normalize.css for example defines `display: table` for `legend`...

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Fixes https://github.com/twbs/bootstrap/issues/29712. Alternative for https://github.com/twbs/bootstrap/pull/29831 which works in Edge.

### CODE REVIEW

**Comment by ysds** [comment]
What is a reason not to use `display: table` like normalize.css?

**Comment by mdo** [comment]
Might be imagining it, but I feel like we ran into an issue with the table approach? Can't remember...

**Comment by MartijnCuppens** [comment]
The reason is ease of theming:
v4: https://codepen.io/MartijnCuppens/pen/vYOdBeo
v5: https://codepen.io/MartijnCuppens/pen/VwLQZWN

**Review by mdo — APPROVED** [review]

**Comment by XhmikosR** [comment]
@MartijnCuppens can you rebase this please?

**Pull request merged**
