### PR TITLE
Accessibility: Minor fixes

### PR DESCRIPTION
**Pull request by louismaximepiton**
### Description

Adding some missing `aria-label` on toggler buttons.
Add an `aria-hidden` to the `<div>` wrapping content outside any `role`/hide an input that doesn't have any `<label>`.

### Motivation & Context

Raises some errors with `aXe devtools`.

### Type of changes

- [x] Refactoring (non-breaking change)

### Checklist

- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
- [x] My code follows the code style of the project _(using `npm run lint`)_
- [x] My change introduces changes to the documentation
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

#### Live previews

- <https://deploy-preview-37616--twbs-bootstrap.netlify.app/>

### Related issues

NA

### CODE REVIEW

**Review by davesheffer — COMMENTED** [review]
All changes where viewed and looked ok

**Review by patrickhlauke — APPROVED** [review]
actually quite concerned that these errors slipped into our docs in the first place. good spot.

**Comment by julien-deramond** [comment]
Hey @louismaximepiton. Could you please resolve the conflicts so that the PR can be merged :)

**Comment by patrickhlauke** [comment]
Fixed the merge conflicts for you @louismaximepiton

**Pull request merged**
