### PR TITLE
v4 - Document migration from panels to cards

### PR DESCRIPTION
**Pull request by kkirsche**
X-Ref: #17120 for `.panel-default` replacement

### CODE REVIEW

**Comment by mdo** [comment]
Not strictly a 1:1 though. Panels were replaced with something similar, but not all those things line up perfectly.

**Comment by kkirsche** [comment]
From a use case perspective they match what the design would be. Not sure I follow what you mean

**Comment by kkirsche** [comment]
X-ref for myself in case this needs to be adjusted based on what @mdo says: #17159

**Comment by mdo** [comment]
For now I'm good with this :).

**Pull request merged**
