### PR TITLE
Meteor integration

### PR DESCRIPTION
**Pull request by dandv**
Hey guys,

This PR lets you publish Bootstrap to Atmosphere, the package repository for [Meteor.js](https://github.com/meteor/meteor). Between Meteor's 21k stars and Bootstrap's 75k, we hope to get even more users to both projects.

I've included the Meteor publishing task in Grunt's `dist` task, and have already [published the current version](https://atmospherejs.com/twbs/bootstrap), so there's nothing to do for now.

Best regards,
Dan & [a bunch of Meteor 3rd party library maintainers](https://github.com/MeteorCommunity/discussions/issues/14)

### CODE REVIEW

**Comment by cvrebert** [comment]
@twbs/team Pinging for more opinions. We should try to come to a decision on this.

**Comment by cvrebert** [comment]
@dandv Based on https://groups.google.com/forum/m/#!topic/meteor-core/DPd6XK4Ow-w , sounds like the Meteor devs are against non-native-Meteor Atmosphere packages, like this would be?

**Comment by dandv** [comment]
@cvrebert The Nov 2014 Google Groups thread is rather old; the current consensus is at https://github.com/percolatestudio/atmosphere/issues/297#issuecomment-67787990. TL;DR - if this PR isn't accepted, it's no big deal; we'll host the integration in the MeteorPackaging repo. Meteor are *for* Meteor integrations on Atmosphere for non-native-Meteor (i.e. 3rd party) packages like Bootstrap.

**Comment by mdo** [comment]
I think I'm a pass on this unfortunately. It's not something most of us on the Bootstrap team use at this time and as we're trying to keep things super lightweight on our end (especially as we head into v4), this would be a bit of a step in the opposite direction. I understand the usefulness though, and deeply appreciate your level of commitment to this effort. That goes a long way in my book :).

Let us know how we can help put some attention from others on this. We have the Expo resources page, but if this is a separate package, feel free to ask for a tweet or two about this down the line.

<3

**Pull request closed without merging**
